cube-js/cube

packages/cubejs-client-core/babel.config.js, packages/cubejs-client-core/package.json, packages/cubejs-client-core/src/ResultSet.js, packages/cubejs-client-core/src/ResultSet.test.js, packages/cubejs-client-core/yarn.lock
Fix `ResultSet.timeSeries` for granularity hour.
=> ResultSet timeseries fix

README.md
How to embed Cubejs in an Express application.
=> API documentation for CubejsServerCore.create(options)

README.md, packages/cubejs-cli/cubejsCli.js, packages/cubejs-cli/templates.js
Added `dotEnv` template for `mongo-bi` to `cli` package.
=> chore(cli): add dotEnv template for mongobi

packages/cubejs-react/package.json, packages/cubejs-react/yarn.lock
adds core-js dependency to cubejs-react package
=> fix(cubejs-react): add core-js dependency

packages/cubejs-cli/cubejsCli.js, packages/cubejs-cli/package.json, packages/cubejs-cli/token.js, packages/cubejs-cli/yarn.lock
Generate JWT tokens via cubejs-cli!
=> feat(cubejs-cli): add token generation

packages/cubejs-jdbc-driver/driver/JDBCDriver.js
This will allow cubejs to connect directly to
SparkSQL and Hive datastores running big
data queries.
=> feat: Added SparkSQL and Hive support to the JDBC driver.

packages/cubejs-schema-compiler/scaffolding/ScaffoldingSchema.js, packages/cubejs-schema-compiler/test/ScaffoldingSchemaTest.js
Fix to discard the Foreign Reference Columns from inclusion in the measures while generating the schema
=> Fix to discard the FR Columns from inclusion in the measures

docs/Cube.js-Backend/Connecting-to-the-Database.md
dbtype for presto  should be `prestodb` not `presto`
=> dbtype should be prestodb not presto

packages/cubejs-api-gateway/package.json, packages/cubejs-schema-compiler/package.json
joi has been moved to @hapi/joi
=> Moved joi dependency to it's new availability

packages/cubejs-server-core/core/index.d.ts
**Check List**
#96
Add typing for new parameter `preAggregationsSchema`
=> Add typing

packages/cubejs-playground/src/libraries/bizChart.js
It will error in "TypeError: Reduce of empty array with no initial value" if result is empty array.
=> fix empty array error

docs/Schema/active-users.md
This is only fixing a small typo in the docs
=> Just fixed a small typo

packages/cubejs-playground/src/scaffolding/react/components/Dashboard.js, packages/cubejs-playground/src/scaffolding/react/components/DashboardItem.js, packages/cubejs-playground/src/scaffolding/react/components/TitleModal.js, packages/cubejs-playground/src/scaffolding/react/pages/DashboardPage.js, packages/cubejs-playground/src/scaffolding/react/pages/ExplorePage.js
=> Scaffolding Updates React

packages/cubejs-server-core/core/FileRepository.js, packages/cubejs-server-core/yarn.lock
=> Read schema subfolders

docs/Guides/Code-Reusability-Schema-Generation.md
**Check List**
n.a
Updated the schema generation docs to improve readability
=> docs: improved readability of dynamic schema generation

docs/Schema/dimensions.md, packages/cubejs-schema-compiler/adapter/BaseQuery.js, packages/cubejs-schema-compiler/compiler/CubeValidator.js, packages/cubejs-schema-compiler/test/ClickHouseDataSchemaCompilerTest.js, packages/cubejs-schema-compiler/test/DataSchemaCompilerTest.js
**Check List**
https://github.com/cube-js/cube.js/issues/235
label is run through the execute sql function
=> feat: dynamic case label

docs/Cube.js-Frontend/@cubejs-client-core.md, packages/cubejs-client-core/src/HttpTransport.js, packages/cubejs-client-core/src/index.js
**Check List**
https://github.com/cube-js/cube.js/issues/241
CubejsApi takes `headers` argument in `options` that passes through to the `HttpTransport`
=> client headers for CubejsApi

packages/cubejs-server-core/core/index.js
=> pretty default logger

docs/Schema/pre-aggregations.md
**Check List**
Some findings on preaggregations that were not fully documented
=> preaggregations docs updates

packages/cubejs-postgres-driver/driver/PostgresDriver.js, packages/cubejs-postgres-driver/package.json, packages/cubejs-postgres-driver/yarn.lock
**Check List**
https://github.com/cube-js/cube.js/issues/265
=> fix: Fix postgres driver timestamp parsing by using pg per-query type parser

docs/Schema/cube.md, docs/Schema/pre-aggregations.md
**Check List**
None
Docs updates
=> Documentation - fix link, fix measures, add segment partitioning

packages/cubejs-query-orchestrator/orchestrator/PreAggregations.js
**Check List**
n/a
n/a
Fixing typo
=> Fix this.versionEntries typo

packages/cubejs-cli/cubejsCli.js
**Check List**
None
Update db list in cubejs cli based on document.
=> update list of supported db based on document

packages/cubejs-schema-compiler/compiler/CubeValidator.js
**Check List**
None
Noticed this issue where BasePreAggregation would get updated
=> fix cube validation from updating BasePreAggregation

packages/cubejs-playground/package.json, packages/cubejs-playground/src/ChartRenderer.js, packages/cubejs-playground/src/libraries/d3.js, packages/cubejs-playground/yarn.lock
=> D3 charts in playground

docs/Schema/Getting-Started-with-Cube.js-Schema.md
=> Fixed typo. Changed Avito to Aviato

packages/cubejs-client-core/src/ResultSet.js
Add `resultSet.series` to the docs as well.
=> feat: Return key in the resultSet.series alongside title

packages/cubejs-client-core/dist/index.d.ts, packages/cubejs-client-core/package.json
**Check List**
Added Typescript types for the `@cubejs-client/core` package. They're not perfect, but that can always be improved in a followup PR 👍
=> feat(@cubejs-client/core): add types

docs/Cube.js-Backend/@cubejs-backend-server-core.md, docs/Cube.js-Backend/@cubejs-backend-server.md, packages/cubejs-server-core/core/index.d.ts, packages/cubejs-server/index.d.ts, packages/cubejs-server/package.json
Added some more typescript definitions and added some examples in documentation for creating healthchecks and creating your own `FileRepository`.
=> docs for healthchecks and filerepository

packages/cubejs-api-gateway/index.js, packages/cubejs-query-orchestrator/orchestrator/PreAggregations.js, packages/cubejs-query-orchestrator/orchestrator/QueryOrchestrator.js
=> Update logger events

packages/cubejs-api-gateway/SubscriptionServer.js
=> fix: define context outside try-catch

packages/cubejs-playground/src/TemplateGallery/TemplateGalleryPage.js, packages/cubejs-server-core/dev/templates/packages/d3-charts/scaffolding/src/components/ChartRenderer.js, packages/cubejs-server-core/dev/templates/packages/react-material-static/scaffolding/src/components/ChartRenderer.js, packages/cubejs-server-core/dev/templates/packages/react-material-static/scaffolding/src/pages/DashboardPage.js
=> Update d3 scaffolding

packages/cubejs-server-core/core/index.d.ts
**Check List**
Fixed CreateOptions interface where queryTransformer had a typo
=> Fix typo on createOptions queryTransformer

packages/cubejs-client-core/dist/index.d.ts
**Check List**
Fixes #350
Loosened types as appropriate.
=> fix(@cubejs-client/core): improve types

packages/cubejs-server-core/core/index.d.ts
Fix Typescript definitions to match the current API of CubejsServerCore.
=> Fix typescript type definition

packages/cubejs-bigquery-driver/driver/index.d.ts, packages/cubejs-bigquery-driver/package.json, packages/cubejs-postgres-driver/driver/index.d.ts, packages/cubejs-postgres-driver/package.json, packages/cubejs-server-core/core/index.d.ts, packages/cubejs-sqlite-driver/driver/index.d.ts, packages/cubejs-sqlite-driver/package.json
* Improve core typings
* Add biquery-driver typings
* Add sqlite-driver typings
* Add postgres-driver typings
=> Add more Typings

.circleci/config.yml, packages/cubejs-oracle-driver/package.json, packages/cubejs-oracle-driver/yarn.lock
**Check List**
Bump oracle driver so that it supports node 12.x better
=> Bump oracle deps

docs/Cube.js-Backend/REST-API.md, packages/cubejs-schema-compiler/compiler/CubeToMetaTransformer.js
=> feat: Extend meta response with aggregation type

packages/cubejs-cli/templates.js
**Check List**
#402 
- Added `const gitIgnore` to templates.js with `.env` as content
- Added `.gitignore` to all exports
Let me know if I'm missing something as I'm not too familiar with the codebase, but this seems to be the only file that should be changed.
=> feat: Add .gitignore with .env content to templates.js

packages/cubejs-api-gateway/index.js, packages/cubejs-api-gateway/requestParser.js, packages/cubejs-server-core/core/index.js
**Check List**
Uses middleware technique to add logging of API Gateway requests using generic logger.
- Default prod log level changed from info to warn (there was nothing logged at info, so no apparent change here)
- Put 1-line per-request logging at info level, this means you'll need to set `CUBEJS_LOG_LEVEL=info` to see it
=> feat: Add API gateway request logging support

packages/cubejs-client-core/dist/index.d.ts
**Check List**
No issue previously existed.
The `progressCallback` type was incorrectly marked as required, it is now changed be to optional.
=> fix(@cubejs-client/core): make `progressCallback` optional

CONTRIBUTING.md
**Check List**
I don't like typing folder names :) This makes it a one-click setup for the development environment, just copy/paste in your CLI.
=> Update CONTRIBUTING.md to include one-click setup

docs/Examples.md
Noticed a bad path for the react dashboard code example. Corrected it.
Will take care of this 404 error [https://cube.dev/docs/guides/react-dashboard]
=> Updated Examples.md

docs/Cube.js-Backend/Connecting-to-the-Database.md, packages/cubejs-postgres-driver/driver/PostgresDriver.js
**Check List**
[fixes #579]
Copied over SSL code from MongoBI Driver. Assumed CUBEJS_DB_SSL_CA will be a filename. Updated the docs with this info.
=> Allow usage of CUBEJS_DB_SSL_CA parameter in postgres Driver.

docs/Cube.js-Frontend/@cubejs-client-core.md, packages/cubejs-client-core/src/ResultSet.js, packages/cubejs-client-core/src/ResultSet.test.js
=> Including format and type in tableColumns

docs/Cube.js-Backend/@cubejs-backend-server-core.md, packages/cubejs-server/WebSocketServer.js
**Check List**
[fixes #583 ]
Added a new parameter websocketsBasePath to the config and passed this in as `path` during the creation of the WebsocketServer
=> Added support for websocketsBasePath

docs/Cube.js-Backend/Security.md
**Check List**
no known existing issue
just a quick note in the docs to help others who might run into the same little issue i had :)
=> add note about type restriction for jwt payload

packages/cubejs-server-core/core/index.d.ts, packages/cubejs-server/index.d.ts
Core server create options should be optional.  Added missing options parameter for CubejsServer.
=> feat: Update server type definitions

packages/cubejs-client-react/src/useCubeQuery.js, packages/cubejs-client-react/src/useDeepCompareMemoize.js
**Check List**
Any change to `options` param passed to `useCubeQuery` will be considered immediately
=> fix: options dependency for useEffect

docs/Cube.js-Frontend/Query-Format.md
Thank you so much for creating this framework! 
There are a number of grammar mistakes in the docs, and I thought I might take some time to try and fix them so they read a bit better for native English speakers. Let me know your thoughts. I can also do some other pages too when I have time.
**Check List**
=> Fixed Grammar on the Query Format Page

packages/cubejs-client-vue/dist/cubejs-client-vue.esm.js, packages/cubejs-client-vue/dist/cubejs-client-vue.js, packages/cubejs-client-vue/dist/cubejs-client-vue.umd.js, packages/cubejs-client-vue/src/QueryBuilder.js
**Check List**
https://github.com/cube-js/cube.js/issues/635
chartType fix
=> fix(client-vue): updateChartType fix

packages/cubejs-postgres-driver/package.json, packages/cubejs-postgres-driver/yarn.lock
=> fix(cubejs-postgres-driver): updated pg version

packages/cubejs-client-core/dist/cubejs-client-core.umd.js, packages/cubejs-playground/src/SchemaPage.js, packages/cubejs-playground/src/index.less
=> fix(cubejs-playground): dashboard style fixes

docs/Getting-started.md
**Check List**
In the Getting Started documentation, in the Vue.js part there is a small unused component error. Instead of **QueryBuilder** the correct thing is to use **QueryRenderer**
=> fix/QueryRenderer in vue.js

packages/cubejs-sqlite-driver/driver/SqliteDriver.js
Resolves #626 
* Fixed regex to extract field names and types
* Added condition to ignore `sqlite_sequence` table created for maintaining autoincrement index in `informationSchemaQuery`
=> Fix sqlite name and type extraction

packages/cubejs-server-core/dev/templates/AppContainer.js
#661 
Downgraded `graphql-tools` version
=> fix(playground): graphql-tools version downgrade

packages/cubejs-schema-compiler/adapter/AWSElasticSearchQuery.js
**Check List**
[For example #683]
=> respect ungrouped parameter

docs/Schema/cube.md
Added warning to the description of SQL_UTILS.convertTz() as suggested in issue #689
**Check List**
=> docs(cube): added warning to convertTz

packages/cubejs-cli/deploy.js
=> fix(cubejs-cli): eslint fixes

docs/Cube.js-Frontend/@cubejs-client-react.md, packages/cubejs-client-core/src/ResultSet.js, packages/cubejs-client-core/src/index.js
drillDown, QueryBuilder order docs
=> docs: drillDown, QueryBuilder order

guides/react-dashboard/content/2_authentication_and_graphql_backend.md
=> Single typo fix

docs/Cube.js-Introduction.md, guides/web-analytics/content/1_overview.md
**Check List**
Not a code change, so the checklist is not relevant.
No issue.
Fixed a couple of typos in docs and guides.
=> docs: fix typos

docs/Cube.js-Frontend/@cubejs-client-react.md
=> docs(cubejs-client-react): updateOrder example

docs-gen/template/publish.js, packages/cubejs-client-core/src/HttpTransport.js, packages/cubejs-client-core/src/ResultSet.js
updated docs, typeDefs presentation fix
=> docs(cubejs-client-core): updated docs

docs-gen/template/publish.js
=> fix: header

docs-gen/template/publish.js, docs/Schema/dimensions.md, packages/cubejs-client-core/src/ResultSet.js
=> docs(cubejs-client-core): updates

packages/cubejs-client-core/dist/cubejs-client-core.esm.js, packages/cubejs-client-core/dist/cubejs-client-core.js, packages/cubejs-client-core/dist/cubejs-client-core.umd.js, packages/cubejs-client-core/src/ResultSet.js, packages/cubejs-client-core/src/tests/table.test.js
=> fix(cubejs-client-core): tableColumns empty data fix

packages/cubejs-playground/src/components/Order/DraggableItem.js, packages/cubejs-playground/src/components/Pivot/Item.js, packages/cubejs-server-core/dev/templates/packages/react-antd-dynamic/scaffolding/src/components/QueryBuilder/Order/DraggableItem.js, packages/cubejs-server-core/dev/templates/packages/react-antd-dynamic/scaffolding/src/components/QueryBuilder/Pivot/Item.js
=> fix(cubejs-playground): Long line ellipsis

packages/cubejs-schema-compiler/adapter/BaseQuery.js
**Check List**
[For example #759 ]
=> include * as part of RE to support elasticsearch indexes

docs-gen/src/resources/helpers/if-parent-kind-is.ts, docs-gen/src/resources/helpers/member-title.ts, docs-gen/src/resources/helpers/meta.ts, docs-gen/src/resources/partials/member.hbs, packages/cubejs-client-core/index.d.ts
=> fix(docs-gen): titles

docs-gen/src/resources/helpers/declaration-title.ts, docs/Cube.js-Frontend/@cubejs-client-core.md, docs/Cube.js-Frontend/@cubejs-client-react.md
=> fix(docs-gen): declaration

docs/Cube.js-Frontend/@cubejs-client-core.md, packages/cubejs-client-core/index.d.ts
#807 
enums exported from declaration files are not accessible
=> fix(cubejs-client-core): enums exported from declaration files are not accessible

packages/cubejs-client-vue/dist/cubejs-client-vue.umd.js, packages/cubejs-client-vue/src/QueryBuilder.js
=> fix(cubejs-client-vue): added deep watch at query props object in Vue QueryBuilder

packages/cubejs-client-vue/dist/cubejs-client-vue.esm.js, packages/cubejs-client-vue/dist/cubejs-client-vue.js, packages/cubejs-client-vue/dist/cubejs-client-vue.umd.js, packages/cubejs-client-vue/src/QueryBuilder.js
=> fix: filter out falsy members

docs/Cube.js-Frontend/@cubejs-client-core.md, packages/cubejs-client-core/dist/cubejs-client-core.esm.js, packages/cubejs-client-core/dist/cubejs-client-core.js, packages/cubejs-client-core/dist/cubejs-client-core.umd.js, packages/cubejs-client-core/index.d.ts, packages/cubejs-client-core/src/ResultSet.js, packages/cubejs-client-react/dist/cubejs-client-react.umd.js, packages/cubejs-client-vue/dist/cubejs-client-vue.esm.js, packages/cubejs-client-vue/dist/cubejs-client-vue.js, packages/cubejs-client-vue/dist/cubejs-client-vue.umd.js
=> feat: ResultSet serializaion and deserializaion

packages/cubejs-client-core/src/ResultSet.js, packages/cubejs-client-core/src/tests/ResultSet.test.js
=> fix: preserve order of sorted data

packages/cubejs-client-core/index.d.ts, packages/cubejs-client-core/src/ResultSet.js
=> feat: expose loadResponse annotation

docs/Cube.js-Backend/Connecting-to-the-Database.md, docs/Schema/pre-aggregations.md
Hey @paveltiunov and @jkotova,
It would be great if you have a minute to check these changes to the docs as, I believe, we need them for our lovely July Newsletter. Thanks in advance!
=> docs: A few additions for the July newsletter

packages/cubejs-client-react/index.d.ts
**Check List**
-- well an example comment anyways
fixes https://github.com/cube-js/cube.js/issues/912
add export of CubeContext type to index.d.ts
usage example comment
=> fix: CubeContext ts type missing

docs/Cube.js-Frontend/@cubejs-client-core.md, docs/Cube.js-Frontend/@cubejs-client-react.md, packages/cubejs-client-core/index.d.ts, packages/cubejs-client-core/src/Meta.js, packages/cubejs-client-core/src/index.js, packages/cubejs-client-react/index.d.ts
=> fix: membersForQuery return type

docs/Schema/Funnels.md
I spotted that this page could do with some tidying up for grammar. Hope this is helpful!
**Check List**
Documentation only.
Updates the Funnels documentation page to improve grammar and readability.
=> docs: Funnels.md language improvements

packages/cubejs-server-core/dev/templates/packages/bizcharts-charts/scaffolding/src/components/ChartRenderer.js
=> fix: bizcharts incorrect geom type

docs/Cube.js-Backend/Security.md
Hi folks, I'm in the process of setting up Cube.js for my project and found some of the language on the Security docs page could be improved for readability and to make it easier to understand as a new user.
**Check List**
Documentation only.
Updates the Security.md documentation for grammar and readability.
=> Security.md language amendments

docs/Cube.js-Backend/@cubejs-backend-server.md
=> docs: add docs for `CubejsServer` specific options

guides/guides-base/package.json, guides/guides-base/yarn.lock, guides/react-dashboard/package.json, guides/react-dashboard/yarn.lock
=> Guides: update cubedev-tracking package to 1.0.1

docs/Cube.js-Backend/@cubejs-backend-server-core.md
fix syntax error in example
**Check List**
There was a syntax error in the example
=> docs: Fix syntax error

packages/cubejs-mssql-driver/driver/MSSqlDriver.js, packages/cubejs-schema-compiler/adapter/MssqlQuery.js, packages/cubejs-schema-compiler/test/MSSqlPreAggregationsTest.js
Updating MSSqlDriver to implement downloadQueryResults function, enabling ability to have source systems use pre-aggregation where readOnly is true and externalDb utilized.
=> feat(mssql-driver): add readonly aggregation for mssql sources

docs/Cube.js-Backend/REST-API.md, packages/cubejs-api-gateway/index.js, packages/cubejs-api-gateway/index.test.js, packages/cubejs-api-gateway/package.json, packages/cubejs-api-gateway/yarn.lock
**Check List**
[Allow HTTP POST for query #723]
=> Add support http method POST for route /v1/load

docs/Cube.js-Frontend/@cubejs-client-vue.md
=> Docs: Vue query builder change sandbox link to new version api

packages/cubejs-client-core/index.d.ts
**Check List**
- [ x ] Tests has been run in packages where changes made if available
- [ x ] Linter has been run for changed code
- [ x ] Tests for the changes have been added if not covered yet
- [ x ] Docs have been added / updated if required
none
Now the type more accurately represents which Filter objects are valid.
This will provide better code completion, documentation and allow the
typechecker to better help in writing more robust new code and in more
easily refactoring existing code.
This is just encoding existing docs in the type system, so no docs are
needed. This also does not add or change any existing behavior, so
tests are not needed.
This has the potential to cause …
=> feat: Make the Filter type more specific.

README.md, docs/Examples.md, guides/react-dashboard/content/1_overview_and_analytics_backend.md, guides/react-dashboard/content/8_deployment.md, guides/react-dashboard/src/components/Hero/Hero.jsx
=> Guides: React-dashboard guide. Change to new link and remove old

README.md, docs/Examples.md, examples/external-rollups/README.md, guides/d3-dashboard/README.md, guides/d3-dashboard/src/pages/index.jsx, guides/web-analytics/README.md
=> Docs, Guides, Examples: Change old links to cubecloud

examples/web-analytics/dashboard-app/package.json, examples/web-analytics/dashboard-app/yarn.lock
=> Examples: web-analytics-demo update cubejs-react package

docs/Cube.js-Backend/Connecting-to-the-Database.md
=> Docs: add links to google BigQuery credentials setup

CONTRIBUTING.md
CubeJS Cli package is published as cubejs-cli package. NPX example is more useful for new users.
**Check List**
=> docs: Use npx for cubejs-cli

packages/cubejs-api-gateway/.eslintrc.js, packages/cubejs-api-gateway/index.js, packages/cubejs-api-gateway/index.test.js, packages/cubejs-client-core/src/HttpTransport.js, packages/cubejs-client-core/src/ResultSet.js, packages/cubejs-client-core/src/index.js, packages/cubejs-client-core/src/tests/compare-date-range.test.js, packages/cubejs-client-core/src/tests/data-blending.test.js, packages/cubejs-client-react/src/QueryBuilder.jsx
=> feat: data blending

packages/cubejs-api-gateway/index.js, packages/cubejs-api-gateway/package.json, packages/cubejs-schema-compiler/adapter/BaseDimension.js, packages/cubejs-schema-compiler/adapter/BaseGroupFilter.js, packages/cubejs-schema-compiler/adapter/BaseMeasure.js, packages/cubejs-schema-compiler/adapter/BaseQuery.js, packages/cubejs-schema-compiler/adapter/BaseSegment.js, packages/cubejs-schema-compiler/adapter/QueryCache.js, packages/cubejs-schema-compiler/compiler/UserError.js, packages/cubejs-schema-compiler/test/SQLGenerationLogicTest.js, packages/cubejs-schema-compiler/test/SQLGenerationTest.js
=> Complex boolean logic

packages/cubejs-dremio-driver/driver/DremioQuery.js
=> replace CAST to TO_TIMESTAMP

docs/Cube.js-Backend/Caching.md
=> docs: Add inspecting queries to the docs

docs-gen/src/resources/helpers/member-symbol.ts, docs/Cube.js-Frontend/@cubejs-client-core.md
**Check List**
Change the signature generation:
Use `>` instead of `▸`
=> fix(docs-gen): change signature generation

docs-gen/src/resources/helpers/member-symbol.ts, docs/Cube.js-Frontend/@cubejs-client-core.md, docs/Cube.js-Frontend/@cubejs-client-react.md
**Check List**
Fix all signature conversions.
=> Typedoc gen signature fix

examples/compare-date-range/README.md
=> examples__comparedaterange updated

docs/Schema/pre-aggregations.md
**Check List** 
#1037
Improve docs
=> Original SQL with incremental refreshKey

docs/Cube.js-Backend/Deployment.md
=> Docs for deployment Serverless Google Cloud Platform

packages/cubejs-athena-driver/driver/AthenaDriver.js, packages/cubejs-athena-driver/package.json
**Check List**
Athena Driver does not access views via the informationSchemaQuery #1083
=> fix(@cubejs-backend/athena-driver): Show views in Playground for Athena

docs/Cube.js-Backend/Query-Format.md
=> docs for Boolean logical operators

packages/cubejs-schema-compiler/adapter/BaseGroupFilter.js, packages/cubejs-schema-compiler/adapter/BaseQuery.js, packages/cubejs-schema-compiler/test/SQLGenerationLogicTest.js
**Check List**
Bugfix: allow filters without arguments.
=> Bugfix: allow filters without arguments.

packages/cubejs-server-core/core/index.js
=> Feature: Share Node's version for debug purposes

packages/cubejs-server-core/core/index.test.js, packages/cubejs-server-core/core/optionsValidate.js
**Check List**
CubejsServerCore Options Validation Breaks Serverless Deployments #1110
=> fix(@cubejs-backend/server-core): orchestratorOptions validation breaks serverless deployments

.circleci/config.yml, .github/workflows/push.yml
=> Feature(ci): Move lint to GitHub actions (more stable then CircleCI)

.github/workflows/push.yml, packages/cubejs-prestodb-driver/config/catalog/postgresql.properties, packages/cubejs-prestodb-driver/docker-compose.yml, packages/cubejs-prestodb-driver/package.json, packages/cubejs-prestodb-driver/test/PrestoDriverTest.js, packages/cubejs-prestodb-driver/yarn.lock
**Check List**
I am going to prepare test base for PrestoDB, before fixing https://github.com/cube-js/cube.js/issues/988
=> Feature(@cubejs-backend/prestodb-driver): Introduce integration tests

packages/cubejs-server-core/core/index.test.js, packages/cubejs-server-core/core/optionsValidate.js
=> Fix(@cubejs-backend/server-core): Allow processSubscriptionsInterval

packages/cubejs-server-core/core/index.test.js, packages/cubejs-server-core/core/optionsValidate.js
=> fix: rollupOnlyMode option validation

packages/cubejs-client-core/src/ResultSet.js
=> fix: drilling into any measure other than the first

packages/cubejs-server-core/core/index.test.js, packages/cubejs-server-core/core/optionsValidate.js
=> Fix(@cubejs-backend/server-core): Support apiSecret

lerna.json
=> Use yarn as default client for lerna

packages/cubejs-schema-compiler/adapter/PrestodbQuery.js, packages/cubejs-schema-compiler/test/integration/postgres/SQLGenerationLogicTest.js, packages/cubejs-schema-compiler/test/integration/postgres/SQLGenerationTest.js
**Check List**
Resolve https://github.com/cube-js/cube.js/issues/988
=> Fix #988 PrestoDB wrong OFFSET/LIMIT order

packages/cubejs-server-core/core/CompilerApi.js, packages/cubejs-server-core/core/DevServer.js, packages/cubejs-server-core/core/FileRepository.js, packages/cubejs-server-core/core/OrchestratorApi.js, packages/cubejs-server-core/core/index.js, packages/cubejs-server-core/dev/DependencyTree.js, packages/cubejs-server-core/package.json
=> Misc: Run lint on server-core/dev directory

packages/cubejs-server-core/dev/PackageFetcher.js, packages/cubejs-server-core/dev/utils.js, packages/cubejs-server-core/package.json, packages/cubejs-server-core/yarn.lock
=> fix: respect npm proxy settings

docs/Cube.js-Frontend/@cubejs-client-core.md, docs/Cube.js-Frontend/@cubejs-client-react.md, docs/Cube.js-Frontend/Real-Time-Data-Fetch.md, packages/cubejs-client-core/index.d.ts, packages/cubejs-client-react/index.d.ts
=> docs: subscribe method description

docs/Cube.js-Backend/REST-API.md
=> Add docs for connectedComponent

docs/Cube.js-Backend/Connecting-to-the-Database.md, packages/cubejs-mysql-driver/driver/MySqlDriver.js, packages/cubejs-mysql-driver/driver/index.d.ts, packages/cubejs-mysql-driver/package.json, packages/cubejs-mysql-driver/yarn.lock, packages/cubejs-postgres-driver/driver/PostgresDriver.js
=> Fix(mysql-driver): Support environment variables for SSL and unix socket

packages/cubejs-server-core/core/index.d.ts
Hello!
My miss while I was implementing the driver.
Thanks
=> Fix(server-core): Add druid to DatabaseType

packages/cubejs-server/__mocks__/http.js, packages/cubejs-server/__mocks__/https.js, packages/cubejs-server/index.js, packages/cubejs-server/index.test.js, packages/cubejs-server/package.json
=> Misc(@cubejs-backend/server): Use linter

packages/cubejs-client-react/index.d.ts
=> fix(@cubejs-client/react): resultSet ts in for QueryBuilderRenderProps

packages/cubejs-client-react/index.d.ts
=> fix(@cubejs-client/react): Duplicate props for type QueryBuilderRenderProps

.github/workflows/publish-docker.yml
=> misc(ci): Automatic docker publish workflow

packages/cubejs-playground/src/components/Settings/Settings.js
PR fixes messed up popovers of settings in Playground.
=> Playground: Fix messed up popovers.

.github/workflows/publish.yml
=> misc(ci): Support tmp tags for testing releases

packages/cubejs-client-core/index.d.ts
**Check List**
Resolves the issue of boolean filters not existing on client-core typings (not in issues) - #259 
Added typings for "and" and "or" logic on binary and unary filters
=> Added boolean filters to Filter typings

docs/Cube.js-ClI/Reference.md, packages/cubejs-cli/cubejsCli.js, packages/cubejs-cli/token.js
**Check List**
#206 
Adds ability to add USER_CONTEXT via CLI
=> FEAT: Adds ability to add USER_CONTEXT via CLI

packages/cubejs-client-core/index.d.ts, packages/cubejs-client-core/src/index.js, packages/cubejs-client-core/src/utils.js, packages/cubejs-client-react/src/QueryBuilder.jsx, packages/cubejs-playground/src/ChartRenderer.js, packages/cubejs-playground/src/PlaygroundQueryBuilder.js, packages/cubejs-playground/src/components/Settings/Settings.js
=> fix(@cubejs-playground): avoid unnecessary load calls, dryRun

packages/cubejs-cli/package.json, packages/cubejs-cli/src/cli.js, packages/cubejs-cli/src/command/deploy.js, packages/cubejs-cli/src/command/deploy.ts, packages/cubejs-cli/src/command/proxy-command.ts, packages/cubejs-cli/src/config.js, packages/cubejs-cli/src/deploy.js, packages/cubejs-cli/src/index.ts, packages/cubejs-cli/src/token.js, packages/cubejs-cli/src/utils.ts, packages/cubejs-cli/tsconfig.json, packages/cubejs-cli/yarn.lock
=> fix(cubejs-cli): deploy command

.github/workflows/push.yml
=> misc(ci): Dont run docker-image-latest on tag

.github/workflows/push.yml
=> misc(ci): Run unit tests under Node.js 15

packages/cubejs-client-core/src/ResultSet.js
=> Duplicates names in ResultSet.seriesNames()

packages/cubejs-cli/src/config.js
=> fix URL to cube cloud service

README.md
=> Add monthly community call info

packages/cubejs-elasticsearch-driver/README.md
=> Add the support section in readme file

packages/cubejs-cli/src/cli.js, packages/cubejs-cli/src/command/create.ts, packages/cubejs-cli/src/command/generate.ts, packages/cubejs-cli/src/index.ts, packages/cubejs-cli/src/templates.test.js, packages/cubejs-cli/src/templates.ts, packages/cubejs-server/bin/dev-server.js
Hello!
After https://github.com/cube-js/cube.js/pull/1227
Refs https://github.com/cube-js/cube.js/issues/1167
Thanks
=> Feature: Introduce Docker template

packages/cubejs-cli/package.json, packages/cubejs-cli/src/command/create.ts, packages/cubejs-cli/src/index.ts, packages/cubejs-cli/yarn.lock, packages/cubejs-server/index.js, packages/cubejs-server/package.json
=> Cubejs cli fixes

packages/cubejs-cli/src/templates.ts, packages/cubejs-server/package.json
=>  fix(@cubejs-backend/server): Allow any version of cubejs higher 0.22

.github/workflows/master.yml, .github/workflows/publish.yml, .github/workflows/push.yml
=> misc(ci): Improve names for jobs/workflows on CI

packages/cubejs-cli/src/templates.ts, packages/cubejs-docker/dev.Dockerfile, packages/cubejs-docker/latest.Dockerfile, packages/cubejs-server-core/dev/PackageFetcher.js
=> Feature: Improve docker DX

.github/workflows/master.yml, packages/cubejs-docker/DEVELOPMENT.md, packages/cubejs-docker/README.md
=> misc(ci): Update a Docker Hub repository description

packages/cubejs-schema-compiler/adapter/BaseQuery.js
=> fix(@cubejs-backend/schema-compiler): deprecation warning

packages/cubejs-cli/src/command/deploy.ts
=> Cube.js deploy single command

.github/workflows/publish.yml, .github/workflows/push.yml, packages/cubejs-jdbc-driver/package.json, packages/cubejs-jdbc-driver/yarn.lock
Hello!
refs https://github.com/cube-js/cube.js/issues/1280
Thanks
=> feat(@cubejs-backend/jdbc-driver): Upgrade vendors

rollup.config.js
=> misc(rollup): Generate source maps for client libraries

packages/cubejs-cli/src/command/proxy-command.ts
=> fix(cubejs-cli): proxyCommand - await external command run on try/catch

packages/cubejs-server-core/package.json, packages/cubejs-server-core/yarn.lock, packages/cubejs-server/package.json, packages/cubejs-server/yarn.lock
=> fix: Warnings on installation

packages/cubejs-cli/src/command/generate.ts
=> fix(cubejs-cli): scaffolding/ScaffoldingTemplate dependency not found.

packages/cubejs-docker/dev.Dockerfile, packages/cubejs-docker/latest.Dockerfile
=> misc(docker): Disable --frozen-lockfile (temporary)

packages/cubejs-server/package.json, packages/cubejs-server/src/command/dev-server.ts, packages/cubejs-server/src/command/server.ts, packages/cubejs-server/src/server/container.ts, packages/cubejs-server/yarn.lock
=> feat(@cubejs-backend/server): dev-server/server - introduce project diagnostics

docs/Cube.js-Backend/Environment-Variables-Reference.md
=> Document all environment variables

packages/cubejs-client-core/index.d.ts, packages/cubejs-client-core/src/index.js, packages/cubejs-client-core/src/utils.js, packages/cubejs-client-react/src/QueryBuilder.jsx
=> fix(@cubejs-playground): boolean filters support

packages/cubejs-cubestore-driver/driver/CubeStoreDriver.js, packages/cubejs-mongobi-driver/driver/MongoBIDriver.js, packages/cubejs-mssql-driver/driver/MSSqlDriver.js, packages/cubejs-mysql-driver/driver/MySqlDriver.js, packages/cubejs-postgres-driver/driver/PostgresDriver.js
Hello!
refs https://github.com/cube-js/cube.js/issues/1212
Thanks
=> fix: CUBEJS_DB_SSL must be true to affect SSL, fix #1212

docs/Examples.md
**Check List**
Fixes #1273, #1344
=> Update and remove invalid links

docs/Cube.js-Backend/Deployment.md
=> docs: Add Enable HTTPS to Deployment

docs/Cube.js-Backend/Deployment.md
=> misc(docs): Update deployment guide for Heroku (docker way)

packages/cubejs-cli/src/command/create.ts, packages/cubejs-cli/src/templates.test.js, packages/cubejs-cli/src/templates.ts, packages/cubejs-cli/src/track.ts
=> feat(cubejs-cli): create - persist template name & version

guides/real-time-dashboard/content/3_frontend_dashboard.md
=> misc(guides/real-time-dashboard): Use configure by cube.js

packages/cubejs-cli/src/config.ts
=> cli: remove selection when we have only one option

docs/Cube.js-Backend/Security.md
**Check List**
Removed a stray reference to TLS encryption.
=> Remove reference to TLS encryption

packages/cubejs-server-core/package.json, packages/cubejs-server-core/yarn.lock
Hello!
Yet another issue comes from oclif, refs https://github.com/oclif/errors/issues/97
Thanks.
=> Node 8 support

packages/cubejs-cli/src/templates.ts, packages/cubejs-server-core/core/DevServer.js
=> feat(cubejs-cli): Share /dashboard-app directory by default

packages/cubejs-cli/src/command/generate.ts, packages/cubejs-cli/src/command/proxy-command.ts, packages/cubejs-cli/src/command/token.ts, packages/cubejs-cli/src/utils.ts
=> fix(cubejs-cli): Generate/token should work inside docker

packages/cubejs-mysql-aurora-serverless-driver/README.md
=> Add the community support section

packages/cubejs-client-core/src/ResultSet.js, packages/cubejs-client-core/src/tests/drill-down.test.js
=> fix: pivot should work well with null values

docs/Deployment/Deployment-Guide.md
**Check List**
Fixes a broken link to the Production Checklist in the Deployment Guide
=> fix(docs): fix broken link in 'Deployment Guide' page

docs/Configuration/Overview.md
**Check List**
Dev Server doesn't really make sense any more, let's just be clear instead.
=> docs: replace reference to 'Dev Server' in 'Configuration Overview'

docs/Deployment/Deployment-Guide.md, packages/cubejs-docker/dev.Dockerfile, packages/cubejs-docker/latest.Dockerfile
=> Docker heroku

packages/cubejs-client-core/src/ResultSet.js, packages/cubejs-client-core/src/tests/drill-down.test.js
=> fix(@cubejs-client/core): propagate segments to drillDown queries

packages/cubejs-backend-shared/src/env.ts, packages/cubejs-backend-shared/src/index.ts, packages/cubejs-backend-shared/src/package.ts, packages/cubejs-server/package.json, packages/cubejs-server/src/command/dev-server.ts, packages/cubejs-server/src/command/server.ts, packages/cubejs-server/src/server/container.ts, packages/cubejs-server/src/shared.ts, packages/cubejs-server/yarn.lock
=>  feat(@cubejs-backend/server): More diagnostics

docs/Getting-started.md
=> Improve Getting Started documentation

docs/Deployment/Production-Checklist.md
**Check List**
Fixes broken links on Production Checklist. Need to add a Gatsby plugin to prevent this from re-occurring.
=> docs: fix broken links in 'Production Checklist' page

packages/cubejs-cli/src/templates.ts, packages/cubejs-server/src/server/container.ts
=> Improve DX

packages/cubejs-docker/package.json, packages/cubejs-docker/yarn.lock, packages/cubejs-server/src/server/container.ts, packages/cubejs-server/src/server/utils.ts
=> Add TypeScript to official Docker image to support cube.ts

.github/workflows/publish.yml, .github/workflows/push.yml, packages/cubejs-docker/DEVELOPMENT.md, packages/cubejs-docker/README.md, packages/cubejs-docker/latest-alpine.Dockerfile
Hello!
refs https://github.com/cube-js/cube.js/issues/1391
Thanks
=> feat(docker): Introduce alpine images

examples/ecom-backend/README.MD
=> Examples: ecom-backend add readme

examples/slack-vibe/index.js
=> fix(examples): Add deprecation warnings to the source code of Slack Vibe

docs/Deployment/Deployment-Guide.md
=> misc(docs): Deployment - build by Heroku

packages/cubejs-backend-shared/src/package.ts, packages/cubejs-server/src/server/container.ts, packages/cubejs-server/src/server/utils.ts
=> misc(@cubejs-backend/server): Improve code quality

examples/angular-dashboard-with-material-ui/package.json, examples/angular-dashboard-with-material-ui/yarn.lock, examples/compare-date-range/package.json, examples/compare-date-range/yarn.lock, examples/d3-dashboard/package.json, examples/d3-dashboard/yarn.lock, examples/data-blending/package.json, examples/data-blending/yarn.lock, examples/drill-downs/package.json, examples/drill-downs/yarn.lock, examples/ecom-backend/package.json, examples/ecom-backend/yarn.lock, examples/hacktoberfest/package.json, examples/highcharts/package.json, examples/highcharts/yarn.lock, examples/mapbox/package.json, examples/mapbox/yarn.lock, examples/material-ui-dashboard/package.json, examples/material-ui-dashboard/yarn.lock, examples/react-data-table/package.json, examples/real-time-dashboard/package.json, examples/real-time-dashboard/yarn.lock, examples/vue-query-builder/package.json, examples/vue-query-builder/yarn.lock, examples/web-analytics/package.json, examples/web-analytics/yarn.lock
=> Examples: update package.json

CONTRIBUTING.md
=> Fixing email address for code of conduct

CODE_OF_CONDUCT.md
=> Simplifying the code of conduct header

packages/cubejs-postgres-driver/driver/PostgresDriver.js, packages/cubejs-postgres-driver/yarn.lock
=> feat(@cubejs-backend/postgres-driver): Support CUBEJS_DB_SSL_KEY

docs-build/static/styles/_layout.scss, docs-build/static/styles/_mixins.scss, docs-build/static/styles/_typography.scss
=> fix(docs): ensure body font size is consistently applied 

packages/cubejs-cli/src/templates.ts
Hello!
refs https://github.com/cube-js/cube.js/issues/1015
Thanks
=> fix(cubejs-cli): template/serverless - specify CORS

package.json, yarn.lock
=> misc: Remove unneeded deps from global package.json

packages/cubejs-server-core/core/index.test.js, packages/cubejs-server-core/core/optionsValidate.js, packages/cubejs-server-core/package.json, packages/cubejs-server-core/yarn.lock, packages/cubejs-server/src/server.ts, packages/cubejs-serverless/Handlers.js
=> fix: add content-type to allowedHeaders

packages/cubejs-backend-shared/package.json, packages/cubejs-cli/package.json, packages/cubejs-client-ws-transport/package.json, packages/cubejs-druid-driver/package.json, packages/cubejs-linter/package.json, packages/cubejs-query-orchestrator/package.json, packages/cubejs-server/package.json
=> misc: Export linter binary from cubejs-linter

.dockerignore, package.json, packages/cubejs-backend-shared/package.json, packages/cubejs-backend-shared/yarn.lock, packages/cubejs-cli/package.json, packages/cubejs-cli/src/utils.ts, packages/cubejs-cli/tsconfig.json, packages/cubejs-cli/yarn.lock, packages/cubejs-docker/dev.Dockerfile, packages/cubejs-docker/package.json, packages/cubejs-docker/yarn.lock, packages/cubejs-druid-driver/package.json, packages/cubejs-druid-driver/tsconfig.json, packages/cubejs-druid-driver/yarn.lock, packages/cubejs-linter/package.json, packages/cubejs-linter/yarn.lock, packages/cubejs-prestodb-driver/driver/PrestoDriver.js, packages/cubejs-query-orchestrator/package.json, packages/cubejs-query-orchestrator/tsconfig.json, packages/cubejs-query-orchestrator/yarn.lock, packages/cubejs-server/package.json, packages/cubejs-server/tsconfig.json, packages/cubejs-server/yarn.lock, tsconfig.base.json, yarn.lock
=> misc: improve ts support

.github/label-actions.yml, .github/workflows/issue-labeler.yml
=> misc(ci): Auto comment on "help wanted"

docs/Configuration/Connecting-to-the-Database.md
=> docs: add SQLite to supported databases list

docs/Cube.js-ClI/Using-the-Cube.js-CLI.md
=> docs: replace global CLI installation instructions with `npx` alternative

docs/Configuration/Overview.md
**Check List**
Add documentation describing how to configure CORS for the REST API.
=> docs: add CORS documentation to 'Configuration Overview' page

docs/content/Configuration/Config.md, docs/content/Configuration/Overview.md
**Check List**
Add missing reference CORS documentation as well as improving the 'Configuration Overview' page
=> docs: improve CORS documentation

docs/build-netlify.sh, docs/netlify.toml, netlify.toml
**Check List**
Added Netlify configuration files for [Deploy Preview functionality](https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/)
=> chore: add Netlify configuration and custom build script

docs/content/Caching/Caching.md, docs/content/Cube.js-Introduction.md, docs/content/Guides/Many-to-Many-Relationship.md, docs/content/Guides/Subquery.md, docs/content/Schema/cohort-retention.md, docs/content/Schema/event-analytics.md
**Check List**
The image URLs changed due to #1456, only spotted this now 😅
=> docs: fix broken image URLs

lerna.json
**Check List**
When cloning the project and running `yarn lerna bootstrap`, the `docs/` package will also have its' dependencies installed.
=> docs: bootstrap dependencies via `lerna`

.github/workflows/docs.yml
**Check List**
Fix the workflow name in GitHub actions
=> ci(docs): fix workflow names

docs/README.md
**Check List**
Improve documentation project setup instructions
=> docs: update documentation project's `README.md`

packages/cubejs-server/src/server/container.ts
=> fix(@cubejs-backend/server): Versions inside error message

docs/.lintstagedrc, docs/.markdownlint.json, docs/.prettierrc, docs/.textlintrc, docs/package.json, docs/yarn.lock
**Check List**
Add text linters to `docs/`.
=> docs: add `markdownlint`, `textlint` and `prettier`

CONTRIBUTING.md, dco.md
=> Adding DCO language

packages/cubejs-docker/package.json, packages/cubejs-docker/yarn.lock
=> feat(docker): Add sqlite driver to built-in drivers

docs/netlify.toml
**Check List**
Currently the Netlify staging site has issues with redirected URLs, this PR aims to fix those issues.
=> docs(@cubejs-docs/site): fix redirects on Netlify staging site

.github/workflows/publish.yml, .github/workflows/push.yml, packages/cubejs-api-gateway/package.json, packages/cubejs-cli/package.json, packages/cubejs-client-vue/package.json, packages/cubejs-server/package.json
=> misc: Dont forget to build

packages/cubejs-bigquery-driver/driver/BigQueryDriver.js, packages/cubejs-bigquery-driver/driver/index.d.ts
Hello!
refs https://github.com/cube-js/cube.js/issues/1028
Thanks
=> feat(@cubejs-backend/bigquery-driver): add support for read-only mode

.github/workflows/docs.yml, docs/gatsby-config.js, docs/package.json, docs/yarn.lock
**Check List**
Add [Percy](https://percy.io/) to documentation site.
=> docs(@cubejs-docs/site): add Percy integration

packages/cubejs-server/src/server/container.ts
=> misc: Show warning instead of error for multiple lock files

packages/cubejs-cli/src/config.ts
=> fix(cubejs-cli): deploy --upload-env - filter CUBEJS_DEV_MODE

DEPRECATION.md
**Check List**
Adding a `DEPRECATION.md` file to list all deprecated functionality.
=> docs: add `DEPRECATION.md`

docs/package.json, docs/yarn.lock
**Check List**
Closes #1544 by removing the unused dependency.
=> chore(@cubejs-docs/site): remove `dompurify`

CODEOWNERS
**Check List**
Add `*.md` to `CODEOWNERS` so @cube-js/developer-relations-and-community is notified for PR review.
=> chore: ensure DevRel team is pinged for review when `.md` files are changed

.github/workflows/examples.yml, examples/hacktoberfest/dashboard/src/App/index.js, examples/hacktoberfest/dashboard/src/Card/PrContentsCountsCard.js, examples/hacktoberfest/dashboard/src/Card/RepoStarCountCard.js, examples/hacktoberfest/schema/PullRequests.js, examples/hacktoberfest/schema/Repos.js
=> chore(examples): Migrate Hacktoberfest example to Cube Store

packages/cubejs-api-gateway/src/SubscriptionServer.js
=> fix(@cubejs-backend/api-gateway): SubscriptionServer - support dryRun

DEPRECATION.md
**Check List**
Missing changes from #1552
=> docs: improve `DEPRECATION.md`

DCO.md
**Check List**
Fixed various typos and an incorrect link in the copy. Also ran Prettier over the file.
=> docs(DCO.md): fix typos, links and run Prettier

packages/cubejs-query-orchestrator/src/orchestrator/QueryOrchestrator.js, packages/cubejs-query-orchestrator/src/orchestrator/RedisPool.ts, packages/cubejs-server-core/core/index.d.ts
Hello!
refs https://github.com/cube-js/cube.js/pull/1595
Thanks
=> feat(@cubejs-backend/query-orchestrator): set pool options from server config

packages/cubejs-query-orchestrator/src/orchestrator/RedisFactory.ts, packages/cubejs-query-orchestrator/src/orchestrator/RedisPool.ts
=> feat(@cubejs-backend/query-orchestrator): Introduce `AsyncRedisClient`

DEPRECATION.md
=> docs(DEPRECATION.md): improve content on deprecated feature removal

packages/cubejs-api-gateway/src/gateway.js, packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/src/interfaces.ts, packages/cubejs-api-gateway/src/query.js
=> refactor(@cubejs-backend/api-gateway): Move to TypeScript

docs/content/Cube-Cloud/Configuration/Connecting-to-Databases.md, docs/content/Cube-Cloud/Configuration/Deployment-Env-Vars.md, docs/content/Cube-Cloud/Configuration/Deployment-Types.md, docs/content/Cube-Cloud/Index.md, docs/content/Cube-Cloud/Quickstart.md
=> docs: Cube Cloud quickstart docs

packages/cubejs-docker/dev.Dockerfile, packages/cubejs-docker/latest-alpine.Dockerfile, packages/cubejs-docker/latest.Dockerfile
Hello!
refs https://cube-js.slack.com/archives/CC0403RRR/p1607992006008900
Thanks
=> fix(docker): Drop usage of VOLUME to protected unexpected behavior

packages/cubejs-api-gateway/test/cached-handler.test.ts
=> fix: random test crash on Node.js 10

packages/cubejs-client-core/index.d.ts
**Check List**
#1621 
Added compareDateRanges as a type to TimeDimension
=> fix(@cubejs-core): Add type definition for compareDateRange, fix #1621

docs/content/Schema/pre-aggregations.md
=> docs: Write about limitations in readOnly mode

docs/content/Schema/pre-aggregations.md
**Check List**
https://cube-js.slack.com/archives/CC0403RRR/p1608239223053800?thread_ts=1608183932.038800&cid=CC0403RRR
=> docs: move readonly external pre-aggregation limitations under parent heading

packages/cubejs-schema-compiler/adapter/BaseQuery.js, packages/cubejs-schema-compiler/adapter/PreAggregations.js, packages/cubejs-schema-compiler/compiler/CubeEvaluator.js, packages/cubejs-schema-compiler/compiler/CubePropContextTranspiler.js, packages/cubejs-schema-compiler/compiler/CubeSymbols.js, packages/cubejs-schema-compiler/compiler/CubeValidator.js, packages/cubejs-schema-compiler/test/integration/mssql/MSSqlPreAggregationsTest.js, packages/cubejs-schema-compiler/test/integration/postgres/PreAggregationsTest.js
=> feat: Rollup join implementation

packages/cubejs-backend-shared/src/track.ts, packages/cubejs-cli/src/command/auth.ts, packages/cubejs-cli/src/command/create.ts, packages/cubejs-cli/src/command/deploy.ts, packages/cubejs-cli/src/command/generate.ts, packages/cubejs-cli/src/command/token.ts, packages/cubejs-cli/src/utils.ts
=> misc: wrong parameter name

packages/cubejs-client-react/src/hooks/cube-query.js, packages/cubejs-client-react/src/hooks/dry-run.js
=> fix(@cubejs-client/react): reset the error on subsequent calls

packages/cubejs-api-gateway/src/gateway.ts
=> feat(api-gateway): Dont run all health checks, when the one is down

packages/cubejs-api-gateway/src/LocalSubscriptionStore.ts, packages/cubejs-api-gateway/src/SubscriptionServer.ts, packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/src/requestParser.ts, packages/cubejs-api-gateway/test/index.test.js
=> refactoring(api-gateway): Move to TS

docs/content/Cube.js-Frontend/@cubejs-client-core.md, packages/cubejs-client-core/src/HttpTransport.js, packages/cubejs-client-core/src/HttpTransport.test.js, packages/cubejs-client-core/src/index.js
=> feat(@cubejs-client/core): allow making HTTP POST requests to Cube.js API

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/test/index.test.js
=> fix(api-gateway): Fix broken POST /v1/dry-run

.github/workflows/rust.yml, rust/cubestore/src/sql/mod.rs
=> feat(cubestore): Support GROUP BY DECIMAL

docs/.markdownlint.json, docs/content/Cube.js-Introduction.md
**Check List**
Minor improvements to Introduction page
=> docs: improve 'Introduction'

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/test/index.test.js, packages/cubejs-playground/src/ExplorePage.js, packages/cubejs-server-core/core/DevServer.js, packages/cubejs-server-core/core/index.js
=> fix(playground): Use basePath from configuration, fix #377

packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts
=> refactor(@cubejs-backend/query-orchestrator): remove unused `isDigestKey` argument

packages/cubejs-athena-driver/driver/AthenaDriver.js, packages/cubejs-athena-driver/driver/index.d.ts, packages/cubejs-athena-driver/package.json
=> feat(athena-driver): Support readOnly option, add typings

DEPRECATION.md
**Check List**
Document removal of `contextToDataSourceId`.
=> docs(DEPRECATION.md): document removal of `contextToDataSourceId`

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/test/cached-handler.test.ts, packages/cubejs-api-gateway/test/index.test.js
=> feat(api-gateway): Support schema inside Authorization header, fix #1297

packages/cubejs-client-react/.eslintrc.js, packages/cubejs-client-react/src/hooks/cube-query.js, packages/cubejs-client-react/src/hooks/dry-run.js
=> fix(@cubejs-client/react): prevent state updates on unmounted components

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/test/index.test.ts
=> fix(api-gateway): /readyz /healthz - correct response for partial outage

packages/cubejs-server-core/package.json, packages/cubejs-server-core/src/core/DevServer.ts, packages/cubejs-server-core/src/core/RefreshScheduler.ts, packages/cubejs-server-core/src/core/server.ts, packages/cubejs-server-core/src/core/types.ts, packages/cubejs-server-core/yarn.lock
=> misc(server-core): Move more parts to TS

packages/cubejs-cli/src/command/create.ts, packages/cubejs-server-core/core/DriverDependencies.js
=> misc(server-core): Compatibility with CLI

packages/cubejs-server/src/server/container.ts
=> misc(server): Remove warning

packages/cubejs-server-core/src/core/server.ts
=> misc: Remove debug console.log

packages/cubejs-backend-shared/src/env.ts, packages/cubejs-backend-shared/test/env.test.ts
=> feat: Allow to specify socket for PORT/TLS_PORT, fix #1681

packages/cubejs-backend-shared/src/env.ts, packages/cubejs-backend-shared/test/env.test.ts
=> fix: Allow CUBEJS_SCHEDULED_REFRESH_TIMER to be boolean

packages/cubejs-backend-shared/src/env.ts, packages/cubejs-backend-shared/test/env.test.ts
=> misc: Better error messages for invalid ENV(s)

packages/cubejs-server-core/src/core/types.ts
=> fix: Declare Add missing externalQueueOptions for QueryCacheOptions

docs/content/Cube-Cloud/Deploys.md, docs/src/components/Layout/MainMenu.tsx
=> docs: Cube Cloud deploys

packages/cubejs-docker/dev.Dockerfile, packages/cubejs-docker/latest-alpine.Dockerfile, packages/cubejs-docker/latest.Dockerfile
=> feat(docker): Upgrade Node.js to Node v12.20.1 (security release)

packages/cubejs-cli/src/config.ts
**Check List**
Uploading with token should take precedence over .cubecloud file and update it
=> Uploading with token should take precedence over .cubecloud file and update it

docs/static/styles/_code.scss, docs/static/styles/_layout.scss, docs/static/styles/_mixins.scss, docs/static/styles/_tables.scss, docs/static/styles/_typography.scss, docs/static/styles/content.css, docs/static/styles/index.module.scss, docs/static/styles/prism.scss
**Check List**
Changed heading font to Cera Pro Bold.
=> docs(@cubejs-docs/site): change heading font and improve styling

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/src/interfaces.ts, packages/cubejs-api-gateway/test/index.test.ts
=> fix(gateway): Allow healthchecks to be requested without auth

packages/cubejs-api-gateway/src/LocalSubscriptionStore.ts, packages/cubejs-api-gateway/src/SubscriptionServer.ts, packages/cubejs-backend-shared/src/env.ts, packages/cubejs-backend-shared/src/index.ts, packages/cubejs-backend-shared/src/promises.ts, packages/cubejs-backend-shared/test/promises.test.ts, packages/cubejs-server-core/src/core/server.ts, packages/cubejs-server/package.json, packages/cubejs-server/src/command/dev-server.ts, packages/cubejs-server/src/command/server.ts, packages/cubejs-server/src/server.ts, packages/cubejs-server/src/server/container.ts, packages/cubejs-server/src/server/gracefull-http.ts, packages/cubejs-server/src/websocket-server.ts, packages/cubejs-server/tests/__mocks__/http.js, packages/cubejs-server/tests/__mocks__/https.js, packages/cubejs-server/tests/__mocks__/server-core.js, packages/cubejs-server/tests/index.test.js, packages/cubejs-server/yarn.lock
=> feat: introduce graceful shutdown

packages/cubejs-cli/src/deploy.ts
=> add dashboard-app folder to black list

packages/cubejs-server-core/src/core/CompilerApi.js, packages/cubejs-server-core/src/core/server.ts, packages/cubejs-server-core/src/core/types.ts
Hello!
refs https://github.com/cube-js/cube.js/issues/1728
Thanks
=> fix: Pass dbType in DialectContext for dialectFactory. fix #1728

packages/cubejs-server/src/server/container.ts
=> feat(server): Throw an exception when env file is not correct

packages/cubejs-server/package.json, packages/cubejs-server/src/server.ts, packages/cubejs-server/src/server/container.ts, packages/cubejs-server/yarn.lock
=> fix(server): configuration reload should overrite old env variables

packages/cubejs-snowflake-driver/driver/SnowflakeDriver.js, packages/cubejs-snowflake-driver/package.json, packages/cubejs-snowflake-driver/yarn.lock
=> fix(snowflake-driver): Handle null values for numbers, dates. fix #1741

packages/cubejs-cli/src/command/create.ts
=> fix(cli): Broken jdbc installation

packages/cubejs-server/src/server/container.ts
=> Revert "feat(server): Throw an exception when env file is not correct"

packages/cubejs-server/package.json
Hello!
refs https://github.com/cube-js/cube.js/issues/1766
Thanks
=> fix(server): Wrong path to typings. fix #1766

packages/cubejs-backend-shared/src/promises.ts, packages/cubejs-backend-shared/test/promises.test.ts, packages/cubejs-server/package.json, packages/cubejs-server/src/server.ts, packages/cubejs-server/src/server/container.ts, packages/cubejs-server/test/index.test.js
=> feat(server): Kill Cube.js if it's stuck in gracefull shutdown

examples/react-muze/dashboard-app/src/App.module.less, examples/react-muze/dashboard-app/src/index.js, examples/react-muze/dashboard-app/src/index.less, examples/react-muze/dashboard-app/src/index.module.less
**Check List**
**List of Fixes**
- Safari: Fix MuzeJS having incorrect width and height initially and then infinitely resizing in small increments
=> examples: Fix resize issue in the MuzeJS sample

rust/Cargo.lock, rust/cubestore/Cargo.toml, rust/cubestore/src/lib.rs, rust/cubestore/src/metastore/mod.rs, rust/cubestore/src/mysql/mod.rs, rust/cubestore/src/queryplanner/query_executor.rs, rust/cubestore/src/sql/mod.rs
See the commit message for more info.
This fixes the crashes and errors I encountered while playing around with adding mock UDFs for HyperLogLog.
=> Improve support for the binary data type in cubestore

packages/cubejs-query-orchestrator/src/orchestrator/QueryCache.ts, packages/cubejs-query-orchestrator/src/orchestrator/QueryOrchestrator.ts, packages/cubejs-server-core/src/core/OrchestratorApi.js, packages/cubejs-server-core/src/core/RefreshScheduler.ts
=> fix: Remove unnecessary `SELECT 1` during scheduled refresh. Fixes #1592

CONTRIBUTING.md
=> docs(contributing): Replace legacy import for BaseDriver

packages/cubejs-docker/README.md
**Check List**
Improved the Docker README with some more instructions
=> docs(@cubejs-backend/docker): improve `README.md`

docs/content/Guides/Subquery.md
**Check List**
Added a warning with information about self-referencing dimensions for subqueries.
=> docs: add warning to 'Subquery' page about self-referential dimensions/measures

packages/cubejs-query-orchestrator/src/orchestrator/RedisPool.ts
Related issues https://github.com/coopernurse/node-pool/issues/175, https://github.com/coopernurse/node-pool/issues/197
=> fix(@cubejs-backend/query-orchestrator): prevent generic pool infinite loop

packages/cubejs-backend-shared/package.json, packages/cubejs-backend-shared/src/promises.ts, packages/cubejs-backend-shared/test/promises.test.ts, packages/cubejs-server-core/src/core/server.ts, packages/cubejs-server/src/websocket-server.ts
=> feat: Log warnings from createCancelableInterval

docs/content/Schema/Dynamic-Schema-Creation.md, docs/content/Schema/schema-execution-environment.md
**Check List**
Create a single page to collect all dynamic schema creation documentation.
**Note to reviewers:** I think we could probably add some examples of dynamic schema creation using the security context too; are there any other examples of interesting dynamic schema creation problems that are worth documenting?
=> docs: add 'Dynamic Schema Creation' page

docs/content/Schema/Dynamic-Schema-Creation.md
**Check List**
The markdown parser doesn't like inline code as headings, removing them till we have a better fix in place
=> docs: fix headings in 'Dynamic Schema Creation' page

packages/cubejs-server-core/src/core/server.ts
=> fix(server-core): Clear refresh uncaughtException for DevServer

packages/cubejs-server-core/src/core/DevServer.ts, packages/cubejs-server/src/server/container.ts
=> feat(server): Guard multiple restart in same time

packages/cubejs-playground/src/pages/ConnectionWizard/components/ConnectionTest.js
=> misc: fix typo in playground.

packages/cubejs-backend-shared/src/promises.ts, packages/cubejs-backend-shared/test/promises.test.ts, packages/cubejs-server-core/src/core/server.ts, packages/cubejs-server-core/src/index.ts, packages/cubejs-server/src/server.ts, packages/cubejs-server/src/server/container.ts
=> fix(server): Unexpected kill on graceful shutdown

CONTRIBUTING.md
=> docs(contributing): Write about Docker, Cube.js Server

packages/cubejs-server-core/src/core/DevServer.ts
=> fix(playground): Create schema directory on changing env

.github/workflows/push.yml, packages/cubejs-schema-compiler/test/integration/clickhouse/ClickHouseDbRunner.js
=> misc(ci): test clickhouse on real version

packages/cubejs-query-orchestrator/src/driver/BaseDriver.js
Hello!
refs https://github.com/cube-js/cube.js/issues/1796
Thanks
=> fix: Map int2/4/8 to generic int type. fix #1796

packages/cubejs-api-gateway/src/dateParser.js, packages/cubejs-api-gateway/test/dateParser.test.js
=> fix(api-gateway): Validate a case when chrono can return empty array

docs/content/Caching/Caching.md
=> docs: Update Caching intro

.github/workflows/rust-pr.yml, .github/workflows/rust.yml, rust/Cargo.lock, rust/cubestore/Cargo.toml, rust/cubestore/src/bin/cubestored.rs, rust/cubestore/src/cluster/mod.rs, rust/cubestore/src/cluster/worker_pool.rs, rust/cubestore/src/config/mod.rs, rust/cubestore/src/import/mod.rs, rust/cubestore/src/lib.rs, rust/cubestore/src/metastore/listener.rs, rust/cubestore/src/metastore/mod.rs, rust/cubestore/src/mysql/mod.rs, rust/cubestore/src/queryplanner/mod.rs, rust/cubestore/src/remotefs/gcs.rs, rust/cubestore/src/remotefs/mod.rs, rust/cubestore/src/remotefs/queue.rs, rust/cubestore/src/remotefs/s3.rs, rust/cubestore/src/scheduler/mod.rs, rust/cubestore/src/sql/mod.rs, rust/cubestore/src/store/compaction.rs, rust/cubestore/src/store/mod.rs, rust/cubestore/src/telemetry/mod.rs, rust/cubestore/src/util/mod.rs
=> feat(cubestore): Migrate to tokio v1.0 and implement GCS support

packages/cubejs-bigquery-driver/driver/BigQueryDriver.js, packages/cubejs-bigquery-driver/package.json, packages/cubejs-bigquery-driver/yarn.lock, packages/cubejs-cubestore-driver/driver/CubeStoreDriver.js, packages/cubejs-query-orchestrator/src/driver/BaseDriver.js, packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts, packages/cubejs-query-orchestrator/test/unit/QueryOrchestrator.test.js, rust/Cargo.lock, rust/cubestore/Cargo.toml, rust/cubestore/src/import/mod.rs, rust/cubestore/src/sql/mod.rs
=> feat: BigQuery CSV pre-aggregation download support

packages/cubejs-server/package.json, packages/cubejs-server/src/graceful-middleware.ts, packages/cubejs-server/src/server-status.ts, packages/cubejs-server/src/server.ts, packages/cubejs-server/src/server/container.ts, packages/cubejs-server/yarn.lock
=> feat(server): Dont accept new request(s) during shutdown

DEPRECATION.md
**Check List**
Reordered the table and existing notices to ascending order. New additions for v0.26 are at the end of the file.
=> docs(DEPRECATION.md): add v0.26 deprecation notices

docs/content/Deployment/Deployment-Guide.md
Added link to CloudFormation template for VPC creation with Internet access via NAT.
=> docs: added link to CloudFormation template for VPC

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-backend-shared/src/convert.ts, packages/cubejs-backend-shared/src/index.ts, packages/cubejs-backend-shared/src/promises.ts, packages/cubejs-backend-shared/test/convert.test.ts, packages/cubejs-backend-shared/test/promises.test.ts, packages/cubejs-server-core/src/core/server.ts, packages/cubejs-server/src/websocket-server.ts, tsconfig.base.json
=> feat: Improve logs for RefreshScheduler and too long execution

packages/cubejs-backend-shared/src/promises.ts, packages/cubejs-backend-shared/test/promises.test.ts
=> fix(shared): 1st interval unexpected call on createCancelableInterval

packages/cubejs-backend-shared/test/promises.test.ts
=> misc(shared): fix random test fail

rust/cubestore/src/config/mod.rs
10 minutes is definitely enough for each test, even on CI.
Probably a much lower value is also ok, just didn't bother to do the research.
=> chore(cubestore): fail tests on timeout (10 minutes for each test)

packages/cubejs-server/src/server/container.ts
=> feat: Disable graceful shutdown by default

docs/content/Deployment/Production-Checklist.md
Reference the fact that the schema name for pre-aggregations is different in production.
=> docs: add mention of `CUBEJS_PREAGGREGATIONS_SCHEMA` to Production Checklist

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/src/index.ts, packages/cubejs-api-gateway/src/requestParser.ts, packages/cubejs-server-core/src/core/DevServer.ts, packages/cubejs-server-core/src/core/server.ts
=> feat: Ability to specify dataSource from request

packages/cubejs-server/index.js, packages/cubejs-server/package.json, packages/cubejs-server/src/index.ts, packages/cubejs-server/src/server.ts, packages/cubejs-server/src/server/container.ts
=> misc: Introduce embeded mode for ServerContainer

rust/Cargo.lock, rust/cubestore/src/sql/mod.rs
Contains a test for the [fix in arrow](https://github.com/cube-js/arrow/pull/6)
=> chore(cubestore): add a test for empty group_by with binary data

packages/cubejs-server-core/src/core/server.ts, packages/cubejs-server-core/src/core/types.ts
=> misc(server-core): scheduledRefreshContexts - should return array

packages/cubejs-client-core/src/ResultSet.js
=> fix(@cubejs-client/core): propagate time dimension to the drill down query

packages/cubejs-server-core/test/unit/index.test.ts
=> misc(server-core): Add test for scheduledRefreshContexts, refs #1904

packages/cubejs-backend-shared/src/env.ts, packages/cubejs-backend-shared/test/env.test.ts
Hello!
refs https://cube-js.slack.com/archives/CLGEK5N1K/p1611789847002300
Thanks
=> fix(shared): Value True is not valid for CUBEJS_SCHEDULED_REFRESH_TIMER

docs/content/Caching/Caching.md, docs/content/Cube.js-Frontend/Dashboard-App.md, docs/content/Developer-Tools/CLI-Reference.md
Fixes a few formatting issues with https://github.com/cube-js/cube.js/pull/1902
=> docs: formatting fixes for #1902

docs/README.md
Added Markdown formatting instructions
=> docs(@cubejs-docs/site): add formatting instructions to `README.md`

rust/README.md
=> docs(cubestore): update `README.md`

docs/content/Configuration/Config.md, docs/content/Configuration/Multitenancy-Setup.md
Hello!
refs https://github.com/cube-js/cube.js/issues/1904
Thanks
=> docs(multitenancy): Add Warning about scheduledRefreshContexts

rust/Cargo.lock, rust/cubestore/Cargo.toml, rust/cubestore/src/queryplanner/query_executor.rs, rust/cubestore/src/queryplanner/serialized_plan.rs
=> feat(cubestore): Rebase to datafusion 2021-01-27 version

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js, packages/cubejs-schema-compiler/test/unit/BaseQueryTest.js
=> fix(schema-compiler): Wrong dayOffset in refreshKey for not UTC computers

packages/cubejs-cli/src/index.ts
=> feat: Warning about Node.js 10 deprecation

packages/cubejs-api-gateway/package.json, packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/src/interfaces.ts, packages/cubejs-api-gateway/test/auth.test.ts, packages/cubejs-api-gateway/test/index.test.ts, packages/cubejs-api-gateway/yarn.lock
=> fix(api-gateway): Await checkAuth middleware

DEPRECATION.md, docs/content/Authentication-&-Authorization.md
There were a few things left on the [v0.26 PR](https://github.com/cube-js/cube.js/pull/1854) that weren't fixed, this PR addresses that.
=> docs: update documentation for v0.26 removals

rust/cubestore/src/metastore/mod.rs
Previously, the sort key columns were used in the order from the table.
This commit provides control over the index data layout.
=> fix(cubestore): sort data in column order from the index

docs/content/Configuration/Config.md, docs/content/Configuration/Multitenancy-Setup.md
=> docs: remove mentions of nested `u` object in security contexts

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/test/auth.test.ts
Hello!
refs https://github.com/cube-js/cube.js/issues/1974#event-4279339404
Thanks
=> fix: coerceForSqlQuery - dont mutate securityContext, fix #1974

packages/cubejs-bigquery-driver/driver/BigQueryDriver.js, packages/cubejs-cubestore-driver/driver/CubeStoreDriver.js, rust/Cargo.lock, rust/cubestore/Cargo.toml, rust/cubestore/src/import/mod.rs, rust/cubestore/src/metastore/mod.rs, rust/cubestore/src/metastore/table.rs, rust/cubestore/src/scheduler/mod.rs, rust/cubestore/src/sql/mod.rs, rust/cubestore/src/sql/parser.rs
=> feat(cubestore): Multiple location load support

docs/content/Configuration/Config.md, docs/content/Configuration/Multitenancy-Setup.md
Formatted files with Prettier, de-duplicated links and added inline codeblocks where they were missing.
Also updated the documentation around `scheduledRefreshContexts` to include the words "pre-aggregation".
=> docs: include mentions of pre-aggregations with `scheduledRefreshContexts`

examples/web-analytics/dashboard-app/src/App.js, examples/web-analytics/dashboard-app/src/components/Dropdown.js, examples/web-analytics/dashboard-app/src/components/SwitchTable.js, examples/web-analytics/dashboard-app/src/index.js
=> examples(web-analytics): fix duplicated key for components

packages/cubejs-schema-compiler/src/adapter/SqliteQuery.js
Hello!
https://cube-js.slack.com/archives/CC0403RRR/p1611910729189700?thread_ts=1611908140.188400&cid=CC0403RRR
```
CAST(-1.99 as int) - (-1.99 < CAST(-1.99 as int)) = -1 - (-1.99 < -1) = -1 - 1 = -2
CAST(1.99 as int) - (1.99 < CAST(1.99 as int)) = 1 - (1.99 < 1) = 1 - 0 = 1
```
Thanks
=> fix(sqlite-driver): Use workaround for FLOOR

packages/cubejs-api-gateway/src/SubscriptionServer.ts, packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/src/interfaces.ts, packages/cubejs-server-core/src/core/types.ts
=> feat: Improve typings for extendContext

CONTRIBUTING.md
refs https://github.com/cube-js/cube.js/issues/1989
=> docs(contributing): Use correct driver pattern fix #1989

packages/cubejs-cli/src/deploy.ts
**Check List**
Block from uploading files and folders (recur) starting from "."
=> feat: Block from uploading files and folders (recur) starting from "."

packages/cubejs-druid-driver/src/DruidClient.ts, packages/cubejs-druid-driver/src/DruidDriver.ts, packages/cubejs-query-orchestrator/src/driver/BaseDriver.js, packages/cubejs-server-core/src/core/types.ts
=> feat(server-core): Correct typings for driverFactory/dialectFactory

DEPRECATION.md
Improve `authInfo` deprecation examples as per conversation [from Slack](https://www.notion.so/Improve-deprecation-doc-6ab921d655cd4464b8313fa9bfdcb215#9f3d1f79355a4b3f8d688b39cb29d2ca).
=> docs(DEPRECATION.md): improve examples for `authInfo` deprecation

rust/Cargo.lock, rust/cubestore/Cargo.toml, rust/cubestore/src/cluster/message.rs, rust/cubestore/src/cluster/mod.rs, rust/cubestore/src/lib.rs, rust/cubestore/src/queryplanner/query_executor.rs, rust/cubestore/src/remotefs/gcs.rs, rust/cubestore/src/remotefs/mod.rs, rust/cubestore/src/remotefs/s3.rs, rust/cubestore/src/scheduler/mod.rs
In addition to the warmup, there is also a fix to the race condition that seems more likely with the warm-up code.
See the commit message for details.
=> Cubestore warmup

packages/cubejs-playground/src/components/Settings/Limit.js
default limit size is too large ,change to 200 and step to 100 https://github.com/cube-js/cube.js/issues/1999
=> limit size is too large  change to 200 step to 100

rust/cubestore/src/import/mod.rs, rust/cubestore/src/store/mod.rs, rust/cubestore/src/util/maybe_owned.rs, rust/cubestore/src/util/mod.rs
It is currently the bottleneck on the ingestion stage, so worth spending more time on it.
=> Speed up CSV parsing

docs/content/Deployment/Production-Checklist.md
Add health check section to Production Checklist and backreferences to the REST API page
=> docs: add healthcheck section to Production Checklist

packages/cubejs-schema-compiler/package.json, packages/cubejs-schema-compiler/test/integration/mssql/MSSqlDbRunner.js, packages/cubejs-schema-compiler/test/integration/postgres/BaseDbRunner.js, packages/cubejs-schema-compiler/test/integration/postgres/PostgresDBRunner.js, packages/cubejs-schema-compiler/test/integration/postgres/async-module.test.ts, packages/cubejs-schema-compiler/test/integration/postgres/dataschema-compiler.test.ts, packages/cubejs-schema-compiler/test/integration/postgres/pre-aggregations-alias.test.ts, packages/cubejs-schema-compiler/test/integration/postgres/pre-aggregations.test.ts, packages/cubejs-schema-compiler/test/integration/postgres/sql-generation-logic.test.ts, packages/cubejs-schema-compiler/test/integration/postgres/sql-generation.test.ts, packages/cubejs-schema-compiler/yarn.lock
=> misc: Improve integration testing

docs/content/Cube.js-Frontend/Real-Time-Data-Fetch.md, docs/static/styles/_code.scss, docs/static/styles/variables.scss
Fix fallback color for codeblocks, as reported by @igorlukanin. Also added missing language to codeblock in Real Time Data Fetch.
=> docs: fix fallback color for codeblocks

.github/workflows/push.yml, packages/cubejs-api-gateway/package.json, packages/cubejs-backend-shared/package.json, packages/cubejs-query-orchestrator/package.json, packages/cubejs-server-core/package.json
=> misc(ci): Upload code coverage to CodeCov

packages/cubejs-backend-shared/package.json, packages/cubejs-backend-shared/src/index.ts, packages/cubejs-backend-shared/src/machine-id.ts, packages/cubejs-backend-shared/src/track.ts, packages/cubejs-backend-shared/test/machine-id.test.ts, packages/cubejs-backend-shared/yarn.lock, packages/cubejs-server/package.json, packages/cubejs-server/yarn.lock
Hello!
refs https://github.com/cube-js/cube.js/issues/1998
Thanks
=> fix: hostname: command not found. fix #1998

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/src/interfaces.ts, packages/cubejs-backend-shared/src/env.ts, packages/cubejs-backend-shared/src/package.ts, packages/cubejs-backend-shared/test/env.test.ts, packages/cubejs-cli/src/command/token.ts, packages/cubejs-linter/index.js, packages/cubejs-linter/yarn.lock, packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts, packages/cubejs-schema-compiler/src/extensions/Reflection.ts, packages/cubejs-schema-compiler/src/extensions/RefreshKeys.ts, packages/cubejs-schema-compiler/test/integration/mssql/MSSqlDbRunner.js, packages/cubejs-schema-compiler/test/integration/postgres/BaseDbRunner.js, packages/cubejs-server-core/src/core/server.ts, packages/cubejs-server-core/src/core/types.ts, packages/cubejs-server-core/test/unit/index.test.ts, packages/cubejs-server/src/command/dev-server.ts, packages/cubejs-server/src/command/server.ts, packages/cubejs-server/src/server.ts, packages/cubejs-server/src/server/container.ts, packages/cubejs-server/src/server/gracefull-http.ts, packages/cubejs-server/src/server/typescript-compiler.ts, packages/cubejs-server/src/server/utils.ts
Hello!
https://github.com/cube-js/cube.js/issues/1972
Thanks
=> fix: CUBEJS_SCHEDULED_REFRESH_TIMER, fix #1972

packages/cubejs-cli/package.json, packages/cubejs-cli/src/command/generate.ts, packages/cubejs-cli/yarn.lock, packages/cubejs-server-core/src/core/server.ts, packages/cubejs-server/yarn.lock, yarn.lock
=> feat(cli): generate - allow to specify dataSource

packages/cubejs-query-orchestrator/src/driver/BaseDriver.js, packages/cubejs-query-orchestrator/test/unit/BaseDriver.test.ts
=> fix(query-orchestrator): detect negative int/decimal as strings

packages/cubejs-query-orchestrator/src/orchestrator/QueryCache.ts
Hello!
refs https://github.com/cube-js/cube.js/issues/1873
Thanks
=> fix: UnhandledPromiseRejectionWarning: Error: Continue wait. fix #1873

.github/workflows/push.yml, packages/cubejs-linter/index.js, packages/cubejs-query-orchestrator/package.json, packages/cubejs-query-orchestrator/src/driver/BaseDriver.js, packages/cubejs-query-orchestrator/test/unit/BaseDriver.test.ts, packages/cubejs-query-orchestrator/yarn.lock, tsconfig.base.json
=> feat: type detection - check overflows for int/bigint

.github/workflows/push.yml
=> misc(ci): fix typo

docs/content/Configuration/Multitenancy-Setup.md
Add simple example based on example provided by @carrasqu [in Slack](https://cube-js.slack.com/archives/CC0403RRR/p1612839117413900?thread_ts=1612833682.412900&cid=CC0403RRR).
=> docs: add simple version of multiple database connection example

rust/cubestore/src/remotefs/queue.rs
Should dramatically improve performance if the file is already
downloaded and there are legitimate downloads in the queue.
=> fix(cubestore): do not wait in queue for already downloaded files

CONTRIBUTING.md
=> Add a new section for a step-by-step guide

packages/cubejs-cli/package.json, packages/cubejs-cli/src/config.ts, packages/cubejs-cli/yarn.lock, packages/cubejs-query-orchestrator/src/driver/BaseDriver.js, packages/cubejs-server/package.json, packages/cubejs-server/src/server.ts, packages/cubejs-server/src/server/container.ts, packages/cubejs-server/yarn.lock
Hello!
For https://github.com/cube-js/cube.js/pull/2010
Thanks
=> feat: support SSL keys in .env files as multiline text

docs/content/Schema/cube.md
Story details: https://app.clubhouse.io/cube-dev/story/21
=> docs: document abstract cubes

rust/cuberpc/src/lib.rs, rust/cubestore/src/cluster/mod.rs, rust/cubestore/src/config/injection.rs, rust/cubestore/src/config/mod.rs, rust/cubestore/src/import/limits.rs, rust/cubestore/src/import/mod.rs, rust/cubestore/src/lib.rs, rust/cubestore/src/metastore/mod.rs, rust/cubestore/src/queryplanner/mod.rs, rust/cubestore/src/queryplanner/query_executor.rs, rust/cubestore/src/remotefs/gcs.rs, rust/cubestore/src/remotefs/mod.rs, rust/cubestore/src/remotefs/queue.rs, rust/cubestore/src/remotefs/s3.rs, rust/cubestore/src/scheduler/mod.rs, rust/cubestore/src/sql/mod.rs, rust/cubestore/src/store/compaction.rs, rust/cubestore/src/store/mod.rs
=> feat(cubestore): Introduce Dependency Injection

packages/cubejs-backend-shared/test/promises.test.ts, packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts, packages/cubejs-query-orchestrator/src/orchestrator/QueryCache.ts, packages/cubejs-query-orchestrator/src/orchestrator/QueryOrchestrator.ts, packages/cubejs-server-core/src/core/OrchestratorApi.ts, packages/cubejs-server-core/src/core/optionsValidate.ts, packages/cubejs-server-core/test/unit/index.test.ts
=> fix: continueWaitTimeout is ignored: expose single centralized continueWaitTimeout option

docs/content/Configuration/Connecting-to-the-Database.md, packages/cubejs-clickhouse-driver/driver/ClickHouseDriver.js, packages/cubejs-clickhouse-driver/package.json, packages/cubejs-clickhouse-driver/yarn.lock, packages/cubejs-druid-driver/package.json, packages/cubejs-druid-driver/src/DruidDriver.ts, packages/cubejs-druid-driver/yarn.lock
=> feat(druid-driver): Support CUBEJS_DB_SSL

rust/cubestore/src/queryplanner/serialized_plan.rs
The code was an incorrect attempt to handle aliasing in the intermediate
version. The logical plan actually has the qualifiers stripped so it
is not required.
Moreover, the code contained an error that could cause comparisons of
different columns during partition pruning.
=> fix(cubestore): fix index schema used for partition pruning

packages/cubejs-client-core/src/utils.js
=> fix(@cubejs-client/core): manage boolean filters for missing members

packages/cubejs-client-core/index.d.ts, packages/cubejs-client-react/index.d.ts
=> fix(@cubejs-client/react): type fixes

packages/cubejs-client-react/src/QueryBuilder.jsx, packages/cubejs-playground/src/QueryBuilder/FilterGroup.js
=> fix(@cubejs-client/react): replace dimension with member

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js, packages/cubejs-schema-compiler/test/unit/mssql-query.test.ts
rebased from https://github.com/cube-js/cube.js/pull/1172 (Contributed by @JoshMentzer)
=> fix(@cubejs-schema-compiler): remove `ORDER BY` from subqueries in MSSQL

packages/cubejs-druid-driver/src/DruidQuery.ts
**Check List**
Fix for https://github.com/cube-js/cube.js/issues/2149
Set valid SQL for current time.
=> fix(druid-driver): set valid sql timestamp

.github/workflows/publish.yml, .github/workflows/rust-master.yml, .github/workflows/rust.yml
=> misc(ci): distribute cubestore in tar.gz

.dockerignore, .github/workflows/publish.yml, packages/cubejs-docker/DEVELOPMENT.md, packages/cubejs-docker/dev-alpine.Dockerfile, packages/cubejs-docker/latest-alpine.Dockerfile, packages/cubejs-docker/latest.Dockerfile, packages/cubejs-docker/package.json, packages/cubejs-docker/yarn.lock, rust/.gitignore, rust/js-wrapper/post-install.ts, rust/package.json, rust/yarn.lock
=> feat(cubestore): Download binary from GitHub release.

.github/workflows/push.yml, rust/js-wrapper/post-install.ts, rust/package.json, rust/tsconfig.json, rust/yarn.lock
=> misc(ci): CUBESTORE_SKIP_POST_INSTALL

packages/cubejs-docker/dev.Dockerfile, packages/cubejs-docker/latest.Dockerfile
=> feat(docker): Upgrade default image to Buster (required for Cube Store)

.github/workflows/rust-master.yml, .github/workflows/rust.yml
=> misc(ci): Use currect working_dir for Rust target cache

rust/cubestore/src/import/mod.rs, rust/cubestore/src/lib.rs, rust/cubestore/src/queryplanner/query_executor.rs, rust/cubestore/src/sql/mod.rs, rust/cubestore/src/table/mod.rs, rust/cubestore/src/table/parquet.rs, rust/cubestore/src/util/mod.rs, rust/cubestore/src/util/ordfloat.rs
This significantly improves performance of import and other operations.
=> fix(cubestore): switch from string to float in table value

docs/content/Configuration/Extending-Cubejs.md, docs/content/Cube.js-Backend/@cubejs-backend-server-core.md, docs/content/Cube.js-Backend/@cubejs-backend-server.md
=> docs: Update extending guide

.github/workflows/push.yml, rust/js-wrapper/download.ts, rust/js-wrapper/index.ts, rust/js-wrapper/post-install.ts, rust/js-wrapper/process.ts, rust/package.json, rust/yarn.lock
=> feat(cubestore): installer - extract on fly

packages/cubejs-bigquery-driver/package.json, packages/cubejs-bigquery-driver/yarn.lock
=> feat(bigquery-driver): Upgrade @google-cloud/bigquery 5.x

docs/content/Caching/Overview.md, docs/content/Caching/Using-Pre-Aggreations.md
Setting the foundation for the new structure of the Caching section.
=> docs: new structure for caching

docs/content/Authentication-&-Authorization.md
Rewrite introduction to Authentication & Authorization, and add new section with information about JWT/JWK integration.
=> docs: add Using JSON Web Key Sets section

.github/workflows/publish.yml, .github/workflows/rust-master.yml, .github/workflows/rust.yml, rust/Cargo.toml, rust/Cross.toml, rust/Dockerfile, rust/cross/README.md, rust/cross/x86_64-pc-windows-gnu.Dockerfile, rust/cross/x86_64-pc-windows-msvc.Dockerfile, rust/cubestore/Cargo.toml, rust/cubestore/src/bin/cubestored.rs, rust/cubestore/src/cluster/mod.rs, rust/cubestore/src/cluster/worker_pool.rs, rust/cubestore/src/config/mod.rs, rust/cubestore/src/lib.rs
=> feat(cubestore): Build for Windows

.github/workflows/publish.yml, .github/workflows/rust-master.yml, .github/workflows/rust.yml, rust/cross/x86_64-unknown-linux-musl.Dockerfile, rust/cubestore/src/sys/malloc.rs
=> feat(cubestore): Build binary for Linux (Musl)

.dockerignore, .github/workflows/publish.yml, .github/workflows/rust-master.yml, .github/workflows/rust.yml, packages/cubejs-docker/dev-alpine.Dockerfile, packages/cubejs-docker/dev.Dockerfile, packages/cubejs-docker/latest-alpine.Dockerfile, packages/cubejs-docker/latest.Dockerfile, rust/.gitignore, rust/bin/cubestore-dev, rust/js-wrapper/download.ts, rust/js-wrapper/process.ts, rust/js-wrapper/utils.ts, rust/package.json, rust/yarn.lock
=> feat(cubestore): installer - detect musl + support windows

rust/Cargo.lock, rust/cubestore/Cargo.toml, rust/cubestore/src/bin/cubestored.rs, rust/cubestore/src/cluster/mod.rs, rust/cubestore/src/cluster/worker_pool.rs, rust/cubestore/src/config/injection.rs, rust/cubestore/src/config/mod.rs, rust/cubestore/src/config/processing_loop.rs, rust/cubestore/src/lib.rs, rust/cubestore/src/metastore/mod.rs, rust/cubestore/src/mysql/mod.rs, rust/cubestore/src/remotefs/queue.rs, rust/cubestore/src/sql/mod.rs, rust/cubestore/src/telemetry/mod.rs, rust/cubestore/src/util/mod.rs
=> feat(cubestore): Wait for processing loops and MySQL password support

rust/Cargo.lock, rust/cubestore/src/sql/mod.rs
Saves >10% of import time in my experiments.
=> feat(cubestore): speed up import with faster timestamp parsing

DEPRECATION.md, docs/content/Auth/Auth0-Guide.md, docs/content/Auth/Overview.md, docs/content/Auth/Security-Context.md, docs/content/Configuration/Config.md, guides/react-dashboard/content/2_authentication_and_graphql_backend.md, packages/cubejs-playground/src/components/SecurityContext/SecurityContext.js
Story details: https://app.clubhouse.io/cube-dev/story/178
=> docs(security): split page into Overview and Security Context pages

.github/workflows/publish.yml, .github/workflows/rust-master.yml, .github/workflows/rust.yml
=> misc(ci): Disable rust cache for target

packages/cubejs-server-core/src/core/server.ts, packages/cubejs-server-core/src/core/types.ts
=> fix: this.externalDriverFactory is not a function

rust/cubestore/src/sys/malloc.rs
=> fix(cubestore): Malloc trim is broken for docker

.github/workflows/publish.yml, .github/workflows/rust-master.yml, .github/workflows/rust.yml
=> feat(cubestore): Build binary with static linking for OpenSSL

rust/cross/x86_64-pc-windows-gnu.Dockerfile, rust/cross/x86_64-unknown-linux-gnu-buster.Dockerfile, rust/cross/x86_64-unknown-linux-gnu-stretch.Dockerfile, rust/cross/x86_64-unknown-linux-musl.Dockerfile
=> feat(cubestore): Bump OpenSSL to 1.1.1h

packages/cubejs-cubestore-driver/index.js, packages/cubejs-cubestore-driver/src/CubeStoreDevDriver.ts, packages/cubejs-cubestore-driver/src/index.ts, packages/cubejs-cubestore-driver/src/rexport.ts, packages/cubejs-cubestore-driver/src/utils.ts, packages/cubejs-server-core/src/core/server.ts, packages/cubejs-server-core/src/core/types.ts, rust/js-wrapper/cubestore-dev.ts, rust/js-wrapper/download.ts, rust/js-wrapper/process.ts
=> feat: Improvements for Cube Store in Cube.js

.github/workflows/publish.yml, .github/workflows/rust-master.yml, .github/workflows/rust.yml
=> feat(cubestore): Compress compiled binaries

.github/workflows/publish.yml, .github/workflows/rust-master.yml, .github/workflows/rust.yml
Hello!
Configuration:
Before
After:
Thanks
=> misc(ci): cross builds cache

rust/js-wrapper/process.ts
=> fix(cubestore): Delay query execution before Cube Store started

packages/cubejs-cubestore-driver/src/CubeStoreDevDriver.ts, packages/cubejs-cubestore-driver/src/CubeStoreDriver.ts
=> fix(cubestore-driver): host must be 127.0.0.1 for CubeStoreDevDriver

rust/js-wrapper/download.ts, rust/js-wrapper/process.ts, rust/package.json, rust/yarn.lock
=> feat(cubestore): post-install - improvements

packages/cubejs-cli/src/command/create.ts, packages/cubejs-cli/src/templates.ts, rust/js-wrapper/download.ts, rust/package.json, rust/yarn.lock
=> feat: Cube Store - GA

rust/cubestore/src/cluster/mod.rs, rust/cubestore/src/cluster/transport.rs, rust/cubestore/src/config/mod.rs
=> feat(cubestore): Extract transport to separate service

docs/content/Caching/Using-Pre-Aggreations.md, docs/content/Configuration/Config.md, docs/content/Configuration/Connecting-to-the-Database.md, docs/content/Schema/pre-aggregations.md
=> docs: Update docs for cube store release phase 1

DEPRECATION.md
**Check List**
N/A
This PR fixes minor typos in `DEPRECATION.md`.
=> docs: fix minor typos in DEPRECATION.md

packages/cubejs-schema-compiler/src/adapter/MssqlQuery.js, packages/cubejs-schema-compiler/test/integration/mssql/mssql-pre-aggregations.test.ts
**Check List**
https://github.com/cube-js/cube.js/issues/2237
=> fix(@cubejs-schema-compiler): Fix addInterval / subtractInterval for Mssql

rust/cubestore/src/bin/cubestored.rs
First sigint initiates a graceful shutdown.
After 3 sigints we kill the process.
=> fix(cubestore): attempt to exit gracefully on sigint (ctrl+c)

rust/cubestore/src/metastore/mod.rs, rust/cubestore/src/mysql/mod.rs, rust/cubestore/src/sys/malloc.rs, rust/cubestore/src/util/mod.rs, rust/cubestore/src/util/time_span.rs
In hopes to find places that cause slowdown.
=> chore(cubestore): warn if some operations run longer than expected

.github/workflows/push.yml, packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/src/jwk.ts, packages/cubejs-backend-shared/src/promises.ts, packages/cubejs-backend-shared/test/promises.test.ts, packages/cubejs-server-core/src/core/server.ts
=> feat: Fetch JWK in background only

docs/content/Configuration/Connecting-to-the-Database.md
=> docs: Document Heroku SSL issue

packages/cubejs-backend-shared/test/promises.test.ts, packages/cubejs-schema-compiler/package.json, packages/cubejs-schema-compiler/yarn.lock
Hello!
refs https://github.com/cube-js/cube.js/issues/2264
Thanks
=> fix(schema-compiler): Lock antlr4ts to 0.5.0-alpha.4, fix #2264

packages/cubejs-backend-shared/test/promises.test.ts
=> misc(tests): Move asyncMemoizeBackground tests to fake timers

docs/content/Auth/Overview.md, docs/content/Auth/Security-Context.md
Story details: https://app.clubhouse.io/cube-dev/story/201
=> docs(security): move Custom Authentication section to Overview page

.github/workflows/publish.yml, .github/workflows/push.yml, rust/bin/postinstall-skip-env.js, rust/package.json, rust/yarn.lock
=> fix(cubestore): post-install - compatbility with non bash env

docs/content/Auth/Overview.md
Story details: https://app.clubhouse.io/cube-dev/story/202
=> docs(security): re-order JWT/JWKS sections in Overview page

.github/workflows/birdbox.yml
=> misc(ci): Introduce Bird 📦

.github/workflows/birdbox.yml
=> misc(ci): Start birdboxes after completed release

docs/content/Auth/Overview.md
Story details: https://app.clubhouse.io/cube-dev/story/193
=> docs(security): add links to Auth0 and AWS Cognito guides

rust/Cargo.lock, rust/cubestore/src/queryplanner/query_executor.rs, rust/cubestore/src/queryplanner/serialized_plan.rs, rust/cubestore/src/sql/mod.rs, rust/cubestore/src/sys/malloc.rs
=> feat(cubestore): Merge aggregate

packages/cubejs-client-react/src/QueryBuilder.jsx
**Check List**
Broken off from #2196
In the React QueryBuilder, an issue I ran into was the interop between query.order and orderMembers. Whenever the query changed, orderMembers potentially needed to be updated, and every time orderMembers changed, the query might need to be updated. This relationship made reasoning about the various state changes difficult, and especially saving/restoring state and reloads.
I refactored the QueryBuilder so that orderMembers is calculated on demand in then render method based on the availableDimensions, availableMeasures, and query.order. Then, I changed updateOrder so that it just modified the query.order and sent it through the normal query update path. This makes query.order the single source of truth, and removes any difficulties with maintaining the …
=> Refactoring QueryBuilder orderMembers for better logic flow

packages/cubejs-cli/src/utils.ts, packages/cubejs-elasticsearch-driver/driver/index.d.ts, packages/cubejs-elasticsearch-driver/package.json
=> feat(elasticsearch-driver): Introduce typings

.gitignore, packages/cubejs-playground/tsconfig.json
Hello!
Broken release https://github.com/cube-js/cube.js/runs/2041942234
Thanks
=> misc: commit changes tsconfig.json

package.json, rust/js-wrapper/download.ts, rust/package.json, rust/yarn.lock, yarn.lock
=> fix(cubestore): Node.js 10 support, switched to cli-progress

.github/workflows/birdbox.yml, packages/cubejs-docker/birdbox-fixtures/postgresql.yml, packages/cubejs-docker/test/abstract-test-case.ts
=> misc(birdbox): test under alpine, allow to specify version

docs/content/Caching/Using-Pre-Aggregations.md, docs/content/Schema/pre-aggregations.md
**Check List**
N/A
Just some minor typo fixes, thanks!
=> Fix Typos and Broken Link in Docs

packages/cubejs-api-gateway/package.json, packages/cubejs-client-core/package.json, packages/cubejs-client-ws-transport/package.json, packages/cubejs-cubestore-driver/package.json, packages/cubejs-schema-compiler/package.json, packages/cubejs-server/package.json, packages/cubejs-serverless-aws/package.json, packages/cubejs-serverless-google/package.json, packages/cubejs-serverless/package.json, yarn.lock
=> misc: align dependencies to reduce size

.github/workflows/publish.yml, .github/workflows/push.yml
=> misc(ci): Use correct cache keys for jobs without matrix (node-version)

packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts, packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
=> feat: Improve error messages

packages/cubejs-schema-compiler/test/integration/mysql/MySqlDbRunner.js
=> misc: Use TEST_MYSQL_VERSION for MySQL version for schema-compiler tests

.github/workflows/birdbox.yml, tsconfig.json, yarn.lock
=> misc(bidrbox): skill cubestore post-install

docs/content/Schema/event-analytics.md
=> docs: add info box for Discourse

.github/workflows/push.yml, packages/cubejs-elasticsearch-driver/docker-compose.yml, packages/cubejs-elasticsearch-driver/driver/ElasticSearchDriver.js, packages/cubejs-elasticsearch-driver/driver/index.d.ts, packages/cubejs-elasticsearch-driver/package.json, packages/cubejs-elasticsearch-driver/test/ElasticSearchOpenDistro.integration.js, yarn.lock
=> feat(elasticsearch-driver): Support USERNAME, PASSWORD and SSL_*

packages/cubejs-client-core/package.json, packages/cubejs-client-core/src/ResultSet.js, yarn.lock
=> fix(playground): Cannot read property 'extendMoment' of undefined

packages/cubejs-schema-compiler/src/adapter/BaseFilter.js, packages/cubejs-schema-compiler/test/unit/base-query.test.ts, packages/cubejs-schema-compiler/test/unit/postgres-query.test.ts
=> fix: Expected one parameter but nothing found

docs/content/Auth/AWS-Cognito.md, docs/content/Auth/Auth0-Guide.md, docs/content/Auth/Overview.md, docs/content/Cube-Cloud/Configuration/Connecting-to-Databases.md, docs/content/Cube-Cloud/Configuration/Deployment-Env-Vars.md, docs/content/Cube-Cloud/Cube-IDE.md, docs/content/Cube-Cloud/Deploys.md, docs/content/Cube-Cloud/Index.md, docs/content/Cube-Cloud/Inspecting-Queries.md, docs/content/Cube-Cloud/Quickstart.md, docs/content/Cube.js-Introduction.md, docs/content/Schema/cohort-retention.md, docs/content/Schema/event-analytics.md, docs/static/styles/_code.scss, docs/static/styles/_layout.scss, docs/static/styles/_typography.scss, docs/static/styles/content.css
Story details: https://app.clubhouse.io/cube-dev/story/200
Callouts: https://deploy-preview-2355--cubejs-docs-staging.netlify.app/security/jwt/auth0
Code blocks: https://deploy-preview-2355--cubejs-docs-staging.netlify.app/config
Headings: https://deploy-preview-2355--cubejs-docs-staging.netlify.app/security/jwt/auth0#create-an-application-custom-claims
Images: https://deploy-preview-2355--cubejs-docs-staging.netlify.app/introduction
Wide links: https://deploy-preview-2355--cubejs-docs-staging.netlify.app/cloud
=> docs: add margins to headings, wide links, code blocks, images and callouts

CONTRIBUTING.md
=> misc: Drop lerna usage from CONTRIBUTING

packages/cubejs-docker/dev-alpine.Dockerfile, packages/cubejs-docker/dev.Dockerfile
=> fix(docker): Drop lerna bootstrap, because we migrated to yarn w

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/test/auth.test.ts, packages/cubejs-api-gateway/test/index.test.ts, packages/cubejs-api-gateway/test/utils.ts, packages/cubejs-server-core/src/core/server.ts, yarn.lock
=> feat: introduce GET /cubejs-system/v1/context

.github/actions/integration/clickhouse.sh, .github/actions/integration/druid.sh, .github/actions/integration/elasticsearch.sh, .github/actions/integration/mssql.sh, .github/actions/integration/mysql.sh, .github/actions/integration/postgres.sh, .github/actions/integration/prestodb.sh, .github/workflows/push.yml
=> misc(ci): Rework integration tests to matrix

package.json, rust/bin/postinstall-skip-env.js, yarn.lock
=> misc: small fixes

.github/actions/integration/clickhouse.sh, .github/actions/integration/druid.sh, .github/actions/integration/elasticsearch.sh, .github/actions/integration/mssql.sh, .github/actions/integration/mysql.sh, .github/actions/integration/postgres.sh, .github/actions/integration/prestodb.sh, packages/cubejs-druid-driver/docker-compose.yml, packages/cubejs-druid-driver/environment, packages/cubejs-druid-driver/package.json, packages/cubejs-druid-driver/src/DruidClient.ts, packages/cubejs-druid-driver/test/druid-driver.test.ts, yarn.lock
=> feat(druid-driver): Support Basic auth via username/passwd

docs/content/Deployment/Production-Checklist.md
Story details: https://app.clubhouse.io/cube-dev/story/227
=> Rename 'Configure JWKS' to 'Secure the deployment'

docs/content/Schema/Funnels.md, docs/content/Schema/active-users.md, docs/content/Schema/cohort-retention.md
=> Add info box for Discourse on Active Users page

packages/cubejs-cli/src/command/create.ts, packages/cubejs-jdbc-driver/driver/JDBCDriver.js
=> fix(cubejs-cli): Create - ability to select a specific JDBC driver

rust/Cargo.lock, rust/cubestore/Cargo.toml, rust/cubestore/src/metastore/index.rs, rust/cubestore/src/metastore/schema.rs, rust/cubestore/src/queryplanner/mod.rs, rust/cubestore/src/queryplanner/optimizations/distributed_partial_aggregate.rs, rust/cubestore/src/queryplanner/optimizations/mod.rs, rust/cubestore/src/queryplanner/optimizations/prefer_inplace_aggregates.rs, rust/cubestore/src/queryplanner/optimizations/rewrite_plan.rs, rust/cubestore/src/queryplanner/planning.rs, rust/cubestore/src/queryplanner/pretty_printers.rs, rust/cubestore/src/queryplanner/query_executor.rs, rust/cubestore/src/queryplanner/serialized_plan.rs, rust/cubestore/src/sql/mod.rs
This is a pretty big change, not intended to have any user-visible changes.
The goal is to simplify future optimizations and make them testable.
=> Refactor query planning, add tests

docs/content/Guides/Data-Blending.md
=> Add Discourse info box for data blending

README.md, docs/content/Examples.md
=> Add the Discourse link to the readme file

docs/content/Auth/Security-Context.md
Story details: https://app.clubhouse.io/cube-dev/story/181
=> docs(security): add mention of `COMPILE_CONTEXT` to Security Context page

packages/cubejs-client-core/index.d.ts
=> fix(@cubejs-client/ngx): wrong type reference

.github/actions/integration/mysql-aurora-serverless.sh, .github/workflows/push.yml, packages/cubejs-mysql-aurora-serverless-driver/docker-compose.yml, packages/cubejs-mysql-aurora-serverless-driver/driver/AuroraServerlessMySqlDriver.js, packages/cubejs-mysql-aurora-serverless-driver/driver/index.d.ts, packages/cubejs-mysql-aurora-serverless-driver/package.json, packages/cubejs-mysql-aurora-serverless-driver/test/AuroraServerlessMySqlDriver.integration.js, yarn.lock
=> misc(ci): Run integration tests for mysql-aurora-serverless

packages/cubejs-cubestore-driver/src/CubeStoreQuery.ts
=> fix(cubestore-driver): Drop limit for table names

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js, packages/cubejs-schema-compiler/test/integration/postgres/sub-query-dimensions.test.ts
=> fix: Allow using sub query dimensions in join conditions

rust/cubestore/src/metastore/mod.rs, rust/cubestore/src/queryplanner/optimizations/rewrite_plan.rs, rust/cubestore/src/queryplanner/planning.rs, rust/cubestore/src/sql/mod.rs
Should help reduce query times
=> fix(cubestore): use less read and write locks during planning

packages/cubejs-backend-shared/src/track.ts, packages/cubejs-server-core/src/core/server.ts, rust/js-wrapper/post-install.ts, yarn.lock
=> fix: Warning/skip Cube Store on unsupported platforms

rust/Cargo.lock, rust/cubestore/src/queryplanner/optimizations/prefer_inplace_aggregates.rs, rust/cubestore/src/queryplanner/pretty_printers.rs, rust/cubestore/src/sql/mod.rs
Now with tests for the important query.
=> fix(cubestore): choose inplace aggregate in more cases

packages/cubejs-server-core/src/core/server.ts, packages/cubejs-server-core/test/unit/index.test.ts
=> fix: this.logger is not a function. fix #2431

packages/cubejs-schema-compiler/package.json, yarn.lock
=> misc: Resolution field @types/ramda@0.27.34 is incompatible

packages/cubejs-server-core/src/core/server.ts
=> fix: Make requireCubeStoreDriver private (to make it internal in d.ts)

docs/content/Caching/Using-Pre-Aggregations.md
Story details: https://app.clubhouse.io/cube-dev/story/246
=> docs(caching): add Partitioning section to Using Pre-aggregations page

packages/cubejs-client-core/index.d.ts, packages/cubejs-client-core/src/ResultSet.js
**Check List**
This PR updates the types in @cubejs-client/core by  addressing the issue https://github.com/cube-js/cube.js/issues/589
=> Updated totalRow within ResultSet

packages/cubejs-backend-maven/.gitignore, packages/cubejs-backend-maven/LICENSE, packages/cubejs-backend-maven/README.md, packages/cubejs-backend-maven/bin/maven-resolve, packages/cubejs-backend-maven/package.json, packages/cubejs-backend-maven/src/index.ts, packages/cubejs-backend-maven/src/maven-resolve.ts, packages/cubejs-backend-maven/src/maven.ts, packages/cubejs-backend-maven/test/fixtures/generate-xml-1.xml, packages/cubejs-backend-maven/test/maven.test.ts, packages/cubejs-backend-maven/tsconfig.json, packages/cubejs-backend-shared/package.json, packages/cubejs-backend-shared/src/cli.ts, packages/cubejs-backend-shared/src/http-utils.ts, packages/cubejs-backend-shared/src/index.ts, packages/cubejs-cli/package.json, rust/bin/postinstall-skip-env.js, rust/js-wrapper/download.ts, rust/js-wrapper/post-install.ts, rust/js-wrapper/utils.ts, rust/package.json, tsconfig.json, yarn.lock
=> feat: Introduce @cubejs-backend/maven (maven deps resolver)

docs/src/components/Header/Desktop.tsx
=> Adding a Discourse button to docs page header

packages/cubejs-server-core/src/core/DevServer.ts, packages/cubejs-server-core/src/core/RefreshScheduler.ts, packages/cubejs-server-core/src/core/server.ts, packages/cubejs-server-core/test/unit/RefreshScheduler.test.ts, packages/cubejs-server/src/server.ts
=> feat: Allow saving state of a scheduled refresh for warmup operations

.github/workflows/publish.yml
=> misc(ci): Build release images for Cube Store

docs/content/Schema/pre-aggregations.md
Story details: https://app.clubhouse.io/cube-dev/story/288
=> docs(schema): add known limitations to using internal pre-aggregations

docs/content/Auth/Security-Context.md, docs/content/Developer-Tools/Developer-Playground.md
Story details: https://app.clubhouse.io/cube-dev/story/190
=> docs(devtools): add Editing the Security Context section to Developer Playground page

rust/js-wrapper/utils.ts
=> fix(cubestore): Detect gnu libc without warning

packages/cubejs-athena-driver/driver/AthenaDriver.js
=> fix(athena-driver): Use correct quoteIdentifier, fix #2363

docs/content/Schema/pre-aggregations.md
Story details: https://app.clubhouse.io/cube-dev/story/66
=> docs(schema): document `rollupJoin`

docs/content/Examples.md
Story details: https://app.clubhouse.io/cube-dev/story/293
=> Update Examples and Tutorials

packages/cubejs-server-core/src/core/RefreshScheduler.ts, packages/cubejs-server-core/test/unit/RefreshScheduler.test.ts
=> fix: Pre-aggregation warmup should wait for partitions to build

docs/content/Auth/Overview.md, docs/content/Cube-Cloud/Deploys.md, docs/content/Developer-Tools/Developer-Playground.md, docs/content/Guides/Many-to-Many-Relationship.md, docs/content/Guides/String-Time-Dimensions.md, docs/content/Guides/Subquery.md, docs/content/Schema/event-analytics.md, docs/content/Schema/types-and-formats.md
Story details: https://app.clubhouse.io/cube-dev/story/275
=> docs: replace mentions of Statsbot with Cube.js

docs/content/Caching/Using-Pre-Aggregations.md
Story details: https://app.clubhouse.io/cube-dev/story/392
=> docs(caching): fix broken link

docs/content/Examples.md
Story details: https://app.clubhouse.io/cube-dev/story/400
=> docs(examples): remove invalid example

docs/content/Cube.js-Backend/REST-API.md
Story details: https://app.clubhouse.io/cube-dev/story/411
=> docs(backend): fix typo in REST API docs

packages/cubejs-cli/src/templates.ts
=> fix(cli): Use binary instead of path in templates (Windows issue)

.github/workflows/birdbox.yml, packages/cubejs-testing/.gitignore, packages/cubejs-testing/package.json, packages/cubejs-testing/src/birdbox.ts, packages/cubejs-testing/src/db/db-runner.abstract.ts, packages/cubejs-testing/src/db/index.ts, packages/cubejs-testing/src/db/postgres.ts, packages/cubejs-testing/src/index.ts, packages/cubejs-testing/test/abstract-test-case.ts, packages/cubejs-testing/test/bin/cypress-birdbox.ts, packages/cubejs-testing/test/birdbox-postgresql-cubestore.test.ts, packages/cubejs-testing/test/birdbox-postgresql.test.ts, packages/cubejs-testing/test/cli-postgresql.test.ts, tsconfig.json, yarn.lock
=> misc(birdbox): Run birdbox on CLI

packages/cubejs-backend-shared/src/node-check.ts, packages/cubejs-server/bin/dev-server, packages/cubejs-server/bin/server, packages/cubejs-server/package.json, packages/cubejs-server/src/bin/dev-server.ts, packages/cubejs-server/src/bin/server.ts
=> feat: Check Node.js version in dev-server/server

docs/content/Caching/Using-Pre-Aggregations.md, docs/content/Deployment/Production-Checklist.md
Story details: https://app.clubhouse.io/cube-dev/story/242
=> docs(caching): add Running Cube Store in Production section to Using Pre-Aggregations

docs/content/Auth/Overview.md
Story details: https://app.clubhouse.io/cube-dev/story/182
=> docs(auth): document JWKS caching logic

docs/content/Configuration/Connecting-to-the-Database.md
Story details: https://app.clubhouse.io/cube-dev/story/378
=> docs(config): add MSSQL section to Connecting to the Database

docs/content/Cube-Cloud/Index.md
Story details: https://app.clubhouse.io/cube-dev/story/375
=> docs: add backlinks to Cube Store

packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts, packages/cubejs-query-orchestrator/src/orchestrator/QueryOrchestrator.ts, packages/cubejs-schema-compiler/src/adapter/PreAggregations.js, packages/cubejs-schema-compiler/test/integration/postgres/pre-aggregations-alias.test.ts
=> fix: sqlAlias on not partioned rollups

rust/cubestore/src/cluster/message.rs, rust/cubestore/src/cluster/mod.rs, rust/cubestore/src/cluster/transport.rs, rust/cubestore/src/config/mod.rs, rust/cubestore/src/lib.rs, rust/cubestore/src/queryplanner/mod.rs, rust/cubestore/src/queryplanner/optimizations/distributed_partial_aggregate.rs, rust/cubestore/src/queryplanner/planning.rs, rust/cubestore/src/queryplanner/query_executor.rs, rust/cubestore/src/queryplanner/topk/execute.rs, rust/cubestore/src/queryplanner/topk/mod.rs, rust/cubestore/src/queryplanner/topk/plan.rs, rust/cubestore/src/sql/mod.rs
This adds general infrastructure for streaming and enables it for top-k.
=> Stream from worker to router in top-k plans

docs/static/styles/_layout.scss
Story details: https://app.clubhouse.io/cube-dev/story/35
Thanks @cainaleaouk!
=> docs: fix strange glow on tab switcher

packages/cubejs-cli/src/command/create.ts
=> fix(cli): @ dependency not found

packages/cubejs-server/command/README.md, packages/cubejs-server/command/dev-server.ts, packages/cubejs-server/command/server.ts, packages/cubejs-server/package.json, packages/cubejs-server/tsconfig.json
=>  fix(server): Compatibility with CLI to run external commands

packages/cubejs-jdbc-driver/package.json, yarn.lock
=> misc: Make java deps as optional (to allow failture in development)

docs/content/Caching/Using-Pre-Aggregations.md, rust/README.md
PR supersedes https://github.com/cube-js/cube.js/pull/2425
Story details: https://app.clubhouse.io/cube-dev/story/277
=> docs(caching): document Cube Store partial MySQL protocol support

.github/workflows/push.yml, packages/cubejs-testing/birdbox-fixtures/postgresql-cubestore.yml, packages/cubejs-testing/birdbox-fixtures/postgresql.yml
=> misc(ci): Start testing docker images before release

rust/package.json, yarn.lock
=> fix(cubestore): installer - compability with windows. fix #2520

packages/cubejs-backend-shared/src/http-utils.ts, rust/js-wrapper/process.test.ts, rust/js-wrapper/process.ts, rust/package.json, yarn.lock
=> fix(cubestore): Something wrong with downloading Cube Store before running it.

packages/cubejs-cubestore-driver/package.json, packages/cubejs-cubestore-driver/src/CubeStoreDriver.ts, packages/cubejs-cubestore-driver/src/WebSocketConnection.ts, packages/cubejs-mysql-driver/driver/MySqlDriver.js, packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts, rust/cubestore/src/config/mod.rs, rust/cubestore/src/http/mod.rs, rust/cubestore/src/import/mod.rs, rust/cubestore/src/lib.rs, rust/cubestore/src/remotefs/mod.rs, rust/cubestore/src/sql/mod.rs, yarn.lock
=> feat: Mysql Cube Store streaming ingests

packages/cubejs-databricks-jdbc-driver/package.json, rust/package.json, yarn.lock
=> fix: post installers compatiblity with Windows #2520

examples/vue-query-builder/dashboard-app/public/index.html, packages/cubejs-client-core/index.d.ts, packages/cubejs-client-vue/src/QueryBuilder.js
=> fix(@cubejs-client/vue): make query reactive

.github/workflows/publish.yml, .github/workflows/rust.yml
=> misc(ci): Install upx from GitHub (instead of bintray)

packages/cubejs-docker/dev-alpine.Dockerfile, packages/cubejs-docker/dev.Dockerfile, packages/cubejs-docker/latest-alpine.Dockerfile, packages/cubejs-docker/latest.Dockerfile
=> fix(docker): Lock yarn, workaround for PATH & post-installers

.github/workflows/birdbox.yml, .github/workflows/push.yml, packages/cubejs-testing/.gitignore, packages/cubejs-testing/birdbox-fixtures/postgresql-cubestore.yml, packages/cubejs-testing/birdbox-fixtures/postgresql.yml, packages/cubejs-testing/birdbox-fixtures/postgresql/schema/Events.js, packages/cubejs-testing/birdbox-fixtures/postgresql/scripts/load.sh, packages/cubejs-testing/package.json, packages/cubejs-testing/src/birdbox.ts, packages/cubejs-testing/src/db/db-runner.abstract.ts, packages/cubejs-testing/src/db/postgres.ts, packages/cubejs-testing/test/__snapshots__/birdbox-postgresql-cubestore.test.ts.snap, packages/cubejs-testing/test/__snapshots__/birdbox-postgresql.test.ts.snap, packages/cubejs-testing/test/abstract-test-case.ts, packages/cubejs-testing/test/bin/download-dataset.ts, packages/cubejs-testing/test/bin/start-birdbox.ts, packages/cubejs-testing/test/bin/utils.ts, packages/cubejs-testing/test/snapshotResolver.js
=> misc: Load data for BirdBoxe(s)

docs/content/Cube.js-Frontend/@cubejs-client-vue.md, docs/yarn.lock
Story details: https://app.clubhouse.io/cube-dev/story/419
=> docs(vue): re-order `QueryBuilder` and `QueryRenderer` and add prop reference table

.github/workflows/push.yml, packages/cubejs-testing/package.json, packages/cubejs-testing/test/bin/cypress-birdbox.ts
=> misc: Start cypress on CI

packages/cubejs-backend-shared/src/type-helpers.ts, packages/cubejs-playground/src/pages/ConnectionWizard/ConnectionWizardPage.tsx, packages/cubejs-playground/src/utils.ts, packages/cubejs-query-orchestrator/src/driver/BaseDriver.js, packages/cubejs-server-core/src/core/DevServer.ts, packages/cubejs-server-core/src/core/server.ts
=> fix(playground): Safety test connection without reloading

packages/cubejs-databricks-jdbc-driver/package.json, packages/cubejs-docker/latest-alpine.Dockerfile, packages/cubejs-docker/latest.Dockerfile, rust/package.json
=> fix: post-install compatibility with yarn

.dockerignore, .github/workflows/push.yml, packages/cubejs-docker/dev-alpine.Dockerfile, packages/cubejs-docker/dev.Dockerfile, packages/cubejs-testing/test/bin/cypress-birdbox.ts
=> test: catch errors in cypress

packages/cubejs-dremio-driver/driver/DremioQuery.js
=> fix(dreamio-driver): Allow casting boolean/number/measure

packages/cubejs-dremio-driver/driver/DremioDriver.js
=> fix(dreamio-driver): Remove unexpected console.log

guides/react-dashboard/content/1_overview_and_analytics_backend.md
Added the `-L` flag to the `curl` command so it follows redirects.
=> examples(react-dashboard): fix incorrect `curl` command

packages/cubejs-dremio-driver/driver/DremioDriver.js, packages/cubejs-dremio-driver/package.json, yarn.lock
query  with sleep for 1s is too long ,  maybe needless  (we can use dremio `Data Reflections` for accelerate data query  )
=> feat(dreamio-driver): Improve polling, similar to BigQuery driver

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/test/auth.test.ts, packages/cubejs-api-gateway/test/index.test.ts
=> feat(api-gateway): Allow to throw CubejsHandlerError in checkAuth

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/test/index.test.ts
=> misc: Dont make BC for HTTP codes in checkAuth

docs/content/Configuration/Environment-Variables-Reference.md
Story details: https://app.clubhouse.io/cube-dev/story/432
=> docs(config): add environment variables for Cube Store

docs/content/Caching/Using-Pre-Aggregations.md
Story details: https://app.clubhouse.io/cube-dev/story/429
=> docs(caching): add Scaling and Storage sections to Using Pre-Aggregations

docs/content/Configuration/Overview.md
Story details: https://app.clubhouse.io/cube-dev/story/434
=> docs(config): add Cube Store to list of Development Mode features

packages/cubejs-query-orchestrator/src/orchestrator/QueryQueue.js
Hello!
refs https://github.com/cube-js/cube.js/issues/2574
Thanks
=> fix: QueryQueue - broken queuing on any error (TimeoutError: ResourceRequest timed out)

packages/cubejs-testing/test/abstract-test-case.ts
=> test(e2e): Fix, use WS transport in WS tests

rust/cubestore/src/cluster/mod.rs, rust/cubestore/src/config/mod.rs, rust/cubestore/src/metastore/chunks.rs, rust/cubestore/src/metastore/mod.rs, rust/cubestore/src/metastore/partition.rs, rust/cubestore/src/queryplanner/query_executor.rs, rust/cubestore/src/scheduler/mod.rs
The warmup should result in lower latencies upon actual queries.
Configurable via `CUBESTORE_STARTUP_WARMUP` environment variable.
=> fix(cubestore): download data files on worker startup

packages/cubejs-server/src/server/container.ts
=> feat(server): Handle Ctrl + C (SIGINT) in Docker

rust/Cargo.lock, rust/cubestore-sql-tests/src/tests.rs
=> fix(cubestore): deploy datafusion fix, add test for failing top-k

packages/cubejs-cli/src/command/generate.ts, packages/cubejs-query-orchestrator/src/driver/BaseDriver.js, packages/cubejs-server-core/src/core/server.ts
=> fix: protect multiple driver creation for one datasource on startup

packages/cubejs-docker/dev-alpine.Dockerfile, packages/cubejs-docker/dev.Dockerfile, packages/cubejs-docker/latest-alpine.Dockerfile, packages/cubejs-docker/latest.Dockerfile
Hello!
refs https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#2021-04-06-version-12221-erbium-lts-mylesborins
Thanks
=> feat(docker): Upgrade Node.js to 12.22.1 [security]

docs/content/Configuration/Environment-Variables-Reference.md
Story details: https://app.clubhouse.io/cube-dev/story/461
=> docs(config): add environment variables for Cube.js - Cube Store integration

guides/react-pivot-table/content/1_overview.md, guides/react-pivot-table/content/3_data.md, guides/react-pivot-table/content/4_app.md, guides/react-pivot-table/content/5_explanation.md
=> Minor typo fix/edit

packages/cubejs-cubestore-driver/src/WebSocketConnection.ts, packages/cubejs-server-core/src/core/server.ts
=> fix(cubestore-driver): Ping connection only when it's OPEN

rust/cubestore/src/queryplanner/topk/execute.rs
First scan the nodes required to make progress on the top candidate.
Improves performance when the top values are missing on some of the nodes.
We need to scan these nodes until the end, but we now do no unnecessary scans of
other nodes that already produced the top values.
=> fix(cubestore): make top-k scan less batches

packages/cubejs-playground/src/components/CachePane.tsx
=> fix(@cubejs-client/playground): cache pane crash

packages/cubejs-backend-shared/src/env.ts
=> fix: Show warning for deprecated variables only once

DEPRECATION.md, docs/content/Schema/cube.md, docs/yarn.lock
=> docs: various fixes

packages/cubejs-backend-shared/src/env.ts, packages/cubejs-cli/src/command/create.ts, packages/cubejs-cubestore-driver/src/CubeStoreDriver.ts, packages/cubejs-docker/package.json, packages/cubejs-dremio-driver/driver/DremioDriver.js, packages/cubejs-server-core/src/core/server.ts, packages/cubejs-server-core/src/core/types.ts, packages/cubejs-server/package.json, packages/cubejs-serverless/Handlers.js, yarn.lock
=> feat: Use Cube Store as default EXTERNAL_DB, prefix variables

docs/content/Getting-Started/Getting-Started-Docker-Compose.md, docs/content/Getting-Started/Getting-Started-Docker.md
Story details: https://app.clubhouse.io/cube-dev/story/493
=> docs(getting-started): add Loom recordings to Docker and Docker Compose guides

docs/content/Caching/Using-Pre-Aggregations.md
Story details: https://app.clubhouse.io/cube-dev/story/486
=> docs(caching): improve Cube Store setup examples

.github/actions/integration/mysql.sh, packages/cubejs-mysql-driver/package.json, packages/cubejs-mysql-driver/test/MySqlDriver.test.js, packages/cubejs-query-orchestrator/src/driver/BaseDriver.js, packages/cubejs-schema-compiler/test/integration/mysql/MySqlDbRunner.js, yarn.lock
Hello!
https://github.com/cube-js/cube.js/issues/2441
Thanks
=> fix(query-orchestrator): tableColumnTypes - compatibility for MySQL 8

packages/cubejs-mysql-driver/package.json, packages/cubejs-mysql-driver/test/MySqlDriver.test.js, packages/cubejs-mysql-driver/test/MySqlDriverPool.test.js, packages/cubejs-mysql-driver/test/mysql.db.runner.js, packages/cubejs-server/bin/dev-server, packages/cubejs-testing/src/db/index.ts, packages/cubejs-testing/src/db/mysql.ts, yarn.lock
=> fix: cubejs-dev-server

packages/cubejs-schema-compiler/src/adapter/MongoBiQuery.js, packages/cubejs-schema-compiler/src/adapter/SqliteQuery.js, packages/cubejs-sqlite-driver/driver/SqliteDriver.js
=> fix(sqlite-driver): TypeError: moment is not a function

packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts, packages/cubejs-query-orchestrator/src/orchestrator/QueryCache.ts, packages/cubejs-query-orchestrator/src/orchestrator/QueryOrchestrator.ts, packages/cubejs-query-orchestrator/src/orchestrator/QueryQueue.js, packages/cubejs-server-core/src/core/optionsValidate.ts, rust/Cargo.lock, rust/cubestore-sql-tests/src/lib.rs, rust/cubestore-sql-tests/src/tests.rs, rust/cubestore-sql-tests/tests/cluster.rs, rust/cubestore/Cargo.toml, rust/cubestore/src/cluster/transport.rs, rust/cubestore/src/http/mod.rs, rust/cubestore/src/lib.rs, rust/cubestore/src/sql/cache.rs, rust/cubestore/src/sql/mod.rs
=> feat: Move External Cache And Queue serving to Cube Store

packages/cubejs-api-gateway/src/interfaces.ts, packages/cubejs-server-core/src/core/optionsValidate.ts, packages/cubejs-server-core/test/unit/index.test.ts
=> feat: Strict validatation for configuration

packages/cubejs-schema-compiler/src/adapter/ClickHouseQuery.js
**Check List**
#2717
Reference to ES/RedShift adapter to fix in Clickhouse adapter
=> fix #2717 support ungrouped tag for Clickhouse schema compiler

.github/workflows/publish.yml, .github/workflows/rust.yml
=> fix: Compress archive (was empty) with Cube Store for Windows (msvc)

rust/js-wrapper/utils.ts
=> feat(cubestore): Use MSVC build for Windows

packages/cubejs-server-core/src/core/optionsValidate.ts, packages/cubejs-server-core/test/unit/index.test.ts, packages/cubejs-server/src/server/container.ts, packages/cubejs-server/src/server/typescript-compiler.ts
=> fix: Add missing validators for configuration values

docs/content/Caching/Running-in-Production.md, docs/content/Getting-Started/Getting-Started-Docker-Compose.md, docs/content/Getting-Started/Getting-Started-Docker.md
Story details: https://app.clubhouse.io/cube-dev/story/559
=> docs: recommend using WSL2 when using Windows 10 as host OS

docs/content/Cube-Cloud/Cube-IDE.md
Story details: https://app.clubhouse.io/cube-dev/story/534
=> docs(cloud): fix typos

packages/cubejs-backend-cloud/src/cloud.ts, packages/cubejs-schema-compiler/package.json, packages/cubejs-schema-compiler/src/adapter/BaseTimeDimension.js, packages/cubejs-schema-compiler/test/unit/base-query.test.ts, yarn.lock
=> fix(schema-compiler): Time-series query with minute granularity

docs/content/Configuration/Config.md
Updates to the config.md readme file to put some example in `extendContext` option and adding custom values to `RequestContext`.
=> Documentation for extendContext option

docs/content/Caching/Running-in-Production.md
Story details: https://app.clubhouse.io/cube-dev/story/561
=> docs(caching): add information about securing Cube Store

packages/cubejs-server-core/src/core/server.ts
=> feat: Start Cube Store on startup in devMode for official images

packages/cubejs-backend-shared/src/env.ts, packages/cubejs-cli/src/templates.ts, packages/cubejs-cli/test/templates.test.ts, packages/cubejs-schema-compiler/src/adapter/PreAggregations.js, packages/cubejs-server-core/src/core/DevServer.ts, packages/cubejs-server-core/src/core/server.ts
=> feat: Enable external pre-aggregations by default for new users

packages/cubejs-client-core/index.d.ts
=> fix(@cubejs-client/core): Meta types fixes

packages/cubejs-server/src/server/container.ts
=> feat: Replace diagnostic error for devPackages to warning

docs/src/components/Layout/MainMenu.tsx
Story details: https://app.clubhouse.io/cube-dev/story/570
Thanks @cainaleaouk for digging in :raised_hands:
=> docs: fix bug preventing use of common category names across OSS and Cloud

packages/cubejs-client-core/src/ResultSet.js
=> fix(@cubejs-client/core): compareDateRange pivot fix

.github/workflows/publish.yml, .github/workflows/rust-master.yml, .github/workflows/rust.yml
=> ci: Fix issue with cross

rust/Cargo.lock, rust/cubestore-sql-tests/src/tests.rs, rust/cubestore/src/metastore/mod.rs, rust/cubestore/src/metastore/table.rs, rust/cubestore/src/queryplanner/planning.rs, rust/cubestore/src/sql/mod.rs, rust/cubestore/src/store/compaction.rs, rust/cubestore/src/store/mod.rs
=> feat(cubestore): Allow to query tables only when they imported and ready

packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts
=> fix: Optimize high load Cube Store serve track: do not use Redis while fetching pre-aggregation tables

docs/content/Cube-Cloud/Configuration/Connecting-to-Databases.md, docs/content/Cube-Cloud/Configuration/Deployment-Env-Vars.md, docs/content/Cube-Cloud/Configuration/Deployment-Types.md, docs/src/components/Layout/MainMenu.tsx
Story details: https://app.clubhouse.io/cube-dev/story/529
=> docs(cloud): rename Configuring Cube Cloud to Configuration to match OSS docs

rust/cubestore/src/queryplanner/partition_filter.rs
In presence of OR expressions that hit the accuracy limits.
=> fix(cubestore): improve partition filter accuracy

docs/content/Getting-Started/Getting-Started-Docker-Compose.md
**Check List**
—
—
Fixing what looks like a mistype in the `docker-compose.yml`.
=> chore(docs): Remove unnecessary port 3000 from Docker Compose docs

docs/content/Getting-Started/Getting-Started-Docker-Compose.md
=> chore(docs): Revert port 3000 and update comments

packages/cubejs-backend-shared/src/env.ts
=> fix: CUBEJS_JWT_KEY - allow string

packages/cubejs-postgres-driver/package.json, packages/cubejs-snowflake-driver/package.json
=> fix: Dont publish source files for snowflake/postgresql

packages/cubejs-cubestore-driver/src/CubeStoreDriver.ts, packages/cubejs-snowflake-driver/src/SnowflakeDriver.ts
=> fix(snowflake-driver): Handle UNLOAD for empty tables

packages/cubejs-schema-compiler/src/compiler/CubeSymbols.js, packages/cubejs-schema-compiler/test/unit/schema.test.ts
=> feat: Make rollup default for preAggregation.type

packages/cubejs-client-react/src/QueryBuilder.jsx
=> fix(@cubejs-client/playground): order reset

docs/content/Configuration/Connecting-to-the-Database.md
Story details: https://app.clubhouse.io/cube-dev/story/573
=> docs(config): document `CUBEJS_DB_BQ_EXPORT_BUCKET`

package.json, packages/cubejs-playground/package.json, patches/@types+styled-components+5.1.9.patch, yarn.lock
=> fix: Drop NodeJs namespace from @types/styled-components
