cube-js/cube

- packages/cubejs-query-orchestrator/src/driver/BaseDriver.js
> fix(postgresql-driver): Map bool/float4/float8 to generic type, use bigint for int8

- docs/content/Configuration/Config.md
Followup from https://github.com/cube-js/cube.js/pull/1422#issuecomment-848264959
> docs(config): update type of `orchestratorOptions`

- packages/cubejs-bigquery-driver/package.json
- packages/cubejs-bigquery-driver/src/BigQueryDriver.ts
> fix(bigquery-driver): Broken package

- packages/cubejs-client-core/index.d.ts
> fix(@cubejs-client/core): decompose type

- packages/cubejs-mysql-aurora-serverless-driver/driver/AuroraServerlessMySqlDriver.js
- packages/cubejs-mysql-driver/driver/MySqlDriver.js
> fix(mysql/aurora-mysql): Unexpected index creation in loop

- examples/vue-query-builder/dashboard-app/src/pages/explore/components/FilterComponent.vue
> examples: vue query builder multi fiter fix

- packages/cubejs-schema-compiler/src/adapter/SnowflakeQuery.js
- packages/cubejs-snowflake-driver/src/SnowflakeDriver.ts
> feat(snowflake-driver): Support HLL

- rust/cubehll/src/instance.rs
We produced invalid encoding in sparse representation before.
Cardinality was correct on sparse representation and wrong after
conversion to dense representation.
> fix(cubestore): fix encoding of sparse HLL imported from Snowflake

- package.json
- packages/cubejs-docker/package.json
- packages/cubejs-elasticsearch-driver/package.json
- yarn.lock
>  feat(docker): Install redshift-driver

- packages/cubejs-server-core/src/core/FileRepository.ts
- packages/cubejs-server-core/src/core/RefreshScheduler.ts
- packages/cubejs-server-core/test/unit/RefreshScheduler.test.ts
> fix: Pass securityContext to contextSymbols in refresh scheduler

- rust/cubestore-sql-tests/src/tests.rs
- rust/cubestore/src/sql/mod.rs
To allow create table with the same name later.
> fix(cubestore): clean up metastore if create table fails, fix #2880

- docs/content/Configuration/Connecting-to-the-Database.md
basic elasticsearch usage directions
took me some time to figure out the env variables needed for elasticsearch, so added them to the documentation
> docs(config): add Elasticsearch instructions to Connecting to the Database

- docs/gatsby-config.js
- docs/package.json
- docs/yarn.lock
Story details: https://app.clubhouse.io/cube-dev/story/494
> docs: use version number from Lerna

- rust/Cross.toml
- rust/cross/README.md
- rust/cross/aarch64-unknown-linux-gnu.Dockerfile
- rust/cross/x86_64-unknown-linux-gnu-buster.Dockerfile
- rust/cross/x86_64-unknown-linux-gnu-stretch.Dockerfile
- rust/cross/x86_64-unknown-linux-musl.Dockerfile
> feat(cross): Upgrade, use llvm/clang 9

- packages/cubejs-backend-shared/package.json
- packages/cubejs-backend-shared/src/http-utils.ts
- packages/cubejs-backend-shared/src/index.ts
- packages/cubejs-backend-shared/src/proxy.ts
- packages/cubejs-templates/package.json
- packages/cubejs-templates/src/utils.ts
- rust/js-wrapper/download.ts
- tsconfig.json
- yarn.lock
Hello!
Before this PR Cube Store installer didn't use proxy settings from NPM, which will be a problem for users who are behind the proxy.
Thanks
> feat(cubestore): Use NPM's proxy settings in post-installer

- packages/cubejs-backend-shared/src/promises.ts
- packages/cubejs-backend-shared/src/type-helpers.ts
- packages/cubejs-query-orchestrator/src/driver/driver.interface.ts
- packages/cubejs-query-orchestrator/src/orchestrator/AsyncRedisClient.ts
- packages/cubejs-query-orchestrator/src/orchestrator/LocalCacheDriver.ts
- packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts
- packages/cubejs-query-orchestrator/src/orchestrator/QueryCache.ts
- packages/cubejs-query-orchestrator/src/orchestrator/RedisCacheDriver.ts
- packages/cubejs-query-orchestrator/src/orchestrator/cache-driver.interface.ts
- packages/cubejs-query-orchestrator/test/integration/QueryCacheRedis.test.ts
- packages/cubejs-query-orchestrator/test/integration/QueryQueueRedis.test.ts
- packages/cubejs-query-orchestrator/test/unit/QueryCache.abstract.ts
- packages/cubejs-query-orchestrator/test/unit/QueryCache.test.ts
- packages/cubejs-query-orchestrator/test/unit/QueryQueue.abstract.ts
- packages/cubejs-query-orchestrator/test/unit/QueryQueue.test.ts
> feat: Introduce locks for dropOrphanedTables (concurrency bug)

- packages/cubejs-query-orchestrator/src/orchestrator/DriverFactory.ts
- packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts
- packages/cubejs-query-orchestrator/src/orchestrator/index.ts
- packages/cubejs-server-core/src/core/OrchestratorApi.ts
- packages/cubejs-server-core/src/core/server.ts
- packages/cubejs-server-core/src/core/types.ts
> feat: skipExternalCacheAndQueue for Cube Store

- rust/cubestore/src/cluster/message.rs
Do not panic and produce slightly more readable errors.
Special-case the common misconfiguration causing CubeJS to send an
HTTP message to CubeStore.
> chore(cubestore): handle some invalid metastore messages

- docs/content/Deployment/Overview.md
Story details: https://app.clubhouse.io/cube-dev/story/688
> docs(deployment): fix invalid dependency ordering in Overview example

- docs/content/Configuration/Overview.md
Story details: https://app.clubhouse.io/cube-dev/story/670
> docs(config): mention expected mount paths for Docker image

- rust/cubestore/src/metastore/mod.rs
- rust/cubestore/src/queryplanner/mod.rs
This was the bottleneck on some production metastores. Some requests
still need to read metastore, but hopefully those are rare enough that
this fix will remove the bottleneck in practice.
Particular changes:
- add cache for access to metastore,
- avoid allocations when creating `MetaStoreSchemaProvider`.
> fix(cubestore): optimize access to table metainformation

- packages/cubejs-cli/src/templates.ts
- packages/cubejs-schema-compiler/src/scaffolding/ScaffoldingTemplate.js
- packages/cubejs-schema-compiler/src/scaffolding/ValueWithComments.ts
- packages/cubejs-schema-compiler/test/unit/scaffolding-schema.test.ts
> feat: Write preAggregations block in schema generation

- packages/cubejs-backend-shared/src/env.ts
- packages/cubejs-snowflake-driver/package.json
- packages/cubejs-snowflake-driver/src/SnowflakeDriver.ts
- yarn.lock
Hello!
Introduce support for UNLOAD from Snowflake to Google Cloud Storage.
Thanks
> feat(snowflake-driver): Support UNLOAD to GCS

- rust/cubestore/src/remotefs/gcs.rs
The new names follow CubeJS conventions:
- `CUBESTORE_GCP_CREDENTIALS` for base64-encoded credentials,
- `CUBESTORE_GCP_KEY_FILE` for path to a file with credentials.
CubeStore still accepts older variants with deprecation warning.
> fix(cubestore): finalize GCP configuration variable names

- docs/content/Configuration/Config.md
- docs/content/Configuration/Multitenancy-Setup.md
- packages/cubejs-api-gateway/src/gateway.ts
- packages/cubejs-api-gateway/src/interfaces.ts
- packages/cubejs-api-gateway/test/index.test.ts
- packages/cubejs-server-core/src/core/optionsValidate.ts
- packages/cubejs-server-core/src/core/server.ts
- packages/cubejs-server-core/src/core/types.ts
> feat: Rename queryTransformer to queryRewrite (with compatibility)

- packages/cubejs-clickhouse-driver/.gitignore
- packages/cubejs-clickhouse-driver/driver/ClickHouseDriver.js
- packages/cubejs-clickhouse-driver/index.js
- packages/cubejs-clickhouse-driver/package.json
- packages/cubejs-clickhouse-driver/src/ClickHouseDriver.ts
- packages/cubejs-clickhouse-driver/src/HydrationStream.ts
- packages/cubejs-clickhouse-driver/src/index.ts
- packages/cubejs-clickhouse-driver/test/ClickHouseDriverTest.js
- packages/cubejs-clickhouse-driver/tsconfig.json
- packages/cubejs-query-orchestrator/src/driver/driver.interface.ts
- tsconfig.json
- yarn.lock
> feat(clickhouse-driver): Streaming / Type Ingestion / TS

- packages/cubejs-server-core/src/core/server.ts
- packages/cubejs-server-core/src/core/types.ts
> fix: TypeError: oldLogger is not a function, fix #2940

- packages/cubejs-mysql-driver/driver/MySqlDriver.js
- packages/cubejs-mysql-driver/driver/index.d.ts
- packages/cubejs-postgres-driver/src/PostgresDriver.ts
- packages/cubejs-redshift-driver/src/RedshiftDriver.ts
> feat: Make MySQL/PostgreSQL readOnly by default

- packages/cubejs-elasticsearch-driver/driver/ElasticSearchDriver.js
- packages/cubejs-mongobi-driver/src/MongoBIDriver.ts
> fix(elasticsearch-driver): Make readOnly

- packages/cubejs-api-gateway/src/gateway.ts
- packages/cubejs-api-gateway/test/index.test.ts
**Check List**
Fix debug api, support authInfo
> fix(api-gateway): debug, handle authInfo for Meta API

- packages/cubejs-backend-shared/src/env.ts
- packages/cubejs-server-core/src/core/server.ts
> misc: Remove reference to dead env variable

- packages/cubejs-mssql-driver/driver/MSSqlDriver.js
> fix(mssql-driver): Support Case Sensitive collation

- packages/cubejs-api-gateway/src/gateway.ts
- packages/cubejs-query-orchestrator/src/orchestrator/QueryOrchestrator.ts
**Check List**
Skip empty pre-aggregations for debug API
> fix: Skip empty pre-aggregations for debug API

- rust/cubestore/src/remotefs/s3.rs
Configurable via `CUBESTORE_AWS_CREDS_REFRESH_EVERY_MINS` env var.
`0` means do not refresh.
By default, refreshes every 3 hours.
This is a temporary workaround until credentials store expiration time
or `rust-s3` handles this automatically.
> fix(cubestore): refresh AWS credentials on timer, fix #2946

- packages/cubejs-schema-compiler/src/adapter/MssqlQuery.js
- packages/cubejs-schema-compiler/test/integration/mssql/mssql-pre-aggregations.test.ts
> feat(mssql-driver): Use DATETIME2 instead of DATETIME

- packages/cubejs-schema-compiler/src/compiler/CubeEvaluator.js
- packages/cubejs-schema-compiler/src/compiler/CubeValidator.js
- packages/cubejs-schema-compiler/src/compiler/transpilers/CubePropContextTranspiler.ts
- packages/cubejs-schema-compiler/test/integration/postgres/pre-aggregations-time.test.ts
- packages/cubejs-schema-compiler/test/unit/schema.test.ts
> fix: Use timeDimension without s on the end (feature api)

- docs/content/Schema/cube.md
- packages/cubejs-schema-compiler/package.json
- packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
- packages/cubejs-schema-compiler/test/unit/base-query.test.ts
- yarn.lock
> test: standard cron syntax

- packages/cubejs-query-orchestrator/src/orchestrator/QueryOrchestrator.ts
- packages/cubejs-server-core/src/core/OrchestratorApi.ts
- packages/cubejs-server-core/src/core/server.ts
- packages/cubejs-server-core/src/core/types.ts
- packages/cubejs-server-core/test/unit/index.test.ts
> misc: Up code quality

- rust/cubestore/src/lib.rs
This helps to diagnose problems.
> chore(cubestore): collect backtraces of all errors

- packages/cubejs-mongobi-driver/src/MySQLType.ts
- packages/cubejs-mysql-driver/driver/MySqlDriver.js
> fix(mysql/mongobi): Map NEWDECIMAL type to decimal

- packages/cubejs-mysql-driver/driver/MySqlDriver.js
- packages/cubejs-mysql-driver/package.json
- packages/cubejs-mysql-driver/test/MySqlDriver.test.js
- yarn.lock
> fix(mysql-driver): Empty results with streaming

- packages/cubejs-clickhouse-driver/package.json
- packages/cubejs-clickhouse-driver/src/ClickHouseDriver.ts
- packages/cubejs-clickhouse-driver/src/HydrationStream.ts
- packages/cubejs-clickhouse-driver/test/ClickHouseDriver.test.ts
- yarn.lock
> fix(clickhouse-driver): Correct support for Decimal

- package.json
- yarn.lock
> misc: Lock rc-tree (node.js 10 compatiblity)

- rust/Cargo.lock
See datafusion commit for the actual fix.
> fix(cubestore): merge operation on unsorted data

- packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
- packages/cubejs-schema-compiler/test/unit/base-query.test.ts
> fix: Unexpected refreshKey refresh (earlier then expected)

- packages/cubejs-backend-shared/src/env.ts
- packages/cubejs-server-core/src/core/server.ts
- packages/cubejs-server-core/test/unit/index.test.ts
> feat: Introduce CUBEJS_REFRESH_WORKER and CUBEJS_ROLLUP_ONLY

- packages/cubejs-query-orchestrator/src/orchestrator/QueryOrchestrator.ts
**Check List**
Incorrect passing params for fetch preview pre-aggregation data, debug API
> fix(query-orchestrator): Incorrect passing params for fetch preview pre-aggregation data, debug API

- packages/cubejs-schema-compiler/src/compiler/CubeEvaluator.js
- packages/cubejs-schema-compiler/src/compiler/CubeValidator.js
- packages/cubejs-schema-compiler/test/unit/schema.test.ts
> feat: Rename refreshRangeStart/End to buildRangeStart/End

- packages/cubejs-backend-shared/src/env.ts
- packages/cubejs-backend-shared/test/env.test.ts
- packages/cubejs-server-core/src/core/server.ts
- packages/cubejs-server-core/test/unit/index.test.ts
> fix: Priorities for REFRESH_WORKER/SCHEDULED_REFRESH/SCHEDULED_REFRESH_TIMER

- package.json
- packages/cubejs-api-gateway/package.json
- yarn.lock
> chore(api-gateway): Remove unused cron-parser, fix #3060

- packages/cubejs-postgres-driver/src/PostgresDriver.ts
> fix(postgres-driver): Support mapping for bpchar

- rust/cubestore/src/sql/cache.rs
This can happen if entry got flushed from LRU cache.
We hit this every time if LRU cache size is set to 0.
Probably never happened in practice.
> chore(cubestore): handle failure to set result in LRU cache

- packages/cubejs-postgres-driver/package.json
- packages/cubejs-postgres-driver/src/PostgresDriver.ts
- packages/cubejs-postgres-driver/src/QueryStream.ts
- packages/cubejs-postgres-driver/test/PostgresDriver.test.ts
- yarn.lock
> fix(postgres-driver): Catch error in streaming

- rust/cubestore-sql-tests/src/tests.rs
- rust/cubestore/src/queryplanner/query_executor.rs
Turns out `take` has a bug with empty lists. Replace it with `MutableArrayData`.
The latter is more efficient anyway.
IIUC, the only place it can hit us is 'count distinct', its accumulator uses
lists for states. If add support for array types, we will need to fix `take`.
> fix(cubestore): fix panic 'Unexpected accumulator state List([NULL])'

- rust/Cargo.lock
- rust/cubestore/src/lib.rs
> chore(cubestore): export some helpers, update DataFusion

- docs/content/Caching/Using-Pre-Aggregations.md
Story details: https://app.clubhouse.io/cube-dev/story/747
> docs(caching): improve batching and export bucket copy

- docs/content/Deployment/Production-Checklist.md
Story details: https://app.clubhouse.io/cube-dev/story/669
> docs(deployment): add Export Bucket section to Production Checklist

- docs/content/Deployment/Platform-Serverless-AWS.md
Story details: https://app.clubhouse.io/cube-dev/story/663
> docs(deployment): create Deploy with Serverless on AWS page

- docs/src/components/Layout/MainMenu.tsx
**Check List**
I think it's more logical to have the `introduction` section before `getting started`. 
We also have a reference section under Data Schema. I wonder if it's better to have the reference in the `introduction` since a lot of newcomers aren't familiar with terms like dimension/measure?
> Update Cube.js docs menu order

- docs/content/Schema/cube.md
> docs(cubes): typo fix

- rust/cubestore-sql-tests/src/tests.rs
- rust/cubestore/src/queryplanner/mod.rs
- rust/cubestore/src/queryplanner/udfs.rs
> feat(cubestore): Introduce support for DATE_ADD

- packages/cubejs-client-core/index.d.ts
- packages/cubejs-client-ngx/src/query-builder/query-members.ts
**Check List**
#3083
Update index.d.ts so that filter field in Query supports logical and/or in TypeScript.
> fix(@cubejs-client/core): incorrect types for logical and/or in query filters (#3083)

- .github/actions/integration/cubestore.sh
- .github/workflows/push.yml
- packages/cubejs-cubestore-driver/package.json
- packages/cubejs-cubestore-driver/test/CubeStoreDriver.js
- packages/cubejs-cubestore-driver/test/CubeStoreQuery.test.ts
- packages/cubejs-query-orchestrator/src/orchestrator/RedisPool.ts
- packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
- packages/cubejs-testing/package.json
- packages/cubejs-testing/src/db/cubestore.ts
- packages/cubejs-testing/src/db/index.ts
- packages/cubejs-testing/src/testing/index.ts
- packages/cubejs-testing/src/testing/query-test.abstract.ts
- packages/cubejs-testing/src/utils.ts
- tsconfig.json
- yarn.lock
> test(cubestore-driver): Correct dialect for refresh keys

- docs/content/Deployment/Platform-Serverless-Google.md
- docs/content/Getting-Started/Getting-Started-Nodejs.md
- docs/static/styles/_layout.scss
Story details: https://app.clubhouse.io/cube-dev/story/811
> Create Deployment with Serverless to Google Cloud page

- docs/content/Schema/Dynamic-Schema-Creation.md
- docs/content/Schema/Funnels.md
- docs/content/Schema/pre-aggregations.md
Story details: https://app.clubhouse.io/cube-dev/story/752
> docs(caching): replace `originalSql` copy and examples with `rollup`

- docs/content/Schema/pre-aggregations.md
Story details: https://app.clubhouse.io/cube-dev/story/806
> docs(schema): rename `refreshRange*` to `buildRange*`

- docs/content/Deployment/Platform-Cube-Cloud.md
Story details: https://app.clubhouse.io/cube-dev/story/850
> docs(deployment): create new Cube Cloud page

- docs/content/Deployment/Platform-Docker.md
- docs/content/Deployment/Platform-Serverless-AWS.md
- docs/content/Deployment/Platform-Serverless-Google.md
Story details: https://app.clubhouse.io/cube-dev/story/864
> docs(deployment): remove 'Deploy with' prefix from Platform titles

- packages/cubejs-snowflake-driver/src/SnowflakeDriver.ts
> fix(snowflake-driver): Restart connection if it's not up

- packages/cubejs-backend-shared/src/env.ts
- packages/cubejs-query-orchestrator/src/orchestrator/QueryOrchestrator.ts
**Check List**
Use experimental flag for pre-aggregations queue events bus, debug API
> fix: Use experimental flag for pre-aggregations queue events bus, debug API

- rust/bin/cubestore-dev
- rust/bin/post-install
> fix(cubestore): Installer (bad path)

- package.json
- packages/cubejs-athena-driver/driver/AthenaDriver.js
- packages/cubejs-athena-driver/package.json
- yarn.lock
> feat(athena-driver): Use AWS-SDK v3 (modular)

- docs/src/components/EventBanner/index.tsx
> fix(docs): top banner animation and utm

- docs/content/Deployment/Platform-Cube-Cloud.md
Story details: https://app.clubhouse.io/cube-dev/story/865
> docs(deployment): remove Node prerequisite for Cube Cloud deployment

- docs/content/Caching/Getting-Started-Pre-Aggregations.md
- docs/content/Caching/Overview.md
- docs/content/Caching/Running-in-Production.md
- docs/content/Caching/Using-Pre-Aggregations.md
Story details: https://app.clubhouse.io/cube-dev/story/883
> docs(caching): add callout for Pre-Aggregations Workshop

- packages/cubejs-client-core/src/ResultSet.js
- packages/cubejs-client-core/src/tests/data-blending.test.js
- packages/cubejs-client-core/src/tests/fixtures/datablending/load-responses.json
- packages/cubejs-client-core/src/utils.js
> fix(@cubejs-client/core): data blending without date range

- packages/cubejs-api-gateway/src/query.js
- packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts
- packages/cubejs-server-core/src/core/RefreshScheduler.ts
**Check List**
Pass metadata into query and log events
> chore: Pass metadata into pre-aggregations queries and log events, Debug API

- packages/cubejs-backend-shared/src/time.ts
- packages/cubejs-cubestore-driver/src/CubeStoreDriver.ts
- packages/cubejs-prestodb-driver/docker-compose.yml
- packages/cubejs-prestodb-driver/test/PrestoDriverTest.js
- packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts
> fix: Optimize timestamp formatting and table names loading for large partition range serving

- docs/content/Configuration/Environment-Variables-Reference.md
- packages/cubejs-serverless-aws/index.js
- packages/cubejs-serverless-google/index.js
**Check List**
https://github.com/cube-js/cube.js/issues/1014
Add explicit environment variable for SNS or Pub/Sub topic name.
> feat: add env var for SNS || Pub/Sub topic

- packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
- packages/cubejs-schema-compiler/src/adapter/BigqueryQuery.js
- packages/cubejs-schema-compiler/src/adapter/MssqlQuery.js
- packages/cubejs-schema-compiler/src/adapter/PreAggregations.js
- packages/cubejs-schema-compiler/test/integration/postgres/pre-aggregations.test.ts
> feat: Rolling window rollup support

- docs/src/components/EventBanner/index.tsx
> docs: fix banner time range

- docs/content/Deployment/Production-Checklist.md
> docs: Update production checklist after changes to the roles mgmt

- docs/content/Caching/Using-Pre-Aggregations.md
- docs/content/Schema/Funnels.md
Story details: https://app.clubhouse.io/cube-dev/story/893
> docs(caching): add time partitioning information to Using Pre-Aggregations page

- docs/content/Auth/Security-Context.md
- docs/content/Configuration/Multitenancy-Setup.md
- docs/content/Cube.js-Backend/REST-API.md
- docs/content/Schema/Reference/cube.md
Story details: https://app.clubhouse.io/cube-dev/story/728
> Promote `queryRewrite` over `SECURITY_CONTEXT`

- rust/cubestore/src/config/mod.rs
> fix(cubestore): improve errors for env var parse failures

- docs/content/Examples.md
Numerous changes bringing this page up-to-date with the current state of things.
> docs: update Examples & Tutorials page

- packages/cubejs-cubestore-driver/src/CubeStoreQuery.ts
- packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
- packages/cubejs-schema-compiler/src/adapter/PreAggregations.js
> fix: Support rolling `countDistinctApprox` rollups

- docs/src/components/EventBanner/index.tsx
> fix(docs): change top banner api url & catch network error

- examples/d3-dashboard/dashboard-app/.env.production
- examples/hacktoberfest/dashboard/src/index.js
- examples/material-ui-dashboard/dashboard-app/.env.production
- examples/react-dashboard/dashboard-app/src/App.js
> fix(examples): change invalid api url

- docs/content/Caching/Getting-Started-Pre-Aggregations.md
- docs/content/Caching/Using-Pre-Aggregations.md
- docs/content/Configuration/Config.md
- docs/content/Configuration/Overview.md
- docs/content/Deployment/Production-Checklist.md
- docs/content/Guides/Incremental-Pre-Aggregations.md
- docs/content/Schema/Funnels.md
- docs/content/Schema/Reference/pre-aggregations.md
- docs/content/Schema/Reference/types-and-formats.md
- packages/cubejs-playground/src/components/RollupDesigner/RollupDesigner.tsx
Story details: https://app.clubhouse.io/cube-dev/story/852
> docs(schema): ensure Pre-Aggregation ToC is consistent with other reference documentation

- packages/cubejs-api-gateway/src/gateway.ts
- packages/cubejs-api-gateway/test/mocks.ts
- packages/cubejs-query-orchestrator/src/orchestrator/QueryOrchestrator.ts
- packages/cubejs-query-orchestrator/test/unit/QueryOrchestrator.test.js
**Check List**
Added expected structure version for each partition, Debug API
> chore: Added expected structure version for each partition, Debug API

- docs/content/Caching/Getting-Started-Pre-Aggregations.md
- docs/content/Caching/Overview.md
- docs/content/Caching/Using-Pre-Aggregations.md
- docs/content/Schema/Reference/schema-execution-environment.md
Story details: https://app.clubhouse.io/cube-dev/story/888
> docs: remove `*Reference` from pre-aggregation definitions

- docs/content/Cube.js-Frontend/@cubejs-client-react.md
- docs/content/Cube.js-Frontend/@cubejs-client-vue.md
> docs(frontend): change invalid API URLs

- docs/content/Configuration/Connecting-to-the-Database.md
- docs/content/Examples-Tutorials-Recipes/Enable-SSL-Connections-To-Database.md
- docs/content/Examples-Tutorials-Recipes/Examples.md
Story details: https://app.clubhouse.io/cube-dev/story/923
> docs(examples): add new recipe for enabling SSL connections to the database

- packages/cubejs-athena-driver/driver/AthenaDriver.js
- packages/cubejs-athena-driver/driver/index.d.ts
Hello!
Athena produces files in S3 bucket for any query, let's use API call to test connection instead of real query.
Thanks
> feat(athena-driver): Use getWorkGroup instead of SELECT 1 for testConnection

- docs/content/Schema/Reference/cube.md
Story details: https://app.clubhouse.io/cube-dev/story/936
> docs(schema): fix broken link to Security Context page

- docs/content/Examples-Tutorials-Recipes/Enable-SSL-Connections-To-Database.md
- docs/content/Examples-Tutorials-Recipes/Examples.md
Story details: https://app.clubhouse.io/cube-dev/story/938
> docs(examples): rename 'Security' to 'Data Sources'

- docs/content/Auth/Security-Context.md
**Check List**
- [ X ] Docs have been added / updated if required
closes #3230
Include return statement in Security-Context.md queryRewrite example
Adding a return statement to the queryRewrite example to follow the correct implementation procedure.
> docs: include return statement in `queryRewrite` example

- packages/cubejs-playground/src/components/PlaygroundQueryBuilder/QueryBuilderContainer.tsx
- packages/cubejs-playground/src/components/QueryTabs/QueryTabs.tsx
- packages/cubejs-playground/src/pages/Explore/ExplorePage.tsx
- packages/cubejs-playground/src/playground/cloud/CloudProvider.tsx
- packages/cubejs-playground/src/playground/components/QueryBuilder.tsx
Closes #3232
Note: we've added the `onTabChange` callback
> fix(@cubejs-client/playground): query param change on tab change

- packages/cubejs-postgres-driver/src/PostgresDriver.ts
> feat(postgres-driver): Load UD types from pg_types for type detection

- .github/workflows/birdbox.yml
- package.json
- packages/cubejs-testing/birdbox-fixtures/postgresql-cubestore.yml
- packages/cubejs-testing/birdbox-fixtures/postgresql.yml
- packages/cubejs-testing/src/birdbox.ts
- yarn.lock
Hello!
There is a regression in test containers and it's why our e2e tests were crashed. I tried to find a problem under the hood, but it's problematic, let's lock test containers to the stable version for now.
Thanks
> test(e2e): Fix crash for postgresql-cubestore

- packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts
**Check List**
Reset preAggregationStartEndQueries into expand function
> chore(query-orchestrator): Reset preAggregationStartEndQueries in expand function

- .github/workflows/publish.yml
- .github/workflows/push.yml
> bugfix(build): added regex replace for emojis in github repo metadata

- packages/cubejs-server-core/src/core/RefreshScheduler.ts
**Check List**
Skip expand partitions for unused pre-aggregations
> fix(server-core): Skip expand partitions for unused pre-aggregations

- packages/cubejs-postgres-driver/src/PostgresDriver.ts
- packages/cubejs-redshift-driver/src/RedshiftDriver.ts
> fix(redshift-driver): Dont load user defined types

- docs/content/Schema/Fundamentals/Concepts.md
Story details: https://app.clubhouse.io/cube-dev/story/784
> docs(schema): create new Concepts page under new Fundamentals section

- packages/cubejs-playground/src/components/Header/RunOnCubeCloud.tsx
> spelling edit

- docs/content/Examples-Tutorials-Recipes/Examples.md
- docs/content/Schema/Advanced/Code-Reusability-Export-and-Import.md
- docs/content/Schema/Advanced/Code-Reusability-Extending-Cubes.md
- docs/content/Schema/Advanced/Data-Blending.md
- docs/content/Schema/Advanced/Dynamic-Schema-Creation.md
- docs/content/Schema/Advanced/Polymorphic-Cubes.md
Story details: https://app.clubhouse.io/cube-dev/story/758
> docs(schema): ensure Advanced pages are under Advanced section

- docs/content/Caching/Getting-Started-Pre-Aggregations.md
- docs/content/Caching/Overview.md
- docs/content/Caching/Using-Pre-Aggregations.md
- docs/content/Schema/Advanced/Dynamic-Schema-Creation.md
- docs/content/Schema/Reference/pre-aggregations.md
Story details: https://app.clubhouse.io/cube-dev/story/738
> docs: remove unused/unnecessary values from examples

- docs/content/Schema/Advanced/Code-Reusability-Export-and-Import.md
- docs/content/Schema/Advanced/Code-Reusability-Extending-Cubes.md
- docs/content/Schema/Advanced/Data-Blending.md
- docs/content/Schema/Advanced/Dynamic-Schema-Creation.md
- docs/content/Schema/Advanced/Polymorphic-Cubes.md
- docs/content/Schema/Fundamentals/Concepts.md
- docs/content/Schema/Reference/cube.md
- docs/content/Schema/Reference/dimensions.md
- docs/content/Schema/Reference/joins.md
- docs/content/Schema/Reference/measures.md
- docs/content/Schema/Reference/pre-aggregations.md
- docs/content/Schema/Reference/schema-execution-environment.md
- docs/content/Schema/Reference/segments.md
- docs/content/Schema/Reference/types-and-formats.md
Story details: https://app.clubhouse.io/cube-dev/story/963
> docs(schema): fix main menu ordering

- docs/content/Caching/Overview.md
- docs/content/Caching/Using-Pre-Aggregations.md
- docs/content/Schema/Reference/pre-aggregations.md
Story details: https://app.clubhouse.io/cube-dev/story/882
> docs(schema): document using `every` and `sql` in `refreshKey` together

- packages/cubejs-oracle-driver/driver/OracleDriver.js
> correction of oracle port definition

- docs/content/Configuration/Databases/AWS-Athena.md
- docs/content/Configuration/Environment-Variables-Reference.md
- packages/cubejs-athena-driver/driver/AthenaDriver.js
**Check List**
Add configuration to define the name of the workgroup in which the query is being started
> feat(athena-driver): add environment variable to define the Athena workgroup

- examples/bigquery-public-datasets/docker-compose.yml
- examples/clickhouse-dashboard/docker-compose.yml
- examples/multi-tenant-analytics/docker-compose.yml
- examples/react-muze/docker-compose.yml
- examples/react-pivot-table/docker-compose.yml
- packages/cubejs-cli/src/templates.ts
- packages/cubejs-docker/README.md
- rust/README.md
**Check List**
Update erroneous reference to Developer Playground when speaking about Dashboard app port 3000.
> chore: Update 3000 ports

- packages/cubejs-client-core/src/index.js
> fix(@cubejs-client/core): prevent redundant auth updates

- docs/content/Schema/Reference/pre-aggregations.md
https://github.com/cube-js/cube.js/releases/tag/v0.28.24
> docs(Time dimensions): Support quarter granularity

- docs/content/Caching/Using-Pre-Aggregations.md
> docs: Remove garbage collection from using pre-aggs

- docs/content/Caching/Using-Pre-Aggregations.md
> docs: Remove read only section drom using pre-aggs

- docs/content/Caching/Using-Pre-Aggregations.md
> docs: Remove background refresh from using pre-aggs

- docs/content/Caching/Using-Pre-Aggregations.md
> docs: Update using pre-aggs -> rollup only mode

- examples/helm-charts/README.md
> Create a new folder for helm charts

- examples/helm-charts/cubejs/Chart.yaml
- examples/helm-charts/cubejs/README.md
- examples/helm-charts/cubejs/templates/common-env.tpl
- examples/helm-charts/cubejs/values.yaml
- examples/helm-charts/cubestore/Chart.yaml
- examples/helm-charts/cubestore/README.md
- examples/helm-charts/cubestore/templates/router/statefulset.yaml
- examples/helm-charts/cubestore/values.yaml
- Update to cube v0.28.28
- Add liveness and readiness probe for cubestore router
- Add missing CUBEJS_ROLLUP_ONLY config
- Add missing cubestore port env vars
- Fix spreadConstraints default value
> feat(helm-charts): Update to version v0.28.28

- docs/content/Schema/Reference/pre-aggregations.md
Story details: https://app.clubhouse.io/cube-dev/story/1039
> docs(schema): add blurb about `refreshKey` being evaluated on a per-partition basis

- docs/content/Caching/Using-Pre-Aggregations.md
> docs: Update Using Pre-Aggs -> Partitioning

- docs/content/Deployment/Overview.md
- docs/content/Deployment/Platform-Cube-Cloud.md
- docs/content/Deployment/Platform-Kubernetes.md
- docs/content/Deployment/Platform-Serverless-AWS.md
- docs/content/Deployment/Platform-Serverless-Google.md
- docs/content/Deployment/Production-Checklist.md
Story details: https://app.clubhouse.io/cube-dev/story/1038
> docs(deployment): add Kubernetes to Overview page and fix menu order

- docs/content/Caching/Using-Pre-Aggregations.md
Story details: https://app.clubhouse.io/cube-dev/story/939
> docs(caching): document how to inspect pre-aggregations in Cube Store with MySQL

- examples/helm-charts/cubejs/README.md
- examples/helm-charts/cubejs/templates/common-env.tpl
- examples/helm-charts/cubejs/templates/workers/deployment.yaml
- examples/helm-charts/cubejs/values.yaml
- Add global.apiSecretFromSecret value
- Fix worker deployment naming
> fix(helm-charts): Add global.apiSecretFromSecret value and fix worker deployment naming

- docs/build-netlify.sh
- docs/static/styles/index.module.scss
> docs: fix fonts load

- packages/cubejs-cubestore-driver/src/CubeStoreQuery.ts
- packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts
- packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
- packages/cubejs-schema-compiler/src/adapter/PreAggregations.js
- packages/cubejs-schema-compiler/test/integration/postgres/BaseDbRunner.ts
> fix: HLL Rolling window query fails

- .github/workflows/publish.yml
> misc: Build cubestore:non-avx (without AVX)

- docs/content/Schema/Reference/cube.mdx
- docs/content/Schema/Reference/dimensions.mdx
- docs/content/Schema/Reference/joins.mdx
- docs/content/Schema/Reference/measures.mdx
- docs/content/Schema/Reference/pre-aggregations.mdx
- docs/content/Schema/Reference/segments.md
Story details: https://app.clubhouse.io/cube-dev/story/896
> docs: ensure all Data Schema reference pages have consistent table of contents

- examples/helm-charts/cube-stack/.gitignore
- examples/helm-charts/cube-stack/.helmignore
- examples/helm-charts/cube-stack/Chart.lock
- examples/helm-charts/cube-stack/Chart.yaml
- examples/helm-charts/cube-stack/README.md
- examples/helm-charts/cube-stack/values.yaml
- examples/helm-charts/cubejs/README.md
- examples/helm-charts/cubejs/templates/common-env.tpl
- examples/helm-charts/cubejs/templates/master/deployment.yaml
- examples/helm-charts/cubejs/templates/workers/deployment.yaml
- examples/helm-charts/cubejs/values.yaml
- examples/helm-charts/cubestore/README.md
- examples/helm-charts/cubestore/templates/common-env.tpl
- examples/helm-charts/cubestore/values.yaml
**Check List**
https://github.com/cube-js/cube.js/issues/3337
> Add cube-stack Helm chart

- examples/helm-charts/cubejs/Chart.yaml
- examples/helm-charts/cubejs/README.md
- examples/helm-charts/cubejs/templates/master/deployment.yaml
- examples/helm-charts/cubejs/templates/workers/deployment.yaml
- examples/helm-charts/cubejs/values.yaml
- examples/helm-charts/cubestore/Chart.yaml
- examples/helm-charts/cubestore/README.md
- examples/helm-charts/cubestore/templates/router/statefulset.yaml
- examples/helm-charts/cubestore/values.yaml
Fix live/ready probe path and expose options
> fix(helm-charts): Fix live/ready probe path and expose options

- docs/env/development.js
- docs/static/styles/_tables.scss
Story details: https://app.clubhouse.io/cube-dev/story/1044
> docs: fix issue with table overflow

- docs/content/Schema/Reference/joins.mdx
Story details: https://app.clubhouse.io/cube-dev/story/1049
> docs(schema): fix broken link

- docs/content/Configuration/Config.mdx
> fix(docs): h4 headers extra id params

- packages/cubejs-api-gateway/src/gateway.ts
- packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts
- packages/cubejs-query-orchestrator/src/orchestrator/QueryOrchestrator.ts
- packages/cubejs-server-core/src/core/OrchestratorApi.ts
- packages/cubejs-server-core/src/core/RefreshScheduler.ts
**Check List**
Handle "rollup only" mode for pre-aggregation preview data query, Debug API
> fix: Handle "rollup only" mode for pre-aggregation preview data query, Debug API

- docs/content/Caching/Getting-Started-Pre-Aggregations.md
- docs/content/Schema/Reference/pre-aggregations.mdx
- packages/cubejs-api-gateway/src/gateway.ts
- packages/cubejs-playground/src/components/RollupDesigner/RollupDesigner.tsx
- packages/cubejs-playground/src/pages/ConnectionWizard/ConnectionWizardPage.tsx
- packages/cubejs-playground/src/pages/ConnectionWizard/components/ConnectionTest.tsx
- packages/cubejs-playground/src/pages/Schema/SchemaPage.tsx
- packages/cubejs-query-orchestrator/src/driver/BaseDriver.js
Story details: https://app.clubhouse.io/cube-dev/story/996
> docs: remove dead links from Caching documentation

- packages/cubejs-docker/dev.Dockerfile
> chore: Reduce dev docker image export layer time

- docs/content/Examples-Tutorials-Recipes/Multiple-Data-Sources-With-Same-Schema.md
> Fix the 404 error for a source code link in a recipe

- packages/cubejs-snowflake-driver/src/SnowflakeDriver.ts
> fix(@cubejs-backend/snowflake-driver): ReferenceError host is not defined

- packages/cubejs-client-react/index.d.ts
- packages/cubejs-client-react/src/hooks/cube-fetch.js
- packages/cubejs-client-react/src/hooks/cube-meta.js
- packages/cubejs-client-react/src/index.js
- packages/cubejs-playground/src/components/ChartRenderer/ChartRenderer.tsx
- packages/cubejs-playground/src/components/PlaygroundQueryBuilder/components/PlaygroundQueryBuilder.tsx
> feat(@cubejs-client/react): useCubeMeta hook

- docs/src/components/FeedbackBlock/FeedbackForm.tsx
- docs/src/components/FeedbackBlock/index.tsx
> fix(docs): feedback block empty message

- docs/src/components/Layout/ScrollMenu.tsx
> fix(website): side menu unique id

- docs/gatsby-config.js
- docs/package.json
- docs/src/templates/DocTemplate.tsx
- docs/static/styles/math.scss
- docs/yarn.lock
> fix(docs): formulas rendering in MDX

- rust/Cargo.lock
- rust/cubestore-sql-tests/src/tests.rs
- rust/cubestore/Cargo.toml
Case-insensitive version of LIKE.
> feat(cubestore): ILIKE operator

- examples/data-warehouse-performance-benchmarks/bigquery/bq-api.js
- examples/data-warehouse-performance-benchmarks/bigquery/bq-queries.js
- examples/data-warehouse-performance-benchmarks/bigquery/cube-api.js
- examples/data-warehouse-performance-benchmarks/bigquery/cube-queries.js
- examples/data-warehouse-performance-benchmarks/bigquery/k6-bq.js
- examples/data-warehouse-performance-benchmarks/bigquery/k6-cube-cloud.js
- examples/data-warehouse-performance-benchmarks/bigquery/k6-cube-local.js
- examples/data-warehouse-performance-benchmarks/bigquery/package.json
- examples/data-warehouse-performance-benchmarks/bigquery/readme.md
- examples/data-warehouse-performance-benchmarks/bigquery/yarn.lock
**Check List**
Updated Data Warehouse load tests.
> examples(dw-benchmarks): Added randomized queries

- packages/cubejs-client-core/index.d.ts
- packages/cubejs-client-react/index.d.ts
- packages/cubejs-client-react/src/hooks/dry-run.js
- packages/cubejs-client-react/src/utils.js
- packages/cubejs-playground/src/ChartContainer.tsx
- packages/cubejs-playground/src/components/PlaygroundQueryBuilder/QueryBuilderContainer.tsx
- packages/cubejs-playground/src/components/PlaygroundQueryBuilder/components/PreAggregationStatus.tsx
- packages/cubejs-playground/src/components/QueryTabs/QueryTabs.tsx
- packages/cubejs-playground/src/components/RollupDesigner/Context.tsx
- packages/cubejs-playground/src/components/RollupDesigner/RollupDesigner.tsx
- packages/cubejs-playground/src/components/RollupDesigner/components/Cubes.tsx
- packages/cubejs-playground/src/components/RollupDesigner/components/RollupDesignerModal.tsx
- packages/cubejs-playground/src/components/RollupDesigner/index.ts
- packages/cubejs-playground/src/components/RollupDesigner/utils.ts
- packages/cubejs-playground/src/index.tsx
- packages/cubejs-playground/src/pages/Explore/ExplorePage.tsx
- packages/cubejs-playground/src/playground/index.ts
Design Rollups without running a query
> feat(playground): add rollup button

- packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts
- packages/cubejs-query-orchestrator/src/orchestrator/QueryOrchestrator.ts
**Check List**
Wrong passing data source for partition range loader
> fix(query-orchestrator): Wrong passing data source for partition range loader, debug API

- docs/src/components/Headers/MyH2.tsx
- docs/src/components/Headers/MyH3.tsx
- docs/src/components/Headers/ScrollSpyH2.tsx
- docs/src/components/Headers/ScrollSpyH3.tsx
- docs/src/templates/DocTemplate.tsx
> chore(docs): transform content headers to links

- rust/cubestore/src/table/parquet.rs
All tables with HyperLogLog columns are affected. If the tables were
large enough for compaction to run, the data in those columns is
corrupted and cannot be recovered. Drop and rebuild those tables via
CubeJS.
> fix(cubestore): invalid data after compaction of binary columns

- packages/cubejs-postgres-driver/src/PostgresDriver.ts
Hello!
```
Error: Unable to detect type for field "@parser" with dataTypeID: 1009
at PostgresDriver.getPostgresTypeForField (/Users/mbir/Projects/Lava/cubejs/node_modules/@cubejs-backend/postgres-driver/src/PostgresDriver.ts:132:11)
at Object.PostgresDriver.getTypeParser (/Users/mbir/Projects/Lava/cubejs/node_modules/@cubejs-backend/postgres-driver/src/PostgresDriver.ts:107:29)
at Result.addFields (/Users/mbir/Projects/Lava/cubejs/node_modules/pg/lib/result.js:92:40)
at Query.handleRowDescription (/Users/mbir/Projects/Lava/cubejs/node_modules/pg/lib/query.js:75:18)
at Client._handleRowDescription (/Users/mbir/Projects/Lava/cubejs/node_modules/pg/lib/client.js:340:22)
at Connection.emit (node:events:394:28)
at /Users/mbir/Projects/Lava/cubejs/node_modules/pg/lib/connection.js:114:12
at …
```
> fix(postgres-driver): Unable to detect type for field "@parser"

- docs/src/components/Layout/MainMenu.tsx
- docs/static/styles/_layout.scss
Story details: https://app.shortcut.com/cube-dev/story/1080
> docs: fix menu truncation

- docs/content/Configuration/Multitenancy-Setup.mdx
- docs/src/pages/index.tsx
> docs: add callout for multitenancy workshop

- packages/cubejs-schema-compiler/src/adapter/PreAggregations.js
- packages/cubejs-schema-compiler/test/unit/pre-agg-by-filter-match.test.ts
check segments when matching pre-aggregations
**Check List**
> check segments when matching pre-aggregations

- .github/workflows/publish.yml
- .github/workflows/rust.yml
> ci: Fix Cube Store build on Windows

- rust/cubesql/src/compile/engine/context.rs
- rust/cubesql/src/compile/engine/mod.rs
- rust/cubesql/src/compile/engine/udf.rs
- rust/cubesql/src/compile/mod.rs
- rust/cubesql/src/mysql/dataframe.rs
- rust/cubesql/src/mysql/mod.rs
> feat(cubesql): Introduce version(), db() function in Query Engine

- packages/cubejs-server-core/src/core/RefreshScheduler.ts
**Check List**
Prevent mutation pre-aggregation objects, debug API
> fix: Prevent mutation pre-aggregation objects, debug API

- rust/cubesql/src/mysql/dataframe.rs
> fix(cubesql): MYSQL_TYPE_STRING for Booleans was null

- packages/cubejs-api-gateway/openspec.yml
- rust/cubeclient/README.md
> feat: Introduce OpenSpec for REST API

- rust/cubesql/src/compile/mod.rs
- rust/cubesql/src/mysql/mod.rs
> feat(cubesql): Execute SHOW DATABASES from AST

- docs/content/Caching/Using-Pre-Aggregations.mdx
- docs/content/Configuration/Databases/AWS-Athena.mdx
- docs/content/Configuration/Databases/AWS-Redshift.mdx
- docs/content/Configuration/Databases/ClickHouse.md
- docs/content/Configuration/Databases/Google-BigQuery.mdx
- docs/content/Configuration/Databases/MS-SQL.mdx
- docs/content/Configuration/Databases/MongoDB.mdx
- docs/content/Configuration/Databases/MySQL.mdx
- docs/content/Configuration/Databases/Postgres.mdx
- docs/content/Configuration/Databases/Snowflake.mdx
Story details: https://app.shortcut.com/cube-dev/story/1127
> docs(caching): add links from each database page to Pre-Aggregations Build-Time Strategies

- rust/Cargo.lock
- rust/cubestore-sql-tests/src/tests.rs
- rust/cubestore/Cargo.toml
- rust/cubestore/src/metastore/index.rs
- rust/cubestore/src/metastore/mod.rs
- rust/cubestore/src/metastore/multi_index.rs
- rust/cubestore/src/sql/mod.rs
- rust/cubestore/src/store/compaction.rs
> Syntax to drop partitioned index, bugfixes and improvements

- docs/src/components/Layout/index.tsx
- docs/static/styles/_layout.scss
Story details: https://app.shortcut.com/cube-dev/story/1137
> docs: fix framework switcher positioning

- packages/cubejs-api-gateway/src/gateway.ts
- packages/cubejs-api-gateway/src/query.js
- packages/cubejs-server-core/src/core/server.ts
- packages/cubejs-testing/birdbox-fixtures/postgresql/schema/Orders.js
- packages/cubejs-testing/birdbox-fixtures/postgresql/single/cube.js
- packages/cubejs-testing/package.json
- packages/cubejs-testing/src/birdbox.ts
- packages/cubejs-testing/test/abstract-test-case.ts
- packages/cubejs-testing/test/cli-postgresql.test.ts
> fix: `TypeError: Cannot read property 'joins' of null` in case of queryRewrite returns empty query

- rust/cubestore/src/cluster/mod.rs
- rust/cubestore/src/metastore/mod.rs
- rust/cubestore/src/queryplanner/info_schema/info_schema_schemata.rs
- rust/cubestore/src/queryplanner/info_schema/info_schema_tables.rs
- rust/cubestore/src/queryplanner/info_schema/mod.rs
- rust/cubestore/src/queryplanner/info_schema/system_chunks.rs
- rust/cubestore/src/queryplanner/info_schema/system_indexes.rs
- rust/cubestore/src/queryplanner/info_schema/system_jobs.rs
- rust/cubestore/src/queryplanner/info_schema/system_partitions.rs
- rust/cubestore/src/queryplanner/info_schema/system_tables.rs
- rust/cubestore/src/queryplanner/mod.rs
- rust/cubestore/src/queryplanner/serialized_plan.rs
- rust/cubestore/src/remotefs/queue.rs
- rust/cubestore/src/scheduler/mod.rs
- rust/cubestore/src/sql/mod.rs
- rust/cubestore/src/sql/parser.rs
- rust/cubestore/src/store/compaction.rs
> feat(cubestore): System tables and commands for debugging

- docs/content/Caching/Using-Pre-Aggregations.mdx
Story details: https://app.shortcut.com/cube-dev/story/1094
> docs(caching): improve copy for Pre-Aggregation Build Optimizations

- docs/content/Cube.js-Backend/Query-Format.md
Story details: https://app.shortcut.com/cube-dev/story/1100
> docs(backend): fix incorrect information about boolean logical operators in filters

- docs/content/Deployment/Platform-Docker.mdx
- docs/content/Deployment/Platform-Kubernetes.mdx
- docs/src/utils/parseHref.ts
- examples/kubernetes/cluster/ingress.yaml
Story details: https://app.shortcut.com/cube-dev/story/1114
> docs(deployment): use different local directory for each Cube Store instance

- docs/content/Configuration/Databases/AWS-Athena.mdx
- docs/content/Configuration/Databases/AWS-Redshift.mdx
- docs/content/Configuration/Databases/ClickHouse.md
- docs/content/Configuration/Databases/Google-BigQuery.mdx
- docs/content/Configuration/Databases/MS-SQL.mdx
- docs/content/Configuration/Databases/MongoDB.mdx
- docs/content/Configuration/Databases/MySQL.mdx
- docs/content/Configuration/Databases/Postgres.mdx
- docs/content/Configuration/Databases/Presto.md
- docs/content/Configuration/Databases/Snowflake.mdx
Story details: https://app.shortcut.com/cube-dev/story/973
> docs(config): add information about `countDistinctApprox` for each supported database

- docs/content/Caching/Overview.mdx
- docs/content/Cube-Cloud/Index.mdx
- docs/content/Deployment/Platform-Cube-Cloud.mdx
- docs/content/Developer-Tools/Developer-Playground.mdx
Story details: https://app.shortcut.com/cube-dev/story/1154
> docs: remove Cube Cloud early access copy

- rust/cubestore-sql-tests/src/tests.rs
- rust/cubestore/src/metastore/mod.rs
- rust/cubestore/src/metastore/partition.rs
- rust/cubestore/src/queryplanner/planning.rs
- rust/cubestore/src/queryplanner/query_executor.rs
- rust/cubestore/src/queryplanner/serialized_plan.rs
- rust/cubestore/src/scheduler/mod.rs
The work is around planning and query distribution onto workers.
> Fixes and tests for partitioned indices

- .github/workflows/push-native.yml
- packages/cubejs-backend-native/src/auth.rs
- packages/cubejs-backend-native/src/channel.rs
- packages/cubejs-backend-native/src/config.rs
- packages/cubejs-backend-native/src/lib.rs
- rust/cubesql/src/compile/mod.rs
- rust/cubesql/src/config/injection.rs
- rust/cubesql/src/config/mod.rs
- rust/cubesql/src/lib.rs
- rust/cubesql/src/mysql/mod.rs
> chore: Check clippy/fmt for cubesql/native

- packages/cubejs-backend-native/Cargo.lock
- rust/Cargo.lock
- rust/cubesql/Cargo.toml
- rust/cubesql/src/compile/engine/udf.rs
- rust/cubesql/src/compile/mod.rs
- rust/cubesql/src/config/injection.rs
- rust/cubesql/src/mysql/mod.rs
Hello!
https://www.youtube.com/watch?v=X-Tk7-Koj48
Thanks
> feat: Improve compatibility with real MySQL server 

- package.json
- rust/cubesql/src/compile/context.rs
- rust/cubesql/src/compile/mod.rs
- yarn.lock
> fix(cubesql): Support identifier escaping in h/m/s granularaties

- .github/workflows/publish.yml
- packages/cubejs-backend-native/package.json
> ci: Add autoretry for artifact uploading

- rust/Cargo.lock
- rust/cubestore-sql-tests/src/tests.rs
Only tests here, see the arrow commit for the actual fix.
Fixes #3661.
> fix(cubestore): 'int64decimal has no natural order'

- docs/content/Examples-Tutorials-Recipes/Examples.md
**Check List**
Added a link to https://cube.dev/blog/building-an-internal-dashboard-with-retool-and-cube/ in the tutorials section under Examples.
> docs(examples): add link in tutorials section

- packages/cubejs-schema-compiler/src/adapter/ClickHouseQuery.js
- packages/cubejs-schema-compiler/test/integration/clickhouse/clickhouse-graph-builder.test.ts
> fixed clickhouse joins in cubejs-schema-compiler

- docs/content/Auth/Overview.mdx
- docs/content/Configuration/Config.mdx
- docs/content/Cube.js-Backend/SQL-API.mdx
> docs(backend): Reflect latest changes in authorization for SQL API

- rust/cubesql/src/compile/context.rs
- rust/cubesql/src/compile/mod.rs
- rust/cubesql/src/schema/mod.rs
> feat(cubesql): Support DATE_TRUNC(string, column);

- rust/cubesql/src/compile/mod.rs
> feat(cubesql): Casting to date on compare with time dimension

- rust/cubesql/src/compile/context.rs
- rust/cubesql/src/compile/mod.rs
- rust/cubesql/src/compile/parser.rs
- rust/cubesql/src/mysql/mod.rs
> fix(cubesql): Parsing error with single comment line

- rust/cubesql/src/compile/mod.rs
> feat(cubesql): Strict check for dates in BETWEEN operator

- docs/content/Examples-Tutorials-Recipes/Examples.md
**Check List**
Added Retool to front-end libs section.
> docs(fix): reorder examples

- rust/cubesql/src/compile/mod.rs
> feat(cubesql): Strict check for dates in binary expr

- .github/workflows/master.yml
- .github/workflows/publish.yml
- .github/workflows/push.yml
- .github/workflows/rust-master.yml
- .github/workflows/rust.yml
> ci: Lock docker buildx on 0.6.3 (0.7 is broken)

- packages/cubejs-backend-native/Cargo.lock
- rust/Cargo.lock
- rust/cubesql/Cargo.toml
- rust/cubesql/src/compile/engine/udf.rs
- rust/cubesql/src/compile/mod.rs
Hello!
This SQL is required for DataGrip:
```sql
select left(user(),instr(concat(user(),'@'),'@')-1);
```
Thanks
> feat(cubesql): Support insrt, left functions

- packages/cubejs-api-gateway/src/SubscriptionServer.ts
- packages/cubejs-api-gateway/src/gateway.ts
- packages/cubejs-server/src/websocket-server.ts
> feat: log network usage

- packages/cubejs-cubestore-driver/codegen/HttpMessage.ts
- packages/cubejs-cubestore-driver/src/CubeStoreDriver.ts
- packages/cubejs-cubestore-driver/src/WebSocketConnection.ts
- packages/cubejs-query-orchestrator/src/driver/BaseDriver.js
- packages/cubejs-query-orchestrator/src/driver/driver.interface.ts
- packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts
- rust/Cargo.lock
- rust/cubestore/Cargo.toml
- rust/cubestore/src/bin/cubestored.rs
- rust/cubestore/src/codegen/http_message.fbs
- rust/cubestore/src/codegen/http_message_generated.rs
- rust/cubestore/src/config/mod.rs
- rust/cubestore/src/http/mod.rs
- rust/cubestore/src/import/mod.rs
- rust/cubestore/src/lib.rs
- rust/cubestore/src/metastore/mod.rs
- rust/cubestore/src/metastore/table.rs
- rust/cubestore/src/mysql/mod.rs
- rust/cubestore/src/sql/mod.rs
- rust/cubestore/src/telemetry/mod.rs
> chore(cubestore): Agent and tracing support

- rust/Cargo.lock
- rust/cubesql/Cargo.toml
- rust/cubesql/src/compile/engine/context.rs
- rust/cubesql/src/config/mod.rs
> feat(cubesql): Select for server variables

- examples/drill-downs/dashboard-app/.env.production
**Check List**
Fixes API env vars for drill down examples: https://drill-downs-demo.cube.dev/#/
Added updated env vars from here: https://examples.cubecloud.dev/deployments/25
> examples(fix): drill down env vars

- packages/cubejs-backend-native/Cargo.lock
- rust/Cargo.lock
- rust/cubesql/Cargo.toml
> fix(cubesql): mysql CLI connection error with COM_FIELD_LIST

- packages/cubejs-backend-native/Cargo.lock
- rust/Cargo.lock
- rust/cubesql/Cargo.toml
- rust/cubesql/src/compile/mod.rs
- rust/cubesql/src/mysql/mod.rs
> fix(cubesql): Ignore SET NAMES on AST level

- rust/cubesql/src/compile/mod.rs
- rust/cubesql/src/mysql/dataframe.rs
- rust/cubesql/src/mysql/mod.rs
> feat(cubesql): Support specifying ColumnFlags in QE

- packages/cubejs-backend-native/Cargo.lock
- rust/Cargo.lock
- rust/cubesql/Cargo.toml
- rust/cubesql/src/compile/mod.rs
> feat(cubesql): Skip SET {GLOBAL|SESSION} TRANSACTION isolation on AST level

- rust/Dockerfile
> ci: fix dev build for Cube Store

- rust/Cargo.lock
- rust/cubestore-sql-tests/src/tests.rs
- rust/cubestore/Cargo.toml
- rust/cubestore/src/sql/mod.rs
Fixes #3742
**Check List**
#3742
> fix(cubestore): Support escaping sequence for ILIKE

- packages/cubejs-backend-native/Cargo.lock
- rust/cubesql/src/compile/engine/context.rs
- rust/cubesql/src/compile/engine/udf.rs
- rust/cubesql/src/compile/mod.rs
> feat(cubesql): Specify transaction_isolation, transaction_read_only

- packages/cubejs-backend-native/Cargo.lock
- rust/Cargo.lock
- rust/cubesql/Cargo.toml
- rust/cubesql/src/compile/engine/information_schema.rs
- rust/cubesql/src/compile/engine/information_schema/columns.rs
- rust/cubesql/src/compile/engine/information_schema/mod.rs
- rust/cubesql/src/compile/engine/information_schema/tables.rs
- rust/cubesql/src/compile/engine/mod.rs
- rust/cubesql/src/compile/engine/provider.rs
- rust/cubesql/src/compile/engine/udf.rs
- rust/cubesql/src/compile/mod.rs
> feat(cubesql): Rewrite INFORMATION_SCHEMA.TABLES & COLUMNS

- docs/content/API-Reference/Query-Format.md
- docs/content/Configuration/Reference/@cubejs-backend-server-core.md
- docs/content/Configuration/Reference/@cubejs-backend-server.md
Story details: https://app.shortcut.com/cube-dev/story/1168
> docs(config): move Node API reference to Configuration section

- docs/src/pages/index.tsx
Story details: https://app.shortcut.com/cube-dev/story/1163
> docs: improve docs landing page

- docs/content/Schema/Reference/joins.mdx
Story details: https://app.shortcut.com/cube-dev/story/1174
> docs(schema): fix broken link to Join Directions page

- docs/content/Configuration/Databases/Google-BigQuery.mdx
> BQ location not required

- packages/cubejs-api-gateway/src/graphql.ts
- packages/cubejs-api-gateway/src/sql-server.ts
`load` was renamed to `cube`
```gql 
query CubeQuery {
cube(timezone: "UTC") {
orders {
status
createdAt {
value 
}
}
}
}
```
> fix(api-gateway): GraphQL boolean filters

- packages/cubejs-api-gateway/src/graphql.ts
Remove irrelevant `contains` and `notcontains` from float filters
> fix(api-gateway): Remove irrelevant GraphQL float filters

- packages/cubejs-api-gateway/src/gateway.ts
Enable GraphiQL header editor to pass security context in dev mode
> feat(api-gateway): Enable GraphiQL header editor to pass security context in dev mode

- docs/content/Frontend-Integrations/@cubejs-client-core.md
- docs/content/Frontend-Integrations/@cubejs-client-ngx.md
- docs/content/Frontend-Integrations/@cubejs-client-react.md
- docs/content/Frontend-Integrations/@cubejs-client-vue.md
- docs/content/Frontend-Integrations/@cubejs-client-ws-transport.md
- docs/content/Frontend-Integrations/Dashboard-App.md
- docs/content/Frontend-Integrations/Introduction-angular.md
- docs/content/Frontend-Integrations/Introduction-react.md
- docs/content/Frontend-Integrations/Introduction-vue.md
- docs/content/Frontend-Integrations/Introduction.md
- docs/content/Frontend-Integrations/Real-Time-Data-Fetch.md
- docs/src/components/Layout/MainMenu.tsx
Story details: https://app.shortcut.com/cube-dev/story/1170
> docs(frontend): rename 'Cube.js Frontend' to 'Frontend Integrations'

- docs/content/Configuration/Config.mdx
> docs: `extendContext` global usage warning

- docs/content/Cube-Cloud/Configuration/Connecting-to-Databases.mdx
Story details: https://app.shortcut.com/cube-dev/story/1164
> docs(cloud): update multiple database connection instructions

- docs/content/Configuration/Environment-Variables-Reference.md
> docs(config): add environment variables for Cube Store minIO support

- docs/content/Getting-Started/Getting-Started-Docker-Compose.mdx
> docs: Small fixes to getting started with docker

- docs/content/Configuration/Overview.mdx
Story details: https://app.shortcut.com/cube-dev/story/1182
> docs(config): update and improve 'Migrating from Express to Docker' section

- docs/content/Schema/Reference/pre-aggregations.mdx
Story details: https://app.shortcut.com/cube-dev/story/568
> docs(schema): improve copy and examples for Segments section in Pre-Aggregations

- docs/content/Caching/Using-Pre-Aggregations.mdx
Story details: https://app.shortcut.com/cube-dev/story/1056
> docs(caching): add new Joins between Pre-Aggregations section

- rust/Cargo.lock
- rust/cubestore-sql-tests/src/tests.rs
- rust/cubestore/Cargo.toml
- rust/cubestore/src/queryplanner/planning.rs
- rust/cubestore/src/queryplanner/pretty_printers.rs
> feat(cubestore): Sort NULLS LAST by default

- examples/helm-charts/cubejs/Chart.yaml
- examples/helm-charts/cubejs/README.md
- examples/helm-charts/cubejs/templates/common-env.tpl
- examples/helm-charts/cubejs/templates/master/deployment.yaml
- examples/helm-charts/cubejs/templates/workers/deployment.yaml
- examples/helm-charts/cubejs/values.yaml
- examples/helm-charts/cubestore/Chart.yaml
- examples/helm-charts/cubestore/templates/common-env.tpl
- examples/helm-charts/cubestore/templates/router/statefulset.yaml
- examples/helm-charts/cubestore/templates/workers/service-headless.yaml
- examples/helm-charts/cubestore/templates/workers/statefulset.yaml
- Add `config.sqlPort` config to enable SQL Api (disabled by default)
- Remove image.tag v* restriction.
- Lint
> feat(helm-charts): Add sqlPort config to enable SQL Api

- rust/cubesql/src/compile/engine/context.rs
- rust/cubesql/src/compile/engine/df/coerce.rs
- rust/cubesql/src/compile/engine/df/mod.rs
- rust/cubesql/src/compile/engine/mod.rs
- rust/cubesql/src/compile/engine/udf.rs
- rust/cubesql/src/compile/mod.rs
> feat(cubesql): Support compound identifier in ORDER BY

- docs/content/API-Reference/GraphQL-API.mdx
Story details: https://app.shortcut.com/cube-dev/story/1183
Thanks @lvauvillier!
> docs(api): improve and update GraphQL API Reference

- docs/content/API-Reference/GraphQL-API.mdx
> docs(api): improve GraphQL API reference

- docs/content/Schema/Reference/pre-aggregations.mdx
Story details: https://app.shortcut.com/cube-dev/story/920
> docs(schema): improve Pre-Aggregation reference

- rust/Cargo.lock
- rust/cubesql/Cargo.toml
- rust/cubesql/src/compile/engine/df/intervals.rs
- rust/cubesql/src/compile/engine/df/mod.rs
- rust/cubesql/src/compile/engine/udf.rs
- rust/cubesql/src/compile/mod.rs
- rust/cubesql/src/mysql/dataframe.rs
> feat(cubesql): Introduce timediff, time_format

- rust/cubesql/src/compile/engine/df/coerce.rs
- rust/cubesql/src/compile/engine/udf.rs
- rust/cubesql/src/compile/mod.rs
> fix(cubesql): Special NULL handling for LEAST function

- .github/workflows/push.yml
> ci: Use LTS versions of Node.js for unit testing

- docs/content/Frontend-Integrations/@cubejs-client-react.md
- docs/content/Frontend-Integrations/@cubejs-client-vue.md
- packages/cubejs-client-vue/src/QueryBuilder.js
**Check List**
fixes https://github.com/cube-js/cube.js/issues/3757
I have added the same prop as `cubejs-client-react` to use the builder without the renderer.
> feat(cubejs-client-vue): add wrapWithQueryRenderer prop

- packages/cubejs-api-gateway/src/SubscriptionServer.ts
- packages/cubejs-api-gateway/src/gateway.ts
- packages/cubejs-api-gateway/src/graphql.ts
- packages/cubejs-api-gateway/src/sql-server.ts
**Check List**
[https://www.notion.so/Event-property-for-SQL-and-GraphQL-API-d685c7e8c9664ce4bfae761778f04523](https://www.notion.so/Event-property-for-SQL-and-GraphQL-API-d685c7e8c9664ce4bfae761778f04523)
> feat(api-gateway): Event property for SQL and GraphQL API

- packages/cubejs-client-ngx/angular.json
- packages/cubejs-client-ngx/package.json
- packages/cubejs-client-ngx/tsconfig.json
- yarn.lock
Closes #2780 
upd: going to be merged once we drop `node 10` support
> chore: angular 12

- docs/content/Examples-Tutorials-Recipes/Entity-Attribute-Value.md
- docs/content/Schema/Getting-Started.mdx
- docs/src/pages/index.tsx
> Add info box for data modeling workshop

- docs/content/Configuration/Environment-Variables-Reference.md
> docs(config): use correct possible values for `CUBEJS_DB_EXPORT_BUCKET_TYPE`

- packages/cubejs-playground/package.json
- yarn.lock
Update react-scripts to fix some vunls.
> refactor(cubejs-playground): update react-scripts

- packages/cubejs-backend-native/Cargo.lock
- rust/cubesql/src/compile/context.rs
- rust/cubesql/src/compile/engine/udf.rs
- rust/cubesql/src/compile/mod.rs
> feat(cubesql): Support DATE, DATE_ADD, NOW functions & Intervals

- packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts
- packages/cubejs-query-orchestrator/test/unit/QueryOrchestrator.test.js
- packages/cubejs-schema-compiler/src/adapter/PreAggregations.js
> Table cache invalidation fix

- docs/content/Frontend-Integrations/@cubejs-client-core.md
- packages/cubejs-client-core/index.d.ts
**Check List**
#3682
Added the missing 'meta' field in TCubeMember type.
> Add 'meta' field to typescript TCubeMember type

- .github/workflows/publish.yml
- .github/workflows/rust-cubestore-master.yml
- .github/workflows/rust-cubestore.yml
- rust/cubestore/Cross.toml
- rust/cubestore/cross/aarch64-unknown-linux-gnu.Dockerfile
Adding
```
RUN apt-get install -y libc6
RUN apt-get install -y gcc-multilib
RUN apt-get install -y gcc-aarch64-linux-gnu
RUN apt-get install -y g++-aarch64-linux-gnu
```
fixes ```sys/cdefs.h' file not found``` when compiling ```librocksdb-sys```
> Cross arm64 cubestore

- docs/content/Examples-Tutorials-Recipes/Accelerating-Non-Additive-Measures.md
- docs/content/Frontend-Integrations/@cubejs-client-vue.md
- docs/content/Frontend-Integrations/Introduction-angular.md
- docs/content/Frontend-Integrations/Introduction-react.md
- docs/content/Frontend-Integrations/Introduction-vue.md
- docs/content/Frontend-Integrations/Introduction.md
> chore: fix codesandboxes

- packages/cubejs-backend-native/src/transport.rs
- packages/cubejs-backend-native/test/sql.test.js
> fix(cubesql/native): Return errors to the client (missing field )

- packages/cubejs-backend-native/Cargo.lock
- rust/cubesql/Cargo.lock
- rust/cubesql/cubesql/Cargo.toml
- rust/cubesql/cubesql/src/compile/mod.rs
> feat(cubesql): Ignore KILL statement without error

- .github/workflows/publish.yml
- packages/cubejs-docker/latest-alpine.Dockerfile
- packages/cubejs-docker/latest.Dockerfile
- Add arm64 to `docker-cubestore`
- Add arm64 to `docker-default`
- Fix `oracledb` failing to install on arm64
- Merge `docker-cubestore` and `docker-cubestore-non-avx`
> Add arm64 to docker-cubestore

- .github/workflows/publish.yml
- .github/workflows/rust-cubestore-master.yml
- .github/workflows/rust-cubestore.yml
> fix: Combine multiarch build for Cube, split multiarch for Cube Store

- packages/cubejs-docker/latest-alpine.Dockerfile
> fix(docker): remove cache from alpine image

- .github/workflows/publish.yml
- .github/workflows/rust-cubesql.yml
- rust/cubestore/Cross.toml
- rust/cubestore/cross/README.md
- rust/cubestore/cross/x86_64-unknown-linux-gnu-buster.Dockerfile
- rust/cubestore/cross/x86_64-unknown-linux-gnu-stretch.Dockerfile
- rust/cubestore/cross/x86_64-unknown-linux-musl.Dockerfile
- rust/cubestore/js-wrapper/src/utils.ts
> feat(native/cubesql): Build for ARM64 linux GNU

- docs/content/Configuration/Config.mdx
- docs/content/Configuration/Multitenancy-Setup.mdx
> docs(config): improve documentation for `contextToOrchestratorId`

- docs/content/Deployment/Overview.mdx
> docs(deployment): add note about Refresh Workers keeping `refreshKey` up-to-date

- packages/cubejs-cli/src/command/typegen.ts
> fix(cubejs-cli): use `process.cwd()` in `typegen` to resolve current project's `node_modules/`

- rust/cubesql/cubesql/src/compile/context.rs
- rust/cubesql/cubesql/src/compile/mod.rs
> fix(cubesql): Alias binding problem with escapes (<expr> as '$1')

- packages/cubejs-backend-native/DEVELOPMENT.md
- rust/cubesql/DEVELOPMENT.md
- rust/cubesql/cubesql/src/compile/context.rs
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/lib.rs
~~Requires https://github.com/cube-js/cube.js/pull/3835 to be merged first~~
**Check List**
Improve errors returned by the Cube SQL API.
> fix(cubesql): improve error messages

- rust/cubestore/Cross.toml
- rust/cubestore/Dockerfile
- rust/cubestore/cross/README.md
- rust/cubestore/cross/aarch64-unknown-linux-gnu.Dockerfile
- rust/cubestore/cross/x86_64-pc-windows-gnu.Dockerfile
- rust/cubestore/cross/x86_64-unknown-linux-gnu-buster.Dockerfile
- rust/cubestore/cross/x86_64-unknown-linux-gnu-stretch.Dockerfile
- rust/cubestore/cross/x86_64-unknown-linux-musl.Dockerfile
> feat(cubestore): Use OpenSSL 1.1.1l for standalone binaries

- .github/workflows/push.yml
- .github/workflows/rust-cubesql.yml
> ci: Collect code coverage for Cube SQL

- rust/cubesql/cubesql/src/compile/engine/information_schema/variables.rs
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/mysql/mod.rs
> feat(cubesql): Execute SHOW VARIABLES via QE instead of hardcoding

- docs/content/Cube-Cloud/Getting-Started/Create-new.md
**Check List**
https://app.shortcut.com/cube-dev/story/1189/merge-getting-started-with-cube-cloud-information
> docs(fix): added cube cloud info on getting started docs

- packages/cubejs-client-core/index.d.ts
- packages/cubejs-client-core/package.json
> fix(@cubejs-client/core): restore support for Angular by removing dependency on `@cubejs-client/dx`

- CONTRIBUTING.md
**Check List**
N/A
* Updates the instructions for creating a dev server setup by merging "Development" and "Linking Server Core for Development" sections.
* Adds WebStorm instructions.
* A few consistencty touches: use yarn over npm everywhere, use `yarn install` instead of `yarn`, use `<cmd>` instead of `$ <cmd>`, use "Run <cmd>" consistently.
See also https://developers.google.com/style/code-syntax for some inspiration.
> docs: improve server development instructions in CONTRIBUTION.md

- docs/content/Schema/Reference/pre-aggregations.mdx
> docs(schema): improve docs for using `buildRangeStart/End` with `refreshKey`

- rust/cubesql/cubesql/src/compile/engine/context.rs
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/mysql/mod.rs
> feat(cubesql): Setup more system variables

- packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts
> [fix] versionEntryByStructureVersion

- rust/cubesql/cubesql/src/compile/engine/context.rs
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/mysql/mod.rs
> feat(cubesql): Support USE 'db' (success reply)

- rust/cubesql/.gitignore
- rust/cubesql/Cargo.lock
- rust/cubesql/cubesql/Cargo.toml
- rust/cubesql/cubesql/src/compile/mod.rs
> feat(cubesql): Support SHOW COLUMNS

- rust/cubesql/Cargo.lock
- rust/cubesql/cubesql/Cargo.toml
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/mysql/mod.rs
> feat(cubesql): Support SHOW TABLES

- packages/cubejs-client-react/index.d.ts
> chore(docs): fix typo

- packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts
> fix: Remove orphaned tables on error while pre-aggregation creation

- packages/cubejs-api-gateway/src/interfaces.ts
…ot properly support logical and and logical or operators
**Check List**
[#4007](https://github.com/cube-js/cube.js/issues/4007)
Update query types in cubejs-api-gateway to properly support logical and and logical or operators.
> fix(@cubejs-backend/api-gateway): fix a type issue where queries did not properly support logical AND/OR operators

- packages/cubejs-backend-native/Cargo.lock
- rust/cubesql/Cargo.lock
- rust/cubesql/cubesql/Cargo.toml
- rust/cubesql/cubesql/src/compile/mod.rs
> fix(cubesql): Ignore case sensitive search for usage of identifiers

- docs/content/Examples-Tutorials-Recipes/Recipes/entity-attribute-value.md
- docs/content/Schema/Getting-Started.mdx
- docs/src/pages/index.tsx
> Remove data modeling workshop banner from main doc

- rust/cubesql/Cargo.lock
- rust/cubesql/cubesql/Cargo.toml
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/mysql/service.rs
> feat(cubesql): Support SHOW COLLATION

- packages/cubejs-playground/src/components/GlobalStyles.tsx
- packages/cubejs-playground/src/components/QueryTabs/QueryTabs.tsx
- packages/cubejs-playground/src/playground/index.less
- packages/cubejs-playground/src/variables.ts
Fixes close button styles in tab dropdown.
> fix(cubejs-playground): tab close button styles

- packages/cubejs-backend-native/Cargo.lock
- rust/cubesql/cubesql/src/compile/engine/udf.rs
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/mysql/auth_service.rs
- rust/cubesql/cubesql/src/mysql/server_manager.rs
- rust/cubesql/cubesql/src/mysql/service.rs
- rust/cubesql/cubesql/src/transport/service.rs
> refactoring(cubesql): ConnectionState - shareable/mutability state

- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/mysql/service.rs
> refactor(cubesql): Move EXPLAIN <table | stmt> to planner 

- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/mysql/service.rs
> refactor(cubesql): Move SET to planner

- rust/cubesql/Cargo.lock
- rust/cubesql/cubesql/Cargo.toml
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/mysql/service.rs
> refactor(cubesql): Move USE <db> to planner

- packages/cubejs-testing/src/birdbox.ts
**Check List**
N/A
Fix accidental birdbox breakage. See https://github.com/cube-js/cube.js/commit/108f42afdd58ae0027b1b81730f7ca9e72ab9122#diff-b3fe204ec00162785971dfb9c8223391d2cc8247e1e85e3df958488428f34684L177
> fix: Accidental birdbox breakage.

- packages/cubejs-testing/DEVELOPMENT.md
**Check List**
N/A
Fix cypress testing recipe formatting
> docs: Fix cypress testing recipe formatting

- examples/helm-charts/cubejs/README.md
- examples/helm-charts/cubejs/templates/common-env.tpl
**Check List**
With the recent changes merged in #4098 we renamed the S3 output env var. This PR edits the Helm template value to be the same.
> examples(helm): edit value for S3 output

- rust/cubestore/Cargo.lock
- rust/cubestore/cubestore-sql-tests/Cargo.toml
- rust/cubestore/cubestore-sql-tests/data/csv.csv
- rust/cubestore/cubestore-sql-tests/data/csv_no_header.csv
- rust/cubestore/cubestore-sql-tests/src/files.rs
- rust/cubestore/cubestore-sql-tests/src/lib.rs
- rust/cubestore/cubestore-sql-tests/src/tests.rs
- rust/cubestore/cubestore/src/queryplanner/panic.rs
**Check List**
N/A
Fixes enterprise csv tests by generating temp csv files
> chore(cubestore): Fixes enterprise csv tests

- README.md
- docs/content/Cube.js-Introduction.md
- docs/content/Frontend-Integrations/Introduction-angular.md
- docs/content/Frontend-Integrations/Introduction-react.md
- docs/content/Frontend-Integrations/Introduction-vue.md
- docs/content/Frontend-Integrations/Introduction.md
https://deploy-preview-4155--cubejs-docs-staging.netlify.app/introduction
> chore: update positioning/messaging

- packages/cubejs-api-gateway/src/graphql.ts
> fix "Cannot read property findIndex of undefined"

- docs/package.json
- docs/yarn.lock
It will update the internal tracking system's version to the latest
> chore: update Cube tracker version to latest

- docs/content/Caching/Getting-Started-Pre-Aggregations.md
- docs/content/Caching/Overview.mdx
- docs/content/Caching/Running-in-Production.mdx
- docs/content/Caching/Using-Pre-Aggregations.mdx
- docs/src/pages/index.tsx
> Add info boxes for the advanced pre-agg workshop

- packages/cubejs-athena-driver/src/AthenaDriver.ts
- packages/cubejs-cubestore-driver/src/CubeStoreDriver.ts
- packages/cubejs-query-orchestrator/src/driver/driver.interface.ts
- packages/cubejs-query-orchestrator/src/driver/utils.ts
- packages/cubejs-testing/DEVELOPMENT.md
- packages/cubejs-testing/birdbox-fixtures/postgresql/schema/OrdersPA.js
- packages/cubejs-testing/test/__snapshots__/athena.query.snapshot
- packages/cubejs-testing/test/__snapshots__/bigquery.query.snapshot
- packages/cubejs-testing/test/birdbox-driver.test.ts
**Check List**
N/A
* Fixes Athena export bucket location. 
* Fixes Athena unload column order, unloads & returns columns explicitly.
> fix(athena): Fixes export bucket location. Fixes column order.

- rust/cubesql/DEVELOPMENT.md
- rust/cubesql/cubesql/src/compile/engine/information_schema/columns.rs
- rust/cubesql/cubesql/src/compile/engine/information_schema/key_column_usage.rs
- rust/cubesql/cubesql/src/compile/engine/information_schema/mod.rs
- rust/cubesql/cubesql/src/compile/engine/information_schema/processlist.rs
- rust/cubesql/cubesql/src/compile/engine/information_schema/referential_constraints.rs
- rust/cubesql/cubesql/src/compile/engine/information_schema/schemata.rs
- rust/cubesql/cubesql/src/compile/engine/information_schema/statistics.rs
- rust/cubesql/cubesql/src/compile/engine/information_schema/tables.rs
- rust/cubesql/cubesql/src/compile/engine/information_schema/utils.rs
- rust/cubesql/cubesql/src/compile/engine/provider.rs
- rust/cubesql/cubesql/src/compile/engine/udf.rs
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/service.rs
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__information_schema_collations.snap
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__information_schema_processlist.snap
- rust/cubesql/cubesql/src/config/mod.rs
- rust/cubesql/cubesql/src/mysql/mod.rs
- rust/cubesql/cubesql/src/mysql/server_manager.rs
- rust/cubesql/cubesql/src/mysql/service.rs
- rust/cubesql/cubesql/src/mysql/session.rs
- rust/cubesql/cubesql/src/mysql/session_manager.rs
> chore(cubesql): Introduce SessionManager

- examples/helm-charts/cubejs/Chart.yaml
- examples/helm-charts/cubejs/README.md
- examples/helm-charts/cubejs/templates/common-env.tpl
- examples/helm-charts/cubejs/templates/master/deployment.yaml
- examples/helm-charts/cubejs/templates/master/service.yaml
- examples/helm-charts/cubejs/values.yaml
- examples/helm-charts/cubestore/Chart.yaml
- Add missing config env vars for sqlAPI
- Remove unnecessary service config to keep the it as simple as possible and allow to expose both http and api ports
- fix s3OutputLocation in values.yaml
> fix(helm-charts): add missing config for sqlAPI

- packages/cubejs-backend-native/Cargo.lock
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__show_processlist.snap
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__show_warnings.snap
> feat(cubesql): Support SHOW processlist

- packages/cubejs-api-gateway/src/gateway.ts
Additional property for better db usage analytics
**Check List**
https://cubedevinc.atlassian.net/browse/CC-262
> feat(cubejs-api-gateway): add dbType to load req success event

- rust/cubesql/cubesql/src/compile/mod.rs
> fix: mysql interface functions are disabled for postgres

- rust/cubesql/Cargo.lock
- rust/cubesql/cubesql/Cargo.toml
- rust/cubesql/cubesql/src/sql/postgres/buffer.rs
- rust/cubesql/cubesql/src/sql/postgres/protocol.rs
- rust/cubesql/cubesql/src/sql/postgres/shim.rs
> chore(cubeql): Deserializers for Parse,Bind,Describe messages in pg-wire

- rust/cubesql/cubesql/src/sql/postgres/protocol.rs
- rust/cubesql/cubesql/src/sql/postgres/shim.rs
> feat: Correct response for SslRequest

- packages/cubejs-server-core/src/core/optionsValidate.ts
- packages/cubejs-server-core/src/core/server.ts
- packages/cubejs-server-core/src/core/types.ts
- packages/cubejs-server-core/test/unit/index.test.ts
> chore(server-core): Allow to configure DataSchemaCompiler's allowNodeRequire option via CubejsServer

- examples/advanced-pre-aggregations-workshop/.env
- examples/advanced-pre-aggregations-workshop/.gitignore
- examples/advanced-pre-aggregations-workshop/cube.js
- examples/advanced-pre-aggregations-workshop/docker-compose.yml
- examples/advanced-pre-aggregations-workshop/package.json
- examples/advanced-pre-aggregations-workshop/schema/Customer.js
- examples/advanced-pre-aggregations-workshop/schema/Nation.js
- examples/advanced-pre-aggregations-workshop/schema/Order.js
- examples/advanced-pre-aggregations-workshop/schema/Region.js
- examples/advanced-pre-aggregations-workshop/utils/request.js
**Check List**
This PR adds code samples for the Advanced Pre-aggregations workshop.
> examples(workshop): Advanced pre-aggregations workshop examples

- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/sql/postgres/shim.rs
> fix(cubesql): Pass client_encoding to client

- docs/content/Schema/Advanced/Code-Reusability-Export-and-Import.md
**Check List**
Faced it myself and it wasn't clear until if it's expected or not. Want to make it clear to users and give an example.
> docs: explain import from parent dirs with example

- rust/cubesql/cubesql/src/sql/postgres/buffer.rs
- rust/cubesql/cubesql/src/sql/postgres/protocol.rs
> fix(cubesql): Fix decoding for messages without body in pg-wire protocol

- examples/advanced-pre-aggregations-workshop/cube.js
- examples/advanced-pre-aggregations-workshop/schema/Customer.js
- examples/advanced-pre-aggregations-workshop/schema/Order.js
- examples/advanced-pre-aggregations-workshop/schema/Region.js
**Check List**
Edited steps to add incremental refresh.
> examples(workshop): Advanced Pre-aggregations workshop updates

- rust/cubestore/cubestore-sql-tests/tests/cluster.rs
- rust/cubestore/cubestore-sql-tests/tests/multi_process.rs
- rust/cubestore/cubestore/src/bin/cubestored.rs
- rust/cubestore/cubestore/src/cluster/mod.rs
- rust/cubestore/cubestore/src/cluster/worker_pool.rs
- rust/cubestore/cubestore/src/config/mod.rs
**Check List**
N/A
* Use config.injector() to configure WorkerServices.
* Remove global WORKER_SERVICES.
> chore(cubestore): Use config.injector() to configure WorkerServices

- packages/cubejs-backend-native/src/transport.rs
- rust/cubesql/cubesql/src/compile/engine/df/scan.rs
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/config/mod.rs
- rust/cubesql/cubesql/src/sql/mysql/service.rs
- rust/cubesql/cubesql/src/sql/postgres/protocol.rs
- rust/cubesql/cubesql/src/sql/postgres/shim.rs
- rust/cubesql/cubesql/src/transport/ctx.rs
- rust/cubesql/cubesql/src/transport/service.rs
> chore(cubesql): Introduce cache for HttpTransport

- examples/advanced-pre-aggregations-workshop/schema/Order.js
**Check List**
Edits from Pavel's feedback.
> examples(workshop): Feedback edit for Adv. pre-agg. workshop

- packages/cubejs-backend-native/src/transport.rs
> chore(cubesql): Fix MetaContext initialization

- examples/advanced-pre-aggregations-workshop/schema/Order.js
**Check List**
Edits from Pavel's feedback.
> examples(workshop): feedback edits

- rust/cubesql/cubesql/src/compile/engine/context.rs
- rust/cubesql/cubesql/src/compile/engine/information_schema/postgres/mod.rs
- rust/cubesql/cubesql/src/compile/engine/information_schema/postgres/pg_settings.rs
- rust/cubesql/cubesql/src/compile/engine/provider.rs
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/sql/database_variables/mod.rs
- rust/cubesql/cubesql/src/sql/database_variables/mysql/global_vars.rs
- rust/cubesql/cubesql/src/sql/database_variables/mysql/session_vars.rs
- rust/cubesql/cubesql/src/sql/database_variables/postgres/global_vars.rs
- rust/cubesql/cubesql/src/sql/database_variables/postgres/mod.rs
- rust/cubesql/cubesql/src/sql/database_variables/postgres/session_vars.rs
- rust/cubesql/cubesql/src/sql/server_manager.rs
- rust/cubesql/cubesql/src/sql/session.rs
> feat: MySQL SET variables / Postgres SHOW SET variables

- docs/content/Caching/Getting-Started-Pre-Aggregations.md
- docs/content/Caching/Overview.mdx
- docs/content/Caching/Running-in-Production.mdx
- docs/content/Caching/Using-Pre-Aggregations.mdx
- docs/src/pages/index.tsx
> Remove adv-pre-agg workshop info box from docs pages

- packages/cubejs-backend-native/Cargo.lock
- packages/cubejs-backend-native/package.json
> fix(native): Post installation issue with npm

- rust/cubestore/Cargo.lock
- rust/cubestore/cubestore-sql-tests/src/tests.rs
**Check List**
IN operator support for decimal type
> feat(cubestore): IN operator support for decimal type

- packages/cubejs-jdbc-driver/src/JDBCDriver.js
**Check List**
- [] Tests has been run in packages where changes made if available
Handle mvn error for empty java dependencies
> fix(jdbc-driver): Handle mvn error for empty java dependencies

- packages/cubejs-playground/src/QueryBuilder/MemberDropdown.tsx
**Check List**
this pr fixes the transparency of the background of the search menu item in some weird cases.
> fix: transparency under the searchbar in some cases

- packages/cubejs-client-core/index.d.ts
> Update index.d.ts for fix the link

- rust/cubestore/cubestore/src/cluster/message.rs
- rust/cubestore/cubestore/src/cluster/mod.rs
- rust/cubestore/cubestore/src/queryplanner/query_executor.rs
- rust/cubestore/cubestore/src/sql/mod.rs
**Check List**
Implementation of `EXPLAIN` and `EXPLAN ANALYZE` for `CubeStore`
* `EXPLAIN` shows the logical plan of the query
* `EXPLAIN ANALYZE` shows the physical plans of the query for the router and all workers
> Explain implementation

- packages/cubejs-backend-native/Cargo.lock
- packages/cubejs-backend-native/Cargo.toml
- packages/cubejs-backend-native/src/lib.rs
- rust/cubesql/cubesql/src/config/injection.rs
- rust/cubesql/cubesql/src/sql/mysql/service.rs
- rust/cubesql/cubesql/src/sql/postgres/service.rs
> chore(cubesql): Testing memory usage

- examples/helm-charts/cubejs/templates/common-env.tpl
**Check List**
- [ x ] Linter has been run for changed code
None
Fixes wrong name of the value referenced
> Fix name of the referenced Snowflake role

- docs/content/Caching/Using-Pre-Aggregations.mdx
- docs/content/Configuration/Databases/AWS-Athena.mdx
**Check List**
Athena docs should reflect our support for export/batching now
Athena config instructions updated to account for export/batching
> [docs] added export/batching support for Athena

- packages/cubejs-questdb-driver/src/QuestQuery.ts
- packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
- packages/cubejs-schema-compiler/src/adapter/BigqueryQuery.js
- packages/cubejs-schema-compiler/src/adapter/ClickHouseQuery.js
- packages/cubejs-schema-compiler/src/compiler/CubeEvaluator.js
- packages/cubejs-schema-compiler/src/compiler/JoinGraph.js
- packages/cubejs-schema-compiler/test/integration/postgres/PostgresDBRunner.js
- packages/cubejs-schema-compiler/test/integration/postgres/sql-generation.test.ts
**Check List**
#4364 
Updated Primary Keys logic to support an array of PKs
> Support Compound Primary Keys

- rust/cubestore/cubestore/src/import/mod.rs
**Check List**
N/A
More informative `ImportServiceImpl::do_import` io errors.
> chore(cubestore): More informative ImportServiceImpl::do_import io errors.

- rust/cubesql/cubesql/e2e/tests/mod.rs
- rust/cubesql/cubesql/e2e/tests/mysql.rs
- rust/cubesql/cubesql/e2e/tests/postgres.rs
- rust/cubesql/cubesql/e2e/tests/snapshots/e2e__tests__mysql__select_cast(true_as_boolean)_as_bool_true_cast(false_as_boolean)_as_bool_false_1_int_as_int_str_as_str_.snap
- rust/cubesql/cubesql/e2e/tests/snapshots/e2e__tests__mysql__select_count(asterisk)_count_status_createdat_from_orders_group_by_status_createdat_order_by_createdat.snap
- rust/cubesql/cubesql/e2e/tests/snapshots/e2e__tests__mysql__select_count(asterisk)_count_status_date_trunc(month_createdat)_date_from_orders_group_by_status_date_trunc(month_createdat)_order_by_date.snap
- rust/cubesql/cubesql/e2e/tests/snapshots/e2e__tests__mysql__select_count(asterisk)_count_status_date_trunc(quarter_createdat)_date_from_orders_group_by_status_date_trunc(quarter_createdat)_order_by_date.snap
- rust/cubesql/cubesql/e2e/tests/snapshots/e2e__tests__mysql__select_count(asterisk)_count_status_from_orders_group_by_status.snap
- rust/cubesql/cubesql/e2e/tests/snapshots/e2e__tests__postgres__select_count(asterisk)_count_status_from_orders_group_by_status.snap
- rust/cubesql/cubesql/e2e/tests/snapshots/e2e__tests__postgres__select_true_as_bool_true_false_as_bool_false_test_1.0_1_.snap
- rust/cubesql/cubesql/e2e/tests/utils.rs
- rust/cubesql/cubesql/src/sql/dataframe.rs
- rust/cubesql/cubesql/src/sql/mysql/service.rs
- rust/cubesql/cubesql/src/sql/postgres/buffer.rs
- rust/cubesql/cubesql/src/sql/postgres/mod.rs
- rust/cubesql/cubesql/src/sql/postgres/protocol.rs
- rust/cubesql/cubesql/src/sql/postgres/shim.rs
- rust/cubesql/cubesql/src/sql/postgres/writer.rs
- rust/cubesql/cubesql/src/sql/statement.rs
> feat(cubesql): Initial support for Binary format in pg-wire

- docs/content/Examples-Tutorials-Recipes/Examples.md
- docs/src/pages/index.tsx
> Add info box for the May workshop

- rust/cubesql/Cargo.lock
- rust/cubesql/cubesql/Cargo.toml
- rust/cubesql/cubesql/e2e/tests/postgres.rs
- rust/cubesql/cubesql/src/compile/engine/information_schema/postgres/mod.rs
- rust/cubesql/cubesql/src/compile/engine/information_schema/postgres/testing_dataset.rs
- rust/cubesql/cubesql/src/compile/engine/provider.rs
- rust/cubesql/cubesql/src/lib.rs
- rust/cubesql/cubesql/src/sql/postgres/extended.rs
- rust/cubesql/cubesql/src/sql/postgres/mod.rs
- rust/cubesql/cubesql/src/sql/postgres/protocol.rs
- rust/cubesql/cubesql/src/sql/postgres/shim.rs
- rust/cubesql/cubesql/src/sql/statement.rs
>  chore(cubesql): Use streaming for pg-wire

- rust/cubesql/Cargo.lock
- rust/cubesql/cubesql/Cargo.toml
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/rewrite/analysis.rs
- rust/cubesql/cubesql/src/compile/rewrite/converter.rs
- rust/cubesql/cubesql/src/compile/rewrite/mod.rs
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__superset_subquery.snap
> feat(cubesql): Correlated subqueries support for introspection queries

- rust/cubesql/cubesql/e2e/tests/postgres.rs
- rust/cubesql/cubesql/src/compile/engine/df/intervals.rs
- rust/cubesql/cubesql/src/compile/engine/provider.rs
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/sql/dataframe.rs
- rust/cubesql/cubesql/src/sql/mysql/service.rs
- rust/cubesql/cubesql/src/sql/postgres/protocol.rs
- rust/cubesql/cubesql/src/sql/postgres/shim.rs
- rust/cubesql/cubesql/src/sql/types.rs
> feat(cubesql): Use proper command completion tags for pg-wire

- rust/cubesql/cubesql/e2e/tests/postgres.rs
- rust/cubesql/cubesql/src/compile/engine/information_schema/postgres/testing_dataset.rs
- rust/cubesql/cubesql/src/compile/engine/provider.rs
- rust/cubesql/cubesql/src/compile/engine/udf.rs
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__pg_backend_pid.snap
- rust/cubesql/cubesql/src/lib.rs
- rust/cubesql/cubesql/src/sql/database_variables/postgres/global_vars.rs
- rust/cubesql/cubesql/src/sql/mysql/service.rs
- rust/cubesql/cubesql/src/sql/postgres/extended.rs
- rust/cubesql/cubesql/src/sql/postgres/protocol.rs
- rust/cubesql/cubesql/src/sql/postgres/service.rs
- rust/cubesql/cubesql/src/sql/postgres/shim.rs
- rust/cubesql/cubesql/src/sql/postgres/writer.rs
- rust/cubesql/cubesql/src/sql/service.rs
> feat(cubesql): Support lc_collate for PostgreSQL

- packages/cubejs-backend-native/Cargo.lock
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/rewrite/analysis.rs
- rust/cubesql/cubesql/src/compile/rewrite/cost.rs
- rust/cubesql/cubesql/src/compile/rewrite/language.rs
- rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs
- rust/cubesql/cubesql/src/compile/rewrite/rules/members.rs
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__explain.snap
- rust/cubesql/cubesql/src/sql/postgres/pg_type.rs
> feat(cubesql): Implement rewrites for SELECT * FROM WHERE 1=0

- package.json
- packages/cubejs-backend-shared/src/env.ts
- packages/cubejs-databricks-jdbc-driver/package.json
- packages/cubejs-databricks-jdbc-driver/src/DatabricksDriver.ts
- yarn.lock
> feat(databricks-driver): Export bucket support for S3/Azure

- docs/content/Configuration/Config.mdx
**Check List**
N/A
Link in the docs was missing an 'e'
> bugfix(docs): Fix broken link to tz database wiki page

- packages/cubejs-client-core/index.d.ts
**Check List**
The LogicalOrFilter.or and LogicalAndFilter.and should accept an array
of any Filter to allow easier management of these filters.
> fix(client-core) Correct LogicalAndFilter/LogicalOrFilter types

- examples/helm-charts/cubejs/templates/master/deployment.yaml
- examples/helm-charts/cubejs/templates/workers/deployment.yaml
**Check List**
No open issue
This key seems to be supported on the values.yaml file, yet not used anywhere in the deployment files
> Add imagePullPolicy to cubejs deployments

- rust/cubesql/cubesql/src/compile/engine/udf.rs
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__unnest_i64_from_table.snap
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__unnest_i64_scalar.snap
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__unnest_str_from_table.snap
> feat(cubesql): Support unnest UDTF

- rust/cubesql/cubesql/src/sql/postgres/shim.rs
> refactoring(cubesql): Drop initial parameters from Connection

- packages/cubejs-testing/test/driver-test-suite.ts
> fix(cubejs-testing): noisy test skiped

- packages/cubejs-backend-native/Cargo.lock
- rust/cubesql/cubesql/src/compile/engine/information_schema/postgres/pg_index.rs
- rust/cubesql/cubesql/src/compile/engine/udf.rs
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__pg_generate_subscripts_1.snap
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__pg_generate_subscripts_2_forward.snap
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__pg_generate_subscripts_2_reverse.snap
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__pg_generate_subscripts_3.snap
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__superset_attname_query.snap
> feat(cubesql): Support generate_subscripts UDTF

- packages/cubejs-clickhouse-driver/README.md
- packages/cubejs-dremio-driver/README.md
- packages/cubejs-druid-driver/README.md
- packages/cubejs-hive-driver/README.md
- packages/cubejs-jdbc-driver/README.md
- packages/cubejs-ksql-driver/README.md
- packages/cubejs-materialize-driver/README.md
- packages/cubejs-mongobi-driver/README.md
- packages/cubejs-questdb-driver/README.md
- packages/cubejs-sqlite-driver/README.md
> Add community support paragraph for drivers

- .github/workflows/publish.yml
- .github/workflows/rust-cubestore-master.yml
- .github/workflows/rust-cubestore.yml
> fix: Disable UPX compressing for Cube Store arm64-linux-gnu, fix #4474

- packages/cubejs-docker/dev-alpine.Dockerfile
- packages/cubejs-docker/dev.Dockerfile
> fix(docker): Pack redshift driver for dev docker image, fix #4497

- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__explain-2.snap
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__explain.snap
> chore(cubesql): Use DF node for Explain/Analyze

- guides/angular-dashboard/redirects.txt
- guides/d3-dashboard/README.md
- guides/material-ui-dashboard/README.md
- guides/multi-tenant-analytics/data/SiteConfig.js
- guides/multi-tenant-analytics/redirects.txt
- guides/real-time-dashboard/redirects.txt
- guides/web-analytics/README.md
Also edit some links in README files
> Add redirects to angular, realtime dashboard, and multi-tenant guides

- packages/cubejs-athena-driver/src/AthenaDriver.ts
- packages/cubejs-athena-driver/test/AthenaDriver.test.ts
- packages/cubejs-testing-shared/src/DriverTests.ts
**Check List**
#4418
Fixes error when data result is empty for Athena Driver
> fix(drivers): Fixes error when data result is empty for AthenaDriver

- DEPRECATION.md
> docs: update `DEPRECATION.md` in preparation for new release

- rust/cubesql/Cargo.lock
- rust/cubesql/cubesql/Cargo.toml
- rust/cubesql/cubesql/src/compile/engine/information_schema/postgres/pg_constraint.rs
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/rewrite/converter.rs
- rust/cubesql/cubesql/src/compile/rewrite/mod.rs
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__pg_expandarray_index.snap
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__pg_expandarray_value.snap
> feat(cubesql): Support dynamic key in Array Index expression

- rust/cubesql/cubesql/src/compile/engine/udf.rs
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/parser.rs
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__format_type.snap
- rust/cubesql/cubesql/src/sql/statement.rs
> feat(cubesql): Superset Postgres protocol support

- packages/cubejs-api-gateway/src/helpers/transformMetaExtended.ts
- fileName
- refreshKey
**Check List**
New fields that needs to be obtained from cubeDefinitions to enrich cube object in meta extended response are:
- fileName
- refreshKey
> chore(cubejs-api-gateway): add fields to cube object from extended meta response

- docs/content/API-Reference/SQL-API.mdx
nothing showstopping, just a few tweaks for readability / syntax
> docs: edits SQL API documentation

- guides/bigquery-public-datasets/redirects.txt
> guides: delete redirects.txt

- examples/building-a-data-app-with-cube-workshop/schema/Orders.js
**Check List**
This PR updates a code example for the Building a Data App with Cube workshop.
> examples(building-data-app-workshop): update samples

- packages/cubejs-query-orchestrator/src/orchestrator/QueryCache.ts
- packages/cubejs-query-orchestrator/src/orchestrator/QueryOrchestrator.ts
- packages/cubejs-server-core/src/core/OrchestratorApi.ts
- packages/cubejs-server-core/src/core/RefreshScheduler.ts
> fix: refresh worker force queue reconcile logic

- rust/cubesql/Cargo.lock
- rust/cubesql/cubesql/Cargo.toml
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__df_fork_is_boolean.snap
- rust/cubesql/cubesql/src/sql/statement.rs
> feat(cubesql): Support IS TRUE|FALSE

- examples/helm-charts/cubejs/templates/master/deployment.yaml
- examples/helm-charts/cubejs/templates/workers/deployment.yaml
- examples/helm-charts/cubestore/templates/router/statefulset.yaml
- examples/helm-charts/cubestore/templates/workers/statefulset.yaml
**Check List**
N/A
Apply the `commonAnnotations` as a template to each pod from statefulset
and deployment
Example of annotation that needs to be added to pod:
`iam.amazonaws.com/role:role_name` to use instance role for iam
> feat: statefulset annotations

- docs/content/Configuration/Downstream/Hex.md
- docs/content/Configuration/Downstream/PowerBI.md
- docs/content/Configuration/Downstream/Tableau.md
> Sql api docs updates part 2

- rust/cubesql/Cargo.lock
- rust/cubesql/cubesql/Cargo.toml
- rust/cubesql/cubesql/e2e/tests/postgres.rs
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__df_escaped_strings.snap
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__df_fork_is_boolean.snap
> feat(cubesql): Support escaped string literals, E'str'

- rust/cubesql/cubesql/e2e/tests/postgres.rs
- rust/cubesql/cubesql/src/compile/parser.rs
- rust/cubesql/cubesql/src/sql/postgres/shim.rs
> feat(cubesql): Support multiple stmts for simple query in pg-wire

- packages/cubejs-backend-native/Cargo.lock
- rust/cubesql/cubesql/src/compile/engine/udf.rs
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__array_lower_column.snap
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__array_lower_scalar.snap
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__array_upper_column.snap
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__array_upper_scalar.snap
> feat(cubesql): Support array_upper, array_lower UDFs

- examples/d3-dashboard/dashboard-app/netlify.toml
- examples/d3-dashboard/dashboard-app/package.json
- examples/d3-dashboard/dashboard-app/yarn.lock
Fix critical dependabot alerts in D3 example.
> examples: update D3 Dashboard example deps

- examples/compare-date-range/dashboard-app/netlify.toml
- examples/compare-date-range/dashboard-app/package.json
- examples/compare-date-range/dashboard-app/src/components/Dashboard.js
- examples/compare-date-range/dashboard-app/src/components/Line.js
- examples/compare-date-range/dashboard-app/src/components/MultipleQueries.js
- examples/compare-date-range/dashboard-app/src/components/SingleQuery.js
- examples/compare-date-range/dashboard-app/yarn.lock
- examples/compare-date-range/yarn.lock
> examples(compare-date-range): update deps 

- examples/cognito/dashboard-app/package.json
- examples/cognito/dashboard-app/src/components/Header.js
- examples/cognito/dashboard-app/yarn.lock
- examples/cognito/package.json
- examples/cognito/yarn.lock
> examples(cognito): update deps

- examples/angular-dashboard-with-material-ui/dashboard-app/netlify.toml
- examples/angular-dashboard-with-material-ui/dashboard-app/package.json
- examples/angular-dashboard-with-material-ui/dashboard-app/yarn.lock
- examples/angular-dashboard-with-material-ui/yarn.lock
> examples(angular-dashboard): update deps

- examples/event-analytics/backend/yarn.lock
- examples/event-analytics/frontend/package.json
- examples/event-analytics/frontend/yarn.lock
> examples(event-analytics): update deps

- examples/auth0/dashboard-app/package.json
- examples/auth0/dashboard-app/yarn.lock
- examples/auth0/yarn.lock
> examples(auth0): update deps

- rust/cubesql/Cargo.lock
- rust/cubesql/cubesql/Cargo.toml
- rust/cubesql/cubesql/e2e/tests/postgres.rs
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/sql/mysql/service.rs
- rust/cubesql/cubesql/src/sql/postgres/extended.rs
- rust/cubesql/cubesql/src/sql/postgres/shim.rs
- rust/cubesql/cubesql/src/sql/server_manager.rs
- rust/cubesql/cubesql/src/sql/statement.rs
- rust/cubesql/cubesql/src/sql/types.rs
- rust/cubesql/pg-srv/src/protocol.rs
> feat: Support FETCH/DECLARE (cursors) for simple query in pg-wire

- examples/async-module-simple/yarn.lock
- examples/aws-web-analytics/analytics-dashboard/package.json
- examples/aws-web-analytics/analytics-dashboard/src/App.js
- examples/aws-web-analytics/analytics-dashboard/yarn.lock
- examples/data-blending/dashboard-app/netlify.toml
- examples/data-blending/dashboard-app/package.json
- examples/data-blending/dashboard-app/yarn.lock
- examples/graphql-api-metrics-dashboard/yarn.lock
- examples/stripe-dashboard/package.json
- examples/stripe-dashboard/yarn.lock
> examples: update deps

- rust/cubesql/Cargo.lock
- rust/cubesql/cubeclient/Cargo.toml
- rust/cubesql/cubeclient/README.md
- rust/cubesql/pg-srv/README.md
> chore: Publish cubeclient on crates.io

- examples/vue-dashboard/frontend/.eslintrc.js
- examples/vue-dashboard/frontend/.gitignore
- examples/vue-dashboard/frontend/package.json
- examples/vue-dashboard/frontend/src/App.vue
- examples/vue-dashboard/frontend/src/components/HelloWorld.vue
- examples/vue-dashboard/frontend/yarn.lock
> examples(vue-dashboard): update deps

- examples/real-time-dashboard/.dockerignore
- examples/real-time-dashboard/Dockerfile
- examples/real-time-dashboard/cube.js
- examples/real-time-dashboard/dashboard-app/.env.development
- examples/real-time-dashboard/dashboard-app/.env.production
- examples/real-time-dashboard/dashboard-app/netlify.toml
- examples/real-time-dashboard/dashboard-app/package.json
- examples/real-time-dashboard/dashboard-app/src/App.js
- examples/real-time-dashboard/dashboard-app/src/components/ChartRenderer.js
- examples/real-time-dashboard/dashboard-app/src/components/Header.js
- examples/real-time-dashboard/dashboard-app/src/index.js
- examples/real-time-dashboard/dashboard-app/src/pages/DashboardPage.js
- examples/real-time-dashboard/dashboard-app/yarn.lock
- examples/real-time-dashboard/package.json
- examples/real-time-dashboard/yarn.lock
- connection error to Cube Cloud
- Cube Cloud timeout error
- Cube Cloud API error
> examples(real-time-dashboard): fix errors

- packages/cubejs-jdbc-driver/src/JDBCDriver.js
> chore(jdbc-driver) testConnection method optimization

- rust/cubesql/cubesql/src/compile/engine/udf.rs
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__array_lower_column.snap
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__array_lower_scalar.snap
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__array_upper_column.snap
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__array_upper_scalar.snap
> fix(cubesql): array_lower, array_upper - correct behaviour

- .github/workflows/rust-cubesql.yml
> chore(cubesql): Speedup unit testing

- rust/cubesql/Cargo.lock
- rust/cubesql/cubesql/Cargo.toml
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__metabase_pg_namespace.snap
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__pg_catalog_udf_search_path.snap
> feat(cubesql): Support ArrayIndex for scalars

- packages/cubejs-databricks-jdbc-driver/src/DatabricksDriver.ts
>  feat(databricks-jdbc): export bucket for azure via databricks api v2.0

- packages/cubejs-databricks-jdbc-driver/package.json
- packages/cubejs-databricks-jdbc-driver/src/DatabricksDriver.ts
> fix(databricks-jdbc) concurrency and garbage collection

- rust/cubesql/Cargo.lock
- rust/cubesql/cubesql/Cargo.toml
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__cast_decimal_default_precision.snap
> feat(cubesql): cast DECIMAL with default precision and scale

- packages/cubejs-databricks-jdbc-driver/src/DatabricksDriver.ts
> fix(databricks-jdbc): concurrency improvements

- examples/helm-charts/cubejs/README.md
- examples/helm-charts/cubejs/templates/master/deployment.yaml
- examples/helm-charts/cubejs/templates/workers/deployment.yaml
- examples/helm-charts/cubejs/values.yaml
- examples/helm-charts/cubestore/README.md
- examples/helm-charts/cubestore/templates/router/statefulset.yaml
- examples/helm-charts/cubestore/templates/workers/statefulset.yaml
- examples/helm-charts/cubestore/values.yaml
**Check List**
Add imagePullSecrets in the K8s manifest.
> feat(helm-charts): Add imagePullSecrets in k8s manifest

- packages/cubejs-databricks-jdbc-driver/src/DatabricksDriver.ts
> fix(databricks-jdbc): docs

- docs/content/Configuration/Downstream/Superset.md
- docs/content/Configuration/Downstream/Superset.mdx
**Check List**
This PR updates the Superset page for downstream tools by adding a video and updating copy.
> docs(downstream): Update Superset

- packages/cubejs-backend-native/Cargo.lock
- rust/cubesql/cubesql/src/sql/postgres/shim.rs
- rust/cubesql/pg-srv/src/pg_type.rs
- rust/cubesql/pg-srv/src/protocol.rs
> fix(cubesql): Allow binary encoding for all types in pg-wire

- docs/content/Configuration/Connecting-to-Downstream-Tools.mdx
- docs/content/Configuration/Connecting-to-the-Database.mdx
- docs/content/Configuration/Databases/Presto.md
> docs: New layout for data stores

- docs/content/Configuration/Downstream/Appsmith.mdx
**Check List**
This PR adds a video guide on connecting Cube to Appsmith, and updates the copy accordingly.
> docs(downstream): Update Appsmith copy and video

- packages/cubejs-databricks-jdbc-driver/src/DatabricksDriver.ts
> fix(databricks-jdbc): decreasing timeouts between API calls

- rust/cubesql/cubesql/src/sql/postgres/extended.rs
- rust/cubesql/cubesql/src/sql/postgres/shim.rs
- rust/cubesql/pg-srv/src/protocol.rs
> fix(cubesql): Simple query: fetch in pg-wire (ODBC)

- packages/cubejs-api-gateway/src/gateway.ts
- packages/cubejs-testing/test/__snapshots__/driver-postgres.test.ts.snap
- packages/cubejs-testing/test/driver-test-suite.ts
> fix(api-gateway): correct calculation of total if there is a query property offset

- packages/cubejs-databricks-jdbc-driver/src/DatabricksDriver.ts
> feat(databricks-jdbc): improving performance

- packages/cubejs-databricks-jdbc-driver/src/DatabricksDriver.ts
> feat(databricks-jdbc): jdbc implementation of the export bucket feature

- packages/cubejs-docker/dev.Dockerfile
> fix(cubejs-docker): fix typos in dev.Dockerfile

- packages/cubejs-backend-shared/src/env.ts
- packages/cubejs-databricks-jdbc-driver/src/DatabricksDriver.ts
- packages/cubejs-jdbc-driver/src/JDBCDriver.js
> fix(databricks-jdbc): communication link failure

- docs/content/Configuration/Connecting-to-the-Database.mdx
- docs/content/Configuration/Databases/Druid.md
- docs/content/Configuration/Databases/Elasticsearch.mdx
- docs/content/Configuration/Databases/Hive.md
- docs/content/Configuration/Databases/MongoDB.mdx
- docs/content/Configuration/Databases/Oracle.md
- docs/content/Configuration/Databases/SQLite.md
> Updates to denote community supported drivers

- packages/cubejs-backend-native/Cargo.lock
- rust/cubesql/Cargo.lock
- rust/cubesql/cubesql/e2e/tests/postgres.rs
- rust/cubesql/cubesql/src/compile/parser.rs
- rust/cubesql/cubesql/src/sql/mysql/service.rs
- rust/cubesql/cubesql/src/sql/postgres/extended.rs
- rust/cubesql/cubesql/src/sql/postgres/shim.rs
- rust/cubesql/cubesql/src/sql/statement.rs
- rust/cubesql/pg-srv/Cargo.toml
- rust/cubesql/pg-srv/src/decoding.rs
- rust/cubesql/pg-srv/src/extended.rs
- rust/cubesql/pg-srv/src/lib.rs
- rust/cubesql/pg-srv/src/protocol.rs
Hello!
Few fixes to make Sigma Computing works.
Thanks
> feat(cubesql): Support bind for INT8 (text, binary)

- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs
- rust/cubesql/cubesql/src/compile/rewrite/rules/split.rs
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__metabase_table_exists.snap
- rust/cubesql/cubesql/src/transport/ctx.rs
Hello!
A small workaround to make Metabase work!
Thanks
> feat(cubesql): Workaround for Metabase introspection query

- examples/d3-dashboard/dashboard-app/src/index.js
> examples: fix D3 dashboard source code link

- docs/content/Configuration/Databases/Databricks-JDBC.mdx
- docs/content/Configuration/Databases/Snowflake.mdx
> docs(config): add documentation for enabling export bucket for Databricks

- docs/content/API-Reference/SQL-API.mdx
- docs/content/Configuration/Connecting-to-Downstream-Tools.mdx
- docs/content/Configuration/Downstream/Hex.md
- docs/content/Configuration/Downstream/Jupyter.md
- docs/content/Configuration/Downstream/PowerBI.md
- docs/content/Configuration/Downstream/Streamlit.md
- docs/content/Configuration/Downstream/Superset.mdx
- docs/content/Configuration/Downstream/Tableau.md
- docs/content/Examples-Tutorials-Recipes/Examples.md
- docs/src/pages/index.tsx
> Remove SQL API workshop banners

- docs/content/Caching/Using-Pre-Aggregations.mdx
> docs(caching): clarify that source database still requires write access when export bucket is used

- rust/cubesql/cubesql/src/sql/postgres/shim.rs
- rust/cubesql/pg-srv/src/protocol.rs
> fix(cubesql): Return error on execute for unknown portal in pg-wire

- docs/content/Configuration/Downstream/Appsmith.mdx
**Check List**
Update Loom link for Appsmith video.
> docs(config): updated appsmith video

- docs/content/Configuration/Multitenancy-Setup.mdx
**Check List**
- https://cube-js.slack.com/archives/C03KNR8SS9Y/p1655244471420619
- https://cube-js.slack.com/archives/CC0403RRR/p1654810028753909
> docs(config): improve multiple database-single schema multitenancy documentation

- rust/cubesql/cubesql/src/sql/dataframe.rs
- rust/cubesql/cubesql/src/sql/postgres/writer.rs
- rust/cubesql/pg-srv/src/buffer.rs
- rust/cubesql/pg-srv/src/decoding.rs
- rust/cubesql/pg-srv/src/encoding.rs
- rust/cubesql/pg-srv/src/extended.rs
- rust/cubesql/pg-srv/src/lib.rs
- rust/cubesql/pg-srv/src/pg_type.rs
- rust/cubesql/pg-srv/src/protocol.rs
> feat(pg-srv): Introduce ToPostgresqlValue trait (encoding)

- rust/cubesql/cubesql/src/sql/postgres/shim.rs
- rust/cubesql/pg-srv/src/buffer.rs
> feat(cubesql): Send parameters at one time at initial for pg-wire

- docs/content/Configuration/Databases/Databricks-JDBC.mdx
> docs(config): improve export bucket instructions for Databricks

- docs/content/Schema/Getting-Started.mdx
> docs: More languages support survey

- packages/cubejs-dbt-schema-extension/src/Dbt.ts
**Check List**
Handle when the name of the table is different than the name of the model
https://docs.getdbt.com/docs/building-a-dbt-project/building-models/using-custom-aliases
https://docs.getdbt.com/reference/resource-configs/alias
> feat: dbt metric take into account table alias

- docs/content/Examples-Tutorials-Recipes/Examples.md
> docs: Update texts

- docs/content/Schema/Reference/pre-aggregations.mdx
> docs(schema): document all valid granularity values

- docs/content/API-Reference/REST-API.mdx
> docs(reference): fix CURL POST example in REST API reference

- docs/content/Configuration/Downstream/Superset.mdx
- docs/content/Schema/Reference/pre-aggregations.mdx
> docs(schema): document `allowNonStrictDateRangeMatch`

- examples/auth0/dashboard-app/public/index.html
- examples/building-a-data-app-with-cube-workshop/dashboard-app/public/index.html
- examples/clickhouse-dashboard/dashboard-app/public/index.html
- examples/compare-date-range/dashboard-app/public/index.html
- examples/d3-dashboard/dashboard-app/public/index.html
- examples/data-blending/dashboard-app/public/index.html
- examples/drill-downs/dashboard-app/public/index.html
- examples/external-rollups/dashboard-app/public/index.html
- examples/graphql-api-metrics-dashboard/public/index.html
- examples/highcharts/dashboard-app/public/index.html
- examples/mapbox/dashboard-app/public/index.html
- examples/material-ui-dashboard/dashboard-app/public/index.html
- examples/multi-tenant-analytics/dashboard-app/public/index.html
- examples/multitenancy-workshop/dashboard-app/public/index.html
- examples/react-dashboard/dashboard-app/public/index.html
- examples/react-data-table/dashboard-app/public/index.html
- examples/react-muze/dashboard-app/public/index.html
- examples/react-pivot-table/dashboard-app/public/index.html
- examples/real-time-dashboard/dashboard-app/public/index.html
- examples/slack-vibe/frontend/public/index.html
- examples/supabase/dashboard-app/public/index.html
> examples: fix seo descriptions

- packages/cubejs-server-core/src/core/OptsHandler.ts
- packages/cubejs-server-core/test/unit/OptsHandler.test.ts
> fix(server-core): dbType assertion

- rust/cubesql/cubesql/src/compile/engine/information_schema/postgres/mod.rs
- rust/cubesql/cubesql/src/compile/engine/information_schema/postgres/role_column_grants.rs
- rust/cubesql/cubesql/src/compile/engine/information_schema/postgres/role_table_grants.rs
- rust/cubesql/cubesql/src/compile/engine/provider.rs
- rust/cubesql/cubesql/src/compile/engine/udf.rs
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__information_schema_role_column_grants_postgresql.snap
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__information_schema_role_table_grants_postgresql.snap
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__observable_grants.snap
Hello!
This functionality is required for Observable.
Thanks
> feat(cubesql): Support grant tables (columns, tables)

- docs/content/API-Reference/SQL-API.mdx
- docs/content/Configuration/Connecting-to-Downstream-Tools.mdx
- docs/content/Examples-Tutorials-Recipes/Examples.md
- docs/src/pages/index.tsx
> July workshop banner for docs pages

- packages/cubejs-server-core/src/core/OptsHandler.ts
> fix(server-core): driverFactory result type checking

- packages/cubejs-backend-shared/src/env.ts
- packages/cubejs-server-core/src/core/OptsHandler.ts
- packages/cubejs-server-core/src/core/OrchestratorApi.ts
- packages/cubejs-server-core/src/core/server.ts
- packages/cubejs-server-core/test/unit/OptsHandler.test.ts
- packages/cubejs-server-core/test/unit/RefreshScheduler.test.ts
- packages/cubejs-server-core/test/unit/index.test.ts
> feat(server-core): adding CUBEJS_PRE_AGGREGATIONS_BUILDER environment variable

- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/rewrite/rules/split.rs
Hello!
This PR introduces support for `Substring` usage in projection which is used in the Metabase BI.
Thanks
> feat(cubesql): Support substring for rewritting

- rust/cubestore/cubestore/src/metastore/mod.rs
**Check List**
Removing HLL columns from indexes
> fix(cubestore): removing HLL columns from indexes

- rust/cubestore/cubestore-sql-tests/src/tests.rs
- rust/cubestore/cubestore/src/queryplanner/planning.rs
**Check List**
Fix index selection in case of AND  in conditions
> fix(cubestore): Fix index selection in case of AND  in conditions

- packages/cubejs-backend-native/Cargo.lock
- rust/cubesql/Cargo.lock
- rust/cubesql/cubesql/Cargo.toml
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/rewrite/rules/members.rs
- rust/cubesql/cubesql/src/compile/rewrite/rules/split.rs
> feat(cubesql): Support DAY/DOW aggregations (Metabase)

- examples/helm-charts/cubejs/templates/master/deployment.yaml
- examples/helm-charts/cubejs/templates/workers/deployment.yaml
- examples/helm-charts/cubejs/values.yaml
- examples/helm-charts/cubestore/templates/router/statefulset.yaml
- examples/helm-charts/cubestore/templates/workers/statefulset.yaml
- examples/helm-charts/cubestore/values.yaml
**Check List**
Adds tolerations and nodeSelector to  the helm chart
> feat: adds node selector and tolerations

- rust/cubesql/cubesql/src/compile/engine/df/scan.rs
> chore(cubesql): Improve error message for unexpected response from Cube

- docs/content/Configuration/Connecting-to-Downstream-Tools.mdx
- docs/content/Configuration/Connecting-to-the-Database.mdx
- docs/content/Configuration/Databases/Druid.md
- docs/content/Configuration/Databases/Elasticsearch.mdx
- docs/content/Configuration/Databases/Hive.md
- docs/content/Configuration/Databases/MongoDB.mdx
- docs/content/Configuration/Databases/Oracle.md
- docs/content/Configuration/Databases/SQLite.md
> docs(config): remove community supported sub-section

- docs/content/Configuration/Downstream/PowerBI.md
**Check List**
corrected ‘microsof’ to ‘microsoft’
> Edits PowerBI docs to fix typo

- rust/cubesql/cubesql/src/compile/engine/udf.rs
- rust/cubesql/cubesql/src/compile/mod.rs
- fix binary operations with negative hour/minute/second intervals
- handle February
- handle leap year
> fix(cubesql): Binary operations with dates and intervals

- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/rewrite/rules/split.rs
Hello!
In the previous PR I've added support for BinaryExpr with `+` operator:
https://github.com/cube-js/cube.js/commit/2565705fcff6a3d3dc4ff5ac2dcd819d8ad040db#diff-7dc005dcca36d622711495451619971bf9af578e1f4e84871047603a52027f70R571
This PR allows to do `+`, `-`, `/` and `*` excluding `* 0`.
Thanks
> feat(cubesql): Support minus, multiply, division for binary expr in projection

- rust/cubesql/cubesql/src/compile/engine/udf.rs
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__has_schema_privilege.snap
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__quicksight_has_schema_privilege_query.snap
**Check List**
This PR adds support for `has_schema_privilege` PostgreSQL UDF that is used by QuickSight. It also adds related tests.
> feat(cubesql): Support `has_schema_privilege` UDF

- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/rewrite/rules/split.rs
> feat(cubesql): Metabase - support Summarize's Bins

- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs
- `WHERE (lower(column) like '%value%')`
- `WHERE (NOT (lower(column) like '%value%') OR column IS NULL)`
> feat(cubesql): Metabase string contains / not contains filters

- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs
Metabase filters:
- `where column between 10 and 20`
- `where column not between 10 and 20`
> feat(cubesql): Metabase - support between numbers queries

- rust/cubesql/cubesql/src/compile/rewrite/converter.rs
> chore(cubesql): Mark members as nullable

- rust/cubesql/Cargo.lock
- rust/cubesql/cubesql/Cargo.toml
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__quicksight_table_cat_query.snap
**Check List**
This PR bumps DataFusion, fixing UDTF behavior when no batch sections are present. It also adds a test to a related query used by QuickSight.
> fix(cubesql): Correct UDTF behavior with no batch sections

- docs/content/Configuration/Connecting-to-Downstream-Tools.mdx
- docs/content/Configuration/Downstream/Appsmith.mdx
- docs/content/Configuration/Downstream/Bubble.mdx
- docs/content/Configuration/Downstream/Budibase.mdx
- docs/content/Configuration/Downstream/Deepnote.mdx
- docs/content/Configuration/Downstream/Hex.mdx
- docs/content/Configuration/Downstream/Observable.mdx
- docs/content/Configuration/Downstream/Retool.mdx
- docs/content/Configuration/Downstream/Superset.mdx
- docs/content/Configuration/Downstream/Tableau.mdx
**Check List**
N/A
This PR updates the existing content in the docs pages for Observable and Deepnote and adds a REST API section for Observable as mentioned here https://github.com/cube-js/cube.js/pull/4936#issuecomment-1188915333
> docs(downstream): update deepnote and observable

- rust/cubestore/cubestore/src/queryplanner/query_executor.rs
- rust/cubestore/cubestore/src/queryplanner/serialized_plan.rs
**Check List**
Removing unused tables from the worker plans
> fix(cubestore): Optimize big plans send out for big number of workers

- docs/content/Configuration/Downstream/Deepnote.mdx
- docs/content/Configuration/Downstream/Observable.mdx
**Check List**
N/A
This PR adds video embeds for Deepnote and Observable.
> docs(downstream): add videos for deepnote and observable

- docs/content/Configuration/Connecting-to-Downstream-Tools.mdx
- docs/content/Configuration/Downstream/Metabase.mdx
- docs/static/icons/metabase.svg
**Check List**
N/A
This PR adds a page for Metabase under downstream BI tools.
> docs(downstream): add metabase page

- packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts
- packages/cubejs-testing/.gitignore
> fix(query-orchestrator): API instance throw on missing partitions

- packages/cubejs-server-core/src/core/OrchestratorApi.ts
- packages/cubejs-server-core/test/unit/OptsHandler.test.ts
> fix(server-core): restoring health check for the API instances

- DEPRECATION.md
- docs/content/Caching/Using-Pre-Aggregations.mdx
- docs/content/Configuration/Config.mdx
- docs/content/Configuration/Multitenancy-Setup.mdx
- docs/content/Schema/Reference/cube.mdx
> docs(config): deprecate `dbType` and update examples

- packages/cubejs-databricks-jdbc-driver/bin/installer.js
- packages/cubejs-databricks-jdbc-driver/bin/post-install
- packages/cubejs-databricks-jdbc-driver/src/installer.ts
> fix(databricks-jdbc): postinstall script with accept_policy env

- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/rewrite/rules/split.rs
> feat(cubesql): Metabase - support Summarize by week of year

- packages/cubejs-server-core/src/core/OrchestratorApi.ts
- packages/cubejs-server-core/test/unit/OptsHandler.test.ts
> feat(server-core): disable health checks for API instances with rollup only mode

- packages/cubejs-backend-shared/src/env.ts
- packages/cubejs-databricks-jdbc-driver/src/DatabricksDriver.ts
> feat(databricks-jdbc): UserAgentEntry property configuration for the databricks-jdbc driver

- docs/content/API-Reference/SQL-API.mdx
- docs/content/Configuration/Config.mdx
- docs/content/Configuration/Environment-Variables-Reference.md
> docs(sql): How to change security context for SQL API

- docs/content/API-Reference/SQL-API.mdx
- docs/content/Configuration/Connecting-to-Downstream-Tools.mdx
- docs/content/Examples-Tutorials-Recipes/Examples.md
- docs/src/pages/index.tsx
> [Chore] Remove July workshop banners from docs pages

- examples/helm-charts/cubestore/README.md
- examples/helm-charts/cubestore/templates/common-env.tpl
- examples/helm-charts/cubestore/templates/pvc.yaml
- examples/helm-charts/cubestore/templates/router/statefulset.yaml
- examples/helm-charts/cubestore/templates/workers/statefulset.yaml
- examples/helm-charts/cubestore/values.yaml
**Check List**
Add values to cubestore Helm manifests to configure cloud storage with minio
> examples(helm-charts): Add values to configure minio

- examples/helm-charts/cubejs/templates/common-env.tpl
**Check List**
Hey, I fixed a small typo on the chart.js Helm repo. There were 14 lines where the `.Values` was missing the trailing **s**
> examples(helm-charts): Replacing wrong key Value with the correct one: Values

- docs/content/Deployment/Overview.mdx
- docs/content/Deployment/Platform-Cube-Cloud.mdx
- docs/content/Deployment/Platform-Docker.mdx
- docs/content/Deployment/Platform-Kubernetes.mdx
- docs/content/Deployment/Platform-Serverless-AWS.mdx
- docs/content/Deployment/Platform-Serverless-Google.mdx
> docs: Update warning boxes for serverless deployments

- docs/content/Caching/Overview.mdx
- docs/content/Caching/Running-in-Production.mdx
- docs/content/Deployment/Overview.mdx
- docs/content/Deployment/Production-Checklist.mdx
> docs: Add messages that Cube Store will replace Redis

- rust/cubesql/cubesql/src/sql/postgres/shim.rs
Hello!
IO's Errors produced `UnexpectedEOF` or `BrokenPipe` produce a lot of noise, let's log about that in the trace level only.
Thanks
> fix(cubesq): Ignore BrokenPipe/UnexpectedEOF as error in pg-wire

- docs/content/Configuration/Downstream/Bubble.mdx
- docs/content/Configuration/Downstream/Deepnote.mdx
- docs/content/Configuration/Downstream/Hex.mdx
- docs/content/Configuration/Downstream/Jupyter.mdx
- docs/content/Configuration/Downstream/Metabase.mdx
- docs/content/Configuration/Downstream/Observable.mdx
- docs/content/Configuration/Downstream/PowerBI.md
- docs/content/Configuration/Downstream/Streamlit.mdx
- docs/content/Configuration/Downstream/Superset.mdx
- docs/content/Configuration/Downstream/Tableau.mdx
**Check List**
N/A
Added videos for Jupyter, Streamlit, and Metabase.
Edited image width for all downstream pages.
Edited REST API explanation for Observable.
> docs(downstream): Update videos, images, and content

- rust/cubesql/cubesql/src/compile/engine/context.rs
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__pg_set_app_show.snap
- rust/cubesql/cubesql/src/sql/database_variables/mod.rs
- rust/cubesql/cubesql/src/sql/server_manager.rs
- rust/cubesql/cubesql/src/sql/session.rs
> refactor(cubesql): Variables handling for ServerManager/Sessions

- rust/cubesql/cubesql/src/sql/postgres/shim.rs
> fix(cubesql): Ignore IO's UnexpectedEof|BrokenPipe on handling error

- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/rewrite/rules/dates.rs
- rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs
- rust/cubesql/cubesql/src/compile/rewrite/rules/split.rs
- Aggregate by measures fix
- min/max by date
> Fix(cubesql): Metabase - range of date aggregation and date filter fixes

- rust/cubestore/cubestore-sql-tests/src/tests.rs
- rust/cubestore/cubestore/src/import/mod.rs
> fix(cubestore): Support a space separated binary strings for varbinary fields in csv

- packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts
- packages/cubejs-query-orchestrator/src/orchestrator/QueryCache.ts
> fix(query-orchestrator): excessive buildRange queries

- packages/cubejs-backend-shared/src/env.ts
- packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts
- packages/cubejs-query-orchestrator/test/unit/QueryOrchestrator.test.js
- packages/cubejs-server-core/src/core/OptsHandler.ts
- packages/cubejs-server-core/src/core/optionsValidate.ts
- packages/cubejs-server-core/src/core/types.ts
> feat: max partitions per cube configuration

- rust/cubesql/cubesql/src/compile/engine/information_schema/mod.rs
- rust/cubesql/cubesql/src/compile/engine/information_schema/redshift/mod.rs
- rust/cubesql/cubesql/src/compile/engine/information_schema/redshift/svv_tables.rs
- rust/cubesql/cubesql/src/compile/engine/provider.rs
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/parser.rs
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__redshift_svv_tables.snap
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__thought_spot_tables.snap
> feat(cubesql): Support svv_tables (Redshift)

- packages/cubejs-backend-native/Cargo.lock
- rust/cubesql/Cargo.lock
- rust/cubesql/cubesql/Cargo.toml
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/rewrite/language.rs
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__df_fork_bitwise_shit.snap
Hello!
This PR introduces support for `>>` and `<<` which is used in ThoughtSpot.
Thanks
> feat(cubesql): Support binary bitwise operators (>>, <<)

- rust/cubestore/Cargo.lock
- rust/cubestore/cubestore-sql-tests/src/tests.rs
- rust/cubestore/cubestore/src/queryplanner/pretty_printers.rs
> fix(cubestore): Fix panic in rolling window processing

- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs
> feat(cubesql): Datastudio - string startWith filter support

- package.json
> chore: link:dev

- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/rewrite/converter.rs
- rust/cubesql/cubesql/src/compile/rewrite/rules/dates.rs
- rust/cubesql/cubesql/src/compile/rewrite/rules/members.rs
- rust/cubesql/cubesql/src/compile/rewrite/rules/split.rs
> feat(cubesql): Datastudio - Min/Max datetime aggregation support

- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/rewrite/converter.rs
- rust/cubesql/cubesql/src/compile/rewrite/rules/dates.rs
- rust/cubesql/cubesql/src/compile/rewrite/rules/members.rs
- rust/cubesql/cubesql/src/compile/rewrite/rules/split.rs
> feat(cubesql): Datastudio - aggr by month and day support

- docs/content/Cube-Cloud/Getting-Started/Overview.mdx
- docs/content/Cube-Cloud/Index.mdx
- docs/content/Deployment/Overview.mdx
- docs/content/Deployment/Platform-Cube-Cloud.mdx
- docs/content/Getting-Started/Overview.mdx
- docs/src/pages/index.tsx
> docs(chore): August workshop banner to docs pages

- packages/cubejs-backend-shared/src/enums.ts
- packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
- packages/cubejs-schema-compiler/src/adapter/MssqlQuery.js
- packages/cubejs-schema-compiler/test/integration/mssql/mssql-pre-aggregations.test.ts
- packages/cubejs-schema-compiler/test/unit/mssql-query.test.ts
- packages/cubejs-schema-compiler/test/unit/utils.ts
**Check List**
[#573](https://github.com/cube-js/cube.js/issues/573)
> feat(schema-compiler): aggregate sub query group by clause

- packages/cubejs-client-vue3/src/QueryBuilder.js
Signed-off-by: José Luis Di Biase <josx@interorganic.com.ar>
**Check List**
#5082 
Add a method for removing Offset
Thanks to @florblue for showing this bug.
> fix(@cubejs-client/vue3): fix removeOffset warning (#5082)

- .github/workflows/rust-cubesql.yml
- packages/cubejs-sqlite-driver/package.json
- packages/cubejs-testing/birdbox-fixtures/postgresql/schema/SecurityContextTest.js
- packages/cubejs-testing/birdbox-fixtures/postgresql/single/sqlapi.js
- packages/cubejs-testing/package.json
- packages/cubejs-testing/src/birdbox.ts
- packages/cubejs-testing/test/__snapshots__/smoke-cubesql.test.ts.snap
- packages/cubejs-testing/test/smoke-cubesql.test.ts
- yarn.lock
> test(cubesql): Introduce E2E tests for SQL API

- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs
> feat(cubesql): Datastudio - between dates filter support

- packages/cubejs-server-core/src/core/DriverResolvers.ts
- packages/cubejs-server-core/src/core/OptsHandler.ts
- packages/cubejs-server-core/src/core/server.ts
- packages/cubejs-server-core/test/unit/OptsHandler.test.ts
> fix(server-core): determining custom drivers from the cube.js file

- rust/cubesql/Cargo.lock
- rust/cubesql/cubesql/Cargo.toml
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/rewrite/language.rs
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__df_fork_coalesce.snap
> feat(cubesql): Support COALESCE function

- packages/cubejs-server-core/src/core/server.ts
- packages/cubejs-server-core/test/unit/OptsHandler.test.ts
> fix(server-core): driverCache removed

- .github/workflows/push.yml
- packages/cubejs-api-gateway/src/query.js
- packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts
- packages/cubejs-testing/birdbox-fixtures/smoke/cube.js
- packages/cubejs-testing/birdbox-fixtures/smoke/schema/Orders.js
- packages/cubejs-testing/birdbox-fixtures/smoke/schema/OrdersPA.js
- packages/cubejs-testing/package.json
- packages/cubejs-testing/src/birdbox.ts
- packages/cubejs-testing/test/smoke-lambda.test.ts
- packages/cubejs-testing/test/smoke-postgres.test.ts
**Check List**
N/A
* Fixes pre-aggregations/partitions to return build_range_end only when defined.
* Fixes pre-aggregations/partitions to accept build_range_end parameter.
> fix(cubejs): Fixes build_range_end for preaggregatons REST API 

- packages/cubejs-docker/latest-debian-jdk.Dockerfile
- packages/cubejs-docker/latest.Dockerfile
> chore(docker): debian version updates

- packages/cubejs-cubestore-driver/src/CubeStoreDriver.ts
**Check List**
N/A
Fixes CubeStoreDriver user/password auth
> fix(cubejs): Fixes CubeStoreDriver user/password auth

- packages/cubejs-cubestore-driver/src/CubeStoreDriver.ts
> chore(cubejs): Fix tracing of CubeStore tables upload

- rust/cubesql/cubesql/src/compile/mod.rs
Hello!
Some analytics queries (non-system tables) can fail on the physical planning step because DF optimizes (second time) logical_plan, but DF optimizers are not ready to optimize plans created by our RTS.
Thanks
> feat(cubesql): Disable optimizers for analytics queries

- rust/cubestore/cubestore/src/telemetry/mod.rs
> chore(cubestore): Http transport for telemetry

- docs/content/Configuration/Databases/Databricks-JDBC.mdx
> docs(config): document `CUBEJS_DB_DATABRICKS_AGENT` and `CUBEJS_DB_DATABRICKS_TOKEN`

- packages/cubejs-backend-native/Cargo.lock
- rust/cubesql/Cargo.lock
- rust/cubesql/cubesql/Cargo.toml
- rust/cubesql/cubesql/src/compile/mod.rs
Hello!
WITH provides a way to write auxiliary statements for use in a larger query. These statements, which are often referred to as Common Table Expressions or CTEs, can be thought of as defining temporary tables that exist just for one query.
This feature is required for ThoughtSpot.
Thanks
> feat: Support usage of CTE (with realiasing)

- docs/content/Configuration/Config.mdx
- docs/content/Configuration/Environment-Variables-Reference.md
> docs(config): document how to set maximum partitions for a pre-aggregation

- packages/cubejs-databricks-jdbc-driver/src/DatabricksDriver.ts
> fix(databricks-jdbc): databricks user-agent

- docs/content/Caching/Using-Pre-Aggregations.mdx
- docs/content/Schema/Reference/pre-aggregations.mdx
> docs(caching): document aggregating indexes functionality

- docs/content/Cube-Cloud/Access Control.mdx
> docs(cloud): document Role-based Access Control for Cube Cloud

- examples/helm-charts/cubejs/README.md
- examples/helm-charts/cubejs/templates/_helpers.tpl
- examples/helm-charts/cubejs/templates/master/deployment.yaml
- examples/helm-charts/cubejs/templates/master/serviceaccount.yaml
- examples/helm-charts/cubejs/templates/workers/deployment.yaml
- examples/helm-charts/cubejs/templates/workers/serviceaccount.yaml
- examples/helm-charts/cubejs/values.yaml
- examples/helm-charts/cubestore/README.md
- examples/helm-charts/cubestore/templates/_helpers.tpl
- examples/helm-charts/cubestore/templates/router/serviceaccount.yaml
- examples/helm-charts/cubestore/templates/router/statefulset.yaml
- examples/helm-charts/cubestore/templates/workers/serviceaccount.yaml
- examples/helm-charts/cubestore/templates/workers/statefulset.yaml
- examples/helm-charts/cubestore/values.yaml
**Check List**
Add values to helm manifests to configure Pod serviceAccount
> feat(helm-charts): add values to configure service account

- rust/cubesql/cubesql/src/compile/engine/information_schema/mysql/processlist.rs
- rust/cubesql/cubesql/src/compile/engine/information_schema/postgres/pg_stat_activity.rs
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/lib.rs
- rust/cubesql/cubesql/src/sql/mysql/service.rs
- rust/cubesql/cubesql/src/sql/postgres/service.rs
- rust/cubesql/cubesql/src/sql/postgres/shim.rs
- rust/cubesql/cubesql/src/sql/session_manager.rs
Hello!
This PR doesn't provide new functionallity or bug fix.
Thanks
> refactor(cubesql): Use Async lock for Server's sessions

- rust/cubesql/cubesql/src/compile/engine/information_schema/postgres/pg_prepared_statements.rs
- rust/cubesql/cubesql/src/sql/postgres/extended.rs
- rust/cubesql/cubesql/src/sql/postgres/shim.rs
- rust/cubesql/cubesql/src/sql/session.rs
> refactor(cubesql): Rework definition of PreparedStatement

- rust/cubesql/cubesql/e2e/tests/postgres.rs
- rust/cubesql/cubesql/src/sql/postgres/shim.rs
> feat(cubesql): Allow to setup any dbname for pg-wire

- docs/content/Deployment/Platform-Docker.mdx
> docs(deployment): fix faulty Cube Store worker configuration

- rust/cubesql/Cargo.lock
- rust/cubesql/cubesql/Cargo.toml
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__test_sort_relations_0.snap
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__test_sort_relations_1.snap
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__test_sort_relations_2.snap
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__test_sort_relations_3.snap
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__test_sort_relations_4.snap
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__test_sort_relations_5.snap
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__test_sort_relations_6.snap
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__test_sort_relations_7.snap
> chore(cubesql): Solve sort node schema column names conflicts

- docs/content/Cube-Cloud/Configuration/Custom-Domains.mdx
- docs/content/Cube-Cloud/Configuration/VPC/Connecting-with-a-VPC.mdx
Story details: https://app.clubhouse.io/cube-dev/story/220
> docs(cloud): add Custom Domains page

- rust/cubestore/cubestore/src/remotefs/gcs.rs
- rust/cubestore/cubestore/src/remotefs/minio.rs
- rust/cubestore/cubestore/src/remotefs/mod.rs
- rust/cubestore/cubestore/src/remotefs/queue.rs
- rust/cubestore/cubestore/src/remotefs/s3.rs
> chore(cubestore): Refactoring  of checking of uploaded files

- docs/content/Cube-Cloud/Getting-Started/Overview.mdx
- docs/content/Cube-Cloud/Index.mdx
- docs/content/Deployment/Overview.mdx
- docs/content/Deployment/Platform-Cube-Cloud.mdx
- docs/content/Getting-Started/Overview.mdx
- docs/src/pages/index.tsx
> docs(chore): Remove workshop banner from docs pages

- docs/content/Cube-Cloud/Configuration/Custom-Domains.mdx
> docs(cloud): add note to Custom Domains page about DNS timeouts

- packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts
- packages/cubejs-query-orchestrator/test/unit/QueryOrchestrator.test.js
> fix(query-orchestrator): delete temp tables

- rust/cubesql/cubesql/src/compile/engine/udf.rs
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__has_schema_privilege_default_user.snap
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__holistics_schema_privilege_query.snap
Support for one of the introspection queries
> feat(cubesql): Holistics - support schema privilege query

- packages/cubejs-backend-native/Cargo.lock
- rust/cubesql/Cargo.lock
- rust/cubesql/cubesql/Cargo.toml
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__df_fork_nullif.snap
Hello!
Before this PR we had two implementations for `nullif` function in DF. One for `utf8`/`largeutf8` and the default one from DataFushion, but both implementations didn't support scalars at all before this PR. 
Thanks
> feat(cubesql): Support nullif with scalars

- packages/cubejs-firebolt-driver/src/FireboltDriver.ts
**Check List**
This PR adds handling of [refresh access tokens](https://docs.firebolt.io/developing-with-firebolt/firebolt-rest-api.html#refresh-access-tokens) after receiving the 401 status code for the query.
> chore(firebolt-driver): refresh access token on expiration

- docs/content/Cube-Cloud/Configuration/VPC/Connecting-with-a-VPC-Azure.mdx
- docs/content/Cube-Cloud/Configuration/VPC/Connecting-with-a-VPC.mdx
**Check List**
Add docs regarding Azure peering
> feat(docs): add azure peering documentation

- packages/cubejs-backend-native/Cargo.lock
- rust/cubesql/Cargo.lock
- rust/cubesql/cubesql/Cargo.toml
- rust/cubesql/cubesql/src/compile/engine/udf.rs
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__df_fork_cast_date32_additional_formats.snap
> feat(cubesql): Support yearly granularity (ThoughtSpot)

- rust/cubestore/cubestore/src/remotefs/queue.rs
- rust/cubestore/cubestore/src/scheduler/mod.rs
- rust/cubestore/cubestore/src/sql/mod.rs
> fix(cubestore): Fix 'no such file or directory' after cubestore restart

- docs/content/Configuration/Config.mdx
- docs/content/Configuration/Extending-Cubejs.mdx
> docs(config): document `initApp()` configuration property

- docs/content/Caching/Using-Pre-Aggregations.mdx
> docs(caching): document `EXPLAIN` and `EXPLAIN ANALYZE` for Cube Store

- rust/cubestore/cubestore/src/cluster/mod.rs
> chore(cubestore): Don't warmup in memory chunks

- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/parser.rs
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__holistics_in_subquery_query.snap
- One of the introspection queries
> feat(cubesql): Holistics - support in subquery introspection query

- packages/cubejs-databricks-jdbc-driver/src/DatabricksDriver.ts
- packages/cubejs-elasticsearch-driver/driver/ElasticSearchDriver.js
- packages/cubejs-hive-driver/driver/HiveDriver.js
- packages/cubejs-materialize-driver/src/MaterializeDriver.ts
- packages/cubejs-mssql-driver/driver/MSSqlDriver.js
- packages/cubejs-mysql-aurora-serverless-driver/driver/AuroraServerlessMySqlDriver.js
- packages/cubejs-oracle-driver/driver/OracleDriver.js
- packages/cubejs-prestodb-driver/driver/PrestoDriver.js
- packages/cubejs-sqlite-driver/driver/SqliteDriver.js
> fix: driver's constructor parameters initializers

- examples/hasura-remote-schema-with-cube/dashboard-app/.env
- examples/hasura-remote-schema-with-cube/dashboard-app/src/components/LineChart.jsx
- examples/hasura-remote-schema-with-cube/dashboard-app/src/components/LoadingIndicator.jsx
- examples/hasura-remote-schema-with-cube/dashboard-app/src/components/LoadingIndicator.module.css
- examples/hasura-remote-schema-with-cube/dashboard-app/src/index.html
- examples/hasura-remote-schema-with-cube/dashboard-app/src/index.js
> examples(blogpost): updated hasura+cube

- packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
- packages/cubejs-schema-compiler/test/integration/postgres/sql-generation.test.ts
- packages/cubejs-schema-compiler/test/unit/base-query.test.ts
> fix(schema-compiler): messed order in sub-query aggregate

- .github/workflows/examples-publish.yml
- examples/hasura-remote-schema-with-cube/dashboard-app/.netlify/state.json
- examples/hasura-remote-schema-with-cube/dashboard-app/package.json
- examples/hasura-remote-schema-with-cube/dashboard-app/src/index.html
- examples/hasura-remote-schema-with-cube/dashboard-app/yarn.lock
example - https://hasura-remote-schema-example.netlify.app
--
**Check List**
> examples: setup hasura remote schema example deployment

- .github/workflows/examples-publish.yml
> examples: skip cube deployment for hasura example

- rust/cubesql/Cargo.lock
- rust/cubesql/cubesql/Cargo.toml
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/sql/statement.rs
> feat(cubesql): Holistics - GROUP BY dates support

- .github/workflows/publish.yml
- packages/cubejs-docker/latest-alpine.Dockerfile
- packages/cubejs-docker/latest-debian-jdk.Dockerfile
- packages/cubejs-docker/latest.Dockerfile
> fix: freeze node.js dependencies for images

- packages/cubejs-backend-native/Cargo.lock
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs
> feat(cubesql): Support IN for __user

- CONTRIBUTING.md
> chore: CONTRIBUTING.md

- packages/cubejs-firebolt-driver/package.json
- packages/cubejs-firebolt-driver/src/FireboltDriver.ts
- packages/cubejs-firebolt-driver/tsconfig.json
- yarn.lock
**Check List**
This pr adds user agent tracking, passing the client name “Cube” and client version into the Node SDK
> feature (firebolt-driver) pass driver version and client name

- packages/cubejs-backend-shared/src/env.ts
- packages/cubejs-databricks-jdbc-driver/src/DatabricksDriver.ts
> fix(databricks-driver): remove env user agent 

- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs
> fix(cubesql): LOWER(?column) IN (?literal) (ThoughtSpot)

- docs/content/Configuration/Databases/Databricks-JDBC.mdx
- docs/content/Configuration/Databases/Firebolt.mdx
> docs(config): remove `CUBEJS_DB_DATABRICKS_AGENT`

- docs/content/API-Reference/GraphQL-API.mdx
> docs(api): add note to GraphQL API about lack of variable support

- examples/hasura-remote-schema-with-cube/dashboard-app/src/index.js
> examples(blog post): edit hasura+cube demo app

- docs/content/Configuration/Multitenancy-Setup.mdx
> docs(config): update `driverFactory()` examples in Multitenancy

- docs/content/Configuration/Config.mdx
> docs(config): document `processSubscriptionsInterval` configuration option

- docs/content/Configuration/Databases/Databricks-JDBC.mdx
> docs(config): make `CUBEJS_DB_DATABRICKS_TOKEN` required for Databricks driver

- docs/content/Configuration/Config.mdx
> docs(config): add warning about `FileRepository` only using files from a single directory

- docs/content/Caching/Using-Pre-Aggregations.mdx
> docs(caching): add note about export bucket requiring `CREATE TABLE` permission

- docs/content/API-Reference/REST-API.mdx
> docs(api): add pagination instructions to REST API reference

- docs/content/Configuration/Databases/QuestDB.mdx
> docs(config): add missing QuestDB link

- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs
**Check List**
This PR adds support for date filtering within one granularity unit, allowing `WHERE` clauses like `date_trunc('day', column) = date_trunc('day', to_timestamp(…))`.
It also adds a related test with a sample query used by QuickSight for all supported granularities.
> feat(cubesql): Support date filtering within one granularity unit

- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs
> feat(cubesql): Holistics - string not contains filter

- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs
**Check List**
This PR adds support for several QuickSight custom filters applicable to strings and numbers: `startsWith`, `endsWith`, `contains`, and `notContains`.
It also adds related tests.
> feat(cubesql): Support QuickSight string/number filters

- rust/cubesql/cubesql/src/compile/engine/udf.rs
- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/rewrite/analysis.rs
- rust/cubesql/cubesql/src/compile/rewrite/mod.rs
- rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs
- rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__ends_with.snap
> feat(cubesql): starts_with, ends_with, LOWER(?column) = ?literal

- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/parser.rs
- rust/cubesql/cubesql/src/sql/mysql/service.rs
- rust/cubesql/cubesql/src/sql/postgres/shim.rs
- rust/cubesql/cubesql/src/telemetry/mod.rs
- refactor logging sanitized query
- add sanitized query to log message
> refactor(cubesql): logging sanitized query

- packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
- packages/cubejs-schema-compiler/src/adapter/PreAggregations.js
- packages/cubejs-schema-compiler/src/compiler/CubeSymbols.js
- packages/cubejs-schema-compiler/src/compiler/CubeValidator.js
- packages/cubejs-schema-compiler/test/unit/pre-aggregations.test.ts
- packages/cubejs-testing/birdbox-fixtures/lambda/schema/Orders.js
> feat: Introduce `rollupLambda` rollup type

- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs
Hello!
Previusly `LOWER(?column) IN (?literal)` was supported only with `__user` field, but PR introduces support for simple dimensions.
Thanks
> feat(cubesql): Support LOWER(?column) IN (?literal) for dimensions

- .github/workflows/examples-publish.yml
- examples/ksql/dashboard-app/.netlify/state.json
> examples: ksqldb deploy

- packages/cubejs-client-core/index.d.ts
- packages/cubejs-server-core/src/core/RefreshScheduler.ts
- packages/cubejs-testing/test/smoke-lambda.test.ts
> chore: Fix system queries for rollupLambda

- docs/content/Configuration/Environment-Variables-Reference.md
> docs(config): fix broken link to Database Connection guide

- packages/cubejs-databricks-jdbc-driver/src/DatabricksQuery.ts
> fix(databricks-driver): using the ILIKE operator in the DatabricksFilter.likeIgnoreCase method

- packages/cubejs-schema-compiler/src/adapter/PreAggregations.js
- packages/cubejs-testing/birdbox-fixtures/lambda/schema/Orders.js
- packages/cubejs-testing/test/smoke-lambda.test.ts
> fix: Invalid identifier day for month `lambdaRollup`

- rust/cubestore/cubestore/src/cluster/worker_pool.rs
> fix(cubestore): Fix error: Internal: channel closed on the next request after cubestore cloud process got OOM

- examples/apollo-federation-with-cube/dashboard-app/src/index.js
- examples/apollo-federation-with-cube/dashboard-app/src/utils/utils.js
> examples(apollo): update naming

- examples/apollo-federation-with-cube/apollo-server-app/graphql/supergraph.graphql
- examples/apollo-federation-with-cube/apollo-server-app/graphql/supergraph.yaml
- examples/apollo-federation-with-cube/apollo-server-app/src/gateway.js
- examples/apollo-federation-with-cube/dashboard-app/.env
> examples(apollo): Add HTTPS to updated graphs

- .github/workflows/examples-publish.yml
- examples/apollo-federation-with-cube/dashboard-app/.netlify/state.json
> examples: enable apollo-federation example deploy

- examples/apollo-federation-with-cube/apollo-server-app/docker-compose.yaml
- examples/apollo-federation-with-cube/apollo-server-app/graphql/router.yaml
- examples/apollo-federation-with-cube/dashboard-app/.env
- examples/apollo-federation-with-cube/dashboard-app/src/index.html
> examples(apollo): add apollo router

- packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts
> fix(query-orchestrator): pre-aggs build range queries cache key alignment

- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs
` select * from table where lower(column) in ('a', 'b');`
> fix(cubesql): WHERE Lower / Upper in list with multiply items

- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/rewrite/cost.rs
- support composite queries with __user
> fix(cubesql): Metabase - substring __user

- rust/cubesql/cubesql/src/compile/mod.rs
- rust/cubesql/cubesql/src/compile/rewrite/rules/split.rs
**supported charts:**
- pivot table
- area chart
- line chart
- column chart
- bar chart
- combine chart
> feat(cubesql): Holistics - support range of charts

- packages/cubejs-schema-compiler/src/compiler/CubeSymbols.js
> fix(schema-compiler): throw an error for the empty pre-aggs

- packages/cubejs-postgres-driver/src/PostgresDriver.ts
- packages/cubejs-postgres-driver/test/PostgresDriver.test.ts
> fix(postgres-driver): release method should not throw

- examples/ksql/dashboard-app/src/components/Header.js
> examples: fix ksql demo dashboard

- examples/building-an-open-source-data-stack-with-clickhouse-and-cube-workshop/cube.js
- examples/building-an-open-source-data-stack-with-clickhouse-and-cube-workshop/dashboard-app-multi-tenancy/src/components/BarChart.jsx
- examples/building-an-open-source-data-stack-with-clickhouse-and-cube-workshop/dashboard-app-multi-tenancy/src/index.js
- examples/building-an-open-source-data-stack-with-clickhouse-and-cube-workshop/dashboard-app-multi-tenancy/src/utils/utils.js
- examples/building-an-open-source-data-stack-with-clickhouse-and-cube-workshop/dashboard-app-multiple-data-sources/src/components/BarChart.jsx
- examples/building-an-open-source-data-stack-with-clickhouse-and-cube-workshop/dashboard-app-multiple-data-sources/src/index.html
- examples/building-an-open-source-data-stack-with-clickhouse-and-cube-workshop/dashboard-app-multiple-data-sources/src/index.js
- examples/building-an-open-source-data-stack-with-clickhouse-and-cube-workshop/dashboard-app-multiple-data-sources/src/utils/utils.js
> examples(altinity-workshop): add query filters

- examples/building-an-open-source-data-stack-with-clickhouse-and-cube-workshop/cube.js
> examples(altinity-workshop): Update demos

- examples/building-an-open-source-data-stack-with-clickhouse-and-cube-workshop/dashboard-app-multiple-data-sources/src/utils/utils.js
> examples(altinity-workshop): edit chart labels

- packages/cubejs-schema-compiler/src/compiler/CubeEvaluator.js
- packages/cubejs-schema-compiler/src/compiler/CubeSymbols.js
- packages/cubejs-schema-compiler/src/compiler/CubeValidator.js
- packages/cubejs-schema-compiler/src/compiler/transpilers/CubePropContextTranspiler.ts
- packages/cubejs-schema-compiler/test/integration/postgres/cube-views.test.ts
> feat: Includes and Excludes directives for Cube Views

- packages/cubejs-server-core/src/core/OrchestratorApi.ts
**Check List**
Added log message after connection test completed successfully
> fix: Added connection test completed successfully log

- packages/cubejs-base-driver/src/driver.interface.ts
- packages/cubejs-ksql-driver/src/KsqlDriver.ts
- packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts
- packages/cubejs-query-orchestrator/test/unit/QueryOrchestrator.test.js
- rust/cubestore/cubestore/src/lib.rs
- rust/cubestore/cubestore/src/metastore/mod.rs
- rust/cubestore/cubestore/src/scheduler/mod.rs
- rust/cubestore/cubestore/src/streaming/mod.rs
> fix: Temp tables dropped for ksql after successfully created

- rust/cubestore/Cargo.lock
- rust/cubestore/cubestore-sql-tests/src/tests.rs
> fix(cubestore): Extension planner for LogicalAlias error

- packages/cubejs-api-gateway/src/gateway.ts
- packages/cubejs-api-gateway/src/helpers/transformData.ts
- packages/cubejs-api-gateway/test/helpers/transformData.test.ts
- packages/cubejs-api-gateway/test/mocks.ts
- packages/cubejs-schema-compiler/src/compiler/CubeEvaluator.js
- packages/cubejs-schema-compiler/src/compiler/CubeToMetaTransformer.js
- packages/cubejs-schema-compiler/src/compiler/CubeValidator.js
- packages/cubejs-schema-compiler/test/integration/postgres/cube-views.test.ts
- packages/cubejs-testing/birdbox-fixtures/driver-test-data/ECommerce.js
- packages/cubejs-testing/birdbox-fixtures/postgresql-cubestore.yml
- packages/cubejs-testing/birdbox-fixtures/postgresql.yml
- packages/cubejs-testing/package.json
- packages/cubejs-testing/src/birdbox.ts
- packages/cubejs-testing/test/__snapshots__/driver-postgres.test.ts.snap
- packages/cubejs-testing/test/driver-postgres.test.ts
- packages/cubejs-testing/test/driver-test-suite.ts
- packages/cubejs-testing/test/driverTests/testSets.ts
- packages/cubejs-testing/test/driverTests/tests.ts
> feat: `shown` flag for cubes and views

- rust/cubestore/cubestore-sql-tests/src/tests.rs
- rust/cubestore/cubestore/src/queryplanner/mod.rs
> chore(cubestore): Small refactoring
