cube-js/cube

docs/content/Caching/Lambda-Pre-Aggregations.mdx, docs/content/Schema/Reference/pre-aggregations.mdx
=> docs(schema): document `unionWithSourceData` and `rollupLambda`

rust/cubestore/cubestore/src/telemetry/mod.rs
**Check List**
Add headers to telemetry request
=> feat(cubestore): CC-1133 - add headers to telemetry request

examples/multitenancy-workshop/dashboard-app/src/App.js, examples/multitenancy-workshop/dashboard-app/yarn.lock
=> Examples fix multitenancy workshop

.github/workflows/publish.yml
=> fix(docker): Use yarn.lock

packages/cubejs-snowflake-driver/package.json, yarn.lock
Hello!
Refs https://github.com/snowflakedb/snowflake-connector-nodejs/commit/cf918c5c73dcf06f90da94a2b958b6670b2824ac
Thanks
=> fix(snowflake-driver): Upgrade snowflake-sdk (bug with aws deps)

examples/aws-web-analytics/analytics-dashboard/src/App.js
=> examples: remove legacy logo from aws example

package.json, yarn.lock
=> chore: Remove unused old packages, fix #5117

rust/cubesql/cubesql/src/compile/mod.rs
**Check List**
This PR adds a cast split aliasing-related test query to ensure that the query works in the future.
Original problem:
```sql
select
q1.datetrunc_8 datetrunc_8,
q1.cast_timestamp_to_datetime_10 cast_timestamp_to_datetime_10 -- See below
/*q1.v_11 v_11*/ -- See below
from (
select
date_trunc('second', "completedAt"::timestamptz) datetrunc_8,
"completedAt"::timestamptz cast_timestamp_to_datetime_10 -- This runs fine by itself but does not work as part of FROM subquery
/*1 v_11*/ -- Error during rewrite: 'v_11' expression can't be coerced to any members of 'Orders' cube.
from "public"."Orders" "Orders"
) q1
```
=> test(cubesql): Add a cast split aliasing-related test

examples/apollo-federation-with-cube/apollo-server-app/readme.md, examples/apollo-federation-with-cube/dashboard-app/src/index.html
=> examples(apollo): Updates for GraphOS

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/test/mocks.ts, packages/cubejs-testing/birdbox-fixtures/driver-test-data/HiddenECommerce.js, packages/cubejs-testing/test/driver-test-suite.ts, packages/cubejs-testing/test/driverTests/driverTest.ts, packages/cubejs-testing/test/driverTests/testSets.ts, packages/cubejs-testing/test/driverTests/tests.ts
=> fix: Remove empty hidden cubes from meta

packages/cubejs-server/src/server/container.ts
=> chore: rename Cube.js server to Cube API server

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-testing/birdbox-fixtures/driver-test-data/ECommerce.js, packages/cubejs-testing/test/driverTests/testSets.ts
=> fix: Revert back strict shown checks behavior for consistency reasons

rust/cubestore/Cargo.lock, rust/cubestore/cubestore-sql-tests/src/tests.rs
=> fix(cubestore): Fix streaming index

rust/cubestore/cubestore/src/queryplanner/partition_filter.rs
=> fix(cubestore): Fix partition pruning

packages/cubejs-schema-compiler/src/compiler/CubeValidator.js, packages/cubejs-schema-compiler/test/integration/postgres/yaml-compiler.test.ts, packages/cubejs-schema-compiler/test/unit/transpilers.test.ts
=> fix: Cannot read property 'apply' of undefined on missed dimension sql

docs/content/Configuration/Databases/Snowflake.mdx
=> docs(config): update Snowflake documentation to link to account identifiers

rust/cubestore/Cargo.lock, rust/cubestore/cubestore-sql-tests/src/tests.rs
=> fix(cubestore): Merge for streaming union

packages/cubejs-schema-compiler/src/compiler/CubeSymbols.js, packages/cubejs-schema-compiler/src/compiler/DataSchemaCompiler.js, packages/cubejs-schema-compiler/test/integration/postgres/yaml-compiler.test.ts, packages/cubejs-schema-compiler/test/unit/PrepareCompiler.js, packages/cubejs-server-core/src/core/FileRepository.ts
=> feat: YAML snake case and `.yaml` extension support

packages/cubejs-prestodb-driver/index.js, packages/cubejs-prestodb-driver/package.json, packages/cubejs-trino-driver/index.js, packages/cubejs-trino-driver/package.json
=> fix: Make Trino driver CommonJS compatible

docs/content/Configuration/Extending-Cubejs.mdx
reference: https://www.npmjs.com/package/winston-loggly-bulk
**Check List**
=> fix: typo for loggly

.github/workflows/push.yml, packages/cubejs-mssql-driver/driver/MSSqlDriver.js, packages/cubejs-testing-shared/src/db/index.ts, packages/cubejs-testing-shared/src/db/mssql.ts, packages/cubejs-testing/birdbox-fixtures/mssql/schema/Orders.js, packages/cubejs-testing/package.json, packages/cubejs-testing/src/REQUIRED_ENV_VARS.ts, packages/cubejs-testing/src/birdbox.ts, packages/cubejs-testing/test/__snapshots__/smoke-mssql.test.ts.snap, packages/cubejs-testing/test/smoke-mssql.test.ts
=> feat(@cubejs-backend/mssql-driver): Make MSSQL `readOnly` by default

rust/cubestore/cubestore/src/scheduler/mod.rs, rust/cubestore/cubestore/src/sql/mod.rs
=> chore(cubestore): Fix compaction schedule

packages/cubejs-cubestore-driver/src/CubeStoreDriver.ts
=> chore: Avoiding replaceAll call

package.json, yarn.lock
=> chore: Bump learn to ^4

docs/content/Configuration/Databases/Databricks-JDBC.mdx, packages/cubejs-databricks-jdbc-driver/src/DatabricksDriver.ts, packages/cubejs-databricks-jdbc-driver/src/installer.ts
=> feat(databricks-jdbc): jdbc driver update (jar)

docs/content/Configuration/Databases/Databricks-JDBC.mdx, packages/cubejs-databricks-jdbc-driver/src/DatabricksDriver.ts, packages/cubejs-databricks-jdbc-driver/src/installer.ts
=> Revert "feat(databricks-jdbc): jdbc driver update (jar)"

docs/content/Configuration/Databases/Databricks-JDBC.mdx, packages/cubejs-databricks-jdbc-driver/src/DatabricksDriver.ts, packages/cubejs-databricks-jdbc-driver/src/installer.ts
=> feat(databricks-jdbc): jdbc (jar) driver update (#5612)

packages/cubejs-druid-driver/src/DruidQuery.ts, packages/cubejs-druid-driver/test/druid-query.test.ts
**Check List**
Respect day light saving time in druid driver
=> fix(druid-driver): respect day light saving

docs/content/Caching/Getting-Started-Pre-Aggregations.md, docs/content/Examples-Tutorials-Recipes/Recipes/active-users.md, docs/content/Examples-Tutorials-Recipes/Recipes/column-based-access.md, docs/content/Examples-Tutorials-Recipes/Recipes/entity-attribute-value.md, docs/content/Examples-Tutorials-Recipes/Recipes/event-analytics.md, docs/content/Examples-Tutorials-Recipes/Recipes/funnels.md, docs/content/Examples-Tutorials-Recipes/Recipes/getting-unique-values-for-a-field.md, docs/content/Examples-Tutorials-Recipes/Recipes/non-additivity.md, docs/content/Examples-Tutorials-Recipes/Recipes/passing-dynamic-parameters-in-a-query.md, docs/content/Examples-Tutorials-Recipes/Recipes/role-based-access.md, docs/content/Examples-Tutorials-Recipes/Recipes/using-different-schemas-for-tenants.md, docs/content/Examples-Tutorials-Recipes/Recipes/using-dynamic-measures.md, docs/content/Schema/Advanced/Code-Reusability-Extending-Cubes.mdx, docs/content/Schema/Advanced/Polymorphic-Cubes.md, docs/content/Schema/Fundamentals/Additional-Concepts.mdx, docs/content/Schema/Fundamentals/Concepts.mdx, docs/content/Schema/Fundamentals/Working-with-Joins.mdx, docs/content/Schema/Reference/cube.mdx, docs/content/Schema/Reference/joins.mdx, examples/recipes/column-based-access/cube.js, examples/recipes/column-based-access/schema/Products.js, examples/recipes/column-based-access/schema/Suppliers.js, examples/recipes/entity-attribute-value/schema/Orders.js, examples/recipes/entity-attribute-value/schema/Users.js
=> docs: update all examples with cube foreign references

rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs
**Check List**
This PR fixes an issue with `limit-push-down-projection` rule pushing down to projection, forcing the new projection to be split with `split-reaggregate-projection`, which forces the limit to push down again, creating an infinite loop.
A test for a sample query is included: `SELECT col FROM (SELECT col FROM tbl LIMIT 10001) tbl LIMIT 10001`.
=> fix(cubesql): Prevent infinite limit push down

rust/cubestore/Cargo.lock, rust/cubestore/cubestore-sql-tests/src/tests.rs
=> fix: Incorrect filter pushdown when filtering two left-joined tables

packages/cubejs-backend-shared/src/env.ts, packages/cubejs-backend-shared/test/db_env_multi.test.ts, packages/cubejs-backend-shared/test/db_env_single.test.ts, packages/cubejs-base-driver/src/BaseDriver.ts, packages/cubejs-base-driver/src/driver.interface.ts, packages/cubejs-databricks-jdbc-driver/src/DatabricksDriver.ts, packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts, packages/cubejs-query-orchestrator/test/unit/QueryOrchestrator.test.js
=> feat: catalog support for the Databricks driver

docs/src/templates/DocTemplate.tsx
=> docs: use proper class "docContent" for algolia crawler

rust/cubesql/Cargo.lock, rust/cubesql/cubesql/Cargo.toml, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/split.rs, rust/cubesql/cubesql/src/sql/statement.rs
**Check List**
This PR adds support for ThoughtSpot search filter, as in typing the dimension values in search field. A related test is added.
=> feat(cubesql): Support ThoughtSpot search filters

docs/package.json, docs/yarn.lock
=> docs: downgrade sitemap plugin to match gatsby version

rust/cubestore/Cargo.lock, rust/cubestore/cubestore-sql-tests/src/tests.rs, rust/cubestore/cubestore/src/cluster/mod.rs, rust/cubestore/cubestore/src/config/mod.rs, rust/cubestore/cubestore/src/metastore/job.rs, rust/cubestore/cubestore/src/metastore/mod.rs, rust/cubestore/cubestore/src/metastore/rocks_store.rs
=> chore(cubestore): Long term jobs

rust/cubestore/Cargo.lock, rust/cubestore/cubestore-sql-tests/src/tests.rs, rust/cubestore/cubestore/src/cluster/mod.rs, rust/cubestore/cubestore/src/cluster/worker_pool.rs, rust/cubestore/cubestore/src/config/mod.rs, rust/cubestore/cubestore/src/metastore/job.rs, rust/cubestore/cubestore/src/metastore/mod.rs, rust/cubestore/cubestore/src/metastore/rocks_store.rs, rust/cubestore/cubestore/src/queryplanner/query_executor.rs, rust/cubestore/cubestore/src/queryplanner/tail_limit.rs, rust/cubestore/cubestore/src/queryplanner/topk/execute.rs, rust/cubestore/cubestore/src/telemetry/mod.rs, rust/cubestore/cubestore/src/telemetry/tracing.rs, rust/cubestore/cubestore/src/util/respawn.rs
=> chore(cubestore): Tracing improvements

rust/cubesql/Cargo.lock, rust/cubesql/cubesql/Cargo.toml, rust/cubesql/cubesql/src/compile/legacy_compiler.rs, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/analysis.rs, rust/cubesql/cubesql/src/compile/rewrite/converter.rs, rust/cubesql/cubesql/src/compile/rewrite/language.rs, rust/cubesql/cubesql/src/compile/rewrite/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/members.rs, rust/cubesql/cubesql/src/sql/statement.rs
**Check List**
This PR adds support for Thoughtspot include filter search feature, as well as the ability to select items to be included and excluded in the query. It also adds related tests.
=> feat(cubesql): Support Thoughtspot include filter search

packages/cubejs-databricks-jdbc-driver/src/DatabricksDriver.ts
=> fix(databricks-jdbc): Databricks pre-aggregations schema with UC

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/test/index.test.ts
…ery against a selected datasource
**Check List**
=> feat(cubejs-api-gateway): added endpoint to run sql query directly

rust/cubesql/cubesql/src/compile/rewrite/rewriter.rs
**Check List**
This PR adds `CUBESQL_DISABLE_REWRITES` environment variable, which is a comma-separated list of rewrite rules that should be ignored, which is helpful for debugging the graph.
=> chore(cubesql): Add env variable to disable specific rewrite rules

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/src/query.js, packages/cubejs-backend-shared/src/env.ts, packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
=> feat: query limits

packages/cubejs-jdbc-driver/src/JDBCDriver.ts
=> fix(jdbc-driver): set default encoding (utf-8)

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-server-core/src/core/CompilerApi.js, packages/cubejs-server-core/test/unit/index.test.ts
=> feat(api-gateway, server-core): Added dataSources list to extended meta

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/test/index.test.ts
=> Revert "feat(cubejs-api-gateway): added endpoint to run sql query directly"

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-server-core/src/core/CompilerApi.js, packages/cubejs-server-core/test/unit/index.test.ts
=> Revert "feat(api-gateway, server-core): Added dataSources list to extended meta"

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-query-orchestrator/package.json, packages/cubejs-query-orchestrator/src/orchestrator/BaseQueueDriver.ts, packages/cubejs-query-orchestrator/src/orchestrator/LocalQueueDriver.js, packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts, packages/cubejs-query-orchestrator/src/orchestrator/QueryCache.ts, packages/cubejs-query-orchestrator/src/orchestrator/QueryQueue.js, packages/cubejs-query-orchestrator/src/orchestrator/RedisQueueDriver.js, packages/cubejs-query-orchestrator/src/orchestrator/utils.ts, packages/cubejs-query-orchestrator/test/unit/QueryCache.abstract.ts, packages/cubejs-query-orchestrator/test/unit/QueryOrchestrator.test.js, packages/cubejs-query-orchestrator/test/unit/QueryQueue.abstract.ts
=> feat: persistent queue

rust/cubestore/cubestore/src/metastore/rocks_fs.rs, rust/cubestore/cubestore/src/metastore/rocks_store.rs
=> chore(cubestore): Small metastore refactoring

packages/cubejs-api-gateway/src/gateway.ts
=> fix(api-gateway): pre-aggregations/jobs auth middleware

packages/cubejs-backend-native/Cargo.lock, packages/cubejs-schema-compiler/src/adapter/BaseQuery.js, packages/cubejs-schema-compiler/src/compiler/CubeToMetaTransformer.js, packages/cubejs-schema-compiler/src/compiler/CubeValidator.js, packages/cubejs-schema-compiler/test/integration/postgres/sql-generation.test.ts, packages/cubejs-schema-compiler/test/unit/cube-validator.test.ts, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/members.rs, rust/cubesql/cubesql/src/compile/test/mod.rs, rust/cubesql/cubesql/src/transport/ext.rs
=> feat: Support `string`, `time` and `boolean` measures

packages/cubejs-backend-shared/src/env.ts, packages/cubejs-cubestore-driver/src/WebSocketConnection.ts
=> fix: Error: WebSocket is not open: readyState 2 (CLOSING)

rust/cubestore/cubestore/src/sql/cache.rs
=> chore(cubestore): Separation of queue and result caches

README.md
=> Remove Discourse link from readme

rust/cubestore/cubestore/src/cachestore/cache_rocksstore.rs, rust/cubestore/cubestore/src/metastore/mod.rs, rust/cubestore/cubestore/src/metastore/rocks_store.rs, rust/cubestore/cubestore/src/metastore/rocks_table.rs
=> chore(cubestore): Improve migration support

.github/workflows/push.yml, packages/cubejs-testing/package.json
=> chore(tests): Enable Athena smoke test

rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs
**Check List**
This PR improves compatibility with Thoughtspot by supporting expressions used in `WHERE` by Thoughtspot:
- Is null or equal to a value (`WHERE NOT(dimension IS NULL OR LOWER(dimension) IN ('literal', 'values'))`)
- Equality with `NOT NULL` as `IN (TRUE, FALSE)` (`WHERE (LOWER(dimension) = 'value1' OR LOWER(dimension) = 'value2') IN (TRUE, FALSE)`)
=> fix(cubesql): Improve Thoughtspot `WHERE IN` support

rust/cubestore/Cargo.lock, rust/cubestore/cubestore-sql-tests/Cargo.toml, rust/cubestore/cubestore-sql-tests/src/benches.rs, rust/cubestore/cubestore-sql-tests/src/tests.rs, rust/cubestore/cubestore/src/cachestore/cache_item.rs, rust/cubestore/cubestore/src/cachestore/cache_rocksstore.rs, rust/cubestore/cubestore/src/cachestore/compaction.rs, rust/cubestore/cubestore/src/cachestore/mod.rs, rust/cubestore/cubestore/src/config/mod.rs, rust/cubestore/cubestore/src/metastore/mod.rs, rust/cubestore/cubestore/src/metastore/rocks_store.rs, rust/cubestore/cubestore/src/metastore/rocks_table.rs, rust/cubestore/cubestore/src/queryplanner/info_schema/info_schema_schemata.rs, rust/cubestore/cubestore/src/queryplanner/info_schema/info_schema_tables.rs, rust/cubestore/cubestore/src/queryplanner/info_schema/mod.rs, rust/cubestore/cubestore/src/queryplanner/info_schema/system_cache.rs, rust/cubestore/cubestore/src/queryplanner/info_schema/system_chunks.rs, rust/cubestore/cubestore/src/queryplanner/info_schema/system_indexes.rs, rust/cubestore/cubestore/src/queryplanner/info_schema/system_jobs.rs, rust/cubestore/cubestore/src/queryplanner/info_schema/system_partitions.rs, rust/cubestore/cubestore/src/queryplanner/info_schema/system_replay_handles.rs, rust/cubestore/cubestore/src/queryplanner/info_schema/system_tables.rs, rust/cubestore/cubestore/src/queryplanner/mod.rs, rust/cubestore/cubestore/src/sql/mod.rs, rust/cubestore/cubestore/src/sql/parser.rs
Hello!
This PR introduces support for CACHE (key, value) storage in Cubestore + driver for Cube.
Supported commands:
```
CACHE GET
CACHE SET [NX] [TTL ?number] key value
CACHE REMOVE
CACHE TRUNCATE
CACHE KEYS
```
refs https://github.com/cube-js/cube.js/issues/5042
Thanks
=> feat(cubestore): Initial support for KV cache

docs/src/components/Header/Desktop.tsx
=> Remove the Discourse icon from docs page

rust/cubestore/cubestore/src/cluster/mod.rs, rust/cubestore/cubestore/src/metastore/mod.rs, rust/cubestore/cubestore/src/queryplanner/serialized_plan.rs, rust/cubestore/cubestore/src/sql/mod.rs, rust/cubestore/cubestore/src/store/compaction.rs, rust/cubestore/cubestore/src/store/mod.rs
=> chore(cubestore): Bulk chunk meta load

rust/cubestore/js-wrapper/src/download.ts
Hello!
https://github.com/cube-js/cube.js/actions/runs/3789874146/jobs/6444029806
Thanks
=> feat(cubestore): Download binary without GH API

packages/cubejs-client-core/package.json
=> fix(client-core): move @babel/runtime to dependencies

rust/cubestore/cubestore/src/cachestore/cache_rocksstore.rs, rust/cubestore/cubestore/src/config/mod.rs, rust/cubestore/cubestore/src/metastore/mod.rs, rust/cubestore/cubestore/src/metastore/rocks_fs.rs, rust/cubestore/cubestore/src/sql/mod.rs, rust/cubestore/cubestore/src/store/compaction.rs, rust/cubestore/cubestore/src/store/mod.rs
=> fix(cubestore): Maintain minimum count of metastore snapshots

rust/cubestore/cubestore/src/metastore/mod.rs, rust/cubestore/cubestore/src/metastore/rocks_fs.rs, rust/cubestore/cubestore/src/metastore/rocks_store.rs, rust/cubestore/cubestore/src/metastore/snapshot_info.rs, rust/cubestore/cubestore/src/queryplanner/info_schema/mod.rs, rust/cubestore/cubestore/src/queryplanner/info_schema/system_snapshots.rs, rust/cubestore/cubestore/src/queryplanner/mod.rs, rust/cubestore/cubestore/src/sql/mod.rs, rust/cubestore/cubestore/src/sql/parser.rs
=> feat(cubestore): Set metastore current snapshot system command

packages/cubejs-docker/dev-alpine.Dockerfile, packages/cubejs-docker/dev.Dockerfile, packages/cubejs-docker/latest-alpine-jdk.Dockerfile, packages/cubejs-docker/latest-alpine.Dockerfile, packages/cubejs-docker/latest-debian-jdk.Dockerfile, packages/cubejs-docker/latest.Dockerfile, packages/cubejs-docker/local.Dockerfile
=> feat(docker): Upgrade Node.js to 14.21.1

rust/cubesql/cubesql/src/sql/dataframe.rs, rust/cubesql/cubesql/src/sql/postgres/extended.rs
=> feat(cubesql): Improve memory usage in writting for pg-wire

packages/cubejs-athena-driver/src/AthenaDriver.ts, packages/cubejs-testing/test/smoke-athena.test.ts
=> fix(athena-driver): TypeError: table.join is not a function

rust/cubesql/Cargo.lock, rust/cubesql/cubesql/Cargo.toml, rust/cubesql/cubesql/e2e/tests/postgres.rs, rust/cubesql/cubesql/src/sql/postgres/shim.rs
=> fix(cubesql): Query cancellation for simple query protocol

packages/cubejs-api-gateway/src/SubscriptionServer.ts, packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/src/interfaces.ts, packages/cubejs-api-gateway/src/types/gateway.ts, packages/cubejs-backend-shared/src/env.ts, packages/cubejs-server-core/package.json, packages/cubejs-server-core/src/core/OptsHandler.ts, packages/cubejs-server-core/src/core/optionsValidate.ts, packages/cubejs-server-core/src/core/server.ts, packages/cubejs-server-core/src/core/types.ts, packages/cubejs-server-core/test/unit/index.test.ts, packages/cubejs-server/src/server.ts, packages/cubejs-server/src/server/container.ts
=> feat: Hooks for the context rejection mechanism

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/test/index.test.ts, packages/cubejs-api-gateway/test/mocks.ts
**Check List**
Added result filters for sql-runner
=> feat(api-gateway): added result filter for sql-runner

packages/cubejs-backend-native/src/channel.rs, packages/cubejs-backend-native/test/server.js
=> feat(native): Channel.resolve/reject without lock

.github/actions/init-ci/action.yaml, .github/workflows/birdbox.yml, .github/workflows/cloud.yml, .github/workflows/docs-publish.yml, .github/workflows/docs.yml, .github/workflows/examples-publish.yml, .github/workflows/issue-labeler.yml, .github/workflows/master.yml, .github/workflows/pr.yml, .github/workflows/publish.yml, .github/workflows/push-cross-images.yml, .github/workflows/push.yml, .github/workflows/rust-cubesql.yml, .github/workflows/rust-cubestore-master.yml, .github/workflows/rust-cubestore.yml
=> chore(ci): Upgrade actions

rust/cubestore/cubestore/src/sql/cache.rs
=> fix(cubestore): Large memory consumption while waiting for the queue cache

rust/cubestore/cubestore/src/sql/cache.rs, rust/cubestore/cubestore/src/sql/mod.rs
=> fix(cubestore): Large memory consumption while waiting for the queue cache: drop context

packages/cubejs-backend-shared/src/time.ts, packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts, packages/cubejs-query-orchestrator/test/unit/QueryOrchestrator.test.js, packages/cubejs-schema-compiler/src/adapter/BaseQuery.js, packages/cubejs-schema-compiler/src/adapter/PreAggregations.js, packages/cubejs-testing/birdbox-fixtures/lambda/schema/Orders.js, packages/cubejs-testing/test/smoke-lambda.test.ts
=> feat: Multiple rollups in `rollupLambda` support

packages/cubejs-schema-compiler/src/adapter/PreAggregations.js, packages/cubejs-server-core/src/core/RefreshScheduler.ts, packages/cubejs-server-core/test/unit/RefreshScheduler.test.ts, packages/cubejs-testing/test/smoke-lambda.test.ts
=> feat: Pre-aggregations API for `rollupLambda` support

rust/cubestore/cubestore/src/queryplanner/flatten_union.rs, rust/cubestore/cubestore/src/queryplanner/mod.rs, rust/cubestore/cubestore/src/sql/mod.rs
=> fix(cubestore): Panic for nested `UNION ALL`

packages/cubejs-server-core/src/core/server.ts
=> chore: shouldAcceptWs not bound

rust/cubestore/cubestore/src/queryplanner/flatten_union.rs, rust/cubestore/cubestore/src/sql/mod.rs
=> fix(cubestore): Panic on combination of `Union All` and single select in root `Union All`

packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts, packages/cubejs-query-orchestrator/test/unit/QueryOrchestrator.test.js
=> fix: Do not update structure version on build range end update

docs/content/Configuration/Advanced/Multiple-Data-Sources.mdx
=> docs(config): fix examples for multiple data source with environment variables

packages/cubejs-client-react/index.d.ts
=> docs(frontend): document the `query` prop correctly

docs/content/Frontend-Integrations/Real-Time-Data-Fetch.md, packages/cubejs-client-core/index.d.ts
=> docs(frontend): show how to unsubscribe from subscriptions

.github/workflows/push.yml, package.json, packages/cubejs-base-driver/src/queue-driver.interface.ts, packages/cubejs-cubestore-driver/package.json, packages/cubejs-cubestore-driver/src/CubeStoreQueueDriver.ts, packages/cubejs-cubestore-driver/src/index.ts, packages/cubejs-mysql-driver/package.json, packages/cubejs-query-orchestrator/DEVELOPMENT.md, packages/cubejs-query-orchestrator/src/orchestrator/BaseQueueDriver.ts, packages/cubejs-query-orchestrator/src/orchestrator/LocalQueueDriver.js, packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts, packages/cubejs-query-orchestrator/src/orchestrator/QueryOrchestrator.ts, packages/cubejs-query-orchestrator/src/orchestrator/QueryQueue.js, packages/cubejs-query-orchestrator/src/orchestrator/RedisPool.ts, packages/cubejs-query-orchestrator/src/orchestrator/RedisQueueDriver.js, packages/cubejs-query-orchestrator/test/integration/cubestore/QueryCacheCubestore.test.ts, packages/cubejs-query-orchestrator/test/integration/cubestore/QueryQueueCubestore.test.ts, packages/cubejs-query-orchestrator/test/unit/QueryCache.abstract.ts, packages/cubejs-query-orchestrator/test/unit/QueryQueue.abstract.ts, packages/cubejs-server-core/src/core/OrchestratorApi.ts, yarn.lock
Hello!
It's an initial version of the cube store queue driver.
refs https://github.com/cube-js/cube.js/issues/5042
```mermaid
sequenceDiagram
participant BackgroundQueryQueue
participant QueueQueue
participant QueueDriverInterface
participant CubeStore
QueueQueue->>QueueDriverInterface: getResult
QueueDriverInterface->>+CubeStore: QUEUE RESULT ?
QueueDriverInterface-->>+QueueQueue: QueryResult|null
deactivate CubeStore
QueueQueue->>QueueDriverInterface: addToQueue
QueueDriverInterface->>+CubeStore: QUEUE ADD PRIORITY N key payload
QueueDriverInterface-->>+QueueQueue: AddToQueueResponse
loop reconcileQueueImpl
QueueQueue->>QueueDriverInterface: getQueriesToCancel
QueueQueue->>QueueDriverInterface: getQueryAndRemove
QueueDriverInterface->>CubeStore: QUEUE TO_CANCEL ?stalled_timeout …
```
=> feat(query-orchestrator): Introduce CubeStoreQueueDriver

packages/cubejs-cubestore-driver/src/CubeStoreQueueDriver.ts, rust/cubestore/cubestore/src/cachestore/cache_rocksstore.rs, rust/cubestore/cubestore/src/cachestore/compaction.rs, rust/cubestore/cubestore/src/cachestore/lazy.rs, rust/cubestore/cubestore/src/cachestore/queue_item.rs, rust/cubestore/cubestore/src/metastore/rocks_table.rs, rust/cubestore/cubestore/src/sql/mod.rs
=> chore: Some improvements for Cube Store queue

rust/cubestore/cubestore/src/app_metrics.rs, rust/cubestore/cubestore/src/sql/mod.rs, rust/cubestore/cubestore/src/sql/parser.rs
=> feat(cubestore): Collect metrics for queue/cache commands

packages/cubejs-backend-native/js/index.ts, packages/cubejs-backend-shared/src/env.ts, packages/cubejs-query-orchestrator/src/orchestrator/QueryStream.ts
=> feat: streaming desync

packages/cubejs-cubestore-driver/src/CubeStoreQueueDriver.ts
=> fix(cubestore-driver): Unexpected token u in JSON at position 0

rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/members.rs
**Check List**
This PR fixes an issue with CubeScan aliases being resolved only with `push-down-projection` but not `push-down-projection-to-empty-scan`. This fixes issues that arise with ProjectionDropOut optimizer that removes realiasing projections, so `push-down-projection` is not applicable in those cases.
As this merely updates the way things tick with benefit to a future PR and no additionally supported queries are introduced, this PR contains no related tests.
=> chore(cubesql): Re-resolve CubeScan aliases

rust/cubesql/Cargo.lock, rust/cubesql/cubesql/Cargo.toml, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__explain-2.snap
**Check List**
This PR enables the `ProjectionDropOut` optimizer which removes redundant realiasing projections and merge aggregates where appropriate.
As this PR aims to improve on plan simplicity without targeting any specific query but rather the existing test suite, no extra tests are included.
=> chore(cubesql): Enable `ProjectionDropOut` optimizer

packages/cubejs-query-orchestrator/test/unit/QueryQueue.abstract.ts, rust/cubestore/cubestore-sql-tests/src/tests.rs, rust/cubestore/cubestore/src/cachestore/cache_rocksstore.rs, rust/cubestore/cubestore/src/cachestore/queue_item.rs
=> feat(cubestore): Support multiple parallel QUEUE RESULT_BLOCKING

rust/cubestore/Cargo.lock, rust/cubestore/cubestore/Cargo.toml
=> feat(cubestore): Upgrade warp to 0.3.3 (use crates.io)

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/test/index.test.ts, packages/cubejs-api-gateway/test/mocks.ts, packages/cubejs-server-core/src/core/CompilerApi.js, packages/cubejs-server-core/test/unit/index.test.ts
=> feat(api-gateway, server-core): Added dataSources method

packages/cubejs-query-orchestrator/src/orchestrator/QueryQueue.js, packages/cubejs-query-orchestrator/src/orchestrator/QueryStream.ts
=> fix(query-orchestrator): streams cluster

rust/cubestore/cubestore/src/sql/mod.rs
=> feat(cubestore): Correct metrics for queue/cache (ignore long commands)

packages/cubejs-server-core/src/core/server.ts
=> chore: move ApiGateway creation into a factory method

rust/cubestore/cubestore/src/streaming/kafka.rs, rust/cubestore/cubestore/src/streaming/mod.rs
=> feat(cubestore): Filters for data from kafka streams

.github/workflows/publish.yml, .github/workflows/rust-cubestore-master.yml, .github/workflows/rust-cubestore.yml
=> fix(cubestore): Support macOS 11 for standalone binary

rust/cubestore/cubestore/src/cluster/mod.rs, rust/cubestore/cubestore/src/config/mod.rs, rust/cubestore/cubestore/src/metastore/mod.rs, rust/cubestore/cubestore/src/sql/mod.rs, rust/cubestore/cubestore/src/store/mod.rs
=> feat(cubestore): Max disk space limit per worker

rust/cubestore/cubestore/src/cachestore/cache_item.rs, rust/cubestore/cubestore/src/cachestore/cache_rocksstore.rs, rust/cubestore/cubestore/src/cachestore/queue_item.rs, rust/cubestore/cubestore/src/cachestore/queue_result.rs, rust/cubestore/cubestore/src/metastore/job.rs, rust/cubestore/cubestore/src/metastore/mod.rs, rust/cubestore/cubestore/src/metastore/multi_index.rs, rust/cubestore/cubestore/src/metastore/replay_handle.rs, rust/cubestore/cubestore/src/metastore/rocks_table.rs, rust/cubestore/cubestore/src/metastore/source.rs, rust/cubestore/cubestore/src/metastore/table.rs
=> feat(cubestore): Cache/Queue - implement migrations via truncating

rust/cubestore/cubestore/src/sql/mod.rs
=> chore(cubestore): Fix flickering test `disk_space_limit`

packages/cubejs-api-gateway/test/index.test.ts, packages/cubejs-api-gateway/test/mocks.ts, packages/cubejs-server-core/src/core/CompilerApi.js, packages/cubejs-server-core/test/unit/index.test.ts
=> feat(cubejs-server-core): add dbType to dataSources

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/test/index.test.ts
=> feat(cubejs-api-gateway): Add scope check to sql runner

packages/cubejs-query-orchestrator/src/orchestrator/QueryQueue.js, packages/cubejs-query-orchestrator/test/unit/QueryQueue.abstract.ts, rust/cubestore/cubestore/src/cachestore/cache_rocksstore.rs, rust/cubestore/cubestore/src/cachestore/lazy.rs, rust/cubestore/cubestore/src/cachestore/queue_item.rs, rust/cubestore/cubestore/src/sql/mod.rs, rust/cubestore/cubestore/src/sql/parser.rs, yarn.lock
=> feat(cubestore): Queue - correct sort over priority (+created)

docs/content/Schema/Advanced/Code-Reusability-Extending-Cubes.mdx
=> docs(schema): add examples showing extended cubes using `FILTER_PARAMS`

rust/cubestore/cubestore/src/streaming/kafka.rs, rust/cubestore/cubestore/src/streaming/mod.rs
=> chore(cubestore): Work with parse_timestamp in kafka filters

packages/cubejs-backend-native/Cargo.lock, packages/cubejs-backend-native/src/channel.rs, packages/cubejs-backend-native/src/stream.rs
=> feat(native): Correct error handling for neon::channel.send

rust/cubesql/cubesql/src/error.rs
=> fix(native): Try to catch panic's reason as String

packages/cubejs-base-driver/src/queue-driver.interface.ts, packages/cubejs-cubestore-driver/src/CubeStoreQueueDriver.ts, packages/cubejs-query-orchestrator/src/orchestrator/QueryQueue.js, packages/cubejs-query-orchestrator/test/unit/QueryQueue.abstract.ts, rust/cubestore/cubestore-sql-tests/src/tests.rs, rust/cubestore/cubestore/src/cachestore/cache_rocksstore.rs, rust/cubestore/cubestore/src/cachestore/queue_item.rs, rust/cubestore/cubestore/src/queryplanner/info_schema/system_queue.rs, rust/cubestore/cubestore/src/sql/mod.rs, rust/cubestore/cubestore/src/sql/parser.rs
refs https://github.com/cube-js/cube.js/issues/5042
=> feat(cubestore): Queue - support custom orphaned ttl

packages/cubejs-jdbc-driver/src/JDBCDriver.ts
=> fix(jdbc-driver): streamQuery connection release

docs/content/Caching/Using-Pre-Aggregations.mdx
=> docs(caching): add index examples

packages/cubejs-server-core/src/core/server.ts
=> fix(server-core): config validation if custom ContextAcceptor is provided

packages/cubejs-query-orchestrator/test/unit/QueryQueue.abstract.ts
=> test(query-orchestrator): Temporary disable orphaned test for Cube Store

rust/cubestore/cubestore/src/cachestore/cache_item.rs, rust/cubestore/cubestore/src/cachestore/queue_item.rs, rust/cubestore/cubestore/src/cachestore/queue_result.rs, rust/cubestore/cubestore/src/metastore/rocks_store.rs, rust/cubestore/cubestore/src/metastore/rocks_table.rs
=> feat(cubestore): Disable MetastoreEvents for queue & cache

rust/cubestore/cubestore-sql-tests/src/tests.rs, rust/cubestore/cubestore/src/app_metrics.rs, rust/cubestore/cubestore/src/sql/cache.rs, rust/cubestore/cubestore/src/sql/mod.rs, rust/cubestore/cubestore/src/sql/parser.rs, rust/cubestore/cubestore/src/util/metrics.rs
=> feat(cubestore): Support SYS DROP QUERY CACHE + metrics

.github/workflows/birdbox.yml, .github/workflows/cloud.yml, .github/workflows/publish.yml, .github/workflows/rust-cubesql.yml, .github/workflows/rust-cubestore-master.yml, .github/workflows/rust-cubestore.yml
=> chore(ci): Workaround for rustup update issue on windows

rust/cubestore/cubestore/src/queryplanner/info_schema/system_snapshots.rs
=> chore(cubestore): Show the creation time in the snapshot list

packages/cubejs-backend-shared/src/proxy.ts
=> fix(shared): getProxySettings use global configuration

rust/cubestore/cubestore/src/queryplanner/info_schema/info_schema_columns.rs, rust/cubestore/cubestore/src/queryplanner/info_schema/mod.rs, rust/cubestore/cubestore/src/queryplanner/mod.rs
=> feat(cubestore): Introduce information_schema.columns

packages/cubejs-backend-native/js/index.ts, packages/cubejs-backend-shared/src/env.ts, packages/cubejs-backend-shared/src/process.ts, packages/cubejs-jdbc-driver/src/QueryStream.ts, packages/cubejs-query-orchestrator/src/orchestrator/QueryCache.ts, packages/cubejs-query-orchestrator/src/orchestrator/QueryQueue.js, packages/cubejs-query-orchestrator/src/orchestrator/QueryStream.ts, packages/cubejs-query-orchestrator/src/orchestrator/RedisPool.ts, packages/cubejs-query-orchestrator/src/orchestrator/utils.ts, packages/cubejs-query-orchestrator/test/unit/QueryQueue.abstract.ts
=> fix: streaming

rust/cubestore/cubestore/src/cachestore/mod.rs, rust/cubestore/cubestore/src/queryplanner/mod.rs, rust/cubestore/cubestore/src/queryplanner/planning.rs, rust/cubestore/cubestore/src/queryplanner/serialized_plan.rs, rust/cubestore/cubestore/src/queryplanner/test_utils.rs
=> fix(cubestore): Support realiasing for information schema tables

packages/cubejs-api-gateway/src/graphql.ts, packages/cubejs-client-core/src/Meta.js
=> feat: GraphQL API variables

rust/cubestore/cubestore/src/cachestore/mod.rs, rust/cubestore/cubestore/src/cachestore/scheduler.rs, rust/cubestore/cubestore/src/config/mod.rs, rust/cubestore/cubestore/src/scheduler/mod.rs, rust/cubestore/cubestore/src/table/mod.rs
=> feat(cubestore): Use separate scheduler for Cache Store

rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/split.rs
**Check List**
This PR improves compatibility with Metabase, rewriting `CAST(column AS DATE)` to `DateTrunc('day', column)`. A related test is included.
=> fix(cubesql): `CAST(column AS DATE)` to DateTrunc day

rust/cubestore/cubestore/src/sql/cachestore.rs, rust/cubestore/cubestore/src/sql/mod.rs
=> chore(cubestore): CacheStoreSqlService - allow to execute select

packages/cubejs-base-driver/src/driver.interface.ts, packages/cubejs-databricks-jdbc-driver/src/DatabricksDriver.ts, packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts
=> fix(databricks-jdbc-driver): export table drops twice in Databricks

packages/cubejs-playground/src/components/Error/FatalError.tsx
**Check List**
CC-1959
Error message inside the modal no more overflows it and the alert container.
=> fix(cubejs-playground): error overflow

.github/workflows/publish.yml, .github/workflows/rust-cubestore.yml
refs https://github.com/cube-js/cube.js/issues/6180
=> chore(cubestore): Fix macos cross build

rust/cubestore/cubestore/src/sql/mod.rs
Hello!
Fix https://github.com/cube-js/cube.js/issues/6172
Thanks
=> feat(cubestore): Allow tinyint type (map as Int)

rust/cubesql/cubesql/src/compile/engine/df/scan.rs
=> feat(cubesql): CubeScan - remove unexpected clone

packages/cubejs-jdbc-driver/src/JDBCDriver.ts
=> fix(jdbc-driver): ResourceRequest timeout

packages/cubejs-query-orchestrator/test/unit/QueryQueue.abstract.ts
=> test(query-orchestrator): Add additional time for CI (random fail)

docs/package.json, docs/yarn.lock
=> docs: update purple banner to 2.0.6

.github/actions/smoke.sh, .github/workflows/push.yml, packages/cubejs-backend-shared/src/process.ts, packages/cubejs-testing-shared/src/db/oracle.ts, packages/cubejs-testing/package.json, packages/cubejs-testing/test/smoke-athena.test.ts, packages/cubejs-testing/test/smoke-bigquery.test.ts, packages/cubejs-testing/test/smoke-crate.test.ts, packages/cubejs-testing/test/smoke-firebolt.test.ts, packages/cubejs-testing/test/smoke-lambda.test.ts, packages/cubejs-testing/test/smoke-materialize.test.ts, packages/cubejs-testing/test/smoke-mssql.test.ts, packages/cubejs-testing/test/smoke-multidb.test.ts, packages/cubejs-testing/test/smoke-oracle.test.ts, packages/cubejs-testing/test/smoke-postgres.test.ts, packages/cubejs-testing/test/smoke-prestodb.test.ts, packages/cubejs-testing/test/smoke-questdb.test.ts, packages/cubejs-testing/test/smoke-redshift.test.ts, packages/cubejs-testing/test/smoke-tests.ts, packages/cubejs-testing/test/smoke-trino.test.ts
=> chore(ci): Enable smoke testing for Oracle

packages/cubejs-backend-shared/src/promises.ts, packages/cubejs-base-driver/src/BaseDriver.ts, packages/cubejs-base-driver/src/driver.interface.ts, packages/cubejs-base-driver/src/utils.ts, packages/cubejs-base-driver/tsconfig.json, packages/cubejs-bigquery-driver/src/BigQueryDriver.ts, packages/cubejs-clickhouse-driver/src/ClickHouseDriver.ts, packages/cubejs-databricks-jdbc-driver/src/DatabricksDriver.ts, packages/cubejs-druid-driver/src/DruidDriver.ts, packages/cubejs-materialize-driver/src/MaterializeDriver.ts, packages/cubejs-templates/src/utils.ts
=> refactor(base-driver): Enable strictNullChecks

packages/cubejs-docker/dev.Dockerfile
=> feat(docker): Use Debian (bullseye) for dev images

rust/cubestore/cubestore/src/metastore/mod.rs, rust/cubestore/cubestore/src/metastore/rocks_store.rs, rust/cubestore/cubestore/src/queryplanner/test_utils.rs, rust/cubestore/cubestore/src/scheduler/mod.rs, rust/cubestore/cubestore/src/sql/mod.rs, rust/cubestore/cubestore/src/store/compaction.rs, rust/cubestore/cubestore/src/store/mod.rs, rust/cubestore/cubestore/src/streaming/buffered_stream.rs, rust/cubestore/cubestore/src/streaming/mod.rs
=> feat(cubestore): Streaming ingestion optimizations

rust/cubestore/cubestore-sql-tests/src/tests.rs, rust/cubestore/cubestore/src/cachestore/cache_rocksstore.rs, rust/cubestore/cubestore/src/cachestore/lazy.rs, rust/cubestore/cubestore/src/metastore/mod.rs, rust/cubestore/cubestore/src/queryplanner/test_utils.rs, rust/cubestore/cubestore/src/sql/cachestore.rs, rust/cubestore/cubestore/src/sql/mod.rs, rust/cubestore/cubestore/src/sql/parser.rs
=> chore(cubestore): Introduce SYS CACHESTORE|METASTORE HEALTHCHECK

rust/cubestore/cubestore/src/metastore/mod.rs, rust/cubestore/cubestore/src/metastore/rocks_store.rs
=> fix(cubestore): Metastore logs are uploaded without the corresponding snapshot

packages/cubejs-databricks-jdbc-driver/src/DatabricksDriver.ts, packages/cubejs-jdbc-driver/src/JDBCDriver.ts
=> fix(jdbc-driver, databricks-jdbc-driver): clearTimeout on validate catch, temp table name

rust/cubestore/cubestore/src/cluster/mod.rs, rust/cubestore/cubestore/src/metastore/mod.rs, rust/cubestore/cubestore/src/queryplanner/serialized_plan.rs, rust/cubestore/cubestore/src/scheduler/mod.rs, rust/cubestore/cubestore/src/sql/mod.rs, rust/cubestore/cubestore/src/store/compaction.rs, rust/cubestore/cubestore/src/store/mod.rs
=> fix(cubestore): Wrong triggering of table deactivation in some cases

packages/cubejs-query-orchestrator/src/orchestrator/QueryOrchestrator.ts
=> fix: Better error message on misconfiguration with Cube Store

packages/cubejs-docker/dev-alpine.Dockerfile, packages/cubejs-docker/dev.Dockerfile, packages/cubejs-docker/latest-alpine-jdk.Dockerfile, packages/cubejs-docker/latest-alpine.Dockerfile, packages/cubejs-docker/latest-debian-jdk.Dockerfile, packages/cubejs-docker/latest.Dockerfile, packages/cubejs-docker/local.Dockerfile
=> chore: Use 120s timeout for docker building (GitHub actions issue)

docs/content/Configuration/Connecting-to-the-Database.mdx
=> docs: Add link to Dremio ODBC Driver

packages/cubejs-athena-driver/src/AthenaDriver.ts, packages/cubejs-base-driver/src/BaseDriver.ts, packages/cubejs-bigquery-driver/src/BigQueryDriver.ts, packages/cubejs-clickhouse-driver/src/ClickHouseDriver.ts, packages/cubejs-databricks-jdbc-driver/src/DatabricksDriver.ts, packages/cubejs-dremio-driver/driver/DremioDriver.js, packages/cubejs-druid-driver/src/DruidDriver.ts, packages/cubejs-elasticsearch-driver/driver/ElasticSearchDriver.js, packages/cubejs-firebolt-driver/src/FireboltDriver.ts, packages/cubejs-hive-driver/driver/HiveDriver.js, packages/cubejs-jdbc-driver/src/JDBCDriver.ts, packages/cubejs-ksql-driver/src/KsqlDriver.ts, packages/cubejs-materialize-driver/src/MaterializeDriver.ts, packages/cubejs-mongobi-driver/src/MongoBIDriver.ts, packages/cubejs-mssql-driver/driver/MSSqlDriver.js, packages/cubejs-mysql-aurora-serverless-driver/driver/AuroraServerlessMySqlDriver.js, packages/cubejs-mysql-driver/src/MySqlDriver.ts, packages/cubejs-oracle-driver/driver/OracleDriver.js, packages/cubejs-postgres-driver/src/PostgresDriver.ts, packages/cubejs-questdb-driver/src/QuestDriver.ts, packages/cubejs-redshift-driver/src/RedshiftDriver.ts, packages/cubejs-server-core/src/core/optionsValidate.ts, packages/cubejs-server-core/src/core/server.ts, packages/cubejs-server-core/src/core/types.ts, packages/cubejs-server-core/test/unit/OptsHandler.test.ts, packages/cubejs-snowflake-driver/src/SnowflakeDriver.ts, packages/cubejs-sqlite-driver/driver/SqliteDriver.js
=> feat: connection validation and logging

packages/cubejs-schema-compiler/src/adapter/PostgresQuery.js, packages/cubejs-schema-compiler/src/adapter/PreAggregations.js, packages/cubejs-testing/birdbox-fixtures/lambda/schema/Orders.js, packages/cubejs-testing/test/smoke-lambda.test.ts, rust/cubestore/cubestore/src/remotefs/mod.rs, yarn.lock
=> feat: Support rollupLambda across different cubes and data sources

packages/cubejs-base-driver/src/queue-driver.interface.ts, packages/cubejs-cubestore-driver/package.json, packages/cubejs-cubestore-driver/src/CubeStoreQueueDriver.ts, yarn.lock
=> fix(cubestore-driver): Correct log while processing for query queue

packages/cubejs-query-orchestrator/src/orchestrator/QueryQueue.js, rust/cubestore/cubestore-sql-tests/src/tests.rs, rust/cubestore/cubestore/src/cachestore/cache_rocksstore.rs, rust/cubestore/cubestore/src/cachestore/lazy.rs, rust/cubestore/cubestore/src/cachestore/mod.rs, rust/cubestore/cubestore/src/cachestore/queue_item.rs, rust/cubestore/cubestore/src/queryplanner/test_utils.rs, rust/cubestore/cubestore/src/sql/cachestore.rs, rust/cubestore/cubestore/src/sql/parser.rs
=> feat(cubestore): Support extended flag for QUEUE retrieve

rust/cubestore/cubestore/src/app_metrics.rs, rust/cubestore/cubestore/src/config/mod.rs, rust/cubestore/cubestore/src/metastore/mod.rs, rust/cubestore/cubestore/src/metastore/rocks_store.rs, rust/cubestore/cubestore/src/metastore/rocks_table.rs, rust/cubestore/cubestore/src/queryplanner/test_utils.rs, rust/cubestore/cubestore/src/scheduler/mod.rs, rust/cubestore/cubestore/src/store/compaction.rs, rust/cubestore/cubestore/src/store/mod.rs, rust/cubestore/cubestore/src/streaming/buffered_stream.rs, rust/cubestore/cubestore/src/streaming/kafka.rs, rust/cubestore/cubestore/src/streaming/mod.rs, rust/cubestore/cubestore/src/util/metrics.rs
=> feat(cubestore): Streaming optimizations 

packages/cubejs-api-gateway/package.json
=> chore(deps): Remove unused package (@hapi/joi)

packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts, packages/cubejs-query-orchestrator/src/orchestrator/QueryOrchestrator.ts
=> chore: Show deprecation notice for Redis

rust/cubestore/Cargo.lock, rust/cubestore/cubestore/Cargo.toml, rust/cubestore/cubestore/src/metastore/rocks_store.rs
Hello!
```sh
in_process::cache_set_get
time:   [10.859 µs 11.142 µs 11.421 µs]
change: [-0.6686% +1.4323% +3.6888%] (p = 0.20 > 0.05)
No change in performance detected.
Found 5 outliers among 100 measurements (5.00%)
```
```sh
in_process::cache_set_get
time:   [8.2918 µs 8.4782 µs 8.6928 µs]
change: [-25.218% -23.466% -21.578%] (p = 0.00 < 0.05)
Performance has improved.
Found 4 outliers among 100 measurements (4.00%)
```
Thanks
=> refactor(cubestore): Remove uneeded spawn_blocking (improve perf)

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/src/types/auth.ts, packages/cubejs-server-core/test/unit/OptsHandler.test.ts
=> fix(server-core, api-gateway): permissions function signature

packages/cubejs-api-gateway/src/gateway.ts
=> fix(api-gateway): contextToPermissions default permissions parameter

packages/cubejs-api-gateway/src/gateway.ts
=> fix(api-gateway): permissions error message

packages/cubejs-api-gateway/test/permissions.test.ts
=> fix(api-gateway): permissions unit test fix

packages/cubejs-api-gateway/test/permissions.test.ts
=> fix(api-gateway): permissions cache removed

rust/cubestore/Cargo.lock, rust/cubestore/cubestore-sql-tests/Cargo.toml, rust/cubestore/cubestore/Cargo.toml, rust/cubestore/cubestore/src/cachestore/cache_rocksstore.rs, rust/cubestore/cubestore/src/metastore/mod.rs, rust/cubestore/cubestore/src/metastore/rocks_store.rs, rust/cubestore/cubestore/src/metastore/rocks_table.rs
Hello!
refs https://github.com/cube-js/cube.js/issues/5042
Thanks
=> feat(cubestore): Upgrade RocksDB to 7.9.2 (0.20)

rust/cubestore/.dockerignore, rust/cubestore/Dockerfile
Hello!
Bump CLang to 15 to protect https://github.com/facebook/rocksdb/issues/9891
Thanks
=> feat(cubestore/docker): Upgrade OS, Clang

packages/cubejs-hive-driver/driver/HiveDriver.js, packages/cubejs-hive-driver/package.json, packages/cubejs-hive-driver/src/HiveDriver.js, packages/cubejs-hive-driver/src/TSaslTransport.js
=> fix(hive-driver): Follow DriverInterface for query method, fix #6281

docs/content/API-Reference/Query-Format.md, packages/cubejs-schema-compiler/src/compiler/CubeValidator.js, packages/cubejs-testing/test/__snapshots__/birdbox-postgresql-pre-aggregations.test.ts.snap, packages/cubejs-testing/test/pre-aggregations-test-case.ts
**Check List**
Replacement for the [PR 3415](https://github.com/cube-js/cube.js/pull/3415). Close the [issue 3411](https://github.com/cube-js/cube.js/issues/3411).
=> feat(schema-compiler): quarter granularity

packages/cubejs-ksql-driver/src/KsqlDriver.ts, packages/cubejs-ksql-driver/src/KsqlQuery.ts, packages/cubejs-schema-compiler/src/adapter/BaseQuery.js, packages/cubejs-schema-compiler/src/adapter/PreAggregations.js, packages/cubejs-schema-compiler/test/integration/postgres/pre-aggregations.test.ts
=> fix: Cross data source `rollupLambda` uses incorrect refreshKey

packages/cubejs-query-orchestrator/src/orchestrator/QueryCache.ts, packages/cubejs-query-orchestrator/src/orchestrator/QueryOrchestrator.ts
=> fix(query-orchestrator): queues reconciliation logic

rust/cubestore/cubestore-sql-tests/src/tests.rs, rust/cubestore/cubestore/src/queryplanner/serialized_plan.rs
=> fix(cubestore): Panic: index out of bounds: the len is 0 but the index is 0

rust/cubesql/cubesql/src/compile/engine/udf.rs, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/parser.rs, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__current_setting.snap, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__grafana_insubquery_where_tables.snap, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__microstrategy_subquery_current_schema.snap, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__quote_ident.snap
**Check List**
This PR adds support for Microstrategy and Grafana introspection queries. Related tests are included.
=> chore(cubesql): Support Microstrategy and Grafana introspection

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/src/types/gateway.ts, packages/cubejs-query-orchestrator/src/orchestrator/QueryCache.ts, packages/cubejs-server-core/src/core/OptsHandler.ts, packages/cubejs-server-core/src/core/OrchestratorApi.ts, packages/cubejs-server-core/src/core/server.ts, packages/cubejs-server-core/test/unit/RefreshScheduler.test.ts, packages/cubejs-server-core/test/unit/index.test.ts
=> fix: Refresh Scheduler - empty securityContext in driverFactory

rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/members.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/split.rs
=> fix(cubesql): Quicksight AVG measures support

rust/cubestore/cubestore/src/import/mod.rs
=> fix(cubestore): Retying for download from external locations

rust/cubestore/cubestore/src/app_metrics.rs, rust/cubestore/cubestore/src/config/mod.rs, rust/cubestore/cubestore/src/metastore/rocks_store.rs, rust/cubestore/cubestore/src/remotefs/gcs.rs, rust/cubestore/cubestore/src/remotefs/mod.rs, rust/cubestore/cubestore/src/remotefs/s3.rs
=> chore(cubestore): Metrics for remote filesystem operations

rust/cubestore/cubestore/src/metastore/mod.rs, rust/cubestore/cubestore/src/queryplanner/test_utils.rs, rust/cubestore/cubestore/src/scheduler/mod.rs
=> fix(cubestore): If job has been scheduled to non-existent node it'd hang around forever

.github/workflows/cloud.yml, packages/cubejs-athena-driver/src/AthenaDriver.ts, packages/cubejs-cubestore-driver/src/CubeStoreDriver.ts
=> feat(cubestore-driver): Support timestamp(3) as a column type

.github/workflows/rust-cubesql.yml, packages/cubejs-backend-native/package.json, packages/cubejs-backend-native/test/meta.js, packages/cubejs-backend-native/test/server.js, packages/cubejs-backend-native/test/sql.test.js, packages/cubejs-testing-shared/src/index.ts, packages/cubejs-testing-shared/src/response-fake.ts
=> chore(native): Implement FakeStream generator for stream testing

docs/package.json, docs/yarn.lock
=> docs: update purple banner to 2.0.7

docs/package.json, docs/yarn.lock
=> docs: banner update

rust/cubestore/cubestore/src/import/mod.rs
=> fix(cubestore): A single-character boolean value in csv is parsed incorrectly

rust/cubestore/Cargo.lock, rust/cubestore/cubestore-sql-tests/Cargo.toml, rust/cubestore/cubestore/Cargo.toml, rust/cubestore/cubestore/src/cachestore/cache_rocksstore.rs, rust/cubestore/cubestore/src/config/mod.rs, rust/cubestore/cubestore/src/metastore/mod.rs, rust/cubestore/cubestore/src/metastore/rocks_store.rs
=> chore(cubestore): Allow to configure checksum_type/cache_capacity for RocksDB

rust/cubestore/cubestore/src/metastore/rocks_store.rs
=> feat(cubestore): Use new XXH3 checksum alg for RocksDB

packages/cubejs-cubestore-driver/src/CubeStoreDriver.ts
=> Sql runner fix cubestore

docs/content/Schema/Advanced/Code-Reusability-Export-and-Import.mdx
=> docs(recipes): Add environment variable example.

packages/cubejs-schema-compiler/src/compiler/CubeToMetaTransformer.js, packages/cubejs-schema-compiler/src/compiler/CubeValidator.js, packages/cubejs-schema-compiler/test/unit/PrepareCompiler.js, packages/cubejs-schema-compiler/test/unit/cube-validator.test.ts, packages/cubejs-schema-compiler/test/unit/schema.test.ts, packages/cubejs-schema-compiler/test/unit/utils.ts
=> feat(schema-compiler): Introduce public field (alias for shown)

packages/cubejs-schema-compiler/src/compiler/CubeEvaluator.js, packages/cubejs-schema-compiler/src/compiler/CubeSymbols.js, packages/cubejs-schema-compiler/src/compiler/CubeToMetaTransformer.js, packages/cubejs-schema-compiler/src/compiler/CubeValidator.js, packages/cubejs-schema-compiler/src/compiler/transpilers/CubePropContextTranspiler.ts, packages/cubejs-schema-compiler/test/integration/postgres/yaml-compiler.test.ts, packages/cubejs-testing-shared/src/db/mssql.ts, packages/cubejs-testing/birdbox-fixtures/driver-test-data/ECommerce.js, packages/cubejs-testing/test/driverTests/testSets.ts, packages/cubejs-testing/test/driverTests/tests.ts
=> feat: Cube based includes and meta exposure

rust/cubestore/Cargo.lock, rust/cubestore/cubestore/Cargo.toml, rust/cubestore/cubestore/src/config/mod.rs
Hello!
refs https://github.com/cube-js/cube/issues/6346
Thanks
=> feat(cubestore): Increase default frame size to 32Mb

rust/cubestore/cubestore-sql-tests/src/tests.rs, rust/cubestore/cubestore/src/bin/cubestored.rs, rust/cubestore/cubestore/src/config/mod.rs, rust/cubestore/cubestore/src/remotefs/gcs.rs, rust/cubestore/cubestore/src/remotefs/mod.rs, rust/cubestore/cubestore/src/remotefs/s3.rs, rust/cubestore/cubestore/src/store/mod.rs, rust/cubestore/cubestore/src/streaming/mod.rs, rust/cubestore/cubestore/src/util/metrics.rs
=> chore(cubestore): Support global tags for metrics

packages/cubejs-schema-compiler/src/compiler/CubeEvaluator.js, packages/cubejs-schema-compiler/src/compiler/CubeValidator.js, packages/cubejs-schema-compiler/test/unit/schema.test.ts, packages/cubejs-schema-compiler/test/unit/utils.ts
=> feat(schema-compiler): Support new aliases for join. relationship

docs/content/Configuration/Databases/QuestDB.mdx, packages/cubejs-questdb-driver/src/QuestDriver.ts
**Check List**
Closes #6394
The patch follows Postgres driver which has a similar config.
=> Add SSL support to QuestDB driver

rust/cubestore/cubestore/src/cachestore/cache_rocksstore.rs, rust/cubestore/cubestore/src/config/mod.rs, rust/cubestore/cubestore/src/metastore/mod.rs, rust/cubestore/cubestore/src/metastore/rocks_fs.rs, rust/cubestore/cubestore/src/metastore/rocks_store.rs, rust/cubestore/cubestore/src/sql/mod.rs, rust/cubestore/cubestore/src/store/compaction.rs, rust/cubestore/cubestore/src/store/mod.rs
=> feat(cubestore): Separate configuration for count of metastore and cachestore snapshots

packages/cubejs-databricks-jdbc-driver/src/DatabricksQuery.ts
=> fix(databricks-jdbc): startsWith, endsWith, contains filters

rust/cubestore/cubestore/src/queryplanner/providers/query_cache.rs, rust/cubestore/cubestore/src/sql/cache.rs, rust/cubestore/cubestore/src/table/mod.rs
=> fix(cubestore): Query Cache - correct size calculation

packages/cubejs-prestodb-driver/src/PrestoDriver.ts, packages/cubejs-prestodb-driver/test/presto-driver.test.ts
=> feat(prestodb-driver): Add schema filter to informationSchemaQuery

packages/cubejs-query-orchestrator/src/orchestrator/QueryCache.ts
=> chore(query-orchestrator): set csvQuery method to protected

packages/cubejs-schema-compiler/src/compiler/YamlCompiler.ts, packages/cubejs-schema-compiler/test/unit/yaml-schema.test.ts
=> fix(schema-compiler): Yaml - crash on fully commented file

packages/cubejs-server-core/src/core/RefreshScheduler.ts
=> fix(server-core): turn off the jobs API renewQuery flag

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/src/types/gateway.ts, packages/cubejs-server-core/src/core/server.ts
=> feat(api-gateway, server-core): Orchestration API telemetry

packages/cubejs-schema-compiler/src/compiler/utils.ts, packages/cubejs-schema-compiler/test/unit/utils.test.ts
=> fix(schema-compiler): Incorrect camelize for meta

.github/workflows/drivers-tests.yml, packages/cubejs-mssql-driver/driver/MSSqlDriver.js
=> fix(mssql-driver): release stream connection

packages/cubejs-linter/package.json, yarn.lock
=> chore(linter): Upgrade typescript-eslint (support TypeScript 4.9)

rust/cubestore/cubestore/src/metastore/mod.rs, rust/cubestore/cubestore/src/metastore/rocks_store.rs, rust/cubestore/cubestore/src/metastore/trace_object.rs, rust/cubestore/cubestore/src/queryplanner/test_utils.rs, rust/cubestore/cubestore/src/sql/mod.rs, rust/cubestore/cubestore/src/store/compaction.rs, rust/cubestore/cubestore/src/store/mod.rs, rust/cubestore/cubestore/src/streaming/kafka.rs, rust/cubestore/cubestore/src/streaming/mod.rs, rust/cubestore/cubestore/src/streaming/traffic_sender.rs
=> feat(cubestore): Traffic tracing for streaming

rust/cubestore/cubestore/src/config/mod.rs, rust/cubestore/cubestore/src/store/compaction.rs
=> feat(cubestore): Split partitions by filesize

rust/cubestore/Cargo.lock, rust/cubestore/cubestore/Cargo.toml
=> chore(cubestore): Update sqlparser (initial support for placeholders)

docs/content/Configuration/Connecting-to-Downstream-Tools.mdx, docs/content/Configuration/Downstream/Delphi.mdx, docs/src/components/YouTubeVideo/YouTubeVideo.tsx, docs/src/templates/DocTemplate.tsx
See subject.
https://deploy-preview-6461--cubejs-docs-staging.netlify.app/config/downstream#custom-data-experiences
https://deploy-preview-6461--cubejs-docs-staging.netlify.app/config/downstream/delphi
=> docs: Delphi integration + YouTubeVideo component

packages/cubejs-athena-driver/src/AthenaDriver.ts, packages/cubejs-base-driver/src/driver.interface.ts, packages/cubejs-databricks-jdbc-driver/src/DatabricksDriver.ts, packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts, packages/cubejs-testing-drivers/fixtures/athena.json, packages/cubejs-testing-drivers/package.json, packages/cubejs-testing-drivers/src/helpers/patchDriver.ts, packages/cubejs-testing-drivers/src/types/PatchedDriver.ts
=> feat(athena-driver): read-only unload

packages/cubejs-api-gateway/src/gateway.ts
=> fix(api-gateway): passing defaultApiScope env to the contextToApiScopesFn

docs/content/Configuration/VPC/Connecting-with-a-VPC-Azure.mdx
**Check List**
Update Azure VPC peering docs for clarity in wording.
=> docs(config): improve "Connecting to a VPC in Azure" page

packages/cubejs-query-orchestrator/src/orchestrator/QueryCache.ts, packages/cubejs-query-orchestrator/src/orchestrator/QueryOrchestrator.ts, packages/cubejs-query-orchestrator/test/unit/QueryOrchestrator.test.js
=> chore(query-orchestrator): Get rid fetchSchema

packages/cubejs-playground/src/ChartContainer.tsx, packages/cubejs-playground/src/QueryBuilder/MissingMemberTooltip.tsx, packages/cubejs-playground/src/components/ChartRenderer/ChartRenderer.tsx, packages/cubejs-playground/src/components/GraphQL/CubeGraphQLConverter.ts, packages/cubejs-playground/src/components/PlaygroundQueryBuilder/QueryBuilderContainer.tsx, packages/cubejs-playground/src/components/PlaygroundQueryBuilder/components/PlaygroundQueryBuilder.tsx, packages/cubejs-playground/src/rollup-designer/RollupDesigner.tsx
=> fix(cubejs-playground): SL-58 CC-1686 text and icon fixes

rust/cubestore/cubehll/src/instance.rs, rust/cubestore/cubestore-sql-tests/src/tests.rs
=> fix(cubestore): Error in Sparse HLL entry parsing

rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/parser.rs, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__psqlodbc_null.snap, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__show_max_identifier_length.snap, rust/cubesql/cubesql/src/sql/database_variables/postgres/session_vars.rs
**Check List**
This PR adds support for `psqlodbc` driver, tested on a Unicode(x64) version of the driver. Related tests are included.
=> feat(cubesql): psqlodbc driver support

packages/cubejs-schema-compiler/src/compiler/CubeEvaluator.js, packages/cubejs-schema-compiler/src/compiler/CubeValidator.js, packages/cubejs-schema-compiler/test/integration/postgres/yaml-compiler.test.ts
=> chore: Update to views spec

packages/cubejs-schema-compiler/src/compiler/DataSchemaCompiler.js, packages/cubejs-schema-compiler/test/integration/postgres/yaml-compiler.test.ts, packages/cubejs-schema-compiler/test/unit/PrepareCompiler.js
=> feat: Support snake case security_context in COMPILE_CONTEXT

packages/cubejs-schema-compiler/src/compiler/CubeEvaluator.js, packages/cubejs-schema-compiler/src/compiler/CubeValidator.js, packages/cubejs-schema-compiler/src/compiler/YamlCompiler.ts, packages/cubejs-schema-compiler/src/compiler/transpilers/CubePropContextTranspiler.ts, packages/cubejs-schema-compiler/src/compiler/utils.ts, packages/cubejs-schema-compiler/test/integration/postgres/yaml-compiler.test.ts, packages/cubejs-testing/birdbox-fixtures/driver-test-data/ECommerce.js
=> chore: Use name instead of cube in cubes parameter

packages/cubejs-base-driver/src/queue-driver.interface.ts, packages/cubejs-cubestore-driver/src/CubeStoreQueueDriver.ts, packages/cubejs-query-orchestrator/src/orchestrator/AsyncRedisClient.ts, packages/cubejs-query-orchestrator/src/orchestrator/BaseQueueDriver.ts, packages/cubejs-query-orchestrator/src/orchestrator/RedisPool.ts, packages/cubejs-query-orchestrator/src/orchestrator/RedisQueueDriver.ts
=> refactor(query-orchestrator): RedisQueueDriver - migrate to TypeScript

packages/cubejs-base-driver/src/BaseDriver.ts, packages/cubejs-base-driver/src/cache-driver.interface.ts, packages/cubejs-base-driver/src/queue-driver.interface.ts, packages/cubejs-base-driver/src/utils.ts, packages/cubejs-base-driver/test/unit/BaseDriver.test.ts, packages/cubejs-base-driver/tsconfig.json
=> refactor(base-driver): Enable noImplicitAny

packages/cubejs-base-driver/src/queue-driver.interface.ts, packages/cubejs-cubestore-driver/src/CubeStoreQueueDriver.ts, rust/cubestore/cubestore-sql-tests/src/tests.rs, rust/cubestore/cubestore/src/cachestore/cache_rocksstore.rs, rust/cubestore/cubestore/src/cachestore/lazy.rs, rust/cubestore/cubestore/src/cachestore/listener.rs, rust/cubestore/cubestore/src/cachestore/queue_item.rs, rust/cubestore/cubestore/src/queryplanner/test_utils.rs, rust/cubestore/cubestore/src/sql/cachestore.rs
=> feat(cubestore): Queue - expose processingId in queue_retrieve

docs/content/Style-Guide/Overview.mdx, docs/src/components/Layout/MainMenu.tsx
https://deploy-preview-6533--cubejs-docs-staging.netlify.app/style-guide
=> docs: Style guide

rust/cubestore/cubestore/src/cachestore/cache_rocksstore.rs
=> fix(cubestore): Queue - protect race condition on get_result_blocking

rust/cubestore/cubestore-sql-tests/src/tests.rs, rust/cubestore/cubestore/src/cachestore/cache_rocksstore.rs, rust/cubestore/cubestore/src/sql/cachestore.rs
=> feat(cubestore): Queue - expose processingId in queue_add

packages/cubejs-cubestore-driver/src/CubeStoreQueueDriver.ts, rust/cubestore/cubestore-sql-tests/src/tests.rs, rust/cubestore/cubestore/src/cachestore/cache_rocksstore.rs, rust/cubestore/cubestore/src/cachestore/lazy.rs, rust/cubestore/cubestore/src/queryplanner/test_utils.rs, rust/cubestore/cubestore/src/sql/cachestore.rs
=> feat(cubestore-driver): Queue - track orphaned set result

rust/cubestore/cubestore/src/cachestore/cache_rocksstore.rs, rust/cubestore/cubestore/src/cachestore/queue_result.rs, rust/cubestore/cubestore/src/metastore/rocks_table.rs
=> chore(cubestore): QueueResult - use same pk as QueueItem

packages/cubejs-snowflake-driver/src/SnowflakeDriver.ts, packages/cubejs-testing/birdbox-fixtures/snowflake/schema/Orders.js, packages/cubejs-testing/test/__snapshots__/smoke-snowflake.test.ts.snap, packages/cubejs-testing/test/smoke-snowflake.test.ts
=> fix(snowflake-driver): Float exported as decimal for pre-aggregations

docs/content/Schema/Fundamentals/Working-with-Joins.mdx, docs/content/Schema/Reference/view.mdx
=> docs: update direction of joins section

packages/cubejs-schema-compiler/src/compiler/CubeEvaluator.js, packages/cubejs-schema-compiler/src/compiler/CubeSymbols.js, packages/cubejs-schema-compiler/src/compiler/transpilers/CubePropContextTranspiler.ts, packages/cubejs-schema-compiler/test/integration/postgres/views.test.ts, packages/cubejs-schema-compiler/test/integration/postgres/yaml-compiler.test.ts
=> fix: join_path for JS schemas and * includes with prefix

rust/cubestore/cubestore/src/remotefs/gcs.rs, rust/cubestore/cubestore/src/remotefs/s3.rs
=> chore(cubestore): Improve remoteFs metrics

packages/cubejs-schema-compiler/src/compiler/YamlCompiler.ts, packages/cubejs-schema-compiler/test/integration/postgres/yaml-compiler.test.ts
=> fix: fix includes all for views

docs/content/Schema/Advanced/schema-execution-environment.mdx, docs/content/Schema/Fundamentals/Additional-Concepts.mdx, docs/content/Schema/Fundamentals/Concepts.mdx, docs/content/Schema/Fundamentals/Syntax.mdx, docs/content/Schema/Fundamentals/Working-with-Joins.mdx, docs/content/Schema/Reference/cube.mdx
=> docs: update data modeling section

packages/cubejs-server-core/src/core/agentCollect.ts
=> chore: deflate APM data when sent over plain http(s)

packages/cubejs-query-orchestrator/DEVELOPMENT.md, rust/cubestore/cubestore-sql-tests/src/tests.rs, rust/cubestore/cubestore/src/cachestore/cache_rocksstore.rs, rust/cubestore/cubestore/src/cachestore/lazy.rs, rust/cubestore/cubestore/src/cachestore/listener.rs, rust/cubestore/cubestore/src/cachestore/mod.rs, rust/cubestore/cubestore/src/cachestore/queue_item.rs, rust/cubestore/cubestore/src/cachestore/queue_result.rs, rust/cubestore/cubestore/src/metastore/rocks_store.rs, rust/cubestore/cubestore/src/queryplanner/test_utils.rs, rust/cubestore/cubestore/src/sql/cachestore.rs, rust/cubestore/cubestore/src/sql/parser.rs
=> feat(cubestore): Queue - support cancel, ack, result_blocking by processingId

rust/cubesql/Cargo.lock, rust/cubesql/cubesql/Cargo.toml, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__df_compare_int_with_null.snap
**Check List**
This PR improves comparison between NULL and int/bool types. This resolves an issue when comparing a number to a null would error out. Related tests are included.
=> fix(cubesql): Improve NULL comparison with int/bool

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/test/index.test.ts, packages/cubejs-schema-compiler/src/adapter/PreAggregations.js, packages/cubejs-testing-drivers/fixtures/snowflake.json, packages/cubejs-testing-drivers/src/helpers/getComposePath.ts, packages/cubejs-testing-drivers/src/helpers/runEnvironment.ts, packages/cubejs-testing-drivers/test/__snapshots__/snowflake-full.test.ts.snap
=> Fix limit check

rust/cubestore/cubestore-sql-tests/src/tests.rs, rust/cubestore/cubestore/src/import/mod.rs, rust/cubestore/cubestore/src/metastore/mod.rs, rust/cubestore/cubestore/src/sql/mod.rs
=> feat(cubestore): Support custom CSV delimiters

docs/content/Guides/Data-Store-Cost-Saving-Guide.mdx, docs/content/Guides/Style-Guide.mdx, docs/src/components/Layout/MainMenu.tsx, docs/src/rename-category.js
https://deploy-preview-6599--cubejs-docs-staging.netlify.app/guides/data-store-cost-saving-guide
=> docs: Add cost-saving guide

rust/cubestore/cubestore-sql-tests/src/tests.rs, rust/cubestore/cubestore/src/cachestore/cache_rocksstore.rs, rust/cubestore/cubestore/src/cachestore/lazy.rs, rust/cubestore/cubestore/src/queryplanner/test_utils.rs, rust/cubestore/cubestore/src/sql/cachestore.rs, rust/cubestore/cubestore/src/sql/parser.rs
=> feat(cubestore): Queue - allow to get by processingId

packages/cubejs-server-core/src/core/CompilerApi.js
=> chore(cubejs-server-core): Extended logs around schema compilation

packages/cubejs-bigquery-driver/src/BigQueryDriver.ts
=> feat(bigquery-driver): Implement timeout for testConnection

rust/cubestore/cubestore/src/http/mod.rs, rust/cubestore/cubestore/src/lib.rs
=> chore(cubestore): The possibility of closing the WS connection

rust/cubestore/cubestore/src/cluster/message.rs, rust/cubestore/cubestore/src/cluster/mod.rs, rust/cubestore/cubestore/src/config/mod.rs, rust/cubestore/cubestore/src/metastore/job.rs, rust/cubestore/cubestore/src/metastore/mod.rs, rust/cubestore/cubestore/src/queryplanner/test_utils.rs, rust/cubestore/cubestore/src/scheduler/mod.rs, rust/cubestore/cubestore/src/sql/mod.rs, rust/cubestore/cubestore/src/store/compaction.rs, rust/cubestore/cubestore/src/store/mod.rs, rust/cubestore/cubestore/src/streaming/mod.rs
=> feat(cubestore): Optimization of inmemory chunk operations for streaming

.github/workflows/publish.yml, .github/workflows/rust-cubesql.yml, packages/cubejs-backend-native/package.json
=> chore(ci): Publish - compile fallback/python builds for native

packages/cubejs-backend-native/bin/post-install, packages/cubejs-backend-native/js/post-install.ts, packages/cubejs-backend-native/package.json, packages/cubejs-backend-shared/src/platform.ts
=> chore(native): New script for post installation

packages/cubejs-backend-native/js/post-install.ts, packages/cubejs-docker/dev.Dockerfile, packages/cubejs-docker/latest-debian-jdk.Dockerfile, packages/cubejs-docker/latest.Dockerfile, packages/cubejs-docker/local.Dockerfile, packages/cubejs-docker/testing-drivers.Dockerfile
=> chore(docker): Install libpython3-dev

packages/cubejs-backend-native/js/post-install.ts, packages/cubejs-backend-native/package.json, packages/cubejs-backend-shared/src/platform.ts
=> chore(native): Disable python for linux-arm64 (not supported)

packages/cubejs-backend-native/README.md, packages/cubejs-backend-shared/src/platform.ts, packages/cubejs-server/src/server/container.ts
=> chore(native): Document supported platforms for python builds

.github/workflows/publish.yml
=> chore(ci): Publish - speedup docker build

rust/cubesql/cubesql/src/compile/engine/udf.rs, rust/cubesql/cubesql/src/compile/mod.rs
**Check List**
This PR adds stubs with correct signatures for most Postgres functions, including undocumented ones, allowing initial plan to be built when any of those functions are provided as part of a query.
=> chore(cubesql): Add stubs for most Postgres functions

.github/workflows/publish.yml, packages/cubejs-backend-native/package.json, yarn.lock
=> chore(native): Publish by action instead of node-pre-gyp

.github/workflows/rust-cubesql.yml, packages/cubejs-backend-native/Cargo.lock, packages/cubejs-backend-native/Cargo.toml, packages/cubejs-backend-native/build.rs, packages/cubejs-backend-native/src/lib.rs, packages/cubejs-backend-native/src/python/cube_config.rs, packages/cubejs-backend-native/src/python/entry.rs, packages/cubejs-backend-native/src/python/linux_dylib.rs, packages/cubejs-backend-native/src/python/mod.rs, packages/cubejs-backend-native/src/python/runtime.rs, packages/cubejs-backend-native/test/config.py, packages/cubejs-backend-native/test/python_async_bench.ts
Hello!
After: https://github.com/cube-js/cube/pull/6465
Thanks
=> feat(native): Python - support async functions

packages/cubejs-backend-shared/src/env.ts, packages/cubejs-server-core/src/core/OptsHandler.ts, packages/cubejs-server-core/test/unit/OptsHandler.test.ts
=> fix: Multi data source CUBEJS_CONCURRENCY env

docs/content/Schema/Reference/joins.mdx
=> Update joins.mdx - updating "shown" to "public"

rust/cubestore/cubestore/src/metastore/job.rs, rust/cubestore/cubestore/src/metastore/mod.rs
=> feat(cubestore): Priorities for job types

.github/workflows/publish.yml
=> feat(native): Publish python builds for darwin platform

packages/cubejs-schema-compiler/src/compiler/YamlCompiler.ts, packages/cubejs-schema-compiler/test/integration/postgres/yaml-compiler.test.ts
=> fix: Support indexes in pre-aggs in yaml

docs/content/Deployment/Cloud/Deployment-Types.mdx, docs/content/Deployment/Cloud/Limits.mdx
New [Limits](https://deploy-preview-6690--cubejs-docs-staging.netlify.app/cloud/limits) page.
=> docs: Document limits, incl. for Query History

rust/cubestore/cubestore/src/cluster/mod.rs, rust/cubestore/cubestore/src/cluster/worker_pool.rs, rust/cubestore/cubestore/src/config/mod.rs, rust/cubestore/cubestore/src/queryplanner/check_memory.rs, rust/cubestore/cubestore/src/queryplanner/mod.rs, rust/cubestore/cubestore/src/queryplanner/optimizations/check_memory.rs, rust/cubestore/cubestore/src/queryplanner/optimizations/mod.rs, rust/cubestore/cubestore/src/queryplanner/pretty_printers.rs, rust/cubestore/cubestore/src/queryplanner/query_executor.rs, rust/cubestore/cubestore/src/sql/mod.rs, rust/cubestore/cubestore/src/util/memory.rs, rust/cubestore/cubestore/src/util/mod.rs
=> chore(cubestore): Memory usage tracing

docs/content/Configuration/Downstream/Superset.mdx, docs/content/Getting-Started/Overview.mdx, docs/content/SQL-API/Overview.mdx, docs/content/Schema/Getting-Started.mdx
=> docs: add banners for webinar

rust/cubestore/cubestore/src/config/mod.rs, rust/cubestore/cubestore/src/store/compaction.rs
=> fix(cubestore): Out of memory on partition compaction

packages/cubejs-backend-native/Cargo.lock, packages/cubejs-backend-native/Cargo.toml, packages/cubejs-backend-native/src/python/cube_config.rs
=> chore(native): Compile python deps only for python builds

packages/cubejs-backend-native/src/python/cross.rs, packages/cubejs-backend-native/test/python.test.ts
=> feat(native): Python - support int64

packages/cubejs-backend-shared/src/convert.ts, packages/cubejs-backend-shared/src/promises.ts, packages/cubejs-backend-shared/test/convert.test.ts, packages/cubejs-server-core/src/core/server.ts
=> fix: Correct duration for refresh sheduler interval warning

docs/content/Deployment/Production-Checklist.mdx
**Check List**
Add warning about dev mode.
=> docs: add warning about dev mode

packages/cubejs-backend-shared/src/platform.ts
=> fix(native): Correct support detection (disable for darwin-aaarch64)

packages/cubejs-backend-native/src/python/template/entry.rs, packages/cubejs-schema-compiler/src/compiler/DataSchemaCompiler.js
=> fix(schema): Load jinja engine only when jinja templates exist

.github/workflows/publish.yml, .github/workflows/rust-cubesql.yml, packages/cubejs-backend-native/README.md
Hello!
Fix: https://github.com/cube-js/cube/issues/6510
Thanks
=> chore(native): Support aarch64-apple-darwin (M1/M2)

packages/cubejs-backend-native/Cargo.lock, packages/cubejs-backend-native/Cargo.toml, rust/cubesql/cubesql/Cargo.toml
=> chore(native): Enable minijinja only for python builds

packages/cubejs-backend-shared/src/platform.ts
Hello!
Fix https://github.com/cube-js/cube/issues/6510
Thanks
=> feat(native): Support darwin-aaarch64

rust/cubestore/cubestore/src/scheduler/mod.rs
=> fix(cubestore): FreeInMemoryChunks fires if there is no inmemory chunks

rust/cubestore/cubestore/src/cluster/worker_pool.rs
=> chore(cubestore): Enviroment for sel worker process titile

rust/cubestore/cubestore/src/lib.rs
=> chore(cubestore): Change error message for deadlines

packages/cubejs-backend-native/js/index.ts, packages/cubejs-backend-native/src/python/template/entry.rs, packages/cubejs-backend-native/test/jinja.test.ts, packages/cubejs-schema-compiler/src/compiler/DataSchemaCompiler.js, packages/cubejs-schema-compiler/src/compiler/YamlCompiler.ts
=> feat(schema): Support multitenancy for jinja templates

rust/cubestore/cubestore/src/app_metrics.rs, rust/cubestore/cubestore/src/config/mod.rs, rust/cubestore/cubestore/src/metastore/mod.rs, rust/cubestore/cubestore/src/queryplanner/test_utils.rs, rust/cubestore/cubestore/src/remotefs/cleanup.rs, rust/cubestore/cubestore/src/remotefs/mod.rs, rust/cubestore/cubestore/src/remotefs/queue.rs
=> chore(cubestore): Remove old local files refactoring

rust/cubestore/cubestore/src/metastore/mod.rs, rust/cubestore/cubestore/src/remotefs/cleanup.rs
=> chore(cubestore): Delay in deleting local files

packages/cubejs-backend-native/TECH.md, packages/cubejs-backend-native/js/index.ts, packages/cubejs-backend-native/package.json, packages/cubejs-backend-native/python/cube/src/__init__.py, packages/cubejs-backend-native/src/lib.rs, packages/cubejs-backend-native/src/python/cross.rs, packages/cubejs-backend-native/src/python/entry.rs, packages/cubejs-backend-native/src/python/mod.rs, packages/cubejs-backend-native/src/python/python_model.rs, packages/cubejs-backend-native/src/python/runtime.rs, packages/cubejs-backend-native/src/python/template/entry.rs, packages/cubejs-backend-native/src/python/template/mj_value.rs, packages/cubejs-backend-native/test/__snapshots__/jinja.test.ts.snap, packages/cubejs-backend-native/test/jinja.test.ts, packages/cubejs-backend-native/test/templates/data-model.yml.jinja, packages/cubejs-backend-native/test/templates/utils.py, packages/cubejs-backend-shared/src/FileRepository.ts, packages/cubejs-schema-compiler/src/compiler/DataSchemaCompiler.js, packages/cubejs-schema-compiler/src/compiler/PrepareCompiler.ts, packages/cubejs-schema-compiler/src/compiler/YamlCompiler.ts, packages/cubejs-server-core/package.json, packages/cubejs-server-core/src/core/CompilerApi.js, packages/cubejs-server-core/src/index.ts
=> feat(schema): Support python @context_func for jinja templates

packages/cubejs-backend-native/src/python/template/entry.rs, packages/cubejs-backend-native/test/__snapshots__/jinja.test.ts.snap
=> fix(schema): Jinja - show source line on error

packages/cubejs-backend-native/js/index.ts, packages/cubejs-backend-native/src/python/entry.rs, packages/cubejs-backend-native/test/python.test.ts, packages/cubejs-backend-native/test/python.ts, packages/cubejs-backend-native/test/python_async_bench.ts, packages/cubejs-server/src/server/container.ts
=> chore(native): Use correct file name for python module loading

rust/cubestore/cubestore-sql-tests/Cargo.toml, rust/cubestore/cubestore/Cargo.toml, rust/cubestore/cubestore/src/cachestore/cache_rocksstore.rs, rust/cubestore/cubestore/src/metastore/rocks_store.rs
=> chore(cubestore): Allow to configure compression type for RocksStore

packages/cubejs-backend-shared/src/env.ts, packages/cubejs-duckdb-driver/src/DuckDBDriver.ts
enableHttpFs is now always `true`
=> feat(duckdb): s3 config support

packages/cubejs-schema-compiler/src/adapter/MssqlQuery.js, packages/cubejs-schema-compiler/test/integration/mssql/mssql-cumulative-measures.test.ts, packages/cubejs-schema-compiler/test/unit/mssql-query.test.ts
Should resolve #6525
I couldn't execute integration tests for MS SQL (I'm on an M1). Hopefully you folks are ok with the CI executing those after review?
Thanks
=> fix(mssql-driver): Fix group by clause for queries with dimensions and cumulative measures in MS SQL

packages/cubejs-backend-shared/src/env.ts, packages/cubejs-duckdb-driver/src/DuckDBDriver.ts
=> feat(duckdb-driver): Allow to specify memory_limit as env variable

rust/cubestore/cubestore/src/cachestore/cache_rocksstore.rs, rust/cubestore/cubestore/src/cachestore/lazy.rs, rust/cubestore/cubestore/src/metastore/rocks_table.rs, rust/cubestore/cubestore/src/queryplanner/info_schema/info_schema_columns.rs, rust/cubestore/cubestore/src/queryplanner/info_schema/info_schema_schemata.rs, rust/cubestore/cubestore/src/queryplanner/info_schema/info_schema_tables.rs, rust/cubestore/cubestore/src/queryplanner/info_schema/system_cache.rs, rust/cubestore/cubestore/src/queryplanner/info_schema/system_chunks.rs, rust/cubestore/cubestore/src/queryplanner/info_schema/system_indexes.rs, rust/cubestore/cubestore/src/queryplanner/info_schema/system_jobs.rs, rust/cubestore/cubestore/src/queryplanner/info_schema/system_partitions.rs, rust/cubestore/cubestore/src/queryplanner/info_schema/system_queue.rs, rust/cubestore/cubestore/src/queryplanner/info_schema/system_queue_results.rs, rust/cubestore/cubestore/src/queryplanner/info_schema/system_replay_handles.rs, rust/cubestore/cubestore/src/queryplanner/info_schema/system_snapshots.rs, rust/cubestore/cubestore/src/queryplanner/info_schema/system_tables.rs, rust/cubestore/cubestore/src/queryplanner/mod.rs, rust/cubestore/cubestore/src/queryplanner/test_utils.rs
=> feat(cubestore): Use push down limit for system tables

rust/cubestore/cubestore/src/cluster/mod.rs
=> chore(cubestore): Data processing tracing fix

rust/cubestore/cubestore/src/cachestore/cache_item.rs, rust/cubestore/cubestore/src/cachestore/compaction.rs, rust/cubestore/cubestore/src/metastore/mod.rs, rust/cubestore/cubestore/src/metastore/rocks_store.rs, rust/cubestore/cubestore/src/metastore/rocks_table.rs
=> chore(cubestore): RocksSecondaryIndexValue - support HashAndTTLExtended

.github/workflows/push.yml, packages/cubejs-schema-compiler/src/compiler/DataSchemaCompiler.js
=> feat(schema-compiler): Support .yaml.jinja extension, fix #7018

.github/workflows/rust-cubesql.yml, packages/cubejs-schema-compiler/src/adapter/BaseQuery.js, rust/cubesql/cubesql/src/compile/engine/df/wrapper.rs, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/wrapper.rs, rust/cubesql/cubesql/src/compile/test/mod.rs, rust/cubesql/cubesql/src/transport/service.rs
=> feat(cubesql): CASE WHEN SQL push down

rust/cubestore/cubestore/src/cachestore/cache_rocksstore.rs
=> feat(cubestore): Optimize CACHE SET on update (uneeded clone)

rust/cubestore/cubestore/src/config/mod.rs, rust/cubestore/cubestore/src/remotefs/cleanup.rs
=> chore(cubestore): Removing orphaned files from remote fs

rust/cubestore/cubestore/src/cluster/mod.rs, rust/cubestore/cubestore/src/cluster/rate_limiter.rs, rust/cubestore/cubestore/src/queryplanner/mod.rs, rust/cubestore/cubestore/src/queryplanner/serialized_plan.rs, rust/cubestore/cubestore/src/sql/cache.rs, rust/cubestore/cubestore/src/sql/cachestore.rs, rust/cubestore/cubestore/src/sql/mod.rs
=> chore(cubestore): Refactoring of data usage tracing

rust/cubestore/cubestore/src/config/mod.rs, rust/cubestore/cubestore/src/remotefs/cleanup.rs
=> chore(cubestore): Improvements of removing remote orphaned files

rust/cubestore/cubestore/src/cachestore/cache_rocksstore.rs, rust/cubestore/cubestore/src/metastore/rocks_table.rs
=> feat(cubestore): Optimize QUEUE ACK/CANCEL, CACHE DELETE

rust/cubestore/cubestore/src/app_metrics.rs, rust/cubestore/cubestore/src/cachestore/cache_rocksstore.rs, rust/cubestore/cubestore/src/cachestore/lazy.rs, rust/cubestore/cubestore/src/config/mod.rs
=> chore(cubestore): Submit additional metrics for cachestore

rust/cubestore/cubestore/src/cluster/message.rs, rust/cubestore/cubestore/src/cluster/mod.rs, rust/cubestore/cubestore/src/scheduler/mod.rs, rust/cubestore/cubestore/src/store/mod.rs
=> chore(cubestore): Bulk in memory chunks drop

.github/actions/integration/mongobi.sh, .github/actions/smoke.sh, .github/workflows/push.yml, packages/cubejs-mongobi-driver/package.json, packages/cubejs-mongobi-driver/src/MongoBIDriver.ts, packages/cubejs-mongobi-driver/test/Dockerfile, packages/cubejs-mongobi-driver/test/MongoBiDriver.test.ts, packages/cubejs-mongobi-driver/test/config.yaml, packages/cubejs-mongobi-driver/test/docker-compose.yml, packages/cubejs-mongobi-driver/test/mongo-init.js, yarn.lock
Stops passing invalid configuration for mysql2 connection
**Check List**
Relates to #5527 
=> fix(mongobi-driver): invalid configuration for mysql2 connection

docs/content/APIs-Integrations/Orchestration-API/Dagster.mdx
=> update code snippet to import class

rust/cubestore/cubestore/src/app_metrics.rs, rust/cubestore/cubestore/src/cachestore/cache_eviction_manager.rs, rust/cubestore/cubestore/src/cachestore/cache_item.rs, rust/cubestore/cubestore/src/cachestore/cache_rocksstore.rs
=> feat(cubestore): Eviction - truncate expired keys

rust/cubestore/cubestore/src/cachestore/cache_eviction_manager.rs
=> fix(cubestore): Eviction - correct size counting for old keys

packages/cubejs-backend-native/Cargo.lock, packages/cubejs-backend-native/js/index.ts, packages/cubejs-backend-native/python/cube/src/conf/__init__.py, packages/cubejs-backend-native/src/python/cross.rs, packages/cubejs-backend-native/src/python/cube_config.rs, packages/cubejs-backend-native/test/config.py, packages/cubejs-backend-native/test/fixtures/schema-tenant-1/test.yml, packages/cubejs-backend-native/test/fixtures/schema-tenant-1/test.yml.jinja, packages/cubejs-backend-native/test/python.test.ts
=> feat(native): Cube.py - support file_repository

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/test/index.test.ts, packages/cubejs-api-gateway/test/mocks.ts, packages/cubejs-server-core/src/core/RefreshScheduler.ts, packages/cubejs-server-core/src/core/server.ts, packages/cubejs-server-core/src/core/types.ts, packages/cubejs-server-core/test/unit/OptsHandler.test.ts, packages/cubejs-server-core/test/unit/RefreshScheduler.test.ts, packages/cubejs-server-core/test/unit/index.test.ts
=> feat(native): Cube.py - support contextToAppId/contextToOrchestratorId

packages/cubejs-api-gateway/src/SubscriptionServer.ts, packages/cubejs-api-gateway/src/interfaces.ts, packages/cubejs-server-core/src/core/server.ts, packages/cubejs-server-core/src/core/types.ts
=> chore(server): Support async/promises for ContextAcceptor

packages/cubejs-docker/dev-alpine.Dockerfile, packages/cubejs-docker/dev.Dockerfile, packages/cubejs-docker/latest-alpine-jdk.Dockerfile, packages/cubejs-docker/latest-alpine.Dockerfile, packages/cubejs-docker/latest-debian-jdk.Dockerfile, packages/cubejs-docker/latest.Dockerfile, packages/cubejs-docker/local.Dockerfile, packages/cubejs-docker/testing-drivers.Dockerfile
=> feat(docker): Upgrade Node.js to 16.20.2

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/src/helpers/prepareAnnotation.ts, packages/cubejs-api-gateway/src/query.js, packages/cubejs-api-gateway/src/sql-server.ts, packages/cubejs-api-gateway/src/types/query.ts, packages/cubejs-api-gateway/src/types/request.ts, packages/cubejs-backend-native/js/index.ts, packages/cubejs-backend-native/src/transport.rs, packages/cubejs-schema-compiler/src/adapter/BaseDimension.js, packages/cubejs-schema-compiler/src/adapter/BaseMeasure.js, packages/cubejs-schema-compiler/src/adapter/BaseQuery.js, packages/cubejs-schema-compiler/src/adapter/MssqlQuery.js, packages/cubejs-schema-compiler/src/adapter/ParamAllocator.ts, packages/cubejs-schema-compiler/src/adapter/PostgresQuery.js, packages/cubejs-schema-compiler/src/compiler/CubeEvaluator.js, packages/cubejs-schema-compiler/src/compiler/CubeSymbols.js, rust/cubesql/cubesql/src/compile/engine/df/scan.rs, rust/cubesql/cubesql/src/compile/engine/df/wrapper.rs, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/converter.rs, rust/cubesql/cubesql/src/compile/rewrite/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/members.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/wrapper.rs, rust/cubesql/cubesql/src/compile/test/mod.rs, rust/cubesql/cubesql/src/sql/types.rs, rust/cubesql/cubesql/src/transport/ext.rs, rust/cubesql/cubesql/src/transport/service.rs
=> feat(cubesql): Ungrouped SQL push down

rust/cubestore/cubestore/src/cachestore/cache_rocksstore.rs, rust/cubestore/cubestore/src/metastore/mod.rs, rust/cubestore/cubestore/src/metastore/rocks_store.rs
=> feat(cubestore): Increase parallelism for Cache Store

rust/cubestore/Cargo.lock, rust/cubestore/cubestore/src/sql/mod.rs
=> fix(cubestore): COUNT(*) don't work on subquery with aggregation

rust/cubestore/Cargo.lock, rust/cubestore/cubestore/src/sql/mod.rs
=> fix(cubestore): Fix error in projection pushdown

rust/cubestore/cubestore/src/cachestore/cache_eviction_manager.rs, rust/cubestore/cubestore/src/config/mod.rs
=> feat(cubestore): Cache Store - auto trigger for full compaction

packages/cubejs-backend-native/python/cube/src/conf/__init__.py, packages/cubejs-backend-native/src/python/cube_config.rs
=> feat(native): Cube.py - support semanticLayerSync/schemaVersion

packages/cubejs-backend-native/src/python/template/mj_value.rs, packages/cubejs-backend-native/test/__snapshots__/jinja.test.ts.snap, packages/cubejs-backend-native/test/jinja.test.ts, packages/cubejs-backend-native/test/templates/arguments-test.yml.jinja, packages/cubejs-backend-native/test/templates/scoped-utils.py, packages/cubejs-backend-native/test/templates/utils.py
=> feat(native): Jinja - support passing Map/Seq to Python

packages/cubejs-backend-native/Cargo.lock, packages/cubejs-backend-native/Cargo.toml, packages/cubejs-backend-native/src/python/entry.rs
=> feat(native): Initial support for Python 3.12

packages/cubejs-backend-native/python/cube/src/conf/__init__.py, packages/cubejs-backend-native/src/python/cube_config.rs, packages/cubejs-server-core/src/core/server.ts, packages/cubejs-server-core/src/core/types.ts
=> feat(native): Cube.py - support pre_aggregations_schema

packages/cubejs-backend-native/python/cube/src/conf/__init__.py, packages/cubejs-backend-native/test/config.py, packages/cubejs-backend-native/test/scoped-config.py
=> feat(native): Cube.py - introduce `@config` decorator

packages/cubejs-backend-shared/src/env.ts, packages/cubejs-databricks-jdbc-driver/src/DatabricksQuery.ts, packages/cubejs-duckdb-driver/src/DuckDBQuery.ts, packages/cubejs-schema-compiler/src/adapter/BaseDimension.js, packages/cubejs-schema-compiler/src/adapter/BaseFilter.js, packages/cubejs-schema-compiler/src/adapter/BaseQuery.js, packages/cubejs-schema-compiler/src/adapter/BaseTimeDimension.js, packages/cubejs-schema-compiler/src/adapter/PostgresQuery.js, packages/cubejs-schema-compiler/src/adapter/PrestodbQuery.js, packages/cubejs-schema-compiler/src/adapter/SnowflakeQuery.js, packages/cubejs-server-core/src/core/CompilerApi.js, packages/cubejs-server-core/src/core/server.ts
=> feat(cubesql): DATE_TRUNC support for SQL push down

rust/cubestore/cubestore/src/cachestore/cache_eviction_manager.rs, rust/cubestore/cubestore/src/metastore/rocks_store.rs
=> fix(cubestore): Eviction - schedule compaction as blocking task

packages/cubejs-server-core/src/core/optionsValidate.ts
=> feat: Strict type validation for config

docs/docs-new/pages/_meta.js, docs/docs-new/styles/globals.css
=> fix(docs): change header layout

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/src/types/auth.ts, packages/cubejs-backend-native/python/cube/src/conf/__init__.py, packages/cubejs-backend-native/src/python/cross.rs, packages/cubejs-backend-native/src/python/cube_config.rs, packages/cubejs-backend-native/src/python/entry.rs, packages/cubejs-server-core/src/core/optionsValidate.ts, packages/cubejs-server-core/src/core/server.ts, packages/cubejs-server-core/src/core/types.ts, packages/cubejs-server/src/server.ts
=> feat(native): Cube.py - support orchestratorOptions/http/jwt

packages/cubejs-schema-compiler/src/compiler/YamlCompiler.ts, packages/cubejs-schema-compiler/test/unit/yaml-schema.test.ts
Hello!
Fix https://github.com/cube-js/cube/issues/7126
Thanks
=> fix(schema-compiler): Yaml - crash on empty string/null, fix #7126

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js, packages/cubejs-schema-compiler/src/adapter/BigqueryQuery.js, packages/cubejs-schema-compiler/src/adapter/PostgresQuery.js, packages/cubejs-schema-compiler/src/adapter/PrestodbQuery.js, packages/cubejs-schema-compiler/src/adapter/SnowflakeQuery.js, rust/cubesql/Cargo.lock, rust/cubesql/cubesql/Cargo.toml, rust/cubesql/cubesql/src/compile/engine/df/scan.rs, rust/cubesql/cubesql/src/compile/engine/df/wrapper.rs, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/dates.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/wrapper.rs, rust/cubesql/cubesql/src/compile/test/mod.rs, rust/cubesql/cubesql/src/transport/service.rs
=> feat(cubesql): `EXTRACT` SQL push down

.github/workflows/rust-cubesql.yml, packages/cubejs-backend-native/python/cube/src/__init__.py, packages/cubejs-backend-native/test/__snapshots__/jinja.test.ts.snap, packages/cubejs-backend-native/test/jinja.test.ts, packages/cubejs-backend-native/test/templates/jinja-instance.py, packages/cubejs-server/src/server.ts
=> feat(native): Python - new Jinja API

packages/cubejs-snowflake-driver/package.json, yarn.lock
=> feat(snowflake-driver): Upgrade snowflake driver to 1.8.0

rust/cubestore/Cargo.lock, rust/cubestore/cubestore-sql-tests/src/tests.rs
=> fix(cubestore): Escape regex symbols in like operator

packages/cubejs-schema-compiler/src/compiler/DataSchemaCompiler.js
=> feat(python): Evaluate Jinja templates inside `.yml` and `.yaml`

rust/cubesql/cubesql/src/compile/engine/df/scan.rs, rust/cubesql/cubesql/src/compile/engine/df/wrapper.rs
=> fix(cubesql): Support unaliased columns for SQL push down

rust/cubesql/Cargo.lock, rust/cubesql/cubesql/Cargo.toml, rust/cubesql/cubesql/e2e/tests/postgres.rs, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__pg_set_role_show.snap, rust/cubesql/cubesql/src/sql/database_variables/postgres/session_vars.rs
**Check List**
This PR adds support for `SET ROLE name` syntax. Related tests are included.
=> feat(cubesql): Support `SET ROLE name`

rust/cubestore/cubestore/src/cachestore/cache_rocksstore.rs, rust/cubestore/cubestore/src/config/mod.rs, rust/cubestore/cubestore/src/metastore/mod.rs, rust/cubestore/cubestore/src/metastore/rocks_store.rs
=> feat(cubestore): Size limit for RocksStore logs file

.github/workflows/push-cross-images.yml, rust/cubestore/cross/README.md, rust/cubestore/cross/aarch64-unknown-linux-gnu.Dockerfile
=> chore(cross): Install python3.9 for aarch64-unknown-linux-gnu

.github/workflows/publish.yml, .github/workflows/rust-cubesql.yml
=> fix(native): Compile python build via cross

packages/cubejs-backend-native/package.json
=> feat(native): Enable python support for Linux/ARM64

rust/cubestore/cross/aarch64-unknown-linux-gnu.Dockerfile, rust/cubestore/cross/x86_64-unknown-linux-gnu.Dockerfile
=> chore(cross): Install Python 3.12

packages/cubejs-backend-native/DEVELOPMENT.md, rust/cubestore/cross/aarch64-unknown-linux-gnu.Dockerfile
=> fix(cross): Enable shared python for aarch64-unknown-linux-gnu

rust/cubestore/cubestore/src/config/mod.rs, rust/cubestore/cubestore/src/import/mod.rs, rust/cubestore/cubestore/src/sql/mod.rs
=> chore(cubestore): Small refactoring of import process

rust/cubestore/Cargo.lock, rust/cubestore/cubestore-sql-tests/src/tests.rs
=> fix(cubestore): Window function don't work with only one Following bound

packages/cubejs-backend-native/src/template/entry.rs, packages/cubejs-backend-native/test/__snapshots__/jinja.test.ts.snap, packages/cubejs-backend-native/test/templates/.utils.jinja, packages/cubejs-backend-native/test/templates/01.yml.jinja, packages/cubejs-backend-native/test/templates/02.yml.jinja, packages/cubejs-backend-native/test/templates/03.yml.jinja, packages/cubejs-backend-native/test/templates/04.yml.jinja, packages/cubejs-backend-native/test/templates/05.yml.jinja
=> fix(native): Jinja - force autoescape for .jinja files

packages/cubejs-backend-native/js/index.ts, packages/cubejs-backend-native/python/cube/src/__init__.py, packages/cubejs-backend-native/src/python/entry.rs, packages/cubejs-backend-native/src/python/python_model.rs, packages/cubejs-backend-native/src/template/entry.rs, packages/cubejs-backend-native/src/template/mj_value/mod.rs, packages/cubejs-backend-native/test/__snapshots__/jinja.test.ts.snap, packages/cubejs-backend-native/test/jinja.test.ts, packages/cubejs-backend-native/test/templates/filters.yml.jinja, packages/cubejs-backend-native/test/templates/jinja-instance.py, packages/cubejs-schema-compiler/src/compiler/DataSchemaCompiler.js, packages/cubejs-schema-compiler/src/compiler/YamlCompiler.ts
=> feat(native): Jinja - passing filters via TemplateContext from Python

rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/converter.rs, rust/cubesql/cubesql/src/compile/rewrite/cost.rs, rust/cubesql/cubesql/src/compile/rewrite/rewriter.rs
=> feat(cubesql): Aggregation over dimensions support

packages/cubejs-oracle-driver/package.json
update oracledb  pacakge to 6.2.0  support `thin` mod
=> feat(oracle-driver): Upgrade to 6.2

rust/cubestore/cubestore/src/cluster/worker_pool.rs
=> chore(cubestore): Fix cancel token for worker pool

packages/cubejs-backend-native/Cargo.lock
Hello!
Link - https://github.com/mitsuhiko/minijinja/blob/main/CHANGELOG.md
It contains important fixes:
- Fixed a memory leak involving macros. Previously using macros was leaking memory due to an undetected cycle.
- Added a new stacker feature which allows raising of the recursion limits. It enables monitoring of the call stack via [stacker](https://crates.io/crates/stacker) and automatically acquires additional memory when the call stack runs out of space.
Thanks
=> feat(native): Jinja - upgrade engine (fixes macros memory leak & stack overflow)

packages/cubejs-backend-native/src/cross/clrepr_python.rs, packages/cubejs-backend-native/src/template/entry.rs, packages/cubejs-backend-native/src/template/mj_value/python.rs, packages/cubejs-backend-native/src/template/mod.rs, packages/cubejs-backend-native/src/template/neon.rs, packages/cubejs-backend-native/test/__snapshots__/jinja.test.ts.snap, packages/cubejs-backend-native/test/jinja.test.ts, packages/cubejs-backend-native/test/templates/dump_context.yml.jinja, packages/cubejs-backend-native/test/templates/jinja-instance.py, packages/cubejs-backend-native/test/templates/python.yml, packages/cubejs-backend-native/test/templates/scoped-utils.py, packages/cubejs-schema-compiler/src/compiler/YamlCompiler.ts
=> feat(native): Jinja - support fields reflection for PyObject

packages/cubejs-base-driver/src/queue-driver.interface.ts, packages/cubejs-cubestore-driver/src/CubeStoreQueueDriver.ts, packages/cubejs-query-orchestrator/src/orchestrator/LocalQueueDriver.js, packages/cubejs-query-orchestrator/src/orchestrator/QueryQueue.js, packages/cubejs-query-orchestrator/src/orchestrator/RedisQueueDriver.ts, packages/cubejs-query-orchestrator/test/unit/QueryQueue.abstract.ts
=> feat(query-orchestrator): Use real queueId in events for processing

packages/cubejs-api-gateway/src/sql-server.ts, packages/cubejs-backend-native/js/index.ts, packages/cubejs-backend-native/src/channel.rs, packages/cubejs-backend-native/src/lib.rs, packages/cubejs-backend-native/src/node_obj_serializer.rs, packages/cubejs-backend-native/src/template/mj_value/python.rs, packages/cubejs-backend-native/src/transport.rs, packages/cubejs-backend-native/test/sql.test.ts, rust/cubesql/cubesql/src/compile/engine/df/scan.rs, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__set_bad_user.snap, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__set_good_user.snap, rust/cubesql/cubesql/src/compile/test/mod.rs, rust/cubesql/cubesql/src/transport/service.rs
=> feat(cubesql): Allow changing current user through `SET user = ?`

rust/cubestore/cubestore/src/cluster/worker_pool.rs, rust/cubestore/cubestore/src/cluster/worker_services.rs
=> chore(cubestore): Fix timeout in worker services

packages/cubejs-query-orchestrator/src/orchestrator/QueryQueue.js
=> refactor(query-queue): Skip generating processingId for Memory & Cube Store

rust/cubestore/Cargo.lock, rust/cubestore/cubestore-sql-tests/src/tests.rs
=> fix(cubestore): Error with pre-aggregation and filters containing comma.

rust/cubestore/cubestore/src/cachestore/cache_rocksstore.rs, rust/cubestore/cubestore/src/config/mod.rs
=> feat(cubestore): Introduce limit for cache_max_entry_size

.github/workflows/publish.yml, .github/workflows/rust-cubestore-master.yml, .github/workflows/rust-cubestore.yml
=> chore(ci): Improve cache for cross building

rust/cubestore/cubestore/src/cluster/worker_services.rs
=> fix(cubestore): Fix broadcasting for worker services

packages/cubejs-backend-native/Cargo.lock, packages/cubejs-backend-native/Cargo.toml, packages/cubejs-backend-native/js/index.ts, packages/cubejs-backend-native/src/lib.rs, packages/cubejs-backend-native/src/template/entry.rs, packages/cubejs-backend-native/src/template/mod.rs, packages/cubejs-backend-native/src/template/workers.rs, packages/cubejs-backend-native/test/jinja.test.ts, packages/cubejs-schema-compiler/src/compiler/DataSchemaCompiler.js, packages/cubejs-schema-compiler/src/compiler/YamlCompiler.ts
=> feat(native): Jinja - don't block schema compiler (async render)

packages/cubejs-backend-native/src/template/engine_python.rs, packages/cubejs-backend-native/src/template/entry.rs, packages/cubejs-backend-native/src/template/mod.rs
=> refactor(native): Jinja - separate injection of Python filters

packages/cubejs-backend-native/src/python/mod.rs, packages/cubejs-backend-native/src/python/utils.rs, packages/cubejs-backend-native/src/template/engine_python.rs, packages/cubejs-backend-native/src/template/mj_value/python.rs
=> refactor(native): Python - extract calling

packages/cubejs-server/src/server/container.ts
=> feat(server): Mark cube.py as stable

packages/cubejs-duckdb-driver/src/DuckDBDriver.ts, packages/cubejs-duckdb-driver/test/DuckDBDriver.test.ts
=> fix(duckdb-driver): Compatibility issue with Cube Store for DATE type

packages/cubejs-cubestore-driver/src/CubeStoreDriver.ts
=> fix(cubestore-driver): Import - check introspection results

rust/cubestore/Cargo.lock, rust/cubestore/cubestore/Cargo.toml
Hello!
https://nvd.nist.gov/vuln/detail/CVE-2023-43669
Thanks
=> chore(cubestore): Upgrade warp/tungstenite (mitigate CVE-2023-43669)

packages/cubejs-client-core/index.d.ts, packages/cubejs-client-core/src/ResultSet.js
=> feat(@cubejs-client/core): expose total rows (#7140)

packages/cubejs-client-core/index.d.ts
https://cube.dev/docs/reference/data-model/types-and-formats#measure-formats
=> fix: support for format in typings for measures

.github/actions/integration/druid.sh, packages/cubejs-druid-driver/docker-compose.yml, packages/cubejs-druid-driver/src/DruidClient.ts, packages/cubejs-druid-driver/src/DruidDriver.ts, packages/cubejs-druid-driver/test/druid-driver.test.ts
=> feat(druid-driver): Retrieve types for columns with new Druid versions

rust/cubestore/cubestore/src/cluster/mod.rs, rust/cubestore/cubestore/src/cluster/worker_pool.rs, rust/cubestore/cubestore/src/cluster/worker_services.rs
=> chore(cubestore): Small refactoring of workers startup

rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/converter.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/wrapper/column.rs, rust/cubesql/cubesql/src/transport/ctx.rs
=> feat(cubesql): SQL push down support for synthetic fields

packages/cubejs-testing-drivers/fixtures/clickhouse.json, yarn.lock
=> chore(ci): Lock version for clickhouse

rust/cubestore/cubestore/src/sql/cachestore.rs, rust/cubestore/cubestore/src/sql/mod.rs, rust/cubestore/cubestore/src/sql/parser.rs, rust/cubestore/cubestore/src/util/metrics.rs
=> feat(cubestore): Metrics - track type for data/cache/queue

rust/cubestore/Cargo.lock, rust/cubestore/cubestore/src/store/compaction.rs
=> fix(cubestore): Natural order for Int96 and Decimal96

rust/cubestore/cubestore/src/cachestore/cache_rocksstore.rs, rust/cubestore/cubestore/src/cachestore/scheduler.rs, rust/cubestore/cubestore/src/sql/cache.rs
=> chore(cubestore): Reset gauge metrics on shutdown

packages/cubejs-athena-driver/src/AthenaDriver.ts
=> fix(athena-driver) #7407 allow to pass credentials

.github/workflows/push.yml, .github/workflows/rust-cubesql.yml, packages/cubejs-backend-native/js/index.ts, packages/cubejs-databricks-jdbc-driver/src/DatabricksDriver.ts, packages/cubejs-linter/package.json, packages/cubejs-query-orchestrator/src/orchestrator/QueryStream.ts, yarn.lock
=> chore(deps): Bump eslint, typescript-eslint to support TypeScript 5.2

packages/cubejs-backend-shared/src/package.ts, packages/cubejs-backend-shared/test/package.test.ts
**Check List**
https://github.com/cube-js/cube/issues/7452
=> Allow to use ECDSA SSL keys

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/test/index.test.ts
=> fix(api-gateway): Handle invalid query (invalid JSON) as 400 Bad Request

packages/cubejs-schema-compiler/src/adapter/MongoBiQuery.js
**Check List**
- [] Tests has been run in packages where changes made if available
- [] Linter has been run for changed code
#7152 
=> replaced argument inside minute check

rust/cubestore/cubestore/src/cluster/ingestion/job_runner.rs, rust/cubestore/cubestore/src/cluster/mod.rs, rust/cubestore/cubestore/src/cluster/rate_limiter.rs
=> chore(cubestore): Refactoring of RateLimiter

rust/cubesql/cubesql/src/compile/engine/df/wrapper.rs, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/test/mod.rs
=> fix(cubesql): Missing template backslash escaping

packages/cubejs-query-orchestrator/src/orchestrator/QueryQueue.js
=> fix(query-orchestartor): Queue - fix possible memory leak with timer

.github/workflows/publish.yml, .github/workflows/rust-cubesql.yml, .github/workflows/rust-cubestore-master.yml, .github/workflows/rust-cubestore.yml
=> chore(ci): Bump Swatinem/rust-cache, allenevans/set-env

packages/cubejs-schema-compiler/src/adapter/BaseGroupFilter.js, packages/cubejs-schema-compiler/src/adapter/BaseQuery.js, packages/cubejs-schema-compiler/test/unit/base-query.test.ts
=> test(schema-compiler): FilterParams - test or->and, and->or

packages/cubejs-client-core/index.d.ts, packages/cubejs-client-ngx/angular.json, packages/cubejs-client-ngx/package.json, packages/cubejs-client-ngx/tsconfig.json
=> feat(client-ngx): enable ivy

rust/cubestore/Cargo.lock, rust/cubestore/cubestore-sql-tests/src/tests.rs, rust/cubestore/cubestore/src/queryplanner/planning.rs
=> fix(cubestore): InplaceAggregate for boolean columns

packages/cubejs-schema-compiler/src/compiler/JoinGraph.js, packages/cubejs-schema-compiler/test/integration/postgres/yaml-compiler.test.ts
=> fix: View tries to join cube twice in case there's join ambiguity

packages/cubejs-databricks-jdbc-driver/src/DatabricksQuery.ts, packages/cubejs-duckdb-driver/src/DuckDBQuery.ts, packages/cubejs-firebolt-driver/src/FireboltQuery.ts, packages/cubejs-questdb-driver/src/QuestQuery.ts, packages/cubejs-schema-compiler/src/adapter/BaseDimension.ts, packages/cubejs-schema-compiler/src/adapter/BaseFilter.ts, packages/cubejs-schema-compiler/src/adapter/BaseGroupFilter.ts, packages/cubejs-schema-compiler/src/adapter/BaseMeasure.ts, packages/cubejs-schema-compiler/src/adapter/BaseQuery.js, packages/cubejs-schema-compiler/src/adapter/BaseSegment.ts, packages/cubejs-schema-compiler/src/adapter/BaseTimeDimension.ts, packages/cubejs-schema-compiler/src/adapter/ParamAllocator.ts
=> refactor(schema-compiler): Migrate code to TypeScript

packages/cubejs-schema-compiler/src/adapter/BaseDimension.ts, packages/cubejs-schema-compiler/src/adapter/BaseQuery.js, packages/cubejs-schema-compiler/src/compiler/ContextEvaluator.js, packages/cubejs-schema-compiler/src/compiler/CubeEvaluator.ts, packages/cubejs-schema-compiler/src/compiler/CubeToMetaTransformer.js, packages/cubejs-schema-compiler/src/compiler/JoinGraph.js
=> refactor(schema-compiler): CubeEvaluator - migrate to TypeScript

packages/cubejs-query-orchestrator/src/orchestrator/QueryQueue.js, packages/cubejs-query-orchestrator/test/unit/QueryQueue.abstract.ts
=> test(query-stream): Queue - make stream test stable

packages/cubejs-api-gateway/package.json, yarn.lock
Hello!
refs https://github.com/advisories/GHSA-hrpp-h998-j3pp
Thanks
=> fix(deps): Upgrade qs to protect possible (CVE-2022-24999)

rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/parser.rs, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__sigma_computing_attnames.snap
**Check List**
This PR fixes an issue that prevented Sigma Computing from syncing the schema of a table. Related test is included.
=> fix(cubesql): Support Sigma Computing table schema sync

rust/cubestore/cubestore/src/cluster/rate_limiter.rs, rust/cubestore/cubestore/src/config/mod.rs, rust/cubestore/cubestore/src/sql/cachestore.rs, rust/cubestore/cubestore/src/sql/mod.rs
=> chore(cubestore): Introduce rate limits for Cache & Queue

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/src/sql-server.ts, packages/cubejs-api-gateway/src/types/request.ts, packages/cubejs-backend-native/js/index.ts, packages/cubejs-backend-native/src/lib.rs, packages/cubejs-backend-native/src/transport.rs, packages/cubejs-backend-native/test/sql.test.ts, rust/cubesql/cubesql/src/compile/engine/df/scan.rs, rust/cubesql/cubesql/src/compile/engine/df/wrapper.rs, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/converter.rs, rust/cubesql/cubesql/src/compile/rewrite/rewriter.rs, rust/cubesql/cubesql/src/compile/test/mod.rs, rust/cubesql/cubesql/src/sql/postgres/extended.rs, rust/cubesql/cubesql/src/sql/postgres/shim.rs, rust/cubesql/cubesql/src/transport/service.rs
=> feat(cubesql): Additional trace event logging for SQL API

rust/cubestore/cubestore/src/cachestore/cache_rocksstore.rs, rust/cubestore/cubestore/src/sql/cachestore.rs, rust/cubestore/cubestore/src/store/mod.rs, rust/cubestore/cubestore/src/table/mod.rs
=> chore(cubestore): Track size for payload in rate limiter

rust/cubesql/Cargo.lock, rust/cubesql/cubesql/Cargo.toml
=> chore(cubesql): Upgrade tokio to 1.35

packages/cubejs-client-core/index.d.ts
=> chore(client-core): add meta field to cube type def

.github/actions/integration/clickhouse.sh, packages/cubejs-clickhouse-driver/package.json, packages/cubejs-clickhouse-driver/src/ClickHouseDriver.ts, packages/cubejs-clickhouse-driver/src/HydrationStream.ts, packages/cubejs-clickhouse-driver/test/ClickHouseDriver.test.ts, packages/cubejs-schema-compiler/test/integration/clickhouse/ClickHouseDbRunner.js, packages/cubejs-testing-shared/src/db/clickhouse.ts, packages/cubejs-testing-shared/src/db/index.ts
=> fix(clickhouse-driver): Correct parsing for DateTime64, fix #7537

packages/cubejs-backend-native/src/node_obj_serializer.rs
=> feat(native): NodeObjSerializer - support serializing sequences

packages/cubejs-jdbc-driver/package.json, packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts, yarn.lock
=> feat(jdbc-driver): Upgrade java to ^0.14

.github/workflows/drivers-tests.yml, .github/workflows/master.yml, .github/workflows/publish.yml, .github/workflows/push-cross-images.yml, .github/workflows/rust-cubestore-master.yml, packages/cubejs-clickhouse-driver/src/HydrationStream.ts, packages/cubejs-clickhouse-driver/test/ClickHouseDriver.test.ts, packages/cubejs-testing-drivers/fixtures/clickhouse.json, packages/cubejs-testing-drivers/src/helpers/runEnvironment.ts
=> fix(clickhouse-driver): Correct parsing for DateTime('timezone')

packages/cubejs-databricks-jdbc-driver/src/DatabricksQuery.ts, packages/cubejs-testing-drivers/fixtures/_schemas.json, packages/cubejs-testing-drivers/fixtures/athena.json, packages/cubejs-testing-drivers/fixtures/bigquery.json, packages/cubejs-testing-drivers/fixtures/clickhouse.json, packages/cubejs-testing-drivers/package.json, packages/cubejs-testing-drivers/src/helpers/runEnvironment.ts, packages/cubejs-testing-drivers/src/tests/testQueries.ts, packages/cubejs-testing-drivers/test/__snapshots__/databricks-jdbc-full.test.ts.snap
=> fix(databricks-jdbc-driver): Time series query with rolling window

rust/cubestore/Cargo.lock
=> fix(cubestore): Panic in hash join

rust/cubestore/Cargo.lock, rust/cubestore/cubestore/Cargo.toml, rust/cubestore/cubestore/src/util/respawn.rs
=> chore(cubestore): Remove unexpected import of serde re-export

rust/cubestore/Cargo.lock
=> chore(cubestore): Support compiling RocksDB with GCC 13

docs/pages/product/caching.mdx
**Check List**
Renamed the caching page so it shows up better in search results and modified one sentence for better readability.
=> Rename caching page

rust/cubesql/cubesql/src/compile/engine/udf.rs, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__to_char_3.snap
=> feat(cubesql): TO_CHAR - support more formats, correct NULL handling

docs/pages/product/data-modeling/concepts.mdx
**Check List**
Fix some small typos I noticed in this doc page.
=> Fix typos in concepts.mdx

packages/cubejs-schema-compiler/src/compiler/CubeSymbols.js, packages/cubejs-schema-compiler/test/unit/views.test.ts
**Check List**
#7475
Modified CubeSymbol.js to assign the resolved members' title.
=> feat(view): members inherit title attribute

packages/cubejs-backend-native/Cargo.lock, rust/cubesql/Cargo.lock, rust/cubesql/cubesql/Cargo.toml, rust/cubesql/cubesql/src/compile/engine/df/scan.rs, rust/cubesql/cubesql/src/compile/engine/df/wrapper.rs, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/analysis.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/dates.rs, rust/cubesql/cubesql/src/compile/test/mod.rs
**Check List**
This PR improves compatibility with Thoughtspot, adding support for KPI charts. Related tests are included.
=> feat(cubesql): Support KPI chart in Thoughtspot

rust/cubestore/cubestore/src/cluster/mod.rs, rust/cubestore/cubestore/src/cluster/worker_pool.rs, rust/cubestore/cubestore/src/cluster/worker_services.rs
=> chore(cubestore): Single job processes

rust/cubestore/cubestore/src/cluster/worker_pool.rs
=> fix(cubestore): Single job process don't stop after job done

docs/pages/product/getting-started/cloud/query-from-bi.mdx
=> Remove old office hours callout

docs/pages/product/caching/using-pre-aggregations.mdx
Export bucket information linked to DB setup pages. They should link to the export bucket headers on those pages.
**Check List**
=> Link to export bucket headers

rust/cubestore/cubestore/src/cluster/mod.rs, rust/cubestore/cubestore/src/config/mod.rs, rust/cubestore/cubestore/src/metastore/job.rs, rust/cubestore/cubestore/src/metastore/mod.rs, rust/cubestore/cubestore/src/queryplanner/test_utils.rs, rust/cubestore/cubestore/src/scheduler/mod.rs, rust/cubestore/cubestore/src/sql/cache.rs, rust/cubestore/cubestore/src/sql/mod.rs, rust/cubestore/cubestore/src/sql/table_creator.rs, rust/cubestore/cubestore/src/store/compaction.rs, rust/cubestore/cubestore/src/store/mod.rs
=> feat(cubestore): CREATE TABLE IF NOT EXISTS support

packages/cubejs-api-gateway/src/graphql.ts
=> feat: Add `ungrouped` flag to GraphQL API

rust/cubestore/cubestore/src/cluster/message.rs, rust/cubestore/cubestore/src/cluster/mod.rs, rust/cubestore/cubestore/src/scheduler/mod.rs, rust/cubestore/cubestore/src/store/compaction.rs, rust/cubestore/cubestore/src/store/mod.rs, rust/cubestore/cubestore/src/streaming/mod.rs
=> fix(cubestore): Use file_name instead of id for in memory chunks

packages/cubejs-backend-native/Cargo.lock, rust/cubesql/Cargo.lock, rust/cubesql/cubesql/Cargo.toml, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__tableau_extract_epoch.snap
=> feat(cubesql): EXTRACT(EPOCH, ...) support

docs/pages/reference/rest-api.mdx
**Check List**
[#7740]
Add missing `meta` property to cube
=> docs: rest-api add meta property to cube

packages/cubejs-backend-native/Cargo.lock, rust/cubesql/Cargo.lock, rust/cubesql/cubesql/Cargo.toml, rust/cubesql/cubesql/src/compile/mod.rs
=> feat(cubesql): Strings with Unicode Escapes

docs/pages/product/workspace/semantic-layer-sync.mdx
Quick typo fix!
**Check List**
=> Update semantic-layer-sync.mdx typo

rust/cubesql/cubesql/src/compile/engine/udf.rs
**Check List**
This PR fixes `DATEDIFF` function, allowing `Timestamp` values of different `TimeUnit`s to be accepted as input.
=> fix(cubesql): Allow different `Timestamp` types in `DATEDIFF`

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/src/sql-server.ts, packages/cubejs-api-gateway/src/types/request.ts, packages/cubejs-schema-compiler/src/adapter/BaseQuery.js, packages/cubejs-testing/birdbox-fixtures/postgresql/schema/BigOrders.js, packages/cubejs-testing/test/__snapshots__/smoke-cubesql.test.ts.snap, packages/cubejs-testing/test/smoke-cubesql.test.ts, rust/cubesql/cubesql/src/compile/engine/df/planner.rs, rust/cubesql/cubesql/src/compile/engine/df/scan.rs, rust/cubesql/cubesql/src/compile/engine/df/wrapper.rs, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/converter.rs, rust/cubesql/cubesql/src/compile/test/mod.rs, rust/cubesql/cubesql/src/config/mod.rs, rust/cubesql/cubesql/src/sql/postgres/shim.rs
=> fix(cubesql): Remove excessive limit on inner wrapped queries

packages/cubejs-schema-compiler/src/adapter/PreAggregations.js, packages/cubejs-schema-compiler/test/unit/pre-aggregations.test.ts, packages/cubejs-schema-compiler/test/unit/utils.ts
=> fix(cubesql): Partition pruning doesn't work when view uses proxy member

packages/cubejs-backend-native/Cargo.lock, rust/cubesql/Cargo.lock, rust/cubesql/cubesql/Cargo.toml, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__fetch_next_rows_only.snap
**Check List**
This PR adds support for `FETCH <FIRST | NEXT> n ROWS ONLY` clause that works like a `LIMIT`. Related test is included.
=> feat(cubesql): Support `FETCH ... n ROWS ONLY`

.github/workflows/drivers-tests.yml, .github/workflows/rust-cubesql.yml
=> chore(ci): Run Driver tests on SQL API changes

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/src/types/request.ts, packages/cubejs-base-driver/src/cache-driver.interface.ts, packages/cubejs-server-core/src/core/RefreshScheduler.ts
=> fix: Job API - correct handling when job is not_found

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/src/types/request.ts, packages/cubejs-server-core/src/core/RefreshScheduler.ts
=> fix: Job API - correct handling on missed pre_agg

packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts
=> fix(query-orchestrator): Job API - builds are not triggered, fix #7726

rust/cubestore/cubestore/src/config/mod.rs
=> fix(cubestore): Wrong calculation of default compaction trigger

rust/cubestore/Cargo.lock, rust/cubestore/cubestore/Cargo.toml, rust/cubestore/cubestore/src/metastore/rocks_fs.rs, rust/cubestore/cubestore/src/metastore/rocks_store.rs
=> feat(cubestore): Reduce memory usage while writting WALs

rust/cubestore/cubestore/src/cachestore/cache_rocksstore.rs, rust/cubestore/cubestore/src/cachestore/queue_item.rs
=> feat(cubestore): Queue - reduce memory usage

docs/pages/reference/configuration/environment-variables.mdx
**Check List**
[Link to source code](https://github.com/cube-js/cube/blob/a55ee863de7c7dfdf2c993ea549ca4cc11f10ca9/packages/cubejs-server-core/src/core/OptsHandler.ts#L464)
CUBE_SCHEDULED_REFRESH_CONCURRENCY has a default
=> Update scheduled refresh concurrency env default

rust/cubestore/cubestore-sql-tests/benches/in_process.rs, rust/cubestore/cubestore-sql-tests/src/benches.rs
=> chore(cubestore): Add benchmark for QUEUE LIST

rust/cubestore/cubestore/src/cachestore/compaction.rs, rust/cubestore/cubestore/src/metastore/rocks_store.rs, rust/cubestore/cubestore/src/metastore/rocks_table.rs
=> fix(cubestore): RocksStore - improve panic safety on migration

docs/pages/product/apis-integrations/sql-api.mdx
https://cube-docs-prod-q6xmzh41v-cube-dev.vercel.app/product/apis-integrations/sql-api#aggregated-and-non-aggregated-queries
=> docs: Aggregate functions for measures in SQL API

rust/cubestore/cross/aarch64-unknown-linux-gnu.Dockerfile, rust/cubestore/cross/x86_64-unknown-linux-gnu.Dockerfile, rust/cubestore/cross/x86_64-unknown-linux-musl.Dockerfile
=> feat(cross): Upgrade llvm from 14 to 18 (02042024)

.github/workflows/drivers-tests.yml, .github/workflows/publish.yml, .github/workflows/rust-cubesql.yml, .github/workflows/rust-cubestore.yml, rust/cubestore/Dockerfile
=> feat(cubestore): Upgrade LLVM/Clang from 14 to 18

rust/cubestore/Cross.toml
=> chore(cubestore): Upgrade cross to 02042024

rust/cubestore/Cargo.lock, rust/cubestore/cubestore-sql-tests/Cargo.toml, rust/cubestore/cubestore/Cargo.toml, rust/cubestore/cubestore/src/http/mod.rs, rust/cubestore/cubestore/src/metastore/mod.rs
=> chore(cubestore): Upgrade tokio to 1.37.0

rust/cubesql/cubesql/src/compile/engine/udf.rs, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__has_schema_privilege.snap, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__has_schema_privilege_default_user.snap, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__has_schema_privilege_multiple.snap
=> fix(cubesql): has_schema_privilege - compatiblity with PostgreSQL

packages/cubejs-server-core/src/core/DevServer.ts, packages/cubejs-server-core/src/core/OptsHandler.ts, packages/cubejs-server-core/src/core/types.ts
=> fix(server-core): Handle schemaPath default value correctly everywhere

rust/cubesql/cubesql/src/compile/engine/udf/common.rs, rust/cubesql/cubesql/src/compile/engine/udf/mod.rs, rust/cubesql/cubesql/src/compile/engine/udf/pg_catalog.rs, rust/cubesql/cubesql/src/compile/engine/udf/utils.rs, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__has_any_column_privilege.snap, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__has_any_column_privilege_default_user.snap, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__has_table_privilege_default_user.snap, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__metabase_table_privilege_query_v2.snap
- Introduce support for `pg_catalog`.`has_any_column_privilege`
- Support lowercase priveleges for `pg_catalog`.`has_table_privilege`
- Refactor UDFs organization
=> fix(cubesql): Support latest Metabase, fix #8105

packages/cubejs-schema-compiler/src/adapter/MssqlQuery.ts, packages/cubejs-schema-compiler/test/integration/mssql/mssql-ungrouped.test.ts, packages/cubejs-schema-compiler/test/unit/mssql-query.test.ts
=> fix: ungrouped not getting applied for MSSQL

rust/cubestore/Cargo.lock, rust/cubestore/cubestore/src/sql/mod.rs
=> fix(cubestore): Fix wrong optimization in total count queries

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js, packages/cubejs-schema-compiler/src/adapter/BaseSegment.ts, packages/cubejs-schema-compiler/test/integration/postgres/sql-generation.test.ts, packages/cubejs-testing/birdbox-fixtures/postgresql/schema/Orders.js, packages/cubejs-testing/test/__snapshots__/smoke-cubesql.test.ts.snap, packages/cubejs-testing/test/smoke-cubesql.test.ts
=> feat: Post aggregate view support

docs/pages/product/deployment/cloud/aws.mdx
=> docs(byoc): Require extra permissions for AWS setup

rust/cubestore/Cargo.lock, rust/cubestore/cubestore/Cargo.toml
Fix https://github.com/cube-js/cube/issues/8163
=> fix(cubestore): S3 - STS credentials (backport fix for 0.32.3)

packages/cubejs-schema-compiler/src/adapter/BaseMeasure.ts, packages/cubejs-schema-compiler/src/adapter/BaseQuery.js, packages/cubejs-schema-compiler/src/compiler/CubeValidator.ts, packages/cubejs-schema-compiler/test/integration/postgres/sql-generation.test.ts, yarn.lock
=> feat: Rolling YTD, QTD and MTD measure support

docs/pages/product/deployment/cloud/vpc/aws.mdx
=> docs(cloud): Add mention of the dedicated pre-aggs storage to the AWS

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js, packages/cubejs-schema-compiler/src/adapter/BaseTimeDimension.ts, packages/cubejs-schema-compiler/src/compiler/CubeEvaluator.ts, packages/cubejs-schema-compiler/src/compiler/CubeValidator.ts, packages/cubejs-schema-compiler/src/compiler/transpilers/CubePropContextTranspiler.ts, packages/cubejs-schema-compiler/test/integration/postgres/sql-generation.test.ts
=> feat: Support post-aggregate time shifts for prior period lookup support

packages/cubejs-schema-compiler/package.json, yarn.lock
**Check List**
Resolves #8203 . This addresses a security vulnerability in the Luxon package.
Updated `cron-parser` to `^4.9.0`
=> updated the cron-parser package in the schema compiler

packages/cubejs-schema-compiler/src/adapter/BaseDimension.ts, packages/cubejs-schema-compiler/src/adapter/BaseMeasure.ts, packages/cubejs-schema-compiler/src/adapter/BaseQuery.js, packages/cubejs-schema-compiler/src/adapter/BaseTimeDimension.ts, packages/cubejs-schema-compiler/src/adapter/PreAggregations.js, packages/cubejs-testing-drivers/fixtures/_schemas.json, packages/cubejs-testing-drivers/fixtures/bigquery.json, packages/cubejs-testing-drivers/fixtures/mysql.json, packages/cubejs-testing-drivers/src/tests/testQueries.ts, packages/cubejs-testing-drivers/test/__snapshots__/athena-full.test.ts.snap, packages/cubejs-testing-drivers/test/__snapshots__/bigquery-full.test.ts.snap, packages/cubejs-testing-drivers/test/__snapshots__/clickhouse-full.test.ts.snap, packages/cubejs-testing-drivers/test/__snapshots__/databricks-jdbc-export-bucket-full.test.ts.snap, packages/cubejs-testing-drivers/test/__snapshots__/databricks-jdbc-full.test.ts.snap, packages/cubejs-testing-drivers/test/__snapshots__/mssql-full.test.ts.snap, packages/cubejs-testing-drivers/test/__snapshots__/mysql-full.test.ts.snap, packages/cubejs-testing-drivers/test/__snapshots__/postgres-full.test.ts.snap, packages/cubejs-testing-drivers/test/__snapshots__/snowflake-full.test.ts.snap, packages/cubejs-testing-drivers/test/athena-full.test.ts, packages/cubejs-testing-drivers/test/bigquery-full.test.ts, packages/cubejs-testing-drivers/test/mysql-full.test.ts
=> fix: Apply time shift after timezone conversions to avoid double casts

packages/cubejs-api-gateway/src/query.js, packages/cubejs-testing/test/smoke-cubesql.test.ts
=> feat: Support probing `LIMIT 0` queries

rust/cubestore/Cargo.lock
fix https://github.com/cube-js/cube/issues/8163
=> fix(cubestore): S3 - STS credentials (align aws-creds to 0.36 in fork)

rust/cubesql/cubesql/benches/benchmarks.rs, rust/cubesql/cubesql/src/compile/rewrite/analysis.rs
clone:
without:
clone:
without:
=> refactor(cubesql): Analysis - merge without clone (perf)

rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/converter.rs
**Check List**
This PR fixes an issue with time dimension range filters chained with `OR` operator producing `AND` filters, leading to no results. Related test is included.
=> fix(cubesql): Fix time dimension range filter chaining with `OR` operator

.gitignore, CONTRIBUTING.md
**Check List**
Small improvements in development documentation.
=> docs: clarify the development setup in contributing guide

docs/pages/product/apis-integrations.mdx, docs/pages/product/apis-integrations/_meta.js, docs/pages/product/apis-integrations/graphql-api.mdx, docs/pages/product/apis-integrations/javascript-sdk.mdx, docs/pages/product/apis-integrations/javascript-sdk/angular.mdx, docs/pages/product/apis-integrations/javascript-sdk/react.mdx, docs/pages/product/apis-integrations/javascript-sdk/vue.mdx, docs/pages/product/apis-integrations/queries.mdx, docs/pages/product/apis-integrations/rest-api.mdx, docs/pages/product/apis-integrations/rest-api/query-format.mdx, docs/pages/product/apis-integrations/sql-api.mdx, docs/pages/product/apis-integrations/sql-api/_meta.js, docs/pages/product/apis-integrations/sql-api/query-format.mdx, docs/pages/product/caching/matching-pre-aggregations.mdx, docs/pages/product/configuration/visualization-tools/superset.mdx, docs/pages/product/data-modeling/_meta.js, docs/pages/product/data-modeling/concepts/publicity.mdx, docs/pages/product/data-modeling/queries.mdx, docs/pages/reference/configuration/config.mdx, docs/pages/reference/configuration/environment-variables.mdx, docs/pages/reference/graphql-api.mdx, docs/plugins/link-environment-variables.mjs
=> docs: SQL Pushdown

rust/cubesql/cubesql/src/compile/engine/df/coerce.rs, rust/cubesql/cubesql/src/compile/engine/udf/common.rs
Removed 2nd identical coercion function and renamed the only one into a more general
**Check List**
=> cubesql-engine (chore): remove duplicates

packages/cubejs-backend-native/Cargo.lock, rust/cubesql/Cargo.lock, rust/cubesql/cubesql/Cargo.toml, rust/cubesql/cubesql/benches/benchmarks.rs, rust/cubesql/cubesql/src/compile/rewrite/mod.rs
**Check List**
This PR improves rewrite engine performance by updating egg and using new iterative search API in `ListNodeSearcher`. It also adds a few generic query benchmarks.
=> perf(cubesql): Improve rewrite engine performance

packages/cubejs-backend-native/Cargo.lock, rust/cubesql/cubesql/src/compile/engine/df/wrapper.rs, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/cost.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/split/cast.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/split/functions.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/split/mod.rs
**Check List**
This PR ports projection cast split rules. Related test is included.
=> fix(cubesql): Support `CAST` projection split

packages/cubejs-duckdb-driver/package.json, yarn.lock
**Check List**
upgrade the duck-db version to 1.0.0
=> feat(duckdb-driver): Upgrade to DuckDB 1.0.0

packages/cubejs-schema-compiler/src/adapter/PreAggregations.js, packages/cubejs-schema-compiler/test/unit/pre-aggregations.test.ts, packages/cubejs-schema-compiler/test/unit/utils.ts
=> fix(cube): Rebuild of PreAggregations with aggregating indexes

docs/pages/product/workspace.mdx, docs/pages/product/workspace/_meta.js, docs/pages/product/workspace/ai-assistant.mdx, docs/pages/product/workspace/semantic-catalog.mdx
Adds documentation for Semantic Catalog and AI Assistant in Cube Cloud
=> docs: Semantic Catalog and AI assistant

packages/cubejs-schema-compiler/src/adapter/BaseMeasure.ts, packages/cubejs-schema-compiler/src/compiler/CubeValidator.ts, packages/cubejs-schema-compiler/test/integration/postgres/sql-generation.test.ts
=> feat: `to_date` rolling window type syntax

docs/pages/product/deployment/cloud/infrastructure.mdx
=> docs: update cloud infrastructure diagrams

.editorconfig, docs/pages/product/configuration/data-sources/databricks-jdbc.mdx, packages/cubejs-base-driver/src/driver.interface.ts, packages/cubejs-databricks-jdbc-driver/src/DatabricksDriver.ts, packages/cubejs-jdbc-driver/README.md
- **Add .editorconfig for DX convenience**
- **feat(cubejs-databricks-jdbc-driver): set readonly mode if no exportBicket options provided**
**Check List**
=> feat(cubejs-databricks-jdbc-driver): read-only mode

docs/pages/product/apis-integrations/queries.mdx
=> fix: queryType for compareDateRange

packages/cubejs-backend-native/Cargo.lock, rust/cubesql/Cargo.lock, rust/cubesql/cubesql/Cargo.toml, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__avg_null_type.snap, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__sum_null_type.snap
**Check List**
This PR allows input type `Null` in aggregate functions `SUM` and `AVG`. The output type is `Null` as well. Related tests are included.
=> feat(cubesql): Support `Null` input type in `SUM` and `AVG` functions

.github/workflows/master.yml, .github/workflows/publish.yml
This PR triggers SQL API test suite run on pushes to master and on releases
=> chore(ci): Trigger sql api test suites run on push to master and on releases

packages/cubejs-backend-native/Cargo.lock, rust/cubesql/Cargo.lock, rust/cubesql/cubesql/Cargo.toml, rust/cubesql/cubesql/src/compile/engine/udf/common.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/utils.rs
**Check List**
I've skimmed through code looking for anything that looked like bit packing for intervals and replaced it with to_parts and make_value from arrow
=> refactor(cubesql): Use arrow interval packing

packages/cubejs-api-gateway/src/sql-server.ts
=> chore(cubesql): add checkSqlAuth extension point

packages/cubejs-backend-native/Cargo.lock
=> chore(cubejs-backend-native): Add leftover from uuid bump

docs/pages/product/workspace.mdx, docs/pages/product/workspace/_meta.js, docs/pages/product/workspace/data-model.mdx, docs/pages/product/workspace/dev-mode.mdx, docs/pages/product/workspace/environments.mdx, rust/cubestore/Cargo.lock
Updated documentation for dev mode and the new Environments page.
=> docs: Dev mode and new environments

docs/pages/product/caching.mdx
**Check List**
Add Databricks to the list of DBs with a default of 2 mins for refresh interval
=> docs: Update refresh key default values

rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__cube_scan_exec.snap, rust/cubesql/cubesql/src/compile/test/mod.rs
**Check List**
Add ability to specify mock responses to `V1LoadRequestQuery` in tests
=> test(cubesql): Implement mock TransportService::load for TestConnectionTransport

rust/cubesql/cubesql/Cargo.toml, rust/cubesql/cubesql/benches/benchmarks.rs, rust/cubesql/cubesql/benches/large_model.rs, rust/cubesql/cubesql/src/compile/test/mod.rs, rust/cubesql/cubesql/src/compile/test/rewrite_engine.rs
**Check List**
This PR adds benchmarks for large data models.
=> chore(cubesql): Add benchmarks for large data models

.github/workflows/rust-cubesql.yml, packages/cubejs-backend-native/src/cross/clrepr_python.rs, packages/cubejs-backend-native/src/cross/py_in_js.rs, packages/cubejs-backend-native/src/python/cube_config.rs
=> chore(cubejs-backend-native): Fix Clippy warnings with python feature and setup CI

rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/members.rs
**Check List**
This PR fixes an issue with aggregates being pushed down to query which already has members, is grouped, and has filters, which could lead to dimensions being dropped, and if filters happen to be over measures, the results could be incorrect. Related test is included.
=> fix(cubesql): Don't push down aggregate to grouped query with filters

packages/cubejs-databricks-jdbc-driver/src/DatabricksDriver.ts
=> chore(databricks-jdbc): do not add extra backticks to table name if backticks already present

packages/cubejs-backend-native/src/node_export.rs
=> fix: allow non-stream mode for sql over http

packages/cubejs-schema-compiler/src/compiler/JoinGraph.js, packages/cubejs-schema-compiler/test/integration/postgres/views-join-order-2.test.ts, packages/cubejs-schema-compiler/test/integration/postgres/views-join-order.test.ts
Fixes #8499
**Check List**
#8499
=> fix: View builds incorrect join graph if join paths partially shared

packages/cubejs-api-gateway/openspec.yml, packages/cubejs-api-gateway/test/index.test.ts, packages/cubejs-api-gateway/test/mocks.ts, packages/cubejs-schema-compiler/test/unit/schema.test.ts, packages/cubejs-schema-compiler/test/unit/utils.ts, packages/cubejs-schema-compiler/test/unit/yaml-schema.test.ts, rust/cubesql/cubeclient/DEVELOPMENT.md, rust/cubesql/cubeclient/src/models/v1_cube_meta.rs, rust/cubesql/cubeclient/src/models/v1_cube_meta_dimension.rs, rust/cubesql/cubeclient/src/models/v1_cube_meta_measure.rs, rust/cubesql/cubeclient/src/models/v1_cube_meta_segment.rs, rust/cubesql/cubesql/benches/large_model.rs, rust/cubesql/cubesql/src/compile/test/mod.rs, rust/cubesql/cubesql/src/transport/ctx.rs
**Check List**
Add new field `description` in OpenAPI schema
=> feat(cubejs-api-gateway): Add description to V1CubeMeta, V1CubeMetaDimension and V1CubeMetaMeasure in OpenAPI

rust/cubestore/Cargo.lock, rust/cubestore/Cargo.toml, rust/cubestore/cubestore/src/config/mod.rs, rust/cubestore/cubestore/src/metastore/mod.rs, rust/cubestore/cubestore/src/metastore/table.rs, rust/cubestore/cubestore/src/queryplanner/info_schema/system_tables.rs, rust/cubestore/cubestore/src/queryplanner/mod.rs, rust/cubestore/cubestore/src/queryplanner/planning.rs, rust/cubestore/cubestore/src/queryplanner/query_executor.rs, rust/cubestore/cubestore/src/queryplanner/test_utils.rs, rust/cubestore/cubestore/src/sql/mod.rs, rust/cubestore/cubestore/src/sql/table_creator.rs, rust/cubestore/cubestore/src/store/compaction.rs, rust/cubestore/cubestore/src/store/mod.rs, rust/cubestore/cubestore/src/streaming/kafka.rs, rust/cubestore/cubestore/src/streaming/kafka_post_processing.rs, rust/cubestore/cubestore/src/streaming/mod.rs, rust/cubestore/cubestore/src/table/parquet.rs
=> Create CubestoreMetadataCacheFactory and TableExtensionService DIServices

docs/pages/product/data-modeling/dynamic/code-reusability-export-and-import.mdx
=> fix import logic and make example easier to understand

packages/cubejs-client-core/index.d.ts
=> chore(client-core): extend client types with custom granularity support

packages/cubejs-duckdb-driver/src/DuckDBQuery.ts
This PR fixes regression with timeStampCast() in DuckDB Query
=> fix(duckdb-driver): fix timeStampCast and dateBin

docs/pages/product/workspace/environments.mdx
Docs for Staging Environments settings page.
=> docs: Staging Environments

packages/cubejs-firebolt-driver/src/FireboltDriver.ts
=> fix(firebolt-driver): use default api endpoint if not provided

rust/cubestore/js-wrapper/src/process.ts
=> feat: Inherit all env variables to Cube Store (auto provisioning)

packages/cubejs-playground/src/QueryBuilderV2/components/TimeListMember.tsx
=> fix(playground): fix not showing granularities for time dimension

packages/cubejs-testing/test/smoke-cubesql.test.ts
=> fix: Error after renaming post aggregate

CONTRIBUTING.md
Doc: update node version in CONTRIBUTING.md/Prerequisites
=> Doc: update node version in CONTRIBUTING.md/`Prerequisites`

packages/cubejs-backend-shared/src/env.ts
=> chore(cubeplanner): Rename CUBEJS_NATIVE_SQL_PLANNER env to CUBEJS_TESSERACT_SQL_PLANNER

docs/theme.config.tsx
=> chore: Update docs extra section

packages/cubejs-server-core/src/core/DevServer.ts
=> fix(cubejs-server-core): driverError overriding

packages/cubejs-server-core/src/core/DevServer.ts
=> Revert "fix(cubejs-server-core): driverError overriding"

docs/pages/product/deployment/cloud/byoc/aws.mdx
=> docs: update the list of AWS BYOC permissions for Cube Cloud

rust/cubesql/cubesql/src/compile/engine/df/wrapper.rs
=> refactor(cubesql): Add explicit check for ungroupedness

packages/cubejs-backend-shared/src/FileRepository.ts
=> fix(FileRepository): create repositoryPath if not exists

packages/cubejs-server-core/src/core/CompilerApi.js
=> fix: patch isVisible when applying member level access policies

packages/cubejs-schema-compiler/test/integration/mssql/mssql-ungrouped.test.ts, packages/cubejs-schema-compiler/test/integration/postgres/sql-generation.test.ts
**Check List**
`sqlstring` uses different question mark sequences for different placehloders: ? for value, ?? for identifier, and skips replacing for ???
=> test(schema-compiler): Fix question mark tests

packages/cubejs-backend-shared/src/env.ts
=> fix(schema-compiler): set missed CUBESQL_SQL_PUSH_DOWN to true by default in convertTzForRawTimeDimension flag

docs/pages/guides/dbt.mdx
=> fix incorrect usage of dbt_cube model property

docs/pages/guides/recipes/query-acceleration/disabling-pre-aggregations.mdx
=> fix incorrect handling of env variable data type

packages/cubejs-api-gateway/src/gateway.ts
**Check List**
An alternative authorization header is required if the Authorization header is already in use.
=> feat(api-gateway): Alternative auth headers

rust/cubestore/cubestore-sql-tests/src/tests.rs, rust/cubestore/cubestore/src/queryplanner/mod.rs, rust/cubestore/cubestore/src/queryplanner/projection_above_limit.rs
=> feat(cubestore): ProjectionAboveLimit query optimization

rust/cubestore/Cargo.lock, rust/cubestore/cubestore/Cargo.toml
=> chore(cubestore): Downgrade rdkafka version to 0.29.0

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js, packages/cubejs-testing/birdbox-fixtures/postgresql/schema/Orders.js, packages/cubejs-testing/test/__snapshots__/smoke-cubesql.test.ts.snap, packages/cubejs-testing/test/smoke-cubesql.test.ts
This PR fixes incorrect inner joined cube dimensions/measures referenced from the view SQL generation.
**Check List**
=> fix(schema-compiler): Fix incorrect sql generation for view queries referencing measures from joined cubes

packages/cubejs-databricks-jdbc-driver/src/DatabricksQuery.ts
=> feat(databricks-driver): Support for intervals and CURRENTDATE for sql push down

packages/cubejs-server-core/src/core/CompilerApi.js
fixes https://github.com/cube-js/cube/issues/9005
=> fix(server-core): fix improper requestId retrieval in DAP

docs/pages/product/caching.mdx
Rewording caching types, especially clarifying in-memory cache
**Check List**
=> docs: Update caching.mdx

docs/pages/reference/data-model/pre-aggregations.mdx
Mention that you can use CRON to trigger a pre-agg at a specific time, and put that info next to the exisitng link to the refresh_key reference docs.
**Check List**
=> docs: Update pre-aggregations.mdx

packages/cubejs-api-gateway/src/sql-server.ts
=> fix(api-gateway): allow switch sql user when the new user is the same

packages/cubejs-duckdb-driver/package.json, yarn.lock
**Check List**
Superceeds https://github.com/cube-js/cube/pull/8795
Upgraded DuckDB dependency in _cubejs-duckdb-driver_ to 1.1.3
=> Upgrade to DuckDB 1.1.3

docs/pages/reference/data-model/pre-aggregations.mdx
=> docs: clarify usage of cron + sql in refresh_key

rust/cubesql/cubesql/src/compile/test/mod.rs
=> test(cubesql): Add forgotten data source for MultiTypeCube

docs/pages/product/configuration/data-sources/snowflake.mdx, packages/cubejs-backend-shared/src/env.ts, packages/cubejs-snowflake-driver/src/SnowflakeDriver.ts
This PR supersedes the #8899 by @mike-taylor-nomihealth.
**Check List**
Closes #7440, [#8765](https://github.com/cube-js/cube/pull/8665), #8899
=> feat(snowflake-driver): Add ignore case statements flag

packages/cubejs-server-core/src/core/optionsValidate.ts, packages/cubejs-server-core/src/core/server.ts, packages/cubejs-server-core/src/core/types.ts
=> feat(cubejs-server-core): add contextToCubeStoreRouterId config option

packages/cubejs-backend-native/python/cube/src/__init__.py, packages/cubejs-backend-native/src/python/cube_config.rs
=> fix(cubejs-backend-native): support context_to_cube_store_router_id

packages/cubejs-jdbc-driver/package.json
=> chore(jdbc-driver): Align dev dependencies with monorepo

packages/cubejs-schema-compiler/src/compiler/CubeEvaluator.ts, packages/cubejs-schema-compiler/test/unit/hierarchies.test.ts
=> fix(schema-compiler): hierarchies to respect prefix value

rust/cubestore/Cargo.lock, rust/cubestore/cubestore/Cargo.toml
Added a comment just to trigger a rebuild
**Check List**
=> chore: rebuild cubestore with an updated rust-s3 fork

packages/cubejs-api-gateway/src/gateway.ts
=> fix(api-gateway): data scope check

packages/cubejs-backend-shared/src/env.ts, packages/cubejs-server-core/src/core/CompilerApi.js, packages/cubejs-server-core/src/core/server.ts
=> feat(server-core): add fastReloadEnabled option to CompilerApi

packages/cubejs-backend-native/src/node_export.rs, rust/cubesql/cubesql/src/compile/plan.rs
=> fix(cubejs-native): sql over http drop sessions, correct error

docs/pages/product/apis-integrations/ai-api/reference.mdx
Example did not have `views` key in the proper place for AI API request
=> fix(docs): fixes bad views usage in example

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-backend-native/src/node_export.rs
=> chore: log cubesql queries

rust/cubestore/package.json
=> chore(deps): update missed dependencies

docs/pages/product/deployment/cloud/vpc/aws.mdx, docs/pages/product/deployment/cloud/vpc/gcp.mdx
=> docs: update pre-platform VPC peering docs

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js, packages/cubejs-schema-compiler/test/integration/postgres/member-expression.test.ts, packages/cubejs-schema-compiler/test/integration/postgres/sql-generation.test.ts, rust/cubesqlplanner/cubesqlplanner/src/cube_bridge/base_query_options.rs, rust/cubesqlplanner/cubesqlplanner/src/cube_bridge/evaluator.rs, rust/cubesqlplanner/cubesqlplanner/src/cube_bridge/mod.rs, rust/cubesqlplanner/cubesqlplanner/src/cube_bridge/options_member.rs, rust/cubesqlplanner/cubesqlplanner/src/cube_bridge/segment_definition.rs, rust/cubesqlplanner/cubesqlplanner/src/plan/filter.rs, rust/cubesqlplanner/cubesqlplanner/src/planner/filter/base_segment.rs, rust/cubesqlplanner/cubesqlplanner/src/planner/filter/mod.rs, rust/cubesqlplanner/cubesqlplanner/src/planner/planners/dimension_subquery_planner.rs, rust/cubesqlplanner/cubesqlplanner/src/planner/planners/multi_stage/applied_state.rs, rust/cubesqlplanner/cubesqlplanner/src/planner/planners/multi_stage/member_query_planner.rs, rust/cubesqlplanner/cubesqlplanner/src/planner/query_properties.rs, rust/cubesqlplanner/cubesqlplanner/src/planner/sql_evaluator/references_builder.rs, rust/cubesqlplanner/cubesqlplanner/src/planner/sql_evaluator/sql_call.rs
=> feat(tesseract): Segments and MemberExpressions segments support

packages/cubejs-backend-shared/src/env.ts, packages/cubejs-backend-shared/src/http-utils.ts, packages/cubejs-backend-shared/test/db_env_multi.test.ts, packages/cubejs-backend-shared/test/db_env_single.test.ts, packages/cubejs-databricks-jdbc-driver/src/DatabricksDriver.ts, packages/cubejs-databricks-jdbc-driver/src/helpers.ts, packages/cubejs-databricks-jdbc-driver/src/installer.ts, packages/cubejs-databricks-jdbc-driver/src/post-install.ts
This reverts commit 29fdd615f7eb70690f5fc85897e0c93a5a0cc29a.
=> Revert(databricks-jdbc-driver): Switch to the latest OSS Databricks JDBC driver

docs/pages/product/apis-integrations/ai-api.mdx
=> docs: adds AI API databricks integration

packages/cubejs-schema-compiler/src/compiler/YamlCompiler.ts, packages/cubejs-schema-compiler/test/unit/yaml-schema.test.ts
=> fix(schema-compiler): Fix incorrect transpilation of yaml models

.github/workflows/drivers-tests.yml
=> ci: Remove unused matrix dimension in drivers tests

packages/cubejs-schema-compiler/src/compiler/CubeSymbols.ts, packages/cubejs-schema-compiler/test/unit/__snapshots__/schema.test.ts.snap, packages/cubejs-schema-compiler/test/unit/base-query.test.ts, packages/cubejs-schema-compiler/test/unit/schema.test.ts, packages/cubejs-schema-compiler/test/unit/utils.ts
Fixes timeshift measure inheritance within views.
**Check List**
=> fix(schema-compiler): Fix not working timeshift in views

packages/cubejs-client-react/package.json, packages/cubejs-client-vue/package.json, packages/cubejs-client-vue3/package.json, packages/cubejs-client-ws-transport/package.json, packages/cubejs-playground/package.json, packages/cubejs-testing-drivers/package.json, packages/cubejs-testing/package.json, yarn.lock
- **dedup ajv**
- **chore(deps): fix versions**
=> chore(deps): Fix package versions

docs/pages/product/configuration/data-sources/snowflake.mdx
=> Update Snowflake docs with permissions

packages/cubejs-backend-native/Cargo.lock, rust/cubenativeutils/Cargo.lock, rust/cubesql/Cargo.lock, rust/cubesql/cubesql/Cargo.toml, rust/cubesqlplanner/Cargo.lock
**Check List**
This PR bumps cube-js/arrow-datafusion@ecd17b3, fixing the `Tracker memory shrink underflow` error overwriting the other errors.
=> fix(cubesql): Fix "Tracker memory shrink underflow" error

rust/cubesqlplanner/cubesqlplanner/src/planner/planners/multi_stage/multi_stage_query_planner.rs
=> fix(tesseract): Removed unnecessary pushdown of measure filters in multistage queries

rust/cubesqlplanner/cubesqlplanner/src/planner/time_dimension/sql_interval.rs
=> fix(tesseract): Fix typo in interval

docs/pages/product/deployment/cloud/vpc/aws/private-link.mdx
=> fix(docs): fix typo in Cube principal name in AWS docs

rust/cubestore/Cargo.lock
Pointer update PR for https://github.com/cube-js/arrow-rs/pull/46
**Check List**
=> chore(cubestore): Tolerate thrift fields used by future Cubestores in Parquet format

examples/README.md
=> chore: fix error repository name

packages/cubejs-api-gateway/openspec.yml, rust/cubesql/cubeclient/src/models/v1_cube_meta_dimension_granularity.rs
=> fix(cubesql): Fix cube rust client schema for custom granularities with sql

rust/cubesqlplanner/cubesqlplanner/src/plan/join.rs
=> fix(tesseract): Fix join condition for toDate Rolling Window

packages/cubejs-backend-native/Cargo.lock, rust/cubenativeutils/Cargo.lock, rust/cubesql/Cargo.lock, rust/cubesql/cubesql/Cargo.toml, rust/cubesql/cubesql/src/compile/test/snapshots/cubesql__compile__test__test_df_execution__date_part_interval.snap, rust/cubesql/cubesql/src/compile/test/test_df_execution.rs, rust/cubesqlplanner/Cargo.lock
**Check List**
This PR bumps cube-js/arrow-datafusion@96c5f17, adding support for extracting from intervals with `DATE_PART`/`EXTRACT`. Related test is included.
=> feat(cubesql): Support `DATE_PART` with intervals

packages/cubejs-ksql-driver/src/KsqlQuery.ts, packages/cubejs-schema-compiler/src/adapter/BaseQuery.js, packages/cubejs-schema-compiler/src/adapter/PreAggregations.ts
=> fix(schema-compiler): Fix pre-agg partitions creation for Ksql

yarn.lock
- **dedup @jridgewell/sourcemap-codec**
- **dedup fast-glob**
- **dedup globby**
- **dedup jsonc-parser**
- **dedup source-map**
- **dedup minipass**
- **dedup esquery**
- **dedup raw-body**
- **dedup rfdc**
- **dedup stylehacks**
- **dedup safe-regex-test**
- **dedup less**
- **dedup pg-pool**
- **dedup launch-editor**
- **dedup nth-check**
- **dedup postcss-***
- **dedup parse5**
- **dedup escalade**
- **dedup cssnano**
- **dedup detect-libc**
- **dedup eslint-visitor-keys**
- **dedup cssnano-preset-default**
- **dedup is-regex**
- **dedup mini-css-extract-plugin**
- **dedup import-local**
- **dedup define-properties**
- **dedup bonjour-service**
- **dedup decimal.js**
- **dedup css-declaration-sorter**
- **dedup @vue/compiler-sfc**
- **dedup enquirer**
- **dedup ipaddr.js**
- **dedup …
=> chore(packages): Update/dedup packages

packages/cubejs-schema-compiler/test/integration/postgres/calendars.test.ts, rust/cubeorchestrator/src/transport.rs, rust/cubesqlplanner/cubesqlplanner/src/physical_plan_builder/builder.rs, rust/cubesqlplanner/cubesqlplanner/src/planner/sql_evaluator/symbols/dimension_symbol.rs
=> fix(tesseract): Fix infine loops during calendar time dimension processing

packages/cubejs-schema-compiler/src/adapter/BigqueryQuery.ts
=> fix(schema-compiler): Fix BigQuery convertTz implementation

docs/redirects.json
=> fix(docs): fix AWS deployment doc redirect

docs/pages/product/deployment/cloud/vpc/azure/_meta.js, docs/pages/product/deployment/cloud/vpc/azure/private-link.mdx, docs/pages/product/deployment/cloud/vpc/azure/vpc-peering.mdx, docs/redirects.json
=> docs: Azure PrivateLink doc

packages/cubejs-server-core/src/core/CompilerApi.js
=> fix(server-core): Fix getCompilersInstances to not return compiler promise

docs/pages/product/data-modeling/reference/pre-aggregations.mdx
Correctly targets the date column
**Check List**
=> fix index date column example on yaml

packages/cubejs-snowflake-driver/package.json, yarn.lock
=> feat(snowflake-driver): Upgrade Snowflake Node.js driver to 2.2.0

docs/pages/product/configuration/data-sources/aws-athena.mdx, packages/cubejs-athena-driver/package.json, packages/cubejs-athena-driver/src/AthenaDriver.ts, packages/cubejs-backend-shared/src/env.ts, yarn.lock
=> feat(athena-driver): export env variables for IAM assume role auth

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js, packages/cubejs-schema-compiler/test/unit/base-query.test.ts
=> fix(schema-compiler): Fix incorrect backAlias members collection for FILTER_PARAMS members

rust/cubesql/cubesql/src/compile/query_engine.rs
**Check List**
This PR adds `planningId` param to SQL API planning events.
=> feat(cubesql): Add "planningId" param to SQL API planning events

packages/cubejs-server-core/src/core/CompilerApi.js
The test for this will be added in https://github.com/cube-js/cube/pull/9951
**Check List**
=> fix(schema-compiler): Fix memberToDataSource processing for views without cubes

packages/cubejs-prestodb-driver/docker-compose.yml
=> chore(cube): fix presto integration test

docs/pages/product/deployment/cloud/byoc/aws/deployment.mdx
=> docs: Update AWS BYOC IAM role
