packages/cubejs-client-core/src/ResultSet.js
Add parentheses to the condition. Without parentheses, it will always create new pivotConfig when timeDimension is present. It makes impossible to pass custom configuration to `pivot()` and `chartPivot()`.
=> ResultSet.normalizePivotConfig() fix

README.md, packages/cubejs-cli/cubejsCli.js, packages/cubejs-cli/templates.js
A few changes for Athena support:
* Documenting Athena support, discussing the environment variables specific to the Athena integration.
* In the `cubejs-cli` package, changing how the `.env` file gets written when the user specifies an Athena DB. 
* Adding Athena to the CLI help docs for the `-d` option.
Some other, small changes to the README:
* Adding note about running a Redis server prior to spinning up the app, and about the associated `REDIS_URL` variable.
* Small changes to word choice in some sections.
I also had a few questions about the process for submitting PRs:
* Do y'all use a testing framework, e.g. Jest? I'd love to add tests for the way I'm conditionally writing the `.env` variables and wanted to ask if you have any framework / test structure I should abide by.
* Should …
=> Athena: additions to docs, conditionally generating Athena-specific environment variables, adding to CLI help text

packages/cubejs-cli/README.md, packages/cubejs-cli/package.json, packages/cubejs-cli/templates.js, packages/cubejs-cli/templates.test.js
* Adding Jest tests for the cubejs-cli changes to the way we generate dot env vars
* Removing extraneous newline on `sharedDotEnvVars` in `templates.js`, exporting `dotEnv` in `module.exports` (new export)
* Adding husky pre-commit hook for `npm test`
=> Dot env tests

docs/Cube.js-Backend/@cubejs-backend-server-core.md, packages/cubejs-api-gateway/index.js, packages/cubejs-server-core/core/index.js
Now it's possible to customize your route like
- `http://localhost:8080/cubejs-api/v1/load?query=...` (default)
- `http://localhost:8080/my-custom-route/v1/load?query=...`
I'm still not fully satisfied with the versioning. In my opinion the endpoint should be like this `http://localhost:8080/my-custom-route/v1/cubejs/load?query=...` where `cubejs` should also be customizable.
But this format is not possible at the moment 🤔 How could we solve this?
=> Make API path namespace configurable

packages/cubejs-react/src/QueryRenderer.jsx
No need to pass redundant blank query to QueryBuilder.
Also, mark cubejsApi prop as required.
=> fix: client-react - query prop now has default blank value

packages/cubejs-schema-compiler/package.json
resolve #47
Fix dependency warning in schema compiler .
Current ```joi@10.6``` version is deprecated so upgrade to latest ```joi@14.3.1``` .
=> In cubejs-schema-compiler joi@10.6.0 upgrade to joi@14.3.1

packages/cubejs-server-core/core/index.js
As discussed on slack, this simple change should be enough to enable the support for redshift in the community edition.
https://cube-js.slack.com/archives/CC0403RRR/p1554375237033600?thread_ts=1554352183.032800&cid=CC0403RRR
Please review :)
=> Add redshift to postgres driver link

packages/cubejs-api-gateway/index.js
resolve #39
Query validation added in Api-gateway.
=> feat:query validation added in api-gateway

docs/Cube.js-Backend/Deployment.md
Added instructions to add redis to docker-compose and run the cube js app next to redis, assuming postgres is hosted somewhere else.
=> Add instructions for Docker-compose Deployment

packages/cubejs-api-gateway/index.js
Member key is more correct name for existing dimension key, since member
in filter could be either dimension or member.
Keep support for dimension key for backwards compatibility.
=> feat(api-gateway): Support member key in filters in query

packages/cubejs-query-orchestrator/orchestrator/RedisCacheDriver.js, packages/cubejs-query-orchestrator/orchestrator/RedisFactory.js, packages/cubejs-query-orchestrator/orchestrator/RedisQueueDriver.js, packages/cubejs-query-orchestrator/package.json, packages/cubejs-query-orchestrator/yarn.lock
Created a simple `RedisFactory` which return a single function `createRedisClient`.
`createRedisClient` takes care of promisifying redis methods.
Was not able to promisify `redis.multi().exec()` without accessing the prototype tho.
I tried to replace `exec` method on `redis.Multi.prototype` and I could not figure out why it was not working. So instead a new `execAsync` method was created
Removed dependency `util-promisifyAll`.
Fixes #84
=> fix(query-orchestrator): add RedisFactory and promisify methods manually

docs/Cube.js-Frontend/@cubejs-client-vue.md, examples/vue-dashboard/frontend/package.json
docs: correct typos of the word "measures"
=> fix: add the missing @cubejs-client/vue package

packages/cubejs-clickhouse-driver/driver/ClickHouseDriver.js, packages/cubejs-clickhouse-driver/test/ClickHouseDriverTest.js, packages/cubejs-schema-compiler/adapter/ClickHouseQuery.js, packages/cubejs-schema-compiler/adapter/QueryBuilder.js, packages/cubejs-schema-compiler/docker-compose.yml, packages/cubejs-schema-compiler/package.json, packages/cubejs-schema-compiler/test/ClickHouseDataSchemaCompilerTest.js, packages/cubejs-schema-compiler/test/ClickHouseDbRunner.js, packages/cubejs-schema-compiler/test/ClickHouseGraphBuilderTest.js, packages/cubejs-schema-compiler/test/TestUtil.js, packages/cubejs-schema-compiler/yarn.lock
Implementation of a `ClickHouseQuery` class
In:
`packages/cubejs-schema-compiler/test/DataSchemaCompilerTest.js`
`packages/cubejs-schema-compiler/test/GraphBuilderTest.js` :
I made some slight mods with the aim to make the DbRunner based tests plugable.  However I ended up cloning these two tests for ClickHouse as there were some other changes required. 
- to make it easier to read the geneated sql strings
- to not render all the debug logging by default but require you to set env.DEBUG_LOG=true
- to make DbRunner to construct the Query class and provide the adapter name
I added a docker-compose.yml to provide a local instance of postgres and clickhouse to run the graph builder and schema compiler tests.   This required changing DbRunner to specify a user and pass as I couldn't get it …
=> clickhouse dialect implementation

docs/Schema/Getting-Started-with-Cube.js-Schema.md, docs/Schema/cohort-retention.md, docs/Schema/dimensions.md, docs/Schema/event-analytics.md, docs/Schema/measures.md, docs/Schema/types-and-formats.md
There is some inconsistency in the docs where at certain places the old `${TABLE}` reference is used, whereas at other places the current `${CUBE}` reference is used
=> Replacing ${TABLE} instances to ${CUBE}

packages/cubejs-schema-compiler/adapter/BaseQuery.js, packages/cubejs-schema-compiler/adapter/PostgresQuery.js
> force escape cubeAlias to work with restricted column names such as "case" in the column name
=> force escape cubeAlias to work with restricted column names

docs/Cube.js-Backend/Caching.md
Prompted by https://github.com/statsbotco/cube.js/issues/132
While I was writing this too, it seems like understanding all of this to get the real time use case is asking users to do a fair amount of digging. That suggests it might be good to expose an option like `skipCaching: true` or `forceQuery: true` or something like that that just ensures the query is re-run every time. I also think that if developers know that their underlying data is rapidly changing (like in the real time use case), executing the `refreshKey` query is actually not very useful, because it will always return something different, so being able to control that with the same option would be useful.
=> Extend the documentation about the refreshKey property and getting real time responsiveness to work

packages/cubejs-mongobi-driver/driver/MongoBIDriver.js
When using multi database dynamic configuration, `authSwitchHandler` causing authentication failure
=> pass configured password to authSwitchHandler on MongoBIDriver

packages/cubejs-mongobi-driver/driver/MongoBIDriver.js
Didn't cover the case where config object was undefined, so my bad
=> change config init

packages/cubejs-bigquery-driver/package.json
To fix bug with empty bigquery results in google cloud serverless mode (issue: https://github.com/cube-js/cube.js/issues/153)
=> Up bigquery client version

packages/cubejs-schema-compiler/adapter/MysqlQuery.js
Unfortunately, MySQL uses CONCAT() for string concat instead of the more common '||'.  This fixes that in cube.js.
=> Fix string concat for MySQL

docs/Cube.js-Frontend/@cubejs-client-vue.md, package.json, packages/cubejs-vue/jest.config.js, packages/cubejs-vue/package.json, packages/cubejs-vue/src/QueryBuilder.js, packages/cubejs-vue/src/QueryRenderer.js, packages/cubejs-vue/src/index.js, packages/cubejs-vue/tests/unit/.eslintrc.js, packages/cubejs-vue/tests/unit/QueryBuilder.spec.js, packages/cubejs-vue/tests/unit/QueryRenderer.spec.js, packages/cubejs-vue/tests/unit/__mocks__/responses.js, packages/cubejs-vue/yarn.lock, rollup.config.js
Since Vue slots are useful to show different parts and states I'm leveraging on a better solution to how queries are loaded. Also covered some areas with unit testing
=> feat: Lean more on vue slots for state

docs/Schema/joins.md
Obviously you can not use number type on TEXT strings.
=> Typo in joins.md

packages/cubejs-postgres-driver/driver/PostgresDriver.js
**Check List**
#200
PostgresDriver not has it's own method uploadTable, which uploads all data using [single query](https://github.com/brianc/node-postgres/issues/957#issuecomment-295583050), which makes uploading process faster.
=> Speedup PG pre aggregations

docs/Cube.js-Frontend/@cubejs-client-vue.md, packages/cubejs-vue/src/QueryBuilder.js, packages/cubejs-vue/tests/unit/QueryBuilder.spec.js
**Check List**
Fixes #32 (only for vue)
Fixes #188 
Adds some missing features to the vue package to bring it more in line with the documentation:
- Added support for measures in filters
- Added support for limit
- Added support for offset
I will add the remaining features in another PR as I didn't want this one to get too big
=> Added missing features to vue package

packages/cubejs-query-orchestrator/orchestrator/LocalQueueDriver.js
**Check List**
I am not familiar with the internals of cube, however I am experiencing a problem where `continueWaitTimeout` is not being honored and upon inspecting the code it seems that the option is only used as a fallback to an argument that is never undefined.
Furthermore it seems thar a pair of parentheses is missing (?) otherwise it will wait for 5ms instead of 5s.
I might be missing something as I am really not familiar with the code, please review.
Thank you.
=> Fix continueWaitTimout is ignored

docs/Cube.js-Frontend/@cubejs-client-vue.md, packages/cubejs-vue/src/QueryBuilder.js, packages/cubejs-vue/tests/unit/QueryBuilder.spec.js
**Check List**
None, just an enhancement and brings the vue component more inline with the plain js version.
- Updated vue QueryBuilder component to enable reactivity on the query prop
- Added ordering support to QB
- Added renewQuery support to QB
- Fixed some spelling/grammar problems in the vue docs.
=> Feature: Add order, renewQuery, and reactivity to Vue component

packages/cubejs-vue/src/QueryBuilder.js, packages/cubejs-vue/tests/unit/QueryBuilder.spec.js
**Check List**
No referred issue
When order is empty `QueryBuilder` object passes it to the `QueryRenderer` as an empty object but `@cubejs-server/core` does not allow it so we get a error
=> feat: solve empty order query format

docs/Cube.js-Backend/Deployment.md, packages/cubejs-query-orchestrator/orchestrator/RedisFactory.js
**Check List**
As my Redis instance has password, I did add configuration for Redis here to support password.
=> support REDIS_PASSWORD env variable

docs/Schema/pre-aggregations.md
Update doc since we have already support pre-aggregation on time hierarchy.
I also think maybe we should consider the time priority when searching for matchable pre-aggregations.
e.g. If there exists both a pre-aggregation on `month` and a pre-aggregation on `day`,  query on `month` should be matched to the pre-aggregation on `month` firstly.
=> docs: Update pre-aggregations on time hierarchy

docs/Cube.js-Backend/@cubejs-backend-server-core.md, packages/cubejs-api-gateway/index.js, packages/cubejs-server-core/core/index.d.ts, packages/cubejs-server-core/core/index.js, packages/cubejs-server-core/package.json, packages/cubejs-server-core/yarn.lock
**Check List**
Exposes option to customize the `RequestContext` and pass it to the `CompilerApi` and `FileRepository` per request.
Adds `lru-cache` to `CompilerApi` for managing many schemas per tenant.  Exposes options to optimize the cache size, and automatically prune the cache for expired items.
**Business Justification**
If schemas need to change based on grant permissions for row and column level security, the number of variations become a memory limitation.  A LRU Cache allows the most frequently used schemas to stay in memory until they are no longer needed, or a defined amount of time passes and grants should be checked again.
Exposing the creation of the context lets you send additional information to your cube server for use in dynamically …
=> feat: hooks for dynamic schemas

packages/cubejs-api-gateway/CubejsHandlerError.js, packages/cubejs-api-gateway/HttpError.js, packages/cubejs-api-gateway/UserError.js, packages/cubejs-api-gateway/index.js
Simple type that can be thrown to return status codes other than 200, 400, or 500.
Specifically useful for communicating with another server within `repositoryFactory` and propagating a 401 for unauthorized access to a schema.
=> feat: type for returning specific http status codes

packages/cubejs-sqlite-driver/driver/SqliteDriver.js
1- .match on line 52 returned null => fixed by removing the EOL character
2- The describe table returns the name of the field between square brackets => fixed by removing the square brackets (see https://www.sqlitetutorial.net/sqlite-tutorial/sqlite-describe-table/)
**Check List**
(self contained, did not create an issue beforehand)
=> fix(SqliteDriver.js): Fixed table schema parsing

docs/Cube.js-Backend/@cubejs-backend-server-core.md, packages/cubejs-api-gateway/SubscriptionServer.js, packages/cubejs-api-gateway/index.js, packages/cubejs-server-core/core/index.d.ts, packages/cubejs-server-core/core/index.js
Proposal for #295 and #296 questions.
Ability to extend context object per request (http or web socket).  Essentially, divide responsibilities of `authInfo` and `context`.  This supports two approaches living side-by-side.
1. Current approach, where every component of the request is considered an authenticated security context. "I certify that this user is id 4 and has a mole on his left cheek."
2. Extended approach where authenticated request identifies a user, and additional request information can be added for customization a developer might need. "I certify that this user is id 4.  Btw, he says he has a mole on his left cheek, if that matters to you."
`requestId` now lives within the `context`, can be accessed for requests made external to cubejs, and can be overridden if not using …
=> feat: Extendable context

packages/cubejs-server-core/core/CompilerApi.js, packages/cubejs-server-core/core/index.js
Fix for #294 
If you override `schemaVersion(context)`, `context` is not the current request's context. This is because the `schemaVersion()` called in `CompilerApi` is a closure.  By adding the `schemaVersion` to the key for the `compilerCache`, `CompilerApi` will effectively recompile with new schemaVersions.
Note: If the server has not specified a `maxCompilerCacheKeepAlive`, the old compilers will remain in memory until `compilerCacheSize` is reached. At that point, the LRU cache will start evicting the old schemas.
Note for `OrchestratorApi`: Current workaround for incorrect context in schemaVersion is to tack the schemaVersion into your `contextToAppId`.  This introduces many `OrchestratorApi`s when there should be far fewer.  Passing the correct `context` to …
=> fix: schemaVersion called with old context

packages/cubejs-server-core/core/OrchestratorApi.js, packages/cubejs-server-core/core/index.js, packages/cubejs-server/index.js, packages/cubejs-server/index.test.js
#302 
These are methods that can be used for checking health.  I did not explicitly add an endpoint because the format of returning health checks varies slightly.  These are methods that can be called with a custom implementation or using another package, e.g. terminus or lightship.
=> feat: Health check methods

packages/cubejs-bigquery-driver/driver/index.d.ts, packages/cubejs-postgres-driver/driver/index.d.ts, packages/cubejs-postgres-driver/package.json, packages/cubejs-server-core/core/index.d.ts, packages/cubejs-sqlite-driver/driver/index.d.ts
Fix my previous PR #369.
It introduced an issue in module augmentation exports and miss a `@types/pg` devDependency to properly work when installing from scratch.
I'm sorry for that.
=> fix: typings export

packages/cubejs-client-core/dist/index.d.ts
**Check List**
Loosen the types enough so that common issues go away. Long term, it might be better to replace the default generic type for `ResultSet` from `any` to `unknown`.
=> fix(@cubejs-client/core): improve types

packages/cubejs-schema-compiler/adapter/BaseQuery.js, packages/cubejs-schema-compiler/adapter/BigqueryQuery.js
Fix BigQuery error:
```
Dropping Cache: {
"cacheKey": [
"SELECT CASE\n    WHEN CURRENT_TIMESTAMP() < DATETIME_ADD(TIMESTAMP(?), INTERVAL 7 day) THEN FLOOR(UNIX_SECONDS(CURRENT_TIMESTAMP()) / 86400) END",
[
"2020-01-12T23:59:59Z"
]
]
} 
Error: No matching signature for function DATETIME_ADD for argument types: TIMESTAMP, INTERVAL INT64 DATE_TIME_PART. Supported signature: DATETIME_ADD(DATETIME, INTERVAL INT64 DATE_TIME_PART) at [2:32]
```
=> fix: Wrong interval functions for BigQuery

package.json, packages/cubejs-client-core/package.json, packages/cubejs-client-core/yarn.lock, packages/cubejs-client-react/package.json, packages/cubejs-client-react/yarn.lock, packages/cubejs-client-vue/package.json, packages/cubejs-client-vue/yarn.lock, packages/cubejs-client-ws-transport/package.json, packages/cubejs-client-ws-transport/yarn.lock, yarn.lock
**Check List**
Try bumping corejs so we dont get the deprecation warning during install
=> Bump corejs

docs/Schema/pre-aggregations.md, packages/cubejs-postgres-driver/driver/PostgresDriver.js, packages/cubejs-query-orchestrator/driver/BaseDriver.js, packages/cubejs-query-orchestrator/orchestrator/PreAggregations.js, packages/cubejs-schema-compiler/adapter/PreAggregations.js
**Check List**
#239 
- Refactors external rollups into three strategies (the third being new):
- Store In Source
- Temp Table External
- Stream External
- Removes ability to cancel temp table creation (not sure if this is actually used or not, can add it back in if needed, it was just getting complicated with the refactor)
- Adds a `readOnly` config to drivers (defaults to `false`) that controls which external strategy is used for rollups
- Adds capability for both row and type data to be returned at query time, called `downloadQueryResults` and implemented so far for Postgres only, as it already had the info it just needed to be surfaced
Example config for specifying a read-only …
=> feat: Support external rollups from readonly source

packages/cubejs-schema-compiler/package.json
**Check List**
[bump version numbers - @hapi/joi@14.5.0, @hapi/hoek@6.2.4 et. al. #411]
(https://github.com/cube-js/cube.js/issues/411)
- Only one version updated so far but so many others are potential.
=> [WIP] Bumping @hapi/joi to ^15.1.1 - Automatic Test Passing - Manual Not tested yet.

packages/cubejs-postgres-driver/driver/PostgresDriver.js
**Check List**
While pre-aggregating data from Aws Athena to postgres, there was an issue because Athena supports "double" whereas postgres does not.
Added a mapping to convert "double" fields to "decimal"
=> cast double to decimal for postgres

packages/cubejs-api-gateway/package.json, packages/cubejs-schema-compiler/package.json
**Check List**
- [n/a] Linter has been run for changed code
- [n/a] Tests for the changes have been added if not covered yet
- [n/a] Docs have been added / updated if required
Continuing of 
https://github.com/cube-js/cube.js/pull/412 and 
https://github.com/cube-js/cube.js/issues/411
Dependencies for cubejs-api-gateway in package.json updated to latest non-breaking version. @hapi/joi": "^15.1.1",
=> build(deps): bump hapi/joi from 14.0.6 to 15.1.1

packages/cubejs-query-orchestrator/orchestrator/LocalQueueDriver.js, packages/cubejs-query-orchestrator/orchestrator/PreAggregations.js, packages/cubejs-query-orchestrator/orchestrator/QueryCache.js, packages/cubejs-query-orchestrator/orchestrator/QueryOrchestrator.js, packages/cubejs-query-orchestrator/orchestrator/QueryQueue.js, packages/cubejs-query-orchestrator/orchestrator/RedisCacheDriver.js, packages/cubejs-query-orchestrator/orchestrator/RedisPool.js, packages/cubejs-query-orchestrator/orchestrator/RedisQueueDriver.js, packages/cubejs-query-orchestrator/package.json, packages/cubejs-query-orchestrator/test/QueryOrchestrator.test.js, packages/cubejs-query-orchestrator/test/QueryQueue.test.js, packages/cubejs-query-orchestrator/test/QueryQueueTest.js, packages/cubejs-query-orchestrator/yarn.lock
**Check List**
Fixes #104 
Adds a connection pool class based on `generic-pool`. By default, uses (min=2, max=10). If max is set to zero (e.g. through the env var), then the pool is disabled and it falls back to prior behavior (non-pooled).
A single instance of the connection pool is created in the `QueryOrchestrator` and is wired up to two final destinations:
- `RedisQueueDriverConnection`
- `RedisCacheDriver`
=> feat: Redis connection pooling

packages/cubejs-query-orchestrator/orchestrator/QueryOrchestrator.js, packages/cubejs-query-orchestrator/test/QueryOrchestrator.test.js
**Check List**
Fixes tests hanging
Was only cleaning up redis pool in one of two test files in Orchestrar, doh. No idea why specs passed on the original branch.
=> fix: Cleanup redis pool properly in tests

packages/cubejs-query-orchestrator/orchestrator/PreAggregations.js, packages/cubejs-query-orchestrator/orchestrator/QueryCache.js, packages/cubejs-query-orchestrator/orchestrator/RedisCacheDriver.js, packages/cubejs-query-orchestrator/orchestrator/RedisPool.js, packages/cubejs-query-orchestrator/test/QueryQueue.test.js
**Check List**
Instead of passing in values directly through the constructor, use the options pattern for easier extensibility.
From a review of https://github.com/cube-js/cube.js/pull/433
=> refactor: Use options pattern in RedisPool constructor

packages/cubejs-server/package.json
**Check List**
The package.json for @cubejs-backend/server specifies a [`"types": "index.d.ts"`](https://github.com/cube-js/cube.js/blob/c2ee5eed8bfdc48de185122e518ba0dc6b83abc7/packages/cubejs-server/package.json#L6), but because index.d.ts is not published to npm, these types are unavailable to third parties using the package.  This fixes it so the types get published correctly.
=> fix: Publish index.d.ts for @cubejs-backend/server.

packages/cubejs-server/index.d.ts
**Check List**
So... when I did [this](https://github.com/cube-js/cube.js/pull/518) I didn't realize there were some problems in the index.d.ts file.  :P
* index.d.ts imports a `CreateOptions` from server-core, but also defined a new conflicting CreateOptions.
* index.d.ts has an `export =`, which is forbidden because it also has an `export interface CreateOptions`, and you can't use`export =` if you have other exports in the same module.
This fixes both of these problems.
=> fix(types): Fix index.d.ts errors in cubejs-server.

packages/cubejs-postgres-driver/driver/PostgresDriver.js
**Check List**
- [ X ] Tests has been run in packages where changes made if available
- [ X] Linter has been run for changed code
#527 
use environment variable `CUBEJS_DB_MAX_POOL`in PostgresDriver
=> feat(postgres-driver): `CUBEJS_DB_MAX_POOL` env variable

packages/cubejs-postgres-driver/driver/PostgresDriver.js
**Check List**
When the pg driver is used with ssl set to true (e.g. `CUBEJS_DB_SSL=true`), the following deprecation warning is logged:
```
(node:23) DeprecationWarning: Implicit disabling of certificate verification is deprecated and will be removed in pg 8. Specify `rejectUnauthorized: true` to require a valid CA or `rejectUnauthorized: false` to explicitly opt out of MITM protection.
```
This PR updates how the ssl configuration options for the pg driver are set to address the deprecation.
Reference: 
https://github.com/GSG-G8/Books-store/issues/26
https://github.com/brianc/node-postgres/issues/2089
=> fix(postgres-driver): Clean-up deprecation warning

packages/cubejs-server-core/core/RefreshScheduler.js
**Check List**
Fixes RefreshScheduler on postgres.
There is a second place that might need the same change but I'm not sure so I left it:
https://github.com/cube-js/cube.js/blob/93a1250b74e594e68d261825c8f3b917a41adaf5/packages/cubejs-server-core/core/RefreshScheduler.js#L107
```
2020-04-05T22:02:00.288643+00:00 app[web.1]: {"message":"Refresh Scheduler Error","error":"Error: time zone \"undefined\" not recognized","requestId":"scheduler-37b13d44-1695-4562-b8c4-f2e8ebe580e2"}
2020-04-05T22:02:00.290804+00:00 app[web.1]: {"message":"Dropping Cache","cacheKey":["select max((\"test\".created_at::timestamptz AT TIME ZONE 'undefined')) from public.ba AS \"test\"",[],[]],"error":"Error: time zone \"undefined\" not recognized\n …
```
=> fix: Pass query options such as timezone in RefreshScheduler

packages/cubejs-server-core/core/CompilerApi.js, packages/cubejs-server-core/core/index.js
**Check List**
- [X ] Tests has been run in packages where changes made if available
- [ X] Linter has been run for changed code
Add support for cases where `schemaVersion` needs to be `async`, e.g. fetching the version from remote storage
=> add await when invoking schemaVersion

packages/cubejs-schema-compiler/adapter/PostgresQuery.js
=> pg_approx_hll

docs/Cube.js-Backend/@cubejs-backend-server-core.md, docs/Cube.js-Backend/@cubejs-backend-server.md, docs/Cube.js-Backend/Caching.md, docs/Cube.js-Backend/Deployment.md, docs/Cube.js-Backend/Multitenancy-Setup.md, docs/Cube.js-Backend/Security.md, examples/d3-dashboard/index.js, examples/event-analytics/backend/index.js, examples/external-rollups/README.md, examples/hn-insights/devServer.js, examples/react-dashboard/backend/index.js, examples/real-time-dashboard/index.js, examples/vue-dashboard/backend/index.js, examples/web-analytics/index.js, guides/react-dashboard/content/2_authentication_and_graphql_backend.md, guides/react-dashboard/demo/index.js, guides/real-time-dashboard/content/3_frontend_dashboard.md, guides/real-time-dashboard/content/5_deployment.md, packages/cubejs-cli/templates.js, packages/cubejs-server-core/core/index.js, packages/cubejs-server/bin/dev-server.js, packages/cubejs-server/index.d.ts, packages/cubejs-server/index.js
**Check List**
Includes the Cube.js version in the startup message:
The version is available in three places:
1. `CubejsServer.version()`
1. `CubejsServerCore.version()`
1. `const { version, port } = await cubejsServer.listen();`
=> feat: Include version in startup message

docs/Cube.js-Backend/@cubejs-backend-server-core.md, packages/cubejs-api-gateway/index.d.ts, packages/cubejs-api-gateway/package.json, packages/cubejs-server-core/core/index.d.ts
**Check List**
This PR builds on #369 and moves the Query type to be owned by the package that is responsible for it - `api-gateway`. Query now means the incoming query - nothing is actually using this at this point, although methods like `load` could be declared to use it.
Internally, `api-gateway` "normalizes" the incoming query and adds a few things to the structure - this is represented by the new `NormalizedQuery` and `NormalizedQueryFilter` types. Since it is actually the `NormalizedQuery` that is made available to query transformers, I was running into a problem where TypeScript was complaining about the use of `dimension`, which it thought wasn't available but it actually is - this will now work properly.
=> feat: Update type defs for query transformer

packages/cubejs-postgres-driver/driver/PostgresDriver.js
**Check List**
#651 
executionTimeout (in seconds) can be added to the driver config argument and will be used as statetment_timeout for postgres. config.executionTimeout=0 will, set statemtent_timeout to infinite. if executionTimeout is undefined, the original default value of 10 min will be used.
=> fix:PostgresDriver execution timeout is hardcoded to 10 minutes #651

packages/cubejs-client-core/dist/cubejs-client-core.esm.js, packages/cubejs-client-core/dist/cubejs-client-core.js, packages/cubejs-client-core/dist/cubejs-client-core.umd.js, packages/cubejs-client-react/dist/cubejs-client-react.esm.js, packages/cubejs-client-react/dist/cubejs-client-react.js, packages/cubejs-client-react/dist/cubejs-client-react.umd.js, packages/cubejs-client-react/src/QueryBuilder.jsx
#749
Exposing updateQuery method
=> feat(cubejs-client-react): Exposing updateQuery method

packages/cubejs-client-core/index.d.ts, packages/cubejs-client-core/src/HttpTransport.js, packages/cubejs-client-core/src/index.js
**Check List**
**Note: the build instructions in the contribution guide are not working for me, so I can't build/run/test this change myself. Sorry about that!**
Original request here: https://github.com/cube-js/cube.js/issues/788
The [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) supports a credentials option to control the session cookies sent along with a request. By adjusting the Cube.js Client to support this option, we will be able to route our cube queries through a different sub-domain.
For example. If your site is running at secure.mydomain.com and your API calls need to go to api.mydomain.com it can be handy to pass the cookies over in …
=> Adjust client options to send credentials when needed

docs/Cube.js-Backend/@cubejs-backend-server-core.md, packages/cubejs-query-orchestrator/orchestrator/BaseQueueDriver.js, packages/cubejs-query-orchestrator/orchestrator/PreAggregations.js, packages/cubejs-query-orchestrator/orchestrator/QueryCache.js, packages/cubejs-query-orchestrator/orchestrator/QueryOrchestrator.js, packages/cubejs-query-orchestrator/orchestrator/QueryQueue.js, packages/cubejs-query-orchestrator/test/PreAggregations.test.js, packages/cubejs-server-core/core/index.d.ts
**Check List**
- Adds support for only allowing queries to hit rollups.
- Adds support for running a separate instance of cube.js to refresh rollups and set the api instance of cubejs to a mode where it doesn't try to check for rollups being current and doesn't try to create or refresh them.
=> feat: Rollup mode

docs/Getting-started.md
Angular-related section was missing on the getting started page of the documentation
=> docs: add angular section to the getting started page

packages/cubejs-playground/src/components/CachePane.js, packages/cubejs-query-orchestrator/orchestrator/PreAggregations.js
**Check List**
The combination of `renewQuery` on a query against a server running in `externalRefresh` mode results in a validation error (and correctly so - you can't renew queries against a server running in that mode), but it is breaking the dev playground's Cache tab.
This PR improves the guards for missing data in the Cache section, and also makes a change to allow `renewQuery` to be specified in dev mode, except it will issue a warning and force it back to false.
=> fix: allow renewQuery in dev mode with warning

packages/cubejs-schema-compiler/adapter/MssqlQuery.js
…a OFFSET.' when using limit and offset together in the query for MSSQL.
**Check List**
#891 
Automatically adjust the parameters when limit and offset are both used in the query.
=> fix: using limit and offset together in MSSql

docs/Cube.js-Backend/Query-Format.md, packages/cubejs-api-gateway/index.js, packages/cubejs-api-gateway/index.test.js
**Check List**
[Update query format API to support ordered `order` specification #773]
Compiler API already support `array of object` format, example `[{ id: 'Sessions.count', desc: true }]` and current API-Gateway already transform public format to Compiler API.
I added support `array of tuples` alternative in Api-gateway layer, that also transform to `array of object` format for Compiler API:
- New rule in joi validation schema for order property
- New function `normalizeQueryOrder`
- Updated docs: Cube.js-Backend => Query-Format
=> Resolve 773: Update query format API to support ordered order specification

packages/cubejs-query-orchestrator/orchestrator/PreAggregations.js, packages/cubejs-query-orchestrator/test/PreAggregations.test.js
**Check List**
Currently,  table caching will cause a test query to be made to BOTH the source and the rollup databases. This PR prevents a connection and query from being ran against the source database when caching the tables in the external rollup database. This is particularly important when `externalRefresh` is being used, as in that architecture the cubejs API instance likely isn't configured with the capability to connect to the source database.
The reason this happens is because `QueryCache.createQueue` will always setup a driver instance for the source database:
https://github.com/cube-js/cube.js/blob/c30a44c26e76e83c3d26234850d5c6b0e76cd924/packages/cubejs-query-orchestrator/orchestrator/QueryCache.js#L190
This …
=> fix: avoid querying source database when caching tables from external rollup db

packages/cubejs-schema-compiler/adapter/ClickHouseQuery.js
**Check List**
No issue created.
The order by clause in the pre aggregation sql failes because multiple order by columns need to be supplied in a tuple (surrounded by parentheses).
=> fix: add parentheses to pre aggregation sql for clickhouse 

packages/cubejs-client-react/index.d.ts, packages/cubejs-client-react/src/useCubeQuery.js
**Check List**
**Tests:**
There are no tests for this package at the moment, so I wasn't able to add any for this extension.
**Docs:**
I updated the `index.d.ts` file, but have not updated the other docs/examples. Are they automatically generated somehow or shall I do it manually?
When loading a Cube Query, it might take some due to waiting in the queue or because pre-aggregations are being built.
By exposing the ProgressResponse from the CubeJS API, the UI can share more information with the user when the query is loading.
This allows us to show the following in our UI (big win for our users):
___
I hope you find this to be a useful addition to Cube.JS :)
=> feat(@cubejs-client/react): Expose progress in useCubeQuery hook

packages/cubejs-client-core/index.d.ts
Commit 3396fb changed TimeDimensionGranularities enum to TimeDimensionGranularity type
and removed the export. This reintroduces the export of the type.
**Check List**
No issue created
Commit 3396fb changed TimeDimensionGranularities enum to TimeDimensionGranularity type
and removed the export. This reintroduces the export of the type.
=> Export TimeDimensionGranularity type

packages/cubejs-client-core/index.d.ts
**Check List**
No issue
Adds the `second` and `minute` option to the `TimeDimensionGranularity` type exposed by `cubejs-client-core`. Do note that from trying to find prior issues/PRs regarding this, I found [this](https://github.com/cube-js/cube.js/issues/177#issuecomment-530034036) and [this](https://github.com/cube-js/cube.js/issues/340#issuecomment-571446275) comment from @paveltiunov on semi-related issues, so I wonder if the omission of these strings from this type is intentional. Where I work, we currently use the `second` granularity in a small number of queries, so we want this so that we have full type safety for such queries.
=> Improve TimeDimensionGranularity Type

packages/cubejs-client-core/index.d.ts
Add correct return type to Meta.resolveMember. The previous type of `Object` was incorrect.
**Check List**
No issue
Updated return types for the Meta function resolveMember. This was previously set as `Object`, but it might actually contain an error object or the returned member details. The returned type is controlled by the `memberType` param provided to the function.
=> fix: cube-client-core resolveMember return type

packages/cubejs-schema-compiler/adapter/ElasticSearchQuery.js
ungrouped condition check for groupByClause function in ElasticSearchQuery
ungrouped: true query still groups by the dimension list
```
{
"limit": 5,
"dimensions": [
"sales_data.State",
"sales_data.Region"
],
"ungrouped": true
}
```
This is the input query that I am passing to cube
```
SELECT
sales_data.State sales_data___state, sales_data.Region sales_data___region
FROM
sales_data AS sales_data
GROUP BY sales_data.State, sales_data.Region ORDER BY sales_data.State ASC LIMIT 5
```
Above is the corresponding SQL query formed
```
const cubeCore = CubejsServerCore.create({
devServer: true,
telemetry: false,
schemaPath: "./src/schema/",
dbType: "elasticsearch",
basePath: appPrefixURL,
apiSecret: cubeSecretKey,
allowUngroupedWithoutPrimaryKey: true,
driverFactory: () =>
new …
```
=> ungrouped condition check in ElasticSearchQuery

docs/Cube.js-Backend/@cubejs-backend-server-core.md, packages/cubejs-schema-compiler/compiler/CubeCheckDuplicatePropTranspiler.js, packages/cubejs-schema-compiler/compiler/PrepareCompiler.js, packages/cubejs-schema-compiler/test/DataSchemaCompilerTest.js, packages/cubejs-server-core/core/CompilerApi.js, packages/cubejs-server-core/core/index.js, packages/cubejs-server-core/core/index.test.js, packages/cubejs-server-core/core/optionsValidate.js
**Check List**
Added class CubeCheckDuplicatePropTranspiler and require logic in PrepareCompiler.
Added option allowDuplicateProps - schema-compiler, server-core, docs.
=> feat: strict cube schema parsing, show duplicate property name errors

packages/cubejs-server-core/core/optionsValidate.js
**Check List**
I've got a problem on local after https://github.com/cube-js/cube.js/pull/1089, cC @RusovDmitriy 
```
/Users/ovr/projects/cube/cube.js/packages/cubejs-server-core/core/optionsValidate.js:65
if (error) throw new Error(`Invalid cube-server-core options: ${error.message || error.toString()}`);
^
Error: Invalid cube-server-core options: "webSockets" is not allowed
```
CubejsServer pass `webSockets` options.
=> Fix(@cubejs-backend/server-core): Support webSockets option

packages/cubejs-server-core/core/index.test.js, packages/cubejs-server-core/core/optionsValidate.js
**Check List**
Add initApp option to server-core validation
=> fix(@cubejs-backend/server-core): Allow initApp as server-core option 

packages/cubejs-api-gateway/index.js, packages/cubejs-client-core/src/ResultSet.js, packages/cubejs-client-core/src/tests/drill-down.test.js
#1138
Propagate drill down parent filters to the query, fix query normalization to use only the `member` field for filters.
=> fix: propagate drill down parent filters

.github/workflows/push.yml
Hey!
Example:
https://github.com/cube-js/cube.js/runs/1178482790
5h 55m 19s, infinity job...
Thanks
=> Misc(ci): Guard jobs by timeouts

packages/cubejs-mysql-driver/driver/MySqlDriver.js
Fix: https://github.com/cube-js/cube.js/issues/1117
MySQL driver casting dates to `Date` by default,  see `dateStrings ` parameter
It's `TIMESTAMP, DATETIME, DATE` by default
There are ways how to resolve this issue:
> timezone: The timezone configured on the MySQL server. This is used to type cast server date/time values to JavaScript Date object and vice versa. This can be 'local', 'Z', or an offset in the form +HH:MM or -HH:MM. (Default: 'local')
Not working, lol
https://github.com/cube-js/cube.js/pull/1159
=> Fix(@cubejs-backend/mysql-driver): Correct dates casting, fix #1117

packages/cubejs-schema-compiler/adapter/MssqlQuery.js, packages/cubejs-schema-compiler/test/unit/MssqlQueryTest.js
**Check List**
#997 
The base query adapter uses ordinal values for group by clauses; unfortunately MSSQL does not support such.  When this.groupByClause() is called, it returns the group by clause for the 'inner query', not the current select statement being created.  In base query, or for databases like Postgres which support ordinal group by clauses, this is fine - 1,2 is still 1,2; but in MSSQL which uses the aliases of the columns being grouped, this is an issue.
Changes here implement a MSSQL specific overTimeSeriesSelect function which creates then uses the proper group by clause; also fixes syntax on the seriesSql() function to properly alias the date columns.
=> fix(@cubejs-schema-compilter): MSSQL rollingWindow with granularity

docs-gen/src/resources/helpers/member-symbol.ts, docs/Cube.js-Backend/@cubejs-backend-server-core.md, docs/Cube.js-Backend/Caching.md, docs/Cube.js-Backend/Deployment.md, docs/Cube.js-Backend/REST-API.md, docs/Cube.js-Frontend/Introduction-angular.md, docs/Cube.js-Frontend/Introduction-react.md, docs/Cube.js-Frontend/Introduction-vue.md, docs/Cube.js-Frontend/Introduction.md, docs/Guides/Direction-of-Joins.md, docs/Guides/Incremental-Pre-Aggregations.md, docs/Schema/cube.md, docs/Schema/dimensions.md, docs/Schema/joins.md, docs/Schema/measures.md, docs/Schema/pre-aggregations.md, docs/Schema/schema-execution-environment.md
- support for framework-specific documentation.
- support for custom blocks (like Warnings)
- unification for all signatures.
=> Docs: add framework-specific documentation & custom blocks

packages/cubejs-client-vue/src/QueryRenderer.js
**Check List**
Since data blending was introduced and allows for an array of queries, `QueryRenderer` component complains when passing Array instead of an Object, although it still handles it properly
=> Allow array props on query renderer to allow datablending usage

packages/cubejs-query-orchestrator/driver/BaseDriver.js
**Check List**
N/A
MSSQL has a type of nvarchar - this type is not being mapped in the DbTypeToGenericType object.  Leads to situation where if you have a MSSQL source system readonly, and a target that does not support that data type, it sends along 'nvarchar' and then preaggregation steps fail.  Added nvarchar to the mapping object, treating it like varchar mapped to text.
=> feat(@cubejs-backend/query-orchestrator): add support for MSSQL nvarchar

packages/cubejs-cli/src/command/deploy.ts
On a Windows operating system, the path module will assume that Windows-style paths are being used. 
This PR converts the file path to POSIX style before check upstreamHashes and upload.
=> fix(cubejs-cli): Deploy and Windows-style paths

packages/cubejs-client-react/package.json
Since the release >=0.20 we are getting a warning caused by the latest `@cubejs-client/core` not satisfying the defined peer dependency of `@cubejs-client/react`:
```
@cubejs-client/react@0.23.6" has incorrect peer dependency "@cubejs-client/core@^0.19.43".
```
Additionally using `@cubejs-client/react@0.23.6` with `@cubejs-client/core@^0.19.43` does not seem to work producing the warnings below:
```
WARNING in ../../node_modules/@cubejs-client/react/dist/cubejs-client-react.esm.js 649:28-43
export 'moveItemInArray' (imported as 'moveItemInArray') was not found in '@cubejs-client/core' (possible exports: HttpTransport, ResultSet, __esModule, default)
WARNING in ../../node_modules/@cubejs-client/react/dist/cubejs-client-react.esm.js 736:32-44
export 'defaultOrder' (imported as …
```
=> Bump peer dependency @cubejs-client/core

packages/cubejs-client-react/src/QueryBuilder.jsx
**Check List**
N/A
Added a minute and second to default granularities for QueryBuilder for cubejs-client-react.
Based on https://github.com/cube-js/cube.js/blob/master/docs/Cube.js-Backend/Query-Format.md
```
Supported granularities: second, minute, hour, day, week, month.
```
=> Add minute and second granularities to React QueryBuilder

packages/cubejs-cli/src/templates.ts
=> feat(cubejs-cli): Use index.js file instead of cube.js for serverless template

docs/Cube.js-Backend/Environment-Variables-Reference.md
**Check List**
Fixes `CUBEJS_REDIS_POOL_MAX` and `CUBEJS_REDIS_POOL_MIN` not being rendered as inline code blocks in the description section of the Environment Variables reference documentation.
=> Ensure reference to environment variable is rendered as inline code

packages/cubejs-client-react/src/QueryBuilder.jsx
**Check List**
- [x ] Tests has been run in packages where changes made if available
- [x ] Linter has been run for changed code
- [x ] Docs have been added / updated if required
[#1348 ](https://github.com/cube-js/cube.js/issues/1348)
Allows either "compareDateRange" or "dateRange" to be passed as an update within the QueryBuilder.
=> feat(react): support 'compareDateRange' when updating 'timeDimensions'

packages/cubejs-server-core/core/index.d.ts
The orchestratorOptions configuration field allows for configuration via a function, but the types did not reflect that.
**Check List**
#1421
=> fix: correct type for `orchestratorOptions`

packages/cubejs-server/src/server.ts, packages/cubejs-serverless/Handlers.js
=> feat: Specify CORS for server/serverless

.github/workflows/rust-master.yml, packages/cubejs-cubestore-driver/README.md, packages/cubejs-cubestore-driver/package.json, rust/README.md, rust/cubestore/src/bin/cubestored.rs, rust/cubestore/src/telemetry/mod.rs
Following a recent discussion, I've updated all user-facing `/(cube).*(store)/i` appearances in our code base to be spelled as "Cube Store".
=> cubestore: Update user-facing "Cube Store" mentions to the correct form

packages/cubejs-playground/src/components/GlobalStyles.js
**Check List**
The scrollbar in a menu (dropdown) is not visible without interaction. (MacOS, Setting selected: Show scroll bars: When scrolling)
Apply CSS styles to always show scrollbar if the content is too big to be displayed without scrolling.
=> fix(@cubejs-client/playground): always show scrollbars in menu

docs/content/Configuration/Connecting-to-the-Database.md, docs/content/Configuration/Environment-Variables-Reference.md, packages/cubejs-postgres-driver/driver/PostgresDriver.js
Hello!
It's needed to fix this such of errors:
> Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: localhost. is not cert's CN: example-dev:pg12
When you are using Google SQL with Postgresql driver.
Thanks
=> feat(@cubejs-backend/postgres-driver): Support `CUBEJS_DB_SSL_SERVERNAME`

docs/netlify.toml
**Check List**
This should stop non-documentation PRs from generating Deploy Previews
=> ci: do not create Deploy Previews for non-documentation PRs

docs/src/components/Layout/index.jsx, docs/src/templates/DocTemplate.jsx
It removes `title` attribute in content sections.
Also, I changed `line-height` of the font-size and made minor refactoring to styles with the designer's consent.
=> docs: remove title attribute from content sections

packages/cubejs-backend-shared/package.json, packages/cubejs-backend-shared/src/package.ts, packages/cubejs-backend-shared/test/package.test.ts, packages/cubejs-backend-shared/yarn.lock, packages/cubejs-cli/package.json, packages/cubejs-cli/src/config.ts, packages/cubejs-cli/src/utils.ts, packages/cubejs-cli/yarn.lock, packages/cubejs-cubestore-driver/driver/CubeStoreDriver.js, packages/cubejs-mongobi-driver/driver/MongoBIDriver.js, packages/cubejs-mysql-driver/driver/MySqlDriver.js, packages/cubejs-postgres-driver/driver/PostgresDriver.js, packages/cubejs-query-orchestrator/package.json, packages/cubejs-query-orchestrator/src/driver/BaseDriver.js, packages/cubejs-query-orchestrator/yarn.lock
Hello!
refs https://github.com/cube-js/cube.js/issues/1495
Thanks
=> feat: Improve UX for SSL keys/certs

packages/cubejs-api-gateway/src/index.ts
#1474 hid two classes I was relying on.
=> fix(@cubejs-backend/api-gateway): Add missing exports

packages/cubejs-playground/src/components/Tabs.js
**Check List**
Fixes the bug: The user can't select text inside the warning in tab content.
=> fix(@cubejs-client/playground): fix user select on tab content

DEPRECATION.md
Hello!
We already has a waning for it inside `cubejs-cli`:
Thanks
=> docs(DEPRECATION.md): add Node.js v8 deprecation notice

packages/cubejs-mysql-driver/driver/MySqlDriver.js, packages/cubejs-postgres-driver/driver/PostgresDriver.js
Hello!
refs https://github.com/cube-js/cube.js/issues/1563
Thanks
=> fix: use `decimal(38,10)` for external MySQL and Postgres pre-aggregations

docs/static/styles/_layout.scss
**Check List**
Fixed the following issue:
=> docs(@cubejs-docs/site): fix alignment of heading anchors

docs/.lintstagedrc
**Check List**
The automatically-generated `CHANGELOG.md` was causing lint errors and preventing new releases. The Lint-Staged configuration file has been updated to exclude it.
=> docs(@cubejs-docs/site): exclude `CHANGELOG.md` from linting

packages/cubejs-api-gateway/src/gateway.ts
Hello!
I think it's expected to support POST for `/v1/dry-run` in flavour of https://github.com/cube-js/cube.js/pull/1608
Thanks
=> feat(api-gateway): Support POST for /v1/dry-run

packages/cubejs-api-gateway/src/cached-handler.ts, packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/test/cached-handler.test.ts, packages/cubejs-api-gateway/test/index.test.js, packages/cubejs-api-gateway/yarn.lock, packages/cubejs-query-orchestrator/src/orchestrator/LocalCacheDriver.ts, packages/cubejs-query-orchestrator/src/orchestrator/QueryCache.ts, packages/cubejs-query-orchestrator/src/orchestrator/QueryOrchestrator.ts, packages/cubejs-query-orchestrator/src/orchestrator/RedisCacheDriver.ts, packages/cubejs-query-orchestrator/src/orchestrator/RedisPool.ts, packages/cubejs-query-orchestrator/src/orchestrator/cache-driver.interface.ts, packages/cubejs-server-core/core/DataSourceStorage.js, packages/cubejs-server-core/core/OrchestratorApi.js, packages/cubejs-server-core/core/index.js
=> feat: Introduce health checks

docs/content/Schema/schema-execution-environment.md
**Check List**
The link on [this page](https://cube.dev/docs/schema-execution-environment#async-module) pointing to `schemaVersion` is broken.
=> docs: fix broken link to `schemaVersion` documentation

packages/cubejs-dremio-driver/driver/DremioDriver.js
Set CUBEJS_DB_SSL=true or config.ssl=true to connect to Dremio via HTTPS. Default is HTTP.
**Check List**
Set CUBEJS_DB_SSL=true or config.ssl=true to connect to Dremio via HTTPS. Default is HTTP.
=> feat(@cubejs-backend/dremio-driver): Add HTTPS support for Dremio

packages/cubejs-query-orchestrator/src/driver/BaseDriver.js
Hello!
https://github.com/cube-js/cube.js/issues/1597
Thanks
=> fix(@cubejs-backend/query-orchestrator): Throw an exception on empty pre-agg in readOnly mode, refs #1597

packages/cubejs-client-react/src/hooks/cube-query.js
Hello!
Exception on server side can do unexpected behaviour on client code:
```
const renderChart = Component => ({ resultSet, error, height, ...props }) =>
(resultSet && <Component resultSet={resultSet} height={height} {...props} />) ||
(error && error.toString()) || <Loader height={height} />;
```
`resultSet` can be not empty on error
Thanks
=> fix(@cubejs-client/react): useCubeQuery - clear resultSet on exception

docs/content/Cube.js-Backend/REST-API.md
**Check List**
Followup for https://github.com/cube-js/cube.js/pull/1607
=> docs: add Healthcheck API endpoints to 'REST API' page

packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts, packages/cubejs-query-orchestrator/test/unit/QueryOrchestrator.test.js
=> fix: Non default data source cache key and table schema queries are forwarded to the default data source: broken test

rust/Cargo.lock, rust/cubestore/Cargo.toml, rust/cubestore/src/import/mod.rs, rust/cubestore/src/lib.rs, rust/cubestore/src/metastore/mod.rs, rust/cubestore/src/sql/mod.rs
BigQuery driver exports binary data:
- in base64 for csv-import mode,
- in hex-encoded string literals in sql-import mode.
Hence both use-cases work. Happy to revisit this if we'll run into trouble while adding support for csv export into other drivers.
=> chore(cubestore): allow to import base64-encoded bytes in CSV

docs/content/Configuration/Config.md
Add a prominent warning to [`orchestratorOptions`](https://cube.dev/docs/config#options-reference-orchestrator-options) in the [Configuration page](https://cube.dev/docs/config).
=> docs: add warning to `orchestratorOptions` in 'Configuration' page

docs/src/components/Header/Desktop.tsx
=> docs(@cubejs-docs/site): fix incorrect spelling of GitHub

rust/Cargo.lock, rust/cubestore/src/queryplanner/mod.rs, rust/cubestore/src/queryplanner/query_executor.rs
Greatly reduces query execution time on properly organized data.
This requires a fix for arrow: https://github.com/cube-js/arrow/pull/9
I'll update the PR with the new arrow commit SHA when the arrow fix lands
=> feat(cubestore): filter rowgroups when reading parquet files

packages/cubejs-api-gateway/package.json, packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/test/auth.test.ts, packages/cubejs-backend-shared/src/helpers.ts, packages/cubejs-backend-shared/src/index.ts, packages/cubejs-backend-shared/test/helper.test.ts
Hello!
Some users are storing original JWT (as string) inside authInfo/securityContext by using custom checkAuth or checkAuthMiddleware, which is unexpected (must be object) and can cause this issue. I started to use {} as the default value for securityContext when it's not an object before passing it to schema-compiler. I've added a warning when a user is storing not object inside securityContext to indicate that they are doing something wrong.
Thanks
=> fix: Cannot create proxy with a non-object as target or handler

rust/Cargo.lock, rust/cubestore/Cargo.toml, rust/cubestore/src/import/mod.rs, rust/cubestore/src/lib.rs, rust/cubestore/src/sql/mod.rs, rust/cubestore/src/store/mod.rs, rust/cubestore/src/sys/malloc.rs, rust/cubestore/src/sys/mod.rs
We seem to hit limitations of `malloc` from glibc, which causes physical
memory to be retained by the allocator even after calls to `free`.
Call `malloc_trim` on allocation-heavy operations to ensure we return
freed memory to the system.
See the comment in the code for details.
=> fix(cubestore): return physical memory to the system at rest

packages/cubejs-athena-driver/driver/index.d.ts, packages/cubejs-bigquery-driver/driver/index.d.ts, packages/cubejs-cubestore-driver/driver/index.d.ts, packages/cubejs-mongobi-driver/driver/index.d.ts, packages/cubejs-mysql-driver/driver/index.d.ts, packages/cubejs-postgres-driver/driver/index.d.ts, packages/cubejs-sqlite-driver/driver/index.d.ts
The drivers are missing type definition as there are not extended by BaseDriver in the definitions file.
Due to this, there are errors in the Typescript project while accessing the methods on the driver.
=> chore: improve drivers typescript definitions

packages/cubejs-server-core/src/core/server.ts
This will fix the issue of not able to pass async driverFactory in config.
=> fix(server-core): add support for async driverFactory

rust/cubestore/src/cluster/mod.rs, rust/cubestore/src/config/mod.rs, rust/cubestore/src/import/limits.rs, rust/cubestore/src/import/mod.rs, rust/cubestore/src/lib.rs, rust/cubestore/src/metastore/mod.rs, rust/cubestore/src/sql/mod.rs, rust/cubestore/src/store/mod.rs
On my machine, this produces 1.8x improvement in ingestion speed.
Wins in prod environment should be higher, since WAL uploads are more
expensive.
=> fix(cubestore): skip WAL, partition data directly during ingestion

docs/content/Cube.js-Frontend/@cubejs-client-core.md
**Check List**
Just a small typo fix that I saw while reading the documentation: 
"console on ~on~startup"
**Note**
I didn't find a specific section on how to contribute to the docs. Please point me to that if I'm missing something.
=> docs: fixes typo on apiToken param description

packages/cubejs-snowflake-driver/driver/SnowflakeDriver.js
**Check List**
N/A
This PR reorders the snowflake execute statement to check for errors before attempting to access `rows.length`since `rows` can be undefined.
Prevents the following error from occurring:
```
TypeError: Cannot read property 'length' of undefined
at EventEmitter.complete (/srv/node_modules/@cubejs-backend/snowflake-driver/driver/SnowflakeDriver.js:104:31)
at RowStream.<anonymous> (/srv/node_modules/snowflake-sdk/lib/connection/statement.js:579:19)
at RowStream.emit (events.js:315:20)
at RowStream.EventEmitter.emit (domain.js:467:12)
at emitError (/srv/node_modules/snowflake-sdk/lib/connection/result/row_stream.js:292:10)
at close …
```
=> fix(snowflake): Reorder snowflake execute statement to prevent undefined errors

packages/cubejs-cli/src/command/generate.ts, packages/cubejs-schema-compiler/src/scaffolding/ScaffoldingTemplate.js, packages/cubejs-schema-compiler/test/unit/scaffolding-schema.test.ts, packages/cubejs-server-core/src/core/DevServer.ts
**Check List**
This changes will add support to pass `extraParams` objects while creating the schema from tables.
I am using `generateFilesByTableNames` function to dynamically generate schema for all the tables but I have to manually add `dataSource`  to the schema files after generating.
This change will add options to pass  `dataSource` along with other params to the cube schema file
=> add support for extra params in generating schema for tables.

rust/cubestore/src/cluster/mod.rs, rust/cubestore/src/config/mod.rs, rust/cubestore/src/import/limits.rs, rust/cubestore/src/import/mod.rs, rust/cubestore/src/lib.rs, rust/cubestore/src/metastore/mod.rs, rust/cubestore/src/sql/mod.rs, rust/cubestore/src/store/mod.rs
The new version uploads files run in parallel with CSV processing.
This enables us to see the effect of the original optimization.
=> Reland "fix(cubestore): skip WAL, partition data directly during ingestion (#2002)"

docs/content/Cube.js-Backend/Query-Format.md
A code example of Boolean logical operators doesn't work.
This PR makes the first condition from "and" logical operator different than the first condition from "or" logical operator. I only changed the value inside the "values" array, but it could be something else. I don't think it must be more descriptive than that, though.
=> docs: change code of boolean logical operators section example

rust/cubestore/src/queryplanner/query_executor.rs, rust/cubestore/src/queryplanner/serialized_plan.rs
To avoid sending unnecessary requests to nodes.
=> fix(cubestore): prune partitions during initial planning

docs/content/Configuration/Connecting-to-the-Database.md
Specify `CUBEJS_DB_SSL_*` environment variables can be contents of PEM file
=> docs: specify `CUBEJS_DB_SSL_*` environment variables can be contents of PEM file

rust/cubestore/src/cluster/mod.rs, rust/cubestore/src/metastore/mod.rs, rust/cubestore/src/remotefs/gcs.rs, rust/cubestore/src/remotefs/mod.rs, rust/cubestore/src/remotefs/queue.rs, rust/cubestore/src/remotefs/s3.rs, rust/cubestore/src/store/compaction.rs, rust/cubestore/src/store/mod.rs
The goal is to free up disks on the worker machines.
This is done via a background process that periodically lists files on
remotes and removes any extra files we have locally. This process runs
every 10 minutes.
The cleanup only affects the direct siblings (i.e. the `.parquet` files)
and not subdirectories. E.g. the exceptions to the cleanup are
`metastore-*` and `node-heart-beats`. The underlying subsystems manage
their local copies directly.
Uploads are now prepared in a separate subdirectory of `.cubestore` to
avoid accidental removals by the cleanup process. The `RemoteFS` APIs
are updated accordingly.
=> feat(cubestore): cleanup local copies of files removed remotely

docs/content/Configuration/Connecting-to-the-Database.md, packages/cubejs-clickhouse-driver/driver/ClickHouseDriver.js
**Added HTTPS support to ClickHouse driver.**
Now it's possible to connect to a HTTPS-enabled ClickHouse database when `CUBEJS_DB_SSL` is set to `true`.
See https://github.com/apla/node-clickhouse#options (the "protocol" option) for implementation details.
**Added read-only support to ClickHouse driver.**
Now it's possible to connect to a ClickHouse server when a user's permissions are restricted to read-only when new config flag `CUBEJS_DB_CLICKHOUSE_READONLY` is set to `true`.
See https://clickhouse.tech/docs/en/operations/settings/permissions-for-queries/#settings_readonly and https://github.com/apla/node-clickhouse#options (the "readonly" option) for implementation details.
---
Documentation is updated in relevant parts.
=> Add HTTPS and readOnly support to ClickHouse driver

rust/cubestore/src/remotefs/gcs.rs, rust/cubestore/src/remotefs/mod.rs, rust/cubestore/src/remotefs/s3.rs
To fix a race when the cleanup process removes the partially downloaded file
=> fix(cubestore): put temporary downloads into a separate directory

rust/cubestore/src/metastore/mod.rs, rust/cubestore/src/metastore/partition.rs, rust/cubestore/src/scheduler/mod.rs
Partitions are frequently updated to set the `last_used` field. This
causes too many warmup requests.
=> fix(cubestore): warmup partitions only once

rust/cubestore/src/config/mod.rs
Does not cause a user-visible change in behavior, but useful for
debugging.
=> chore(cubestore): turn off mysql in stop_processing_loops()

rust/cubestore/src/queryplanner/mod.rs, rust/cubestore/src/queryplanner/query_executor.rs, rust/cubestore/src/remotefs/gcs.rs, rust/cubestore/src/remotefs/mod.rs
Concretely:
- `NamedTempFile` usages call system APIs,
- `batch_to_dataframe` are potentially compute-intensive.
Meta plans should generally be cheap, but put them into
`spawn_blocking` too for consistency.
=> fix(cubestore): use `spawn_blocking` on potentially expensive operations

rust/cubestore/src/queryplanner/partition_filter.rs, rust/cubestore/src/queryplanner/serialized_plan.rs
This allows to prune the first and the last partitions, a common case
that we definitely should support.
=> fix(cubestore): allow to prune partitions with unbounded min or max

packages/cubejs-client-core/index.d.ts, packages/cubejs-client-react/index.d.ts
**Check List**
Broken off of #2196
I tried using cube.js react client in a typescript project, and found a number of issues with the provided typescript types. In many cases, the types were not specific enough to be used in a strict typescript project, but in others the types were simply incorrect. The included changes were necessary for me to use it in my project, where I use a I have created QueryBuilder wrapper similar to that in the playground, but strongly typed.
=> TypeScript fixes

.github/workflows/publish.yml, .github/workflows/push.yml
Hello!
Problems:
- docs/node_modules are not cached
- 2 caches, which is slow for downloading and persistence after job
Before
- 9 minutes total (pretty random thing)
- 1 19 yarn cache
- 2 11 lerna cache
After
Thanks
=> misc(ci): Cache docs/node_modules + use only one cache

.github/workflows/publish.yml, .github/workflows/push.yml
Hello!
- Remove duplicated run for push event (- 10 another jobs in queue)
- Don't run `yarn install` on exact cache hit (validation is not needed) (-15 secs)
- Use yarn from hosted machine (-25-40 sec)
Before
After
Thanks
=> misc(ci): Speedup 🚀 

rust/cubestore/src/queryplanner/query_executor.rs
The router will only pipe the results back to the client.
=> fix(cubestore): fully execute a single-node query on a worker

docs/content/Schema/pre-aggregations.md
Mention that `sqlAlias` property can be defined on both the cube and pre-aggregation definitions to ensure shorter table names.
Also a minor typo fix.
=> docs: mention `sqlAlias` can also be specified in the pre-aggregation definition

docs/content/Auth/Overview.md
Followup to https://github.com/cube-js/cube.js/pull/2272
=> docs(security): fix incorrect grammar in callout

packages/cubejs-server/src/server.ts, packages/cubejs-server/src/server/container.ts
Hello!
fix https://github.com/cube-js/cube.js/issues/2267
Thanks
=> fix(server): overide env variables only on reload, fix #2267

rust/cubestore/src/queryplanner/mod.rs, rust/cubestore/src/queryplanner/optimizations/mod.rs, rust/cubestore/src/queryplanner/optimizations/prefer_inplace_aggregates.rs, rust/cubestore/src/queryplanner/query_executor.rs
The new physical plan optimization aims to change the consumer of
`CubeTableExec` from `MergeExec` to `MergeSortExec`, but only if
results get consumed by aggregations.
This lets us use more efficient inplace aggregations in more cases.
=> fix(cubestore): use merge sort exec when aggregations are required

packages/cubejs-client-react/index.d.ts, packages/cubejs-client-react/src/QueryBuilder.jsx
**Check List**
Broken off from #2196 
I ran into some issues while making other changes to the React QueryBuilder, and realized that it was because the QueryBuilder was neither fully controller nor uncontrolled, and was using the React anti-pattern of [unconditionally copying props to state](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#anti-pattern-unconditionally-copying-props-to-state).  Following the recommendations in that article and based on my experience as a React developer, I decided to make QueryBuilder uncontrolled.  This means that QueryBuilder controls it's own state, and can't be modified from the outside save for in specific ways that are allowed through props.
This involved deprecating the `query`, `setQuery`, `vizState`, and `setVizState` …
=> Refactoring React QueryBuilder to be uncontrolled

rust/Cargo.lock, rust/cubestore/src/queryplanner/query_executor.rs
The latter causes us to put cluster send in the wrong place, often
leading to performance degradation.
=> fix(cubestore): fix crash on empty sort order, temporarily disable full hash aggregate optimization

packages/cubejs-client-react/src/QueryBuilder.jsx
**Check List**
Related to #2303 
Prevents `onVizStateChanged` from being called twice unnecessarily by doing an `equals` object comparison before calling the second time.
After this change, in all my testing, it was only called once.  I was unable to find a test case where the query or pivotConfig was changed after `dry-run`.  I'd be happy to test more if you can identify a sequence of actions that could lead to that.  Looking at the code, it _should_ run twice if changed, but I have not proven that.
=> Prevent calling onVizStateChanged twice unless needed

rust/cubestore/src/config/mod.rs, rust/cubestore/src/metastore/mod.rs, rust/cubestore/src/remotefs/queue.rs
We avoid any uploads of metastore or remote filesystem in this mode.
To enable, set `CUBESTORE_NO_UPLOAD` environment variable to any value.
Useful for debugging, not for production use.
=> feat(cubestore): add 'no upload' mode

rust/cubestore/src/config/mod.rs, rust/cubestore/src/lib.rs, rust/cubestore/src/metastore/chunks.rs, rust/cubestore/src/metastore/mod.rs, rust/cubestore/src/metastore/partition.rs, rust/cubestore/src/scheduler/mod.rs, rust/cubestore/src/sql/mod.rs
To reduce write contention on metastore.
We still need to avoid removing partitions used by queries.
In order to do so, we now run the cleanup only after the corresponding timeout.
=> fix(cubestore): make get active partitions a read operation

rust/Cargo.lock, rust/cubestore/src/lib.rs, rust/cubestore/src/queryplanner/mod.rs, rust/cubestore/src/queryplanner/optimizations/mod.rs, rust/cubestore/src/queryplanner/planning.rs, rust/cubestore/src/queryplanner/pretty_printers.rs, rust/cubestore/src/queryplanner/serialized_plan.rs, rust/cubestore/src/queryplanner/topk/execute.rs, rust/cubestore/src/queryplanner/topk/mod.rs, rust/cubestore/src/queryplanner/topk/plan.rs, rust/cubestore/src/sql/mod.rs
This allows to more efficiently execute queries like:
```
SELECT group_key, SUM(agg) FROM … GROUP BY 1 ORDER BY 2 LIMIT 10
```
Previously, we would:
1. pre-aggregate results on the workers,
2. send pre-aggregated results from each worker to the router,
3. do the final aggregation on the router for the full data,
4. sort full results,
5. return top 10 rows.
When the dataset is large and the limit is small, we clearly do a
lot more work than needed, both on the workers and on the router.
After this change, we:
1. pre-aggregate and sort on the workers,
2. send results to the router,
3. process only the required number of rows from each worker to get
the 10 result rows.
After this change, we do much less work on the router.
More improvements are on the way:
- stream only the required number …
=> feat(cubestore): top-k query planning and execution

docs/content/Cube-Cloud/Index.md
Story details: https://app.clubhouse.io/cube-dev/story/409
=> docs(cloud): fix typo in Cube Cloud page

packages/cubejs-query-orchestrator/package.json, packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts, packages/cubejs-query-orchestrator/src/orchestrator/QueryCache.ts, packages/cubejs-query-orchestrator/test/unit/QueryOrchestrator.test.js, yarn.lock
=> fix: Reduce Redis traffic while querying immutable pre-aggregation partitions by introducing LRU in memory cache for refresh keys

rust/Cargo.lock, rust/cubestore/Cargo.toml, rust/cubestore/src/queryplanner/query_executor.rs
Sending large result sets via IPC or network is much cheaper now.
=> fix(cubestore): reduce serialization time for record batches

docs/content/Configuration/Config.md
Story details: https://app.clubhouse.io/cube-dev/story/315
=> docs(config): remove outdated `u` reference in `queryTransformer` example

rust/cubestore/src/queryplanner/topk/plan.rs
This causes performance problems in some operation modes.
Will re-enable when fixed.
=> fix(cubestore): temporarily disable streaming in top-k

rust/cubestore/src/queryplanner/planning.rs
=> chore(cubestore): temporarily disable top-k

rust/cubestore/src/config/mod.rs, rust/cubestore/src/queryplanner/mod.rs, rust/cubestore/src/queryplanner/planning.rs, rust/cubestore/src/queryplanner/topk/execute.rs, rust/cubestore/src/sql/mod.rs
Also adds more verbose logs for a panic that we hit in practice.
This also reverts commits:
- ca668ea24dde6a9e6fa1663bdca9f7cdee8eb8e5: Revert "chore(cubestore): temporarily disable top-k (#2559)"
- eebb2facd8491d3a2ac0ff9f2ffcec89c76073e9: Revert "chore(cubestore): revert streaming once again: ignore topk tests"
=> fix(cubestore): allow to disable top-k with env var

packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts, packages/cubejs-query-orchestrator/test/unit/QueryOrchestrator.test.js
=> fix: Continuous refresh during Scheduled Refresh in case of both external and internal pre-aggregations are defined for the same data source

packages/cubejs-client-core/index.d.ts
**Check List**
- [ x ] Tests has been run in packages where changes made if available
- [ x ] Linter has been run for changed code
There is a `categories` method on `resultSet` which is even shown in cube.js homepage examples.
but due to the absence of its type definitions, I am unable to use it in a TS project without `ts-ignore`
=> feat(@cubejs-client/core): add type definition to the categories method

packages/cubejs-mssql-driver/driver/MSSqlDriver.js
fix The multi-part identifier "columns.data_type" could not be bound
=> fix: multi-part identifier `columns.data_type`

rust/Cargo.lock, rust/cubestore-sql-tests/src/tests.rs
Currently fires on HLL sketches, see the added tests.
The underlying code is also shared by `MergeSortExec`, so the error
fired even without explicit CASE expression.
See the added test for examples.
=> fix(cubestore): fix error on binary results of CASE

packages/cubejs-schema-compiler/src/adapter/PreAggregations.js, packages/cubejs-schema-compiler/test/integration/postgres/pre-aggregations.test.ts
=> fix: Original SQL table is not found when `useOriginalSqlPreAggregations` used together with `CUBE.sql()` reference

rust/cubestore/src/bin/cubestored.rs, rust/cubestore/src/cluster/mod.rs, rust/cubestore/src/cluster/worker_pool.rs, rust/cubestore/src/config/mod.rs, rust/cubestore/src/import/mod.rs, rust/cubestore/src/sql/mod.rs, rust/cubestore/src/store/compaction.rs, rust/cubestore/src/store/mod.rs, rust/cubestore/src/sys/malloc.rs, rust/cubestore/src/util/malloc_trim_loop.rs, rust/cubestore/src/util/mod.rs
Remove on-demand calls and spawn a separate thread that
periodically calls `trim_alloc`.
The period is configurable via `CUBESTORE_MALLOC_TRIM_EVERY_SECS`
environment variable.
The advantages are:
- No need to annonate memory-allocating code.
- Less calls to `trim_alloc` on a lot of simple requests.
A slight disadvantage is that calls to `trim_alloc` are now slightly
less predictable. Although in practice we normally have concurrent
requests that were calling `trim_allocs` at unpredictable times too.
=> fix(cubestore): simplify `trim_alloc` handling

rust/cubestore/src/metastore/mod.rs, rust/cubestore/src/remotefs/gcs.rs, rust/cubestore/src/remotefs/mod.rs
This fixes at least one potential race: the cleanup loop in queue fs
could delete the file while we were writing it.
We also guard against potential errors better now.
Note that any concurrent access to `metastore-current` can still result
in inconsistent state. We do not know any particular instances where
this happens, though.
The GCS change does not affect correctness of uploads, but guards
against potentially incorrect file sizes and make them more
discoverable, e.g. there is now a slightly higher chance to get an error
when reading the file.
=> fix(cubestore): create `metastore-current` atomically, do not send content-length to GCS

rust/cubestore-sql-tests/src/tests.rs, rust/cubestore-sql-tests/tests/cluster.rs, rust/cubestore/src/cluster/mod.rs, rust/cubestore/src/config/mod.rs
`start_processing_loops` only returns when ports are open.
Also reverts the changes that run tests in parallel on multiple ports.
=> chore(cubestore): fix races on cluster test startup

rust/cubestore/src/cluster/mod.rs, rust/cubestore/src/config/mod.rs, rust/cubestore/src/util/error.rs, rust/cubestore/src/util/mod.rs
Simply log the errors and continue. Also logs errors as they appear,
previsouly CubeStore used to wait for program termination.
This can produce spurious errors in the logs due to missing files after
compaction finished. To avoid them, we must propagate 404 errors from
remote fs and log those in debug mode.
=> fix(cubestore): do not stop startup warmup on errors

docs/content/Caching/Running-in-Production.md
We do not communicate between workers. However, we may rely on the
exact struct of the whole cluster to perform some operations.
=> docs(caching): Mention CUBESTORE_WORKERS needs to be set on workers

packages/cubejs-client-core/src/index.js
**Check List**
I have a specific authorization use case that I would like to add to the CubejsApi class. Without access to the class I have to modify the instantiated object which doesn't feel as clean or scalable.
This change just adds the `CubejsApi` class to the named exports so that more experienced developers can extend the API.
=> Exporting CubejsApi class

docs/content/Cube-Cloud/Developer-Tools/Cube-IDE.md, docs/src/components/Layout/MainMenu.tsx
Story details: https://app.clubhouse.io/cube-dev/story/574
=> docs(cloud): move Cube IDE to Developer Tools to match OSS docs

rust/cubestore-sql-tests/src/tests.rs, rust/cubestore/src/http/mod.rs, rust/cubestore/src/import/mod.rs, rust/cubestore/src/metastore/mod.rs, rust/cubestore/src/mysql/mod.rs, rust/cubestore/src/queryplanner/query_executor.rs, rust/cubestore/src/sql/mod.rs, rust/cubestore/src/table/data.rs, rust/cubestore/src/table/mod.rs, rust/cubestore/src/table/parquet.rs, rust/cubestore/src/util/decimal.rs, rust/cubestore/src/util/mod.rs
There is a caveat with this change. It can break existing cubestore instances that have non-default indexes on decimal columns.
I believe this is the only case where CubeStore actually wrote decimal columns into metastore.
There is not easy fix: users will probably have to recreate the database in that case.
We did not write decimals into the default index, though, so most users should be unaffected.
=> fix(cubestore): allow decimal and float type in index keys 

packages/cubejs-mssql-driver/driver/MSSqlDriver.js
Hi, this PR provides type mappings from generic types to MSSQL data types. Fixes bugs when creating external pre-aggregation tables in a MSSQL database.
**Check List**
#2831
=> fix(@cubejs-backend/mssql-driver): add column type mappings for MSSQL external pre-aggregations

rust/cubestore/src/remotefs/gcs.rs, rust/cubestore/src/sql/mod.rs
The new env vars are:
- `CUBESTORE_GCP_SERVICE_ACCOUNT`
- `CUBESTORE_GCP_SERVICE_ACCOUNT_JSON`
- `CUBESTORE_GCP_GOOGLE_APPLICATION_CREDENTIALS`
- `CUBESTORE_GCP_GOOGLE_APPLICATION_CREDENTIALS_JSON`
Eventually we want to disallow `SERVICE_ACCOUNT` for consistency with
AWS configuration. To allow gradual transition, CubeStore warns
when it sees the old variants.
=> feat(cubestore): cubestore-specific env vars for GCS configuration

rust/Cargo.lock, rust/cubestore/src/cluster/message.rs, rust/cubestore/src/cluster/mod.rs, rust/cubestore/src/queryplanner/mod.rs, rust/cubestore/src/queryplanner/query_executor.rs, rust/cubestore/src/sql/mod.rs
... instead of the router.
Combining query results can require heavy compute resources, e.g.
grouping, sorting, etc. Doing this on the router node does not as we
have only one router.
=> feat(cubestore): combine query results on worker

packages/cubejs-backend-shared/src/env.ts, packages/cubejs-cli/src/templates.ts, packages/cubejs-cli/test/templates.test.ts, packages/cubejs-schema-compiler/src/adapter/PreAggregations.js, packages/cubejs-schema-compiler/src/compiler/CubeEvaluator.js, packages/cubejs-schema-compiler/test/unit/schema.test.ts, packages/cubejs-server-core/src/core/DevServer.ts
Hello!
In the next major version, We are going to make `scheduledRefresh: true` by default for any pre-aggregations, but before We are going to make an preview period for new projects to verify that everything works without errors.
Thanks
=> feat: Make scheduledRefresh true by default (preview period)

rust/cubestore/src/http/mod.rs, rust/cubestore/src/lib.rs, rust/cubestore/src/mysql/mod.rs
Show them in the logs, but send only the message back to the user.
=> fix(cubestore): remove backtraces from error messages

packages/cubejs-api-gateway/src/dateParser.js, packages/cubejs-api-gateway/test/dateParser.test.js
… days than previous month
**Check List**
- [x ] Tests has been run in packages where changes made if available
- [x ] Linter has been run for changed code
- [x ] Tests for the changes have been added if not covered yet
#2141 
Order of operations on moment were reversed when dateParser evaluated 'last X months' dateStrings.
=> fix(@cubejs-api-gateway): fix end date when current month has less days than previous month

packages/cubejs-client-core/package.json, packages/cubejs-client-core/src/index.js
**Check List**
`@cubejs-client/core` depends on `uuid@3.4.0`, which uses the older `browser` fields instead of the new `exports` field in its `package.json`, which causes issues for newer bundlers that don't support the `browser` field.  By updating to `uuid@8.3.2`, `@cubejs-client/core` can be used in projects that use modern bundlers like Vite/esbuild.
=> @cubejs-client/core: update uuid package 3.4.0 -> 8.3.2

packages/cubejs-bigquery-driver/src/HydrationStream.ts
Hello!
BigQuery SDK uses Buffer for HLL in streaming, which causes a problem with CSV reading on the Cube Store side.
Thanks
=> fix(bigquery-driver): Encode buffer as base64 for CSV (streaming)

docs/content/Guides/Incremental-Pre-Aggregations.md, docs/content/Schema/pre-aggregations.md
We're getting questions about `autorollup` pre-aggregations. However, this feature is not supported. Let's remove mentions of this feature from docs so we don't confuse Cube.js users.
=> docs: Remove mentions of non-existent autorollup feature

packages/cubejs-client-vue/src/QueryBuilder.js, packages/cubejs-client-vue/tests/unit/QueryBuilder.spec.js
**Check List**
This PR provides support for filters containing [boolean logical operators](https://cube.dev/docs/query-format#boolean-logical-operators). Previously, fields `and` and `or` were discarded by `validatedQuery` watcher.
=> feat(@cubejs-client/vue): support logical operator filters

packages/cubejs-client-vue/src/QueryBuilder.js, packages/cubejs-client-vue/tests/unit/QueryBuilder.spec.js
**Check List**
This PR ensures all PivotConfig properties are assigned when updated via builder slot props' `updatePivotConfig.update`. Previously only `x` and `y` were assigned.
=> feat(@cubejs-client/vue): support all pivotConfig props

rust/cubestore/src/bin/cubestored.rs, rust/cubestore/src/cluster/worker_pool.rs, rust/cubestore/src/telemetry/mod.rs, rust/cubestore/src/util/logger.rs, rust/cubestore/src/util/mod.rs
Logs now show pid and name of the logging process.
The latter only shows for select worker subprocesses.
=> chore(cubestore): add context information to logs

packages/cubejs-schema-compiler/src/adapter/MssqlQuery.js
Addresses a bug with casting to DATETIME in MSSQL
#2729
=> Change MssqlQuery dateTimeCast to DATETIME2

rust/cubestore-sql-tests/src/tests.rs, rust/cubestore/src/metastore/mod.rs, rust/cubestore/src/queryplanner/serialized_plan.rs, rust/cubestore/src/sql/mod.rs, rust/cubestore/src/sql/parser.rs, rust/cubestore/src/util/mod.rs, rust/cubestore/src/util/strings.rs
The dump contains enough information to allow reproducing the same query
on another machine. Intended only for debugging CubeStore and not designed
for heavy use in production.
To use, prefix select queries with `dump`, e.g.
```sql
DUMP SELECT customer_id, SUM(total) FROM s.orders GROUP BY 1
```
The above SQL returns the dump directory. Inside there are parquet files,
metastore backup and the SQL query.
To reproduce the same query, first restore the metastore backup:
```sh
ldb --db=$DUMP/metastore restore --backup_dir=$DUMP/metastore-backup
```
Then run CubeStore inside the dump:
```sh
CUBESTORE_DATA_DIR=$DUMP ./cubestored
```
=> feat(cubestore): debug data dumps for select queries

packages/cubejs-cli/src/templates.ts
=> fix: Use CUBEJS_REDIS_URL in serverless templates, fix #2970

docs/content/Getting-Started/Getting-Started-Nodejs.md
=> docs(getting-started): fix link format typo

packages/cubejs-cubestore-driver/package.json, packages/cubejs-dremio-driver/package.json, packages/cubejs-elasticsearch-driver/test/ElasticSearchOpenDistro.integration.js, packages/cubejs-prestodb-driver/package.json, packages/cubejs-prestodb-driver/test/PrestoDriverTest.js, packages/cubejs-schema-compiler/package.json, packages/cubejs-schema-compiler/test/integration/clickhouse/ClickHouseDbRunner.js, packages/cubejs-schema-compiler/test/integration/mssql/MSSqlDbRunner.js, packages/cubejs-schema-compiler/test/integration/mysql/MySqlDbRunner.js, packages/cubejs-sqlite-driver/package.json, yarn.lock
Hello!
We use yarn workspaces to reduce disk usage with transitive dependencies, let's align all versions of test containers to one major version.
Thanks
=> misc: migrate testcontainers to ^7.5

rust/Cargo.lock, rust/cubestore-sql-tests/Cargo.toml, rust/cubestore-sql-tests/src/multiproc.rs, rust/cubestore-sql-tests/tests/cluster.rs, rust/cubestore-sql-tests/tests/multi_process.rs, rust/cubestore/Cargo.toml, rust/cubestore/src/bin/cubestored.rs, rust/cubestore/src/cluster/mod.rs, rust/cubestore/src/cluster/worker_pool.rs, rust/cubestore/src/lib.rs, rust/cubestore/src/sys/mod.rs, rust/cubestore/src/sys/process.rs, rust/cubestore/src/util/mod.rs, rust/cubestore/src/util/respawn.rs
procspawn now only used as a dev dependency for test support code.
- The child process now stars with `argv[0]`. Command line arguments are
passed by the callers instead of being replicated. Theses should
produce better UX and more context in process monitoring tools.
CubeStore itself ignores all command-line arguments.
- Implementation is simpler, although the idea is the same.
- The API usage is a bit more complicated, requires registering main
functions separately. This allows to simplify implementation by avoiding
the mapping of function addresses across processes.
=> chore(cubestore): replace procspawn with custom implementation

rust/cubestore/src/util/respawn.rs
So library consumers can write respawn-based tests.
=> chore(cubestore): make respawn test helper public

packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts, packages/cubejs-server-core/src/core/server.ts, packages/cubejs-server-core/test/unit/index.test.ts
Hello!
Few versions ago we introduced CUBEJS_REFRESH_WORKER, but it will not work with Refresh Scheduler.
Thanks
=> fix: CUBEJS_REFRESH_WORKER shouldn't enabled externalRefresh

rust/cubestore/src/config/mod.rs, rust/cubestore/src/sql/mod.rs
- `CUBESTORE_MAX_ACTIVE_DOWNLOADS` for limit on concurrent downloads.
- `CUBESTORE_MAX_ACTIVE_UPLOADS` for limit on concurrent uploads.
- `CUBESTORE_MAX_CACHED_QUERIES` for limit on SQL query LRU cache size.
=> feat(cubestore): add some configuration variables

packages/cubejs-client-core/src/HttpTransport.js
**Check List**
#1558 
**Description**
In HttpTransport, `this.method = this.method || (url.length < 2000 ? 'GET' : 'POST');` the later url length logic will only get run once if method is undefined. Any request afterwards will be taken from `this.method`. For apps that uses the client as a singleton like angular, client will never fire a `POST` request if query is too long.
=> fix(@cubejs-client/core): Long Query 413 URL too large

packages/cubejs-cubestore-driver/src/CubeStoreQuery.ts
=> fix(cubestore-driver): Use correct syntax for Intervals

packages/cubejs-cubestore-driver/src/CubeStoreDriver.ts
Hello!
refs https://github.com/cube-js/cube.js/issues/3100
Right now, Cube Store supports UUID, but it's mapping it to Bytes internally, it's why it's expected to use hex encoding in CSV parsing, but it's impossibly hard to do it on the Cube.js side (because it requires a lot of refactoring in each driver). As I quick solution I am going to use varchar(64) for UUID type.
Thanks
=> fix(cubestore-driver): Map UUID to VARCHAR(64)

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js, packages/cubejs-schema-compiler/src/compiler/CubeValidator.js, packages/cubejs-schema-compiler/test/unit/base-query.test.ts
Hello!
Some users can define `refreshKey` with `sql`, and cube.js will check this SQL every 10 seconds, which is too often and it can be useless for performance & cost reasons (example, `SELECT MAX(created) FROM table`). In this PR I've introduced support for every in refresh key that declares SQL.
Thanks
=> feat: Support every for refreshKey with SQL

rust/Cargo.lock, rust/cubestore-sql-tests/src/lib.rs, rust/cubestore-sql-tests/src/rows.rs, rust/cubestore-sql-tests/src/tests.rs, rust/cubestore/src/queryplanner/optimizations/prefer_inplace_aggregates.rs, rust/cubestore/src/queryplanner/planning.rs, rust/cubestore/src/queryplanner/topk/plan.rs
This fixes another instance of the "unmerged data" error.
Order of columns is propagated to the `MergeSortExec` nodes and it must
match the actual data order.
Also land the arrow fix for `HashAggregateExec`.
Both are required for the added test to work.
=>  fix(cubestore): only pick index with exact column order 

docs/content/Deployment/Overview.md
**Check List**
link to deployment guidelines to GCP (GCP Serverless) is 404
=> docs(deployment): fix incorrect URL for GCP deployments

packages/cubejs-api-gateway/src/SubscriptionServer.ts, packages/cubejs-api-gateway/src/gateway.ts
**Check List**
Debug API, allow subscribe to pre-aggregations queue events only by playground JWT
=> fix(api-gateway): Debug API, allow subscribe to pre-aggregations queue events only by playground JWT

packages/cubejs-bigquery-driver/src/BigQueryDriver.ts
Hello!
There are two different permissions in BigQuery to get tables from INFORMATION_SCHEMA & get list of dataSets. Right now, we load the list of dataSets and load tables for each dataSet, but if the user didn't specify `tables.get` permission for dataSet we are not able to get a list of tables. There is no way to get permissions, let's ignore dataSets with wrong permissions from introspection.
Thanks
=> fix(bigquery-driver): Ignore dataSets with wrong permissions

packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts, packages/cubejs-query-orchestrator/src/orchestrator/QueryCache.ts
=> fix: Load build range query only on refresh key changes

rust/Cargo.lock, rust/cubestore-sql-tests/src/tests.rs, rust/cubestore/Cargo.toml, rust/cubestore/src/queryplanner/topk/execute.rs, rust/cubestore/src/sql/mod.rs
The actual fix is in DataFusion.
In addition to the correct semantics, also fixes an infinite loop.
=> fix(cubestore): proper support for nulls in group by

packages/cubejs-client-core/src/index.js
**Check List**
The cloned response stream and the original stream have to be resolved in parallel, otherwise if the response is bigger than the `highWaterMark` (16kB in Node.js) the text stream will hang.
In theory, this can also affect browsers but the `highWaterMark` is usually much bigger there.
See https://github.com/node-fetch/node-fetch/issues/151 and [node-fetch and `highWaterMark`](https://github.com/node-fetch/node-fetch#custom-highwatermark).
=> Fix client hangs when loading big responses (node)

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js, packages/cubejs-schema-compiler/test/integration/postgres/pre-aggregations.test.ts, packages/cubejs-schema-compiler/test/unit/base-query.test.ts
=> fix: Pre-aggregations should have default refreshKey of every 1 hour if it doesn't set for Cube

docs/content/Cube.js-Backend/Query-Format.md, packages/cubejs-api-gateway/src/dateParser.js, packages/cubejs-api-gateway/test/dateParser.test.js
=> feat(cubejs-api-gateway): Add `next` keyword for relative date ranges

packages/cubejs-server-core/src/core/agentCollect.ts
**Check List**
Re-create agent transport after reject WS connection on retries
=> fix(server-core): Re-create agent transport after reject WS connection on retries

rust/cubestore-sql-tests/src/tests.rs, rust/cubestore/src/sys/process.rs, rust/cubestore/src/util/respawn.rs
Enabled only with `process-cleanup` feature.
=> fix(cubestore): do not keep zombie child processes 

rust/cubestore/src/bin/cubestored.rs, rust/cubestore/src/cluster/mod.rs, rust/cubestore/src/config/injection.rs, rust/cubestore/src/config/mod.rs, rust/cubestore/src/http/mod.rs, rust/cubestore/src/http/status.rs, rust/cubestore/src/lib.rs
Available only on router nodes via `/livez` and `/readyz`.
Use `CUBESTORE_STATUS_BIND_ADDR` or `CUBESTORE_STATUS_PORT` for
endpoint configuration. Default is `0.0.0.0:3031`.
Runs as a separate HTTP server to simplify implementation. Main HTTP
server does waits for metastore from remote before it starts listening
on a socket.
The checks are very basic. Liveness check tries to execute a trivial
query. Readiness check after metastore got loaded from remote and
can serve another trivial query.
=> feat(cubestore): readiness and liveness probes 

packages/cubejs-server-core/src/core/types.ts
Following https://github.com/cube-js/cube.js/pull/557, the `schemaVersion` option also supports an async function.
**Check List**
I'm afraid that for a type change, I don't have time to checkout the repo, install the build tools and run these tasks :(. I'm assuming the CI will do it anyway?
N/A
Following https://github.com/cube-js/cube.js/pull/557, the `schemaVersion` option also supports an async function. This is also what the docs describe.
=> fix schemaVersion type

rust/Dockerfile
By default, we still build with AVX2.
Use `docker --build-arg WITH_AVX2=0` to build without AVX2.
=> chore(cubestore): add option to build docker image without AVX2

rust/Cargo.lock, rust/cubestore-sql-tests/src/tests.rs, rust/cubestore/Cargo.toml, rust/cubestore/src/queryplanner/serialized_plan.rs
- fix `GROUP BY DIMENSION` with timestamps
- add `OFFSET` clause for rolling aggregates
See DataFusion commits for more details.
=> chore(cubestore): updates to rolling window

packages/cubejs-backend-shared/src/time.ts, packages/cubejs-cubestore-driver/src/CubeStoreQuery.ts, packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts, packages/cubejs-query-orchestrator/src/orchestrator/QueryOrchestrator.ts, packages/cubejs-query-orchestrator/test/unit/PreAggregations.test.js, packages/cubejs-schema-compiler/src/adapter/BaseMeasure.js, packages/cubejs-schema-compiler/src/adapter/BaseQuery.js, packages/cubejs-schema-compiler/src/adapter/BaseTimeDimension.js, packages/cubejs-schema-compiler/src/adapter/PreAggregations.js, rust/Cargo.lock, rust/cubestore-sql-tests/src/tests.rs
=> feat: Mixed rolling window and regular measure queries from rollup support

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js, packages/cubejs-schema-compiler/test/integration/postgres/sql-generation.test.ts
**Check List**
No related issue.
This PR adds support to properly process multiple filters over the same dimension when accessing them through `FILTER_PARAMS` context variable, this becomes particularly handy when the expression involved is an `ILIKE` operator (or similar).
With this change it's possible to define SQLs like:
```js
cube('Foo', {
sql: `SELECT id, name FROM foo WHERE ${FILTER_PARAMS.Foo.name.filter('name')}`,
dimensions: {
id: {
type: 'number',
sql: 'id',
primaryKey: true
},
name: {
type: 'string',
sql: 'name'
}
}
}
```
and if the filter passed are in the form:
```js
filters: [
{
dimension: 'Foo.name',
operator: 'contains',
values: ['Foo']
}, {
dimension: 'Foo.name', …
```
=> Support multi-value filtering on same column through FILTER_PARAMS

rust/Cargo.lock
And other issues caused by invalid reads from Parquet.
The actual fix is in arrow repository.
=> fix(cubestore): 'unsorted data in merge'

packages/cubejs-bigquery-driver/src/BigQueryDriver.ts, packages/cubejs-query-orchestrator/src/driver/BaseDriver.js
Hello!
There was a problem before this PR that we use an additional call for each table to introspect columns.
1. list of datasets
2. list of tables
3. list of columns for each table
In this PR we started to use INFORMATION_SCHEMA.COLUMNS for each dataset, it will reduce the number of calls that we send to API.
Thanks
=> feat(bigquery-driver): Use INFORMATION_SCHEMA.COLUMNS for introspection

packages/cubejs-client-core/src/ResultSet.js, packages/cubejs-client-core/src/tests/table.test.js
Prefix the key used to build the schema with an underscore to ensure the key is treated as a string and not as a numeric and thus as an array index.
**Check List**
https://github.com/cube-js/cube.js/issues/3367
=> fix(client-core): keep order of elements within tableColumns

packages/cubejs-postgres-driver/src/PostgresDriver.ts
Hello!
Proof, External pre-aggregation in Cube Store with HLL sketch:
Thanks
=> fix(postgres-driver): Use correct encoding for HLL_POSTGRES

packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts, packages/cubejs-query-orchestrator/test/unit/PreAggregations.test.js
**Check List**
554e6e014f684792b20147bd2fd2f3cb
From "One or more pre-aggregation tables could not be found to satisfy that query"
To 
"Your configuration restricts query requests to only be served from pre-aggregations, and no pre-aggregation was found matching this query. Either update your pre-aggregations or disable rollup only mode in your Cube.js configuration."
=> fix(@cubejs-backend/query-orchestrator): rollup only mode error message update

rust/cubestore/src/bin/cubestored.rs, rust/cubestore/src/config/mod.rs
Hard failures now produce more meaningful error messages.
And we also report some new warnings on common misconfigurations.
=> fix(cubestore): improve diagnostics on invalid configurations

.github/workflows/publish.yml
We used to publish CubeStore image into the CubeJS repository.
=> fix(cubestore): fix Docker Hub repository name

packages/cubejs-client-vue/src/QueryBuilder.js
**Check List**
#3449
Added a `catch` promise to contain errors returned when executing the following `dryRun`: 
* https://github.com/cube-js/cube.js/blob/master/packages/cubejs-client-vue/src/QueryBuilder.js#L395
=> fix(@cubejs-client/vue): catch `dryRun` errors on `query-builder` mount

docs/content/Deployment/Platform-Docker.mdx, docs/content/Getting-Started/Getting-Started-Docker-Compose.mdx
When starting up cube.js locally with `docker-compose up` it is possible for the dev dependencies to leak into container.
This fix demonstrates in documentation how to prevent this.
No code has been changed.
=> docs(deployment): prevent dev dependencies leaking in Docker Compose startup

examples/helm-charts/cubejs/templates/common-env.tpl, examples/helm-charts/cubestore/templates/workers/statefulset.yaml, examples/kubernetes/cluster/cube-api-deployment.yaml, examples/kubernetes/cluster/cube-api-schema-configmap.yaml, examples/kubernetes/cluster/cube-refresh-worker-deployment.yaml
**Check List**
Running the default setup of cube-stack did not connect cubejs to cubestore automatically. This PR adds a default setup to connect cubejs to cubestore without specifying values.
=> examples(helm-charts): Default values for cube store and redis

examples/helm-charts/cubejs/Chart.yaml, examples/helm-charts/cubejs/README.md, examples/helm-charts/cubejs/templates/_helpers.tpl, examples/helm-charts/cubejs/templates/common-env.tpl, examples/helm-charts/cubejs/templates/ingress.yaml, examples/helm-charts/cubejs/values.yaml
- Fix standalone cubejs chart
- Add ingressClassName to support k8s 1.22
- Update version to 0.28.39
=> examples(helm-charts): Fix standalone cubejs chart and add ingressClassName support

rust/cubestore/Cargo.toml, rust/cubestore/src/config/mod.rs, rust/cubestore/src/import/mod.rs, rust/cubestore/src/metastore/mod.rs, rust/cubestore/src/sql/mod.rs, rust/cubestore/src/store/compaction.rs, rust/cubestore/src/store/mod.rs, rust/cubestore/src/table/data.rs, rust/cubestore/src/table/mod.rs, rust/cubestore/src/table/parquet.rs, rust/cubestore/src/table/redistribute.rs
To remove an extra implementation of parquet reads, parquet writes and
an extra merge operation. This also lends the arena-based data
primitives obsolete as column-based storage should also be reasonably
efficient.
This commit also removes `WALStore` and the corresponding code.
It was not used anywhere and used rewritten primitives.
=> chore(cubestore): rewrite compaction using arrow primitives 

packages/cubejs-cubestore-driver/src/CubeStoreQuery.ts
Hello!
Cube.js has a contains filter which is a case insensitive filter (https://cube.dev/docs/query-format/#contains). Starting from `v0.28.37` Cube Store started to support ILIKE operator (https://github.com/cube-js/cube.js/commit/6a3fe647fb5f93932521591b6a7c572b88758bfe) which is the correct way to handle the contains filter.
Thanks
=> fix(cubestore-driver): Use ILIKE for contains filter

rust/Cargo.lock, rust/cubestore/src/table/parquet.rs
The arrow code writes statistics with a different ordering. Tweak it in
our fork to use lexicographical order.
=> fix(cubestore): fix parquet statistics for string columns

rust/Cargo.lock, rust/cubestore-sql-tests/src/tests.rs, rust/cubestore/Cargo.toml, rust/cubestore/src/cluster/mod.rs, rust/cubestore/src/lib.rs, rust/cubestore/src/metastore/index.rs, rust/cubestore/src/metastore/job.rs, rust/cubestore/src/metastore/mod.rs, rust/cubestore/src/metastore/multi_index.rs, rust/cubestore/src/metastore/partition.rs, rust/cubestore/src/queryplanner/filter_by_key_range.rs, rust/cubestore/src/queryplanner/mod.rs, rust/cubestore/src/queryplanner/planning.rs, rust/cubestore/src/queryplanner/pretty_printers.rs, rust/cubestore/src/queryplanner/query_executor.rs, rust/cubestore/src/queryplanner/serialized_plan.rs, rust/cubestore/src/scheduler/mod.rs, rust/cubestore/src/sql/cache.rs, rust/cubestore/src/sql/mod.rs, rust/cubestore/src/sql/parser.rs, rust/cubestore/src/store/compaction.rs, rust/cubestore/src/store/mod.rs, rust/cubestore/src/table/data.rs, rust/cubestore/src/table/parquet.rs
The index will ensure the data from multiple tables is partitioned
with the same keys and collocated on the same machines. This allows
to evenly distribute the work on JOIN queries and avoid duplicating
same keys on different machines.
However, we need more work to keep partitions at async on ingestion
and compaction.
```
CREATE PARTITIONED INDEX schema.pindex(id int, url text);
CREATE TABLE schema.foo(some_id int, some_url text, data text)
ADD TO PARTITIONED INDEX pindex(some_id, some_url);
CREATE TABLE schema.bar(other_id int, other_url text, other_data text)
ADD TO PARTITIONED INDEX pindex(other_id, other_url);
SELECT some_id, data, other_data
FROM schema.foo f
JOIN schema.bar b ON f.some_id = b.other_id AND f.some_url = b.other_url
```
This is an early version. There are known …
=> feat(cubestore): partitioned indexes for faster joins 

packages/cubejs-client-core/src/ResultSet.js, packages/cubejs-client-core/src/tests/granularity.test.js
**Check List**
Hii^^ I'm using cubeJS for analytics API^^ 
First of all, thank you for creating a really great platform. thanks to you, I'm so into cubeJs these days..
if I change the locale value of dayjs on the front-end, no value is displayed when granularity is week.
Currently, if you look at the ResultSet code, the weekStart must be set to 1 to work properly.
However, the value can be modified by the client as much as possible (https://day.js.org/docs/en/i18n/changing-locale)
so it seems necessary to guide or cope with it. 
To reproduces the problem, you can overwrite the locale of dayjs with ko or another value and test it.
please refer to the test code..
thank you^^
=> fix(client-core): dayjs locale conflict

examples/kubernetes/cluster/cubestore-router-statefulset.yaml, examples/kubernetes/cluster/cubestore-workers-statefulset.yaml
**Check List**
This adds a K8s config example to resolve the issue of not having dedicated data dirs for Cube Store.
This example will be used in the docs where @hassankhan will implement updates. As per @ilya-biryukov request to use the same remote dir and dedicated data dirs, this example will now adhere to this requirement.
=> examples(k8s): added cubestore data dir env var

.github/workflows/publish.yml, .github/workflows/rust-master.yml, .github/workflows/rust.yml
Hello!
We started to support Windows build for Cube Store from GNU builds, but after some time we switched to MSVC because: GNU toolkit requires GNU libc which is not installed on Windows by default. 
Thanks
=> misc: Disable build for x86_64-pc-windows-gnu (replaced by msvc)

docs/content/Configuration/Config.mdx
Thanks @igorlukanin!
Story details: https://app.shortcut.com/cube-dev/story/1145
=> docs(config): fix broken link to `dataSource` documentation

docs/content/Configuration/Databases/AWS-Redshift.mdx, docs/content/Configuration/Databases/Google-BigQuery.mdx, docs/content/Configuration/Databases/Snowflake.mdx
Thanks @tanvi-cota
Story details: https://app.shortcut.com/cube-dev/story/1146
=> docs(config): fix broken link to Export Bucket documentation

rust/cubestore/src/queryplanner/hll.rs, rust/cubezetasketch/src/encoding.rs, rust/cubezetasketch/src/sketch.rs, rust/cubezetasketch/src/sparse.rs
Add a buffer that delays write into VLE-encoded array for Sparse HLLs.
This produces 45x improvement for merging 10k single-value HLLs.
This adds up to 180x improvement with the previous commit.
The buffer is a `BTreeSet` instead of vector in the original
implementation. This allows to keep the buffer smaller and do less
compactions in some cases, e.g. when merging HLLs with many common
elements. It does use more memory and CPU when merging HLLs with
many different hashes.
=> fix(cubestore): speed up HLL++ merges, up to 180x in some cases 

docs/content/Caching/Running-in-Production.mdx, docs/content/Configuration/Environment-Variables-Reference.md
Story details: https://app.shortcut.com/cube-dev/story/1095
=> docs(caching): document that Cube Store can use EC2 instance metadata for IAM credentials

packages/cubejs-backend-native/lib/index.ts, packages/cubejs-backend-native/native.d.ts, packages/cubejs-backend-native/src/channel.rs, packages/cubejs-backend-native/src/lib.rs, packages/cubejs-backend-native/src/utils.rs
Hello!
Internal change. In the previous version of API, I used additional functions to resolve `AsyncChannel`: `channel_resolve` & `channel_reject`. These functions weren't mapped to an object (`AsyncChannel`) and we used an additional argument (first argument) to pass a reference to AsyncChannel via JsBox (external reference in the API). In upcoming changes, I am going to rewrite AsynChannel to be used with `JsPromise` (awaiting results from Promise), but to do it `AsyncChannel` must be a generic object to accept value from the `promise.then`.
For unpacking JsBox from an argument we used a code:
```
let channel = cx.argument::<JsBox<JsAsyncChannel>>(0)?;
```
But these functions didn't know anything about what type `JsAsyncChannel` will store in it and to resolve this limitation I mapped …
=> chore(native): Store state of JsAsyncChannel as JsBox in this

packages/cubejs-oracle-driver/package.json
Hello!
It's needed to unblock developers of Cube.js which are using arm64.
Thanks
=> chore(oracle-driver): Use oracledb as optionalDependency

packages/cubejs-api-gateway/package.json, packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/src/graphql.ts, packages/cubejs-server-core/src/core/CompilerApi.js
This PR is an implementation of the GraphQL spec described in issue #3433
I think i covered all the main functionalities of the REST API.
A new endpoint `/cubejs-api/graphql` is added in the gateway.
All security middlewares (checkAuth, queryRewrite, etc.) are still used.
In dev mode, graphiql UI is available.
- GraphQL schema is automatically generated using the compilerApi.
- GraphQL AST info are used to generate cubequery at root cube entity level
- Results are remapped to the graphql query shape
Current implementation will raise an error for a `continueWait` response. Long polling is not implemented (and not possible with this API design).
original query:
```json
{
"measures": ["Stories.count"],
"dimensions": ["Stories.category"],
"filters": [{
"member": "Stories.isDraft",
"operator": …
```
=> feat(gateway): Add GraphQL endpoint

docs/content/Deployment/Platform-Docker.mdx
I've been working on deploying an httos cubejs instance using `docker-compose` over the past few days. Although it was good enough for me to finally make it, as an absolute Docker Compose beginner I ran into some issues that might have been obvious to a more experienced dev, but they weren't for me. Although it was a cool learning experience, I think updating the documentation to be more accurate and work out of the box will make things easier for those ahead.
The changes are:
- Specify that the `cube.conf` file goes inside a `nginx` directory, otherwise nothing will be mounted in the corresponding
- Don't mount the `nginx` directly on top of `etc/nginx`, do it on `etc/nginx/conf.d` instead, otherwise it will overwrite existing nginx configuration, and the webserver will fail to start.
- …
=> docs(deployment): improve Docker reverse proxy documentation

docs/content/Deployment/Platform-Cube-Cloud.mdx, docs/content/Deployment/Production-Checklist.mdx
Story details: https://app.shortcut.com/cube-dev/story/1150
=> docs(deployment): add links to Migrating to Cube Cloud blog post

rust/.gitignore, rust/cubestore/src/config/mod.rs, rust/cubestore/src/remotefs/minio.rs, rust/cubestore/src/remotefs/mod.rs, rust/cubestore/src/remotefs/s3.rs
**Check List**
- [-] Tests for the changes have been added if not covered yet (Still working on this one)
- [-] Docs have been added / updated if required (Will get to this once we've tested it well)
MinIO intergration for cubestore
=> Master minio intergration

docs/content/Examples-Tutorials-Recipes/Recipes/Optimizing-complex-cubes.mdx
The "Query Acceleration" category is duplicated:
I changed the category name as in previous recipes  😃
=> docs(recipes): fix recipes menu order

docs/src/templates/DocTemplate.tsx
**Check List**
Fix scroll to correct element if multiple child menu have the same id. 
Eg: in https://cube.dev/docs/@cubejs-client-vue, clicking on QueryRender > props scrolls to **QueryBuilder** > props.
=> docs: fix menu scroll when item is selected

packages/cubejs-client-core/src/ResultSet.js, packages/cubejs-client-core/src/tests/ResultSet.test.js, packages/cubejs-client-core/src/tests/data-blending.test.js
All `undefined`/`null` measure values will now be converted to `0`
=> fix(client-core): nullish measure values [v0.29]

packages/cubejs-playground/src/QueryBuilder/FilterGroup.tsx
The field selector inside FILTERS should expand to contain the full name of the field.
=> fix(cubejs-playground): responsive filter group size

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts, packages/cubejs-query-orchestrator/src/orchestrator/QueryCache.ts, packages/cubejs-server-core/src/core/RefreshScheduler.ts, packages/cubejs-server-core/test/unit/RefreshScheduler.test.ts
=> fix: refresh process for `useOriginalSqlPreAggregations` is broken

packages/cubejs-client-vue/src/QueryBuilder.js
The returned mem value is sometimes an object, so an error will be reported when deleting it, which has been fixed
=> fix(@cubejs-client/vue): fix error when executing deletion

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
**Check List**
(if it is okay, please validate the above, as doing so should be a lot easier for someone that already has things setup locally)
This change should allow `null` to exist as a value of a property within the security context. Prior to this change, if a `null` value was encountered in the security context, a `Cannot create proxy with a non-object as target or handler` error would be thrown, as `typeof null === "object"`. This PR should resolve this by explicitly checking for `null` before passing the property value to `contextSymbolsProxy`.
=> fix(schema-compiler): Handle `null` Values in Security Context

packages/cubejs-linter/index.js, packages/cubejs-query-orchestrator/src/driver/BaseDriver.js, packages/cubejs-query-orchestrator/src/orchestrator/QueryCache.ts, packages/cubejs-query-orchestrator/src/orchestrator/QueryQueue.js, packages/cubejs-query-orchestrator/test/unit/BaseDriver.test.ts, packages/cubejs-query-orchestrator/test/unit/PreAggregations.test.js, packages/cubejs-query-orchestrator/test/unit/QueryOrchestrator.test.js
**Check List**
* Make eslint no-unused-vars ignore unused args/vars starting with _
* Fix @cubejs-backend/query-orchestrator lint errors.
=> style: Make eslint no-unused-vars ignore unused args/vars starting with _

packages/cubejs-postgres-driver/src/PostgresDriver.ts, packages/cubejs-postgres-driver/test/PostgresDriver.test.ts
The user defined enum types were being dropped in the Postgres driver.
As per the postgres documentation these are stored internally as four
bytes on disk however the translations occur at query time to the label
from pg_enum which specifies:
"The length of an enum value's textual label is limited by the NAMEDATALEN
setting compiled into PostgreSQL; in standard builds this means at most
63 bytes." [1]
For the purposes of cubejs it should be acceptable to coerce into a
string.
[1] https://www.postgresql.org/docs/9.1/datatype-enum.html
https://github.com/cube-js/cube.js/issues/3946
=> fix: postgres driver add enum support

packages/cubejs-backend-shared/package.json, packages/cubejs-backend-shared/src/http-utils.ts, packages/cubejs-backend-shared/src/node-check.ts, packages/cubejs-backend-shared/test/iterators.test.ts, packages/cubejs-linter/index.js
**Check List**
N/A
Enable for..of loops in eslint. Among other things, helps with `for await(...)` loops to transform async iterators into arrays. Tested with Node v12.22.9 and v16.13.1.
=> style: Enable for..of loops in eslint

rust/cubesql/cubesql/src/compile/context.rs, rust/cubesql/cubesql/src/compile/mod.rs
Hello!
This PR introduces support for `COUNT(1)`, which is the same as `COUNT(*)`. Why? Because some BIs use this syntax.
Thanks
=> feat(cubesql): Support COUNT(1)

examples/external-rollups/dashboard-app/src/App.js
Change outdated 'External rollups' to 'Cube Store pre-aggregations'
=> chore(examples): rename outdated term at heading and switch control label

packages/cubejs-client-ngx/src/client.ts
[Fix] ngx cubejs.watch() not producing errors.
[Spelling] apiInstace -> apiInstance
**Check List**
- [N/A] Tests has been run in packages where changes made if available
- [N/A] Linter has been run for changed code
- [N/A] Tests for the changes have been added if not covered yet
- [N/A] Docs have been added / updated if required
#3961
Added a try catch to throw errors when the watch() promise fails.
=> [Fix] ngx cubejs.watch() not producing errors

rust/cubesql/cubesql/src/compile/engine/information_schema/collations.rs, rust/cubesql/cubesql/src/compile/engine/information_schema/mod.rs, rust/cubesql/cubesql/src/compile/engine/provider.rs, rust/cubesql/cubesql/src/compile/mod.rs
**Check List**
This PR adds support for `information_schema.COLLATIONS` table to cubesql.
`utf8mb4` charset tables from MySQL 8.0 are defined.
=> feat(cubesql): Support information_schema.COLLATIONS table

rust/cubesql/cubesql/src/mysql/server_manager.rs, rust/cubesql/cubesql/src/mysql/service.rs
Hello!
This feature is required for Tableau, which is a popular BI system.
Thanks
=> feat(cubesql): Support prepared statements in MySQL protocol

DEPRECATION.md, packages/cubejs-server-core/src/core/server.ts
=> chore: add deprecation warning for non-Cube Store databases being used as an external database

rust/cubestore/cubestore-sql-tests/src/tests.rs, rust/cubestore/cubestore/src/queryplanner/query_executor.rs
**Check List**
Used specific schema order for in_memory chunks
=> fix(cubestore): Schema type mismatch when in memory chunks are queried

rust/cubestore/cubestore/src/config/mod.rs, rust/cubestore/cubestore/src/metastore/mod.rs, rust/cubestore/cubestore/src/queryplanner/partition_filter.rs, rust/cubestore/cubestore/src/queryplanner/pretty_printers.rs, rust/cubestore/cubestore/src/queryplanner/query_executor.rs, rust/cubestore/cubestore/src/sql/mod.rs
**Check List**
Provides support for decimal in partition pruning algorithm. Before that change decimals in filters were ignored by the partition pruning algorithm.
=> feat(cubestore): Decimal partition pruning

examples/helm-charts/cubejs/templates/common-env.tpl
**Check List**
N/A
`CUBEJS_AWS_OUTPUT_LOCATION` isn't used by CubeJS and it's `CUBEJS_AWS_S3_OUTPUT_LOCATION` instead. This PR just corrects it.
=> fix(helm-charts): correct s3 output location env variable

examples/material-ui-dashboard/README.md
When the command `curl http://cube.dev/downloads/ecom-dump.sql > ecom-dump.sql` is used, the result file is:
```
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>CloudFront</center>
</body>
</html>
```
because of the redirection of the http request to the respective https.
The proposed simple fix (at the url) is enough in order to download the file successfully.
=> Fix the URL of dump db file

packages/cubejs-schema-compiler/src/compiler/CubeValidator.js
**Check List**
Updates schema definitions to be strict on all boolean fields. This aligns with the schema defined in [`cubejs-client-core`](https://github.com/cube-js/cube.js/blob/master/packages/cubejs-client-core/index.d.ts). Previously it was valid to pass along the string `"false"` to fields like `shown` in the cube measure definition, this would be reflected in API responses to clients. As a result, the client library wouldn't effectively filter on just `measure.isVisible` due of truthiness semantics in JS.
This is a bit of a blind change across the board so some review of the other boolean fields should be done before merging.
=> fix(compiler): add strictness to booleans in definition

rust/cubesql/cubesql/e2e/tests/postgres.rs, rust/cubesql/cubesql/src/sql/postgres/buffer.rs, rust/cubesql/cubesql/src/sql/postgres/protocol.rs, rust/cubesql/cubesql/src/sql/postgres/shim.rs
**Check List**
This PR adds support for PLAIN authentication method to pg server.
=> feat(cubesql): Add PLAIN authentication method to pg-wire

packages/cubejs-query-orchestrator/package.json, yarn.lock
**Check List**
Pin es5-ext version to avoid unwanted message in console (https://github.com/medikoo/es5-ext/commit/28de285ed433b45113f01e4ce7c74e9a356b2af2)
Pin version here, because deps tree looks like @cubejs-backend/postgres-driver@0.29.33 -> @cubejs-backend/query-orchestrator@0.29.33 -> moment-range@4.0.2 -> es6-symbol@3.1.3 -> d@1.0.1 -> es5-ext@0.10.59
How to test:
```sh
npx cubejs-cli create -d postgres cubejs-test
```
produces:
=> fix(query-orchestrator): Pin es5-ext version

docs-gen/src/components/helpers.component.ts, docs-gen/src/subthemes/docusaurus2/theme.ts, examples/react-dashboard/dashboard-app/config/paths.js, guides/angular-dashboard/data/SiteConfig.js, guides/bigquery-public-datasets/data/SiteConfig.js, guides/clickhouse-dashboard/data/SiteConfig.js, guides/d3-dashboard/data/SiteConfig.js, guides/mapbox/data/SiteConfig.js, guides/material-ui-dashboard/data/SiteConfig.js, guides/multi-tenant-analytics/data/SiteConfig.js, guides/react-dashboard/data/SiteConfig.js, guides/react-pivot-table/data/SiteConfig.js, guides/real-time-dashboard/data/SiteConfig.js, guides/web-analytics/data/SiteConfig.js, packages/cubejs-backend-shared/src/env.ts, packages/cubejs-postgres-driver/src/PostgresDriver.ts, packages/cubejs-query-orchestrator/src/orchestrator/utils.ts, packages/cubejs-server-core/src/core/DevServer.ts, packages/cubejs-testing/cypress/integration/chart-renderers.spec.js, rust/cubestore/js-wrapper/src/download.ts
**Check List**
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
=> refactor: replace deprecated String.prototype.substr()

packages/cubejs-schema-compiler/src/adapter/BaseGroupFilter.js, packages/cubejs-schema-compiler/test/unit/base-query.test.ts
The BaseGroupFilter needs to implement the `filterParams` and
`conditionSql` methods order to support using or/and filters with
FILTER_PARAMS.
**Check List**
If `FILTER_PARAMS` were used in a cube's `sql` it would not allow filtering with `or`/`and` filters and would crash at query time because `filtersProxy` was not a method on `BaseGroupFilter`. Now when resolving the FILTER_PARAMS filters any OR/AND filters are able to be added correctly.
=> feat(schema-compiler): Allow filtering with or/and in FILTER_PARAMS.

packages/cubejs-backend-shared/src/env.ts, packages/cubejs-server-core/src/core/server.ts
allowUngroupedWithoutPrimaryKey is an option that is not available to set over the environment variables
I am trying to run the service as a docker and this will help with that
If this name is fine, I can also update the environment variables doc
=> Picking up allowUngroupedWithoutPrimaryKey from env

rust/cubesql/cubesql/src/compile/engine/udf.rs, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__current_schema_postgres.snap, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__explain-3.snap
**Check List**
This PR adds support for `current_schema()` and initial support for `current_schemas(…)` postgres functions.
Additionally, it fixes EXPLAIN queries, enabling them to work with postgres.
=> feat(cubesql): Support current_schema() and current_schemas() postgres functions

rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__show_variable_quoted.snap
**Check List**
This PR fixes processing queries with variable names quoted with SHOW <variable> syntax, such as `SHOW "lc_collate"`.
=> fix(cubesql): Allow quoted variables with SHOW <variable> syntax

docs/content/Configuration/Environment-Variables-Reference.md, rust/cubestore/js-wrapper/src/download.ts
=> feat(cubestore): add CUBEJS_GH_API_TOKEN env var to download script

rust/cubestore/cubestore/src/metastore/mod.rs, rust/cubestore/cubestore/src/store/compaction.rs
`cannot compact inactive partition` error replaced with warning
=> chore(cubestore): Inactive partition compaction: replace error with warn

rust/cubestore/cubestore/src/remotefs/mod.rs, rust/cubestore/cubestore/src/remotefs/s3.rs
**Check List**
#[4131](https://github.com/cube-js/cube.js/issues/4131)
Fix the issue that CubeStore can't find files in AWS S3 if `CUBESTORE_S3_SUB_PATH` is empty
I also covered the `RemoteFS` interface with tests for `LocalDirRemoteFS` and `S3RemoteFS` implementations.
=> fix(cubestore): Work with empty CUBESTORE_S3_SUB_PATH  

rust/cubestore/Cargo.lock, rust/cubestore/cubestore-sql-tests/Cargo.toml, rust/cubestore/cubestore-sql-tests/src/tests.rs, rust/cubestore/cubestore/src/import/mod.rs, rust/cubestore/cubestore/src/sql/mod.rs
**Check List**
Fix of an error with a broken data import if HyperLogLog data is presented in form `02 f6 4a ...` instead of base64 encoded
=> fix(cubestore): Support a space separated binary strings for HyperLogLog fields in csv

packages/cubejs-mssql-driver/driver/MSSqlDriver.js
Add of type uniqueidentifier in packages/cubejs-mssql-driver/driver/MSSqlDriver.js
This fixes a bug while creating preaggregation tables with uniqueidentifier columns for MSSQL.
Error fixed : 
Error during create table: CREATE TABLE dev_pre_aggregations.... : User: Custom type 'uniqueidentifier' is not supported
=> fix: Add uniqueidentifier type support

rust/cubesql/cubesql/src/compile/engine/udf.rs, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__pg_datetime_precision_simple.snap, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__pg_datetime_precision_types.snap, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__pg_get_userbyid_invalid.snap, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__pg_get_userbyid_main.snap, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__pg_numeric_precision_simple.snap, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__pg_numeric_precision_types.snap, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__pg_numeric_scale_simple.snap, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__pg_numeric_scale_types.snap
**Check List**
This PR adds support for the following UDFs:
- information_schema._pg_datetime_precision
- information_schema._pg_numeric_precision
- information_schema._pg_numeric_scale
- pg_get_userbyid
=> feat(cubesql): Support extra information_schema UDFs and pg_get_userbyid

packages/cubejs-backend-native/Cargo.lock, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/analysis.rs, rust/cubesql/cubesql/src/compile/rewrite/converter.rs, rust/cubesql/cubesql/src/compile/rewrite/language.rs, rust/cubesql/cubesql/src/compile/rewrite/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/rewriter.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/dates.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/members.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/split.rs, rust/cubesql/cubesql/src/sql/postgres/extended.rs, rust/cubesql/cubesql/src/transport/ext.rs
=> feat(cubesql): Projection aggregate split to support Tableau casts

packages/cubejs-client-core/src/HttpTransport.js
fix http  subscribe poll not working https://github.com/cube-js/cube.js/issues/3493
=> fix(@cubejs-client/core): fix HTTP poll not working if Cube API stops and recovers

packages/cubejs-client-core/index.d.ts, packages/cubejs-client-core/src/index.js, packages/cubejs-client-react/index.d.ts
**Check List**
#4160
Change the declared types of the core methods that accept a Query to accept a query that has been defined using `as const`. This is a less intrusive change than making the Query type itself deeply readonly.
Also, when the `responseFormat` is `COMPACT`, don't modify the passed queries' `responseFormat`, but rather create a new query. The prior behavior is inconsistent with the new types, and it probably wasn't the best behavior anyway.
=> Accept immutable queries

packages/cubejs-client-core/src/RequestError.js, packages/cubejs-client-core/src/index.js
**Check List**
* https://github.com/cube-js/cube.js/issues/833
This PR adds the status code into the `RequestError` class.
=> Add HTTP status code to RequestError

rust/cubestore/cubestore/src/queryplanner/planning.rs, rust/cubestore/cubestore/src/queryplanner/query_executor.rs, rust/cubestore/cubestore/src/remotefs/mod.rs
**Check List**
* Fixed a bug that required the order of columns in group by to be the same as the order of columns in the index.
* Fixed a bug that made it possible to call MergeSort on unsorted index columns
=> fix(cubestore): Fixed the bug with index selection for different permutations of columns in a group by

packages/cubejs-playground/src/components/GraphQL/GraphiQLSandbox.tsx
**Check List**
None
This PR fixes the bug with the scrolling header in the graphiql explorer.
=> fix(cubejs-playground): fix history header scrolling in graphql explorer

packages/cubejs-client-core/index.d.ts, packages/cubejs-client-react/index.d.ts
**Check List**
#4202
A reimplementation of #4375.
This implementation does not make the `Query` type generic. Instead, it leans entirely on `QueryRecordType`. Although this makes `QueryRecordType` more complex, it's probably easier to follow on the whole, and it's certainly a less intrusive change. This implementation should also produce correct types for time dimensions (e.g. inferring `Foo.createdAt.day`), which was a challenge under the prior PR.
As in the prior PR:
- There are no functional changes, so there are no updates to the tests.
- Only `core` and `react` get the augmented types, since I'm not familiar with the other front-end packages.
- The change should be backward-compatible, *except* that when a narrower type can be inferred, it will be. When no narrower type can be …
=> New implementation of detailed types

packages/cubejs-schema-compiler/src/adapter/PrestodbQuery.js
**Check List**
Athena pre-aggregations refresh uses incompatible date format #4221
Use same iso8601 timestamp function in timestamp cast as in datetime cast, resolving formatting issues in both prestodb and athena
=> fix(prestodb): timestamp cast

packages/cubejs-api-gateway/src/graphql.ts
Fixes: https://github.com/cube-js/cube.js/issues/4399
Please see the discussion on this ticket on why this breaks things.
Currently the actual cubeJS schema does not have nullable types, and assuming all dimensions and measures are non-Nullable is not necessarily correct and blocking the use of the graphQL api entirely for cubes that can return null for dimensions or measures.
I think the ideal solution is to implement nullable types in the actual cubeJS schema so they can be translated 100% correct to a graphQL schema. However that is probably an overall bigger change.
For now, allowing graphQL Member fields to be nullable generates a more useable schema than the current nonNull configuration. (neither are 100% accurate though).
**Check List**
#4399
=> GraphQL: Make dimensions and measures nullable fields.

examples/helm-charts/cubestore/README.md, examples/helm-charts/cubestore/templates/pvc.yaml, examples/helm-charts/cubestore/values.yaml
**Check List**
N/A
Using the default storage class of the AWS EKS cluster (gp2), the default
it is not possible to use the EBS volume for the persistent storage of the
Kubernetes cluster for the persistent volume claim
It should be possible to configure this via values.
The default value for the workersCount must be reduced to 1, because the
ReadWriteOnce volume mode do not support multiple mounts.
=> feat: persistence access mode

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/src/helpers/transformMetaExtended.ts, packages/cubejs-api-gateway/test/helpers/transformMetaExtended.test.ts, packages/cubejs-api-gateway/test/index.test.ts, packages/cubejs-api-gateway/test/mocks.ts, packages/cubejs-server-core/src/core/CompilerApi.js, packages/cubejs-server-core/test/unit/index.test.ts
**Check List**
We need to extend /meta endpoint response with additional data for the schema.
- Add SQL field to cubes / measures / dimensions
- Add "Segments" and "Filters"
- Add "Cases" to dimensions
- Add “Joins”
=> chore: extend meta response for catalog

rust/cubesql/Cargo.lock, rust/cubesql/cubesql/Cargo.toml, rust/cubesql/cubesql/src/compile/mod.rs
**Check List**
This PR bumps `sqlparser-rs` to support `SELECT INTO TABLE tblname` syntax and adds an error gracefully rejecting all `SELECT INTO` queries.
=> fix(cubesql): Reject `SELECT INTO` queries gracefully

packages/cubejs-backend-native/src/channel.rs, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/converter.rs, rust/cubesql/cubesql/src/lib.rs, rust/cubesql/cubesql/src/sql/mysql/service.rs, rust/cubesql/cubesql/src/sql/postgres/shim.rs
=> chore(cubesql): Improve error handling

rust/cubesql/cubesql/e2e/tests/postgres.rs, rust/cubesql/cubesql/e2e/tests/snapshots/e2e__tests__postgres__datepart_quarter.snap, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__date_part_quarter.snap, rust/cubesql/cubesql/src/sql/postgres/pg_type.rs
**Check List**
This PR adds support for `quarter` field in `date_part` SQL function and includes a related test.
=> feat(cubesql): Support `quarter` field in `date_part` SQL function

docs/content/Examples-Tutorials-Recipes/Examples.md, docs/src/pages/index.tsx
Remove info boxes for the "building data apps with Cube" workshop in documentation pages
=> chore(docs): Remove workshop info box

packages/cubejs-cubestore-driver/src/CubeStoreDriver.ts
**Check List**
Wrong order in "create table" for import streaming source. Unique keys should be before indexes.
=> fix(@cubejs-backend/cubestore-driver): Wrong order in "create table" for import streaming source. Unique keys should be before indexes.

rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__pg_truetypid_truetypmod.snap, rust/cubesql/cubesql/src/sql/statement.rs
**Check List**
This PR fixes `UdfWildcardArgReplacer` to iterate over functions nested as function arguments, allowing expressions like `information_schema._pg_numeric_precision(information_schema._pg_truetypid(att.*, ty.*), information_schema._pg_truetypmod(att.*, ty.*))`.
=> chore(cubesql): Iterate UDF wildcard replacer over function arguments

rust/cubesql/Cargo.lock, rust/cubesql/cubesql/Cargo.toml, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__join_where_and_or.snap
**Check List**
This PR bumps `arrow-datafusion` to include a fix for queries with `JOIN` having `AND` + `OR` in `WHERE` returning 0 rows.
It also adds a related test.
=> fix(cubesql): Fix 0 rows result on `JOIN` with `AND` + `OR` in `WHERE`

rust/cubesql/Cargo.lock, rust/cubesql/cubesql/Cargo.toml, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__df_string_boolean_comparison.snap
**Check List**
This PR bumps `arrow-datafusion` to allow comparison between `Utf8` and `Boolean` types, allowing queries like `SELECT TRUE = 't'`. It also adds a related test.
=> feat(cubesql): Support comparison between strings and booleans

rust/cubesql/cubesql/src/sql/postgres/shim.rs, rust/cubesql/pg-srv/src/buffer.rs, rust/cubesql/pg-srv/src/protocol.rs
**Check List**
This PR handles `Flush` pg-wire message, used by Excel Devart extension. As there's no network buffer implemented at the moment, the message is simply ignored instead of throwing an error.
=> fix(cubesql): Handle `Flush` pg-wire message

packages/cubejs-backend-native/Cargo.lock, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/analysis.rs, rust/cubesql/cubesql/src/compile/rewrite/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/members.rs
=> feat(cubesql): PowerBI contains filter support

.github/dependabot.yml
I changed the settings so that the bot only reports essential notifications in the examples.
=> chore(dependabot): example' rules

rust/cubesql/cubesql/src/sql/postgres/shim.rs, rust/cubesql/pg-srv/src/protocol.rs
**Check List**
This PR fixes `pg-wire` protocol to send `Empty Query` message on empty simple query.
=> fix(cubesql): Send `Empty Query` message on empty query

rust/cubesql/cubesql/src/compile/engine/df/scan.rs, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/analysis.rs, rust/cubesql/cubesql/src/compile/rewrite/converter.rs, rust/cubesql/cubesql/src/compile/rewrite/cost.rs, rust/cubesql/cubesql/src/compile/rewrite/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/rewriter.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/members.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/mod.rs, rust/cubesql/cubesql/src/transport/ctx.rs, rust/cubesql/cubesql/src/transport/ext.rs
=> feat(cubesql): PowerBI support for wrapped queries

rust/cubestore/cubestore-sql-tests/src/tests.rs, rust/cubestore/cubestore/src/metastore/mod.rs, rust/cubestore/cubestore/src/metastore/table.rs, rust/cubestore/cubestore/src/queryplanner/planning.rs, rust/cubestore/cubestore/src/sql/mod.rs, rust/cubestore/cubestore/src/store/compaction.rs
**Check List**
Aggregating indexes are used when processing queries. 
It is also the latest PR in the implementation of aggregating indexes in CubeStore side. After merging it, we can merge the features/aggregating_index branch to the master
=> feat(cubestore): Using aggregating indexes in queries

rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/parser.rs, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__sigma_computing_with_subquery_query.snap
**Check List**
This PR contains changes to workaround Sigma Computing query that uses subqueries in `WITH`. It also adds a relevant test.
=> chore(cubesql): Workaround CTEs with subqueries

docs/content/Configuration/Databases/Databricks-JDBC.mdx
=> docs(config): correctly show 'Simple' strategy as default for building pre-aggregations with Databricks

docs/content/Schema/Reference/pre-aggregations.mdx
=> docs(schema): add note about `scheduledRefresh` being unsupported for `rollupJoin` pre-aggregations

rust/cubesql/Cargo.lock, rust/cubesql/cubesql/Cargo.toml
Hello!
In the previous version of the DF when some called `execute_stream` it calls `create_physical_plan` where there was a call to `optimize` which led to a double optimization of the `LogicalPlan`. Right now, we disabled all optimizers excluding built-in optimizers placed in the implementation of LogicalNode (for example JOIN).
Thanks
=> chore(cubesql): Stop optimizing queries twice (on streaming)

packages/cubejs-client-react/src/hooks/is-mounted.js
**Check List**
#4570
Starting in React 18, StrictMode intentionally double-invokes effects (`mount` -> `unmount` -> `mount`) for newly mounted components during development. Because the `isMounted` flag inside the `useIsMounted` hook is only set to true during initialisation, the flag gets set to false immediately during the 'unmount' phase and never gets restored to true. Setting the flag to true in the 'mount' phase restores the correct behaviour.
See: https://github.com/reactwg/react-18/discussions/19
=> fix(client-react): update useIsMounted hook to be compatible with React 18 StrictMode

rust/cubesql/cubesql/e2e/tests/postgres.rs, rust/cubesql/cubesql/src/sql/postgres/extended.rs, rust/cubesql/cubesql/src/sql/postgres/shim.rs, rust/cubesql/pg-srv/src/protocol.rs
Hello!
This functionality is used in the Observable. 
> If Execute terminates before completing the execution of a portal (due to reaching a nonzero result-row count), it will send a PortalSuspended message; the appearance of this message tells the frontend that another Execute should be issued against the same portal to complete the operation. The CommandComplete message indicating completion of the source SQL command is not sent until the portal's execution is completed. Therefore, an Execute phase is always terminated by the appearance of exactly one of these messages: CommandComplete, EmptyQueryResponse (if the portal was created from an empty query string), ErrorResponse, or PortalSuspended.
Thanks
=> fix(cubesql): Correct portal pagination (use PortalSuspended) in pg-wire

packages/cubejs-api-gateway/src/gateway.ts
**Check List**
Otherwise, we send events without request-id and other context payloads.
=> fix(api-gateway): Sending "Incoming network usage" event after context resolver

rust/cubesql/cubesql/e2e/tests/postgres.rs, rust/cubesql/cubesql/src/sql/postgres/shim.rs, rust/cubesql/cubesql/src/sql/types.rs
**Check List**
This PR adds support for `PREPARE` queries, similar to `Parse` packet with a difference of them being sent as a simple query. These are used by Hightouch. A related simple test is also added.
=> feat(cubesql): Support `PREPARE` queries in pg-wire

packages/cubejs-firebolt-driver/src/FireboltQuery.ts, packages/cubejs-firebolt-driver/test/Firebolt.test.ts, packages/cubejs-firebolt-driver/test/FireboltQuery.test.ts, packages/cubejs-testing/birdbox-fixtures/firebolt/schema/Orders.js, packages/cubejs-testing/test/__snapshots__/smoke-firebolt.test.ts.snap, packages/cubejs-testing/test/smoke-firebolt.test.ts, yarn.lock
**Check List**
Firebolt does not support timezone now. 
This PR changes firebolt driver sql generation to not use timezones in `timeStampCast` and `convertTz`
Also changes `timeGroupedColumn` since Firebolt now supports `DATE_TRUNC`
=> fix (firebolt-driver) incorrect firebolt query generation for timestamp conversion

rust/cubesql/cubesql/src/compile/engine/udf.rs, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__pg_total_relation_size.snap
**Check List**
This PR adds `pg_total_relation_size` PostgreSQL UDF stub (used by QuickSight), returning the smallest sane table size. It also adds a related test.
=> feat(cubesql): Support `pg_total_relation_size` UDF

rust/cubesql/cubesql/src/sql/database_variables/postgres/session_vars.rs, rust/cubesql/cubesql/src/sql/postgres/shim.rs
Hello!
This PR fixes a compatibility issue with SQLAlchemy. It's important for Superset/Preset.
Thanks
=> feat(cubesql): Define standard_conforming_strings (Preset compatibility)

packages/cubejs-client-react/src/hooks/cube-query.js, packages/cubejs-playground/src/hooks/is-mounted.ts
This is the same fix as #4740 but applied to the `useCubeQuery` hook. I noticed there is another version of `useIsMounted` in playground as well so I updated that as well.
**Check List**
#4904
=> fix(client-react): update hooks for React 18 StrictMode

packages/cubejs-cli/src/command/deploy.ts
**Check List**
None
Enable an `--directory` option for `cubejs-cli deploy`
```
node ../cube.js/packages/cubejs-cli/dist/src/cli.js deploy --help
Usage: deploy [options]
Deploy project to Cube Cloud
Options:
--upload-env        Upload .env file to CubeCloud
--token <token>     Add auth token to CubeCloud
--directory <path>  Specify path to conf directory (default: "./") 
-h, --help          output usage information
```
Can confirm that I successfully uploaded a config directory using the modified code and it worked as expected:
from within my `packages/cube` directory in an adjacent project:
```
node ../../../cube.js/packages/cubejs-cli/dist/src/cli.js deploy --upload-env --token …
```
=> add --directory option to cubejs-cli

packages/cubejs-client-core/index.d.ts
**Check List**
#5065
The compiler was complaining about:
```ts
type QueryArrayRecordType<T extends DeeplyReadonly<Query[]>> =
T extends readonly [infer First, ...infer Rest]
? SingleQueryRecordType<First> | QueryArrayRecordType<Rest>
: never;
```
`Rest` must be `DeeplyReadonly<Query[]>`, but apparently the compiler isn't inferring that, so it's complaining. This PR adds adds a union that actually does nothing, but give tsc the confidence to succeed.
=> Fix a type inference failure

rust/cubesql/cubesql/e2e/tests/postgres.rs, rust/cubesql/cubesql/src/sql/postgres/shim.rs, rust/cubesql/cubesql/src/sql/types.rs
Hello!
> DEALLOCATE — deallocate a prepared statement
https://www.postgresql.org/docs/current/sql-deallocate.html
Thanks
=> feat(cubesql): Support DEALLOCATE in pg-wire

package.json, packages/cubejs-clickhouse-driver/package.json, packages/cubejs-crate-driver/package.json, packages/cubejs-dbt-schema-extension/package.json, packages/cubejs-dremio-driver/package.json, packages/cubejs-druid-driver/package.json, packages/cubejs-elasticsearch-driver/package.json, packages/cubejs-mysql-aurora-serverless-driver/package.json, packages/cubejs-mysql-driver/package.json, packages/cubejs-prestodb-driver/package.json, packages/cubejs-schema-compiler/package.json, packages/cubejs-testing-shared/package.json, packages/cubejs-testing/package.json, yarn.lock
Hello!
Previously We had a problem with `testcontainers` library (some where there was a bug), and I've locked it to `7.12.1` in https://github.com/cube-js/cube.js/commit/a13b9fb4c8c8ab59e8f9dc5ac78a583d408f5946. The biggest problem with that approach is that some components require 8 or 7 (two different major versions), but resolution resolves it to 7.
Thanks
=> chore: Bump & align testcontainers to ^8.12

packages/cubejs-client-vue3/src/QueryBuilder.js, packages/cubejs-client-vue3/tests/unit/QueryBuilder.spec.js
Signed-off-by: José Luis Di Biase <josx@interorganic.com.ar>
**Check List**
> But for vue3
https://github.com/cube-js/cube.js/issues/2097
https://github.com/cube-js/cube.js/pull/2950
Support for filters containing [boolean logical operators](https://cube.dev/docs/query-format#boolean-logical-operators). Previously, fields and and or were discarded by validatedQuery watcher.
It is based on the last commits on vue cliente regarding this topic:
- https://github.com/cube-js/cube.js/commit/1313dad6a1f4b9da7e6ca194415b1a756e715692
- https://github.com/cube-js/cube.js/commit/8a3bb3dc8e427c30d2ac0cdd504662087dcf1e19
- https://github.com/cube-js/cube.js/commit/904171ee85185f1ba1fcf812ba58ae6bc1 …
=> feat(@cubejs-client/vue3): support logical operator filters (#2950)

packages/cubejs-client-vue3/src/QueryBuilder.js
Signed-off-by: José Luis Di Biase <josx@interorganic.com.ar>
**Check List**
#5084 
Avoid annoying "[Vue warn]: Property "setQuery" was accessed during render but is not defined on instance"
=> fix(@cubejs-client/vue3): avoid setQuery Vue3 warnings (#5084)

rust/cubesql/cubesql/e2e/tests/postgres.rs, rust/cubesql/cubesql/src/error.rs
Before this PR, our error messages which clients saw were with debug information. `fmt::Display` trait should implement human-readable text without debug information.
=> fix(cubesql): Normalize error messsage

.github/workflows/publish.yml, .github/workflows/rust-cubesql.yml
This PR introduce support for @cubejs-backend/native (SQL API) for Node.js 18. In the October 2022, Node.js 18 will be flagged as LTS.
=> feat(cubesql): Support Node.js 18.x

rust/cubesql/cubesql/src/compile/context.rs, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/members.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/split.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/utils.rs
Hello!
Thought Spot uses `qtr` granularity for `DateTrunc` function, which is the same as `quarter`.
Thanks
=> feat(cubesql): Support DateTrunc qtr granularity for analytics queries

packages/cubejs-cubestore-driver/src/CubeStoreDriver.ts
=> fix(@cubejs-backend/cubestore-driver): Aggregate function MERGE not allowed for column type bytes

rust/cubestore/Cargo.lock, rust/cubestore/cubestore-sql-tests/src/tests.rs
This PR bumps Arrow to support casting from timestamp type to string type. https://github.com/cube-js/arrow-rs/commit/6bfc9fb4f038f09f72d41e0aa51929e8e40c4e6f
=> feat(cubestore): Support Cast from timestamp to string

packages/cubejs-cubestore-driver/src/CubeStoreDriver.ts, packages/cubejs-cubestore-driver/src/CubeStoreQuery.ts
Fixed cast to string on count() with unique keys. Also fixed the unique key definition.
=> fix: Wrong cast to string in cubestore driver, UNIQUE KEY brackets missing  

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-schema-compiler/src/compiler/CompileError.ts, packages/cubejs-schema-compiler/src/compiler/ErrorReporter.ts
Introduce `plainError` as an alternative to the error containing code frames
=> chore: plain error messages

rust/cubesql/cubesql/src/compile/engine/udf.rs, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/dates.rs, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__localtimestamp.snap
**Check List**
This PR adds support for `LOCALTIMESTAMP` function, which is currently equivalent to `CURRENT_TIMESTAMP`. It also adds a related test.
=> feat(cubesql): Support `LOCALTIMESTAMP`

packages/cubejs-backend-maven/package.json, packages/cubejs-query-orchestrator/test/unit/QueryOrchestrator.test.js
Right now, We don't use `@cubejs-backend/maven` package. It was a prototype to replace `node-java-maven`. Right now, we don't plan to use this package, but it's a blocker for our CI. Let's disable it for a while before we will back to it. As another problem, it takes a lot of time for the integration tests which downloads packages.
=> chore(ci): Disable testing for @cubejs-backend/maven

rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs
There is a problem with `Filter: True` which we didn't truncate before this PR. Filter node is a limitation for implementation of limit push down through projections for queries which contain `Filter` or `Aggregation` nodes.
=> feat(cubesql): Simplify filter for true literal

.github/workflows/birdbox.yml, .github/workflows/publish.yml, .github/workflows/push.yml, .github/workflows/rust-cubesql.yml
From time to time, there are network issues on GitHub runners. They still didn't fix them, and it's a huge problem to restart jobs everytime.
- Windows: https://github.com/actions/runner-images/issues/5850
- Linux/MacOS: https://github.com/actions/runner-images/issues/5615
=> chore(ci): Retry yarn install on fail (random networks issues)

rust/cubesql/cubesql/src/compile/rewrite/language.rs, rust/cubesql/cubesql/src/compile/rewrite/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/split.rs
This PR allows us to check `DataType` in any place where we want. It allows us to write more safety rules with casting.
=> chore(cubesql): Helpers for checking Arrows's DataType

rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/split.rs
Now we support the following charts:
- gauge
- world cloud
- radar
- kpi
- conversion funnel
- scatter
- bubble
- pie
- piramide
- funnel
- table
=> feat(cubesql): Holistics - support range of charts

docs/content/Cube-Cloud/Developer-Tools/Developer-Playground.md
Cube IDE link links to an unexisting page ("/cloud/cube-ide") rather than "/cloud/dev-tools/cube-ide"
**Check List**
=> docs(cloud): fix broken link in Developer Playground documentation

rust/cubesql/cubesql/src/sql/server_manager.rs
I've implemented these limits to protect possible memory leaks because at the begining, we didn't implement: discard/diallocate/transactions. Right now, it's safe to increase these limits.
- Prepared statements: 128, because some PG clients use the local map to parse statements once, and then it reuses them while a connection is still alive.
- Cursors: 16, because by default it lives inside a transaction. Some clients can use `WITH HOLD` to use it without a transaction.
- Portals: 64, because It's a too large object, and it should be closed after usage. Previously it was 15, but let's give it a try.
=> feat(cubesql): Increase limits for statements/portals/cursors

rust/cubesql/Cargo.lock, rust/cubesql/cubesql/Cargo.toml, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__interval_sum.snap
**Check List**
This PR fixes parser to allow queries with interval sum chaining (e.g. `TO_TIMESTAMP(…) + INTERVAL '…' + INTERVAL '…'`) with PostgreSQL protocol. It also adds a related test.
=> fix(cubesql): Allow interval sum chaining

rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs
**Check List**
This PR allows `WHERE` expressions to filter data from Cube queries by exact year with `WHERE TRUNC(EXTRACT(YEAR FROM column)) = literal_year`. Such queries are used by Tableau. It also adds a related test.
=> feat(cubesql): Allow filter by exact year

rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/utils.rs
**Check List**
This PR adds support for filters where the left side of an expression is a `date_trunc` over a column, the right side is a `date_trunc` with literal expression, the condition between expression is *less than* (`<=`), and granularities match.
Example: `date_trunc('day', column) <= date_trunc('day', literal_date)`
This expression is effectively the same as `column < date_trunc('day', literal_date) + interval '1 day'`.
A special case is considered for *excluding N weeks* expression used by QuickSight.
The PR also contains a fix for `interval_mul` test, fixing `LOCALTIMESTAMP` usage result which made the test break over time.
=> feat(cubesql): Support `date_trunc` over column filter with `<=`

rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/sql/statement.rs
**Check List**
This PR adds support for `float8` and `bool` casts. Those are used by ThoughtSpot. It also fixes an issue when casts written in uppercase or mixed-case (as opposed to lowercase) would not be recognized. ThoughtSpot, for instance, issued `CAST(… AS INT2)` which resulted in an error.
A related test is also added.
=> feat(cubesql): Add `float8`, `bool` casts

rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/split.rs
**Check List**
This PR adds support for `char_length` function to be used when querying cubes. This is used by ThoughtSpot. It also adds a related test.
=> feat(cubesql): Allow `char_length` function to be used with cubes

rust/cubesql/Cargo.lock, rust/cubesql/cubesql/Cargo.toml, rust/cubesql/cubesql/src/compile/mod.rs
**Check List**
This PR bumps `datafusion` in order to fix an issue with derived tables where you could not have a dot in a column alias of a derived table. It also adds a related test with a query used by PowerBI.
=> fix(cubesql): Allow derived tables to have a dot in column name

packages/cubejs-cubestore-driver/src/CubeStoreQuery.ts, packages/cubejs-schema-compiler/src/adapter/BaseFilter.js, packages/cubejs-schema-compiler/src/adapter/BaseQuery.js, packages/cubejs-schema-compiler/src/adapter/PreAggregations.js, packages/cubejs-schema-compiler/src/compiler/CubeEvaluator.js, packages/cubejs-schema-compiler/src/compiler/CubeSymbols.js, packages/cubejs-schema-compiler/src/compiler/CubeValidator.js, packages/cubejs-schema-compiler/src/compiler/DataSchemaCompiler.js, packages/cubejs-schema-compiler/src/compiler/JoinGraph.js, packages/cubejs-schema-compiler/src/compiler/transpilers/CubeCheckDuplicatePropTranspiler.ts, packages/cubejs-schema-compiler/src/compiler/transpilers/CubePropContextTranspiler.ts, packages/cubejs-schema-compiler/test/integration/mysql/mysql-pre-aggregations.test.ts, packages/cubejs-schema-compiler/test/integration/postgres/cube-views.test.ts, packages/cubejs-schema-compiler/test/integration/postgres/dataschema-compiler.test.ts, packages/cubejs-schema-compiler/test/integration/postgres/pre-aggregations.test.ts
=> feat: Cube Views implementation

packages/cubejs-schema-compiler/src/extensions/Funnels.ts
Funnels extension would not properly handle a subquery in the step view definition if it starts with an uppercase SELECT statement
**Check List**
=> fix(extensions): fix SELECT handling in the Funnels extensions

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js, packages/cubejs-schema-compiler/src/compiler/CubeEvaluator.js, packages/cubejs-schema-compiler/test/integration/postgres/cube-views.test.ts
=> fix: Cube not found for path due to FILTER_PARAMS are used in members

packages/cubejs-materialize-driver/package.json, packages/cubejs-materialize-driver/src/MaterializeDriver.ts, yarn.lock
**Check List**
[Reference](https://github.com/cube-js/cube.js/pull/5148)
I had to create another branch due to a local main branch incompatibility (the PR got automatically closed.)
cc. @buntarb 
Newer versions of Materialize have a different way to query the schema.
This PR maintains backward compatibility with older versions too.
Added `semver` lib to calculate the versions.
Added `ramda` lib to keep the same mechanism to return the schema as BaseDriver in `tablesSchema`.
=> fix(materialize-driver) schema inference 

rust/cubesql/cubesql/src/sql/postgres/extended.rs, rust/cubesql/cubesql/src/sql/postgres/shim.rs
Refactoring: Portal requires Prepared Statement as input, but prepared statement can be empty. Before this PR we used workaround with Option, which is not blocker for implementing `pg_catalog.pg_cursors`.
=> refactor(cubesql): Introduce Portal with Empty state

packages/cubejs-mssql-driver/driver/MSSqlDriver.js
Hello!
https://stackoverflow.com/questions/57456939/what-is-the-difference-between-bit-and-boolean-why-we-can-use-boolean-in-sql-s
MSSQL server uses `bit` as an alias for the `boolean` type.
Thanks
=> feat(mssql-driver): Add column type mapping for bit

packages/cubejs-athena-driver/src/AthenaDriver.ts, packages/cubejs-base-driver/src/BaseDriver.ts, packages/cubejs-bigquery-driver/src/BigQueryDriver.ts, packages/cubejs-clickhouse-driver/src/ClickHouseDriver.ts, packages/cubejs-crate-driver/src/CrateDriver.ts, packages/cubejs-databricks-jdbc-driver/src/DatabricksDriver.ts, packages/cubejs-databricks-jdbc-driver/src/index.ts, packages/cubejs-dremio-driver/driver/DremioDriver.js, packages/cubejs-druid-driver/src/DruidDriver.ts, packages/cubejs-elasticsearch-driver/driver/ElasticSearchDriver.js, packages/cubejs-firebolt-driver/src/FireboltDriver.ts, packages/cubejs-hive-driver/driver/HiveDriver.js, packages/cubejs-jdbc-driver/src/JDBCDriver.ts, packages/cubejs-ksql-driver/src/KsqlDriver.ts, packages/cubejs-materialize-driver/src/MaterializeDriver.ts, packages/cubejs-mongobi-driver/src/MongoBIDriver.ts, packages/cubejs-mssql-driver/driver/MSSqlDriver.js, packages/cubejs-mysql-aurora-serverless-driver/driver/AuroraServerlessMySqlDriver.js, packages/cubejs-mysql-driver/src/MySqlDriver.ts, packages/cubejs-oracle-driver/driver/OracleDriver.js, packages/cubejs-postgres-driver/src/PostgresDriver.ts, packages/cubejs-prestodb-driver/driver/PrestoDriver.js, packages/cubejs-questdb-driver/src/QuestDriver.ts, packages/cubejs-redshift-driver/src/RedshiftDriver.ts, packages/cubejs-snowflake-driver/src/SnowflakeDriver.ts, packages/cubejs-sqlite-driver/driver/SqliteDriver.js
=> fix: drivers imports alignment

packages/cubejs-druid-driver/src/DruidQuery.ts, packages/cubejs-druid-driver/test/druid-query.test.ts
**Check List**
[issue 5371](https://github.com/cube-js/cube.js/issues/5371)
`MINUTES` to `MINUTE` replacement
=> fix: ISSUE-5371 DruidQuery timezone MINUTES fix

examples/helm-charts/cubejs/README.md
Not having an understanding of how redis expects URLs to be constructed, it would be helpful to have this note saying that you can't just use the IP or hostname, you have to include the protocol prefix as well.
**Check List**
Just a small README.md addition.
=> docs(examples): add note on how to configure Redis URL in helm chart `README`

rust/cubesql/Cargo.lock, rust/cubesql/cubesql/Cargo.toml, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__test_extract_string_field.snap
**Check List**
This PR introduces a change that allows `EXTRACT` expression to accept date/time fields as strings, e.g. `EXTRACT('year' FROM column)`. PostgreSQL [allows those kinds of strings](https://www.postgresql.org/docs/current/functions-datetime.html#FUNCTIONS-DATETIME-EXTRACT).
It also adds a related test.
=> feat(cubesql): Allow `EXTRACT` field to be parsed as a string

examples/web-analytics/dashboard-app/src/pages/ReportPage.js
Use default daterange in 2020-2021, to avoid showing void data
**Check List**
=> examples: set default daterange to 2020, to show existing stats

packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts, packages/cubejs-query-orchestrator/src/orchestrator/QueryCache.ts
Hello!
I've found a strange moment, that PreAggregation creates a new instance of a CacheDriver instead of using the driver from QueryCache.
Thanks
=> refactor(query-orchestrator): Re-use cacheDriver from QueryCache

rust/cubesql/Cargo.lock, rust/cubesql/cubesql/Cargo.toml, rust/cubesql/cubesql/src/compile/engine/udf.rs, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs, rust/cubesql/cubesql/src/sql/statement.rs
**Check List**
This PR adds support for string filters used by Sigma Computing. `notStartsWith` and `notEndsWith` are currently ignored as those are not supported by Cube. Related tests are included.
=> feat(cubesql): Support Sigma Computing string filters

rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/cost.rs, rust/cubesql/cubesql/src/compile/rewrite/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/members.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/split.rs
**Check List**
This PR introduces rewrites to enable aggregation on top of projection with CubeScan, allowing re-aggregation (DF post-processing). An example use case is to extract `MONTH` with `DatePart` without `GROUP BY` clause.
=> chore(cubesql): Reaggregate CubeScan projections

rust/cubesql/Cargo.lock, rust/cubesql/cubesql/Cargo.toml, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/language.rs, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__test_bool_and_or.snap
**Check List**
This PR bumps cube-js/arrow-datafusion@66fee4a, adding support for `BOOL_AND` and `BOOL_OR` aggregate functions. A related test is included.
=> feat(cubesql): Support `BOOL_AND`, `BOOL_OR` aggregate functions

packages/cubejs-client-core/src/Meta.js
**Check List**
`filterOperatorsForMember` should return operators `startsWith` and `endsWith` for string members
=> fix: cubejs-client - startsWith and endsWith to filterOperatorsForMember

.github/workflows/push.yml, packages/cubejs-prestodb-driver/driver/PrestoDriver.js, packages/cubejs-testing-shared/src/db/index.ts, packages/cubejs-testing-shared/src/db/prestodb.ts, packages/cubejs-testing/birdbox-fixtures/presto/schema/Orders.js, packages/cubejs-testing/birdbox-fixtures/prestodb.yml, packages/cubejs-testing/package.json, packages/cubejs-testing/src/REQUIRED_ENV_VARS.ts, packages/cubejs-testing/src/birdbox.ts, packages/cubejs-testing/test/__snapshots__/smoke-prestodb.test.ts.snap, packages/cubejs-testing/test/smoke-prestodb.test.ts
**Check List**
[ISSUE-5528](https://github.com/cube-js/cube.js/issues/5528)
Same with AthenaDriver hack
=> fix: ISSUE-5528 prestodb - replace double escaping in contain filter

.github/workflows/rust-cubesql.yml, rust/cubesql/Cargo.lock, rust/cubesql/Cargo.toml, rust/cubesql/cubesql/Cargo.toml, rust/cubesql/cubesql/src/compile/engine/udf.rs, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/members.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/split.rs
**Check List**
This PR adds rewrites to support Skyvia date granularities. Related tests are included.
It also contains improvements to reaggregation rules, fixes `char_length` test by adding an alias, and fixes a warning with cargo due to profile not being defined at the workspace root.
Additionally, rewrite engine timeout has been raised from 15 to 30 seconds for one CI check since rewrites in debug mode are much slower.
=> feat(cubesql): Support Skyvia date granularities

rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/converter.rs, rust/cubesql/cubesql/src/compile/rewrite/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/members.rs
**Check List**
This PR fixes an issue with CubeScans missing relations for literal values, which prevented referencing them from outer query. For instance, this query was broken before the proposed fix:
```sql
SELECT t.* FROM (
SELECT "column", 'literal' AS literal
FROM table
) t
```
=> fix(cubesql): Keep CubeScan literal values relation

rust/cubesql/Cargo.lock, rust/cubesql/cubesql/Cargo.toml, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__union_ctes.snap
**Check List**
This PR bumps cube-js/arrow-datafusion@a5ad4c5, fixing an issue with UNION expressions failing to see referenced CTEs. This fixes queries like the one below:
```sql
WITH w AS (SELECT 1 l)
SELECT w.l
FROM w
UNION ALL (SELECT w.l FROM w)
```
=> fix(cubesql): Allow referencing CTEs in UNION

rust/cubestore/cubestore/src/config/mod.rs, rust/cubestore/cubestore/src/metastore/metastore_fs.rs, rust/cubestore/cubestore/src/metastore/mod.rs, rust/cubestore/cubestore/src/metastore/rocks_store.rs, rust/cubestore/cubestore/src/sql/mod.rs, rust/cubestore/cubestore/src/store/compaction.rs, rust/cubestore/cubestore/src/store/mod.rs
Hello!
This PR introduces an initial ability to build a new type of store. In this PR `MetaStore` uses the new API `RocksStore`. Next PR (https://github.com/cube-js/cube.js/pull/5607) will use the same functionality to build `CacheStore`
Thanks
=> refactor(cubestore): Introduce RocksMetaStore via BaseMetaStore

rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/analysis.rs, rust/cubesql/cubesql/src/compile/rewrite/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/members.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/order.rs
**Check List**
This PR fixes an issue with projections not pushing down to CubeScan if any literal members are present. For instance, a simple query like `SELECT dimension, 1 lit FROM cube ORDER BY dimension ASC` would be missing the `order` clause. It also adds a related test.
=> fix(cubesql): Push down projection to CubeScan with literals

rust/cubesql/.gitignore, rust/cubesql/cubesql/src/compile/legacy_compiler.rs, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/parser.rs, rust/cubesql/cubesql/src/compile/qtrace.rs, rust/cubesql/cubesql/src/compile/rewrite/rewriter.rs, rust/cubesql/cubesql/src/compile/test/rewrite_engine.rs, rust/cubesql/cubesql/src/sql/mysql/service.rs, rust/cubesql/cubesql/src/sql/postgres/shim.rs
**Check List**
This PR adds support for a query tracing debug tool which outputs information about the different transformations applied to a query in a machine-readabale JSON format. Use `CUBESQL_DEBUG_QTRACE=true` env to enable. This will output .json files (one per query) in `debug-qtrace` folder.
=> chore(cubesql): Add query trace debug option

rust/cubesql/Cargo.lock, rust/cubesql/cubesql/Cargo.toml, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__like_escape_symbol.snap
**Check List**
This PR fixes an issue with `LIKE` expressions ignoring escape symbols, making it impossible to match literal `_` and `%` symbols. ThoughtSpot, for instance, uses meta queries that match the table name with `LIKE` expression, thus making it impossible to obtain column information for a table without this fix. A related test is also included.
=> fix(cubesql): Fix escape symbols in `LIKE` expressions

rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/sql/statement.rs
**Check List**
This PR fixes an issue with `CAST` expressions with custom names not being available within `HAVING` expressions. Such expressions are used by Thoughtspot. A related test is also added.
=> fix(cubesql): Support `CAST` in `HAVING` clause

rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs
`select * from cube where COLUMN > 0`
in case COLUMN is in a different register than in the cube schema, we caught the error
=> fix(cubesql): normalize column names in filter node

rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/split.rs
**Check List**
This PR adds support for `LEFT` and `RIGHT` post-processing functions to be used in projections. This improves compatibility with Thoughtspot. Test suite is included.
=> feat(cubesql): Support `LEFT`, `RIGHT` in projection

rust/cubesql/cubesql/src/compile/engine/df/scan.rs, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/converter.rs
**Check List**
This PR allows post-processing with JOIN queries when the result of joined Cube requests is below the maximum limit (50000 rows by default, controlled with `CUBEJS_DB_QUERY_LIMIT`). When the limit is reached, an error is thrown if `CUBESQL_FAIL_ON_MAX_LIMIT_HIT` env is `true`. The same error is introduced for large UNION queries to avoid incorrect data due to the limit.
=> feat(cubesql): Allow postprocessing with JOIN below Cube query limit

rust/cubestore/cubestore/src/cachestore/compaction.rs, rust/cubestore/cubestore/src/metastore/rocks_store.rs, rust/cubestore/cubestore/src/metastore/rocks_table.rs
Hello!
Any kind of migration doesn't remove old values from the database; it's why compaction should remove them.
Thanks
=> chore(cubestore): Improve safety on compaction

docs/content/Frontend-Integrations/Dashboard-App.md
Zeit was rebranded to Vercel couple years ago - https://vercel.com/blog/zeit-is-now-vercel
And `now` is deprecated (https://www.npmjs.com/package/now):
=> docs(frontend): update dashboard deploy instructions from deprecated Zeit to Vercel

packages/cubejs-client-core/index.d.ts
**Check List**
Following update for https://github.com/cube-js/cube.js/pull/5836
Hello Cube team 👋 ,
When testing, I was using only the `.seriesNames` and didn't notice that the `.series` method had a separate return type, so I missed adding the `shortTitle` property typing in the Series.
This PR adds this missing type.
Thank you so much for reviewing the other PR, and sorry for the mistake.
I don't think this needs to be merged soon (`seriesNames` is enough on our side), this typing will solve the [other issue](https://github.com/cube-js/cube.js/issues/673) by exposing it correctly though.
=> fix(@cubejs-client/core): add missing Series.shortTitle typing

.github/workflows/publish.yml, .github/workflows/push.yml, .github/workflows/rust-cubesql.yml, packages/cubejs-backend-native/package.json, packages/cubejs-testing/package.json, yarn.lock
Hello!
`@cubejs-backend/native` uses <= NAPI-6 (not Node.js's ABI), which allows us to use a single artifact for each platform-libc.
Thanks
=> feat(cubesql): Support Node.js 18/19

packages/cubejs-client-core/index.d.ts
**Problem**:
type Meta has 2 problems:
- Not having a constructor inside the type.
- Returned data in cubesMap does not match its type
**Solution**
- Added type CubesMap for cubeMap in Meta
- Added constructor to Meta
**Check List**
https://github.com/cube-js/cube.js/issues/5887
=> fix(client-core): Invalid type Meta: not correct type cubesMap, type not have a constructor

rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/utils.rs
**Check List**
This PR adds support for Thoughtspot `startsWith`/`endsWith` expressions using LIKE with ESCAPE symbol (re-encoding). Previously support for a similar expr `contains` was added; the changes here extend the support.
=> feat(cubesql): Support Thoughtspot starts/ends LIKE exprs

rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/split.rs
**Check List**
This PR adds support for `NULLIF` post-processing function in projection.
A related test is included.
=> feat(cubesql): Support `NULLIF` in projection

rust/cubesql/cubesql/src/compile/engine/udf.rs, rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/dates.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/split.rs
**Check List**
This PR adds support for `to_date` expressions in `datediff` functions, used by Thoughtspot. `to_date` itself is a stub and cannot be used, but is effectively rewritten to another function.
A related PR is included.
=> chore(cubesql): Support `to_date` in `datediff`

examples/helm-charts/cubejs/templates/common-env.tpl, examples/helm-charts/cubejs/templates/master/deployment.yaml, examples/helm-charts/cubejs/templates/master/service.yaml, examples/helm-charts/cubejs/values.yaml
**Check List**
-
Helm chart, although had a doc entry for `config.pgSqlPort` doesn't really support it. This PR should add the correct env mapping for that config value
=> Add CUBEJS_PG_SQL_PORT to cubejs helm chart env

examples/helm-charts/cubejs/templates/master/deployment.yaml, examples/helm-charts/cubejs/templates/workers/deployment.yaml, examples/helm-charts/cubestore/templates/router/statefulset.yaml, examples/helm-charts/cubestore/templates/workers/statefulset.yaml
At the moment of writing is not possible to add custom labels to add pod level. This change can be useful cause a lot of 
network policy frameworks like `Cilium` use labels at the pod level to apply a particular rule
=> Helm chart : export commons labels at pod level

packages/cubejs-cubestore-driver/src/CubeStoreCacheDriver.ts, packages/cubejs-query-orchestrator/src/orchestrator/QueryCache.ts, packages/cubejs-query-orchestrator/src/orchestrator/QueryOrchestrator.ts, packages/cubejs-query-orchestrator/test/integration/cubestore/QueryCacheCubestore.test.ts
Hello!
Cube Store is used as the default external database; let's reuse the connection from external driver for caching.
Thanks
=> feat: Re-use connection to Cube Store from externalDriver

rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/dates.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/utils.rs
**Check List**
This PR improves compatibility with Thoughtspot:
- Support `date_trunc` over column and a literal filter (`WHERE DATE_TRUNC('MONTH', time_dimension) </<=/>/>= literal_date`)
- Support double `date_trunc` with double `cast` (`DATE_TRUNC('MONTH', CAST(DATE_TRUNC('MONTH', CAST(time_dimension as TIMESTAMP)) as TIMESTAMP))`)
=> feat(cubesql): Thoughtspot improvements

docs/src/components/CodeTabs/CodeTabs.tsx
https://user-images.githubusercontent.com/827338/211882248-e1ba6f1a-0904-4061-81b1-4747d426ccae.mp4
=> docs: sync selected code lang across all CodeTabs components and all opened docs pages

packages/cubejs-docker/DEVELOPMENT.md, packages/cubejs-docker/dev-alpine.Dockerfile, packages/cubejs-docker/latest-alpine-jdk.Dockerfile, packages/cubejs-docker/latest-alpine.Dockerfile
Hello!
https://github.com/cube-js/cube.js/actions/runs/3890140417/jobs/6639503153
There are no new docker images for Node.js and Alpine 3.14. Let's migrate to 3.15 (as nearest version).
Thanks
=> feat(docker): Alpine - migrate to 3.15 (3.14 was removed)

packages/cubejs-schema-compiler/src/compiler/CubeEvaluator.js, packages/cubejs-testing/birdbox-fixtures/lambda/schema/Orders.js, packages/cubejs-testing/test/smoke-lambda.test.ts
=> fix: Rollups are sorted by name in `rollups` params of pre-aggregations

rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/analysis.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/members.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/split.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/utils.rs
**Check List**
This PR improves compatibility regarding reaggregation:
- Allow unaliased expressions (`SELECT EXTRACT(YEAR FROM column) FROM cube`)
- Avoid direct mapping of values with `SUBSTRING` (except the Metabase case)
=> chore(cubesql): Reaggregation improvements

examples/helm-charts/cubejs/templates/common-env.tpl, examples/helm-charts/cubejs/templates/master/deployment.yaml, examples/helm-charts/cubejs/templates/workers/deployment.yaml, examples/helm-charts/cubejs/values.yaml
Hi,
could you please review this Pr.
With this PR users are enabled to define custom env vars and load env vars from k8s secrets using `envFrom` definition [example](https://kubernetes.io/docs/concepts/configuration/secret/#use-cases.). With this extension is possible to use it in k8s  [configuring-data-sources](https://cube.dev/docs/config/multiple-data-sources#configuring-data-sources-with-environment-variables
)
=> Add possibility to define extra env in helm chart

examples/helm-charts/cubejs/templates/common-env.tpl, examples/helm-charts/cubestore/templates/common-env.tpl
Hi,
please review this PR. Enable char to define 
`CUBEJS_DB_BQ_KEY_FILE` and `CUBESTORE_TELEMETRY` in cubestore chart
=> manage BQkeyFile and CubeStore telemetry

packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts, packages/cubejs-query-orchestrator/src/orchestrator/QueryCache.ts, packages/cubejs-query-orchestrator/src/orchestrator/QueryOrchestrator.ts, packages/cubejs-query-orchestrator/src/orchestrator/QueryQueue.js
=> fix: Re-use external connection for CubeStore in queue

packages/cubejs-cubestore-driver/src/CubeStoreQueueDriver.ts, packages/cubejs-query-orchestrator/test/unit/QueryQueue.abstract.ts, rust/cubestore/cubestore-sql-tests/src/tests.rs, rust/cubestore/cubestore/src/sql/parser.rs
=> feat(cubestore): Support negative priority for queue

rust/cubestore/cubestore-sql-tests/src/tests.rs, rust/cubestore/cubestore/src/cachestore/cache_rocksstore.rs, rust/cubestore/cubestore/src/cachestore/queue_item.rs
=> feat(cubestore): Correct orphaned detection + optimizations

rust/cubesql/cubesql/src/compile/rewrite/rules/split.rs
**Check List**
This PR fixes an inconsistency with Thoughtspot's "day in quarter" expression which should yield numbers starting from 1 (with first day in quarter being 1 and last up to 92) instead of being zero-based as it was before the fix.
=> fix(cubesql): Correct Thoughtspot day in quarter offset

package.json, packages/cubejs-backend-shared/package.json, packages/cubejs-backend-shared/src/index.ts, packages/cubejs-backend-shared/src/process.ts, packages/cubejs-base-driver/src/queue-driver.interface.ts, packages/cubejs-cubestore-driver/src/CubeStoreQueueDriver.ts, packages/cubejs-query-orchestrator/package.json, packages/cubejs-query-orchestrator/src/orchestrator/QueryCache.ts, packages/cubejs-query-orchestrator/src/orchestrator/QueryQueue.js, packages/cubejs-query-orchestrator/src/orchestrator/utils.ts, packages/cubejs-query-orchestrator/test/unit/QueryQueue.abstract.ts, rust/cubestore/cubestore/src/cachestore/cache_rocksstore.rs, rust/cubestore/cubestore/src/cachestore/lazy.rs, rust/cubestore/cubestore/src/cachestore/listener.rs, rust/cubestore/cubestore/src/cachestore/queue_item.rs, rust/cubestore/cubestore/src/sql/mod.rs, rust/cubestore/cubestore/src/sql/parser.rs, yarn.lock
=> feat(cubestore-driver): Support persistent flag for query

rust/cubestore/cubestore/src/config/mod.rs, rust/cubestore/cubestore/src/metastore/mod.rs, rust/cubestore/cubestore/src/sql/mod.rs
=> feat(cubestore): Max disk space limit

packages/cubejs-base-driver/src/queue-driver.interface.ts, packages/cubejs-cubestore-driver/src/CubeStoreQueueDriver.ts, packages/cubejs-query-orchestrator/src/orchestrator/BaseQueueDriver.ts, packages/cubejs-query-orchestrator/src/orchestrator/LocalQueueDriver.js, packages/cubejs-query-orchestrator/src/orchestrator/QueryCache.ts, packages/cubejs-query-orchestrator/src/orchestrator/QueryQueue.js, packages/cubejs-query-orchestrator/src/orchestrator/RedisQueueDriver.js, packages/cubejs-query-orchestrator/src/orchestrator/utils.ts, packages/cubejs-query-orchestrator/test/unit/QueryQueue.abstract.ts, rust/cubestore/cubestore/src/cachestore/cache_rocksstore.rs, yarn.lock
=> fix(cubestore-driver): Cancel handling

rust/cubesql/cubesql/src/compile/engine/df/mod.rs, rust/cubesql/cubesql/src/compile/engine/df/optimizers/filter_push_down.rs, rust/cubesql/cubesql/src/compile/engine/df/optimizers/limit_push_down.rs, rust/cubesql/cubesql/src/compile/engine/df/optimizers/mod.rs, rust/cubesql/cubesql/src/compile/engine/df/optimizers/sort_push_down.rs, rust/cubesql/cubesql/src/compile/engine/df/optimizers/utils.rs, rust/cubesql/cubesql/src/compile/mod.rs
**Check List**
This PR adds optimizers to push down `Filter`, `Sort`, and `Limit` in logical plan. This benefits queries with CubeScan that have projections with post-processing. Related tests are included.
=> chore(cubesql): Push down `WHERE`, `ORDER`, `LIMIT`

packages/cubejs-hive-driver/README.md
In installation using docker there was a missing step of Downloading the TCLIService.thrift file
**Check List**
- [-] Tests has been run in packages where changes made if available
- [-] Linter has been run for changed code
- [-] Tests for the changes have been added if not covered yet
- [V] Docs have been added / updated if required
---------
missing step added
=> Add missing step in Docker installation

docs/content/SQL-API/SQL-Functions-and-Operators.mdx
Fixed two small typos with regards to the "not equal" operator.
**Check List**
=> docs(sql): fix incorrect "Not Equals" example and description

docs/content/Cube-Cloud/Getting-Started/Create-new.mdx, docs/content/Cube-Cloud/Getting-Started/Import-Bitbucket-repository-via-SSH.mdx, docs/content/Cube-Cloud/Getting-Started/Import-Git-repository-via-SSH.mdx, docs/content/Cube-Cloud/Getting-Started/Import-GitHub-repository.mdx, docs/content/Cube-Cloud/Getting-Started/Import-GitLab-repository-via-SSH.mdx, docs/content/Cube-Cloud/Getting-Started/Upload-with-CLI.mdx
[`Connecting to the Database`](https://cube.dev/docs/cloud/configuration/connecting-to-the-database) page was moved from `/cloud/configuration/connecting-to-databases` to `/cloud/configuration/connecting-to-the-database`, but we had some references to the old url, causing 404 errors
https://github.com/cube-js/cube.js/blob/master/docs/content/Cube-Cloud/Configuration/Connecting-to-Databases.mdx?plain=1#L6-L7
=> docs: fix connect to db link refereneces

.github/workflows/publish.yml, .github/workflows/push.yml, packages/cubejs-docker/latest-alpine-jdk.Dockerfile, packages/cubejs-docker/latest-alpine.Dockerfile, packages/cubejs-docker/latest-debian-jdk.Dockerfile, packages/cubejs-docker/latest.Dockerfile, packages/cubejs-docker/local.Dockerfile
=> chore(ci): Trying to fix release with workaround for yarn v1

packages/cubejs-redshift-driver/src/RedshiftDriver.ts
**Check List**
#6023
Referenced changes made to Athena driver in [PR 4183](https://github.com/cube-js/cube.js/pull/4183) and updated the unload query in the Redshift driver to match.
=> fix(redshift-driver): fixes column order

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/test/index.test.ts
Hello!
```js
export default {
extendContext: (req) => {
throw new Error("Should not crash");
},
};
```
Thanks
=> fix: Catch exception from extendContext (unhandledRejection)

packages/cubejs-backend-native/src/transport.rs
Hello!
The root cause is a non-blocking STDOUT set by the Node.js at startup. I don't think that it's a correct idea to set up O_NONBLOCK for STDOUT, let's hide some trace logs as a workaround for this issue. 
Thanks!
=> fix(cubesql): Failed printing to stdout: Resource temporarily unavailable

packages/cubejs-server-core/src/core/optionsValidate.ts
=> fix: Allow to specify cubestore as cacheAndQueueDriver by config

rust/cubestore/cubestore/src/lib.rs, rust/cubestore/cubestore/src/metastore/rocks_store.rs
Hello!
Issue: Single panic in the rw loop can break the whole processing
```
mysql> cache get “1”;
ERROR 1815 (HY000): channel closed
mysql> cache set “1" “1”;
ERROR 1815 (HY000): channel closed
```
Thanks
=> feat(cubestore): RocksStore - panic protection for RW loop

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js, packages/cubejs-schema-compiler/src/adapter/index.ts, packages/cubejs-schema-compiler/src/compiler/CompilerCache.ts, packages/cubejs-schema-compiler/src/compiler/CubeEvaluator.js, packages/cubejs-schema-compiler/src/compiler/CubeValidator.js, packages/cubejs-schema-compiler/src/compiler/DataSchemaCompiler.js, packages/cubejs-schema-compiler/src/compiler/YamlCompiler.ts, packages/cubejs-schema-compiler/src/compiler/transpilers/CubePropContextTranspiler.ts, packages/cubejs-schema-compiler/test/unit/base-query.test.ts, packages/cubejs-schema-compiler/test/unit/cube-validator.test.ts, packages/cubejs-schema-compiler/test/unit/pre-aggregations.test.ts, packages/cubejs-schema-compiler/test/unit/utils.ts
Hello!
This PR introduces syntax sugar. Instead of writing `sql: 'SELECT * FROM my_table'`, you can do `sqlTable: 'my_table'`.
Thanks
=> feat(schema): Introduce support for sqlTable

yarn.lock
Hello!
Vulnerabilities in this depends didn't affect us but let's upgrade them to skip false positive alarms.
- https://dso.docker.com/cve/CVE-2022-31129
- https://dso.docker.com/cve/CVE-2022-24785
- https://dso.docker.com/cve/GHSA-56x4-j7p9-fcf9
Thanks
=> fix(deps): Upgrade moment, moment-timezone, refs #6340

docs/content/Configuration/Advanced/Multitenancy.mdx, docs/content/Deployment/Overview.mdx, docs/content/Deployment/Platform-Cube-Cloud.mdx, docs/content/Deployment/Platform-Docker.mdx
Please see the commit messages.
=> docs(deployment): add Redis notice to Overview

rust/cubesql/cubesql/src/compile/mod.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs, rust/cubesql/cubesql/src/compile/rewrite/rules/utils.rs
**Check List**
This PR adds support for `date_trunc(granularity, time_dimension) = literal_date` filter expressions, such as `WHERE DATE_TRUNC('week', "pickupDate") = str_to_date('2022-11-14 00:00:00.000000', 'YYYY-MM-DD HH24:MI:[SS.US]')`.
A related test is included.
=> feat(cubesql): Support `date_trunc = literal date` filter

rust/cubestore/Cargo.lock, rust/cubestore/cubestore-sql-tests/src/benches.rs, rust/cubestore/cubestore/Cargo.toml, rust/cubestore/cubestore/src/app_metrics.rs, rust/cubestore/cubestore/src/config/mod.rs, rust/cubestore/cubestore/src/metastore/mod.rs, rust/cubestore/cubestore/src/sql/cache.rs, rust/cubestore/cubestore/src/sql/mod.rs, rust/cubestore/cubestore/src/store/mod.rs, rust/cubestore/cubestore/src/table/mod.rs, rust/cubestore/cubestore/src/util/decimal.rs
Hello!
The first implementation of Query Cache was based on a simple LRU, which doesn't provide flexibility for configuration. In this PR I've introduced a new Query Cache on top of `moka` crate, that allows making limits on capacity/time to idle.
Thanks
=> feat(cubestore): Query cache - limits by time_to_idle/max_capacity

packages/cubejs-duckdb-driver/src/DuckDBQuery.ts, packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
=> feat(duckdb-driver): Support countDistinctApprox

packages/cubejs-api-gateway/src/gateway.ts, packages/cubejs-api-gateway/src/interfaces.ts, packages/cubejs-api-gateway/src/types/auth.ts, packages/cubejs-api-gateway/src/types/gateway.ts, packages/cubejs-api-gateway/src/types/strings.ts, packages/cubejs-api-gateway/test/permissions.test.ts, packages/cubejs-backend-shared/src/env.ts, packages/cubejs-server-core/src/core/optionsValidate.ts, packages/cubejs-server-core/src/core/server.ts, packages/cubejs-server-core/src/core/types.ts, packages/cubejs-server-core/test/unit/OptsHandler.test.ts, packages/cubejs-testing/birdbox-fixtures/lambda/cube.js
=> feat(api-gateway, server-core): Renamed Permissions to ApiScopes

packages/cubejs-base-driver/src/BaseDriver.ts, packages/cubejs-mongobi-driver/package.json, packages/cubejs-mongobi-driver/src/MongoBIDriver.ts, packages/cubejs-prestodb-driver/src/PrestoDriver.ts, yarn.lock
=> chore(base-driver): Use TLS.ConnectionOptions for SSL configuration

docs/content/Configuration/Advanced/Multitenancy.mdx, docs/content/Examples-Tutorials-Recipes/Recipes/using-different-schemas-for-tenants.mdx, docs/content/Reference/Configuration/Config.mdx
Updates the imports in docs as follows:
```js
const { FileRepository } = require('@cubejs-backend/server-core');
```
=> docs: Update import for FileRepository

docs/content/Reference/Configuration/Config.mdx
Updates documentation to show that `continueWaitTimeout` should be defined under `OrchestratorOptions `.
Additionally, adds `rollupOnlyMode` to `OrchestratorOptions` where it was missing.
=> docs: Move `continueWaitTimeout` to `OrchestratorOptions`

docs/content/Reference/CLI/CLI-Reference.mdx
We should not assume that `cubejs` is installed locally, so it's safer to use `npx cubejs-cli` in docs.
=> docs: Replace `cubejs` with `npx cubejs-cli`

docs/content/Configuration/Overview.mdx, docs/content/REST-API/REST-API.mdx
CORS configuration is irrelevant to the high-level configuration overview and should be placed under the REST API section.
=> docs: Move CORS configuration to the REST API page

docs/content/Getting-Started/Core/01-Overview.mdx
https://cube.dev/docs/getting-started/docker has moved to https://cube.dev/docs/getting-started/core/overview.
=> docs: Add missing redirect
