docs/content/Examples-Tutorials-Recipes/Recipes/pagination.mdx
docs/content/REST-API/Query-Format.mdx
docs/content/Reference/GraphQL-API/GraphQL-API.mdx
docs/content/SQL-API/Overview.mdx

The pagination recipe provides a workaround for the 50,000 row limit.

docs: Reference the pagination recipe from the mentions of the 50,000 row limit

---

docs/content/Deployment/Production-Checklist.mdx

Example of setting `--max-old-space-size`.

docs: Clarify how Node.js heap size limit can be set

---

rust/cubesql/cubesql/src/compile/engine/udf.rs
rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__psql_list.snap

**Check List**
This PR adds support for psql's `\list` command. New functions supported as part of this PR are `pg_encoding_to_char` and `array_to_string`. A related test is included.

feat(cubesql): Support psql's `\list` command

---

packages/cubejs-firebolt-driver/src/FireboltQuery.ts
packages/cubejs-firebolt-driver/test/FireboltQuery.test.ts

**Check List**
Cube.js by default generate sql that is not supported by firebolt yet. (compare boolean column with "true", "false" string values)
This pr will fix issue with queries such as `select * from a_table where a_boolean = "true"`  by casting boolean parameters using `cast` syntax

fix (firebolt-driver) cast boolean params

---

rust/cubestore/cubestore-sql-tests/src/tests.rs
rust/cubestore/cubestore/src/cachestore/cache_rocksstore.rs
rust/cubestore/cubestore/src/cachestore/lazy.rs
rust/cubestore/cubestore/src/queryplanner/test_utils.rs
rust/cubestore/cubestore/src/sql/cachestore.rs
rust/cubestore/cubestore/src/sql/parser.rs

Hello!
This PR introduces support for doing `HEARTBEAT` and `MERGE_EXRA` with `id` to protect race conditions.
Thanks

feat(cubestore): Queue - allow to do merge_extra, heartbeat by processingId

---

packages/cubejs-databricks-jdbc-driver/src/DatabricksDriver.ts

This aims to solve #6197. The `package.json` file is removed during image build, so the version is never actually used. However, in case there is an exception while connecting to Databricks, the actual exception will be hidden with the error related to this instead. This makes debugging Databricks connection issues impossible.

Remove package.json dependency from DatabricksDriver.ts

---

rust/cubestore/cubestore/src/config/mod.rs
rust/cubestore/cubestore/src/remotefs/gcs.rs
rust/cubestore/cubestore/src/remotefs/queue.rs
rust/cubestore/cubestore/src/remotefs/s3.rs

chore(cubestore): Tuning local files cleanup

---

packages/cubejs-api-gateway/src/gateway.ts
packages/cubejs-api-gateway/src/query.js
packages/cubejs-api-gateway/src/types/query.ts
packages/cubejs-api-gateway/test/index.test.ts

fix: Limit override isn't respected in queryRewrite

---

docs/content/Getting-Started/Overview.mdx

We can add a link to "Architecture" later when we have it.

docs: A one-liner about how Cube is packaged

---

packages/cubejs-cli/src/templates.ts

JavaScript models can still be generated with the `docker-js` template.

chore(cubejs-cli): update `docker` template to use YAML files by default

---

.github/workflows/cloud.yml
.github/workflows/publish.yml
.github/workflows/push.yml
.github/workflows/rust-cubesql.yml

Hello!
GitHub allows storing only 10GB for cache, which is insufficient for a separate cache per Node.js versions. This PR drops a separate cache and uses only the global cache from the yarn directory.
Thanks

chore(ci): Use global yarn cache only (reduce cache usage)

---

rust/cubesql/Cargo.lock
rust/cubesql/cubesql/Cargo.toml
rust/cubesql/cubesql/src/compile/engine/df/scan.rs
rust/cubesql/cubesql/src/compile/engine/udf.rs
rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/language.rs
rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__current_date.snap

**Check List**
This PR bumps cube-js/arrow-datafusion@104887f, adding support for `CURRENT_DATE` scalar function. Related tests are included.

feat(cubesql): Support `CURRENT_DATE` scalar function

---

.github/actions/smoke.sh
.github/workflows/push.yml
packages/cubejs-athena-driver/test/AthenaDriver.test.ts
packages/cubejs-jdbc-driver/package.json
packages/cubejs-jdbc-driver/src/JDBCDriver.ts
packages/cubejs-schema-compiler/src/compiler/YamlCompiler.ts
packages/cubejs-testing-drivers/fixtures/athena.json
packages/cubejs-testing-drivers/fixtures/bigquery.json
packages/cubejs-testing-drivers/fixtures/clickhouse.json
packages/cubejs-testing-drivers/fixtures/mssql.json
packages/cubejs-testing-drivers/fixtures/mysql.json
packages/cubejs-testing-drivers/fixtures/postgres.json
packages/cubejs-testing-drivers/fixtures/snowflake.json
packages/cubejs-testing-drivers/src/tests/testQueries.ts
packages/cubejs-testing-drivers/test/__snapshots__/databricks-jdbc-full.test.ts.snap
packages/cubejs-testing-shared/src/db/oracle.ts
packages/cubejs-testing/test/smoke-oracle.test.ts
yarn.lock

fix(databricks-jdbc-driver): Return NULL decimal as NULL instead of 0

---

rust/cubestore/cubestore/src/cluster/mod.rs
rust/cubestore/cubestore/src/cluster/rate_limiter.rs
rust/cubestore/cubestore/src/config/mod.rs
rust/cubestore/cubestore/src/import/mod.rs
rust/cubestore/cubestore/src/queryplanner/mod.rs
rust/cubestore/cubestore/src/queryplanner/optimizations/mod.rs
rust/cubestore/cubestore/src/queryplanner/optimizations/trace_data_loaded.rs
rust/cubestore/cubestore/src/queryplanner/query_executor.rs
rust/cubestore/cubestore/src/queryplanner/trace_data_loaded.rs
rust/cubestore/cubestore/src/sql/mod.rs
rust/cubestore/cubestore/src/store/compaction.rs
rust/cubestore/cubestore/src/store/mod.rs
rust/cubestore/cubestore/src/util/batch_memory.rs
rust/cubestore/cubestore/src/util/mod.rs

feat(cubestore): Tracking data amount using in processing

---

rust/cubestore/cubestore/src/queryplanner/partition_filter.rs

fix(cubestore): Missing filter in the middle of an index prunes unnecessary partitions

---

rust/cubesql/Cargo.lock
rust/cubesql/cubesql/Cargo.toml
rust/cubesql/cubesql/e2e/tests/postgres.rs

**Check List**
This PR bumps cube-js/sqlparser-rs@b098e2d, adding support for setting several values in `SET`, comma-separated, e.g. `SET a = b, c`.
One case where this is problematic is `SET search_path = public, other_schema` with PostgreSQL. Such a query is issued, for instance, by DBeaver.

feat(cubesql): Support multiple values in `SET`

---

rust/cubesql/Cargo.lock
rust/cubesql/cubesql/Cargo.toml
rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__holistics_date_trunc_date32.snap

**Check List**
This PR bumps cube-js/arrow-datafusion@915a600, adding support for `Date32` to `TimestampNanosecond` coercion. This is in line with PostgreSQL.
This improves compatibility with Holistics, which issues this query where `DATE` is passed directly to `DATE_TRUNC`:
```sql
with "h__dates" AS (
SELECT
CAST ('2023-02-01' AS date) as "start_range",
CAST ( '2023-02-28' AS date ) as "end_range",
28 as "length"
)
SELECT
DATE_TRUNC( 'month', "start_range") AS "dm_ddt_d_6e2110",
MAX("length") AS "h_dates_length"
FROM "h__dates"
GROUP BY 1
;
```

feat(cubesql): Support `Date32` to `Timestamp` coercion

---

rust/cubesql/cubesql/src/compile/engine/udf.rs
rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__zoho_inet_server_addr.snap

**Check List**
This PR adds support for `inet_server_addr` function stub, returning `127.0.0.1/32` as a valid value.
This function is used by Zoho Analytics. Related test is included.
Note that the function returns `Utf8` type. In accordance with PostgreSQL, it should return `inet` type but we do not support that; this is mitigated by the fact that the function call is directly cast to the `text` type within the query.

feat(cubesql): Support `inet_server_addr` stub

---

packages/cubejs-backend-native/src/python/cross.rs
packages/cubejs-backend-native/src/python/template/mj_value.rs
packages/cubejs-backend-native/test/__snapshots__/jinja.test.ts.snap
packages/cubejs-backend-native/test/jinja.test.ts
packages/cubejs-backend-native/test/templates/arguments-test.yml.jinja
packages/cubejs-backend-native/test/templates/scoped-utils.py
packages/cubejs-backend-native/test/templates/utils.py

feat(native): Python / Jinja - support Tuple

---

packages/cubejs-schema-compiler/src/compiler/YamlCompiler.ts
packages/cubejs-schema-compiler/test/unit/yaml-schema.test.ts

Hello!
refs https://github.com/cube-js/cube/issues/7033
Thanks

fix(schema-compiler): YAML - crash on unammed measure/dimension/join

---

rust/cubestore/Cargo.lock
rust/cubestore/cubestore-sql-tests/src/tests.rs

fix(cubestore): Escape regex symbols in all versions of like operator

---

packages/cubejs-databricks-jdbc-driver/src/DatabricksDriver.ts
packages/cubejs-databricks-jdbc-driver/src/helpers.ts
packages/cubejs-testing-drivers/src/tests/testIncrementalSchemaLoading.ts

We can not connect to Databricks by using the JDBC URL they provide.
To fix this, users [have to add](https://github.com/cube-js/cube/issues/6197#issuecomment-1690843865) `UID=token`.
This happens because the driver is trying to use a user/password mechanism to authenticate instead of a token in the URL because we're explicitly passing the params to `getConnection()` (PWD).
https://github.com/cube-js/cube/blob/master/packages/cubejs-jdbc-driver/src/JDBCDriver.ts#L140

fix(databricks-jdbc-driver): ensure default UID property is set

---

packages/cubejs-backend-native/python/cube/src/__init__.py
packages/cubejs-backend-native/src/python/entry.rs
packages/cubejs-backend-native/test/templates/jinja-instance.py

feat(python): Support `@template.function("name")` definitions

---

packages/cubejs-backend-shared/src/env.ts
packages/cubejs-duckdb-driver/src/DuckDBDriver.ts

**Expected Behaviour:**
when connecting to Motherduck and going through the data model wizard, the “Select Tables” page should show the database > schema > table hierarchy.  It should then create the cubes with sql_table: database.schema.table
**Actual Behaviour:**
the database level is missing from the data model wizard, so schemas from all databases are grouped together.  The database is also missing from the generated cube definitions, displaying as sql_table: schema.table

fix(duckdb-driver): allow setting default schema

---

packages/cubejs-playground/src/pages/FrontendIntegrations/FrontendIntegrationsPage.tsx

**Check List**
GraphQL endpoint has been incorrect here for a while.
Removed the `/v1` in front of `/graphql` so we render the correct endpoint.

fix: Correct GraphQL endpoint displayed on front-end

---

packages/cubejs-client-core/src/index.js
packages/cubejs-client-react/index.d.ts
packages/cubejs-client-react/src/CubeProvider.jsx
packages/cubejs-client-react/src/hooks/cube-fetch.js
packages/cubejs-client-react/src/hooks/cube-query.js

`cubejsApi` is deprecated in favor of `cubeApi` and will be removed in the following versions

chore: deprecate cubejsApi prop in favor of cubeApi

---

packages/cubejs-schema-compiler/src/compiler/CubeSymbols.js
packages/cubejs-schema-compiler/src/compiler/CubeValidator.js
packages/cubejs-schema-compiler/test/integration/postgres/cube-views.test.ts

feat: Split view support

---

packages/cubejs-cli/src/command/create.ts
packages/cubejs-jdbc-driver/src/JDBCDriver.ts

Addressed an issue where the JDBC driver, utilizing the `node-java-maven` library, attempted to read a `package.json` file in the YAML deployment template directory. As this file was absent, queries failed to execute. The fix involves specifying the path to a valid `package.json` file using the `packageJsonPath` option in `node-java-maven`.

fix(jdbc-driver): node-java-maven package.json path issue

---

packages/cubejs-duckdb-driver/src/DuckDBDriver.ts

There is a change on DuckDB's side, so previously `SET schema=<value>` worked for `information_schema` queries.
Now, we need the combination of `SET` and `WHERE` clause.
- `WHERE` clause will narrow the list of returned schemas
- `SET` will allow using these tables without referencing the catalog to resolve ambiguity.
> There is confusion with the param naming on DuckDB's side. While the param is called `schema` in [docs](https://duckdb.org/docs/archive/0.9.1/sql/configuration), when you issue `SET schema=<value>` it sets the **catalog**.

fix(duckdb-driver): use schema param in information_schema queries

---

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-schema-compiler/src/adapter/RedshiftQuery.js

**Check List**
This PR adds SQL push down support for `COVAR_POP` and `COVAR_SAMP` aggregation functions, with the exception of Redshift which lacks support for these.

feat(cubesql): Enable `COVAR` aggr functions push down

---

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
rust/cubesql/cubesql/src/compile/engine/df/wrapper.rs
rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/wrapper/in_list_expr.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/wrapper/mod.rs
rust/cubesql/cubesql/src/compile/test/mod.rs
rust/cubesql/cubesql/src/transport/service.rs

**Check List**
This PR adds SQL push down support for `[NOT] IN` expression. Related test is included.

feat(cubesql): Support `[NOT] IN` SQL push down

---

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
rust/cubesql/cubesql/src/compile/engine/df/wrapper.rs
rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/wrapper/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/wrapper/negative_expr.rs
rust/cubesql/cubesql/src/compile/test/mod.rs
rust/cubesql/cubesql/src/transport/service.rs

**Check List**
This PR adds SQL push down support for `-` (unary minus) operator. Related test is included.

feat(cubesql): Support `-` (unary minus) SQL push down

---

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
rust/cubesql/cubesql/src/compile/engine/df/wrapper.rs
rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/wrapper/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/wrapper/not_expr.rs
rust/cubesql/cubesql/src/compile/test/mod.rs
rust/cubesql/cubesql/src/transport/service.rs

**Check List**
This PR adds SQL push down support for `NOT` operator. Related test is included.

feat(cubesql): Support `NOT` SQL push down

---

packages/cubejs-schema-compiler/src/adapter/AWSElasticSearchQuery.ts
packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-schema-compiler/src/adapter/BigqueryQuery.ts
packages/cubejs-schema-compiler/src/adapter/ClickHouseQuery.ts
packages/cubejs-schema-compiler/src/adapter/CrateQuery.ts
packages/cubejs-schema-compiler/src/adapter/ElasticSearchQuery.ts
packages/cubejs-schema-compiler/src/adapter/HiveQuery.ts
packages/cubejs-schema-compiler/src/adapter/MongoBiQuery.ts
packages/cubejs-schema-compiler/src/adapter/MssqlQuery.ts
packages/cubejs-schema-compiler/src/adapter/MysqlQuery.ts
packages/cubejs-schema-compiler/src/adapter/OracleQuery.ts
packages/cubejs-schema-compiler/src/adapter/PostgresQuery.ts
packages/cubejs-schema-compiler/src/adapter/PrestodbQuery.ts
packages/cubejs-schema-compiler/src/adapter/RedshiftQuery.ts
packages/cubejs-schema-compiler/src/adapter/SnowflakeQuery.ts
packages/cubejs-schema-compiler/src/adapter/SqliteQuery.ts
packages/cubejs-schema-compiler/src/adapter/VerticaQuery.ts

refactor(schema-compiler): Migrate dialects to TypeScript

---

packages/cubejs-databricks-jdbc-driver/src/DatabricksQuery.ts
packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-schema-compiler/src/adapter/BigqueryQuery.ts
packages/cubejs-schema-compiler/src/adapter/PostgresQuery.ts
packages/cubejs-schema-compiler/src/adapter/RedshiftQuery.ts
packages/cubejs-schema-compiler/src/adapter/SnowflakeQuery.ts
rust/cubesql/cubesql/src/compile/engine/df/wrapper.rs
rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/test/mod.rs
rust/cubesql/cubesql/src/transport/service.rs

**Check List**
This PR adds SQL push down support for these functions:
- `ASCII`
- `ATAN2`
- `BTRIM`
- `CHAR_LENGTH`
- `COT`
- `DATEDIFF`
- `DEGREES`
- `LTRIM`
- `RADIANS`
- `REPLACE`
- `RTRIM`
- `SIGN`
- `STRPOS`
- `TO_CHAR`
It also fixes an issue with pushing down `DLOG10` in Redshift.

feat(cubesql): Support SQL push down for several functions

---

packages/cubejs-backend-native/Cargo.lock
rust/cubesql/Cargo.lock
rust/cubesql/cubesql/Cargo.toml
rust/cubesql/cubesql/src/compile/engine/udf.rs
rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/analysis.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/dates.rs
rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__test_string_multiply_interval.snap

**Check List**
This PR adds support for `Utf8 * Interval` (and vice versa) expressions, mainly to support `NULL * INTERVAL '…'` expressions. It also fixes with `date_add`/`date_sub` functions where adding a `NULL` interval would not yield `NULL`. Related tests are included.

feat(cubesql): Support `Utf8 * Interval` expression

---

package.json
packages/cubejs-athena-driver/package.json
packages/cubejs-base-driver/package.json
packages/cubejs-bigquery-driver/package.json
packages/cubejs-cli/package.json
packages/cubejs-client-dx/package.json
packages/cubejs-client-vue/jest.config.js
packages/cubejs-client-vue/package.json
packages/cubejs-client-vue3/jest.config.js
packages/cubejs-client-vue3/package.json
packages/cubejs-crate-driver/package.json
packages/cubejs-dremio-driver/package.json
packages/cubejs-duckdb-driver/package.json
packages/cubejs-firebolt-driver/package.json
packages/cubejs-hive-driver/package.json
packages/cubejs-ksql-driver/package.json
packages/cubejs-materialize-driver/package.json
packages/cubejs-mongobi-driver/package.json
packages/cubejs-mssql-driver/package.json
packages/cubejs-mysql-aurora-serverless-driver/package.json
packages/cubejs-oracle-driver/package.json
packages/cubejs-postgres-driver/package.json
packages/cubejs-prestodb-driver/package.json
packages/cubejs-query-orchestrator/package.json
packages/cubejs-query-orchestrator/test/unit/QueryQueue.abstract.ts
packages/cubejs-questdb-driver/package.json
packages/cubejs-redshift-driver/package.json
yarn.lock

chore(@cubejs-client/vue2/3): Bump tooling (to remove deasync for dev)

---

packages/cubejs-duckdb-driver/src/DuckDBDriver.ts

feat(duckdb-driver): Declare user agent information

---

packages/cubejs-api-gateway/src/gateway.ts

fix(api-gateway): Fallback to global error middelware for async handlers

---

packages/cubejs-api-gateway/src/gateway.ts
packages/cubejs-api-gateway/test/permissions.test.ts

fix(api-gateway): Catch error from contextToApiScopes

---

packages/cubejs-dremio-driver/driver/DremioQuery.js

**Check List**
Conversation in Slack: https://cube-js.slack.com/archives/C04KDTE2EF7/p1701944283139919
Dremio docs:
* https://docs.dremio.com/cloud/reference/sql/sql-functions/functions/TO_TIMESTAMP/
* https://docs.dremio.com/cloud/reference/sql/sql-functions/DATE_TIME/#datetime-formatting

fix(cubejs-dremio-driver): Change TIMESTAMP to TO_TIMESTAMP

---

docs/pages/guides/designing-metrics.mdx

docs: Add details on Designing for metrics

---

packages/cubejs-client-ngx/package.json

fesm5 is no longer supported by angular package format
**Check List**
Closes #7570

fix(@cubejs-client/ngx): set module to fesm2015

---

packages/cubejs-backend-native/Cargo.lock
packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
rust/cubesql/Cargo.lock
rust/cubesql/cubesql/Cargo.toml
rust/cubesql/cubesql/src/compile/engine/df/scan.rs
rust/cubesql/cubesql/src/compile/engine/df/wrapper.rs
rust/cubesql/cubesql/src/compile/engine/udf.rs
rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs
rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__domo_group_date_by_month.snap
rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__test_cast_string_to_interval.snap
rust/cubesql/cubesql/src/compile/test/mod.rs
rust/cubesql/cubesql/src/sql/dataframe.rs

**Check List**
This PR improves compatibility with Domo, list of included changes:
- Added `Mon` format string to `to_char` function
- Added `Utf8` to `Interval` casting support
- Added `TimestampMillisecond` output support
- Push down `DATE` function
- Fix `ORDER BY` remapping with an expression that is equal to a projection expression with an alias containing uppercase letters
- Support parsing date with zeroed time as `Date32` value

feat(cubesql): Support Domo data queries

---

packages/cubejs-base-driver/src/queue-driver.interface.ts
packages/cubejs-cubestore-driver/src/CubeStoreQueueDriver.ts
packages/cubejs-query-orchestrator/src/orchestrator/QueryQueue.js

feat(query-orchestrator): QueryQueue - reduce trafic for processing

---

docs/pages/reference/frontend/cubejs-client-react.mdx
packages/cubejs-client-react/index.d.ts

The type for useCubeQueryResult was out of date and prevented typescript libraries from using the actually returned value from useCubeQuery.
Unforunate that these types are not updated automatically or at least enforced in the library they're defined in.
**Check List**
- [N/A] Tests has been run in packages where changes made if available
- [N/A] Tests for the changes have been added if not covered yet

fix(cubejs-client/react): types for useCubeQuery

---

rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/analysis.rs
rust/cubesql/cubesql/src/compile/rewrite/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/rewriter.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/dates.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/members.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/order.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/split.rs

feat(cubesql): Parameterized cache

---

rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/analysis.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs
rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__redshift_regexp_replace_default_replacer.snap

**Check List**
This PR adds support for Sigma Sunday week granularity. Related test is included. It also fixes an issue with unary minus having lower precedence than some operators.

fix(cubesql): Support Sigma Sunday week granularity

---

rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/analysis.rs
rust/cubesql/cubesql/src/compile/test/mod.rs

**Check List**
This PR enables constant folding for unary minus expressions (`-expr`), fixing a regression introduced with d5a935a. Related test is included.

fix(cubesql): Enable constant folding for unary minus exprs

---

packages/cubejs-databricks-jdbc-driver/src/DatabricksQuery.ts
packages/cubejs-schema-compiler/src/adapter/PostgresQuery.ts
packages/cubejs-schema-compiler/src/adapter/RedshiftQuery.ts
rust/cubesql/cubesql/src/compile/mod.rs

**Check List**
This PR adds support for `DATEDIFF` push down for Databricks and PostgreSQL. Related tests are included.

feat(cubesql): Extend `DATEDIFF` push down support

---

packages/cubejs-backend-native/src/channel.rs

fix(native): Handle error without panic (drop unwrap)

---

packages/cubejs-backend-native/src/channel.rs

**Check List**
#7476 
This PR changes the behavior of native sending data via `JsAsyncChannel`, ignoring the case when data couldn't be sent. This happens when a cancel request packet is received (which is done via a separate connection).

fix(native): Don't crash after query cancellation

---

packages/cubejs-schema-compiler/src/adapter/PrestodbQuery.ts
rust/cubesql/cubesql/src/compile/mod.rs

**Check List**
This PR adds support for OFFSET and LIMIT push down for Athena, swapping them in the template. Related test is included.

feat(cubesql): Support Athena OFFSET and LIMIT push down

---

rust/cubesql/cubesql/src/compile/engine/udf.rs
rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__has_table_privilege.snap
rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__has_table_privilege_default_user.snap
rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__metabase_table_privilege_query.snap

**Check List**
This PR improves compatibility with Metabase v48, adding support for `pg_catalog.has_table_privilege` function. Related tests are included.

fix(cubesql): Support new Metabase meta queries

---

packages/cubejs-duckdb-driver/src/DuckDBDriver.ts

DuckDB NodeJS API does not parse URL parameters for its options (the token parameter is parsed by MotherDuck extension, so it's special). We should pass the `custom_user_agent` in the config map like this:
```js
const db = new duckdb.Database(token ? `md:?motherduck_token=${token}` : ':memory:', {
'custom_user_agent': `Cube/${version}`
});
```

feat(duckdb-driver): pass Cube user agent

---

packages/cubejs-backend-native/Cargo.lock
rust/cubesql/Cargo.lock
rust/cubesql/cubesql/Cargo.toml
rust/cubesql/cubesql/src/compile/engine/df/columar.rs
rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/analysis.rs

**Check List**
This PR bumps cube-js/arrow-datafusion@824a1a3, adding support for `TimestampNanosecond` matching in `CASE` expressions. Related test is included.
Additionally, a duplicate match case yielding an error has been removed.

feat(cubesql): Support `TimestampNanosecond` in `CASE`

---

packages/cubejs-backend-native/Cargo.lock
rust/cubesql/Cargo.lock
rust/cubesql/cubesql/Cargo.toml
rust/cubesql/cubesql/src/compile/engine/df/scan.rs

**Check List**
This PR fixes an issue introduced with 2b7cc30 preventing evaluation of `NULL` values in `CASE` expression in some cases.

fix(cubesql): Allow `NULL` values in `CASE`

---

rust/cubesql/cubesql/src/compile/engine/df/scan.rs

**Check List**
This PR extends `Timestamp` response transformation, supporting `Z` suffix variant.

fix(cubesql): Support `Z` postfix in `Timestamp` response transformation

---

rust/cubesql/cubesql/e2e/tests/postgres.rs
rust/cubesql/cubesql/src/compile/engine/provider.rs
rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/sql/mod.rs
rust/cubesql/cubesql/src/sql/mysql/service.rs
rust/cubesql/cubesql/src/sql/postgres/extended.rs
rust/cubesql/cubesql/src/sql/postgres/shim.rs
rust/cubesql/cubesql/src/sql/session.rs
rust/cubesql/cubesql/src/sql/temp_tables.rs
rust/cubesql/cubesql/src/sql/types.rs

**Check List**
This PR adds support for temporary tables, allowing queries of form:
- `CREATE TEMPORARY TABLE tblname AS SELECT ...`
- `SELECT ... INTO TEMPORARY TABLE tblname FROM...`
- `DROP TABLE ...`

feat(cubesql): Support temporary tables

---

packages/cubejs-backend-native/Cargo.lock
rust/cubesql/Cargo.lock
rust/cubesql/cubesql/Cargo.toml
rust/cubesql/cubesql/src/sql/statement.rs

**Check List**
This PR bumps cube-js/sqlparser-rs@347f769 and cube-js/arrow-datafusion@28a07c3, adding support for placeholders in `OFFSET` and `FETCH ...` expressions. Related tests are included.

feat(cubesql): Support placeholders in `OFFSET`, `FETCH ...`

---

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-testing-drivers/src/tests/testQueries.ts
packages/cubejs-testing-drivers/test/__snapshots__/postgres-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/snowflake-full.test.ts.snap

fix(cubesql): `ungrouped` query can be routed to Cube Store

---

docs/pages/product/configuration/data-sources/materialize.mdx
packages/cubejs-backend-shared/src/env.ts
packages/cubejs-materialize-driver/README.md
packages/cubejs-materialize-driver/src/MaterializeDriver.ts
packages/cubejs-materialize-driver/test/MaterializeDriver.test.ts
packages/cubejs-playground/src/shared/env-vars-db-map.tsx
packages/cubejs-testing-shared/src/db/materialize.ts
packages/cubejs-testing/test/smoke-materialize.test.ts

**Check List**
https://github.com/MaterializeInc/materialize/issues/25060
Added `Cluster` and `CUBEJS_MZ_CLUSTER` env variable as a new configuration option for Materialize:
SSL is now enabled by default as well.

Add cluster option to Materialize driver

---

packages/cubejs-backend-native/Cargo.lock
rust/cubesql/Cargo.lock
rust/cubesql/cubesql/Cargo.toml
rust/cubesql/cubesql/src/compile/engine/df/optimizers/filter_push_down.rs
rust/cubesql/cubesql/src/compile/engine/df/optimizers/limit_push_down.rs
rust/cubesql/cubesql/src/compile/engine/df/optimizers/sort_push_down.rs
rust/cubesql/cubesql/src/compile/engine/df/optimizers/utils.rs
rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/converter.rs
rust/cubesql/cubesql/src/compile/rewrite/mod.rs
rust/cubesql/cubesql/src/sql/statement.rs

feat(cubesql): In subquery support

---

packages/cubejs-client-core/src/utils.js

**Check List**
Incorrect index in movePivotItem.
When moving a dimension from x to y at the second last index, dimension is inserted at third last index.
For example,
|  x | y | 
| ------------ | -------------| 
|dimension2 | dimension1 |
|| measures |
After dragging dimension2 to y index 1 (below dimension1 and above measure),
|  x | y | 
| ------------ | -------------| 
|| dimension2|
|| dimension1|
|| measures |
The expected behavior should be
|  x | y | 
| ------------ | -------------| 
|| dimension1|
|| dimension2|
|| measures |

Fix incorrect index in movePivotItem

---

packages/cubejs-backend-native/Cargo.lock
rust/cubesql/Cargo.lock
rust/cubesql/cubesql/Cargo.toml
rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__cast_float_to_text.snap

**Check List**
This PR bumps cube-js/arrow-datafusion@18d735d, altering the way `Float` types are converted to `Utf8`, trimming the ".0" postfix if a float has no fractional part. This is in accordance with how PostgreSQL converts floats to text, and does not affect `Decimal` (numeric) which retain their fractional part even if it is 0.

fix(cubesql): Trim ".0" postfix when converting `Float to `Utf8`

---

rust/cubesql/cubesql/e2e/tests/postgres.rs
rust/cubesql/cubesql/src/sql/postgres/extended.rs
rust/cubesql/cubesql/src/sql/session.rs
rust/cubesql/cubesql/src/sql/session_manager.rs
rust/cubesql/cubesql/src/sql/temp_tables.rs

**Check List**
This PR introduces memory limits for temporary tables enforced upon their creation. The limits are controlled with the env variables:
- `CUBESQL_TEMP_TABLE_SESSION_MEM` (default: 10 (MiB))
- `CUBESQL_TEMP_TABLE_TOTAL_MEM` (default: 100 (MiB))
It also fixes an issue when trying to create a temporary table with the name of an already existing temporary table would not yield an error but rather report that the table has been created successfully, although no action has actually been taken.

chore(cubesql): Introduce temp table memory limit

---

rust/cubesql/cubesql/src/compile/engine/information_schema/postgres/mod.rs
rust/cubesql/cubesql/src/compile/engine/information_schema/postgres/schemata.rs
rust/cubesql/cubesql/src/compile/engine/provider.rs
rust/cubesql/cubesql/src/compile/parser.rs

**Check List**
This PR removes introspection subquery hacks with most of the queries that didn't run before due to lack of `InSubquery` support.

chore(cubesql): Remove introspection subquery hacks

---

rust/cubesql/cubesql/src/compile/engine/df/wrapper.rs

This reverts commit c7736ccb2c3e1fd809d98adf58bad012fc38c8b7.
https://github.com/cube-js/cube/actions/runs/8234676588/job/22517813069

Revert "fix(cubesql): Fix push down column remapping"

---

rust/cubesql/cubesql/src/compile/engine/df/scan.rs

**Check List**
This PR allows parsing `Timestamp` values from strings containing only date in response.

chore(cubesql): Allow parsing `Timestamp` from just date in response

---

rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/converter.rs

**Check List**
This PR fixes an issue with queries having two `inDateRange` filters over the same time dimension. Sample query:
```
SELECT id
FROM Orders
WHERE
completedAt BETWEEN '2019-02-01T00:00:00' AND '2020-01-01T00:00:00'
AND completedAt BETWEEN '2019-06-01T00:00:00' AND '2020-06-01T00:00:00'
```

fix(cubesql): Don't ignore second filter over same time dimension

---

docs/pages/reference/data-model/context-variables.mdx

docs: Explain FILTER_GROUP

---

packages/cubejs-backend-native/Cargo.lock
rust/cubesql/Cargo.lock
rust/cubesql/cubesql/Cargo.toml
rust/cubesql/cubesql/src/compile/engine/udf.rs
rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/analysis.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/dates.rs

**Check List**
This PR bumps cube-js/arrow-datafusion@b051b03, adding support for distinct binary expression types. This removes hacks with the planned types and allows execution of binary expression with distinct types directly in DataFusion instead of rewriting such expressions into UDFs. The rewrite rules in questions have been removed, and tests have been altered accordingly.

chore(cubesql): Support distinct binary expression types

---

packages/cubejs-backend-native/Cargo.lock
rust/cubesql/Cargo.lock
rust/cubesql/cubesql/Cargo.toml

**Check List**
This PR bumps cube-js/arrow-datafusion@4ede2d0, adding support for parsing timestamp strings as date. This is in accordance with Postgres, which would disregard the time and timezone.

feat(cubesql): Parse timestamp strings as `Date32`

---

packages/cubejs-backend-native/Cargo.lock
rust/cubesql/Cargo.lock
rust/cubesql/cubesql/Cargo.toml
rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/language.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/old_split.rs
rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__exponentiate_op.snap

**Check List**
This PR bumps cube-js/arrow-datafusion@9ba8150, adding support for exponentiation operator (`^`), allowing evaluation of expressions like `3^5`. Related test is included.

feat(cubesql): Support `a ^ b` exponentiation

---

rust/cubesql/cubesql/src/compile/engine/df/scan.rs
rust/cubesql/cubesql/src/compile/legacy_compiler.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs

**Check List**
This PR fixes `parse_from_str` calls, using the correct fractional second placeholder in the format string.

fix(cubesql): Fix timestamp parsing format string

---

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-schema-compiler/test/integration/postgres/sql-generation.test.ts

Proper wrapping count distinct aggregation should be supported by flatten rewrites and fixes to cost function
**Check List**

fix: Render all distinct counts as `1` for ungrouped queries to not fail ratio measures

---

rust/cubestore/cubestore/src/metastore/rocks_store.rs
rust/cubestore/cubestore/src/metastore/rocks_table.rs

Hello!
Iterating without an upper bound leads to reading keys from next table, next index. Downgrading can lead to an unknown tableId on migration. Let's skip these errors by using a range iterator.
Debug of fixed version:
```
2024-03-28 14:22:12,368 TRACE [cubestore::metastore::rocks_store] <pid:50477> Migration for cachestore: started
2024-03-28 14:22:12,369 TRACE [cubestore::metastore::rocks_table] <pid:50477> Migrating table QueueItems from [3, 1] to [2, 1]
2024-03-28 14:22:12,369 INFO  [cubestore::metastore::rocks_table] <pid:50477> Migrating by truncating rows from QueueItemRocksTable table
row_key Table(QueueItems, 4262)
row_key Table(QueueItems, 4263)
row_key Table(QueueItems, 4264)
2024-03-28 14:22:12,370 TRACE [cubestore::metastore::rocks_table] <pid:50477> Migrating by …
```

fix(cubestore): RocksStore - migrate table by truncate (unknown tables)

---

rust/cubestore/cubestore/src/cachestore/cache_rocksstore.rs
rust/cubestore/cubestore/src/config/mod.rs
rust/cubestore/cubestore/src/metastore/mod.rs
rust/cubestore/cubestore/src/metastore/rocks_store.rs

feat(cubestore): CacheStore - allow to disable logs

---

rust/cubesql/cubesql/src/compile/rewrite/rules/members.rs

**Check List**
This PR removes binary expression associative rewrite rules as those happen to lead to self-references and conflict with other rules.

fix(cubesql): Remove binary expression associative rewrites

---

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-schema-compiler/src/adapter/PreAggregations.js
packages/cubejs-testing-drivers/fixtures/_schemas.json
packages/cubejs-testing-drivers/src/tests/testQueries.ts
packages/cubejs-testing-drivers/test/__snapshots__/postgres-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/snowflake-full.test.ts.snap

feat: Ungrouped query pre-aggregation support

---

.github/workflows/publish.yml
.github/workflows/rust-cubestore.yml

There is a problem with the new Rust version (https://github.com/cube-js/cube/pull/7640) and rust-embedded/cross:
```
Failed to run rustc: rustc: error while loading shared libraries: libLLVM-17-rust-1.77.0-nightly.so: cannot open shared object file: No such file or directory
```
It's not a Rust bug; it's a bug somewhere in cross CLI.
Let's compile standalone binaries without using of that CLI.

chore(ci): Compile cross without rust-embedded/cross

---

packages/cubejs-query-orchestrator/DEVELOPMENT.md
rust/cubestore/cubestore-sql-tests/src/tests.rs
rust/cubestore/cubestore/src/cachestore/cache_rocksstore.rs
rust/cubestore/cubestore/src/cachestore/lazy.rs
rust/cubestore/cubestore/src/cachestore/mod.rs
rust/cubestore/cubestore/src/cachestore/queue_item.rs
rust/cubestore/cubestore/src/cachestore/queue_item_payload.rs
rust/cubestore/cubestore/src/metastore/mod.rs
rust/cubestore/cubestore/src/metastore/rocks_store.rs
rust/cubestore/cubestore/src/queryplanner/info_schema/system_queue.rs
rust/cubestore/cubestore/src/queryplanner/test_utils.rs
rust/cubestore/cubestore/src/sql/cachestore.rs

This PR separates a payload field (can be a large string) from `QueueItem` to a separate table called `QueueItemPayload`. Why? Because we have commands that iterates over the whole data. For example `QUEUE LIST` or `QUEUE TO_CANCEL` or `QUEUE PENDING`. It's super expensive to read payload from RocksDB, and deserialize it.
For backward compatibility, I've bumped the version of QueueItem from `2` to `3`. For forward, and backward migration, Cache Store will truncate this table.
```
in_process::queue_list_bench
time:   [10.684 ms 10.769 ms 10.858 ms]
change: [-75.723% -74.952% -74.200%] (p = 0.00 < 0.05)
Performance has improved.
```

feat(cubestore): Queue - optimize list/pending operations

---

.github/workflows/birdbox.yml
.github/workflows/cloud.yml
.github/workflows/drivers-tests.yml
.github/workflows/publish.yml
.github/workflows/push.yml
.github/workflows/rust-cubesql.yml
.github/workflows/rust-cubestore-master.yml
.github/workflows/rust-cubestore.yml
rust/cubestore/Cargo.lock
rust/cubestore/Dockerfile
rust/cubestore/cubehll/src/instance.rs
rust/cubestore/cubestore-sql-tests/Cargo.toml
rust/cubestore/cubestore-sql-tests/src/lib.rs
rust/cubestore/cubestore-sql-tests/src/tests.rs
rust/cubestore/cubestore/Cargo.toml
rust/cubestore/cubestore/src/cachestore/cache_eviction_manager.rs
rust/cubestore/cubestore/src/cluster/mod.rs
rust/cubestore/cubestore/src/config/mod.rs
rust/cubestore/cubestore/src/import/mod.rs
rust/cubestore/cubestore/src/lib.rs
rust/cubestore/cubestore/src/metastore/listener.rs
rust/cubestore/cubestore/src/metastore/mod.rs
rust/cubestore/cubestore/src/queryplanner/physical_plan_flags.rs
rust/cubestore/cubestore/src/sql/mod.rs
rust/cubestore/cubestore/src/store/compaction.rs
rust/cubestore/rust-toolchain.toml

Hello!
```
rustc 1.77.0-nightly (635124704 2024-01-27)
binary: rustc
commit-hash: 635124704849eeead4e3a7bb6e663c5351571d93
commit-date: 2024-01-27
host: aarch64-apple-darwin
release: 1.77.0-nightly
LLVM version: 17.0.6
```
Thanks

feat(cubestore): Upgrade rust to 1.77.0-nightly (635124704 2024-01-27)

---

rust/cubestore/Cargo.lock
rust/cubestore/Cargo.toml
rust/cubestore/Dockerfile
rust/cubestore/cuberockstore/Cargo.toml
rust/cubestore/cuberockstore/src/lib.rs
rust/cubestore/cubestore-sql-tests/Cargo.toml
rust/cubestore/cubestore-sql-tests/benches/in_process.rs
rust/cubestore/cubestore/Cargo.toml
rust/cubestore/cubestore/src/cachestore/cache_item.rs
rust/cubestore/cubestore/src/cachestore/cache_rocksstore.rs
rust/cubestore/cubestore/src/cachestore/compaction.rs
rust/cubestore/cubestore/src/cachestore/queue_item.rs
rust/cubestore/cubestore/src/cachestore/queue_item_payload.rs
rust/cubestore/cubestore/src/cachestore/queue_result.rs
rust/cubestore/cubestore/src/config/mod.rs
rust/cubestore/cubestore/src/lib.rs
rust/cubestore/cubestore/src/metastore/mod.rs
rust/cubestore/cubestore/src/metastore/rocks_store.rs
rust/cubestore/cubestore/src/metastore/rocks_table.rs
rust/cubestore/cubestore/src/sql/mod.rs
rust/cubestore/cubestore/src/store/compaction.rs
rust/cubestore/cubestore/src/store/mod.rs

refs https://github.com/cube-js/cube/issues/7545

feat(cubestore): Enable jemalloc allocator for RocksDB on linux GNU

---

rust/cubestore/Cargo.lock
rust/cubestore/cubestore/Cargo.toml
rust/cubestore/cubestore/src/lib.rs
rust/cubestore/cubestore/src/remotefs/minio.rs
rust/cubestore/cubestore/src/remotefs/s3.rs

**Check List**
I did not create an issue but [this comment](https://cube-js.slack.com/archives/C0206EXEVAS/p1673613378695449) in slack highlights what happens.
Brings `rust-s3` lib up to ~`v0.28.1`~ `v0.32.3`. Main motivation is to solve issue in ECS where current version would fail due to it not being an `ec2` instance (see: https://github.com/durch/rust-s3/pull/200). This was solved in `v0.27.0`.
Going for minimal update possible to reduce breakage.
related MRs:
- (closed) https://github.com/cube-js/cube.js/pull/5673
- (stale) https://github.com/cube-js/cube.js/pull/4411

chore(cubestore): bump rust-s3 0.26.3 -> 0.32.3

---

.gitignore
packages/cubejs-backend-native/Cargo.toml
rust/cubesql/Cargo.lock
rust/cubesql/cubeclient/Cargo.toml
rust/cubesql/cubesql/Cargo.toml
rust/cubesql/cubesql/src/compile/rewrite/analysis.rs
rust/cubesql/cubesql/src/compile/rewrite/language.rs
rust/cubesql/cubesql/src/compile/rewrite/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/rewriter.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/members.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/order.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/wrapper/column.rs

This PR adds a few optimizations around the use of egg.
1. It updates egg from the older 0.7 to a new, unreleased version. It is currently pinned to [this commit](https://github.com/egraphs-good/egg/commit/2f1514c58517e2f38acfe337175f843f156530cf) on the main egg repo.
- The latest released egg version has an e-matching performance regression from 0.7; the above commit fixed that.
2. Many of the appliers are called very frequently and perform heavyweight manipulations over datafusion expressions. This commit reduces the amount of work done in these appliers. I only updated the appliers whose impact I could measure from the `cargo bench` benchmarks, so others may need to be adjusted if they are not represented in that benchmark suite.
Benchmark improvements over main:
```shell
$ …
```

Update egg and remove some clones

---

rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/utils.rs

**Check List**
This PR fixes filters like `WHERE date_trunc(column) <= literal_date` being incorrectly offset, a regression introduced in 6b9ae70 (#7041).
The changes include:
- Remove legacy `filter-date-trunc-leeq` rule (`filter-binary-expr-date-trunc-column-with-literal` does the same and is more versatile)
- Fix `filter-binary-expr-date-trunc-column-with-literal` transform logic to produce correct binary operators
- Use the minimum unit for offset (currently `millisecond`) instead of a `second`
- Fix incorrect test result expectations

fix(cubesql): Fix `date_trunc` over column offset in filters

---

packages/cubejs-backend-native/Cargo.lock
rust/cubesql/Cargo.lock
rust/cubesql/cubesql/Cargo.toml
rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/analysis.rs

**Check List**
This PR bumps egraphs-good/egg@7e60716 and makes an attempt to resolve singularities (`AST node limit reached` error) by using a new `allow_ematching_cycles` option. Related test is included.

fix(cubesql): Disallow ematching cycles

---

packages/cubejs-api-gateway/src/gateway.ts
packages/cubejs-api-gateway/src/sql-server.ts

**Check List**
This PR improves performance of api-gateway by fixing two issues:
- With `onlyCompilerId` flag, `meta` fn would still process cube information, then reject it. This is now fixed, no extra processing is done once we have the `compilerId`.
- `filterVisibleItemsInMeta`, used in quite a few places, would call `getEnv` in a filter inside a map, which greatly hits performance as the cube amount grows. This is now resolved, `getEnv` is only called once for each invocation.

fix(gateway): Improve meta performance

---

packages/cubejs-databricks-jdbc-driver/src/DatabricksQuery.ts

**Check List**
This PR fixes Databricks dialect, specifying correct identifier quotes (`) for SQL push down.

fix(cubesql): Fix Databricks identifier quotes

---

rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs
rust/cubesql/cubesql/src/compile/test/mod.rs

fix(cubesql): Remove incorrect LOWER match rules and fallback to SQL pushdown

---

rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs

**Check List**
This PR addresses an issue with large `IN` list filters generating a large rewrite graph. `transform_filter_in_to_equal` would generate a binary expression for each value. This is now only applied if there is just one value in the list.

fix(cubesql): Do not generate large graphs for large `IN` filters

---

packages/cubejs-backend-native/src/channel.rs
packages/cubejs-testing-drivers/src/tests/testQueries.ts
packages/cubejs-testing-drivers/test/__snapshots__/athena-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/postgres-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/snowflake-full.test.ts.snap
rust/cubesql/cubesql/src/compile/engine/df/wrapper.rs
rust/cubesql/cubesql/src/compile/test/mod.rs
rust/cubesql/cubesql/src/transport/service.rs

**Check List**
This PR fixes param render on SQL API side, making it respect reuse params flag of the dialect.

fix(cubesql): Make param render respect dialect's reuse params flag

---

packages/cubejs-testing-drivers/src/tests/testQueries.ts
packages/cubejs-testing-drivers/test/__snapshots__/athena-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/postgres-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/snowflake-full.test.ts.snap

**Check List**
This PR fixes an issue in `cubejs-testing-drivers` with the newly introduced reuse params query test, wrapping the result of the sum in a `ROUND` function, preventing rounding errors.

chore(cubesql): Fix rounding error in reuse params test query

---

packages/cubejs-backend-native/Cargo.lock
rust/cubesql/Cargo.lock
rust/cubesql/cubesql/Cargo.toml
rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/analysis.rs
rust/cubesql/cubesql/src/compile/rewrite/converter.rs
rust/cubesql/cubesql/src/compile/rewrite/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/rewriter.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/case.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/common.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/dates.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/flatten/column.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/flatten/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/flatten/top_level.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/members.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/old_split.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/split/dates.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/split/functions.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/split/granularity.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/split/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/split/top_level.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/wrapper/aggregate.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/wrapper/extract.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/wrapper/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/wrapper/projection.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/wrapper/scalar_function.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/wrapper/window.rs
rust/cubesql/cubesql/src/compile/test/rewrite_engine.rs

**Check List**
This PR introduces flat list expression rewrites, flattening:
- Projection expressions
- Aggregate group and aggr expressions
- UDF arguments
- Window expressions
Fixes #6307

feat(cubesql): Flatten list expression rewrites to improve performance

---

rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/split/dates.rs

**Check List**
This PR removes `date_trunc` and `date_part` pass through rules. This resolves an issue with queries containing a lot of `date_part` calls in `SELECT` exploding with AST nodes.

chore(cubesql): Remove pass through `date_trunc` and `date_part` rules

---

rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/converter.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs

**Check List**
This PR fixes a rewrite rule that is supposed to support expressions of form `date_trunc(…) = literal`, but does not support strings or constant folded expressions. Related test is included.

fix(cubesql): Support `DATE_TRUNC` equals literal string

---

rust/cubestore/cubestore/src/config/mod.rs
rust/cubestore/cubestore/src/queryplanner/mod.rs
rust/cubestore/cubestore/src/sql/cache.rs
rust/cubestore/cubestore/src/sql/mod.rs

fix(cubestore): Channel closed in query queue cache

---

CONTRIBUTING.md
dev_env_setup.sh

The development setup requires running a bunch of steps, described in `CONTRIBUTING.md`. 
It's pretty tedious, especially if you have to do it multiple times. This PR introduces a shell script that simplifies that for you :)
This PR depends on: https://github.com/cube-js/cube/pull/8330
It asks for the drivers you want to use and can create a test project for you.

Add script to simplify development environment setup

---

packages/cubejs-backend-native/Cargo.lock
rust/cubesql/Cargo.lock
rust/cubesql/cubesql/Cargo.toml
rust/cubesql/cubesql/src/compile/rewrite/analysis.rs
rust/cubesql/cubesql/src/compile/rewrite/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/rewriter.rs

This PR adds an incremental rule scheduler for egg, as well as refactoring ChainSearcher to use the new api. This leads to pretty substantial benchmark improvements!
```
split_query             time:   [91.347 ms 91.807 ms 92.241 ms]
change: [-22.903% -21.789% -20.587%] (p = 0.00 < 0.05)
split_query_count_distinct
time:   [91.948 ms 92.780 ms 93.344 ms]
change: [-19.652% -18.776% -17.989%] (p = 0.00 < 0.05)
wrapped_query           time:   [94.391 ms 94.948 ms 95.317 ms]
change: [-19.749% -18.607% -17.554%] (p = 0.00 < 0.05)
power_bi_wrap           time:   [62.294 ms 62.461 ms 62.610 ms]
change: [-62.622% -62.423% -62.170%] (p = 0.00 < 0.05)
power_bi_sum_wrap       time:   [61.937 ms 62.235 ms 62.650 ms]
change: [-86.397% -86.294% -86.179%] (p = 0.00 < 0.05)
long_in_expr            time: …
```

Use an incremental rule scheduler for egg

---

packages/cubejs-backend-native/Cargo.lock
rust/cubesql/Cargo.lock
rust/cubesql/cubesql/Cargo.toml
rust/cubesql/cubesql/src/compile/mod.rs

**Check List**
This updates a git commit pointer to arrow-datafusion for https://github.com/cube-js/arrow-datafusion/pull/158 and adds tests.
Some test values are rendered pretty screwily because of another bug outside the scope of this feature, involving formatting in IntervalValue::as_postgresql_str and misconstructed IntervalValues in batch_to_dataframe.  That needs to be fixed but is seemingly a separate issue.
Edit: The test values will be fixed in the branch interval-rendering.

feat: Timestamp subtraction, epoch extraction from intervals

---

rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/sql/dataframe.rs
rust/cubesql/pg-srv/src/encoding.rs

**Check List**
Fixes some bugs when rendering intervals in dataframes, particularly negative ones, and those built using nanosecond or millisecond values.

fix(cubesql): Proper interval dataframe values and better formatting

---

rust/cubesql/cubesql/src/compile/rewrite/analysis.rs
rust/cubesql/cubesql/src/compile/rewrite/rewriter.rs

This adds a fix to #8340 to make the nodes added at EGraph creation have distinguishable timestamp values from those created by the first round of rewrites.  This improves performance on some benchmarks and, unsurprisingly, not some others.
**Check List**
Benchmark results.
```
split_query             time:   [11.687 ms 11.699 ms 11.708 ms]
change: [-1.0177% -0.3939% +0.7496%] (p = 0.54 > 0.05)
split_query_count_distinct
time:   [11.566 ms 11.573 ms 11.578 ms]
change: [-1.7806% -1.7163% -1.6513%] (p = 0.00 < 0.05)
wrapped_query           time:   [12.530 ms 12.568 ms 12.593 ms]
change: [-0.9316% -0.7545% -0.5633%] (p = 0.00 < 0.05)
power_bi_wrap           time:   [13.211 ms 13.267 ms 13.349 ms]
change: [-0.8045% -0.5273% -0.1190%] (p = 0.01 < 0.05)
power_bi_sum_wrap       time:   [24.299 …
```

perf(cubesql): Make incremental rule scheduler distinguish between generation 0 and 1

---

.github/workflows/birdbox.yml
.github/workflows/publish.yml
.github/workflows/rust-cubesql.yml
.github/workflows/rust-cubestore-master.yml
.github/workflows/rust-cubestore.yml

This is a scheduled macOS-11 brownout. The macOS-11 environment is deprecated and will be removed on June 28th, 2024.

chore(ci): Bump macOS from 11 to 12

---

rust/cubesql/Cargo.lock
rust/cubesql/cubesql/Cargo.toml
rust/cubesql/cubesql/src/compile/mod.rs

This PR introduces support for expressions like `timestamp datatype value - date datatype value`.
And add tests for these.
This PR depends on https://github.com/cube-js/arrow-datafusion/pull/160
**Check List**

feat(cubesql): support timestamp subtract date in SQL API, tests

---

docs/pages/product/configuration/data-sources/questdb.mdx

**Check List**
Hi team!
Updates the QuestDB docs with Docker and interlinks.

Update QuestDB doc

---

docs/pages/product/apis-integrations/queries.mdx

**Check List**
N/A
While reading the docs, it took me a few searches to figure out how to make use of the `compareDateRange` functionality through plain REST API. Just thought on adding an example for quick reference, but kept the references to the [Comparing Data over Different Time Periods](https://cube.dev/blog/comparing-data-over-different-time-periods) blogpost

docs/data-modeling: Adding compareDateRange example

---

packages/cubejs-backend-native/Cargo.toml

This avoids stack overflows in datafusion, caused by very inefficient Rust stack layout in opt-level 0, that makes the
sql_expr_to_logical_expr function, called recursively, use 50KB stack frames.  (Some other functions use 90KB or over 100KB, as well.)
**Check List**

chore(cubesql): Set opt-level to 1 in dev debug builds

---

packages/cubejs-testing-shared/src/db-container-runners/oracle.ts

**Check List**
Hey all,
Thanks a lot for using my Oracle Database images.
I have noticed that you are still using the old Oracle Database XE version of my images.
Oracle has discontinued Oracle Database XE and instead offers Oracle Database Free as the successor, which was first released last year.
The database editions are compatible, hence nothing should break or change other than the connect string and the Docker image tag.
I have taken the liberty to provide the modifications based on what I could find in the repository.
Thanks,

Upgrade to Oracle Database Free

---

packages/cubejs-api-gateway/src/sql-server.ts
packages/cubejs-backend-native/js/index.ts
packages/cubejs-backend-native/src/node_export.rs
packages/cubejs-server/src/server.ts
rust/cubesql/cubesql/src/bin/cubesqld.rs
rust/cubesql/cubesql/src/config/mod.rs
rust/cubesql/cubesql/src/sql/postgres/service.rs
rust/cubesql/cubesql/src/sql/postgres/shim.rs
rust/cubesql/cubesql/src/sql/postgres/writer.rs
rust/cubesql/pg-srv/src/buffer.rs
rust/cubesql/pg-srv/src/protocol.rs

Aside from fatal error message injection, we also add logic to wait on and properly join the postgres connections and tasks.  Otherwise we would not properly gracefully shut down.
One easily reversible decision made was to avoid passing the CancellationToken down recursively and instead track partially written socket buffers.  Because we have other CancellationTokens floating around in query logic (which IIRC are not actually used -- nothing triggers them) that might have a reason to change in the future.

feat: Make graceful shutdown add fatal messages in postgres

---

.github/actions/init-ci/action.yaml
.github/workflows/birdbox.yml
.github/workflows/cloud.yml
.github/workflows/drivers-tests.yml
.github/workflows/examples-publish.yml
.github/workflows/master.yml
.github/workflows/publish.yml
.github/workflows/push-cross-images.yml
.github/workflows/push.yml
.github/workflows/rust-cubesql.yml
.github/workflows/rust-cubestore-master.yml
.github/workflows/rust-cubestore.yml
.github/workflows/workflow-lint.yml

We have too many outdated actions. Some use super old node versions. Here is an attempt to update all actions to the latest.
> The following actions uses node12 which is deprecated and will be forced to run on node16: actions-rs/toolchain@v1
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/setup-node@v3, actions/cache/restore@v3, nick-invision/retry@v2
> .....
Also updated obsolete `echo "::save-state name={name}::{value}"`. More info can be found [here](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
Also this fixes all `shellcheck` warnings across workflows
And to keep our workflows clean and correct — this PR adds new workflow linter.
This PR includes:
* chore(ci): update …

chore: CI Workflow updates

---

rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/split/aggregate_function.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/split/mod.rs

**Check List**
This PR fixes projection-aggregate split, avoiding putting aggregate function expressions in `Projection`, which is incorrect. Related test is included.

fix(cubesql): Don't put aggregate functions in `Projection` on split

---

packages/cubejs-postgres-driver/src/PostgresDriver.ts

fix intermittent error when pre-aggregation enabled and used postgresql
**Check List**

fix(pg-driver): fix PostgresDriver pre-aggregation issue

---

rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs

**Check List**
#8344 
This PR fixes an issue with a filter transformation that would transform expression like `col = literal_timestamp` into `dateRange` with the same start and end date; this is generally valid, with the exception of when the `col` is a time dimension **with granularity set**. This case was unhandled, and the filter was incorrect; this is now fixed. Related test is included.

fix(cubesql): Fix incorrect `dateRange` when filtering over `date_trunc`'d column in outer query

---

packages/cubejs-postgres-driver/src/PostgresDriver.ts
packages/cubejs-testing/test/__snapshots__/smoke-cubesql.test.ts.snap
packages/cubejs-testing/test/smoke-cubesql.test.ts

**Check List**
Adapted from 393b193.
This PR resolves an issue when running queries like `SELECT field, * FROM ...` with `CUBESQL_STREAM_MODE` set to `true`. As the query contains pseudo fields like `__user`, those are interpreted as `unknown` type with oid `705`. This oid is not defined as part of the `pg-types` library, so we define it locally. Related test is included.

fix(postgres-driver): Don't throw errors for pseudo fields like `__user`

---

rust/cubestore/Cargo.lock

This versions includes fix for https://github.com/MaterializeInc/rust-sasl/issues/51, which includes unreleased patch for vendored version of cyrus-sasl
**Check List**
At the moment `sasl2-sys` have `version = "0.1.20+2.1.28"` in Cargo.lock. This version contains vendored code of cyrus-sasl, that contains a bug (invalid autoconf header check), that leads to warning on older GCC, and that warning turns to error in GCC 14. It looks like this (and there's one more for `clock`):
```
[sasl2-sys 0.1.20+2.1.28] saslutil.c: In function 'sasl_mkchal':
[sasl2-sys 0.1.20+2.1.28] saslutil.c:280:3: error: implicit declaration of function 'time' [-Wimplicit-function-declaration]
[sasl2-sys …
```

chore(deps): Bump sasl2-sys to 0.1.22+2.1.28

---

.github/workflows/publish.yml
.github/workflows/rust-cubestore-master.yml
.github/workflows/rust-cubestore.yml
rust/cubestore/Dockerfile
rust/cubestore/builder.Dockerfile
rust/cubestore/docker-bake.hcl
rust/cubestore/rust-toolchain.toml

It reduces build time by:
- 15 minutes for windows
- 7 minutes for macOS
- 2,5 minutes for linux
3 minutes on a cache layer miss + reduce cache usage on GHA + protection for errors like 'apt.llvm.org' not resolved

chore(ci): Publish - speedup

---

rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/split/dates.rs

**Check List**
This PR fixes column dependency in date splits, allows splitting with non-comparable granularities, and adds a `DATE_PART(CAST(DATE_TRUNC(...)))` split variant.

chore(cubesql): Fix date split column dependency

---

packages/cubejs-api-gateway/src/gateway.ts
packages/cubejs-api-gateway/src/query.js
packages/cubejs-api-gateway/src/sql-server.ts
packages/cubejs-api-gateway/src/types/query.ts
packages/cubejs-api-gateway/src/types/request.ts
packages/cubejs-api-gateway/test/index.test.ts
packages/cubejs-api-gateway/test/permissions.test.ts

- **fix typos**
- **Add unparsedMemberExpressionValidator for query**
**Check List**

fix(cubesql): Fix "unable to represent JsFunction in Python" in queries when using python for cube configuration

---

packages/cubejs-server-core/src/core/DevServer.ts

**Check List**
Due to forgotten return, one of request handlers tries to send response twice, leading to rejection, which gets caught, but error handler tries to send response one more time, throwing another exception, and crashing process with unhandled rejection.

fix(server-core): Headers sent multiple times from dev-server handlers crashes it

---

packages/cubejs-questdb-driver/src/QuestDriver.ts
packages/cubejs-testing-shared/src/db-container-runners/questdb.ts

**Check List**
QuestDB returns `table_name` column name instead of `table` from `SHOW TABLES;` SQL starting from v7.3.3.
* Fix the column name
* Update integration tests to use the latest QuestDB version

fix(cubejs-questdb-driver): fix obsolete column name in SHOW TABLES

---

rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs

**Check List**
This PR alters the rewrite rule `in-filter-equal`, allowing all expressions to be transformed, not just constants. Related test is included.

fix(cubesql): Transform `IN` filter with one value to `=` with all expressions

---

packages/cubejs-schema-compiler/src/adapter/ClickHouseQuery.ts
packages/cubejs-schema-compiler/test/integration/clickhouse/ClickHouseDbRunner.js
packages/cubejs-schema-compiler/test/integration/clickhouse/clickhouse-dataschema-compiler.test.ts

**Check List**
This PR updates the ClickHouseQuery adapter to replace all instances of `toDateTime` with `toDateTime64`. This change ensures that dates before 1970 are handled correctly, particularly in time dimensions functionality.
**Important Note for Users:**
If your dataset includes dates before 1970, ensure that the `enable_extended_results_for_datetime_functions` ClickHouse option is turned on. This setting is crucial for functions like `toStartOfYear` to work correctly with dates outside the typical range.
For more information, refer to the [ClickHouse documentation](https://clickhouse.com/docs/en/operations/settings/settings#enable-extended-results-for-datetime-functions).

fix(schema-compiler): use toDateTime64 for pre-1970 dates CH

---

packages/cubejs-backend-native/Cargo.lock
rust/cubesql/Cargo.lock
rust/cubesql/cubeclient/Cargo.toml
rust/cubesql/cubesql/Cargo.toml
rust/cubesql/cubesql/src/error.rs

I am going to use `Axum` in https://github.com/cube-js/cube/pull/8472 PR, which uses `hyper` 1+, it's why I am going to upgrade `request` to `0.13`

feat(rust/cubeclient): Upgrade reqwest to 0.13 (hyper 1)

---

rust/cubesql/cubesql/src/compile/rewrite/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs

**Check List**
This PR fixes a regression introduced with 671e067 which broke `IN`->`=` transformation when push down is set to `false`.

fix(cubesql): Apply `IN`->`=` transformation with push down disabled

---

packages/cubejs-api-gateway/src/sql-server.ts
packages/cubejs-backend-native/js/index.ts
packages/cubejs-backend-native/src/node_export.rs
packages/cubejs-backend-native/test/server.js
packages/cubejs-backend-native/test/sql.test.ts
packages/cubejs-server/src/server.ts
packages/cubejs-server/src/server/container.ts
packages/cubejs-testing/package.json
packages/cubejs-testing/src/birdbox.ts
packages/cubejs-testing/test/__snapshots__/smoke-graceful-shutdown.test.ts.snap
packages/cubejs-testing/test/smoke-graceful-shutdown.test.ts
rust/cubesql/cubesql/src/bin/cubesqld.rs
rust/cubesql/cubesql/src/config/mod.rs
rust/cubesql/cubesql/src/config/processing_loop.rs
rust/cubesql/cubesql/src/error.rs
rust/cubesql/cubesql/src/sql/postgres/service.rs
rust/cubesql/cubesql/src/sql/postgres/shim.rs
rust/cubesql/cubesql/src/sql/session.rs

"Smart" matches the behavior of Postgres -- it stops accepting connections but lets them keep running -- and right now it's not possible.  "Semi-Fast" is willing to end a connection once it has nothing active going on and is triggered by SIGTERM (when graceful shutdown is configured to be enabled).

feat: Smart and Semi-Fast shutdown

---

rust/cubesql/cubesql/src/compile/rewrite/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/members.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/order.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/wrapper/aggregate.rs

Makes column_name_to_member_vec do caching, removes some of its calls.  But also, we replace a bunch of usage of `find_member_by_alias_immutably` with the mutable, caching version.
Most benchmarks do the same or better.  `long_simple_in_number_expr_1k` is one which gets worse, at +9%.  A few of the numbers:
```
power_bi_wrap                    -8.5660%
power_bi_sum_wrap                -9.1824%
long_in_expr                    -12.923%
long_simple_in_number_expr_1k    +9.1547%
```
The main source of *worse* performance would come from pre-emptively copying out and cloning vectors that were previously iterated in-place to avoid holding multiple mutable references to the EGraph.  We could probably deal with that efficiently by using RefCell in the member_name_to_expr field, but we don't do …

perf(cubesql): More complete usage of member_name_to_expr caching

---

packages/cubejs-schema-compiler/test/integration/mssql/MSSqlDbRunner.js
packages/cubejs-schema-compiler/test/integration/postgres/PostgresDBRunner.js

This fixes:
* Ms sql server integration test due to latests changes in `2019-latest` docker image.
* Postgres integration test and introduces correct postges readyness check including possible initdb flow.

chore(ci): fix integration tests run

---

rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/split/functions.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/split/mod.rs

**Check List**
Add separate split rules for handling `ScalarFunctionExprArgs` of any size. This allows simple pass-through for any scalar function. E.g. `SUBSTR` can now push down dimension from any argument, not only from first one.

Make split rules for scalar functions variadic

---

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-schema-compiler/test/unit/base-query.test.ts

This PR fixes a wrong SQL generated for query that includes same time dimension few times but with different granularities.
Example:
```js
{
measures: [
'cards.count'
],
timeDimensions: [
{
dimension: 'cards.createdAt',
granularity: 'quarter',
},
{
dimension: 'cards.createdAt',
granularity: 'month',
}
],
filters: [],
}
```
Only one time dimension was included in generated SQL. Now the generated SQL includes both!

fix(schema-compiler): incorrect sql for query with same dimension with different granularities

---

rust/cubestore/Dockerfile

Fix #8568
In https://github.com/cube-js/cube/pull/8554/commits/54a15e918285667bb7b0d5c1f033d8d6450cc682, i've removed curl, but it requires ca-certificates.
Let's install ca-certificates.
ca-certitifcates -> openssl (3 for booworm) -> libssl3

fix(cubestore): Docker - install ca-certificates, fix #8568

---

rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/split/aggregate_function.rs
rust/cubesql/cubesql/src/compile/test/mod.rs
rust/cubesql/cubesql/src/compile/test/test_bi_workarounds.rs
rust/cubesql/cubesql/src/compile/test/utils.rs

**Check List**
This PR splits PowerBI `COUNT(DISTINCT(...)) + MAX(CASE ...)` expression, ignoring NULL values, as we can't count them as distinct yet. Related test is included.

fix(cubesql): Split PowerBI count distinct expression

---

rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/members.rs

**Check List**
This PR is a fix for #8577, improving grouped push down handling.

chore(cubesql): Don't push down aggregate to grouped query with filters

---

.github/workflows/rust-cubesql.yml
rust/cubesql/cubesql/benches/large_model.rs

**Check List**
Run `cargo check` for all targets in cubesql
Run rustfmt for all cubesql workspace 
Add `--locked` to clippy runs in cubejs-backend-native

ci: More CI checks in cubesql and cubejs-backend-native

---

rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/split/dates.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/utils.rs
rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__date_part_day_from_dimension.snap
rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__date_part_dow_from_dimension.snap
rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__date_part_doy_from_dimension.snap
rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__date_part_epoch_from_dimension.snap
rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__date_part_qtr_from_dimension.snap
rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__date_part_quarter_from_dimension.snap
rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__extract_day_from_dimension.snap
rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__extract_dow_from_dimension.snap
rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__extract_doy_from_dimension.snap
rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__extract_epoch_from_dimension.snap
rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__extract_quarter_from_dimension.snap

**Check List**
Rules for splitting date_part calls now parses date_part argument and use it to check if split is possible, and what granularity to use in date_trunc
`EXTRACT(EPOCH FROM dim_date0)`
**Before**
Split to `date_part('epoch', date_trunc('epoch', dim_date0))`, which is incorrect, `date_trunc` does not accept `'epoch'`, and would issue CubeScan with `"timeDimensions": [{"dimension": "dim_date0", "granularity": "epoch"}]`
**After**
Split as a simple dimension request and `date_part('epoch', ...` projection
`EXTRACT(DOW FROM dim_date0)`
**Before**
Split to `date_part('day', date_trunc('day', dim_date0))`, which is incorrect, truncation is correct, but `date_part('day', ...` is not
**After**
Split as …

fix(cubesql): Use date_part => date_part + date_trunc split only with appropriate date_part argument

---

.github/workflows/master.yml

**Check List**
Triggers master workflow on changes in Rust dependencies of native backend. For example, it should publish `cubejs/cube:dev` after cubesql-only changes.

ci: Add Rust dependencies of native backend to master workflow filter

---

rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/split/functions.rs
rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__noninjective_coalesce_from_dimension.snap
rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__noninjective_left_from_dimension.snap
rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__noninjective_nullif_from_dimension.snap
rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__noninjective_right_from_dimension.snap

**Check List**
Rules for splitting functions like coalesce now does **not** allow projection split, but does pick up columns from any argument.
`COALESCE(foo, '(none)')` + `GROUP BY`
**Before**
`Projection(CubeScan)`, which is incorrect, it can return two rows with same grouping key
**After**
`Aggregation(CubeScan)`, would re-argregate result from CubeScan
`COALESCE(foo, bar, '(none)')`
**Before**
Would not detect `bar` column at all
**After**
Would detect CubeScan with two members.

fix(cubesql): Fix non-injective functions split rules, make them variadic

---

docs/pages/product/auth.mdx
docs/pages/reference/configuration/config.mdx
packages/cubejs-api-gateway/src/gateway.ts
packages/cubejs-api-gateway/src/types/auth.ts
packages/cubejs-api-gateway/test/auth.test.ts
packages/cubejs-api-gateway/test/index.test.ts
packages/cubejs-backend-native/js/index.ts
packages/cubejs-backend-native/test/config.py
packages/cubejs-backend-native/test/python.test.ts

**Check List**
#8133
This is useful with Python configs, where input checkAuth context is a copy of original context

feat(cubejs-api-gateway): Support returning new security context from check_auth

---

packages/cubejs-schema-compiler/src/adapter/MssqlQuery.ts

In MS SQL there is no `"string" || "string"` operator, instead simple `+` is used.

fix(schema-compiler): correct string concatenation and casting for MS SQL

---

packages/cubejs-schema-compiler/src/adapter/MysqlQuery.ts

In MySQL there is no such type `TEXT` so casting from BaseQuery must be overridden.

fix(schema-compiler): correct string casting for MySQL

---

packages/cubejs-schema-compiler/src/adapter/BigqueryQuery.ts

In BigQuery there is no such type TEXT so casting from BaseQuery must be overridden.

fix(schema-compiler): correct string casting for BigQuery

---

packages/cubejs-databricks-jdbc-driver/src/DatabricksQuery.ts

In Databricks there is no such type TEXT so casting from BaseQuery must be overridden.

fix(schema-compiler): correct string casting for Databricks

---

packages/cubejs-schema-compiler/src/adapter/BigqueryQuery.ts

**Check List**
This PR adds support for `CURRENT_DATE` expression SQL push down in BigQuery. Like PostgreSQL, BigQuery has the 
function with the same name that can be called without arguments.

fix(schema-compiler): Support `CURRENT_DATE` SQL push down for BigQuery

---

packages/cubejs-schema-compiler/src/adapter/BaseGroupFilter.ts
packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-schema-compiler/src/adapter/PreAggregations.js
packages/cubejs-schema-compiler/test/integration/postgres/yaml-compiler.test.ts
packages/cubejs-schema-compiler/test/unit/base-query.test.ts
packages/cubejs-server-core/src/core/CompilerApi.js

Fix with propagating FILTER_PARAMS from views to inner Cube's SELECT statements.
**Check List**

fix(schema-compiler): propagate FILTER_PARAMS from view to inner cube's SELECT

---

packages/cubejs-backend-native/Cargo.lock
rust/cubenativeutils/Cargo.lock
rust/cubesql/Cargo.lock
rust/cubesql/cubesql/Cargo.toml
rust/cubesql/cubesql/src/compile/test/mod.rs
rust/cubesql/cubesql/src/compile/test/snapshots/cubesql__compile__test__test_df_execution__join_with_coercion.snap
rust/cubesql/cubesql/src/compile/test/snapshots/cubesql__compile__test__test_df_execution__triple_join_with_coercion.snap
rust/cubesql/cubesql/src/compile/test/test_df_execution.rs
rust/cubesqlplanner/Cargo.lock
rust/cubesqlplanner/cubesqlplanner/Cargo.toml

**Check List**
Bump datafusion to version with type coercion support for join. This is useful, for example, for introspection queries that join `pg_catalog.pg_attribute` with `pg_catalog.pg_description` on `pg_attribute.attnum = pg_description.objsubid`. Both can represent column number, but `attnum` is `int2`, and `objsubid` is `int4`

feat(cubesql): Support join with type coercion

---

rust/cubestore/cubestore-sql-tests/src/tests.rs
rust/cubestore/cubestore/src/queryplanner/mod.rs
rust/cubestore/cubestore/src/queryplanner/udfs.rs

This PR brings `date_bin()` support into CubeStore. This will be used at least by custom granularities feature.
Refs:
* #8537
* #8664
**Check List**

feat(cubestore): Support date_bin function

---

rust/cubesql/cubesql/src/compile/engine/df/wrapper.rs
rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/test/mod.rs
rust/cubesql/cubesql/src/compile/test/test_user_change.rs

**Check List**
Use same meta for both SQL generation and execution calls

fix(cubesql): Use load meta with user change for SQL generation calls

---

packages/cubejs-schema-compiler/src/adapter/CubeStoreQuery.ts
packages/cubejs-schema-compiler/test/unit/base-query.test.ts
packages/cubejs-testing-drivers/fixtures/_schemas.json
packages/cubejs-testing-drivers/src/tests/testQueries.ts

This PR brings `date_bin()` support to `CubeStoreQuery`. This makes sense for Custom Granularities.
Related to:
* #8664
Depends on:
* #8537
* #8672
**Check List**

feat(schema-compiler): Support date_bin function in Cube Store queries

---

DEPRECATION.md
packages/cubejs-schema-compiler/src/compiler/CubeSymbols.js
packages/cubejs-schema-compiler/src/compiler/transpilers/ValidationTranspiler.ts
packages/cubejs-schema-compiler/test/integration/clickhouse/clickhouse-graph-builder.test.ts
packages/cubejs-schema-compiler/test/integration/mssql/mssql-ungrouped.test.ts
packages/cubejs-schema-compiler/test/integration/postgres/sql-generation-logic.test.ts
packages/cubejs-schema-compiler/test/integration/postgres/sql-generation.test.ts
packages/cubejs-schema-compiler/test/unit/transpilers.test.ts

BREAKING CHANGE: This functionality was deprecated starting from v0.26.0. Please migrate to SECURITY_CONTEXT.

chore!: Remove support for USER_CONTEXT

---

packages/cubejs-schema-compiler/src/compiler/CubeValidator.ts
packages/cubejs-schema-compiler/test/unit/cube-validator.test.ts

- **fix(schema-compiler): Add missing “quarter” time unit to granularity definitions**
- **add tests for quarters in granularities**
- **fix(schema-compiler): allow custom granularities with 1 week interval definition**
- **more tests**

fix(schema-compiler): Add missing “quarter” time unit to granularity definitions

---

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-schema-compiler/src/adapter/Granularity.ts
packages/cubejs-schema-compiler/src/compiler/CubeEvaluator.ts
packages/cubejs-schema-compiler/src/compiler/CubeSymbols.js
packages/cubejs-schema-compiler/test/integration/postgres/custom-granularities.test.ts
packages/cubejs-schema-compiler/test/unit/base-query.test.ts
packages/cubejs-schema-compiler/test/unit/utils.ts

This PR introduces the ability to reference the time dimension granularity in dimension definition like this:
```yaml
.....
dimensions:
- name: created_at_half_year
sql: "{created_at.half_year}"
type: string
- name: created_at_fiscal_year_feb
sql: "{created_at.fiscal_year_by_1st_feb}"
type: string
- name: created_at
sql: created_at
type: time
granularities:
- name: half_year
interval: 6 months
- name: half_year_by_1st_april
interval: 6 months
offset: 3 months
- name: fiscal_year_by_1st_feb
interval: 1 year
offset: 1 month
- name: fiscal_year_by_15th_march
interval: 1 year
origin: '2024-03-15'
- name: created_at_predefined_year
sql: "{createdAt.year}"                   # You can refer even predefined granularities
type: string
```
Then you can request those dimensions like any other: add …

feat(schema-compiler): Reference granularities in a proxy dimension

---

packages/cubejs-firebolt-driver/src/FireboltQuery.ts
packages/cubejs-query-orchestrator/src/orchestrator/BaseQueueEventsBus.ts
packages/cubejs-query-orchestrator/src/orchestrator/LocalQueueEventsBus.ts
packages/cubejs-server-core/test/unit/OptsHandler.test.ts
packages/cubejs-server-core/test/unit/index.test.ts
tsconfig.base.json

Starting from the v0.36 release, Node.js 18 is deprecated (we are using Node.js 20 for docker). This means that we are ready to use es2022 as a minimal version for our target in tsconfig.

chore: tsconfig - target es2022 (Node.js 18)

---

packages/cubejs-schema-compiler/src/adapter/Granularity.ts
packages/cubejs-schema-compiler/src/adapter/PreAggregations.js
packages/cubejs-schema-compiler/test/unit/pre-agg-time-dim-match.test.ts

- **remove doubled query.newTimeDimension() call in transformQueryToCanUseForm**
- **fix(schema-compiler): correct origin timestamp initialization in Granularity instance**
- **tests for custom preagg matches**
**Check List**

fix(schema-compiler): correct origin timestamp initialization in Granularity instance

---

rust/cubesql/cubesql/src/compile/test/mod.rs
rust/cubesql/cubesql/src/config/mod.rs
rust/cubesql/cubesql/src/sql/postgres/mod.rs
rust/cubesql/cubesql/src/sql/postgres/pg_auth_service.rs
rust/cubesql/cubesql/src/sql/postgres/shim.rs
rust/cubesql/cubesql/src/sql/server_manager.rs
rust/cubesql/pg-srv/src/buffer.rs
rust/cubesql/pg-srv/src/protocol.rs

**Check List**
This PR refactors pg-srv, making authentication request methods and message tag parsing to be extendable. It also adds `PostgresAuthService` to be able to extend the auth process.

refactor(cubesql): Make Postgres authentication extensible

---

packages/cubejs-schema-compiler/src/adapter/BaseTimeDimension.ts
packages/cubejs-schema-compiler/src/adapter/Granularity.ts
packages/cubejs-schema-compiler/src/adapter/PreAggregations.js

feat(schema-compiler): exact match preagg with custom granularity without the need for allow_non_strict_date_range_match option

---

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-schema-compiler/test/unit/base-query.test.ts
packages/cubejs-schema-compiler/test/unit/utils.ts

- **fix(schema-compiler): fix FILTER_PARAMS propagation from view to cube's SQL query**
- **Add tests for fix**
**Check List**

fix(schema-compiler): fix FILTER_PARAMS propagation from view to cube's SQL query

---

.github/workflows/drivers-tests.yml

This happens from time to time due to various reasons like docker hub image pull timeouts and other errors. This helps in such a cases.

chore(testing-drivers): add retry for failures during drivers matrix tests

---

rust/cubestore/Cargo.lock
rust/cubestore/cubestore/src/sql/table_creator.rs
rust/cubestore/cubestore/src/store/compaction.rs
rust/cubestore/cubestore/src/table/parquet.rs

**Check List**
Makes TableExtensionService::get_extension return a Result.
This PR will still need its Cargo.lock pointer to be updated with the commit of https://github.com/cube-js/arrow-datafusion/pull/169 after it has been merged.

Metadata cache factory result

---

.github/workflows/drivers-tests.yml
.github/workflows/publish.yml

This PR improves the CI flows: If there are no secrets for cloud databases — the CI will skip related driver tests.

chore(ci): run cloud db drivers tests only when credentials are set

---

docs/pages/reference/configuration/environment-variables.mdx

docs: fix typo in the description of CUBESTORE_GCP_CREDENTIALS env var

---

docs/pages/reference/data-model/dimensions.mdx
rust/cubestore/cubestore/src/sys/malloc.rs
rust/cubestore/cubezetasketch/src/sparse.rs

**Check List**
fix some comments

chore: fix some comments

---

packages/cubejs-api-gateway/openspec.yml
packages/cubejs-api-gateway/src/helpers/prepareAnnotation.ts
packages/cubejs-api-gateway/test/helpers/prepareAnnotation.test.ts
packages/cubejs-api-gateway/test/index.test.ts
packages/cubejs-api-gateway/test/mocks.ts
packages/cubejs-schema-compiler/src/compiler/CubeToMetaTransformer.js
packages/cubejs-schema-compiler/test/unit/schema.test.ts

This is a further extension of API to support custom granularities. Now, granularity's details are exposed. They are required at least for chart generation on the client side, without granularity details (e.g. Interval, offset/origin) — it is not possible to generate time series points.
**Check List**

feat(schema-compiler): expose custom granularities details via meta API and query annotation

---

packages/cubejs-client-core/index.d.ts
packages/cubejs-client-core/src/ResultSet.js
packages/cubejs-client-core/src/index.js
packages/cubejs-client-core/src/tests/ResultSet.test.js
packages/cubejs-client-core/src/tests/granularity.test.js
packages/cubejs-client-core/src/tests/utils.test.js
packages/cubejs-client-core/src/time.js
packages/cubejs-client-core/src/utils.js

This PR brings custom granularity time-series generation. This allows to build charts not only for predefined granularities like `month` or `day` but for any interval defined in custom granularity for time dimension.
This depends on:
* https://github.com/cube-js/cube/pull/8740
**Check List**

feat(client-core): timeseries for custom intervals

---

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js

**Check List**
This PR adds a meaningful error for queries where `COUNT(*)` was referenced, but is not part of a view, and as such is ambiguous.

fix(schema-compiler): Warn when `COUNT(*)` is referenced in a view where `count` is not defined

---

rust/cubestore/Cargo.lock
rust/cubestore/cubestore/src/config/mod.rs
rust/cubestore/cubestore/src/sql/mod.rs
rust/cubestore/cubestore/src/store/compaction.rs
rust/cubestore/cubestore/src/store/mod.rs
rust/cubestore/cubestore/src/table/parquet.rs

**Check List**
A related PR is https://github.com/cube-js/arrow-datafusion/pull/170 -- we do not need to update the Cargo.lock before merging this, but we'd want to do so anyway in a separate PR, so it is a good idea.

refactor(cubestore): Move build_writer_props to CubestoreMetadataCacheFactory

---

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-schema-compiler/test/unit/pre-aggregations.test.ts

This closes the regression bug #8754
**Check List**

fix(schema-compiler): fix FILTER_PARAMS flow in pre aggregations filtering

---

.github/workflows/drivers-tests.yml

This PR updates the testing-drivers CI: the built docker image is transferred from `build` to `tests` job via upload/download artifact and is loaded into local docker, thus avoiding the need to upload/download the docker image from dockerhub registry

chore(ci): use built docker image for tests without the need of uploading to dockerhub

---

packages/cubejs-databricks-jdbc-driver/src/DatabricksQuery.ts

**Check List**
This PR adds `DATE_PART` and `EXTRACT` SQL push down support for Databricks.

feat(cubesql): Support `DATE_PART` SQL push down with Databricks

---

packages/cubejs-postgres-driver/src/PostgresDriver.ts
packages/cubejs-postgres-driver/test/PostgresDriver.test.ts
packages/cubejs-redshift-driver/src/RedshiftDriver.ts

**Check List**
`PostgresDriver` uses `pg` module as a driver, and `pg` does not check incoming params, and if there's too many it just sends incorrect bind message. It would end up as "expected a lot of params, but 0 was passed" error from server.
`RedshiftDriver` extends `PostgresDriver`, but there's another catch: Redshift server misbehaves a little, and breaks on 32768 or more parameters with `there is no parameter $-32768`.
There's not much we can do about it, but at least we can make error messages clear.

fix: Add explicit parameters limit in PostgreSQL and Redshift drivers

---

packages/cubejs-playground/package.json
packages/cubejs-playground/src/QueryBuilderV2/QueryBuilderExtras.tsx
packages/cubejs-playground/src/QueryBuilderV2/components/ChartRenderer.tsx
packages/cubejs-playground/src/QueryBuilderV2/components/GranularityListMember.tsx
packages/cubejs-playground/src/QueryBuilderV2/components/ListMember.tsx
packages/cubejs-playground/src/QueryBuilderV2/components/SidePanelCubeItem.tsx
packages/cubejs-playground/src/QueryBuilderV2/components/TimeListMember.tsx
packages/cubejs-playground/src/QueryBuilderV2/utils/format-date-by-granularity.tsx
packages/cubejs-playground/src/QueryBuilderV2/utils/index.ts
packages/cubejs-playground/src/QueryBuilderV2/utils/titleize.ts
yarn.lock

This PR brings support for custom granularities in our playground V2! Now you can choose custom granularities in Query Builder, get the results and even see the charts with custom intervals!
This depends on:
* https://github.com/cube-js/cube/pull/8742
* https://github.com/cube-js/cube-ui-kit/pull/500
**Check List**

feat(playground): custom granularities support

---

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-schema-compiler/src/adapter/PrestodbQuery.ts
packages/cubejs-testing/test/smoke-cubesql.test.ts
rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/test/mod.rs
rust/cubesql/cubesql/src/compile/test/test_wrapper.rs

**Check List**
`if limit` condition in Jinja will fail for both `None` and `Some(0)`
This is more or less fine for offset, but completely wrong for limit. For consistency both are changed.

fix: Render LIMIT 0 and OFFSET 0 properly in SQL templates

---

docs/pages/product/caching/using-pre-aggregations.mdx
rust/cubestore/cubestore/src/metastore/mod.rs

This change improves the cube store preaggregation creation: the default index for a preaggregation now excludes all measures from the sorting keys
**Check List**

fix(cubestore): don't add all measures to default preagg index

---

packages/cubejs-backend-shared/src/env.ts
packages/cubejs-base-driver/package.json
packages/cubejs-base-driver/src/BaseDriver.ts
packages/cubejs-snowflake-driver/src/SnowflakeDriver.ts
yarn.lock

This PR improves the Snowflake driver:
* Support for DefaultAzureCredential()
**Check List**

feat(snowflake-driver): support DefaultAzureCredential and Managed Identity auth for export bucket

---

docs/pages/product/deployment/cloud/byoc/aws.mdx

docs: update the list of AWS credentials required for BYOC

---

rust/cubestore/cubestore/src/metastore/rocks_store.rs

The number of threads RocksDB will use for all background operations. Even if you increase the max_background_jobs but keep parallelism as 1, it won’t lead to a lot of performance increase. Ideally, this option should be kept equal to the number of cores in your machine.
max_background_jobs is 2, but parallelism was 1. Must be aligned.

fix(cubestore): Metastore - increase parallelism to 2 (align with max background jobs)

---

packages/cubejs-databricks-jdbc-driver/src/DatabricksQuery.ts

**Check List**
This PR changes `TRUNC` SQL push down definition for Databricks, as in Databricks `TRUNC` has an entirely different meaning, working with dates instead of numbers. There's no alternative, so `CASE` is required to emulate behavior.

fix(cubesql): Fix `TRUNC` SQL push down for Databricks

---

rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs
rust/cubesql/cubesql/src/compile/test/test_user_change.rs

**Check List**
This PR ignores `__user IS NOT NULL` filter expression when replacing filters for Cube. The filter is redundant and has no effect, but forces SQL push down without the fix. Related test is included.

fix(cubesql): Ignore `__user IS NOT NULL` filter

---

.gitignore
packages/cubejs-api-gateway/src/gateway.ts
packages/cubejs-api-gateway/src/helpers/prepareAnnotation.ts
packages/cubejs-api-gateway/test/index.test.ts
packages/cubejs-api-gateway/test/mocks.ts
packages/cubejs-schema-compiler/src/compiler/CompilerCache.ts
packages/cubejs-schema-compiler/src/compiler/CubeEvaluator.ts
packages/cubejs-schema-compiler/src/compiler/CubeSymbols.js
packages/cubejs-schema-compiler/src/compiler/CubeValidator.ts
packages/cubejs-schema-compiler/src/compiler/YamlCompiler.ts
packages/cubejs-schema-compiler/src/compiler/transpilers/CubePropContextTranspiler.ts
packages/cubejs-schema-compiler/src/compiler/utils.ts
packages/cubejs-schema-compiler/test/unit/schema.test.ts
packages/cubejs-schema-compiler/test/unit/utils.ts
packages/cubejs-schema-compiler/test/unit/yaml-schema.test.ts
packages/cubejs-server-core/src/core/CompilerApi.js
packages/cubejs-server-core/src/core/optionsValidate.ts
packages/cubejs-server-core/src/core/server.ts
packages/cubejs-server-core/src/core/types.ts
packages/cubejs-server-core/test/unit/index.test.ts
packages/cubejs-testing/birdbox-fixtures/rbac/cube.js
packages/cubejs-testing/birdbox-fixtures/rbac/model/cubes/line_items.js
packages/cubejs-testing/birdbox-fixtures/rbac/model/cubes/orders.js
packages/cubejs-testing/birdbox-fixtures/rbac/model/cubes/orders_open.yaml
packages/cubejs-testing/birdbox-fixtures/rbac/model/cubes/users.yaml
packages/cubejs-testing/birdbox-fixtures/rbac/model/views/views.yaml
packages/cubejs-testing/package.json
packages/cubejs-testing/test/__snapshots__/smoke-rbac.test.ts.snap
packages/cubejs-testing/test/smoke-cubesql.test.ts
packages/cubejs-testing/test/smoke-rbac.test.ts

This commit introduces a new style Role Based Access Control framework
for cubes. User can now define `accessPolicies` on Cubes and Views which
will be evaluated into `queryRewrite` and visibility rules.
This commit introduces a new config: `contextToRoles(context):
string[]`. It should return a list of user role names based on the
request context. Access Policies are defined per Cube x Role name like
```
access_policy:
- role: "manager"
conditions:
- if "{ security_context.isNotSuspended }"
row_level:
filters:
- member: `access_level`
operator: lt
values: [2]
member_level:
includes: "*"
excludes: [`top_secret_field`]
```
Each policy can define a `row_level` and `member_level` rules.
Row level rules can be defined as a list of filters or `allow_all: true`
Member level rules should specify …

feat: new style RBAC framework

---

packages/cubejs-backend-shared/src/env.ts
packages/cubejs-snowflake-driver/src/SnowflakeDriver.ts

feat(snowflake-driver): OAuth token path support

---

packages/cubejs-backend-shared/src/env.ts
rust/cubesql/cubesql/src/compile/rewrite/rewriter.rs
rust/cubesql/cubesql/src/config/mod.rs

BREAKING CHANGE: Enabling `CUBESQL_SQL_PUSH_DOWN` is backward incompatible to many default behaviors of SQL API
**Check List**

feat: Enable `CUBESQL_SQL_PUSH_DOWN` by default

---

packages/cubejs-firebolt-driver/package.json
packages/cubejs-firebolt-driver/src/FireboltDriver.ts
yarn.lock

**Check List**
Delegating connection verification to the Firebolt SDK driver. This allows more flexibility and more importantly avoids unnecessary charges to Firebolt's customers: Firebolt engines have auto-stop functionality that allows them to spin down when not in use. However, healthcheck queries can keep them up, despite not having any useful load. Firebolt's SDK provides a way to check if the connection is working without resetting the auto-stop timer. If the engine is down or there are connectivity errors `testConnection` will still error out, as before.

feat(Firebolt): Use driver's own test connection method

---

packages/cubejs-backend-shared/src/env.ts
packages/cubejs-base-driver/src/BaseDriver.ts

feat(base-driver): add an option to skip connection test probes

---

packages/cubejs-backend-native/Cargo.lock
rust/cubenativeutils/Cargo.lock
rust/cubesql/Cargo.lock
rust/cubesql/cubesql/Cargo.toml
rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/query_engine.rs
rust/cubesql/cubesql/src/compile/rewrite/cost.rs
rust/cubesql/cubesql/src/compile/rewrite/rewriter.rs
rust/cubesql/cubesql/src/config/mod.rs
rust/cubesqlplanner/Cargo.lock

**Check List**
This PR adds a top-down extractor for e-graphs in addition to the previously used bottom-up extractor. This allows extracting nodes from e-classes with respect to their state. Use flag `CUBESQL_TOP_DOWN_EXTRACTOR=true` to enable.

feat(cubesql): Top-down extractor for rewrites

---

packages/cubejs-bigquery-driver/src/BigQueryDriver.ts

Optimize `testConnection()` with free of charge request instead of `SELECT 1`
**Check List**

feat(bigquery-driver): optimize testConnection() with free of charge request

---

packages/cubejs-redshift-driver/src/RedshiftDriver.ts

Optimize testConnection() with just establishing a db connection without performing the `SELECT 1` query which makes serverless instances to keep running...
**Check List**

feat(redshift-driver): optimize testConnection() with just establishing connection without real query

---

packages/cubejs-api-gateway/src/gateway.ts
packages/cubejs-api-gateway/test/auth.test.ts

fix: return client customized error, if present, on auth fail in playground
fixes #CORE-1134

fix: return client customized error, if present, on auth fail in playground

---

.editorconfig
rust/cubesql/cubesql/egraph-debug-template/package.json
rust/cubesql/cubesql/egraph-debug-template/src/index.js
rust/cubesql/cubesql/src/compile/rewrite/analysis.rs
rust/cubesql/cubesql/src/compile/rewrite/rewriter.rs

**Check List**
Various improvements to EGraph debugger:
* Used JSON instead of JS to store debug data
* Move data collection from `IterationData` to analysis, to store and access initial EGraph state
* Fixed some hooks dependencies
* Enabled prettier
* Enabled eslint

refactor(cubesql): Improve EGraph debugger, part 1: initial state, JSON for data, eslint, prettier, hooks deps, 

---

rust/cubesql/cubesql/egraph-debug-template/package.json
rust/cubesql/cubesql/egraph-debug-template/src/index.js
rust/cubesql/cubesql/egraph-debug-template/src/index.tsx
rust/cubesql/cubesql/egraph-debug-template/tsconfig.json
rust/cubesql/cubesql/src/compile/rewrite/rewriter.rs

**Check List**
Various improvements to EGraph debugger:
* Port to TypeScript
* Lots of small changed for proper typing
* Moved ELK to worker. Now UI stays responsive while ELK is working on layout
* Add simple cleanup for layout effect. Now user don't have to wait for ALL animations triggered for layouts, only for last one.

refactor(cubesql): Improve EGraph debugger, part 2: TypeScript, ELK in worker, simplify ReactFlow <-> ELK interop

---

packages/cubejs-backend-shared/src/env.ts
packages/cubejs-snowflake-driver/src/SnowflakeDriver.ts

**Check List**
[Snowpark docs: connecting to snowflake from inside a container](https://docs.snowflake.com/en/developer-guide/snowpark-container-services/additional-considerations-services-jobs#connecting-to-snowflake-from-inside-a-container)
> When creating a connection to Snowflake from a container, you must use SNOWFLAKE_HOST, SNOWFLAKE_ACCOUNT, and the OAuth token. You cannot use the OAuth token without also using SNOWFLAKE_HOST, and you cannot use the OAuth token outside Snowpark Container Services.

feat(snowflake-driver): host env variable

---

lerna-publish.sh

Lerna uses single push for tag & commit, which breaks GitHub logic for detection of `github.event.base_ref`.

chore: Release script - push tag and commit manually

---

rust/cubesql/cubesql/src/sql/postgres/extended.rs
rust/cubesql/cubesql/src/sql/postgres/shim.rs

**Check List**
This PR changes the behavior of `isDataQuery` flag, instead passing it as `false` by default on `Prepare` step, when query is parsed, and then passing the updated value only on `Execute` step. This avoids duplicated entries in query history for the same query with, for instance, Tablaeu, which would parse the query and get its meta result first, then repeat the same steps, but next time execute the query.

fix(cubesql): Don't show meta OLAP queries in query history

---

.github/workflows/publish.yml
.github/workflows/rust-cubesql.yml
.github/workflows/rust-cubestore-master.yml
.github/workflows/rust-cubestore.yml

**Check List**
Old actions used `node16` runtime, which is deprecated, and `actionlint` yells at me.
I've checked changelogs, nothing notable there.

ci: Bump GHA actions to modern runner

---

.github/workflows/rust-cubesql.yml
rust/cubesql/cubesql/src/compile/mod.rs

ci(cubesql): Run unit tests for both top-down and bottom-up extractors

---

rust/cubestore/cubestore/src/config/mod.rs

chore(cubestore): Expose parts of Config::test for customization

---

rust/cubestore/README.md

chore(cubestore): Update cubestore README development section

---

packages/cubejs-backend-shared/src/env.ts

As SQL PUSH DOWN is now enabled by default this PR fixes one missed default value processing in convertTzForRawTimeDimension env flag.
**Check List**

fix(schema-compiler): set missed CUBESQL_SQL_PUSH_DOWN to true by default in convertTzForRawTimeDimension flag

---

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-schema-compiler/test/unit/base-query.test.ts

fix(schema-compiler): fix Maximum call stack size exceeded if FILTER_PARAMS are used inside dimensions/measures

---

packages/cubejs-playground/src/pages/Schema/SchemaPage.tsx

This fixes incorrect version checking for yaml data model generation in PG (as v1.0 was treated < 0.31)
This fixes #8943

fix(playground): fix version check for yaml model generation

---

rust/cubesql/cubesql/e2e/tests/postgres.rs

I figured out that CI is broken for contributors. I am not totally sure, but I belive it's related to that env variables are defined, while being empty.
https://github.com/cube-js/cube/pull/8947

chore(cubesql): E2E - check that env variables are not empty

---

packages/cubejs-jdbc-driver/src/JDBCDriver.ts
packages/cubejs-testing-drivers/src/helpers/getDriver.ts

**Check List**
`generic-pool` will just silently throw those away, so we should at least log them

fix(jdbc-driver): Log errors from connection pool factory

---

packages/cubejs-base-driver/src/BaseDriver.ts
packages/cubejs-testing-drivers/fixtures/databricks-jdbc.json
packages/cubejs-testing-drivers/test/__snapshots__/databricks-jdbc-export-bucket-azure-full.test.ts.snap

Fix databricks bucket URL parsing. Now driver supports both (legacy and modern urls)
This PR also fixes incorrect processing of databricks preaggregations exported to azure.
> The legacy Windows Azure Storage Blob driver (WASB) has been deprecated. ABFS has numerous benefits over WASB. See [Azure documentation on ABFS](https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-abfs-driver). For documentation for working with the legacy WASB driver, see [Connect to Azure Blob Storage with WASB (legacy)](https://learn.microsoft.com/en-us/azure/databricks/archive/storage/wasb-blob).

fix(databricks-driver): fix databricks bucket URL parsing. Now driver supports both (legacy and modern urls)

---

packages/cubejs-backend-shared/src/env.ts
packages/cubejs-backend-shared/test/env.test.ts
packages/cubejs-base-driver/src/BaseDriver.ts
packages/cubejs-clickhouse-driver/package.json
packages/cubejs-clickhouse-driver/src/ClickHouseDriver.ts
packages/cubejs-clickhouse-driver/src/HydrationStream.ts
packages/cubejs-clickhouse-driver/test/ClickHouseDriver.test.ts
packages/cubejs-testing-drivers/src/tests/testQueries.ts
yarn.lock

**Check List**
Switch client library used to talk to ClickHouse to upstream one. Lots of related changes:
* Streaming now does not use streaming JSON parser, so we can't rely on `meta` field in JSON format. Instread it relies on `JSONCompactEachRowWithNamesAndTypes`: first two rows returned should contain names and types. https://clickhouse.com/docs/en/sql-reference/formats#jsoncompacteachrowwithnamesandtypes
* Streaming now use async iterators instread of Node.js streams internally. External API returns stream, as before
* Pooling moved completely to client library. `generic-pool` is not used at all, `dbMaxPoolSize`  is passed to client library to limit open sockets. New client maintains `http.Agent` internally, and …

feat(clickhouse-driver): Switch from apla-clickhouse to @clickhouse/client

---

rust/cubesql/cubesql/src/compile/engine/df/wrapper.rs
rust/cubesql/cubesql/src/compile/test/test_wrapper.rs

**Check List**
#8967
cubesql can introduce `ScalarValue::TimestampNanosecond(..., Some("UTC"))` during constant folding, and `generate_sql_for_expr` trips on unsupported timezones.
This PR just allows `None` as well as `Some("UTC")` as timezones. Because DataFusion will always generate `UTC`, it should be fine for now.
See https://github.com/cube-js/arrow-datafusion/blob/dcf3e4aa26fd112043ef26fa4a78db5dbd443c86/datafusion/physical-expr/src/datetime_expressions.rs#L357-L367

fix(cubesql): Support explicit UTC as timezone in pushdown SQL generation

---

rust/cubesql/cubesql/src/compile/engine/df/scan.rs

This PR fixes timestamp parsing handling unwrapping that may lead to panic:
```
thread 'tokio-runtime-worker' panicked at cube/rust/cubesql/cubesql/src/compile/engine/df/scan.rs:1133:86:
called `Option::unwrap()` on a `None` value
```
**Check List**

fix(cubesql): fix unhandled timestamp unwrapping in df/transform_response

---

packages/cubejs-backend-shared/src/env.ts
packages/cubejs-pinot-driver/src/PinotDriver.ts

This PR adds optional Auth and database headers to driver requests if related env vars are set (CUBEJS_DB_NAME, CUBEJS_DB_PINOT_AUTH_TOKEN)
**Check List**

feat(pinot-driver): add optional Auth headers

---

docs/pages/product/workspace/environments.mdx

docs: Update Staging Environments docs

---

packages/cubejs-server-core/src/core/CompilerApi.js
packages/cubejs-testing/test/smoke-rbac.test.ts

fix: ensure public is in sync with isVisible when using DAP

---

packages/cubejs-schema-compiler/src/adapter/PreAggregations.js
packages/cubejs-schema-compiler/test/unit/pre-aggregations.test.ts

This PR fixes the incorrect SQL query generation for queries using preaggregation with `type: rollup_lambda`, which include dimensions from the joined cubes.
**Check List**

fix(schema-compiler): Undefined columns for lambda pre-aggregation queries referencing dimensions from joined cubes

---

packages/cubejs-databricks-jdbc-driver/src/DatabricksQuery.ts
packages/cubejs-duckdb-driver/src/DuckDBQuery.ts
packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-schema-compiler/src/adapter/ClickHouseQuery.ts
packages/cubejs-schema-compiler/src/adapter/CubeStoreQuery.ts
packages/cubejs-schema-compiler/src/adapter/Granularity.ts
packages/cubejs-schema-compiler/src/adapter/MssqlQuery.ts
packages/cubejs-schema-compiler/src/adapter/MysqlQuery.ts
packages/cubejs-schema-compiler/src/adapter/OracleQuery.ts
packages/cubejs-schema-compiler/src/adapter/SnowflakeQuery.ts
packages/cubejs-schema-compiler/test/integration/mssql/mssql-pre-aggregations.test.ts
packages/cubejs-schema-compiler/test/unit/base-query.test.ts
packages/cubejs-schema-compiler/test/unit/pre-agg-time-dim-match.test.ts

fix(schema-compiler): use query timezone for time granularity origin

---

rust/cubestore/Cargo.lock
rust/cubestore/cubestore/Cargo.toml
rust/cubestore/cubestore/src/cluster/mod.rs
rust/cubestore/cubestore/src/cluster/worker_pool.rs
rust/cubestore/cubestore/src/cluster/worker_services.rs
rust/cubestore/cubestore/src/telemetry/tracing.rs

This PR also adds the ability to setup worker teardown callback

chore(cubestore): make trace_id and span_id suitable for open telemetry.

---

docs/pages/product/apis-integrations/ai-api.mdx
docs/pages/product/workspace/ai-assistant.mdx
docs/pages/reference/ai-api.mdx

Adds documentation for new AI API and Assistant features:
* Chart generation
* Custom prompts
* Meta tags
* Other LLM providers

docs: ai api updates

---

rust/cubestore/Cargo.lock
rust/cubestore/cubestore-sql-tests/src/tests.rs
rust/cubestore/cubestore/src/metastore/table.rs

This includes test changes adding new sort_order information to expected pretty-print values, because of this (performance-related) bug fix: https://github.com/cube-js/arrow-datafusion/commit/b3acc9fd434cec56c2ba7b18f592a56e051ba616
**Check List**

perf(cubestore): Arrow Cargo.lock pointers for GroupsAccumulator changes

---

rust/cubestore/cubestore/src/config/mod.rs

fix(cubestore): Disable writing cachestore logs by default to reduce use of disk space

---

rust/cubesql/cubesql/src/compile/query_engine.rs
rust/cubesql/cubesql/src/compile/rewrite/rewriter.rs
rust/cubesql/cubesql/src/compile/router.rs
rust/cubesql/cubesql/src/sql/compiler_cache.rs
rust/cubesql/cubesql/src/sql/postgres/shim.rs

**Check List**
This PR restructures the way compiler cache works, removing the need to call async Node functions while planning, at the cost of passing around `compiler_id`.

chore(cubesql): Do not call async Node functions while planning

---

.github/workflows/publish.yml
.github/workflows/rust-cubestore-master.yml
.github/workflows/rust-cubestore.yml

**Check List**
macOS 12 runner is unsupported since 2024-12-03
See https://github.com/actions/runner-images/issues/10721

ci: Switch macos-12 runner to macos-13

---

rust/cubesql/cubesql/src/compile/rewrite/rules/members.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/wrapper/cube_scan_wrapper.rs
rust/cubesql/cubesql/src/compile/test/test_wrapper.rs

**Check List**
`Aggregate(CubeScan(limit=n))` is not equivalent to `CubeScan(aggregation, limit=n)`
Former does aggregation over first n rows, latter returns first n rows after aggregation.

fix(cubesql): Allow aggregation pushdown only for unlimited CubeScan

---

rust/cubesql/cubesql/src/compile/rewrite/analysis.rs
rust/cubesql/cubesql/src/compile/rewrite/converter.rs
rust/cubesql/cubesql/src/compile/rewrite/mod.rs

**Check List**
Extensions is used meaningfully only for CubeScan, but not for CubeScanWrapper. Both are first-class logical plan nodes for us, so Extension is not helpful in egraph

refactor(cubesql): Remove Extension from LogicalPlanLanguage::CubeScan

---

packages/cubejs-backend-native/Cargo.lock
rust/cubenativeutils/Cargo.lock
rust/cubesql/Cargo.lock
rust/cubesql/cubesql/Cargo.toml
rust/cubesql/cubesql/egraph-debug-template/package.json
rust/cubesql/cubesql/egraph-debug-template/src/index.tsx
rust/cubesql/cubesql/src/compile/rewrite/analysis.rs
rust/cubesql/cubesql/src/compile/rewrite/rewriter.rs
rust/cubesqlplanner/Cargo.lock

**Check List**
Add proper parsing on UI side, to catch data format changes.
Move most of data preparation related to UI (like a concepts of edge or combo) to UI completely, simplify data collection on rewriter side.

refactor(cubesql): Improve EGraph debugger, part 3: parsing and data preparation in UI side

---

rust/cubestore/cubestore/src/util/metrics.rs

**Check List**
Fix annoying warning about `shared reference of mutable static is discouraged`

refactor(cubestore): Use OnceLock for GLOBAL_SINK

---

packages/cubejs-api-gateway/src/gateway.ts
packages/cubejs-testing/birdbox-fixtures/rbac/cube.js
packages/cubejs-testing/birdbox-fixtures/rbac/model/cubes/users.yaml
packages/cubejs-testing/test/__snapshots__/smoke-rbac.test.ts.snap
packages/cubejs-testing/test/smoke-rbac.test.ts

fixes an issue when processing queries with member expressions
**Check List**

fix(api-gateway): make sure DAP works with sql pushdown

---

packages/cubejs-api-gateway/src/gateway.ts
packages/cubejs-server-core/src/core/CompilerApi.js
packages/cubejs-testing/birdbox-fixtures/rbac-python/cube.py
packages/cubejs-testing/birdbox-fixtures/rbac-python/model/cubes/users.yaml
packages/cubejs-testing/src/birdbox.ts
packages/cubejs-testing/test/__snapshots__/smoke-rbac.test.ts.snap
packages/cubejs-testing/test/smoke-rbac.test.ts

fix(schema-compiler): fix DAP with query_rewrite and python config

---

packages/cubejs-firebolt-driver/src/FireboltDriver.ts
packages/cubejs-firebolt-driver/test/autostart.test.ts

Backporting https://github.com/cube-js/cube/pull/9001 to stable

feat(firebolt): Automatically start the engine after connection (#9001)

---

rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/converter.rs
rust/cubesql/cubesql/src/compile/rewrite/mod.rs
rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__values_literal_table.snap

**Check List**
This PR adds basic support for VALUES logical plan node in rewrite engine. Related test is included.

feat(cubesql): Basic VALUES support in rewrite engine

---

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-schema-compiler/src/adapter/BigqueryQuery.ts
packages/cubejs-schema-compiler/src/adapter/PostgresQuery.ts
packages/cubejs-schema-compiler/src/adapter/SnowflakeQuery.ts
packages/cubejs-schema-compiler/test/integration/postgres/multi-fact-join.test.ts
rust/cubesqlplanner/cubesqlplanner/src/cube_bridge/join_item.rs
rust/cubesqlplanner/cubesqlplanner/src/plan/builder/join.rs
rust/cubesqlplanner/cubesqlplanner/src/plan/filter.rs
rust/cubesqlplanner/cubesqlplanner/src/plan/join.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/base_measure.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/base_query.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/planners/full_key_query_aggregate_planner.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/planners/join_planner.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/planners/multi_stage/member_query_planner.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/planners/multiplied_measures_query_planner.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/planners/simple_query_planer.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/query_properties.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/query_tools.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/sql_evaluator/collectors/multiplied_measures_collector.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/sql_evaluator/compiler.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/sql_templates/plan.rs

feat(tesseract): Support multiple join paths within single query

---

docs/pages/product/apis-integrations/ai-api.mdx
docs/pages/product/workspace/ai-assistant.mdx

docs(ai): adds value search section

---

packages/cubejs-api-gateway/src/gateway.ts
packages/cubejs-api-gateway/test/mocks.ts
packages/cubejs-server-core/src/core/CompilerApi.js
packages/cubejs-testing/birdbox-fixtures/rbac-python/model/cubes/products.yaml
packages/cubejs-testing/birdbox-fixtures/rbac/model/cubes/products.yaml
packages/cubejs-testing/test/__snapshots__/smoke-rbac.test.ts.snap
packages/cubejs-testing/test/smoke-rbac.test.ts

fix(api-gateway): fix DAP RLS issue with denied queries and python conf

---

packages/cubejs-backend-native/js/index.ts
packages/cubejs-backend-native/test/config.py
packages/cubejs-backend-native/test/python.test.ts

This is necessary for `extend_context`. By the time `extendContext` is called, `req` in JS-land is already extended with `securityContext` after `checkAuth`, and JS config receives it with extensions.
**Check List**
#8753
This is necessary for `extend_context`. By the time `extendContext` is called, `req` in JS-land is already extended with `securityContext` after `checkAuth`, and JS config receives it with extensions.

fix(backend-native): Pass req.securityContext to Python config

---

docs/pages/product/configuration/data-sources/snowflake.mdx

**Check List**
Instrucctions for **_feat(snowflake-driver): support azure exports buckets_** #8730

docs: Add Azure blob storage instructions to Snowflake

---

.github/pull_request_template.md
packages/cubejs-schema-compiler/src/adapter/Granularity.ts
packages/cubejs-schema-compiler/test/integration/clickhouse/custom-granularities.test.ts
packages/cubejs-schema-compiler/test/integration/mssql/custom-granularities.test.ts
packages/cubejs-schema-compiler/test/integration/mysql/custom-granularities.test.ts
packages/cubejs-schema-compiler/test/integration/postgres/custom-granularities.test.ts
packages/cubejs-testing-drivers/fixtures/_schemas.json

This PR fixes incorrect TD granularity formatting in the query timezone.
**Check List**

fix(schema-compiler): fix time dimension granularity origin formatting in local timezone

---

packages/cubejs-dremio-driver/package.json

**Check List**
`dremio-driver` has old version of intra-repo dependency, and is stuck to it: lerna won't upgrade it, thinking that's intended. Also this is the reason of unnecessary diff in `yarn.lock`.
Strangely, we are using `yarn install --frozen-lockfile` in CI, but it finish successfully, and does not change lockfile.

fix(dremio-driver): Fix stale version of testing-shared dependency

---

packages/cubejs-clickhouse-driver/src/ClickHouseDriver.ts

Add the ability to override the username and password from the driver configuration. Currently, when using multiple data sources for different tenants ([Multitenancy vs Multiple Data Sources](https://cube.dev/docs/product/configuration/advanced/multitenancy#multitenancy-vs-multiple-data-sources)) it is not possible to use the username and password defined in the `ClickHouseDriver` config instead of the default ENV variables CUBEJS_DB_USER, CUBEJS_DB_PASS
**Check List**

fix(clickhouse-driver): Support overriding Username & Password from Driver Config

---

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-schema-compiler/test/integration/postgres/sql-generation.test.ts

**Check List**
If dimension is member expression, `d.dimension` would be object, and key would be `[object Object]` string, so separate dimensions would have same key, and all but one will be eliminated

fix(schema-compiler): Handle member expressions in keyDimensions

---

packages/cubejs-api-gateway/src/gateway.ts

Make dry-run return pre-rewrittien queries

fix(gateway): dryRun to return  pre-rewritten queries

---

packages/cubejs-client-ws-transport/src/index.ts

**Check List**
Before this there were a race between `setTimeout` in `sendMessage` and `close`. Even for a good citizen, that calls `unsubscribe()` and awaits result there were no synchronization between unsubscribe adding message to `messageQueue` and restarting timer, and actually sending this message to WebSocket. When `close()` is called close frame is sent immediately to WebSocket. If at that moment messageQueue is not empty, and timer is armed it can wake up, and discover socket in CLOSING state: send side closed, recv side open.
For now - just flush everything queued, and send close frame after, so it would look like close was queued after. More complete solution is to add synchronization between unsubscribe call …

fix(client-ws-transport): Flush send queue in close() to avoid race

---

packages/cubejs-docker/dev.Dockerfile
packages/cubejs-docker/latest-debian-jdk.Dockerfile
packages/cubejs-docker/latest.Dockerfile
packages/cubejs-docker/local.Dockerfile

By default node-gyp looks only for `python` and `python3` executables, and python3.11 package installs only `python3.11` That leads to failure during installation optional dependency `java` from NPM even in `-jdk` image
Without `python3` executable `java` fails during installation, and because it is marked optional, installation is successful.
But later, at runtime any JDBC driver would fail with `Cannot find module 'java'`, even in image with JDK installed.
This PR installs `python3` executable, as expected by node-gyp, but there are alternative aproaches:
* Use `PYTHON` environment variable
* Use `npm/yarn config set python`, but that is not supported in NPM 9 and newer (See …

fix: Install python3 executable for node-gyp

---

rust/cubesql/cubesql/src/compile/rewrite/cost.rs

fix(cubesql): Add forgotten Distinct in ast_size_outside_wrapper cost component

---

rust/cubesql/cubesql/benches/benchmarks.rs
rust/cubesql/cubesql/src/compile/rewrite/language.rs
rust/cubesql/cubesql/src/compile/rewrite/mod.rs

**Check List**
* Add separate cheaper error type, without backtrace and input part
* Avoid run-time formatting to add `:`
* Avoid calls to replace when `strip_prefix` + `to_string` is enough
On my laptop it gives this:
`cargo bench -- rules_loading`
from ~21.5 ms to ~5.5 ms
`cargo test` reported time for `Running unittests src/lib.rs`
from ~49s to ~35s
`cargo test --release` reported time for `Running unittests src/lib.rs`
from ~6.9s to ~3.5s

perf(cubesql): Improve rules loading perf

---

rust/cubesql/cubesql/src/compile/rewrite/rules/wrapper/wrapper_pull_up.rs

fix(cubesql): Pass proper in_projection flag in non-trivial wrapper pull up rule

---

rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs
rust/cubesql/cubesql/src/compile/test/mod.rs
rust/cubesql/cubesql/src/compile/test/test_filters.rs

fix(cubesql): Fix condition for joining two date range filters

---

packages/cubejs-schema-compiler/.eslintignore
packages/cubejs-schema-compiler/src/compiler/CubeEvaluator.ts
packages/cubejs-schema-compiler/src/compiler/CubeSymbols.js
packages/cubejs-schema-compiler/src/compiler/CubeValidator.ts
packages/cubejs-schema-compiler/src/compiler/YamlCompiler.ts
packages/cubejs-schema-compiler/src/compiler/transpilers/CubePropContextTranspiler.ts
packages/cubejs-schema-compiler/test/unit/fixtures/orders.js
packages/cubejs-schema-compiler/test/unit/hierarchies.test.ts

Hierarchies are defined as objects in js models instead of arrays for consistency with other members
```
hierarchies: {
hello: {
title: 'World',
levels: [status],
},
},
```

fix(schema-compiler): update hierarchies handling to use object pattern

---

docs/pages/product/configuration/data-sources/databricks-jdbc.mdx
docs/pages/reference/configuration/environment-variables.mdx
packages/cubejs-backend-shared/src/env.ts
packages/cubejs-backend-shared/test/db_env_multi.test.ts
packages/cubejs-backend-shared/test/db_env_single.test.ts
packages/cubejs-base-driver/src/BaseDriver.ts
packages/cubejs-databricks-jdbc-driver/README.md
packages/cubejs-databricks-jdbc-driver/package.json
packages/cubejs-databricks-jdbc-driver/src/DatabricksDriver.ts
packages/cubejs-databricks-jdbc-driver/test/DatabricksDriver.test.ts

This PR supersedes the original PR by @MaggieZhang-01 https://github.com/cube-js/cube/pull/6763, rebased on the latest master and resolves all the conflicts.
**Check List**
In the Databricks driver, the credential is generated by the Azure storage account access key now which provides full access to the storage account. For security best practice, Microsoft recommends using authorization with Azure Active Directory.
This PR supports Azure AD authentication via service principal, providing more fine-grained control over access to storage resources.
Closes https://github.com/cube-js/cube/pull/6763

feat(databricks-driver): Enable Azure AD authentication via Client Secret

---

packages/cubejs-prestodb-driver/src/PrestoDriver.ts

Use `get nodes()` REST API Request query for testing connection instead of a heavy one `show catalogs like ?`
**Check List**

fix(presto-driver): Optimize testConnection() to issue <get Nodes()> instead of heavy show catalogs query

---

packages/cubejs-mysql-driver/src/MySqlDriver.ts
packages/cubejs-mysql-driver/test/MySqlDriver.test.ts
packages/cubejs-oracle-driver/driver/OracleDriver.js
packages/cubejs-postgres-driver/src/PostgresDriver.ts
packages/cubejs-postgres-driver/test/PostgresDriver.test.ts
packages/cubejs-redshift-driver/src/RedshiftDriver.ts

The check for the table name length is been moved to the driver from query class, thus it is enforced
ony for specific datasources.
**Check List**

fix(schema-compiler): move create table name check to underlying driver for Postgres, MySQL, Oracle

---

docs/pages/product/configuration/data-sources/mysql.mdx
docs/pages/reference/configuration/environment-variables.mdx
packages/cubejs-api-gateway/package.json
packages/cubejs-backend-shared/package.json
packages/cubejs-backend-shared/src/env.ts
packages/cubejs-cubestore-driver/package.json
packages/cubejs-dremio-driver/driver/DremioQuery.js
packages/cubejs-dremio-driver/package.json
packages/cubejs-dremio-driver/test/DremioQuery.test.ts
packages/cubejs-druid-driver/package.json
packages/cubejs-druid-driver/src/DruidQuery.ts
packages/cubejs-query-orchestrator/package.json
packages/cubejs-schema-compiler/package.json
packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-schema-compiler/src/adapter/CubeStoreQuery.ts
packages/cubejs-schema-compiler/src/adapter/MysqlQuery.ts
packages/cubejs-vertica-driver/package.json
packages/cubejs-vertica-driver/src/VerticaQuery.js
yarn.lock

Remove unneeded moment-timezone dependency and use timezone names for tz conversions
**Check List**

feat(schema-compiler): Add flag for using named timezones in MySQL Query class

---

.github/workflows/cloud.yml
.github/workflows/drivers-tests.yml
.github/workflows/post-release.yml

- **fix post-release ci job**
- **fix cloud tests ci mb?**

chore(ci): Fix post-release and cloud db tests ci workflows

---

packages/cubejs-client-ngx/README.md
packages/cubejs-client-ngx/angular.json
packages/cubejs-client-ngx/package.json
packages/cubejs-client-ngx/src/query-builder/query-members.ts
packages/cubejs-client-ngx/tsconfig.json
packages/cubejs-client-ngx/tsconfig.prod.json
packages/cubejs-playground/src/hooks/deep-compare-memoize.ts

This pull request updates the `@cubejs-client/ngx` library to fix its outdated Angular Package Format (APF) configuration and ensure compatibility with Angular 12+. Key changes include aligning the build and TypeScript settings with Angular 13 standards, updating the README to reflect the new minimum Angular version, and switching the `fast-deep-equal` import paths to ES6 modules. These fixes resolve build errors and maintain backward compatibility for projects on older Angular versions.
#9140

fix(@cubejs-client/ngx): Update APF configuration and build settings for Angular 12+ compatibility

---

rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs
rust/cubesql/cubesql/src/compile/test/test_filters.rs

fix(cubesql): Avoid panics during filter rewrites

---

packages/cubejs-schema-compiler/src/compiler/DataSchemaCompiler.js
packages/cubejs-schema-compiler/src/compiler/PrepareCompiler.ts
packages/cubejs-schema-compiler/src/compiler/ViewCompilationGate.ts
packages/cubejs-schema-compiler/src/compiler/YamlCompiler.ts
packages/cubejs-schema-compiler/src/compiler/transpilers/CubePropContextTranspiler.ts
packages/cubejs-testing/birdbox-fixtures/rbac-python/model/views/users_view.yaml
packages/cubejs-testing/birdbox-fixtures/rbac/model/views/users.js
packages/cubejs-testing/test/__snapshots__/smoke-rbac.test.ts.snap
packages/cubejs-testing/test/smoke-rbac.test.ts
yarn.lock

fix(schema-compiler): make sure view members are resolvable in DAP

---

docs/pages/product/deployment/cloud/byoc/_meta.js
docs/pages/product/deployment/cloud/byoc/azure.mdx

docs: Azure BYOC Deployment doc

---

.github/workflows/push.yml
packages/cubejs-backend-shared/src/env.ts
packages/cubejs-schema-compiler/package.json
packages/cubejs-schema-compiler/src/compiler/CubeSymbols.js
packages/cubejs-schema-compiler/src/compiler/DataSchemaCompiler.js
packages/cubejs-schema-compiler/src/compiler/ErrorReporter.ts
packages/cubejs-schema-compiler/src/compiler/PrepareCompiler.ts
packages/cubejs-schema-compiler/src/compiler/transpilers/CubePropContextTranspiler.ts
packages/cubejs-schema-compiler/src/compiler/transpilers/LightweightNodeCubeDictionary.ts
packages/cubejs-schema-compiler/src/compiler/transpilers/LightweightSymbolResolver.ts
packages/cubejs-schema-compiler/src/compiler/transpilers/transpiler.interface.ts
packages/cubejs-schema-compiler/src/compiler/transpilers/transpiler_worker.ts
yarn.lock

Parsing and transpiling huge data modes takes a significant amount of time and blocks the node event loop.
This PR tries to improve this.
Some charts are below. It has ~300 model files with ~400 members each.
**Before:**
**After: Non-blocking sequential processing using 1 thread**
**After: Non-blocking parallel processing using N threads** (default to the number of CPU's minus one, in my case 5)
**Check List**

feat(schema-compiler): Move transpiling to worker threads (under the flag)

---

packages/cubejs-backend-shared/src/time.ts
packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-schema-compiler/src/adapter/BaseTimeDimension.ts
packages/cubejs-schema-compiler/src/adapter/Granularity.ts
packages/cubejs-schema-compiler/src/adapter/PreAggregations.js
packages/cubejs-schema-compiler/src/compiler/CubeEvaluator.ts
packages/cubejs-schema-compiler/test/integration/postgres/pre-agg-allow-non-strict.test.ts
packages/cubejs-schema-compiler/test/integration/postgres/pre-aggregations.test.ts
packages/cubejs-schema-compiler/test/unit/pre-agg-time-dim-match.test.ts

This fixes queries with time dimensions but without granularities that don't hit pre-aggregations having set allow_non_strict_date_range_match=true.
**Check List**

fix(schema-compiler): Fix queries with time dimensions without granularities don't hit pre-aggregations with allow_non_strict_date_range_match=true

---

rust/cubesql/cubesql/src/compile/query_engine.rs
rust/cubesql/cubesql/src/sql/postgres/shim.rs
rust/cubesql/cubesql/src/sql/session.rs

This PR adds `api_type` argument to `get_load_request_meta` function, allowing to provide a custom API type.

feat(cubesql): Allow providing API type when getting load request meta

---

packages/cubejs-athena-driver/src/AthenaDriver.ts
packages/cubejs-backend-shared/src/env.ts
packages/cubejs-clickhouse-driver/src/ClickHouseDriver.ts
packages/cubejs-databricks-jdbc-driver/src/DatabricksDriver.ts
packages/cubejs-firebolt-driver/src/FireboltDriver.ts
packages/cubejs-pinot-driver/src/PinotDriver.ts
packages/cubejs-redshift-driver/src/RedshiftDriver.ts
packages/cubejs-server-core/src/core/OptsHandler.ts
packages/cubejs-server-core/test/unit/OptsHandler.test.ts
packages/cubejs-snowflake-driver/src/SnowflakeDriver.ts

- Add **CUBEJS_SCHEDULED_REFRESH_QUERIES_PER_APP_ID**
- Deprecate **CUBEJS_SCHEDULED_REFRESH_CONCURRENCY**
- **increase DefaultConcurrency settings for drivers**
- **use refreshWorkerConcurrency only for refresh workers**
**Check List**

feat(server-core): Introduce CUBEJS_REFRESH_WORKER_CONCURRENCY env and update default concurrency settings for drivers

---

packages/cubejs-backend-native/python/cube/src/__init__.py
packages/cubejs-backend-native/src/python/cube_config.rs
packages/cubejs-server-core/src/core/optionsValidate.ts
packages/cubejs-server-core/src/core/server.ts
packages/cubejs-server-core/src/core/types.ts

feat(cubejs-server-core): add contextToCubeStoreRouterId config option

---

rust/cubesql/cubesql/src/compile/rewrite/rules/wrapper/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/wrapper/projection.rs
rust/cubesql/cubesql/src/compile/test/test_wrapper.rs

**Check List**
Allow to flatten projection node into internal WrappedSelect. This should allow to execute plans like Projection(Filter(...)) as a single ungrouped wrapper with push-to-Cube

feat(cubesql): Add projection flattening rule

---

docs/pages/product/configuration/data-sources/pinot.mdx
docs/pages/reference/configuration/environment-variables.mdx
packages/cubejs-backend-shared/src/env.ts
packages/cubejs-pinot-driver/src/PinotDriver.ts

feat(pinot-driver): Add `enableNullHandling` to query options using env var

---

rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/members.rs

This PR fixes correct Cube query generation for `SELECT DISTINCT xxxx` queries via SQL API.
**Check List**

fix(cubesql): Fix SELECT DISTINCT on pushdown

---

packages/cubejs-server-core/src/core/CompilerApi.js
packages/cubejs-testing/birdbox-fixtures/rbac/cube.js
packages/cubejs-testing/birdbox-fixtures/rbac/model/cubes/line_items.js
packages/cubejs-testing/test/__snapshots__/smoke-rbac.test.ts.snap
packages/cubejs-testing/test/smoke-rbac.test.ts
yarn.lock

 fix(cubejs-server-core): fix schema caching in SQL API with DAP on

---

packages/cubejs-testing/test/driver-postgres.test.ts
packages/cubejs-testing/test/driver-test-suite.ts
packages/cubejs-testing/test/driverTests/driverTest.ts
packages/cubejs-testing/test/driverTests/testSets.ts
packages/cubejs-testing/test/driverTests/tests.ts
rust/cubeorchestrator/src/transport.rs
rust/cubestore/package.json

Fixes an issue with incorrect CompareDateRange query transformations done on native side.
**Check List**

fix(api-gateway): Fix CompareDateRange queries native transformations

---

packages/cubejs-backend-native/Cargo.lock
rust/cubenativeutils/Cargo.lock
rust/cubesql/Cargo.lock
rust/cubesql/cubesql/Cargo.toml
rust/cubesql/cubesql/src/compile/engine/df/scan.rs
rust/cubesql/cubesql/src/compile/engine/udf/common.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/utils.rs
rust/cubesqlplanner/Cargo.lock

chore(cubesql): Bump chrono and fix deprecation warnings

---

packages/cubejs-backend-native/js/index.ts

**Check List**
DataFusion can execute complex queries, containing multiple CubeScans, specifically multiple `CubeScanExecutionPlan` in physical plan
`CubeScanExecutionPlan`s can be executed concurrently, and as such concurrently trigger load calls on `TransportService`
Then, if one of several concurrent calls receives error whole stream with still-executing-plans can be dropped
For `NodeBridgeTransport` this would lead to dropping receiver side in `call_raw_js_with_channel_as_callback`
But sender side would continue to live in JS thread
Then JS side can call `writerOrChannel.resolve`, and it would find that channel is closed, and raise exception
But then this exception will be caught, leading to `writerOrChannel.reject` …

fix(backend-native): Handle closed channel on Rust side

---

packages/cubejs-server-core/src/core/CompilerApi.js

This is a backport of https://github.com/cube-js/cube/pull/9017 fix

backport: fix improper requestId retrieval in DAP

---

packages/cubejs-api-gateway/openspec.yml
rust/cubesql/cubeclient/src/models/v1_cube_meta_dimension.rs
rust/cubesql/cubeclient/src/models/v1_cube_meta_measure.rs
rust/cubesql/cubesql/benches/large_model.rs
rust/cubesql/cubesql/src/compile/test/mod.rs

**Check List**
This PR adds `short_title` field to measures and dimensions meta in `cubeclient`.

feat(cubeclient): Add `short_title` to dimensions and measures

---

packages/cubejs-schema-compiler/src/adapter/BaseTimeDimension.ts
packages/cubejs-schema-compiler/src/adapter/PreAggregations.js
packages/cubejs-schema-compiler/test/integration/postgres/pre-agg-allow-non-strict.test.ts

This PR fixes pre-agg matching for queries without granularities and with allowNonStrictDateRangeMatch set to true for pre-agg.
**Check List**

fix(schema-compiler): fix allowNonStrictDateRangeMatch pre-agg match for dateRange queries without granularities

---

packages/cubejs-redshift-driver/src/RedshiftDriver.ts
packages/cubejs-testing-drivers/src/tests/testExternalSchemas.ts

This PR fixes incorrect gathering table meta data  for Redshift Spectrum tables.
**Check List**

fix(redshift-driver): Fix empty tableColumnTypes for external (Spectrum) tables

---

packages/cubejs-server-core/package.json
packages/cubejs-server-core/src/core/agentCollect.ts
yarn.lock

feat(cubejs-server-core): support proxy in http agent transport

---

rust/cubesql/cubesql/src/compile/rewrite/cost.rs
rust/cubesql/cubesql/src/compile/test/test_wrapper.rs

**Check List**
Break symmetry for pust-to-Cube vs non-push-to-Cube plans, and test pushed members count on simple query.
Consider this query:
```
SELECT
CAST(dim_date0 AS DATE) AS "dim_date0"
FROM
MultiTypeCube
LIMIT 10
;
```
It can be represented with these two wrapper plans: 
Without changes in cost both of those would have the same cost:
```
CubePlanCost {
replacers: 0,
table_scans: 0,
empty_wrappers: 0,
non_detected_cube_scans: 0,
unwrapped_subqueries: 0,
member_errors: 0,
ungrouped_aggregates: 0,
non_pushed_down_window: 0,
non_pushed_down_grouping_sets: 0,
non_pushed_down_limit_sort: 0,
joins: 0,
wrapper_nodes: 1,
ast_size_outside_wrapper: 0,
wrapped_select_ungrouped_scan: 1,
filters: 0,
structure_points: 0, …
```

fix(cubesql): Break cost symmetry for (non)-push-to-Cube WrappedSelect

---

.github/workflows/publish.yml
.github/workflows/rust-cubestore-master.yml
.github/workflows/rust-cubestore.yml

ARM64 runners are in public preview, but It's ready for our use case. This PR allows us to shut down our own self-hosted runner on top of ARM64.
@bsod90 You should happy :)

chore(ci): Use ARM64 shared runners from GitHub

---

yarn.lock

**Check List**
This fixes an issue with just-released Node.js 22.14.0. It has N-API version '10', and it broke version comparison inside `prebuild-install` for `sqlite3`.
See this fix in `napi-build-utils`:
https://github.com/inspiredware/napi-build-utils/pull/7

chore: Bump napi-build-utils and prebuild-install

---

packages/cubejs-server-core/src/core/CompilerApi.js
packages/cubejs-testing/test/__snapshots__/smoke-multidb.test.ts.snap
packages/cubejs-testing/test/smoke-multidb.test.ts

**Check List**
api-gateway calls getSqlGenerator with empty query and concrete data source to initialize SQL API But because query is empty `sqlGenerator.dataSource` can be undefined, and it would trigger re-creating query with new data source, which would be `default`

fix(server-core): Handle empty query in getSqlGenerator

---

rust/cubesql/cubesql/src/compile/engine/context.rs
rust/cubesql/cubesql/src/sql/types.rs

**Check List**
This PR changes type of timestamp literal values in `CubeScan` to `TimestampNanosecond`. They previously converted to `TimestampMillisecond` which does not match member type (which is actually `TimestampNanosecond` despite Cube returning millisecond precision values). This led to issues with two CubeScans, one containing a member and another a literal, being unable to `UNION`.
Example plan that fails to execute:
```
Union
Projection: CAST(NULL AS Timestamp(Millisecond, None)) AS date, #SUM(amount) AS amount
Aggregate: groupBy=[[]], aggr=[[SUM(#cube.amount)]]
TableScan: cube projection=None
Projection: #cube.date AS date, #SUM(amount) AS amount
Aggregate: groupBy=[[#cube.date]], aggr=[[SUM(#cube.amount)]]
TableScan: cube projection=None
```
As …

fix(cubesql): Match CubeScan timestamp literal types to member types

---

docs/pages/product/apis-integrations/dax-api/reference.mdx

**Check List**
This PR updates DAX API function reference, specifically:
- Remove mention of `groupLevelFilter` being unsupported in `ROLLUPADDISSUBTOTAL` as it is now supported
- Document `NONVISUAL` function stub
- Document newly added `COUNTA` function
- Remove mention of `COUNT` behavior differing from the official docs
- Document newly added `DISTINCTCOUNT` function and its caveat (it does not count blanks as opposed to official docs)

docs: Update DAX API function reference

---

packages/cubejs-backend-shared/src/env.ts
packages/cubejs-server-core/src/core/CompilerApi.js
packages/cubejs-server-core/src/core/server.ts

feat(server-core): add fastReloadEnabled option to CompilerApi

---

packages/cubejs-client-ngx/.gitignore
packages/cubejs-client-ngx/README.md
packages/cubejs-client-ngx/package.json

This pull request updates the `@cubejs-client/ngx` package to explicitly define its Lerna publish directory at the package level. Previously, Lerna was publishing the entire dist folder instead of its contents, leading to module resolution issues when linking the package in Angular projects.
Key changes include adding the `lerna.command.publish.directory` configuration inside the package’s package.json, ensuring that Lerna correctly publishes from the intended dist location.
Reference: [Lerna directory documentation](https://lerna.js.org/docs/concepts/configuring-published-files#--directory)

fix(cubejs-client-ngx): Configure package-level Lerna publish directory for Angular

---

packages/cubejs-schema-compiler/src/compiler/CubeEvaluator.ts
packages/cubejs-schema-compiler/src/compiler/CubeSymbols.js
packages/cubejs-schema-compiler/test/unit/fixtures/folders.yml
packages/cubejs-schema-compiler/test/unit/fixtures/hierarchies.yml
packages/cubejs-schema-compiler/test/unit/hierarchies.test.ts

feat(schema-compiler): auto include hierarchy dimensions

---

packages/cubejs-backend-native/Cargo.lock
packages/cubejs-backend-shared/src/env.ts
packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-schema-compiler/src/adapter/PreAggregations.js
rust/cubenativeutils/src/wrappers/context.rs
rust/cubesqlplanner/Cargo.lock
rust/cubesqlplanner/cubesqlplanner/Cargo.toml
rust/cubesqlplanner/cubesqlplanner/src/planner/filter/base_filter.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/planners/simple_query_planer.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/query_tools.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/sql_templates/plan.rs

feat(tesseract): Pre-aggregation planning fallback

---

packages/cubejs-schema-compiler/test/integration/postgres/multi-stage.test.ts
rust/cubesqlplanner/cubesqlplanner/src/planner/sql_evaluator/collectors/sub_query_dimensions.rs

chore(tesseract): Fix for multi stage with sub queries

---

packages/cubejs-backend-native/python/cube/src/__init__.py
packages/cubejs-backend-native/src/python/cube_config.rs
packages/cubejs-backend-shared/src/env.ts
packages/cubejs-server-core/src/core/CompilerApi.js
packages/cubejs-server-core/src/core/OptsHandler.ts
packages/cubejs-server-core/src/core/optionsValidate.ts
packages/cubejs-server-core/src/core/server.ts
packages/cubejs-server-core/src/core/types.ts

chore(fast-reload): support fastReloadEnabled as a server option

---

rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/cost.rs
rust/cubesql/cubesql/src/compile/rewrite/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/rewriter.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs
rust/cubesql/cubesql/src/compile/test/mod.rs
rust/cubesql/cubesql/src/compile/test/test_wrapper.rs

**Check List**
This should avoid unexpected unifications of simplified expression in unrelated context. For example, same expression can be present in filter and projection, but due to over-unification in filters it can receive different representation in projection, and break aliases later, during extraction

fix(cubesql): Use pushdown-pullup scheme for FilterSimplifyReplacer

---

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-schema-compiler/test/unit/base-query.test.ts

This PR fixes incorrect ORDER BY clause generation for queries with time dimensions with dateRanges.
**Check List**

fix(schema-compiler): Fix ORDER BY clause generation for queries with td with filters

---

packages/cubejs-query-orchestrator/src/orchestrator/PreAggregationLoader.ts

This PR fixes improper temp table removal during pre-aggregation creations.
The same CacheLock Key was used for dropping tables, so in the case when there were more than 1 simultaneous
temp table creations (e.g. a few partitions for the table) - there was lock contention which prevents table drops.
**Check List**

fix(query-orchestrator): Fix dropping temp tables during pre-agg creation

---

rust/cubesql/cubesql/src/compile/rewrite/rules/wrapper/join.rs
rust/cubesql/cubesql/src/compile/test/test_cube_join_grouped.rs

**Check List**
Before this only expressions like `CAST(left.dim AS TEXT) = CAST(right.col AS TEXT)` were supported.
TopN over calculated fields can actually generate joins with calculated field in condition, so we have to support condition like `CAST(left.dim1 AS TEXT) || CAST(left.dim2 AS TEXT) = CAST(right.col AS TEXT)`

feat(cubesql): Support multiple columns in expression on each side in ungrouped-grouped join condition

---

docs/pages/product/deployment/cloud/vpc/azure.mdx

fix(docs): fix client id in the azure vpc peering doc

---

rust/cubesql/cubesql/src/compile/rewrite/rules/members.rs
rust/cubesql/cubesql/src/compile/test/mod.rs
rust/cubesql/cubesql/src/compile/test/test_cube_scan.rs
rust/cubesql/cubesql/src/compile/test/test_wrapper.rs

**Check List**
Before this in `Limit(Limit(CubeScan))` logical plan outer fetch and skip values would win.
Not they are calculated properly.

fix(cubesql): Calculate proper limit and offset for CubeScan in nested limits case

---

rust/cubesql/cubesql/src/compile/engine/df/wrapper.rs
rust/cubesql/cubesql/src/compile/rewrite/converter.rs
rust/cubesql/cubesql/src/compile/test/test_cube_join.rs

**Check List**
Now it should catch plans like `Join(CubeScan, Projection(CubeScan))`

fix(cubesql): Make cube join check stricter

---

packages/cubejs-schema-compiler/test/integration/postgres/sql-generation.test.ts
rust/cubesqlplanner/cubesqlplanner/src/plan/builder/select.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/planners/full_key_query_aggregate_planner.rs

fix(tesseract): Don't generate COALESCE with single argument

---

packages/cubejs-schema-compiler/test/integration/postgres/sql-generation.test.ts
rust/cubesqlplanner/cubesqlplanner/src/planner/sql_templates/plan.rs

fix(tesseract): fix wrong default alias for symbols with digits in name

---

rust/cubesql/cubesql/src/compile/engine/df/wrapper.rs
rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/test/test_wrapper.rs

**Check List**
Turns dimension-only member expressions in projection to `dimensions`, not `measures`
This helps with queries like `SELECT dim1, ... dimN, mea1, ... meaM FROM cube`, whether explicit or implicit (SQL API generate every member in SELECT for zero-member CubeScan in wrapper)

feat(cubesql): Move dimensions-only projections to dimensions for push-to-Cube wrapper

---

packages/cubejs-backend-native/Cargo.lock
rust/cubenativeutils/Cargo.lock
rust/cubesql/Cargo.lock
rust/cubesql/cubesql/Cargo.toml
rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__current_date.snap
rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__current_schema_postgres.snap
rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__localtimestamp.snap
rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__pg_catalog_udf_search_path.snap
rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__quicksight_sql_implementation_info.snap
rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__set_good_user.snap
rust/cubesql/cubesql/src/compile/test/snapshots/cubesql__compile__test__test_introspection__datagrip_introspection.snap
rust/cubesql/cubesql/src/compile/test/snapshots/cubesql__compile__test__test_introspection__dbeaver_introspection_init.snap
rust/cubesql/cubesql/src/compile/test/snapshots/cubesql__compile__test__test_introspection__zoho_inet_server_addr.snap
rust/cubesql/cubesql/src/compile/test/snapshots/cubesql__compile__test__test_udfs__pg_backend_pid.snap
rust/cubesqlplanner/Cargo.lock
rust/cubesqlplanner/cubesqlplanner/Cargo.toml

**Check List**
This PR fixes an issue with functions being aliased as the expression when no alias is specified. For instance, the query `SELECT version()` would name the resulting column `version()` instead of `version` like PostgreSQL does. Related tests are adjusted.

fix(cubesql): Functions without arguments alias as plain function name

---

package.json
packages/cubejs-cubestore-driver/package.json
packages/cubejs-databricks-jdbc-driver/package.json
packages/cubejs-dbt-schema-extension/package.json
packages/cubejs-dremio-driver/package.json
packages/cubejs-druid-driver/package.json
packages/cubejs-hive-driver/package.json
packages/cubejs-jdbc-driver/package.json
packages/cubejs-jdbc-driver/src/JDBCDriver.ts
packages/cubejs-ksql-driver/package.json
packages/cubejs-mongobi-driver/package.json
packages/cubejs-mysql-driver/package.json
packages/cubejs-query-orchestrator/package.json
packages/cubejs-schema-compiler/package.json
yarn.lock

- **sync generic-pool version across repo**
- **use @cubejs-backend/node-java-maven for jdbc driver**
- **update yarn.lock**
- **update @cubejs-backend/jdbc version**
- **sync yarn.lock**
- **get rid of lodash v3**
- **udpate axios in dremio driver**
- **udpate axios in druid driver**
- **update axios in yarn.lock**
- **udpate axios in ksql driver**
- **get rid of axios@^0.28.0**

chore(deps): Update node-java-maven & node-jdbc dependencies

---

docs/pages/product/apis-integrations/rest-api/reference.mdx
packages/cubejs-api-gateway/src/gateway.ts
packages/cubejs-api-gateway/src/sql-server.ts
packages/cubejs-backend-native/js/index.ts
packages/cubejs-backend-native/src/sql4sql.rs
packages/cubejs-testing/test/__snapshots__/smoke-cubesql.test.ts.snap
packages/cubejs-testing/test/smoke-cubesql.test.ts
rust/cubesql/cubesql/src/compile/rewrite/cost.rs
rust/cubesql/cubesql/src/compile/rewrite/rewriter.rs
rust/cubesql/cubesql/src/sql/database_variables/mysql/global_vars.rs
rust/cubesql/cubesql/src/sql/database_variables/mysql/session_vars.rs
rust/cubesql/cubesql/src/sql/database_variables/postgres/global_vars.rs
rust/cubesql/cubesql/src/sql/database_variables/postgres/session_vars.rs
rust/cubesql/cubesql/src/sql/mod.rs

**Check List**
Second part of  #9301

feat: Implement disable_post_processing in /v1/sql

---

rust/cubesql/cubesql/src/compile/query_engine.rs
rust/cubesql/cubesql/src/compile/snapshots/cubesql__compile__tests__explain-2.snap
rust/cubesql/cubesql/src/compile/test/snapshots/cubesql__compile__test__test_df_execution__union_all_alias_mismatch.snap
rust/cubesql/cubesql/src/compile/test/test_df_execution.rs

**Check List**
It can drop projection for mismatched alias in UNION ALL, leading to missing columns and out-of-bounds panic during execution in DF

fix(cubesql): Disable projection_push_down DF optimizer

---

.github/workflows/push.yml
rust/cubesqlplanner/cubesqlplanner/src/planner/filter/base_segment.rs

chore(tesseract): Turn on lint checks and fix some lint issues

---

docs/pages/product/apis-integrations/rest-api/reference.mdx
packages/cubejs-api-gateway/package.json
packages/cubejs-api-gateway/src/dateParser.js
packages/cubejs-api-gateway/src/gateway.ts
packages/cubejs-api-gateway/src/query.js
packages/cubejs-api-gateway/src/types/request.ts
packages/cubejs-api-gateway/test/dateParser.test.js
packages/cubejs-api-gateway/test/index.test.ts
packages/cubejs-backend-shared/package.json
packages/cubejs-backend-shared/src/time.ts
packages/cubejs-backend-shared/test/time.test.ts
packages/cubejs-query-orchestrator/package.json
packages/cubejs-query-orchestrator/src/orchestrator/PreAggregationLoadCache.ts
packages/cubejs-query-orchestrator/src/orchestrator/PreAggregationLoader.ts
packages/cubejs-query-orchestrator/src/orchestrator/PreAggregationPartitionRangeLoader.ts
packages/cubejs-query-orchestrator/src/orchestrator/QueryCache.ts
packages/cubejs-query-orchestrator/src/orchestrator/QueryOrchestrator.ts
packages/cubejs-query-orchestrator/src/orchestrator/utils.ts
packages/cubejs-schema-compiler/package.json
packages/cubejs-schema-compiler/src/compiler/CubeEvaluator.ts
packages/cubejs-server-core/package.json
packages/cubejs-server-core/src/core/RefreshScheduler.ts
packages/cubejs-server-core/test/unit/RefreshScheduler.test.ts

This PR introduce new selector for jobs triggering: dateRange. If it is set (in addition to other selectors or standalone) then only partitions which intersect with it will be rebuilt.
**Check List**

feat(server-core,api-gateway): Allow manual rebuilding pre-aggregation partitions within date Range

---

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-schema-compiler/test/integration/postgres/member-expressions-on-views.test.ts

**Check List**
`fullKeyQueryAggregate` is using measure.cube() a lot, like for grouping measures to key cube
This can be wrong for measure targeting view: we want to attach measure to subquery
for its definition cube, and there should be no subquery for view itself
It's expected that `fullKeyQueryAggregateMeasures` would resolve and prepare all measures from its original form in query to actual leaf measures in cubes, then build subqueries with those, and then `joinFullKeyQueryAggregate` would use `renderedReference` to point to these leaf measures
Hard case is a measure that:
* targeting view
* is a member expression
* references only dimensions from that view
Measure like that are "leaf" - there's nowhere to push it, …

fix(schema-compiler): Handle measures with dimension-only member expressions

---

packages/cubejs-bigquery-driver/src/BigQueryDriver.ts
packages/cubejs-elasticsearch-driver/driver/ElasticSearchDriver.js
packages/cubejs-ksql-driver/src/KsqlDriver.ts
packages/cubejs-mssql-driver/driver/MSSqlDriver.js
packages/cubejs-mysql-driver/package.json
packages/cubejs-snowflake-driver/package.json
packages/cubejs-snowflake-driver/src/SnowflakeDriver.ts
yarn.lock

Supersedes https://github.com/cube-js/cube/pull/9159

chore(snowflake-driver): Update snowflake-sdk to 2.0.x version

---

packages/cubejs-redshift-driver/src/RedshiftDriver.ts

This PR supersedes the original [PR](uhttps://github.com/cube-js/cube/pull/3877rl) by @emmanuel with conflict resolving and some polishment
**Check List**
Fixes https://github.com/cube-js/cube/issues/3876.

fix(redshift-driver): Use Redshift-specific schema query

---

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-schema-compiler/test/unit/postgres-query.test.ts

This fixes incorrect SQL generation for compound time dimensions with custom granularities.
**Check List**

fix(schema-compiler): Fix doubled calls to convertTz() for compound time dimensions with custom granularities

---

packages/cubejs-api-gateway/src/sql-server.ts
packages/cubejs-backend-native/js/index.ts
packages/cubejs-backend-native/src/auth.rs
packages/cubejs-backend-native/src/node_export.rs
packages/cubejs-backend-native/test/sql.test.ts

I am going to expose `checkAuth` in the next PR. To protect a situation with name collisions, I am going to rename functions that are used as `checkSqlAuth`.

refactor(cubesql): Use corresponding name for checkSqlAuth

---

docs/pages/product/configuration/data-sources/clickhouse.mdx
docs/pages/reference/configuration/environment-variables.mdx
packages/cubejs-backend-shared/src/env.ts
packages/cubejs-backend-shared/test/db_env_multi.test.ts
packages/cubejs-backend-shared/test/db_env_single.test.ts
packages/cubejs-clickhouse-driver/src/ClickHouseDriver.ts

**Check List**
[**Issue Reference this PR resolves**](https://github.com/cube-js/cube/issues/9340)
Allow to enable compression via env variable for clickhouse driver

feat(clickhouse-driver): allow to enable compression

---

packages/cubejs-backend-shared/src/env.ts
packages/cubejs-backend-shared/src/http-utils.ts
packages/cubejs-backend-shared/test/db_env_multi.test.ts
packages/cubejs-backend-shared/test/db_env_single.test.ts
packages/cubejs-databricks-jdbc-driver/src/DatabricksDriver.ts
packages/cubejs-databricks-jdbc-driver/src/helpers.ts
packages/cubejs-databricks-jdbc-driver/src/installer.ts
packages/cubejs-databricks-jdbc-driver/src/post-install.ts

Switch to the brand new OSS JDBC Driver proposed by Databricks.
Read more [here](https://docs.databricks.com/aws/en/integrations/jdbc/oss).
**Check List**

feat(databricks-jdbc-driver): Switch to the latest OSS Databricks JDBC driver

---

packages/cubejs-schema-compiler/src/adapter/BigqueryQuery.ts
rust/cubesql/cubesql/src/compile/mod.rs

This PR fixes datetime WEEK truncing for BigQuery.
Closes #9330
**Check List**

fix(schema-compiler): Fix BigQuery DATETIME_TRUNC() week processing

---

.github/workflows/push.yml

https://github.com/cube-js/cube/commit/f47b826ef37baf0ddc6d549cf0225acf1366771b
@KSDaemon

chore(ci): PR workflow - build native once for all jobs (speedup builds)

---

.github/workflows/push.yml

`21 minutes` for unit tests, but `integration` depends on it.
`9` minutes for unit tests, integration tests will start earlier by `21-9=12 minutes` & the whole workflow will end earlier.

chore(ci): PR workflow - reorganize core builds (speedup builds)

---

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-schema-compiler/src/compiler/CubeSymbols.ts
packages/cubejs-schema-compiler/test/integration/postgres/sql-generation.test.ts
rust/cubesqlplanner/cubesqlplanner/src/cube_bridge/base_tools.rs
rust/cubesqlplanner/cubesqlplanner/src/cube_bridge/dimension_definition.rs
rust/cubesqlplanner/cubesqlplanner/src/cube_bridge/evaluator.rs
rust/cubesqlplanner/cubesqlplanner/src/plan/time_series.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/base_dimension.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/base_time_dimension.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/mod.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/planners/multi_stage/applied_state.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/planners/multi_stage/member_query_planner.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/planners/multi_stage/rolling_window_planner.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/query_tools.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/sql_evaluator/compiler.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/sql_evaluator/dependecy.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/sql_evaluator/sql_call.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/sql_evaluator/sql_nodes/time_dimension.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/sql_evaluator/symbols/time_dimension_symbol.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/sql_templates/plan.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/time_dimension/date_time.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/time_dimension/date_time_helper.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/time_dimension/granularity.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/time_dimension/granularity_helper.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/time_dimension/mod.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/time_dimension/sql_interval.rs

feat(tesseract): Custom granularities support

---

packages/cubejs-schema-compiler/src/compiler/DataSchemaCompiler.js

- **fix(schema-compiler): Skip syntax check for transpiled files**
- **get rid of R.endsWith in favor of native js endsWith**

fix(schema-compiler): Skip syntax check for transpiled files

---

packages/cubejs-schema-compiler/src/compiler/CubeValidator.ts
packages/cubejs-schema-compiler/test/unit/cube-validator.test.ts

Fix validation to throw error for incorrect aliased included members for view.
**Check List**

fix(schema-compiler): Fix model validation for aliased included members for views

---

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-schema-compiler/test/integration/postgres/sql-generation.test.ts

**Check List**
This PR changes the behavior of `renderSqlMeasure` to respect `ungroupedAliases` from context for ungrouped measures.

fix(schema-compiler): Respect ungrouped alias in measures

---

rust/cubesql/cubesql/src/compile/rewrite/cost.rs
rust/cubesql/cubesql/src/compile/test/test_cube_join_grouped.rs

fix(cubesql): Penalize CrossJoins in favor of wrapper

---

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js

fix(tesseract): Fix for multi fact queries

---

.github/workflows/rust-cubestore.yml
rust/cubestore/cubestore-sql-tests/src/multiproc.rs
rust/cubestore/cubestore-sql-tests/src/tests.rs

**Check List**
This is to avoid issues like "GHA updated CMake, and now librdkafka won't build"

ci(cubestore): Run workflow in container

---

packages/cubejs-schema-compiler/src/adapter/BigqueryQuery.ts
rust/cubesql/cubesql/src/compile/engine/df/wrapper.rs
rust/cubesql/cubesql/src/compile/mod.rs

This fixes the BigQuery dateadd/timestampadd functions genereation, because of:
`TIMESTAMP_ADD doesn't support YEAR interval`.
**Check List**

fix(schema-compiler): Fix BigQuery DATE_ADD push down template for years/quarters/months

---

packages/cubejs-schema-compiler/src/compiler/CubeEvaluator.ts
packages/cubejs-schema-compiler/src/compiler/CubeSymbols.ts
packages/cubejs-schema-compiler/src/compiler/DynamicReference.js
packages/cubejs-schema-compiler/src/compiler/DynamicReference.ts

refactor(schema-compiler): More types for CubeEvaluator, CubeSymbols and DynamicReference

---

packages/cubejs-api-gateway/package.json
packages/cubejs-api-gateway/src/gateway.ts
packages/cubejs-api-gateway/src/query.js
packages/cubejs-api-gateway/src/types/query.ts
packages/cubejs-api-gateway/test/index.test.ts
packages/cubejs-schema-compiler/src/adapter/BaseMeasure.ts
packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-schema-compiler/src/compiler/CubeEvaluator.ts
packages/cubejs-schema-compiler/test/integration/postgres/sql-generation.test.ts
packages/cubejs-testing/test/__snapshots__/smoke-cubesql.test.ts.snap
packages/cubejs-testing/test/smoke-cubesql.test.ts
rust/cubesql/cubesql/src/compile/engine/df/snapshots/cubesql__compile__engine__df__wrapper__tests__member_expression_patch_measure.snap
rust/cubesql/cubesql/src/compile/engine/df/snapshots/cubesql__compile__engine__df__wrapper__tests__member_expression_sql.snap
rust/cubesql/cubesql/src/compile/engine/df/wrapper.rs
rust/cubesql/cubesql/src/compile/engine/udf/common.rs
rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/query_engine.rs
rust/cubesql/cubesql/src/compile/rewrite/analysis.rs
rust/cubesql/cubesql/src/compile/rewrite/language.rs
rust/cubesql/cubesql/src/compile/rewrite/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/members.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/wrapper/aggregate.rs
rust/cubesql/cubesql/src/compile/test/test_cube_join_grouped.rs
rust/cubesql/cubesql/src/compile/test/test_filters.rs
rust/cubesql/cubesql/src/compile/test/test_wrapper.rs
rust/cubesql/cubesql/src/transport/ext.rs
yarn.lock

**Check List**
Add new member expression: `PatchMeasure`.
It allows to change aggregation type and add measure filters for existing measure. This is to allow queries like `MIN(avgMeasure)` and `SUM(CASE dim = 'foo' WHEN TRUE THEN sumMeasure ELSE NULL END)` in SQL API.
Under the hood
* SQL API now allows mismatched aggregation functions and aggregation on top of `CASE` in SQL pushdown rules, and rewrites that to special expression `__patch_measure(measure_column, 'new_agg_type', boolean_expression)`
* This expression is syntactic-only, it should never execute, instead it would be handled by wrapper SQL generation
* Generated member expression is passed to JS-side
* `api-gateway` evaluates it from JSON from JS functions
* …

feat: PatchMeasure member expression

---

packages/cubejs-server-core/src/core/CompilerApi.js
packages/cubejs-server-core/src/core/OrchestratorStorage.ts

In this PR OrchestratorStorage is switched to use LRUCache instead of simple js Map.
This PR depends on [9424](https://github.com/cube-js/cube/pull/9424) because it uses `lru-cache` v11.
**Check List**

feat(server-core): Make OrchestratorStorage LRUCache

---

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-schema-compiler/test/integration/postgres/member-expression.test.ts
rust/cubesqlplanner/cubesqlplanner/src/cube_bridge/base_query_options.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/base_dimension.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/base_measure.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/base_query.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/params_allocator.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/planners/dimension_subquery_planner.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/planners/multi_stage/applied_state.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/planners/multi_stage/member_query_planner.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/planners/multi_stage/multi_stage_query_planner.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/query_properties.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/query_tools.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/sql_evaluator/collectors/member_childs_collector.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/sql_evaluator/references_builder.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/sql_evaluator/symbols/member_expression_symbol.rs

fix(tesseract): Fix issues with member expressions over multi stage

---

packages/cubejs-schema-compiler/test/integration/postgres/member-expression.test.ts
rust/cubesqlplanner/cubesqlplanner/src/planner/base_measure.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/planners/multi_stage/applied_state.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/planners/multi_stage/member.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/planners/multi_stage/multi_stage_query_planner.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/sql_evaluator/collectors/find_owned_by_cube.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/sql_evaluator/collectors/mod.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/sql_evaluator/mod.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/sql_evaluator/sql_nodes/factory.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/sql_evaluator/sql_nodes/time_shift.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/sql_evaluator/symbols/measure_symbol.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/sql_evaluator/symbols/mod.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/time_dimension/sql_interval.rs
yarn.lock

chore(tesseract): Refactoring of multistage time-shifts

---

packages/cubejs-schema-compiler/src/compiler/transpilers/ImportExportTranspiler.ts
packages/cubejs-schema-compiler/test/unit/transpilers.test.ts

This supersedes the original [PR](https://github.com/cube-js/cube/pull/8774) by @arkadiusz-swierczek-pm with some improvements/fixes.
**Check List**
Closes https://github.com/cube-js/cube/pull/8774

fix(schema-compiler): ExportNamedDeclaration for variables object

---

yarn.lock

- **dedup yargs**
- **dedup tslib**
- **dedup rc-util**
- **dedup mime-types**
- **dedup which-typed-array**
- **dedup ignore**
- **dedup has-symbols**
- **dedup has-property-descriptors**
- **dedup socks**
- **dedup schema-utils**
- **dedup source-map-js**
- **dedup signal-exit**
- **dedup terser-webpack-plugin**
- **dedup get-intrinsic**
- **dedup es-abstract**
- **dedup update-browserslist-db**
- **dedup prop-types**
- **dedup postcss-selector-parser**
- **dedup ramda**
- **dedup @types/http-proxy**
- **dedup axios**
- **dedup browserslist**
- **dedup call-bind**
- **dedup caniuse-lite**
- **dedup chokidar**
- **yarn.lock sync**
- **dedup picomatch**
- **dedup html-entities**
- **dedup tiny-invariant**
- **dedup is-core-module**
- **dedup fast-glob**
- **dedup acorn**
- **dedup …

chore(deps): Deduplicate some packages

---

rust/cubeorchestrator/src/query_message_parser.rs
rust/cubeorchestrator/src/query_result_transform.rs

This fixes incorrect null values parsing received from Cubestore in flatbuffers. Previously null values were encoded into empty string instead of **nulls**.
**Check List**

fix(cubeorchestrator): Fix incorrect null-values parsing from CubeStore Result

---

packages/cubejs-backend-native/js/index.ts
packages/cubejs-schema-compiler/src/compiler/DataSchemaCompiler.js

Update the transpilation flow to use Native transpilation with file batching instead of processing files one by one, improving performance.
**Check List**

feat(schema-compiler): Implement bulk processing for js transpilation in native

---

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-schema-compiler/src/compiler/CubeSymbols.ts
packages/cubejs-schema-compiler/test/integration/postgres/multiple-join-paths.test.ts
packages/cubejs-schema-compiler/test/integration/postgres/pre-aggregations.test.ts
packages/cubejs-schema-compiler/test/integration/postgres/view-and-indirect-members.test.ts

**Check List**
Without this when following from view to cube member join hints will be collected and ignored, then join hints would be collected for references from cube member to other cube members, and only those would be used for join tree

fix(schema-compiler): Do not drop join hints when view member is not itself owned

---

.github/workflows/rust-cubesql.yml
rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/query_engine.rs
rust/cubesql/cubesql/src/compile/rewrite/cost.rs
rust/cubesql/cubesql/src/compile/rewrite/rewriter.rs
rust/cubesql/cubesql/src/config/mod.rs

feat(cubesql): Remove bottom-up extraction completely

---

docs/pages/reference/configuration/environment-variables.mdx
packages/cubejs-backend-shared/src/env.ts

It's time to enable CUBEJS_TESSERACT_ORCHESTRATOR by default.
**Check List**

feat(schema-compiler)!: Turn CUBEJS_TESSERACT_ORCHESTRATOR=true by default

---

docs/pages/product/caching/matching-pre-aggregations.mdx
docs/pages/product/configuration/visualization-tools/superset.mdx
docs/pages/reference/configuration/environment-variables.mdx
docs/pages/reference/data-model/pre-aggregations.mdx
packages/cubejs-backend-shared/src/env.ts
packages/cubejs-schema-compiler/src/compiler/CubeSymbols.ts
packages/cubejs-schema-compiler/test/integration/postgres/pre-aggregations.test.ts
packages/cubejs-schema-compiler/test/unit/schema.test.ts

This PR introduces new env var: `CUBEJS_PRE_AGGREGATIONS_ALLOW_NON_STRICT_DATE_RANGE_MATCH` which is set to `true` by default.
If Pre-aggregation in data model includes allowNonStrictDateRangeMatch property - it's kept as is, no changes.
**Check List**

feat(schema-compiler)!: Set preAggregation.allowNonStrictDateRangeMatch = true by default

---

DEPRECATION.md
packages/cubejs-schema-compiler/src/compiler/CubeSymbols.ts
packages/cubejs-schema-compiler/src/compiler/CubeValidator.ts
packages/cubejs-schema-compiler/test/integration/postgres/cube-views.test.ts
packages/cubejs-schema-compiler/test/unit/views.test.ts

Dropping support for top-level includes/excludes in views, which were deprecated long ago...
**Check List**

chore(schema-compiler)!: Drop support for top-level includes/excludes in views

---

docs/pages/product/data-modeling/syntax.mdx
packages/cubejs-schema-compiler/src/compiler/YamlCompiler.ts
packages/cubejs-schema-compiler/test/integration/postgres/yaml-compiler.test.ts
packages/cubejs-schema-compiler/test/unit/yaml-schema.test.ts

Previously it was not possible for example to define a JSON literal in `sql` property of cube or do similar things.
Now it's fixed!
So you can do for example this in yaml models:
```yaml
cubes:
- name: ActiveUsers
sql: > 
SELECT 1 as user_id, 
'2022-01-01'::TIMESTAMP as timestamp, 
CAST('\{"key":"value"\}'::JSON AS TEXT) AS json_col
dimensions:
- name: time
sql: "{CUBE}.timestamp"
type: time
- name: json_col
sql: json_col
type: string
```
And if you query it:
```js
{
dimensions: ['ActiveUsers.time', 'ActiveUsers.json_col'],
}
```
You'll get an expected result:
```js
[{
active_users__time: '2022-01-01T00:00:00.000Z',
active_users__json_col: '{"key":"value"}',
}]
```
This closes #8250
**Check List**

fix(schema-compiler): Allow escaping of curly braces in yaml models

---

docs/pages/reference/data-model/cube.mdx
packages/cubejs-query-orchestrator/src/orchestrator/BaseQueueEventsBus.ts
packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts
packages/cubejs-query-orchestrator/src/orchestrator/QueryCache.ts
packages/cubejs-query-orchestrator/src/orchestrator/QueryOrchestrator.ts
packages/cubejs-schema-compiler/package.json
packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-schema-compiler/test/integration/mssql/mssql-pre-aggregations.test.ts
packages/cubejs-schema-compiler/test/unit/base-query.test.ts
packages/cubejs-server-core/src/core/OrchestratorApi.ts
yarn.lock

This PR makes RefreshKey SQL generation to use the query timezone. This is important for the case when there are a few scheduled refresh timezones (or even one but different from `UTC`) and there is a pre-aggregation with `day` partition granularity. So you want them to be updated at midnight in the provided timezone rather than at `UTC`.
This fixes it.
The change is also made in cron-based refresh keys, making them timezone-aware. If the pre-aggregation `refresh_key` does not define a `timezone`, then the `timezone` of the query will be used.
**Check List**

fix(schema-compiler): Make RefreshKeySql timezone-aware

---

rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs
rust/cubesql/cubesql/src/compile/test/test_filters.rs

**Check List**
Consider this query
```
SELECT
dim_str0,
avgPrice
FROM (
SELECT
dim_str0,
AVG(avgPrice) AS avgPrice
FROM
MultiTypeCube
GROUP BY 1
) t
WHERE
avgPrice > 1
OR (
avgPrice = 1
AND
dim_str0 = 'completed'
)
;
```
Before this filter replacer would push a single filter to CubeScan with all of predicates together.
Cube.js does not support mixing measures and dimension in a single filter, only as a separate filters.
So, now it stops rewriting if resulting filter would contain both measures and dimensions.
Initial plan 
```
Initial Plan: Projection: #t.dim_str0, #t.avgPrice
Filter: #t.avgPrice > Int64(1) OR #t.avgPrice = Int64(1) AND #t.dim_str0 = Utf8("completed")
Projection: #MultiTypeCube.dim_str0, …
```

fix(cubesql): Disallow mixing measure and dimension filters in a single FilterOp

---

docs/pages/product/auth/context.mdx

**Check List**
We moved the location where the auth metadata is located in the security context from `cloud` to `cubeCloud`.

docs: Update reserved jwt params

---

rust/cubesql/cubesql/src/compile/engine/df/optimizers/snapshots/cubesql__compile__engine__df__optimizers__sort_push_down__tests__sort_down_cross_join_sort_left.snap
rust/cubesql/cubesql/src/compile/engine/df/optimizers/snapshots/cubesql__compile__engine__df__optimizers__sort_push_down__tests__sort_down_cross_join_sort_right.snap
rust/cubesql/cubesql/src/compile/engine/df/optimizers/snapshots/cubesql__compile__engine__df__optimizers__sort_push_down__tests__sort_down_join_sort_left.snap
rust/cubesql/cubesql/src/compile/engine/df/optimizers/snapshots/cubesql__compile__engine__df__optimizers__sort_push_down__tests__sort_down_join_sort_right.snap
rust/cubesql/cubesql/src/compile/engine/df/optimizers/snapshots/cubesql__compile__engine__df__optimizers__sort_push_down__tests__sort_down_multiple_projections.snap
rust/cubesql/cubesql/src/compile/engine/df/optimizers/snapshots/cubesql__compile__engine__df__optimizers__sort_push_down__tests__sort_down_projection.snap
rust/cubesql/cubesql/src/compile/engine/df/optimizers/snapshots/cubesql__compile__engine__df__optimizers__sort_push_down__tests__sort_down_sort.snap
rust/cubesql/cubesql/src/compile/engine/df/optimizers/sort_push_down.rs

**Check List**
`LogicalPlan::Join` and `CrossJoin` do not preserve the ordering semantically
When planned as `HashJoin` it will output batches in same order as they are coming from right stream
But both `Join` and `CrossJoin` will have same partitioning as right input (even when `repartition_joins` disabled), and these partitions can be collected in arbitrary order by `CoalescePartitions`
Side note: Substrait says that for both Join and Cross Product
> Orderedness is empty post operation
See https://substrait.io/relations/logical_relations/#join-operation

fix(cubesql): Fix SortPushDown pushing sort through joins

---

packages/cubejs-schema-compiler/src/adapter/RedshiftQuery.ts
packages/cubejs-testing-drivers/fixtures/redshift.json
packages/cubejs-testing-drivers/test/__snapshots__/redshift-full.test.ts.snap

Previously only `day-to-second` intervals were supported for Redshift custom granularities maths. This adds support for `Year-to-month` intervals. So all of this is now possible:
```yaml
- name: saletime
sql: saletime
type: time
granularities:
- name: half_year
title: 6 month intervals
interval: 6 months
- name: half_year_by_1st_april
title: Half year from Apr to Oct
interval: 6 months
offset: 3 months
- name: fiscal_year_by_1st_feb
title: Fiscal year by Feb
interval: 1 year
offset: 1 month
- name: fiscal_year_by_15th_march
interval: 1 year
origin: '2024-03-15'
- name: two_weeks_by_friday
interval: 2 weeks
origin: '2024-09-20 03:00:00+03:00'
```
**Check List**

feat(schema-compiler): Support custom granularities with Year-Month intervals for AWS Redshift dialect

---

packages/cubejs-schema-compiler/src/compiler/CubeEvaluator.ts
packages/cubejs-schema-compiler/src/compiler/CubeSymbols.ts
packages/cubejs-schema-compiler/src/compiler/CubeValidator.ts
packages/cubejs-schema-compiler/test/unit/__snapshots__/schema.test.ts.snap
packages/cubejs-schema-compiler/test/unit/cube-validator.test.ts
packages/cubejs-schema-compiler/test/unit/schema.test.ts

This change allows to override of some descriptive properties in the view's included members.
So now it's possible to do things like this:
```yaml
views:
- name: orders_view
cubes:
- join_path: orders
includes:
- name: status
alias: my_beloved_status
title: My Beloved and not Favorite Status!    <<<<<<< this <<<<<<<
description: Don't you believe this?          <<<<<<< this <<<<<<<
meta:                                         <<<<<<< this. Please note, <<<<<<<
- c1: iddqd                                 <<<<<<< that Meta is overridden as a whole <<<<<<<
- c2: idkfa                                 <<<<<<< and not extended <<<<<<<
```
**Check List**

feat(schema-compiler): Support overriding `title`, `description`, `meta`, and `format` on view members

---

rust/cubesql/cubesql/src/compile/engine/udf/extension/mod.rs
rust/cubesql/cubesql/src/compile/engine/udf/extension/xirr.rs
rust/cubesql/cubesql/src/compile/engine/udf/mod.rs
rust/cubesql/cubesql/src/compile/query_engine.rs
rust/cubesql/cubesql/src/compile/test/snapshots/cubesql__compile__test__test_udfs__extension_udf_xirr.snap
rust/cubesql/cubesql/src/compile/test/test_udfs.rs

**Check List**
This PR adds support for `XIRR` aggregate function. Related test is included.

feat(cubesql): Add `XIRR` aggregate function

---

docs/pages/product/data-modeling/concepts/_meta.js
docs/pages/product/data-modeling/concepts/code-reusability-extending-cubes.mdx
docs/pages/reference/data-model/cube.mdx
docs/pages/reference/data-model/view.mdx
packages/cubejs-schema-compiler/src/compiler/CubeEvaluator.ts
packages/cubejs-schema-compiler/src/compiler/CubeSymbols.ts
packages/cubejs-schema-compiler/src/compiler/CubeValidator.ts
packages/cubejs-schema-compiler/test/unit/__snapshots__/cube-schema-converter.test.ts.snap
packages/cubejs-schema-compiler/test/unit/__snapshots__/schema.test.ts.snap
packages/cubejs-schema-compiler/test/unit/fixtures/folders.yml
packages/cubejs-schema-compiler/test/unit/folders.test.ts
packages/cubejs-schema-compiler/test/unit/schema.test.ts
packages/cubejs-schema-compiler/test/unit/utils.ts

Makes it possible to inherit some views from others.
**Check List**

feat(schema-compiler): Support view extends

---

packages/cubejs-schema-compiler/src/adapter/BaseDimension.ts
packages/cubejs-schema-compiler/src/adapter/BaseMeasure.ts
packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-schema-compiler/src/adapter/BaseSegment.ts
packages/cubejs-schema-compiler/src/adapter/BaseTimeDimension.ts
packages/cubejs-schema-compiler/src/adapter/Granularity.ts
packages/cubejs-schema-compiler/src/adapter/PreAggregations.js
packages/cubejs-schema-compiler/test/integration/postgres/pre-aggregations.test.ts
packages/cubejs-schema-compiler/test/unit/pre-agg-time-dim-match.test.ts

This fixes cases when a query with custom granularity doesn't hit the pre-aggregation with the same custom granularity.
**Check List**

fix(schema-compiler): Fix non-match for exact custom granularity pre-aggregation

---

rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/members.rs
rust/cubesql/cubesql/src/compile/test/snapshots/cubesql__compile__test__test_cube_join__join_with_trivial_cast.snap
rust/cubesql/cubesql/src/compile/test/test_cube_join.rs

**Check List**
This should allow pushing down expressions like `CAST(dimension AS TEXT) AS alias` into `CubeScan` as regular dimensions.
This should allow `__cubeJoinField` joins to see more `CubeScan`s
Supporting changes:
Remove unused rule for member pushdown from `AllMembers`
All matching happening with `CubeScanMembers` on top of actual members node, and this rule does not expect that
`member_name_to_expr` part of analysis can extract members from `CubeScanMembers(AllMembers)`, so there's no reason to keep this rule
Add explicit type in `var!` macro, to avoid type confusion.

feat(cubesql): Support trivial casts in member pushdown

---

rust/cubesql/cubesql/src/compile/engine/df/optimizers/filter_push_down.rs
rust/cubesql/cubesql/src/compile/engine/df/optimizers/snapshots/cubesql__compile__engine__df__optimizers__filter_push_down__tests__filter_down_cross_join_right_one_row.snap
rust/cubesql/cubesql/src/compile/engine/df/optimizers/snapshots/cubesql__compile__engine__df__optimizers__filter_push_down__tests__filter_down_projection.snap
rust/cubesql/cubesql/src/compile/engine/df/optimizers/snapshots/cubesql__compile__engine__df__optimizers__filter_push_down__tests__filter_down_sort.snap
rust/cubesql/cubesql/src/compile/engine/df/optimizers/snapshots/cubesql__compile__engine__df__optimizers__filter_push_down__tests__filters_down_aggregate.snap
rust/cubesql/cubesql/src/compile/engine/df/optimizers/snapshots/cubesql__compile__engine__df__optimizers__filter_push_down__tests__multiple_filters_down_projections.snap
rust/cubesql/cubesql/src/compile/engine/df/optimizers/snapshots/cubesql__compile__engine__df__optimizers__filter_push_down__tests__multiple_filters_down_projections_with_post_processing.snap
rust/cubesql/cubesql/src/compile/test/test_cube_join_grouped.rs

**Check List**
This should help with rewrites filters on top of complex ungrouped-grouped joins as a subquery joins

fix(cubesql): Disable filter pushdown over Filter(CrossJoin)

---

docs/pages/product/configuration.mdx
docs/pages/product/data-modeling/dynamic/jinja.mdx
packages/cubejs-backend-native/src/python/entry.rs
packages/cubejs-backend-native/test/config.py
packages/cubejs-backend-native/test/globals.py
packages/cubejs-backend-native/test/globals_w_import_path.py
packages/cubejs-backend-native/test/python.test.ts
packages/cubejs-backend-native/test/subdir_for_test/meta.py
packages/cubejs-backend-native/test/utils.py

This fix allows to import python modules from files relative to `cube.py`. See more info and issue description in https://github.com/cube-js/cube/issues/8443.
Closes https://github.com/cube-js/cube/issues/8443
**Check List**

feat(backend-native): Allow importing modules from python files within `cube.py` and `globals.py`

---

docs/pages/reference/data-model/data-access-policies.mdx

fix incorrect allow_all reference in docs

---

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-schema-compiler/src/compiler/CubeEvaluator.ts
packages/cubejs-schema-compiler/src/compiler/CubeValidator.ts
packages/cubejs-schema-compiler/test/integration/postgres/sql-generation.test.ts
packages/cubejs-schema-compiler/test/unit/cube-validator.test.ts

This change allows you to define one time shift for a measure without specifying a time dimension. In this case, timeShift `interval` and `type` will be applied to query time dimension(s) just like `rollingWindows` do.
You still can define an array of timeShifts (>1), but in this case, you'll have to specify time dimensions in each.
**Check List**

feat(schema-compiler): Allow one measure timeShift without time dimension

---

packages/cubejs-backend-native/src/python/entry.rs

fix: Throw a user-friendly error on an empty cube.py file

---

packages/cubejs-schema-compiler/src/adapter/BaseFilter.ts
packages/cubejs-schema-compiler/test/integration/postgres/sql-generation.test.ts

Fixes errors for queries with measures with type `time` used as date filters.
**Check List**
Closes https://github.com/cube-js/cube/issues/9435

fix(schema-compiler): Fix filtering by time measure

---

packages/cubejs-api-gateway/src/gateway.ts
packages/cubejs-backend-shared/src/time.ts
packages/cubejs-backend-shared/test/time.test.ts
packages/cubejs-query-orchestrator/src/orchestrator/PreAggregationPartitionRangeLoader.ts
packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts
packages/cubejs-query-orchestrator/test/unit/PreAggregations.test.js
packages/cubejs-schema-compiler/src/adapter/CubeStoreQuery.ts
packages/cubejs-server-core/test/unit/RefreshScheduler.test.ts

Cube expects the underlying data source connection to be using `UTC` as the session timezone (where it is applicable), or expects date_time functions (like `now()`) to return time in `UTC`. DateRange Build Start/End queries were parsed incorrectly, for non-UTC timezones this leads to incorrect partitions being rebuilt. This PR fixes that.
**Check List**

fix(query-orchestrator): Correct local date parsing for partition start/end queries

---

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-schema-compiler/test/integration/postgres/sql-generation.test.ts

This PR fixes incorrect SQL generation for queries that reference view members with timeShift from joined cubes
**Check List**

fix(schema-compiler): Fix view queries with timeShift members

---

packages/cubejs-ksql-driver/src/KsqlQuery.ts
packages/cubejs-schema-compiler/src/adapter/BaseDimension.ts
packages/cubejs-schema-compiler/src/adapter/BaseFilter.ts
packages/cubejs-schema-compiler/src/adapter/BaseGroupFilter.ts
packages/cubejs-schema-compiler/src/adapter/BaseMeasure.ts
packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-schema-compiler/src/adapter/BaseSegment.ts
packages/cubejs-schema-compiler/src/adapter/CubeStoreQuery.ts
packages/cubejs-schema-compiler/src/adapter/HiveQuery.ts
packages/cubejs-schema-compiler/src/adapter/PreAggregations.js
packages/cubejs-schema-compiler/src/adapter/PreAggregations.ts
packages/cubejs-schema-compiler/src/compiler/CubeEvaluator.ts
packages/cubejs-schema-compiler/src/compiler/CubeSymbols.ts
packages/cubejs-schema-compiler/src/compiler/CubeValidator.ts
packages/cubejs-schema-compiler/test/integration/postgres/pre-aggregations.test.ts

Finally, move PreAggregations from js to ts with most of the types described! 🎉
Also switching to TS uncovered some incorrectness that is now fixed!

chore(schema-compiler): move preAggregations class to typescript

---

packages/cubejs-schema-compiler/src/adapter/CubeStoreQuery.ts
packages/cubejs-schema-compiler/src/adapter/PreAggregations.ts
packages/cubejs-schema-compiler/test/integration/postgres/multiple-join-paths.test.ts
packages/cubejs-schema-compiler/test/integration/postgres/pre-aggregation-utils.ts
packages/cubejs-schema-compiler/test/integration/postgres/sql-generation.test.ts

**Check List**
Fixes rendered references to include both full join path and regular member path as keys.
Without this SQL to read from pre-aggregation table would render members as a regular `cube_table.member_sql` expressions

fix(schema-compiler): Fix rendered references for preaggregations with join paths

---

packages/cubejs-api-gateway/src/sql-server.ts
packages/cubejs-backend-native/src/auth.rs
packages/cubejs-backend-native/test/sql.test.ts
packages/cubejs-testing/birdbox-fixtures/postgresql/single/sqlapi.js
rust/cubesql/cubesql/src/compile/router.rs
rust/cubesql/cubesql/src/compile/test/mod.rs
rust/cubesql/cubesql/src/sql/auth_service.rs
rust/cubesql/cubesql/src/sql/mod.rs
rust/cubesql/cubesql/src/sql/postgres/pg_auth_service.rs

feat: introduce "protocol" and "method" props for request param in checkSqlAuth

---

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-schema-compiler/test/integration/postgres/sql-generation.test.ts

fix(schema-compiler): Fix view queries for measure with single timeshift reference without time dimension

---

packages/cubejs-schema-compiler/src/adapter/BaseDimension.ts
packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-testing-drivers/fixtures/_schemas.json
packages/cubejs-testing-drivers/src/tests/testQueries.ts
packages/cubejs-testing-drivers/test/__snapshots__/athena-export-bucket-s3-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/bigquery-export-bucket-gcs-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/clickhouse-export-bucket-s3-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/clickhouse-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/databricks-jdbc-export-bucket-azure-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/databricks-jdbc-export-bucket-azure-prefix-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/databricks-jdbc-export-bucket-gcs-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/databricks-jdbc-export-bucket-gcs-prefix-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/databricks-jdbc-export-bucket-s3-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/databricks-jdbc-export-bucket-s3-prefix-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/databricks-jdbc-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/mssql-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/mysql-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/postgres-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/redshift-export-bucket-s3-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/redshift-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/snowflake-encrypted-pk-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/snowflake-export-bucket-azure-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/snowflake-export-bucket-azure-via-storage-integration-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/snowflake-export-bucket-gcs-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/snowflake-export-bucket-s3-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/snowflake-full.test.ts.snap

fix(schema-compiler): Fix timeshift measure queries coming from SQL API

---

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-testing/test/__snapshots__/smoke-cubesql.test.ts.snap
packages/cubejs-testing/test/smoke-cubesql.test.ts

**Check List**
This is necessary to support queries where output references only join subqueries.
Before, when query does have subqeury joins, but does not have any measures/dimensions/... join hints would be empty, and join tree would be `null`, which is almost okay, but to generate query with join subqueries we need to build join query, so join tree is more-or-less required.

fix(schema-compiler): Collect join hints from subquery join conditions

---

rust/cubeorchestrator/src/transport.rs

This fixes load response serialization (omitting the not-filled properties of time dimensions) that break the following up cubeApi instance queries (like `drilldown()`)
**Check List**

fix(backend-native): Fix load response serialization (that breaks cubeApi further processing)

---

rust/cubesql/cubesql/src/compile/engine/df/wrapper.rs
rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/test/test_wrapper.rs

**Check List**
This PR changes the behavior of SQL push down generation for `DATE_TRUNC` expressions, generating a member expression with granularity rather than `DATE_TRUNC` SQL equivalent. Related tests are adjusted.

feat(cubesql): Push down `DATE_TRUNC` expressions as member expressions with granularity

---

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-testing/birdbox-fixtures/postgresql/schema/Orders.js
packages/cubejs-testing/test/__snapshots__/smoke-cubesql.test.ts.snap
packages/cubejs-testing/test/smoke-cubesql.test.ts

**Check List**
Context change can alter behaviour for other TD references in same context, specifically in same member expression, rendering different expression

fix(schema-compiler): Avoid mutating context on first occasion of TD with granularity

---

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-testing/test/__snapshots__/birdbox-postgresql-pre-aggregations.test.ts.snap
packages/cubejs-testing/test/__snapshots__/cli-postgresql-pre-aggregations.test.ts.snap

This PR fixes incorrect sql generation for queries with rolling windows coming from SQL API with member expressions instead of time dimensions.
**Check List**

fix(schema-compiler): Fix rolling window queries with expressions from SQL API

---

rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/converter.rs

**Check List**
This PR changes the erroneous behavior of filter to date range transformation, which previously could merge filters inside OR filter. Related test is included.

fix(cubesql): Do not merge time dimension ranges in "or" filter into date range

---

packages/cubejs-schema-compiler/src/adapter/BaseFilter.ts
packages/cubejs-schema-compiler/src/adapter/BaseTimeDimension.ts
packages/cubejs-schema-compiler/test/integration/postgres/multi-stage.test.ts
packages/cubejs-schema-compiler/test/integration/postgres/sql-generation.test.ts

fix(schema-compiler): exclude time dimensions w/o granularities from select list in base queries

---

packages/cubejs-testing-drivers/fixtures/clickhouse.json
packages/cubejs-testing-drivers/fixtures/mssql.json
packages/cubejs-testing-drivers/fixtures/mysql.json
packages/cubejs-testing-drivers/fixtures/redshift.json
packages/cubejs-testing-drivers/src/tests/testQueries.ts
packages/cubejs-testing-drivers/test/__snapshots__/athena-export-bucket-s3-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/bigquery-export-bucket-gcs-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/databricks-jdbc-export-bucket-azure-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/databricks-jdbc-export-bucket-azure-prefix-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/databricks-jdbc-export-bucket-gcs-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/databricks-jdbc-export-bucket-gcs-prefix-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/databricks-jdbc-export-bucket-s3-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/databricks-jdbc-export-bucket-s3-prefix-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/databricks-jdbc-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/postgres-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/snowflake-encrypted-pk-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/snowflake-export-bucket-azure-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/snowflake-export-bucket-azure-prefix-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/snowflake-export-bucket-azure-via-storage-integration-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/snowflake-export-bucket-gcs-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/snowflake-export-bucket-gcs-prefix-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/snowflake-export-bucket-s3-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/snowflake-export-bucket-s3-prefix-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/snowflake-full.test.ts.snap
rust/cubesql/cubesql/src/compile/engine/df/wrapper.rs

**Check List**
This PR quotes join aliases as identifiers when generating SQL for SQL push down to cube. Related test is included.

fix(cubesql): Quote subquery joins alias in SQL push down to cube

---

packages/cubejs-api-gateway/openspec.yml
packages/cubejs-schema-compiler/src/compiler/CubeEvaluator.ts
packages/cubejs-schema-compiler/src/compiler/CubeToMetaTransformer.js
packages/cubejs-schema-compiler/test/unit/__snapshots__/schema.test.ts.snap
packages/cubejs-schema-compiler/test/unit/hierarchies.test.ts
rust/cubesql/cubeclient/src/models/v1_cube_meta_hierarchy.rs

While working on new hierarchy support for MDX, I've figured out that there is no `aliasMember` (and generally no way) for hierarchies in views. It's important because I am using it to construct Analysis Services hierarchies.
**Check List**

feat: Expose aliasMember for hierarchy in View

---

packages/cubejs-prestodb-driver/package.json
packages/cubejs-prestodb-driver/src/PrestoDriver.ts
packages/cubejs-schema-compiler/src/adapter/index.ts
packages/cubejs-trino-driver/package.json
packages/cubejs-trino-driver/src/TrinoDriver.ts
yarn.lock

This PR includes a special `testConnection()` implementation for Trino, as the one for PrestoDB is not working for Trino Server.
Also updated the "presto-client" to the latest "^1.1.0".
This fixes https://github.com/cube-js/cube/issues/9303
**Check List**

feat(trino-driver): Add special testConnection for Trino

---

packages/cubejs-backend-shared/src/env.ts
packages/cubejs-prestodb-driver/src/PrestoDriver.ts
packages/cubejs-trino-driver/src/TrinoDriver.ts

This PR introduces a new configurable option for Prestodb/Trino drivers family: `CUBEJS_DB_PRESTO_AUTH_TOKEN`.
You can use it to specify the auth token, like JWT to be sent in Authorization header instead of basic http auth.
**Check List**

feat(prestodb-driver, trino-driver): Support custom auth headers (JWT)

---

packages/cubejs-backend-shared/src/track.ts
packages/cubejs-server-core/src/core/DevServer.ts
packages/cubejs-server-core/src/core/agentCollect.ts
packages/cubejs-server-core/src/core/server.ts
packages/cubejs-server-core/src/core/types.ts
rust/cubesql/cubesql/src/sql/compiler_cache.rs

The idea is simple: When an `async` function is called in an `async` function with `await`, the real execution can be delayed to micro tasking in Node.js. It results in incorrect timestamps, which I see in APM.

fix: Report more accurate time to APM on heavy used deployments

---

packages/cubejs-cli/src/command/validate.ts
packages/cubejs-schema-compiler/src/compiler/DataSchemaCompiler.js

This PR fixes incorrect compilation and error handling during `validate` command run.
Also this fixes https://github.com/cube-js/cube/issues/9506

fix(cubejs-cli): Fix validate command

---

packages/cubejs-client-core/src/SqlQuery.ts
packages/cubejs-client-core/src/index.ts
packages/cubejs-client-core/test/SqlQuery.test.ts

**Check List**
This PR fixes issue [9589](https://github.com/cube-js/cube/issues/9589)
The generated SQL tab started crashing since v1.3.16 and it was linked to the PR [9562](https://github.com/cube-js/cube/pull/9562/files). There are multiple ways of fixing the issue so I have attempted the one with minimal changes. Since I have limited understanding of the codebase, happy to modify the PR if a different approach should be taken to fix the problem.

fix(client-core): Fix for the issue with Generated SQL tab in playground

---

rust/cubesql/cubesql/src/compile/engine/df/optimizers/filter_split_meta.rs
rust/cubesql/cubesql/src/compile/test/test_user_change.rs

**Check List**
This PR enhances `FilterSplitMeta` optimizer to split `__user` filter when it's wrapped in a cast. Related test is included.

fix(cubesql): Split meta on `CAST` over `__user` column

---

packages/cubejs-api-gateway/src/query.js
packages/cubejs-backend-shared/src/time.ts
packages/cubejs-databricks-jdbc-driver/src/DatabricksQuery.ts
packages/cubejs-questdb-driver/src/QuestQuery.ts
packages/cubejs-schema-compiler/src/adapter/AWSElasticSearchQuery.ts
packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-schema-compiler/src/adapter/ClickHouseQuery.ts
packages/cubejs-schema-compiler/src/adapter/ElasticSearchQuery.ts
packages/cubejs-schema-compiler/src/adapter/HiveQuery.ts
packages/cubejs-schema-compiler/src/adapter/QueryBuilder.ts
packages/cubejs-schema-compiler/src/adapter/QueryCache.ts
packages/cubejs-schema-compiler/test/unit/postgres-query.test.ts

This PR introduces the ability to specify granularity in the order section of the query and fixes the ordering when same time dimension is requested multiple times (with different granularities).
Imaging you have a query like this:
```js
{
measures: [
'BigECommerce.rollingCountYTD',
],
timeDimensions: [{
dimension: 'BigECommerce.orderDate',
granularity: 'month',
dateRange: ['2020-01-01', '2020-12-31'],
}, {
dimension: 'BigECommerce.orderDate',
granularity: 'week',
dateRange: ['2020-01-01', '2020-12-31'],
}],
order: [
['BigECommerce.orderDate', 'asc'],
],
}
```
Note the `order` part.
Before now - the sorting will be done by 1st td with `month` granularity. But resulting rows still could jump around because week timestamps inside one month are not guaranteed to be ordered. Now column with …

feat(schema-compiler): Allow to specify td with granularity in REST API query order section

---

packages/cubejs-duckdb-driver/package.json
yarn.lock

Bumped DuckDB version to 1.3.1 to support DuckLake
**Check List**

chore(deps): bump DuckDB from 1.2.1 to 1.3.1

---

rust/cubesql/cubesql/src/compile/engine/df/optimizers/filter_split_meta.rs
rust/cubesql/cubesql/src/compile/test/test_user_change.rs

**Check List**
This PR extends `FilterMetaSplit` optimizer to push down `__user` filter as much as possible. This solves an issue with SQL push down queries with joins and multiple `__user` filters being part of the generated SQL.

fix(cubesql): Push down `__user` meta filter further

---

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
rust/cubesql/cubesql/src/compile/engine/df/wrapper.rs
rust/cubesql/cubesql/src/compile/test/test_wrapper.rs

fix(cubejs-schema-compiler): Stay unchanged `__user` / `__cubejoinfield` names in aliasing

---

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-schema-compiler/src/adapter/BigqueryQuery.ts
packages/cubejs-testing-drivers/fixtures/athena.json
packages/cubejs-testing-drivers/fixtures/clickhouse.json
packages/cubejs-testing-drivers/src/tests/testQueries.ts
packages/cubejs-testing-drivers/test/__snapshots__/bigquery-export-bucket-gcs-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/databricks-jdbc-export-bucket-azure-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/databricks-jdbc-export-bucket-azure-prefix-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/databricks-jdbc-export-bucket-gcs-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/databricks-jdbc-export-bucket-gcs-prefix-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/databricks-jdbc-export-bucket-s3-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/databricks-jdbc-export-bucket-s3-prefix-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/databricks-jdbc-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/mssql-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/mysql-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/postgres-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/redshift-export-bucket-s3-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/redshift-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/snowflake-encrypted-pk-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/snowflake-export-bucket-azure-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/snowflake-export-bucket-azure-prefix-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/snowflake-export-bucket-azure-via-storage-integration-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/snowflake-export-bucket-gcs-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/snowflake-export-bucket-gcs-prefix-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/snowflake-export-bucket-s3-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/snowflake-export-bucket-s3-prefix-full.test.ts.snap
packages/cubejs-testing-drivers/test/__snapshots__/snowflake-full.test.ts.snap
rust/cubesqlplanner/cubesqlplanner/src/planner/filter/base_filter.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/filter/base_segment.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/sql_templates/plan.rs

This fixes queries with filters for BigQuery, when casting is needed  (like cast to FLOAT64 for numbers).
**Check List**

fix(tesseracrt): Fix filter params casting for BigQuery dialect

---

rust/cubestore/cubestore/src/cachestore/cache_eviction_manager.rs
rust/cubestore/cubestore/src/cachestore/compaction.rs
rust/cubestore/cubestore/src/metastore/rocks_store.rs
rust/cubestore/cubestore/src/metastore/rocks_table.rs

queue_add queues:1, size:64 kb/512:
time:  [644.70 ms 648.88 ms 653.45 ms] -> [547.18 ms 558.58 ms 571.78 ms]
queue_add queues:1, size:256 kb/512
time:  [334.21 ms 336.78 ms 339.56 ms] -> [286.95 ms 291.70 ms 297.12 ms]
queue_add queues:1, size:512 kb/512
time:   [363.73 ms 367.60 ms 371.73 ms] -> [304.42 ms 310.45 ms 317.43 ms]
```
queue_add queues:1, size:64 kb/512
time:   [644.70 ms 648.88 ms 653.45 ms]
change: [-4.3588% -2.6419% -0.9566%] (p = 0.00 < 0.05)
Change within noise threshold.
Found 4 outliers among 100 measurements (4.00%)
3 (3.00%) high mild
1 (1.00%) high severe
Benchmarking queue_add queues:1, size:256 kb/512: Warming up for 3.0000 s
queue_add queues:1, size:256 kb/512
time:   [334.21 ms 336.78 ms 339.56 ms]
change: [-0.7991% +0.4350% +1.7476%] (p = 0.50 > 0.05)
No …
```

feat(cubestore): Rockstore - optimize index scanning

---

rust/cubesql/cubesql/src/compile/engine/udf/common.rs
rust/cubesql/cubesql/src/compile/query_engine.rs
rust/cubesql/cubesql/src/compile/test/snapshots/cubesql__compile__test__test_udfs__age.snap
rust/cubesql/cubesql/src/compile/test/test_udfs.rs

**Check List**
This PR adds support for executing `AGE` function. Related test is included.

feat(cubesql): Support `AGE` function

---

rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs

This PR allows filters to be pushed down with `DATE_PART('year')` by pushing it as `inDateRange`. Now, such queries will be accelerated with pre-aggregations. 
```
ovr=> explain select count(*), date_part('YEAR', created) as year from orders where date_part('YEAR', created) = '2022' group by year;
plan_type   |                                                                                               plan                                                                                                
---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
logical_plan  | Projection: #COUNT(UInt8(1)), …
```

feat(cubesql): Filter push down for date_part('year', ?col)  = ?literal

---

packages/cubejs-schema-compiler/src/compiler/CubeValidator.ts
packages/cubejs-schema-compiler/test/integration/postgres/calendars.test.ts
packages/cubejs-schema-compiler/test/unit/__snapshots__/schema.test.ts.snap
packages/cubejs-schema-compiler/test/unit/fixtures/custom_calendar.yml
rust/cubesqlplanner/cubesqlplanner/src/physical_plan_builder/builder.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/planners/multi_stage/applied_state.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/planners/multi_stage/mod.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/planners/multi_stage/time_shift_state.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/sql_evaluator/sql_nodes/calendar_time_shift.rs

- **throw error if named timeshift not found**
- **feat(tesseract): Allow named calendar timeshifts for common intervals**
- **add tests**
**Check List**

feat(tesseract): Allow named calendar timeshifts for common intervals

---

packages/cubejs-api-gateway/src/sql-server.ts

When using cube.py it’s fundamental to see errors and even better the stack trace of errors generated from python code, currently the logs doesn’t show any errors generated from python check_sql_auth.
This PR propagates such errors to the log.
Imaging this cube.py config:
```py
@config('check_sql_auth')
def check_sql_auth(query: dict, username: str, password: str) -> dict:
raise Exception('You should be able to see this error in the logs')
```
And let's try to connect to Cube via psql:
```sh
❯ psql -h 127.0.0.1 -p 15432 -U cube
psql: error: connection to server at "127.0.0.1", port 15432 failed: FATAL:  password authentication failed for user "cube"
```
And here is what we now can see in logs:
```
cubejs-server
🔥 Cube Store (1.3.19) is assigned to 3030 port.
🔓 Authentication checks are …
```

fix(cubesql): Propagate errors from SqlAuthService to the user

---

.github/workflows/rust-cubesql.yml
rust/cubesql/cubesql/src/compile/rewrite/rules/order.rs

**Check List**
This PR workarounds an issue with recently introduced Limit-Sort push down Projection rules, throwing an error when sort column has been replaced with a complex expression and SQL push down is involved. This is a bug in SQL push down generation, so for now only expressions that resolve to columns are being pushed down.

fix(cubesql): Fix sort push down projection on complex expressions

---

packages/cubejs-backend-native/src/node_export.rs
packages/cubejs-backend-native/test/sql.test.ts
packages/cubejs-testing/test/smoke-cubesql.test.ts

fix: Send column schema and empty data for empty /cubesql result sets instead of empty response

---

packages/cubejs-backend-shared/src/env.ts
packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-schema-compiler/src/adapter/PreAggregations.ts
packages/cubejs-schema-compiler/test/integration/postgres/pre-aggregations.test.ts
rust/cubesqlplanner/cubesqlplanner/src/logical_plan/optimizers/pre_aggregation/compiled_pre_aggregation.rs
rust/cubesqlplanner/cubesqlplanner/src/logical_plan/optimizers/pre_aggregation/pre_aggregations_compiler.rs
rust/cubesqlplanner/cubesqlplanner/src/logical_plan/pre_aggregation.rs
rust/cubesqlplanner/cubesqlplanner/src/physical_plan_builder/builder.rs
rust/cubesqlplanner/cubesqlplanner/src/plan/builder/select.rs
rust/cubesqlplanner/cubesqlplanner/src/plan/from.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/query_tools.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/sql_templates/plan.rs

feat(tesseract): Lambda rollup support

---

packages/cubejs-base-driver/src/queue-driver.interface.ts
packages/cubejs-query-orchestrator/src/orchestrator/QueryQueue.js

Cube Store allows updating the heartbeat by path or QueueId. Using QueueId provides better performance and fixes possible concurrency issues, such as slippage

fix(query-orchestrator): QueryQueue - update heartbeat by QueueId

---

docs/components/common/Footer/Footer.tsx

Replaced the footer link to point to /consulting/consulting-partners and updated the link label from "Cube Partner Network" to "Consulting Partners".

feat(partners): rename link

---

packages/cubejs-backend-shared/src/type-helpers.ts
packages/cubejs-base-driver/src/queue-driver.interface.ts
packages/cubejs-query-orchestrator/CLAUDE.md
packages/cubejs-query-orchestrator/src/orchestrator/PreAggregationLoader.ts
packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts
packages/cubejs-query-orchestrator/src/orchestrator/QueryCache.ts
packages/cubejs-query-orchestrator/src/orchestrator/QueryOrchestrator.ts
packages/cubejs-query-orchestrator/src/orchestrator/QueryQueue.ts
packages/cubejs-query-orchestrator/test/benchmarks/QueueBench.abstract.ts
packages/cubejs-query-orchestrator/test/unit/PreAggregations.test.js
packages/cubejs-query-orchestrator/test/unit/QueryCache.abstract.ts
packages/cubejs-query-orchestrator/test/unit/QueryCache.test.ts
packages/cubejs-query-orchestrator/test/unit/QueryQueue.abstract.ts
packages/cubejs-query-orchestrator/test/unit/QueryQueue.test.ts
packages/cubejs-server-core/src/core/RefreshScheduler.ts

refactor(query-orchestrator): Migrate QueryQueue to TypeScript

---

packages/cubejs-prestodb-driver/src/PrestoDriver.ts

https://github.com/tagomoris/presto-client-node/blob/master/lib/presto-client/index.js#L270
By default, it's specified as 60 seconds.

fix(prestodb/trino-driver): Specify correct timeouts for query execution

---

packages/cubejs-backend-shared/src/env.ts
packages/cubejs-query-orchestrator/src/orchestrator/PreAggregations.ts
packages/cubejs-query-orchestrator/src/orchestrator/QueryCache.ts

We use both flags: used and touch. We have already had LRU cache for a long time with the touch flag to reduce the number of updates in the Cache Store, but we didn't do it for the used. 
This leads to a situation where, for a schema with 100 pre-aggs, we will do 200 cache sets per 1 minute because the default refresh interval is set to 30 seconds.

feat(query-ochestrator): Reduce number of cache set for used flag

---

rust/cubestore/CLAUDE.md
rust/cubestore/Cargo.lock
rust/cubestore/cubestore/Cargo.toml
rust/cubestore/cubestore/src/queryplanner/info_schema/info_schema_columns.rs
rust/cubestore/cubestore/src/queryplanner/info_schema/info_schema_schemata.rs
rust/cubestore/cubestore/src/queryplanner/info_schema/info_schema_tables.rs
rust/cubestore/cubestore/src/queryplanner/info_schema/system_cache.rs
rust/cubestore/cubestore/src/queryplanner/info_schema/system_chunks.rs
rust/cubestore/cubestore/src/queryplanner/info_schema/system_indexes.rs
rust/cubestore/cubestore/src/queryplanner/info_schema/system_jobs.rs
rust/cubestore/cubestore/src/queryplanner/info_schema/system_partitions.rs
rust/cubestore/cubestore/src/queryplanner/info_schema/system_queue.rs
rust/cubestore/cubestore/src/queryplanner/info_schema/system_queue_results.rs
rust/cubestore/cubestore/src/queryplanner/info_schema/system_replay_handles.rs
rust/cubestore/cubestore/src/queryplanner/info_schema/system_snapshots.rs
rust/cubestore/cubestore/src/queryplanner/info_schema/system_tables.rs

- Replace intermediate Vec allocations with direct iterator consumption
- Use from_iter/from_iter_values instead of collect() followed by from()
- Remove unnecessary .as_str() conversions where &String is sufficient
- Simplify Option<String> handling with .as_deref() instead of .as_ref().map()
This optimization eliminates ~78 unnecessary heap allocations across all info schema table implementations, improving performance, especially with large datasets.

perf(cubestore): Reduce allocations in info schema tables

---

packages/cubejs-client-core/src/ResultSet.ts
packages/cubejs-client-core/test/ResultSet.test.ts

**Check List**
Back in May when release 1.3.6 came out, [the client package was migrated to typescript](https://github.com/cube-js/cube/pull/9562). While trying to upgrade from previous versions to the newer releases, i ended up seeing discrepancies when running tests against some cube models. 
After some digging, it seems like the default value was added during the migration process. The previous behaviour being that if you are joining on a table that does not have a matching row for your model, the requested columns were `null` and not `""`.
I'm wondering if that behaviour is expected, and if so why?

fix(client-core): Remove default value in table pivot

---

packages/cubejs-schema-compiler/package.json
packages/cubejs-schema-compiler/src/compiler/CubeEvaluator.ts
packages/cubejs-schema-compiler/src/compiler/CubeSymbols.ts
packages/cubejs-schema-compiler/src/compiler/CubeValidator.ts
packages/cubejs-schema-compiler/src/compiler/JoinGraph.ts
packages/cubejs-schema-compiler/src/compiler/YamlCompiler.ts
packages/cubejs-schema-compiler/src/compiler/transpilers/CubePropContextTranspiler.ts
packages/cubejs-schema-compiler/test/unit/__snapshots__/schema.test.ts.snap
packages/cubejs-schema-compiler/test/unit/schema.test.ts
yarn.lock

- **more types in CubeSymbols**
- **change joins schema in Validator**
- **specify type for accessPolicy**
- **make prepareJoins() aware of arrays**
- **make joins in CubeSymbols / CubeEvaluator as array instead of hashmap**
- **update JoinGraph to treat joins as array instead of hashmap**
- **fix CubePropContextTranspiler to convert joins hashmap into array**
- **add @types/js-yaml**
- **make YamlCompiler aware of joins as array**
- **fix/update snapshots for schema tests**
- **fix transform yaml joins**
- **add schema tests for joins as array/object**
**Check List**

chore(schema-compiler): Make cube joins to be an array instead of hashmap

---

packages/cubejs-api-gateway/src/helpers/transformMetaExtended.ts
packages/cubejs-api-gateway/test/helpers/transformMetaExtended.test.ts

After PR #9800, joins are stored as arrays instead of objects in the schema compiler. The transformJoins function in the API gateway was still using Object.entries() which, when applied to arrays, returns numeric indices as keys instead of actual join names.
This fix:
- Checks if joins is an array and preserves the name property
- Maintains backward compatibility with object format
- Adds test coverage for both array and object formats
Fixes the issue where join names appear as "0", "1", "2" instead of their actual names in the /meta?extended endpoint response.
**Check List**

fix(api-gateway): Handle array format for joins in /meta?extended endpoint

---

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
rust/cubesql/cubesql/src/compile/engine/df/wrapper.rs
rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/members.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/wrapper/aggregate.rs

**Check List**
This PR avoids pushing down `COUNT(*)` to CubeScan with joined cubes. This allows correct `COUNT` calculation of queries with joined cubes like this:
```
SELECT COUNT(*)
FROM (
SELECT c1.m1, c2.m2
FROM c1
LEFT JOIN c2 ON c1.__cubeJoinField = c2.__cubeJoinField
)
```
For grouped CubeScan queries, post-processing is the default method of calculating `COUNT`. For other cases, including ungrouped queries, SQL push down is involved.

feat(cubesql): Avoid `COUNT(*)` pushdown to joined cubes

---

packages/cubejs-playground/package.json
packages/cubejs-playground/src/QueryBuilderV2/hooks/query-builder.ts

Fixes the issue when all members in playground are marked "missing" on any update of the metadata or a refresh.

fix(cubejs-playground): meta update propagation

---

.github/actions/smoke.sh
.github/workflows/push.yml

Have to disable Vertica tests as vertica-ce docker images are not available.
see https://github.com/vertica/vertica-containers/issues/64

chore(ci): Disable Vertica tests until vertica docker image will be available

---

packages/cubejs-schema-compiler/src/compiler/DataSchemaCompiler.ts
packages/cubejs-schema-compiler/src/compiler/PrepareCompiler.ts
packages/cubejs-schema-compiler/src/compiler/YamlCompiler.ts
packages/cubejs-schema-compiler/src/compiler/transpilers/IIFETranspiler.ts
packages/cubejs-schema-compiler/src/compiler/transpilers/ImportExportTranspiler.ts
packages/cubejs-schema-compiler/src/compiler/transpilers/index.ts
packages/cubejs-schema-compiler/src/compiler/transpilers/transpiler_worker.ts
packages/cubejs-schema-compiler/test/unit/transpilers.test.ts

This PR brings more memory improvements into the model compilation flow.
Compare the memory usage for 1-time pass of compiling 300 js model files:
```sh
Before:
Memory footprint { rss: '431 MB', heapUsed: '289 MB', heapTotal: '320 MB' }
After this change:
Memory footprint { rss: '254 MB', heapUsed: '120 MB', heapTotal: '154 MB' }
```
And for a 30-times pass of compilation:
```sh
Before:
Memory footprint { rss: '2389 MB', heapUsed: '1937 MB', heapTotal: '2004 MB' }
After this change:
Memory footprint { rss: '895 MB', heapUsed: '523 MB', heapTotal: '565 MB' }
```
**Check List**

perf(schema-compiler): Reduce JS compilation memory usage 3x-5x times.

---

packages/cubejs-backend-native/Cargo.lock
rust/cubenativeutils/Cargo.lock
rust/cubesql/Cargo.lock
rust/cubesql/cubesql/Cargo.toml
rust/cubesqlplanner/Cargo.lock

Compiling brotli, zstd, etc. compression libraries takes a lot of time. We don't use parquet files at all in SQL API, so let's disable them for now to speed up release builds.
It saves ~10 seconds on my M3 Max machine in release builds; it should save ~1 minute on a 4-CPU machine used on CI.
More importantly, it reduces the size of the cache.

chore(cubesql): Disable parquet compression (not used, speedup build)

---

rust/cubesql/cubesql/src/compile/query_engine.rs

**Check List**
This PR adds `SQL API Plan Rewrite` and `SQL API Plan Rewrite Success` event reporting, along with `duration` property for the latter.

feat(cubesql): Report rewrite start/success events

---

.github/workflows/publish.yml
.github/workflows/push.yml
.github/workflows/rust-cubestore-master.yml
.github/workflows/rust-cubestore.yml
rust/cubestore/cubestore/src/queryplanner/planning.rs
rust/cubestore/cubestore/src/queryplanner/query_executor.rs

fix(cubestore): Allowing window functions in cluster send planning

---

packages/cubejs-schema-compiler/src/adapter/PrestodbQuery.ts
rust/cubesql/cubesql/src/compile/mod.rs

**Check List**
This PR fixes SQL pushdown `TRUNC` function template for PrestoDB and derivatives to produce `TRUNCATE` function instead of `TRUNC`. Related test is included.

fix(cubesql): Fix SQL pushdown `TRUNC` template for Presto

---

rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/cost.rs

**Check List**
This PR fixes an issue with e-graph top-down extractor which would avoid picking nodes with best costs in some complex cases where recursive nodes are involved by introducing a two-pass extractor when deep recursion is involved.

fix(cubesql): Correctly calculate eclass cost for recursive nodes

---

rust/cubesql/cubesql/src/compile/engine/df/wrapper.rs
rust/cubesql/cubesql/src/transport/service.rs

**Check List**
This PR fixes an issue with SQL push down where window expressions weren't passed to the SELECT.

fix(cubesql): Pass window expressions in SQL push down

---

docs/pages/product/deployment/cloud/byoc/aws/privatelink.mdx
docs/pages/product/deployment/cloud/infrastructure.mdx

docs: Explanation of the Cube Cloud Region

---

rust/cubesql/cubesql/src/compile/date_parser.rs

**Check List**
This PR updates the `parse_date_str` shared function, adding the value that couldn't be parsed to the error message. This will aid in debugging date/time values that could not be parsed.

feat(cubesql): Print value of the date/time that couldn't be parsed

---

packages/cubejs-schema-compiler/src/compiler/CubeSymbols.ts
packages/cubejs-schema-compiler/src/compiler/DataSchemaCompiler.ts
packages/cubejs-schema-compiler/src/compiler/PrepareCompiler.ts
packages/cubejs-schema-compiler/src/compiler/YamlCompiler.ts
packages/cubejs-schema-compiler/src/compiler/transpilers/transpiler_worker.ts
packages/cubejs-schema-compiler/test/integration/postgres/dataschema-compiler.test.ts

This is the second PR in the series to reach the YAML compilation speed-up.
It is based on and incorporates https://github.com/cube-js/cube/pull/9926. For ease of review, it's targeted parent branch instead of master.
This brings YAML transpilation to worker threads, thus unblocking the main event loop and utilizing more cores.
**Check List**

perf(schema-compiler): YAML transpilation in worker threads

---

packages/cubejs-client-core/src/ResultSet.ts
packages/cubejs-client-core/src/time.ts
packages/cubejs-client-core/test/granularity.test.ts

This PR fixes time series generation for some cases like 
`['2019-01-08T01:45:25.342', '2019-01-08T07:35:58.399'] with hour granularity` - previously, there will be no `'2019-01-08T07:00:00'` entity generated. Now it's fixed.
**Check List**

fix(client-core): Fix time series generation

---

packages/cubejs-backend-native/Cargo.lock
rust/cubesql/Cargo.lock
rust/cubesql/cubesql/Cargo.toml
rust/cubesql/cubesql/src/compile/mod.rs

**Check List**
This PR bumps cube-js/arrow-datafusion@6ac1062, fixing an issue with initial logical plan referencing non-existing aggregate expressions in `Sort` (`ORDER BY`). Related test is included.

fix(cubesql): Add missing aggregate expressions for `ORDER BY` clause

---

rust/cubesql/cubesql/src/compile/mod.rs
rust/cubesql/cubesql/src/compile/rewrite/rules/filters.rs

**Check List**
This PR matches a pair of EXTRACT filters generated by Tableau as `inDateRange` filter.
Example predicate:
```
CAST(TRUNC(EXTRACT(MONTH FROM registration_date)) AS INTEGER) = 3
AND CAST(TRUNC(EXTRACT(YEAR FROM registration_date)) AS INTEGER) = 2024
```

feat(cubesql): Match Tableau year-month extract filter pair as `inDateRange`

---

packages/cubejs-athena-driver/src/AthenaDriver.ts
packages/cubejs-base-driver/src/driver.interface.ts
packages/cubejs-cubestore-driver/src/CubeStoreDriver.ts
rust/cubestore/cubestore-sql-tests/src/tests.rs
rust/cubestore/cubestore/src/import/mod.rs
rust/cubestore/cubestore/src/sql/mod.rs

fix(cubestore): Disable quoting in csv parser for Athena

---

packages/cubejs-schema-compiler/src/adapter/BaseQuery.js
packages/cubejs-schema-compiler/src/adapter/PreAggregations.ts
rust/cubesqlplanner/cubesqlplanner/src/cube_bridge/base_query_options.rs
rust/cubesqlplanner/cubesqlplanner/src/logical_plan/optimizers/pre_aggregation/optimizer.rs
rust/cubesqlplanner/cubesqlplanner/src/logical_plan/optimizers/pre_aggregation/pre_aggregations_compiler.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/base_query.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/planners/dimension_subquery_planner.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/planners/multi_stage/member_query_planner.rs
rust/cubesqlplanner/cubesqlplanner/src/planner/query_properties.rs

**Check List**
This PR resolves an issue with SQL push down queries having pre-aggregation description which let it bypass rollup-only mode and get registered as a pre-aggregated query.

fix(schema-compiler): Do not collect disabled external pre-aggregations

---

packages/cubejs-testing-drivers/src/helpers/runEnvironment.ts

An attempt to fix occasional errors during drivers tests

chore(ci): use Wait.forListeningPorts() in drivers tests

---

packages/cubejs-schema-compiler/src/compiler/CompileError.ts
packages/cubejs-schema-compiler/src/compiler/CubeValidator.ts
packages/cubejs-schema-compiler/src/compiler/DataSchemaCompiler.ts
packages/cubejs-schema-compiler/src/compiler/ErrorReporter.ts
packages/cubejs-schema-compiler/test/unit/__snapshots__/error-reporter.test.ts.snap
packages/cubejs-schema-compiler/test/unit/error-reporter.test.ts

This PR updates ErrorReporter to fancy print compile errors grouped by files.
Something like this:
```sh
Compile errors:
schema/custom.js Errors:
Parse error
schema/orders.js Errors:
Missing required field
schema/products.js Errors:
Validation error
schema/users.js Errors:
Syntax Error: Invalid measure definition
2 |   sql: \`SELECT * FROM users\`,
3 |   measures: {
> 4 |     count: {
|    ^^^^^ Invalid measure definition
5 |       type: 'count'
6 |     }
7 |   }
```
**Check List**

feat(schema-compiler): Pretty print compile errors grouped by files

---

packages/cubejs-backend-shared/jest.config.js
packages/cubejs-backend-shared/package.json
packages/cubejs-base-driver/jest.config.js
packages/cubejs-base-driver/package.json
packages/cubejs-base-driver/tsconfig.jest.json
packages/cubejs-query-orchestrator/jest.config.js
packages/cubejs-query-orchestrator/package.json
packages/cubejs-query-orchestrator/tsconfig.jest.json

- **chore(ci): Switch backend-shared unit tests to ts-jest**
- **chore(ci): Switch query-orchestrator unit tests to ts-jest**
- **chore(ci): Switch base-driver unit tests to ts-jest**
Supersedes https://github.com/cube-js/cube/pull/3911
Closes https://github.com/cube-js/cube/pull/3911

chore(ci): Switch few packages unit tests to ts-jest
